# ПЕРВАЯ КНИГА {-}

## ЧАСТЬ первая. ПЯТИЧАСОВОЙ СКОРЫЙ {-}

### 1 {-}

Шли и шли и пели «Вечную память», и когда останавливались, казалось, что её по залаженному продолжают петь ноги, лошади, дуновения ветра.<br/> Прохожие пропускали шествие, считали венки, крестились.<br/> Любопытные входили в процессию, спрашивали: «Кого хоронят?» Им отвечали: «Живаго». «Вот оно что. Тогда понятно». — «Да не его. Её». — «Все равно. Царствие небесное. Похороны богатые».<br/> Замелькали последние минуты, считанные, бесповоротные.<br/> «Господня земля и исполнение ея, вселенная и вси живущие на ней». Священник крестящим движением бросил горсть земли на Марью Николаевну. Запели «Со духи праведных». Началась страшная гонка. Гроб закрыли, заколотили, стали опускать.<br/> Отбарабанил дождь комьев, которыми торопливо в четыре лопаты забросали могилу. На ней вырос холмик. На него взошел десятилетний мальчик.<br/> Только в состоянии отупения и бесчувственности, обыкновенно наступающих к концу больших похорон, могло показаться, что мальчик хочет сказать слово на материнской могиле.<br/> Он поднял голову и окинул с возвышения осенние пустыри и главы монастыря отсутствующим взором. Его курносое лицо исказилось. Шея его вытянулась. Если бы таким движением поднял голову волчонок, было бы ясно, что он сейчас завоет. Закрыв лицо руками, мальчик зарыдал. Летевшее навстречу облако стало хлестать его по рукам и лицу мокрыми плетьми холодного ливня.<br/> К могиле прошел человек в черном, со сборками на узких облегающих рукавах. Это был брат покойной и дядя плакавшего мальчика, расстриженный по собственному прошению священник Николай Николаевич Веденяпин. Он подошел к мальчику и увел его с кладбища.

