### 2 {-}

Они ночевали в одном из монастырских покоев, который отвели дяде по старому знакомству. Был канун Покрова. На другой день они с дядей должны были уехать далеко на юг, в один из губернских городов Поволжья, где отец Николай служил в издательстве, выпускавшем прогрессивную газету края. Билеты на поезд были куплены, вещи увязаны и стояли в келье. С вокзала по соседству ветер приносил плаксивые пересвистывания маневрировавших вдали паровозов.<br/> К вечеру сильно похолодало. Два окна на уровне земли выходили на уголок невзрачного огорода, обсаженного кустами желтой акации, на мерзлые лужи проезжей дороги и на тот конец кладбища, где днем похоронили Марию Николаевну. Огород пустовал, кроме нескольких муаровых гряд посиневшей от холода капусты. Когда налетал ветер, кусты облетелой акации метались, как бесноватые, и ложились на дорогу.<br/> Ночью Юру разбудил стук в окно. Темная келья была сверхъестественно озарена белым порхающим светом. Юра в одной рубашке подбежал к окну и прижался лицом к холодному стеклу.<br/> За окном не было ни дороги, ни кладбища, ни огорода. На дворе бушевала вьюга, воздух дымился снегом. Можно было подумать, будто буря заметила Юру и, сознавая, как она страшна, наслаждается производимым на него впечатлением. Она свистела и завывала и всеми способами старалась привлечь Юрино внимание. С неба оборот за оборотом бесконечными мотками падала на землю белая ткань, обвивая её погребальными пеленами. Вьюга была одна на свете, ничто с ней не соперничало.<br/> Первым движением Юры, когда он слез с подоконника, было желание одеться и бежать на улицу, чтобы что-то предпринять.<br/> То его пугало, что монастырскую капусту занесет и её не откопают, то что в поле заметет маму, и она бессильна будет оказать сопротивление тому, что уйдет еще глубже и дальше от него в землю.<br/> Дело опять кончилось слезами. Проснулся дядя, говорил ему о Христе и утешал его, а потом зевал, подходил к окну и задумывался. Они начали одеваться. Стало светать.

