### 3 {-}

Пока жива была мать, Юра не знал, что отец давно бросил их, ездит по разным городам Сибири и заграницы, кутит и распутничает, и что он давно просадил и развеял по ветру их миллионное состояние. Юре всегда говорили, что он то в Петербурге, то на какой-нибудь ярмарке, чаще всего на Ирбитской.<br/> А потом у матери, всегда болевшей, открылась чахотка. Она стала ездить лечиться на юг Франции и в Северную Италию, куда Юра её два раза сопровождал. Так, в беспорядке и среди постоянных загадок прошла детская жизнь Юры, часто на руках у чужих, которые все время менялись. Он привык к этим переменам, и в обстановке вечной нескладицы отсутствие отца не удивляло его.<br/> Маленьким мальчиком он застал еще то время, когда именем, которое он носил, называлось множество саморазличнейших вещей.<br/> Была мануфактура Живаго, банк Живаго, дома Живаго, способ завязывания и закалывания галстука булавкою Живаго, даже какой-то сладкий пирог круглой формы, вроде ромовой бабы, под названием Живаго, и одно время в Москве можно было крикнуть извозчику «к Живаго!», совершенно как «к черту на кулички!», и он уносил вас на санках в тридесятое царство, в тридевятое государство. Тихий парк обступал вас. На свисающие ветви елей, осыпая с них иней, садились вороны. Разносилось их карканье, раскатистое, как треск древесного сука. С новостроек за просекой через дорогу перебегали породистые собаки. Там зажигали огни. Спускался вечер. Вдруг все это разлетелось. Они обеднели.

