### 4 {-}

Летом тысяча девятьсот третьего года на тарантасе парой Юра с дядей ехали по полям в Дуплянку, имение шелкопрядильного фабриканта и большого покровителя искусств Кологривова, к педагогу и популяризатору полезных знаний Ивану Ивановичу Воскобойникову.<br/> Была Казанская, разгар жатвы. По причине обеденного времени или по случаю праздника в полях не попадалось ни души. Солнце палило недожатые полосы, как полуобритые арестантские затылки.<br/> Над полями кружились птицы. Склонив колосья, пшеница тянулась в струнку среди совершенного безветрия или высилась в крестцах далеко от дороги, где при долгом вглядывании принимала вид движущихся фигур, словно это ходили по краю горизонта землемеры и что-то записывали.<br/> — А эти, — спрашивал Николай Николаевич Павла, чернорабочего и сторожа из книгоиздательства, сидевшего на козлах боком, сутуло и перекинув нога за ногу, в знак того, что он не заправский кучер и правит не по призванию, — а это как же, помещиковы или крестьянские?<br/> — Энти господсти, — отвечал Павел и закуривал, — а вот эфти, — отвозившись с огнем и затянувшись, тыкал он после долгой паузы концом кнутовища в другую сторону, — эфти свои.<br/> Ай заснули? — то и дело прикрикивал он на лошадей, на хвосты и крупы которых он все время косился, как машинист на манометры.<br/> Но лошади везли, как все лошади на свете, то есть коренник бежал с прирожденной прямотой бесхитростной натуры, а пристяжная казалась непонимающему отъявленной бездельницей, которая только и знала, что, выгнувшись лебедью, отплясывала вприсядку под бренчание бубенчиков, которое сама своими скачками подымала.<br/> Николай Николаевич вез Воскобойникову корректуру его книжки по земельному вопросу, которую ввиду усилившегося цензурного нажима издательство просило пересмотреть.<br/> — Шалит народ в уезде, — говорил Николай Николаевич. — В Паньковской волости купца зарезали, у земского сожгли конный завод. Ты как об этом думаешь? Что у вас говорят в деревне?<br/> Но оказывалось, что Павел смотрит на вещи еще мрачнее, чем даже цензор, умерявший аграрные страсти Воскобойникова.<br/> — Да что говорят? Распустили народ. Баловство, говорят. С нашим братом нешто возможно? Мужику дай волю, так ведь у нас друг дружку передавят, истинный Господь. Ай заснули?<br/> Это была вторая поездка дяди и племянника в Дуплянку. Юра думал, что он запомнил дорогу, и всякий раз, как поля разбегались вширь и их тоненькой каемкой охватывали спереди и сзади леса, Юре казалось, что он узнает то место, с которого дорога должна повернуть вправо, а с поворота показаться и через минуту скрыться десятиверстная Кологривовская панорама с блещущей вдали рекой и пробегающей за ней железной дорогой. Но он все обманывался. Поля сменялись полями. Их вновь и вновь охватывали леса. Смена этих просторов настраивала на широкий лад. Хотелось мечтать и думать о будущем.<br/> Ни одна из книг, прославивших впоследствии Николая Николаевича, не была еще написана. Но мысли его уже определились. Он не знал, как близко его время.<br/> Скоро среди представителей тогдашней литературы, профессоров университета и философов революции должен был появиться этот человек, который думал на все их темы и у которого, кроме терминологии, не было с ними ничего общего.<br/> Все они скопом держались какой-нибудь догмы и довольствовались словами и видимостями, а отец Николай был священник, прошедший толстовство и революцию и шедший все время дальше. Он жаждал мысли, окрыленно-вещественной, которая прочерчивала бы нелицемерно различимый путь в своем движении и что-то меняла в свете к лучшему и которая даже ребенку и невежде была бы заметна, как вспышка молнии или след прокатившегося грома. Он жаждал нового.<br/> Юре хорошо было с дядей. Он был похож на маму. Подобно ей он был человеком свободным, лишенным предубеждения против чего бы то ни было непривычного. Как у нее, у него было дворянское чувство равенства со всем живущим. Он так же, как она, понимал все с первого взгляда и умел выражать мысли в той форме, в какой они приходят в голову в первую минуту, пока они живы и не обессмыслятся.<br/> Юра был рад, что дядя взял его в Дуплянку. Там было очень красиво, и живописность места тоже напоминала маму, которая любила природу и часто брала Юру с собой на прогулки. Кроме того Юре было приятно, что он опять встретится с Никой Дудоровым, гимназистом, жившим у Воскобойникова, который наверное презирал его, потому что был года на два старше его, и который, здороваясь, с силой дергал руку книзу и так низко наклонял голову, что волосы падали ему на лоб, закрывая лицо до половины.

