### 5 {-}

— Жизненным нервом проблемы пауперизма, — читал Николай Николаевич по исправленной рукописи.<br/> — Я думаю, лучше сказать — существом, — говорил Иван Иванович и вносил в корректуру требующееся исправление.<br/> Они занимались в полутьме стеклянной террасы. Глаз различал валявшиеся в беспорядке лейки и садовые инструменты. На спинку поломанного стула был наброшен дождевой плащ. В углу стояли болотные сапоги с присохшей грязью и отвисающими до полу голенищами.<br/> — Между тем статистика смертей и рождений показывает, — диктовал Николай Николаевич.<br/> — Надо вставить, за отчетный год, — говорил Иван Иванович и записывал.<br/> Террасу слегка проскваживало. На листах брошюры лежали куски гранита, чтобы они не разлетелись.<br/> Когда они кончили, Николай Николаевич заторопился домой.<br/> — Гроза надвигается. Надо собираться.<br/> — И не думайте. Не пущу. Сейчас будем чай пить.<br/> — Мне к вечеру надо обязательно в город.<br/> — Ничего не поможет. Слышать не хочу.<br/> Из палисадника тянуло самоварной гарью, заглушавшей запах табака и гелиотропа. Туда проносили из флигеля каймак, ягоды и ватрушки. Вдруг пришло сведенье, что Павел отправился купаться и повел купать на реку лошадей. Николаю Николаевичу пришлось покориться.<br/> — Пойдемте на обрыв, посидим на лавочке, пока накроют к чаю, — предложил Иван Иванович.<br/> Иван Иванович на правах приятельства занимал у богача Кологривова две комнаты во флигеле управляющего. Этот домик с примыкающим к нему палисадником находился в черной, запущенной части парка со старой полукруглою аллеей въезда. Аллея густо заросла травою. По ней теперь не было движения, и только возили землю и строительный мусор в овраг, служивший местом сухих свалок. Человек передовых взглядов и миллионер, сочувствовавший революции, сам Кологривов с женою находился в настоящее время за границей. В имении жили только его дочери Надя и Липа с воспитательницей и небольшим штатом прислуги.<br/> Ото всего парка с его прудами, лужайками и барским домом садик управляющего был отгорожен густой живой изгородью из черной калины. Иван Иванович и Николай Николаевич обходили эту заросль снаружи, и по мере того как они шли, перед ними равными стайками на равных промежутках вылетали воробьи, которыми кишела калина. Это наполняло её ровным шумом, точно перед Иваном Ивановичем и Николаем Николаевичем вдоль изгороди текла вода по трубе.<br/> Они прошли мимо оранжереи, квартиры садовника и каменных развалин неизвестного назначения. У них зашел разговор о новых молодых силах в науке и литературе.<br/> — Попадаются люди с талантом, — говорил Николай Николаевич. — Но сейчас очень в ходу разные кружки и объединения. Всякая стадность — прибежище неодаренности, все равно верность ли это Соловьеву, или Канту, или Марксу. Истину ищут только одиночки и порывают со всеми, кто любит её недостаточно. Есть ли что-нибудь на свете, что заслуживало бы верности? Таких вещей очень мало. Я думаю, надо быть верным бессмертию, этому другому имени жизни, немного усиленному.<br/> Надо сохранять верность бессмертию, надо быть верным Христу!<br/> Ах, вы морщитесь, несчастный. Опять вы ничегошеньки не поняли.<br/> — Мда, — мычал Иван Иванович, тонкий белокурый вьюн с ехидною бородкой, делавшей его похожим на американца времен Линкольна (он поминутно захватывал её в горсть и ловил её кончик губами). — Я, конечно, молчу. Вы сами понимаете — я смотрю на эти вещи совершенно иначе. Да, кстати. Расскажите, как вас расстригали. Я давно хотел спросить. Небось перетрухнули? Анафеме вас предавали? А?<br/> — Зачем отвлекаться в сторону? Хотя, впрочем, что ж. Анафеме? Нет, сейчас не проклинают. Были неприятности, имеются последствия. Например, долго нельзя на государственную службу. Не пускают в столицы. Но это ерунда. Вернемся к предмету разговора. Я сказал — надо быть верным Христу. Сейчас я объясню. Вы не понимаете, что можно быть атеистом, можно не знать, есть ли Бог и для чего он, и в то же время знать, что человек живет не в природе, а в истории, и что в нынешнем понимании она основана Христом, что Евангелие есть её обоснование. А что такое история? Это установление вековых работ по последовательной разгадке смерти и её будущему преодолению. Для этого открывают математическую бесконечность и электромагнитные волны, для этого пишут симфонии. Двигаться вперед в этом направлении нельзя без некоторого подъема. Для этих открытий требуется духовное оборудование. Данные для него содержатся в Евангелии. Вот они. Это, во-первых, любовь к ближнему, этот высший вид живой энергии, переполняющей сердце человека и требующей выхода и расточения, и затем это главные составные части современного человека, без которых он немыслим, а именно идея свободной личности и идея жизни как жертвы. Имейте в виду, что это до сих пор чрезвычайно ново.<br/> Истории в этом смысле не было у древних. Там было сангвиническое свинство жестоких, оспою изрытых Калигул, не подозревавших, как бездарен всякий поработитель. Там была хвастливая мертвая вечность бронзовых памятников и мраморных колонн. Века и поколенья только после Христа вздохнули свободно. Только после него началась жизнь в потомстве, и человек умирает не на улице под забором, а у себя в истории, в разгаре работ, посвященных преодолению смерти, умирает, сам посвященный этой теме. Уф, аж взопрел, что называется. А ему хоть кол теши на голове!<br/> — Метафизика, батенька. Это мне доктора запретили, этого мой желудок не варит.<br/> — Ну да Бог с вами. Бросим. Счастливец! Вид-то от вас какой — не налюбуешься! А он живет и не чувствует.<br/> На реку было больно смотреть. Она отливала на солнце, вгибаясь и выгибаясь, как лист железа. Вдруг она пошла складками. С этого берега на тот поплыл тяжелый паром с лошадьми, телегами, бабами и мужиками.<br/> — Подумайте, только шестой час, — сказал Иван Иванович.<br/> — Видите, скорый из Сызрани. Он тут проходит в пять с минутами.<br/> Вдали по равнине справа налево катился чистенький желто-синий поезд, сильно уменьшенный расстоянием. Вдруг они заметили, что он остановился. Над паровозом взвились белые клубочки пара. Немного спустя пришли его тревожные свистки.<br/> — Странно, — сказал Воскобойников. — Что-нибудь неладное. Ему нет причины останавливаться там на болоте.<br/> Что-то случилось. Пойдемте чай пить.

