### 6 {-}

Ники не оказалось ни в саду, ни в доме. Юра догадывался, что он прячется от них, потому что ему скучно с ними, и Юра ему не пара. Дядя с Иваном Ивановичем пошли заниматься на террасу, предоставив Юре слоняться без цели вокруг дома.<br/> Здесь была удивительная прелесть! Каждую минуту слышался чистый трехтонный высвист иволог, с промежутками выжидания, чтобы влажный, как из дудки извлеченный звук до конца пропитал окрестность. Стоячий, заблудившийся в воздухе запах цветов пригвожден был зноем неподвижно к клумбам. Как это напоминало Антибы и Бордигеру! Юра поминутно поворачивался направо и налево. Над лужайками слуховой галлюцинацией висел призрак маминого голоса, он звучал Юре в мелодических оборотах птиц и жужжании пчел. Юра вздрагивал, ему то и дело мерещилось, будто мать аукается с ним и куда-то его подзывает.<br/> Он пошел к оврагу и стал спускаться. Он спустился из редкого и чистого леса, покрывавшего верх оврага, в ольшаник, выстилавший его дно.<br/> Здесь была сырая тьма, бурелом и падаль, было мало цветов и членистые стебли хвоща были похожи на жезлы и посохи с египетским орнаментом, как в его иллюстрированном священном писании.<br/> Юре становилось все грустнее. Ему хотелось плакать. Он повалился на колени и залился слезами.<br/> — Ангеле Божий, хранителю мой святый, — молился Юра, — утверди ум мой во истиннем пути и скажи мамочке, что мне здесь хорошо, чтобы она не беспокоилась. Если есть загробная жизнь, Господи, учини мамочку в рай, идеже лицы святых и праведницы сияют яко светила. Мамочка была такая хорошая, не может быть, чтобы она была грешница, помилуй ее, Господи, сделай, чтобы она не мучилась. Мамочка! — в душераздирающей тоске звал он её с неба, как новопричтенную угодницу, и вдруг не выдержал, упал наземь и потерял сознание.<br/> Он не долго лежал без памяти. Когда он очнулся, он услышал, что дядя зовет его сверху. Он ответил и стал подыматься. Вдруг он вспомнил, что не помолился о своем без вести пропадающем отце, как учила его Мария Николаевна.<br/> Но ему было так хорошо после обморока, что он не хотел расставаться с этим чувством легкости и боялся потерять его. И он подумал, что ничего страшного не будет, если он помолится об отце как-нибудь в другой раз.<br/> — Подождет. Потерпит, — как бы подумал он. Юра его совсем не помнил.

