### 7 {-}

В поезде в купе второго класса ехал со своим отцом, присяжным поверенным Гордоном из Оренбурга, гимназист второго класса Миша Гордон, одиннадцатилетний мальчик с задумчивым лицом и большими черными глазами. Отец переезжал на службу в Москву, мальчик переводился в московскую гимназию. Мать с сестрами были давно на месте, занятые хлопотами по устройству квартиры.<br/> Мальчик с отцом третий день находился в поезде.<br/> Мимо в облаках горячей пыли, выбеленная солнцем, как известью, летела Россия, поля и степи, города и села. По дорогам тянулись обозы, грузно сворачивая с дороги к переездам, и с бешено несущегося поезда казалось, что возы стоят не двигаясь, а лошади подымают и опускают ноги на одном месте.<br/> На больших остановках пассажиры как угорелые бегом бросались в буфет, и садящееся солнце из-за деревьев станционного сада освещало их ноги и светило под колеса вагонов.<br/> Все движения на свете в отдельности были рассчитанно-трезвы, а в общей сложности безотчетно пьяны общим потоком жизни, который объединял их. Люди трудились и хлопотали, приводимые в движение механизмом собственных забот.<br/> Но механизмы не действовали бы, если бы главным их регулятором не было чувство высшей и краеугольной беззаботности. Эту беззаботность придавало ощущение связности человеческих существований, уверенность в их переходе одного в другое, чувство счастья по поводу того, что все происходящее совершается не только на земле, в которую закапывают мертвых, а еще в чем-то другом, в том, что одни называют царством Божиим, а другие историей, а третьи еще как-нибудь.<br/> Из этого правила мальчик был горьким и тяжелым исключением.<br/> Его конечною пружиной оставалось чувство озабоченности, и чувство беспечности не облегчало и не облагораживало его. Он знал за собой эту унаследованную черту и с мнительной настороженностью ловил в себе её признаки. Она огорчала его.<br/> Ее присутствие его унижало.<br/> С тех пор как он себя помнил, он не переставал удивляться, как что при одинаковости рук и ног и общности языка и привычек можно быть не тем, что все, и притом чем-то таким, что нравится немногим и чего не любят? Он не мог понять положения, при котором, если ты хуже других, ты не можешь приложить усилий, чтобы исправиться и стать лучше. Что значит быть евреем? Для чего это существует? Чем вознаграждается или оправдывается этот безоружный вызов, ничего не приносящий, кроме горя?<br/> Когда он обращался за ответом к отцу, тот говорил, что его исходные точки нелепы и так рассуждать нельзя, но не предлагал взамен ничего такого, что привлекло бы Мишу глубиною смысла и обязало бы его молча склониться перед неотменимым.<br/> И делая исключение для отца и матери, Миша постепенно преисполнился презрением к взрослым, заварившим кашу, которой они не в силах расхлебать. Он был уверен, что когда он вырастет, он все это распутает.<br/> Вот и сейчас, никто ни решился бы сказать, что его отец поступил не правильно, пустившись за этим сумасшедшим вдогонку, когда он выбежал на площадку, и что не надо было останавливать поезда, когда, с силой оттолкнув Григория Осиповича и распахнувши дверцу вагона, он бросился на всем ходу со скорого вниз головой на насыпь, как бросаются с мостков купальни под воду, когда ныряют.<br/> Но так как ручку тормоза повернул не кто-нибудь, а именно Григорий Осипович, то выходило, что поезд продолжает стоять так необъяснимо долго по их милости.<br/> Никто толком не знал причины проволочки. Одни говорили, что от внезапной остановки произошло повреждение воздушных тормозов, другие, что поезд стоит на крутом подъеме и без разгона паровоз не может его взять. Распространяли третье мнение, что так как убившийся видное лицо, то его поверенный, ехавший с ним в поезде, потребовал, чтобы с ближайшей станции Кологривовки вызвали понятых для составления протокола. Вот для чего помощник машиниста лазил на телефонный столб. Дрезина наверное уже в пути.<br/> В вагоне чуть-чуть несло из уборных, зловоние которых старались отбить туалетной водой, и пахло жареными курами с легким душком, завернутыми в грязную промасленную бумагу. В нем по-прежнему пудрились, обтирали платком ладони и разговаривали грудными скрипучими голосами седеющие дамы из Петербурга, поголовно превращенные в жгучих цыганок соединением паровозной гари с жирною косметикой. Когда они проходили мимо Гордоновского купе, кутая углы плеч в накидки и превращая тесноту коридора в источник нового кокетства, Мише казалось, что они шипят или, судя по их поджатым губам, должны шипеть: «Ах, скажите, пожалуйста, какая чувствительность! Мы особенные! Мы интеллигенты! Мы не можем!»<br/> Тело самоубийцы лежало на траве около насыпи. Струйка запекшейся крови резким знаком чернела поперек лба и глаз разбившегося, перечеркивая это лицо словно крестом вымарки.<br/> Кровь казалась не его кровью, вытекшею из него, а приставшим посторонним придатком, пластырем, или брызгом присохшей грязи, или мокрым березовым листком.<br/> Кучка любопытных и сочувствующих вокруг тела все время менялась. Над ним хмуро без выражения стоял его приятель и сосед по купе, плотный и высокомерный адвокат, породистое животное в вымокшей от пота рубашке. Он изнывал от жары и обмахивался мягкой шляпой. На все расспросы он нелюбезно цедил, пожимая плечами и даже не оборачиваясь: «Алкоголик. Неужели непонятно? Самое типическое следствие белой горячки».<br/> К телу два или три раза подходила худощавая женщина в шерстяном платье с кружевной косынкою. Это была вдова и мать двух машинистов, старуха Тиверзина, бесплатно следовавшая с двумя невестками в третьем классе по служебным билетам. Тихие, низко повязанные платками женщины безмолвно следовали за ней, как две сестры за настоятельницей. Эта группа вселяла уважение. Перед ними расступались.<br/> Муж Тиверзиной сгорел заживо при одной железнодорожной катастрофе. Она становилась в нескольких шагах от трупа, так, чтобы сквозь толпу ей было видно, и вздохами как бы проводила сравнение. «Кому как на роду написано, — как бы говорила она. — Какой по произволению Божию, а тут, вишь, такой стих нашел — от богатой жизни и ошаления рассудка».<br/> Все пассажиры поезда перебывали около тела и возвращались в вагон только из опасения, как бы у них чего не стащили.<br/> Когда они спрыгивали на полотно, разминались, рвали цветы и делали легкую пробежку, у всех было такое чувство, будто местность возникла только что благодаря остановке, и болотистого луга с кочками, широкой реки и красивого дома с церковью на высоком противоположном берегу не было бы на свете, не случись несчастия.<br/> Даже солнце, тоже казавшееся местной принадлежностью, по-вечернему застенчиво освещало сцену у рельсов, как бы боязливо приблизившись к ней, как подошла бы к полотну и стала бы смотреть на людей корова из пасущегося по соседству стада.<br/> Миша потрясен был всем происшедшим и в первые минуты плакал от жалости и испуга. В течение долгого пути убившийся несколько раз заходил посидеть у них в купе и часами разговаривал с Мишиным отцом. Он говорил, что отходит душой в нравственно чистой тишине и понятливости их мира, и расспрашивал Григория Осиповича о разных юридических тонкостях и кляузных вопросах по части векселей и дарственных, банкротств и подлогов.<br/> — Ах вот как? — удивлялся он разъяснениям Гордона. — Вы располагаете какими-то более милостивыми узаконениями. У моего поверенного иные сведения. Он смотрит на эти вещи гораздо мрачнее.<br/> Каждый раз, как этот нервный человек успокаивался, за ним из первого класса приходил его юрист и сосед по купе и тащил его в салон-вагон пить шампанское. Это был тот плотный, наглый, гладко выбритый и щеголеватый адвокат, который стоял теперь над телом, ничему на свете не удивляясь. Нельзя было отделаться от ощущения, что постоянное возбуждение его клиента в каком-то отношении ему на руку.<br/> Отец говорил, что это известный богач, добряк и шелапут, уже наполовину невменяемый. Не стесняясь Мишиного присутствия, он рассказывал о своем сыне, Мишином ровеснике, и о покойнице жене, потом переходил к своей второй семье, тоже покинутой.<br/> Тут он вспоминал что-то новое, бледнел от ужаса и начинал заговариваться и забываться.<br/> К Мише он выказывал необъяснимую, вероятно, отраженную и, может быть, не ему предназначенную нежность. Он поминутно дарил ему что-нибудь, для чего выходил на самых больших станциях в залы первого класса, где были книжные стойки и продавали игры и достопримечательности края.<br/> Он пил не переставая и жаловался, что не спит третий месяц и, когда протрезвляется хотя бы ненадолго, терпит муки, о которых нормальный человек не имеет представления.<br/> За минуту до конца он вбежал к ним в купе, схватил Григория Осиповича за руку, хотел что-то сказать, но не мог и, выбежав на площадку, бросился с поезда.<br/> Миша рассматривал небольшой набор уральских минералов в деревянном ящичке — последний подарок покойного. Вдруг кругом все задвигалось. По другому пути к поезду подошла дрезина. С нее соскочил следователь в фуражке с кокардой, врач, двое городовых. Послышались холодные деловые голоса. Задавали вопросы, что-то записывали. Вверх по насыпи, все время обрываясь и съезжая по песку, кондуктора и городовые неловко волокли тело. Завыла какая-то баба. Публику попросили в вагоны и дали свисток. Поезд тронулся.

