### 8 {-}

«Опять это лампадное масло!» — злобно подумал Ника и заметался по комнате. Голоса гостей приближались. Отступление было отрезано. В спальне стояли две кровати, Воскобойниковская и его, Никина. Недолго думая, Ника залез под вторую. Он слышал, как искали, кликали его в других комнатах, удивлялись его пропаже. Потом вошли в спальню.<br/> — Ну что ж делать, — сказал Веденяпин, — пройдись, Юра, может быть, после найдется товарищ, поиграете.<br/> Некоторое время они говорили об университетских волнениях в Петербурге и Москве, продержав Нику минут двадцать в его глупой унизительной засаде. Наконец они ушли на террасу. Ника тихонько открыл окно, выскочил в него и ушел в парк.<br/> Он был сегодня сам не свой и предшествующую ночь не спал.<br/> Ему шел четырнадцатый год. Ему надоело быть маленьким. Всю ночь он не спал и на рассвете вышел из флигеля. Всходило солнце, и землю в парке покрывала длинная, мокрая от росы, петлистая тень деревьев. Тень была не черного, а темно-серого цвета, как промокший войлок. Одуряющее благоухание утра, казалось, исходило именно от этой отсыревшей тени на земле с продолговатыми просветами, похожими на пальцы девочки.<br/> Вдруг серебристая струйка ртути, такая же, как капли росы в траве, потекла в нескольких шагах от него. Струйка текла, текла, а земля её не впитывала. Неожиданно резким движением струйка метнулась в сторону и скрылась. Это была змея медянка.<br/> Ника вздрогнул.<br/> Он был странный мальчик. В состоянии возбуждения он громко разговаривал с собой. Он подражал матери в склонности к высоким материям и парадоксам.<br/> «Как хорошо на свете!» — подумал он. — «Но почему от этого всегда так больно? Бог, конечно, есть. Но если он есть, то он это я. Вот я велю ей», — подумал он, взглянув на осину, всю снизу доверху охваченную трепетом (ее мокрые переливчатые листья казались нарезанными из жести), — «вот я прикажу ей» — и в безумном превышении своих сил он не шепнул, но всем существом своим, всей своей плотью и кровью пожелал и задумал: «Замри!» — и дерево тотчас же послушно застыло в неподвижности. Ника засмеялся от радости и со всех ног бросился купаться на реку.<br/> Его отец, террорист Дементий Дудоров, отбывал каторгу, по высочайшему помилованию взамен повешения, к которому он был приговорен. Его мать из грузинских княжен Эристовых была взбалмошная и еще молодая красавица, вечно чем-нибудь увлекающаяся — бунтами, бунтарями, крайними теориями, знаменитыми артистами, бедными неудачниками.<br/> Она обожала Нику и из его имени Иннокентий делала кучу немыслимо нежных и дурацких прозвищ вроде Иночек или Ноченька и возила его показывать своей родне в Тифлис. Там его больше всего поразило разлапое дерево на дворе дома, где они остановились. Это был какой-то неуклюжий тропический великан.<br/> Своими листьями, похожими на слоновые уши, он ограждал двор от палящего южного неба. Ника не мог привыкнуть к мысли, что это дерево — растение, а не животное.<br/> Мальчику было опасно носить страшное отцовское имя. Иван Иванович с согласия Нины Галактионовны собирался подавать на высочайшее имя о присвоении Нике материнской фамилии.<br/> Когда он лежал под кроватью, возмущаясь ходом вещей на свете, он среди всего прочего думал и об этом. Кто такой Воскобойников, чтобы заводить так далеко свое вмешательство?<br/> Вот он их проучит!<br/> А эта Надя! Если ей пятнадцать лет, значит, она имеет право задирать нос и разговаривать с ним как с маленьким? Вот он ей покажет! «Я её ненавижу, — несколько раз повторил он про себя. — Я её убью! Я позову её кататься на лодке и утоплю».<br/> Хороша также и мама. Она надула, конечно, его и Воскобойникова, когда уезжала. Ни на каком она не на Кавказе, а просто-напросто свернула с ближайшей узловой на север и преспокойно стреляет себе в Петербурге вместе со студентами в полицию. А он должен сгнить заживо в этой глупой яме. Но он их всех перехитрит. Утопит Надю, бросит гимназию и удерет подымать восстание к отцу в Сибирь.<br/> Край пруда порос сплошь кувшинками. Лодка взрезала эту гущу с сухим шорохом. В разрывах заросли проступала вода пруда, как сок арбуза в треугольнике разреза.<br/> Мальчик и девочка стали рвать кувшинки. Оба ухватились за один и тот же нервущийся и тугой, как резина, стебель. Он стянул их вместе. Дети стукнулись головами. Лодку как багром подтянуло к берегу. Стебли перепутывались и укорачивались, белые цветы с яркою, как желток с кровью, сердцевиной уходили под воду и выныривали со льющеюся из них водою.<br/> Надя и Ника продолжали рвать цветы, все более накреняя лодку и почти лежа рядом на опустившемся борту.<br/> — Надоело учиться, — сказал Ника. — Пора начинать жизнь, зарабатывать, идти в люди.<br/> — А я как раз хотела попросить тебя объяснить мне квадратные уравнения. Я так слаба в алгебре, что дело чуть не кончилось переэкзаменовкой.<br/> Нике в этих словах почудились какие-то шпильки. Ну, конечно, она ставит его на место, напоминая ему, как он еще мал. Квадратные уравнения! А они еще и не нюхали алгебры.<br/> Не выдавая, как он уязвлен, он спросил притворно равнодушно, в ту же минуту поняв, как это глупо:<br/> — Когда ты вырастешь, за кого ты выйдешь замуж?<br/> — О, это еще так далеко. Вероятно ни за кого. Я пока не думала.<br/> — Не воображай, пожалуйста, что мне это очень интересно.<br/> — Тогда зачем спрашиваешь?<br/> — Ты дура.<br/> Они начали ссориться. Нике вспомнилось его утреннее женоненавистничество. Он пригрозил Наде, что если она не перестанет говорить дерзости, он её утопит.<br/> — Попробуй, — сказала Надя.<br/> Он схватил её поперек туловища. Между ними завязалась драка. Они потеряли равновесие и полетели в воду.<br/> Оба умели плавать, но водяные лилии цеплялись за их руки и ноги, а дна они еще не могли нащупать. Наконец, увязая в тине, они выбрались на берег. Вода ручьями текла из их башмаков и карманов. Особенно устал Ника.<br/> Если бы это случилось совсем еще недавно, не дальше чем нынешней весной, то в данном положении, сидя мокры-мокрешеньки вдвоем после такой переправы, они непременно бы шумели, ругались бы или хохотали.<br/> А теперь они молчали и еле дышали, подавленные бессмыслицей случившегося. Надя возмущалась и молча негодовала, а у Ники болело все тело, словно ему перебили палкою ноги и руки и продавили ребра.<br/> Наконец тихо, как взрослая, Надя проронила: «Сумасшедший!»<br/> — и он также по-взрослому сказал: «Прости меня».<br/> Они стали подниматься к дому, оставляя мокрый след за собой, как две водовозные бочки. Их дорога лежала по пыльному подъему, кишевшему змеями, невдалеке от того места, где Ника утром увидал медянку.<br/> Ника вспомнил волшебную приподнятость ночи, рассвет и свое утреннее всемогущество, когда он по своему произволу повелевал природой. Что приказать ей сейчас? — подумал он. Чего бы ему больше всего хотелось? Ему представилось, что больше всего хотел бы он когда-нибудь еще раз свалиться в пруд с Надею и много бы отдал сейчас, чтобы знать, будет ли это когда-нибудь или нет.

