## ЧАСТЬ вторая. ДЕВОЧКА ИЗ ДРУГОГО КРУГА {-}

### 1 {-}

Война с Японией еще не кончилась. Неожиданно её заслонили другие события. По России прокатывались волны революции, одна другой выше и невиданней.<br/> В это время в Москву с Урала приехала вдова инженера-бельгийца и сама обрусевшая француженка Амалия Карловна Гишар с двумя детьми, сыном Родионом и дочерью Ларисою. Сына она отдала в кадетский корпус, а дочь в женскую гимназию, по случайности ту самую и тот же самый класс, в которых училась Надя Кологривова.<br/> У мадам Гишар были от мужа сбережения в бумагах, которые раньше поднимались, а теперь стали падать. Чтобы приостановить таяние своих средств и не сидеть сложа руки, мадам Гишар купила небольшое дело, швейную мастерскую Левицкой близ Триумфальных ворот у наследников портнихи, с правом сохранения старой фирмы, с кругом её прежних заказчиц и всеми модистками и ученицами.<br/> Мадам Гишар сделала это по совету адвоката Комаровского, друга своего мужа и своей собственной опоры, хладнокровного дельца, знавшего деловую жизнь в России как свои пять пальцев.<br/> С ним она списалась насчет переезда, он встречал их на вокзале, он повез через всю Москву в меблированные комнаты «Черногория» в Оружейном переулке, где снял для них номер, он же уговорил отдать Родю в корпус, а Лару в гимназию, которую он порекомендовал, и он же невнимательно шутил с мальчиком и заглядывался на девочку так, что она краснела.

