### 2 {-}

Перед тем как переселиться в небольшую квартиру в три комнаты, находившуюся при мастерской, они около месяца прожили в «Черногории».<br/> Это были самые ужасные места Москвы, лихачи и притоны, целые улицы, отданные разврату, трущобы «погибших созданий».<br/> Детей не удивляла грязь в номерах, клопы, убожество меблировки. После смерти отца мать жила в вечном страхе обнищания. Родя и Лара привыкли слышать, что они на краю гибели. Они понимали, что они не дети улицы, но в них глубоко сидела робость перед богатыми, как у питомцев сиротских домов.<br/> Живой пример этого страха подавала им мать. Амалия Карловна была «полная блондинка лет тридцати пяти, у которой сердечные припадки сменялись припадками глупости. Она была страшная трусиха и смертельно боялась мужчин. Именно поэтому она с перепугу и от растерянности все время попадала к ним из объятия в объятие.<br/> В «Черногории» они занимали двадцать третий номер, а в двадцать четвертом со дня основания номеров жил виолончелист Тышкевич, потливый и лысый добряк в паричке, который молитвенно складывал руки и прижимал их к груди, когда убеждал кого-нибудь, и закидывал голову назад и вдохновенно закатывал глаза, играя в обществе и выступая на концертах. Он редко бывал дома и на целые дни уходил в Большой театр или Консерваторию. Соседи познакомились. Взаимные одолжения сблизили их.<br/> Так как присутствие детей иногда стесняло Амалию Карловну во время посещений Комаровского, Тышкевич, уходя, стал оставлять ей ключ от своего номера для приема её приятеля.<br/> Скоро мадам Гишар так свыклась с его самопожертвованием, что несколько раз в слезах стучалась к нему, прося у него защиты от своего покровителя.

