### 3 {-}

Дом был одноэтажный, недалеко от угла Тверской.<br/> Чувствовалась близость Брестской железной дороги. Рядом начинались её владения, казенные квартиры служащих, паровозные депо и склады.<br/> Туда ходила домой к себе Оля Демина, умная девочка, племянница одного служащего с Москвы-Товарной.<br/> Она была способная ученица. Ее отмечала старая владелица и теперь стала приближать к себе новая. Оле Деминой очень нравилась Лара.<br/> Все оставалось, как при Левицкой. Как очумелые, крутились швейные машины под опускающимися ногами или порхающими руками усталых мастериц. Кто-нибудь тихо шил, сидя на столе и отводя на отлет руку с иглой и длинной ниткой. Пол был усеян лоскутками. Разговаривать приходилось громко, чтобы перекричать стук швейных машин и переливчатые трели Кирилла Модестовича, канарейки в клетке под оконным сводом, тайну прозвища которой унесла с собой в могилу прежняя хозяйка.<br/> В приемной дамы живописной группой окружали стол с журналами. Они стояли, сидели и полуоблокачивались в тех позах, какие видели на картинках, и, рассматривая модели, советовались насчет фасонов. За другим столом на директорском месте сидела помощница Амалии Карловны из старших закройщиц, Фаина Силантьевна Фетисова, костлявая женщина с бородавками в углублениях дряблых щек.<br/> Она держала костяной мундштук с папиросой в пожелтевших зубах, щурила глаз с желтым белком и, выпуская желтую струю дыма ртом и носом, записывала в тетрадку мерки, номера квитанций, адреса и пожелания толпившихся заказчиц.<br/> Амалия Карловна была в мастерской новым и неопытным человеком. Она не чувствовала себя в полном смысле хозяйкою.<br/> Но персонал был честный, на Фетисову можно было положиться.<br/> Тем не менее время было тревожное. Амалия Карловна боялась задумываться о будущем. Отчаяние охватывало ее. Все валилось у нее из рук.<br/> Их часто навещал Комаровский. Когда Виктор Ипполитович проходил через всю мастерскую, направляясь на их половину и мимоходом пугая переодевавшихся франтих, которые скрывались при его появлении за ширмы и оттуда игриво парировали его развязные шутки, мастерицы неодобрительно и насмешливо шептали ему вслед: «Пожаловал», «Ейный», «Амалькина присуха», «Буйвол», «Бабья порча».<br/> Предметом еще большей ненависти был его бульдог Джек, которого он иногда приводил на поводке и который такими стремительными рывками тащил его за собою, что Комаровский сбивался с шага, бросался вперед и шел за собакой, вытянув руки, как слепой за поводырем.<br/> Однажды весной Джек вцепился Ларе в ногу и разорвал ей чулок.<br/> — Я его смертью изведу, нечистую силу, — по-детски прохрипела Ларе на ухо Оля Демина.<br/> — Да, в самом деле противная собака. Но как же ты, глупенькая, это сделаешь?<br/> — Тише, ты не ори, я вас научу. Вот яйца есть на Пасху каменные. Ну вот у вашей маменьки на комоде…<br/> — Ну да, мраморные, хрустальные.<br/> — Ага, вот-вот. Ты нагнись, я на ухо. Надо взять, вымочить в сале, сало пристанет, наглотается он, паршивый пес, набьет, сатана, пестерь, и — шабаш! Кверху лапки! Стекло!<br/> Лара смеялась и с завистью думала: девочка живет в нужде, трудится. Малолетние из народа рано развиваются. А вот поди же ты, сколько в ней еще неиспорченного, детского. Яйца, Джек — откуда что берется? «За что же мне такая участь, — думала Лара, — что я все вижу и так о всем болею?»

