### 4 {-}

«Ведь для него мама — как это называется… Ведь он — мамин, это самое… Это гадкие слова, не хочу повторять. Так зачем в таком случае он смотрит на меня такими глазами? Ведь я её дочь».<br/> Ей было немногим больше шестнадцати, но она была вполне сложившейся девушкой. Ей давали восемнадцать лет и больше. У нее был ясный ум и легкий характер. Она была очень хороша собой.<br/> Она и Родя понимали, что всего в жизни им придется добиваться своими боками. В противоположность праздным и обеспеченным, им некогда было предаваться преждевременному пронырству и теоретически разнюхивать вещи, практически их еще не касавшиеся. Грязно только лишнее. Лара была самым чистым существом на свете.<br/> Брат и сестра знали цену всему и дорожили достигнутым. Надо было быть на хорошем счету, чтобы пробиться. Лара хорошо училась не из отвлеченной тяги к знаниям, а потому что для освобождения от платы за учение надо было быть хорошей ученицей, а для этого требовалось хорошо учиться. Так же хорошо, как она училась, Лара без труда мыла посуду, помогала в мастерской и ходила по маминым поручениям. Она двигалась бесшумно и плавно, и все в ней — незаметная быстрота движений, рост, голос, серые глаза и белокурый цвет волос были под стать друг другу.<br/> Было воскресенье, середина июля. По праздникам можно было утром понежиться в постели подольше. Лара лежала на спине, закинувши руки назад и положив их под голову.<br/> В мастерской стояла непривычная тишина. Окно на улицу было отворено. Лара слышала, как громыхавшая вдали пролетка съехала с булыжной мостовой в желобок коночного рельса и грубая стукотня сменилась плавным скольжением колеса как по маслу.<br/> «Надо поспать еще немного», — подумала Лара. Рокот города усыплял, как колыбельная песня.<br/> Свой рост и положение в постели Лара ощущала сейчас двумя точками — выступом левого плеча и большим пальцем правой ноги. Это были плечо и нога, а все остальное — более или менее она сама, её душа или сущность, стройно вложенная в очертания и отзывчиво рвущаяся в будущее.<br/> «Надо уснуть», — думала Лара и вызывала в воображении солнечную сторону Каретного ряда в этот час, сараи экипажных заведений с огромными колымагами для продажи на чисто подметенных полах, граненое стекло каретных фонарей, медвежьи чучела, богатую жизнь. А немного ниже, в мыслях рисовала себе Лара, — учение драгун во дворе Знаменских казарм, чинные ломающиеся лошади, идущие по кругу, прыжки с разбега в седла и проездка шагом, проездка рысью, проездка вскачь. И разинутые рты нянек с детьми и кормилиц, рядами прижавшихся снаружи к казарменной ограде. А еще ниже, думала Лара, — Петровка, Петровские линии.<br/> «Что вы, Лара! Откуда такие мысли? Просто я хочу показать вам свою квартиру. Тем более что это рядом».<br/> Была Ольга, у его знакомых в Каретном маленькая дочь именинница. По этому случаю веселились взрослые — танцы, шампанское. Он приглашал маму, но мама не могла, ей нездоровилось. Мама сказала: «Возьмите Лару. Вы меня всегда предостерегаете: „Амалия, берегите Лару“. Вот теперь и берегите ее». И он её берег, нечего сказать! Ха-ха-ха!<br/> Какая безумная вещь вальс! Кружишься, кружишься, ни о чем не думая. Пока играет музыка, проходит целая вечность, как жизнь в романах. Но едва перестают играть, ощущение скандала, словно тебя облили холодной водой или застали неодетой. Кроме того, эти вольности позволяешь другим из хвастовства, чтобы показать, какая ты уже большая.<br/> Она никогда не могла предположить, что он так хорошо танцует. Какие у него умные руки, как уверенно берется он за талию! Но целовать себя так она больше никому не позволит. Она никогда не могла предположить, что в чужих губах может сосредоточиться столько бесстыдства, когда их так долго прижимают к твоим собственным.<br/> Бросить эти глупости. Раз навсегда. Не разыгрывать простушки, не умильничать, не потуплять стыдливо глаз. Это когда-нибудь плохо кончится. Тут совсем рядом страшная черта.<br/> Ступить шаг, и сразу же летишь в пропасть. Забыть думать о танцах. В них все зло. Не стесняться отказывать. Выдумать, что не училась танцевать или сломала ногу.

