### 5 {-}

Осенью происходили волнения на железных дорогах московского узла. Забастовала Московско-Казанская железная дорога. К ней должна была примкнуть Московско-Брестская. Решение о забастовке было принято, но в комитете дороги не могли столковаться о дне её объявления. Все на дороге знали о забастовке, и требовался только внешний повод, чтобы она началась самочинно.<br/> Было холодное пасмурное утро начала октября. В этот день на линии должны были выдавать жалованье. Долго не поступали сведения из счетной части. Потом в контору прошел мальчик с табелью, выплатной ведомостью и грудой отобранных с целью взыскания рабочих книжек. Платеж начался. По бесконечной полосе незастроенного пространства, отделявшего вокзал, мастерские, паровозные депо, пакгаузы и рельсовые пути от деревянных построек правления, потянулись за заработком проводники, стрелочники, слесаря и их подручные, бабы поломойки из вагонного парка.<br/> Пахло началом городской зимы, топтанным листом клена, талым снегом, паровозной гарью и теплым ржаным хлебом, который выпекали в подвале вокзального буфета и только что вынули из печи. Приходили и отходили поезда. Их составляли и разбирали, размахивая свернутыми и развернутыми флагами. На все лады заливались рожки сторожей, карманные свистки сцепщиков и басистые гудки паровозов. Столбы дыма бесконечными лестницами подымались к небу. Растопленные паровозы стояли готовые к выходу, обжигая холодные зимние облака кипящими облаками пара.<br/> По краю полотна расхаживали взад и вперед начальник дистанции инженер путей сообщения Фуфлыгин и дорожный мастер привокзального участка Павел Ферапонтович Антипов. Антипов надоедал службе ремонта жалобами на материал, который отгружали ему для обновления рельсового покрова. Сталь была недостаточной вязкости. Рельсы не выдерживали пробы на прогиб и излом и по предположениям Антипова должны были лопаться на морозе. Управление относилось безучастно к жалобам Павла Ферапонтовича. Кто-то нагревал себе на этом руки.<br/> На Фуфлыгине была расстегнутая дорогая шуба с путейским кантиком и под нею новый штатский костюм из шевиота. Он осторожно ступал по насыпи, любуясь общей линией пиджачных бортов, правильностью брючной складки и благородной формой своей обуви.<br/> Слова Антипова влетали у него в одно ухо и вылетали в другое. Фуфлыгин думал о чем-то своем, каждую минуту вынимал часы, смотрел на них и куда-то торопился.<br/> — Верно, верно, батюшка, — нетерпеливо прерывал он Антипова, — но это только на главных путях где-нибудь или на сквозном перегоне, где большое движение. А вспомни, что у тебя? Запасные пути какие-то и тупики, лопух да крапива, в крайнем случае — сортировка порожняка и разъезды маневровой «кукушки». И он еще недоволен! Да ты с ума сошел! Тут не то что такие рельсы, тут можно класть деревянные.<br/> Фуфлыгин посмотрел на часы, захлопнул крышку и стал вглядываться в даль, откуда к железной дороге приближалась шоссейная. На повороте дороги показалась коляска. Это был свой выезд Фуфлыгина. За ним пожаловала жена. Кучер остановил лошадей почти у полотна, все время сдерживая их и потпрукивая на них тоненьким бабьим голоском, как няньки на квасящихся младенцев, — лошади пугались железной дороги. В углу коляски, небрежно откинувшись на подушки, сидела красивая дама.<br/> — Ну, брат, как-нибудь в другой раз, — сказал начальник дистанции и махнул рукой — не до твоих, мол, рельсов. Есть поважнее материи.<br/> Супруги укатили.

