### 6 {-}

Через часа три или четыре, поближе к сумеркам, в стороне от дороги в поле как из-под земли выросли две фигуры, которых раньше не было на поверхности, и, часто оглядываясь, стали быстро удаляться. Это были Антипов и Тиверзин.<br/> — Пойдем скорее, — сказал Тиверзин. — Я не шпиков остерегаюсь, как бы не выследили, а сейчас кончится эта волынка, вылезут они из землянки и нагонят. А я их видеть не могу. Когда всё так тянуть, незачем и огород городить. Не к чему тогда и комитет, и с огнем игра, и лезть под землю! И ты тоже хорош, эту размазню с Николаевской поддерживаешь.<br/> — У моей Дарьи тиф брюшной. Мне бы её в больницу. Покамест не свезу, ничего в голову не лезет.<br/> — Говорят, выдают сегодня жалованье. Схожу в контору. Не платежный бы день, вот как перед Богом, плюнул бы я на вас и, не медля ни минуты, своей управой положил бы конец гомозне.<br/> — Это, позвольте спросить, каким же способом?<br/> — Дело нехитрое. Спустился в котельную, дал свисток и кончен бал.<br/> Они простились и пошли в разные стороны.<br/> Тиверзин шел по путям в направлении к городу. Навстречу ему попадались люди, шедшие с получкою из конторы. Их было очень много. Тиверзин на глаз определил, что на территории станции расплатились почти со всеми.<br/> Стало смеркаться. На открытой площадке возле конторы толпились незанятые рабочие, освещенные конторскими фонарями.<br/> На въезде к площадке стояла Фуфлыгинская коляска. Фуфлыгина сидела в ней в прежней позе, словно она с утра не выходила из экипажа. Она дожидалась мужа, получавшего деньги в конторе.<br/> Неожиданно пошел мокрый снег с дождем. Кучер слез с козел и стал поднимать кожаный верх. Пока, упершись ногой в задок, он растягивал тугие распорки, Фуфлыгина любовалась бисерно-серебристой водяной кашей, мелькавшей в свете конторских фонарей. Она бросала немигающий мечтательный взгляд поверх толпившихся рабочих с таким видом, словно в случае надобности этот взгляд мог бы пройти без ущерба через них насквозь, как сквозь туман или изморось.<br/> Тиверзин случайно подхватил это выражение. Его покоробило.<br/> Он прошел, не поклонившись Фуфлыгиной, и решил зайти за жалованьем попозже, чтобы не сталкиваться в конторе с её мужем. Он пошел дальше, в менее освещенную сторону мастерских, где чернел поворотный круг с расходящимися путями в паровозное депо.<br/> — Тиверзин! Куприк! — окликнуло его несколько голосов из темноты. Перед мастерскими стояла кучка народу. Внутри кто-то орал и слышался плач ребенка. — Киприян Савельевич, заступитесь за мальчика, — сказала из толпы какая-то женщина.<br/> Старый мастер Петр Худолеев опять по обыкновению лупцевал свою жертву, малолетнего ученика Юсупку.<br/> Худолеев не всегда был истязателем подмастерьев, пьяницей и тяжелым на руку драчуном. Когда-то на бравого мастерового заглядывались купеческие дочери и поповны подмосковных мануфактурных посадов. Но мать Тиверзина, в то время выпускница епархиалка, за которую он сватался, отказала ему и вышла замуж за его товарища, паровозного машиниста Савелия Никитича Тиверзина.<br/> На шестой год её вдовства, после ужасной смерти Савелия Никитича (он сгорел в 1888 году при одном нашумевшем в то время столкновении поездов), Петр Петрович возобновил свое искательство, и опять Марфа Гавриловна ему отказала. С тех пор Худолеев запил и стал буянить, сводя счеты со всем светом, виноватым, как он был уверен, в его нынешних неурядицах.<br/> Юсупка был сыном дворника Гимазетдина с тиверзинского двора. Тиверзин покровительствовал мальчику в мастерских. Это подогревало в Худолееве неприязнь к нему.<br/> — Как ты напилок держишь, азиат, — орал Худолеев, таская Юсупку за волосы и костыляя по шее. — Нешто так отливку обдирают? Я тебе спрашиваю, будешь ты мне работу поганить, касимовская невеста, алла мулла косые глаза?<br/> — Ай не буду, дяинька, ай не буду, не буду, ай больно!<br/> — Тыщу раз ему сказывали, вперед подведи бабку, а тады завинчивай упор, а он знай свое, знай свое. Чуть мне шпентель не сломал, сукин сын.<br/> — Я шпиндил не трогал, дяинька, ей-Богу, не трогал.<br/> — За что ты мальчика тиранишь? — спросил Тиверзин, протиснувшись сквозь толпу.<br/> — Свои собаки грызутся, чужая не подходи, — отрезал Худолеев.<br/> — Я тебя спрашиваю, за что ты мальчика тиранишь?<br/> — А я тебе говорю, проходи с Богом, социал-командир. Его убить мало, сволочь этакую, чуть мне шпентель не сломал. Пущай мне руки целует, что жив остался, косой черт, — уши я ему только надрал да за волосы поучил.<br/> — А что же, по-твоему, ему за это надо голову оторвать, дядя Худолей? Постыдился бы право. Старый мастер, дожил до седых волос, а не нажил ума.<br/> — Проходи, проходи, говорю, покуда цел. Дух из тебя я вышибу учить меня, собачье гузно! Тебя на шпалах делали, севрюжья кровь, у отца под самым носом. Мать твою, мокрохвостку, я во как знаю, кошку драную, трепаный подол!<br/> Все происшедшее дальше заняло не больше минуты. Оба схватили первое, что подвернулось под руку на подставках станков, на которых валялись тяжелые инструменты и куски железа, и убили бы друг друга, если бы народ в ту же минуту не бросился кучею их разнимать. Худолеев и Тиверзин стояли, нагнув головы и почти касаясь друг друга лбами, бледные с налившимися кровью глазами. От волнения они не могли выговорить ни слова. Их крепко держали, ухвативши сзади за руки. Минутами, собравшись с силой, они начинали вырываться, извиваясь всем телом и волоча за собой висевших на них товарищей. Крючки и пуговицы у них на одёже пообрывались, куртки и рубахи сползли с оголившихся плеч. Нестройный гам вокруг них не умолкал.<br/> — Зубило! Зубило у него отыми — проломит башку. — Тише, тише, дядя Петр, вывернем руку! — Это всё так с ними хороводиться? Растащить врозь, посадить под замок — и дело с концом.<br/> Вдруг нечеловеческим усилием Тиверзин стряхнул с себя клубок навалившихся тел и, вырвавшись от них, с разбега очутился у двери. Его кинулись было ловить, но увидав, что у него совсем не то на уме, оставили в покое. Его окружала осенняя сырость, ночь, темнота.<br/> — Ты им стараешься добро, а они норовят тебе нож в ребро, — ворчал он и не сознавал, куда и зачем он идет.<br/> Этот мир подлости и подлога, где разъевшаяся барынька смеет так смотреть на дуралеев-тружеников, а спившаяся жертва этих порядков находит удовольствие в глумлении над себе подобным, этот мир был ему сейчас ненавистнее, чем когда-либо. Он шел быстро, словно поспешность его походки могла приблизить время, когда все на свете будет разумно и стройно, как сейчас в его разгоряченной голове. Он знал, что их стремления последних дней, беспорядки на линии, речи на сходках и их решение бастовать, не приведенное пока еще в исполнение, но и не отмененное, — все это отдельные части этого большого и еще предстоящего пути.<br/> Но сейчас его возбуждение дошло до такой степени, что ему не терпелось пробежать все это расстояние разом, не переводя дыхания. Он не соображал, куда он шагает, широко раскидывая ноги, но ноги прекрасно знали, куда несли его.<br/> Тиверзин долго не подозревал, что после ухода его и Антипова из землянки на заседании было постановлено приступить к забастовке в этот же вечер. Члены комитета тут же распределили между собой, кому куда идти и кого где снимать.<br/> Когда из паровозоремонтного, словно со дна Тиверзинской души, вырвался хриплый, постепенно прочищающийся и выравнивающийся сигнал, от входного семафора к городу уже двигалась толпа из депо и с товарной станции, сливаясь с новою толпой, побросавшей работу по Тиверзинскому свистку из котельной.<br/> Тиверзин много лет думал, что это он один остановил в ту ночь работы и движение на дороге. Только позднейшие процессы, на которых его судили по совокупности и не вставляли подстрекательства к забастовке в пункты обвинения, вывели его из этого заблуждения.<br/> Выбегали, спрашивали:<br/> — Куда народ свищут? — Из темноты отвечали:<br/> — Небось и сам не глухой. Слышишь — тревога. Пожар тушить. — А где горит? — Стало быть горит, коли свищут.<br/> Хлопали двери, выходили новые. Раздавались другие голоса.<br/> — Толкуй тоже — пожар! Деревня! Не слушайте дурака. Это называется зашабашили, понял? Вот хомут, вот дуга, я те больше не слуга. По домам, ребята.<br/> Народу все прибывало. Железная дорога забастовала.

