### 7 {-}

Тиверзин пришел домой на третий день продрогший, невыспавшийся и небритый. Накануне ночью грянул мороз, небывалый для таких чисел, а Тиверзин был одет по-осеннему. У ворот встретил его дворник Гимазетдин.<br/> — Спасибо, господин Тиверзин, — зарядил он. — Юсуп обида не давал, заставил век Бога молить.<br/> — Что ты очумел, Гимазетдин, какой я тебе господин? Брось ты это, пожалуйста. Говори скорее, видишь мороз какой.<br/> — Зачем мороз, тебе тепло, Савельич. Мы вчерашний день твой мамаша Марфа Гавриловна Москва-Товарная полный сарай дров возили, одна береза, хорошие дрова, сухие дрова.<br/> — Спасибо, Гимазетдин. Ты еще что-то сказать хочешь, скорее, пожалуйста, озяб я, понимаешь.<br/> — Сказать хотел, дома не ночуй, Савельич, хорониться надо.<br/> Постовой спрашивал, околодочный спрашивал, кто, говорит, ходит. Я говорю, никто не ходит. Помощник, говорю, ходит, паровозная бригада ходит, железная дорога ходит. А чтобы кто-нибудь чужой, ни-ни!<br/> Дом, в котором холостой Тиверзин жил вместе с матерью и женатым младшим братом, принадлежал соседней церкви святой Троицы. Дом этот был заселен некоторою частью причта, двумя артелями фруктовщиков и мясников, торговавших в городе с лотков вразнос, а по преимуществу мелкими служащими Московско-Брестской железной дороги.<br/> Дом был каменный с деревянными галереями. Они с четырех сторон окружали грязный немощеный двор. Вверх по галереям шли грязные и скользкие деревянные лестницы. На них пахло кошками и квашеной капустой. По площадкам лепились отхожие будки и кладовые под висячими замками.<br/> Брат Тиверзина был призван рядовым на войну и ранен под Вафангоу. Он лежал на излечении в Красноярском госпитале, куда для встречи с ним и принятия его на руки выехала его жена с двумя дочерями. Потомственные железнодорожники Тиверзины были легки на подъем и разъезжали по всей России по даровым служебным удостоверениям. В настоящее время в квартире было тихо и пусто. В ней жили только сын да мать.<br/> Квартира помещалась во втором этаже. Перед входною дверью на галерее стояла бочка, которую наполнял водой водовоз. Когда Киприян Савельевич поднялся в свой ярус, он обнаружил, что крышка с бочки сдвинута набок и на обломке льда, сковавшего воду, стоит примерзшая к ледяной корочке железная кружка.<br/> — Не иначе — Пров, — подумал Тиверзин, усмехнувшись. — Пьет, не напьется, прорва, огненное нутро.<br/> Пров Афанасьевич Соколов, псаломщик, видный и нестарый мужчина, был дальним родственником Марфы Гавриловны.<br/> Киприян Савельевич оторвал кружку от ледяной корки, надвинул крышку на бочку и дернул ручку дверного колокольчика.<br/> Облако жилого духа и вкусного пара двинулось ему навстречу.<br/> — Жарко истопили, маменька. Тепло у нас, хорошо.<br/> Мать бросилась к нему на шею, обняла и заплакала. Он погладил её по голове, подождал и мягко отстранил.<br/> — Смелость города берет, маменька, — тихо сказал он, — стоит моя дорога от Москвы до самой Варшавы.<br/> — Знаю. Оттого и плачу. Несдобровать тебе. Убраться бы тебе, Купринька, куда-нибудь подальше.<br/> — Чуть мне голову не проломил ваш миленький дружок, любезный пастушок ваш, Петр Петров.<br/> Он думал рассмешить ее. Она не поняла шутки и серьезно ответила:<br/> — Грех над ним смеяться, Купринька. Ты б его пожалел.<br/> Отпетый горемыка, погибшая душа.<br/> — Забрали Антипова Пашку. Павла Ферапонтовича. Пришли ночью, обыск, все перебуторили. Утром увели. Тем более Дарья его тиф это, в больнице. Павлушка малый, — в реальном учится, — один в доме с теткой глухой. Притом гонят их с квартиры. Я считаю, надо мальчика к нам. Зачем Пров заходил?<br/> — Почем ты знаешь?<br/> — Бочка, вижу, не покрыта и кружка стоит. Обязательно, думаю, Пров бездонный воду хлобыстал.<br/> — Какой ты догадливый, Купринька. Твоя правда. Пров, Пров, Пров Афанасьевич. Забежал попросить дров взаймы — я дала. Да что я дура, — дрова! Совсем из головы у меня вон, какую он новость принес. Государь, понимаешь, манифест подписал, чтобы все перевернуть по-новому, никого не обижать, мужикам землю и всех сравнять с дворянами. Подписанный указ, ты что думаешь, только обнародовать. Из синода новое прошение прислали, вставить в ектинью, или там какое-то моление заздравное, не хочу врать. Провушка сказывал, да я вот запамятовала.

