### 8 {-}

Патуля Антипов, сын арестованного Павла Ферапонтовича и помещенной в больницу Дарьи Филимоновны, поселился у Тиверзиных. Это был чистоплотный мальчик с правильными чертами лица и русыми волосами, расчесанными на прямой пробор. Он их поминутно приглаживал щеткою и поминутно оправлял куртку и кушак с форменной пряжкой реального училища. Патуля был смешлив до слез и очень наблюдателен. Он с большим сходством и комизмом передразнивал все, что видел и слышал.<br/> Вскоре после манифеста семнадцатого октября задумана была большая демонстрация от Тверской заставы к Калужской. Это было начинание в духе пословицы «у семи нянек дитя без глазу».<br/> Несколько революционных организаций, причастных к затее, перегрызлись между собой и одна за другой от нее отступились, а когда узнали, что в назначенное утро люди все же вышли на улицу, наскоро послали к манифестантам своих представителей.<br/> Несмотря на отговоры и противодействие Киприяна Савельевича, Марфа Гавриловна пошла на демонстрацию с веселым и общительным Патулей.<br/> Был сухой морозный день начала ноября, с серо-свинцовым спокойным небом и реденькими, почти считанными снежинками, которые долго и уклончиво вились, перед тем как упасть на землю и потом серою пушистой пылью забиться в дорожные колдобины.<br/> Вниз по улице валил народ, сущее столпотворение, лица, лица и лица, зимние пальто на вате и барашковые шапки, старики, курсистки и дети, путейцы в форме, рабочие трамвайного парка и телефонной станции в сапогах выше колен и кожаных куртках, гимназисты и студенты.<br/> Некоторое время пели «Варшавянку», «Вы жертвою пали» и «Марсельезу», но вдруг человек, пятившийся задом перед шествием и взмахами зажатой в руке кубанки дирижировавший пением, надел шапку, перестал запевать и, повернувшись спиной к процессии, пошел впереди и стал прислушиваться, о чем говорят остальные распорядители, шедшие рядом. Пение расстроилось и оборвалось. Стал слышен хрустящий шаг несметной толпы по мерзлой мостовой.<br/> Доброжелатели сообщали инициаторам шествия, что демонстрантов впереди подстерегают казаки. О готовящейся засаде телефонировали в близлежащую аптеку.<br/> — Так что же, — говорили распорядители. — Тогда главное — хладнокровие и не теряться. Надо немедленно занять первое общественное здание, какое попадется по дороге, объявить людям о грозящей опасности и расходиться поодиночке.<br/> Заспорили, куда будет лучше всего. Одни предлагали в Общество купеческих приказчиков, другие в Высшее техническое, третьи в Училище иностранных корреспондентов.<br/> Во время этого спора впереди показался угол казенного здания. В нем тоже помещалось учебное заведение, годившееся в качестве прибежища ничуть не хуже перечисленных.<br/> Когда идущие поравнялись с ним, вожаки поднялись на полукруглую площадку и знаками остановили голову процессии.<br/> Многостворчатые двери входа открылись, и шествие в полном составе, шуба за шубой и шапка за шапкой стало вливаться в вестибюль школы и подниматься по её парадной лестнице.<br/> — В актовый зал, в актовый зал! — кричали сзади единичные голоса, но толпа продолжала валить дальше, разбредаясь в глубине по отдельным коридорам и классам.<br/> Когда публику все же удалось вернуть, и все расселись на стульях, руководители несколько раз пытались объявить собранию о расставленной впереди ловушке, но их никто не слушал.<br/> Остановка и переход в закрытое помещение были поняты как приглашение на импровизированный митинг, который тут же и начался.<br/> Людям после долгого шагания с пением хотелось посидеть немного молча, и чтобы теперь кто-нибудь другой отдувался за них и драл свою глотку. По сравнению с главным удовольствием отдыха безразличны были ничтожные разногласия говоривших, почти во всем солидарных друг с другом.<br/> Поэтому наибольший успех выпал на долю наихудшего оратора, не утомлявшего слушателей необходимостью следить за ним.<br/> Каждое его слово сопровождалось ревом сочувствия. Никто не жалел, что его речь заглушается шумом одобрения. С ним торопились согласиться из нетерпения, кричали «позор», составляли телеграмму протеста и вдруг, наскучив однообразием его голоса, поднялись как один и, совершенно забыв про оратора, шапка за шапкой и ряд за рядом толпой спустились по лестнице и высыпали на улицу. Шествие продолжалось.<br/> Пока митинговали, на улице повалил снег. Мостовые побелели.<br/> Снег валил все гуще.<br/> Когда налетели драгуны, этого в первую минуту не подозревали в задних рядах. Вдруг спереди прокатился нарастающий гул, как когда толпою кричат «ура». Крики «караул», «убили» и множество других слились во что-то неразличимое. Почти в ту же минуту на волне этих звуков по тесному проходу, образовавшемуся в шарахнувшейся толпе, стремительно и бесшумно пронеслись лошадиные морды и гривы и машущие шашками всадники.<br/> Полувзвод проскакал, повернул, перестроился и врезался сзади в хвост шествия. Началось избиение.<br/> Спустя несколько минут улица была почти пуста. Люди разбегались по переулкам. Снег шел реже. Вечер был сух, как рисунок углем. Вдруг садящееся где-то за домами солнце стало из-за угла словно пальцем тыкать во все красное на улице: в красноверхие шапки драгун, в полотнище упавшего красного флага, в следы крови, протянувшиеся по снегу красненькими ниточками и точками.<br/> По краю мостовой полз, притягиваясь на руках, стонущий человек с раскроенным черепом. Снизу шагом в ряд ехало несколько конных. Они возвращались с конца улицы, куда их завлекло преследование. Почти под ногами у них металась Марфа Гавриловна в сбившемся на затылок платке и не своим голосом кричала на всю улицу: «Паша! Патуля!»<br/> Он все время шел с ней и забавлял ее, с большим искусством изображая последнего оратора, и вдруг пропал в суматохе, когда наскочили драгуны.<br/> В переделке Марфа Гавриловна сама получила по спине нагайкой, и хотя её плотно подбитый ватою шушун не дал ей почувствовать удара, она выругалась и погрозила кулаком удалявшейся кавалерии, возмущенная тем, как это ее, старуху, осмелились при всем честном народе вытянуть плеткой.<br/> Марфа Гавриловна бросала взволнованные взгляды по обе стороны мостовой. Вдруг она по счастью увидала мальчика на противоположном тротуаре. Там в углублении между колониальной лавкой и выступом каменного особняка толпилась кучка случайных ротозеев.<br/> Туда загнал их крупом и боками своей лошади драгун, въехавший верхом на тротуар. Его забавлял их ужас, и, загородив им выход, он производил перед их носом манежные вольты и пируэты, пятил лошадь задом и медленно, как в цирке, подымал её на дыбы. Вдруг впереди он увидел шагом возвращающихся товарищей, дал лошади шпоры и в два-три прыжка занял место в их ряду.<br/> Народ, сжатый в закоулке, рассеялся. Паша, раньше боявшийся подать голос, кинулся к бабушке.<br/> Они шли домой. Марфа Гавриловна все время ворчала:<br/> — Смертоубийцы проклятые, окаянные душегубы! Людям радость, царь волю дал, а эти не утерпят. Все бы им испакостить, всякое слово вывернуть наизнанку.<br/> Она была зла на драгун, на весь свет кругом и в эту минуту даже на родного сына. В моменты запальчивости ей казалось, что все происходящее сейчас, это всё штуки Купринькиных путаников, которых она звала промахами и мудрофелями.<br/> — Злые аспиды! Что им, оглашенным, надо? Никакого понятия!<br/> Только бы лаяться да вздорить. А этот, речистый, как ты его, Пашенька? Покажи, милый, покажи. Ой помру, ой помру! Ни дать ни взять как вылитый. Тру-ру ру-ру-ру. Ах ты зуда-жужелица, конская строка!<br/> Дома она накинулась с упреками на сына, не в таких, мол, она летах, чтобы её конопатый болван вихрастый с коника хлыстом учил по заду.<br/> — Да что вы, ей-Богу, маменька! Словно я, право, казачий сотник какой или шейх жандармов.

