### 9 {-}

Николай Николаевич стоял у окна, когда показались бегущие.<br/> Он понял, что это с демонстрации, и некоторое время всматривался вдаль, не увидит ли среди расходящихся Юры или еще кого-нибудь. Однако знакомых не оказалось, только раз ему почудилось, что быстро прошел этот (Николай Николаевич забыл его имя), сын Дудорова, отчаянный, у которого еще так недавно извлекли пулю из левого плеча и который опять околачивался, где не надо.<br/> Николай Николаевич приехал сюда осенью из Петербурга. В Москве у него не было своего угла, а в гостиницу ему не хотелось. Он остановился у Свентицких, своих дальних родственников. Они отвели ему угловой кабинет наверху в мезонине.<br/> Этот двухэтажный флигель, слишком большой для бездетной четы Свентицких, покойные старики Свентицкие с незапамятных времен снимали у князей Долгоруких. Владение Долгоруких с тремя дворами, садом и множеством разбросанных в беспорядке разностильных построек выходило в три переулка и называлось по-старинному Мучным городком.<br/> Несмотря на свои четыре окна, кабинет был темноват. Его загромождали книги, бумаги, ковры и гравюры. К кабинету снаружи примыкал балкон, полукругом охватывавший этот угол здания. Двойная стеклянная дверь на балкон была наглухо заделана на зиму.<br/> В два окна кабинета и стекла балконной двери переулок был виден в длину — убегающая вдаль санная дорога, криво расставленные домики, кривые заборы.<br/> Из сада в кабинет тянулись лиловые тени. Деревья с таким видом заглядывали в комнату, словно хотели положить на пол свои ветки в тяжелом инее, похожем на сиреневые струйки застывшего стеарина.<br/> Николай Николаевич глядел в переулок и вспоминал прошлогоднюю петербургскую зиму, Гапона, Горького, посещение Витте, модных современных писателей. Из этой кутерьмы он удрал сюда, в тишь да гладь первопрестольной, писать задуманную им книгу. Куда там! Он попал из огня да в полымя. Каждый день лекции и доклады, не дадут опомниться. То на Высших женских, то в Религиозно-философском, то на Красный Крест, то в Фонд стачечного комитета. Забраться бы в Швейцарию, в глушь лесного кантона. Мир и ясность над озером, небо и горы, и звучный, всему вторящий, настороженный воздух.<br/> Николай Николаевич отвернулся от окна. Его поманило в гости к кому-нибудь или просто так без цели на улицу. Но тут он вспомнил, что к нему должен прийти по делу толстовец Выволочнов, и ему нельзя отлучаться. Он стал расхаживать по комнате. Мысли его обратились к племяннику.<br/> Когда из приволжского захолустья Николай Николаевич переехал в Петербург, он привез Юру в Москву в родственный круг Веденяпиных, Остромысленских, Селявиных, Михаелисов, Свентицких и Громеко. Для начала Юру водворили к безалаберному старику и пустомеле Остромысленскому, которого родня запросто величала Федькой. Федька негласно сожительствовал со своей воспитанницей Мотей и потому считал себя потрясателем основ, поборником идеи. Он не оправдал возложенного доверия и даже оказался нечистым на руку, тратя в свою пользу деньги, назначенные на Юрино содержание. Юру перевели в профессорскую семью Громеко, где он и по сей день находился.<br/> У Громеко Юру окружала завидно благоприятная атмосфера.<br/> — У них там такой триумвират, — думал Николай Николаевич:<br/> Юра, его товарищ и одноклассник гимназист Гордон и дочь хозяев Тоня Громеко. Этот тройственный союз начитался «Смысла любви» и «Крейцеровой сонаты» и помешан на проповеди целомудрия.<br/> Отрочество должно пройти через все неистовства чистоты. Но они пересаливают, у них заходит ум за разум.<br/> Они страшные чудаки и дети. Область чувственного, которая их так волнует, они почему-то называют «пошлостью» и употребляют это выражение кстати и некстати. Очень неудачный выбор слова! «Пошлость» — это у них и голос инстинкта, и порнографическая литература, и эксплуатация женщины, и чуть ли не весь мир физического. Они краснеют и бледнеют, когда произносят это слово!<br/> Если бы я был в Москве, — думал Николай Николаевич, — я бы не дал этому зайти так далеко. Стыд необходим, и в некоторых границах…<br/> — А, Нил Феоктистович! Милости просим, — воскликнул он и пошел навстречу гостю.

