### 10 {-}

В комнату вошел толстый мужчина в серой рубашке, подпоясанный широким ремнем. Он был в валенках, штаны пузырились у него на коленках. Он производил впечатление добряка, витающего в облаках. На носу у него злобно подпрыгивало маленькое пенсне на широкой черной ленте.<br/> Разоблачаясь в прихожей, он не довел дело до конца. Он не снял шарфа, конец которого волочился у него по полу, и в руках у него осталась его круглая войлочная шляпа. Эти предметы стесняли его в движениях и не только мешали Выволочнову пожать руку Николаю Николаевичу, но даже выговорить слова приветствия, здороваясь с ним.<br/> — Э-мм, — растерянно мычал он, осматриваясь по углам.<br/> — Кладите где хотите, — сказал Николай Николаевич, вернув Выволочнову дар речи и самообладание.<br/> Это был один из тех последователей Льва Николаевича Толстого, в головах которых мысли гения, никогда не знавшего покоя, улеглись вкушать долгий и неомраченный отдых и непоправимо мельчали.<br/> Выволочнов пришел просить Николая Николаевича выступить в какой-то школе в пользу политических ссыльных.<br/> — Я уже раз читал там.<br/> — В пользу политических?<br/> — Да.<br/> — Придется еще раз.<br/> Николай Николаевич поупрямился и согласился. Предмет посещения был исчерпан. Николай Николаевич не удерживал Нила Феоктистовича. Он мог подняться и уйти. Но Выволочнову казалось неприличным уйти так скоро. На прощанье надо было сказать что-нибудь живое, непринужденное. Завязался разговор, натянутый и неприятный.<br/> — Декадентствуете? Вдались в мистику?<br/> — То есть это почему же?<br/> — Пропал человек. Земство помните?<br/> — А как же. Вместе по выборам работали.<br/> — За сельские школы ратовали и учительские семинарии. Помните?<br/> — Как же. Жаркие были бои. Вы потом, кажется, по народному здравию подвизались и общественному призрению. Не правда ли?<br/> — Некоторое время.<br/> — Нда. А теперь эти фавны и ненюфары, эфебы и «будем как солнце». Хоть убейте, не поверю. Чтобы умный человек с чувством юмора и таким знанием народа… Оставьте, пожалуйста… Или, может быть, я вторгаюсь… Что-нибудь сокровенное?<br/> — Зачем бросать наудачу слова, не думая? О чем мы препираемся? Вы не знаете моих мыслей.<br/> — России нужны школы и больницы, а не фавны и ненюфары.<br/> — Никто не спорит.<br/> — Мужик раздет и пухнет от голода…<br/> Такими скачками подвигался разговор. Сознавая наперед никчемность этих попыток, Николай Николаевич стал объяснять, что его сближает с некоторыми писателями из символистов, а потом перешел к Толстому.<br/> — До какой-то границы я с вами. Но Лев Николаевич говорит, что чем больше человек отдается красоте, тем больше отдаляется от добра.<br/> — А вы думаете, что наоборот? Мир спасет красота, мистерии и тому подобное, Розанов и Достоевский?<br/> — Погодите, я сам скажу, что я думаю. Я думаю, что если бы дремлющего в человеке зверя можно было остановить угрозою, все равно, каталажки или загробного воздаяния, высшею эмблемой человечества был бы цирковой укротитель с хлыстом, а не жертвующий собою проповедник. Но в том-то и дело, что человека столетиями поднимала над животным и уносила ввысь не палка, а музыка: неотразимость безоружной истины, притягательность её примера. До сих пор считалось, что самое важное в Евангелии нравственные изречения и правила, заключенные в заповедях, а для меня самое главное то, что Христос говорит притчами из быта, поясняя истину светом повседневности. В основе этого лежит мысль, что общение между смертными бессмертно и что жизнь символична, потому что она значительна.<br/> — Ничего не понял. Вы бы об этом книгу написали.<br/> Когда ушел Выволочнов, Николаем Николаевичем овладело страшное раздражение. Он был зол на себя за то, что выболтал чурбану Выволочнову часть своих заветных мыслей, не произведя на него ни малейшего впечатления. Как это иногда бывает, досада Николая Николаевича вдруг изменила направление. Он совершенно забыл о Выволочнове, словно его никогда не бывало.<br/> Ему припомнился другой случай. Он не вел дневников, но раз или два в году записывал в толстую общую тетрадь наиболее поразившие его мысли. Он вынул тетрадь и стал набрасывать крупным разборчивым почерком. Вот что он записал.<br/> «Весь день вне себя из-за этой дуры Шлезингер. Приходит утром, засиживается до обеда и битых два часа томит чтением этой галиматьи. Стихотворный текст символиста А. для космогонической симфонии композитора Б. с духами планет, голосами четырех стихий и прочая и прочая. Я терпел, терпел и не выдержал, взмолился, что, мол, не могу, увольте.<br/> Я вдруг все понял. Я понял, отчего это всегда так убийственно нестерпимо и фальшиво даже в Фаусте. Это деланный, ложный интерес. Таких запросов нет у современного человека.<br/> Когда его одолевают загадки вселенной, он углубляется в физику, а не в гекзаметры Гезиода.<br/> Но дело не только в устарелости этих форм, в их анахронизме. Дело не в том, что эти духи огня и воды вновь неярко запутывают то, что ярко распутано наукою. Дело в том, что этот жанр противоречит всему духу нынешнего искусства, его существу, его побудительным мотивам.<br/> Эти космогонии были естественны на старой земле, заселенной человеком так редко, что он не заслонял еще природы. По ней еще бродили мамонты и свежи были воспоминания о динозаврах и драконах. Природа так явно бросалась в глаза человеку и так хищно и ощутительно — ему в загривок, что, может быть, в самом деле все было еще полно богов. Это самые первые страницы летописи человечества, они только еще начинались.<br/> Этот древний мир кончился в Риме от перенаселения.<br/> Рим был толкучкою заимствованных богов и завоеванных народов, давкою в два яруса, на земле и на небе, свинством, захлестнувшимся вокруг себя тройным узлом, как заворот кишок.<br/> Даки, герулы, скифы, сарматы, гиперборейцы, тяжелые колеса без спиц, заплывшие от жира глаза, скотоложество, двойные подбородки, кормление рыбы мясом образованных рабов, неграмотные императоры. Людей на свете было больше, чем когда-либо впоследствии, и они были сдавлены в проходах Колизея и страдали.<br/> И вот в завал этой мраморной и золотой безвкусицы пришел этот легкий и одетый в сияние, подчеркнуто человеческий, намеренно провинциальный, галилейский, и с этой минуты народы и боги прекратились и начался человек, человек-плотник, человек-пахарь, человек-пастух в стаде овец на заходе солнца, человек, ни капельки не звучащий гордо, человек, благодарно разнесенный по всем колыбельным песням матерей и по всем картинным галереям мира».

