### 11 {-}

Петровские линии производили впечатление петербургского уголка в Москве. Соответствие зданий по обеим сторонам проезда, лепные парадные в хорошем вкусе, книжная лавка, читальня, картографическое заведение, очень приличный табачный магазин, очень приличный ресторан, перед рестораном — газовые фонари в круглых матовых колпаках на массивных кронштейнах.<br/> Зимой это место хмурилось с мрачной неприступностью. Здесь жили серьезные, уважающие себя и хорошо зарабатывающие люди свободных профессий.<br/> Здесь снимал роскошную холостяцкую квартиру во втором этаже по широкой леснице с широкими дубовыми перилами Виктор Ипполитович Комаровский. Заботливо во все вникающая и в то же время ни во что не вмешивающаяся Эмма Эрнестовна, его экономка, нет — кастелянша его тихого уединения, вела его хозяйство, неслышимая и незримая, и он платил ей рыцарской признательностью, естественной в таком джентльмене, и не терпел в квартире присутствия гостей и посетительниц, не совместимых с её безмятежным стародевическим миром. У них царил покой монашеской обители — шторы опущены, ни пылинки, ни пятнышка, как в операционной.<br/> По воскресеньям перед обедом Виктор Ипполитович имел обыкновение фланировать со своим бульдогом по Петровке и Кузнецкому, и на одном из углов выходил и присоединялся к ним Константин Илларионович Сатаниди, актер и картежник.<br/> Они пускались вместе шлифовать панели, перекидывались короткими анекдотами и замечаниями настолько отрывистыми, незначительными и полными такого презрения ко всему на свете, что без всякого ущерба могли бы заменить эти слова простым рычанием, лишь бы наполнять оба тротуара Кузнецкого своими громкими, бесстыдно задыхающимися и как бы давящимися своей собственной вибрацией басами.

