### 12 {-}

Погода перемогалась. «Кап-кап-кап» долбили капли по железу водосточных труб и карнизов. Крыша перестукивалась с крышею, как весною. Была оттепель.<br/> Всю дорогу она шла, как невменяемая, и только по приходе домой поняла, что случилось.<br/> Дома все спали. Она опять впала в оцепенение и в этой рассеянности опустилась перед маминым туалетным столиком в светло-сиреневом, почти белом платье с кружевной отделкой и длинной вуали, взятыми на один вечер в мастерской, как на маскарад. Она сидела перед своим отражением в зеркале и ничего не видела. Потом положила скрещенные руки на столик и упала на них головою.<br/> Если мама узнает, она убьет ее. Убьет и покончит с собой.<br/> Как это случилось? Как могло это случиться? Теперь поздно.<br/> Надо было думать раньше.<br/> Теперь она, — как это называется, — теперь она — падшая.<br/> Она — женщина из французского романа и завтра пойдет в гимназию сидеть за одной партой с этими девочками, которые по сравнению с ней еще грудные дети. Господи, Господи, как это могло случиться!<br/> Когда-нибудь, через много-много лет, когда можно будет, Лара расскажет это Оле Деминой. Оля обнимет её за голову и разревется.<br/> За окном лепетали капли, заговаривалась оттепель. Кто-то с улицы дубасил в ворота к соседям. Лара не поднимала головы. У нее вздрагивали плечи. Она плакала.

