### 13 {-}

— Ax, Эмма Эрнестовна, это, милочка, неважно. Это надоело.<br/> Он расшвыривал по ковру и дивану какие-то вещи, манжеты и манишки и вдвигал и выдвигал ящики комода, не соображая, что ему надо.<br/> Она требовалась ему дозарезу, а увидеть её в это воскресенье не было возможности. Он метался, как зверь, по комнате, нигде не находя себе места.<br/> Она была бесподобна прелестью одухотворения. Ее руки поражали, как может удивлять высокий образ мыслей. Ее тень на обоях номера казалась силуэтом её неиспорченности. Рубашка обтягивала ей грудь простодушно и туго, как кусок холста, натянутый на пяльцы.<br/> Комаровский барабанил пальцами по оконному стеклу, в такт лошадям, неторопливо цокавшим внизу по асфальту проезда.<br/> «Лара», — шептал он и закрывал глаза, и её голова мысленно появлялась в руках у него, голова спящей с опущенными во сне ресницами, не ведающая, что на нее бессонно смотрят часами без отрыва. Шапка её волос, в беспорядке разметанная по подушке дымом своей красоты ела Комаровскому глаза и проникала в душу.<br/> Его воскресная прогулка не удалась. Комаровский сделал с Джеком несколько шагов по тротуару и остановился. Ему представились Кузнецкий, шутки Сатаниди, встречный поток знакомых. Нет, это выше его сил! Как это все опротивело!<br/> Комаровский повернул назад. Собака удивилась, остановила на нем неодобрительный взгляд с земли и неохотно поплелась сзади.<br/> — Что за наваждение! — думал он. — Что все это значит?<br/> Что это — проснувшаяся совесть, чувство жалости или раскаяния? Или это — беспокойство? Нет, он знает, что она дома у себя и в безопасности. Так что же она не идет из головы у него!<br/> Комаровский вошел в подъезд, дошел по лестнице до площадки и обогнул ее. На ней было венецианское окно с орнаментальными гербами по углам стекла. Цветные зайчики падали с него на пол и подоконник. На половине второго марша Комаровский остановился.<br/> Не поддаваться этой мытарящей, сосущей тоске! Он не мальчик, он должен понимать, что с ним будет, если из средства развлечения эта девочка, дочь его покойного друга, этот ребенок, станет предметом его помешательства. Опомниться! Быть верным себе, не изменять своим привычкам. А то все полетит прахом.<br/> Комаровский до боли сжал рукой широкие перила, закрыл на минуту глаза и, решительно повернув назад, стал спускаться. На площадке с зайчиками он перехватил обожающий взгляд бульдога.<br/> Джек смотрел на него снизу, подняв голову, как старый, слюнявый карлик с отвислыми щеками.<br/> Собака не любила девушки, рвала ей чулки, рычала на нее и скалилась. Она ревновала хозяина к Ларе, словно боясь, как бы он не заразился от нее чем-нибудь человеческим.<br/> — Ах, так вот оно что! Ты решил, что все будет по-прежнему — Сатаниди, подлости, анекдоты? Так вот тебе за это, вот тебе, вот тебе, вот тебе!<br/> Он стал избивать бульдога тростью и ногами. Джек вырвался, воя и взвизгивая, и с трясущимся задом заковылял вверх по лестнице скрестись в дверь и жаловаться Эмме Эрнестовне.<br/> Проходили дни и недели.

