### 14 {-}

О какой это был заколдованный круг! Если бы вторжение Комаровского в Ларину жизнь возбуждало только её отвращение, Лара взбунтовалась бы и вырвалась. Но дело было не так просто.<br/> Девочке льстило, что годящийся ей в отцы красивый, седеющий мужчина, которому аплодируют в собраниях и о котором пишут в газетах, тратит деньги и время на нее, зовет божеством, возит в театры и на концерты и, что называется, «умственно развивает» ее.<br/> И ведь она была еще невзрослою гимназисткой в коричневом платье, тайной участницей невинных школьных заговоров и проказ. Ловеласничанье Комаровского где-нибудь в карете под носом у кучера или в укромной аванложе на глазах у целого театра пленяло её неразоблаченной дерзостью и побуждало просыпавшегося в ней бесенка к подражанию.<br/> Но этот озорной школьнический задор быстро проходил. Ноющая надломленность и ужас перед собой надолго укоренялись в ней. И все время хотелось спать. От недоспанных ночей, от слез и вечной головной боли, от заучивания уроков и общей физической усталости.

### 15 {-}

Он был её проклятием, она его ненавидела. Каждый день она перебирала эти мысли заново.<br/> Теперь она на всю жизнь его невольница, чем он закабалил ее? Чем вымогает её покорность, а она сдается, угождает его желаниям и услаждает его дрожью своего неприкрашенного позора?<br/> Своим старшинством, маминой денежной зависимостью от него, умелым ее, Лары, запугиванием? Нет, нет и нет. Все это вздор.<br/> Не она в подчинении у него, а он у нее. Разве не видит она, как он томится по ней? Ей нечего бояться, её совесть чиста.<br/> Стыдно и страшно должно быть ему, если она уличит его. Но в том-то и дело, что она никогда этого не сделает. На это у нее не хватит подлости, главной силы Комаровского в обращении с подчиненными и слабыми.<br/> Вот в чем их разница. Этим и страшна жизнь кругом. Чем она оглушает, громом и молнией? Нет, косыми взглядами и шепотом оговора. В ней все подвох и двусмысленность. Отдельная нитка, как паутинка, потянул — и нет ее, а попробуй выбраться из сети — только больше запутаешься.<br/> И над сильным властвует подлый и слабый.

