### 16 {-}

Она говорила себе:<br/> — А если бы она была замужем? Чем бы это отличалось? Она вступила на путь софизмов. Но иногда тоска без исхода охватывала ее.<br/> Как ему не стыдно валяться в ногах у нее и умолять: «Так не может продолжаться. Подумай, что я с тобой сделал. Ты катишься по наклонной плоскости. Давай откроемся матери. Я женюсь на тебе».<br/> И он плакал и настаивал, словно она спорила и не соглашалась. Но все это были одни фразы, и Лара даже не слушала этих трагических пустозвонных слов.<br/> И он продолжал водить её под длинною вуалью в отдельные кабинеты этого ужасного ресторана, где лакеи и закусывающие провожали её взглядами и как бы раздевали. И она только спрашивала себя: разве когда любят, унижают?<br/> Однажды ей снилось. Она под землей, от нее остался только левый бок с плечом и правая ступня. Из левого соска у неё растет пучок травы, а на земле поют «Черные очи да белая грудь» и «Не велят Маше за реченьку ходить».

### 17 {-}

Лара не была религиозна. В обряды она не верила. Но иногда для того, чтобы вынести жизнь, требовалось, чтобы она шла в сопровождении некоторой внутренней музыки. Такую музыку нельзя было сочинять для каждого раза самой. Этой музыкой было слово Божие о жизни, и плакать над ним Лара ходила в церковь.<br/> Раз в начале декабря, когда на душе у Лары было, как у Катерины из «Грозы», она пошла помолиться с таким чувством, что вот теперь земля расступится под ней и обрушатся церковные своды. И поделом. И всему будет конец. Жаль только, что она взяла с собой Олю Демину, эту трещотку.<br/> — Пров Афанасьевич, — шепнула ей Оля на ухо.<br/> — Тсс. Отстань, пожалуйста. Какой Пров Афанасьевич?<br/> — Пров Афанасьевич Соколов. Наш троюродный дядюшка. Который читает.<br/> — А, это она про псаломщика. Тиверзинская родня. Тсс. Замолчи. Не мешай мне, пожалуйста.<br/> Они пришли к началу службы. Пели псалом: «Благослови, душе моя, Господа, и вся внутренняя моя имя святое Его».<br/> В церкви было пустовато и гулко. Лишь впереди тесной толпой сбились молящиеся. Церковь была новой стройки. Нерасцвеченное стекло оконницы ничем не скрашивало серого заснеженного переулка и прохожих и проезжих, которые по нему сновали. У этого окна стоял церковный староста и громко на всю церковь, не обращая внимания на службу, вразумлял какую-то глуховатую юродивую оборванку, и его голос был того же казенного будничного образца, как окно и переулок.<br/> Пока, медленно обходя молящихся, Лара с зажатыми в руке медяками шла к двери за свечками для себя и Оли и так же осторожно, чтобы никого не толкнуть, возвращалась назад, Пров Афанасьевич успел отбарабанить девять блаженств, как вещь, и без него всем хорошо известную.<br/> Блажени нищие духом… Блажени плачущие… Блажени алчущие и жаждущие правды…<br/> Лара шла, вздрогнула и остановилась. Это про нее. Он говорит: завидна участь растоптанных. Им есть что рассказать о себе. У них все впереди. Так он считал. Это Христово мнение.

