### 18 {-}

Были дни Пресни. Они оказались в полосе восстания. В нескольких шагах от них на Тверской строили баррикаду. Ее было видно из окна гостиной. С их двора таскали туда ведрами воду и обливали баррикаду, чтобы связать ледяной броней камни и лом, из которых она состояла.<br/> На соседнем дворе было сборное место дружинников, что-то вроде врачебного или питательного пункта.<br/> Туда проходили два мальчика. Лара знала обоих. Один был Ника Дудоров, приятель Нади, у которой Лара с ним познакомилась. Он был Лариного десятка — прямой, гордый и неразговорчивый. Он был похож на Лару и не был ей интересен.<br/> Другой был реалист Антипов, живший у старухи Тиверзиной, бабушки Оли Деминой. Бывая у Марфы Гавриловны, Лара стала замечать, какое действие она производит на мальчика. Паша Антипов был так еще младенчески прост, что не скрывал блаженства, которое доставляли ему её посещения, словно Лара была какая-нибудь березовая роща в каникулярное время с чистою травою и облаками, и можно было беспрепятственно выражать свой телячий восторг по её поводу, не боясь, что за это засмеют.<br/> Едва заметив, какое она на него оказывает влияние, Лара бессознательно стала этим пользоваться. Впрочем, более серьезным приручением мягкого и податливого характера она занялась через несколько лет, в гораздо более позднюю пору своей дружбы с ним, когда Патуля уже знал, что любит её без памяти и что в жизни ему нет больше отступления.<br/> Мальчики играли в самую страшную и взрослую из игр, в войну, притом в такую, за участие в которой вешали и ссылали.<br/> Но концы башлыков были у них завязаны сзади такими узлами, что это обличало в них детей и обнаруживало, что у них есть еще папы и мамы. Лара смотрела на них, как большая на маленьких.<br/> Налет невинности лежал на их опасных забавах. Тот же отпечаток сообщался от них всему остальному. Морозному вечеру, поросшему таким косматым инеем, что вследствие густоты он казался не белым, а черным. Синему двору. Дому напротив, где скрывались мальчики. И главное, главное — револьверным выстрелам, все время щелкавшим оттуда. «Мальчики стреляют», — думала Лара.<br/> Она думала так не о Нике и Патуле, но обо всем стрелявшем городе. «Хорошие, честные мальчики, — думала она. — Хорошие, оттого и стреляют».

