### 19 {-}

Узнали, что по баррикаде могут открыть огонь из пушки и что их дом в опасности. О переходе куда-нибудь к знакомым в другую часть Москвы поздно было думать, их район был оцеплен. Надо было приискать угол поближе, внутри круга. Вспомнили о «Черногории».<br/> Выяснилось, что они не первые. В гостинице все было занято.<br/> Многие оказались в их положении. По старой памяти их обещали устроить в бельевой.<br/> Собрали самое необходимое в три узла, чтобы не привлекать внимание чемоданами, и стали со дня на день откладывать переход в гостиницу.<br/> Ввиду патриархальных нравов, царивших в мастерской, в ней до последнего времени продолжали работать, несмотря на забастовку. Но вот как-то в холодные, скучные сумерки с улицы позвонили. Вошел кто-то с претензиями и упреками. На парадное потребовали хозяйку. В переднюю унимать страсти вышла Фаина Силантьевна.<br/> — Сюда, девоньки! — вскоре позвала она туда мастериц и по очереди стала всех представлять вошедшему.<br/> Он с каждою отдельно поздоровался за руку прочувствованно и неуклюже и ушел, о чем-то уговорившись с Фетисовой.<br/> Вернувшись в зал, мастерицы стали повязываться шалями и вскидывать руки над головами, продевая их в рукава тесных шубеек.<br/> — Что случилось? — спросила подоспевшая Амалия Карловна.<br/> — Нас сымают, мадам. Мы забастовали.<br/> — Разве я… Что я вам сделала плохого? — Мадам Гишар расплакалась.<br/> — Вы не расстраивайтесь, Амалия Карловна. У нас зла на вас нет, мы очень вами благодарны. Да ведь разговор не об вас и об нас. Так теперь у всех, весь свет. А нешто супротив него возможно?<br/> Все разошлись до одной, даже Оля Демина и Фаина Силантьевна, шепнувшая на прощание хозяйке, что инсценирует эту стачку для пользы владелицы и заведения. А та не унималась.<br/> — Какая черная неблагодарность! Подумай, как можно ошибаться в людях! Эта девчонка, на которую я потратила столько души! Ну хорошо, допустим, это ребенок. Но эта старая ведьма!<br/> — Поймите, мамочка, они не могут сделать для вас исключения, — утешала её Лара. — Ни у кого нет озлобления против вас. Наоборот. Все, что происходит сейчас кругом, делается во имя человека, в защиту слабых, на благо женщин и детей. Да, да, не качайте так недоверчиво головой. От этого когда-нибудь будет лучше мне и вам.<br/> Но мать ничего не понимала.<br/> — Вот так всегда, — говорила она, всхлипывая. — Когда мысли и без того путаются, ты ляпнешь что-нибудь такое, что только вылупишь глаза. Мне гадят на голову, и выходит, что это в моих интересах. Нет, верно, правда выжила я из ума.<br/> Родя был в корпусе. Лара с матерью одни слонялись по пустому дому. Неосвещенная улица пустыми глазами смотрела в комнаты. Комнаты отвечали тем же взглядом.<br/> — Пойдемте в номера, мамочка, пока не стемнело. Слышите, мамочка? Не откладывая, сейчас.<br/> — Филат, Филат! — позвали они дворника. — Филат, проводи нас, голубчик, в «Черногорию».<br/> — Слушаюсь, барыня.<br/> — Захватишь узлы, и вот что, Филат, присматривай тут, пожалуйста, пока суд да дело. И зерна и воду не забывай Кириллу Модестовичу. И все на ключ. Да, и, пожалуйста, наведывайся к нам.<br/> — Слушаюсь, барыня.<br/> — Спасибо, Филат. Спаси тебя Христос. Ну, присядем на прощание, и с Богом.<br/> Они вышли на улицу и не узнали воздуха, как после долгой болезни. Морозное, как под орех разделанное пространство, легко перекатывало во все стороны круглые, словно на токарне выточенные, гладкие звуки. Чмокали, шмякали и шлепались залпы и выстрелы, расшибая дали в лепешку.<br/> Сколько ни разуверял их Филат, Лара и Амалия Карловна считали эти выстрелы холостыми.<br/> — Ты, Филат, дурачок. Ну ты сам посуди, как не холостые, когда не видно, кто стреляет. Кто же это, по-твоему, святой дух стреляет, что ли? Разумеется, холостые.<br/> На одном из перекрестков их остановил сторожевой патруль.<br/> Их обыскали, нагло оглаживая их с ног до головы, ухмыляющиеся казаки. Бескозырки на ремешках были лихо сдвинуты у них на ухо. Все они казались одноглазыми.<br/> Какое счастье! — думала Лара. Она не увидит Комаровского все то время, что они будут отрезаны от остального города! Она не может развязаться с ним благодаря матери. Она не может сказать: мама, не принимайте его. А то все откроется. Ну и что же? А зачем этого бояться? Ах, Боже, да пропади все пропадом, только бы конец. Господи, Господи, Господи! Она сейчас упадет без чувств посреди улицы от омерзения. Что она сейчас вспомнила?! Как называлась эта страшная картина с толстым римлянином в том первом отдельном кабинете, с которого все началось? «Женщина или ваза». Ну как же. Конечно. Известная картина. «Женщина или ваза». И она тогда еще не была женщиной, чтобы равняться с такой драгоценностью. Это пришло потом. Стол был так роскошно сервирован.<br/> — Куда ты как угорелая? Не угнаться мне за тобой, — плакала сзади Амалия Карловна, тяжело дыша и еле за ней поспевая.<br/> Лара шла быстро. Какая-то сила несла ее, словно она шагала по воздуху, гордая, воодушевляющая сила.<br/> «О как задорно щелкают выстрелы, — думала она. — Блаженны поруганные, блаженны оплетенные. Дай вам Бог здоровья, выстрелы! Выстрелы, выстрелы, вы того же мнения!».

