### 20 {-}

Дом братьев Громеко стоял на углу Сивцева Вражка и другого переулка. Александр и Николай Александрович Громеко были профессора химии, первый — в Петровской Академии, а второй — в университете. Николай Александрович был холост, а Александр Александрович женат на Анне Ивановне, урожденной Крюгер, дочери фабриканта-железоделателя и владельца заброшенных бездоходных рудников на принадлежавшей ему огромной лесной даче близ Юрятина на Урале.<br/> Дом был двухэтажный. Верх со спальнями, классной, кабинетом Александра Александровича и библиотекой, будуаром Анны Ивановны и комнатами Тони и Юры был для жилья, а низ для приемов. Благодаря фисташковым гардинам, зеркальным бликам на крышке рояля, аквариуму, оливковой мебели и комнатным растениям, похожим на водоросли, этот низ производил впечатление зеленого, сонно колышущегося морского дна.<br/> Громеко были образованные люди, хлебосолы и большие знатоки и любители музыки. Они собирали у себя общество и устраивали вечера камерной музыки, на которых исполнялись фортепианные трио, скрипичные сонаты и струнные квартеты.<br/> В январе тысяча девятьсот шестого года, вскоре после отъезда Николая Николаевича за границу, в Сивцевом должно было состояться очередное камерное. Предполагалось сыграть новую скрипичную сонату одного начинающего из школы Танеева и трио Чайковского.<br/> Приготовления начались накануне. Передвигали мебель, освобождая зал. В углу тянул по сто раз одну и ту же ноту и разбегался бисерными арпеджиями настройщик. На кухне щипали птицу, чистили зелень и растирали горчицу на прованском масле для соусов и салатов.<br/> С утра пришла надоедать Шура Шлезингер, закадычный друг Анны Ивановны, её поверенная.<br/> Шура Шлезингер была высокая худощавая женщина с правильными чертами немного мужского лица, которым она несколько напоминала государя, особенно в своей серой каракулевой шапке набекрень, в которой она оставалась в гостях, лишь слегка приподнимая приколотую к ней вуальку.<br/> В периоды горестей и хлопот беседы подруг приносили им обоюдное облегчение. Облегчение это заключалось в том, что Шура Шлезингер и Анна Ивановна говорили друг другу колкости все более язвительного свойства. Разыгрывалась бурная сцена, быстро кончавшаяся слезами и примирением. Эти регулярные ссоры успокоительно действовали на обеих, как пиявки от прилива крови.<br/> Шура Шлезингер была несколько раз замужем, но забывала мужей тотчас по разводе и придавала им так мало значения, что во всех своих повадках сохраняла холодную подвижность одинокой.<br/> Шура Шлезингер была теософка, но вместе с тем так превосходно знала ход православного богослужения, что даже toure transportee1в состоянии полного экстаза не могла утерпеть, чтобы не подсказывать священнослужителям, что им говорить или петь. «Услыши, Господи», «иже на всякое время», «честнейшую херувим» — все время слышалась её хриплая срывающаяся скороговорка.<br/> Шура Шлезингер знала математику, индийское тайноведение, адреса крупнейших профессоров Московской консерватории, кто с кем живет, и, Бог ты мой, чего она только не знала. Поэтому её приглашали судьей и распорядительницей во всех серьезных случаях жизни.<br/> В назначенный час гости стали съезжаться. Приехали Аделаида Филипповна, Гинц, Фуфковы, господин и госпожа Басурман, Вержицкие, полковник Кавказцев. Шел снег, и когда отворяли парадное, воздух путано несся мимо, весь словно в узелках от мелькания больших и малых снежинок. Мужчины входили с холода в болтающихся на ногах глубоких ботиках и поголовно корчили из себя рассеянных и неуклюжих увальней, а их посвежевшие на морозе жены в расстегнутых на две верхних пуговицы шубках и сбившихся назад пуховых платках на заиндевевших волосах, наоборот, изображали прожженных шельм, само коварство, пальца в рот не клади. «Племянник Кюи», — пронесся шепот, когда приехал новый, в первый раз в этот дом приглашенный пианист.<br/> Из зала через растворенные в двух концах боковые двери виднелся длинный, как зимняя дорога, накрытый стол в столовой.<br/> В глаза бросалась яркая игра рябиновки в бутылках с зернистой гранью. Воображение пленяли судки с маслом и уксусом в маленьких графинчиках на серебряных подставках, и живописность дичи и закусок, и даже сложенные пирамидками салфетки, стойком увенчивавшие каждый прибор, и пахнувшие миндалем сине-лиловые цинерарии в корзинах, казалось, дразнили аппетит. Чтобы не отдалять желанного мига вкушения земной пищи, поторопились как можно скорее обратиться к духовной. Расселись в зале рядами.<br/> «Племянник Кюи», — возобновился шепот, когда пианист занял свое место за инструментом. Концерт начался.<br/> Про сонату знали, что она скучная и вымученная, головная.<br/> Она оправдала ожидания, да к тому же еще оказалась страшно растянутой.<br/> Об этом в перерыве спорили критик Керимбеков с Александром Александровичем. Критик ругал сонату, а Александр Александрович защищал. Кругом курили и шумели, передвигая стулья с места на место.<br/> Но опять взгляды упали на сиявшую в соседней комнате глаженую скатерть. Все предложили продолжать концерт без промедления.<br/> Пианист покосился на публику и кивнул партнерам, чтобы начинали. Скрипач и Тышкевич взмахнули смычками. Трио зарыдало.<br/> Юра, Тоня и Миша Гордон, который полжизни проводил теперь у Громеко, сидели в третьем ряду.<br/> — Вам Егоровна знаки делает, — шепнул Юра Александру Александровичу, сидевшему прямо перед его стулом.<br/> На пороге зала стояла Аграфена Егоровна, старая седая горничная семьи Громеко, и отчаянными взглядами в Юрину сторону и столь же решительными вымахами головы в сторону Александра Александровича давала Юре понять, что ей срочно надо хозяина.<br/> Александр Александрович повернул голову, укоризненно взглянул на Егоровну и пожал плечами. Но Егоровна не унималась. Вскоре между ними из одного конца зала в другой завязалось объяснение, как между глухонемыми. В их сторону смотрели. Анна Ивановна метала на мужа уничтожающие взгляды.<br/> Александр Александрович встал. Надо было что-нибудь предпринять. Он покраснел, тихо под углом обошел зал и подошел к Егоровне.<br/> — Как вам не стыдно, Егоровна! Что это вам, право, приспичило? Ну, скорее, что случилось?<br/> Егоровна что-то зашептала ему.<br/> — Из какой Черногории?<br/> — Номера.<br/> — Ну так что же?<br/> — Безотлагательно требовают. Какие-то ихние кончаются.<br/> — Уж и кончаются. Воображаю. Нельзя, Егоровна. Вот доиграют кусочек, и скажу. А раньше нельзя.<br/> — Номерной дожидается. И то же самое извозчик. Я вам говорю, помирает человек, понимаете? Господского звания дама.<br/> — Нет и нет. Великое дело пять минут, подумаешь.<br/> Александр Александрович тем же тихим шагом вдоль стены вернулся на свое место и сел, хмурясь и растирая переносицу.<br/> После первой части он подошел к исполнителям и, пока гремели рукоплескания, сказал Фадею Казимировичу, что за ним приехали, какая-то неприятность и музыку придется прекратить.<br/> Потом движением ладоней, обращенных к залу, Александр Александрович остановил аплодисменты и громко сказал:<br/> — Господа. Трио придется приостановить. Выразим сочувствие Фадею Казимировичу. У него огорчение. Он вынужден нас покинуть. В такую минуту мне не хотелось бы оставлять его одного. Мое присутствие, может быть, будет ему необходимо. Я поеду с ним. Юрочка, выйди, голубчик, скажи, чтобы Семен подавал к подъезду, у него давно заложено. Господа, я не прощаюсь. Всех прошу оставаться. Отсутствие мое будет кратковременно.<br/> Мальчики запросились прокатиться с Александром Александровичем ночью по морозу.

