### 21 {-}

Несмотря на нормальное течение восстановившейся жизни, после декабря все еще постреливали где-нибудь, и новые пожары, какие бывают постоянно, казались догорающими остатками прежних.<br/> Никогда еще они не ехали так далеко и долго, как в эту ночь. Это было рукой подать — Смоленский, Новинский и половина Садовой. Но зверский мороз с туманом разобщал отдельные куски свихнувшегося пространства, точно оно было не одинаковое везде на свете. Косматый, рваный дым костров, скрип шагов и визг полозьев способствовали впечатлению, будто они едут уже Бог знает как давно и заехали в какую-то ужасающую даль.<br/> Перед гостиницей стояла накрытая попоной лошадь с забинтованными бабками, впряженная в узкие щегольские сани. На месте для седоков сидел лихач, облапив замотанную голову руками в рукавицах, чтобы согреться.<br/> В вестибюле было тепло, и за перилами, отделявшими вешалку от входа, дремал, громко всхрапывал и сам себя этим будил швейцар, усыпленный шумом вентилятора, гуденьем топящейся печки и свистом кипящего самовара.<br/> Налево в вестибюле перед зеркалом стояла накрашенная дама с пухлым, мучнистым от пудры лицом. На ней был меховой жакет, слишком воздушный для такой погоды. Дама кого-то дожидалась сверху и, повернувшись спиной к зеркалу, оглядывала себя то через правое, то через левое плечо, хороша ли она сзади.<br/> В дверь с улицы просунулся озябший лихач. Формою кафтана он напоминал какой-то крендель с вывески, а валивший от него клубами пар еще усиливал это сходство.<br/> — Скоро ли они там, мамзель, — спросил он даму у зеркала.<br/> — С вашим братом свяжешься, только лошадь студить.<br/> Случай в двадцать четвертом был мелочью в обычном каждодневном озлоблении прислуги. Каждую минуту дребезжали звонки и вылетали номерки в длинном стеклянном ящике на стене, указуя, где и под каким номером сходят с ума и, сами не зная, чего хотят, не дают покоя коридорным.<br/> Теперь эту старую дуру Гишарову отпаивали в двадцать четвертом, давали ей рвотного и полоскали кишки и желудок.<br/> Горничная Глаша сбилась с ног, подтирая там пол и вынося грязные и внося чистые ведра. Но нынешняя буря в официантской началась задолго до этой суматохи, когда еще ничего не было в помине и не посылали Терешку на извозчике за доктором и за этою несчастною пиликалкой, когда не приезжал еще Комаровский и в коридоре перед дверью не толклось столько лишнего народу, затрудняя движение.<br/> Сегодняшний сыр-бор загорелся в людской оттого, что днем кто-то неловко повернулся в узком проходе из буфетной и нечаянно толкнул официанта Сысоя в тот самый момент, когда он, изогнувшись, брал разбег из двери в коридор с полным подносом на правой, поднятой кверху руке. Сысой грохнул поднос, пролил суп и разбил посуду, три глубоких тарелки и одну мелкую.<br/> Сысой утверждал, что это судомойка, с нее и спрос, с нее и вычет. Теперь была ночь, одиннадцатый час, половине скоро расходиться с работы, а у них до сих пор еще шла по этому поводу перепалка.<br/> — Руки-ноги дрожат, только и забот день и ночь обнявшись с косушкой, как с женой, нос себе налакал инда как селезень, а потом зачем толкали его, побили ему посуду, пролили уху! Да кто тебя толкал, косой чорт, нечистая сила? Кто толкал тебя, грыжа астраханская, бесстыжие глаза?<br/> — Я вам сказывал, Матрена Степановна, — придерживайтесь выраженьев.<br/> — Добро бы что-нибудь стоящее, ради чего шум и посуду бить, а то какая невидаль, мадам Продам, недотрога бульварная, от хороших делов мышьяку хватила, отставная невинность. В Черногорских номерах пожили, не видали шилохвосток и кобелей.<br/> Миша и Юра похаживали по коридору перед дверью номера. Все ведь вышло не так, как предполагал Александр Александрович. Он представлял себе — виолончелист, трагедия, что-нибудь достойное и чистоплотное. А это чорт знает что. Грязь, скандальное что-то и абсолютно не для детей.<br/> Мальчики топтались в коридоре.<br/> — Вы войдите к тетеньке, молодые господа, — во второй раз неторопливым тихим голосом убеждал подошедший к мальчикам коридорный. — Вы войдите, не сумлевайтесь. Они ничего, будьте покойны. Они теперь в полной цельности. А тут нельзя стоять.<br/> Тут нынче было несчастье, кокнули дорогую посуду. Видите — услужаем, бегаем, теснота. Вы войдите.<br/> Мальчики послушались.<br/> В номере горящую керосиновую лампу вынули из резервуара, в котором она висела над обеденным столом, и перенесли за дощатую перегородку, вонявшую клопами, на другую половину номера.<br/> Там был спальный закоулок, отделенный от передней и посторонних взоров пыльной откидной портьерой. Теперь в переполохе её забывали опускать. Ее пола была закинута за верхний край перегородки. Лампа стояла в алькове на скамье.<br/> Этот угол был резко озарен снизу словно светом театральной рампы.<br/> Травились йодом, а не мышьяком, как ошибочно язвила судомойка.<br/> В номере стоял терпкий, вяжущий запах молодого грецкого ореха в неотверделой зеленой кожуре, чернеющей от прикосновения.<br/> За перегородкой девушка подтирала пол и, громко плача и свесив над тазом голову с прядями слипшихся волос, лежала на кровати мокрая от воды, слез и пота полуголая женщина.<br/> Мальчики тотчас же отвели глаза в сторону, так стыдно и непорядочно было смотреть туда. Но Юру успело поразить, как в некоторых неудобных, вздыбленных позах, под влиянием напряжения и усилий, женщина перестает быть тем, чем её изображает скульптура, и становится похожа на обнаженного борца с шарообразными мускулами в коротких штанах для состязания.<br/> Наконец-то за перегородкой догадались опустить занавеску.<br/> — Фадей Казимирович, милый, где ваша рука? Дайте мне вашу руку, — давясь от слез и тошноты, говорила женщина. — Ах, я перенесла такой ужас! У меня были такие подозрения! Фадей Казимирович… Мне вообразилось… Но по счастью оказалось, что все это глупости, мое расстроенное воображение. Фадей Казимирович, подумайте, какое облегчение! И в результате… И вот… И вот я жива.<br/> — Успокойтесь, Амалия Карловна, умоляю вас, успокойтесь.<br/> Как это все неудобно получилось, честное слово, неудобно.<br/> — Сейчас поедем домой, — буркнул Александр Александрович, обращаясь к детям.<br/> Пропадая от неловкости, они стояли в темной прихожей, на пороге неотгороженной части номера и, так как им некуда было девать глаза, смотрели в его глубину, откуда унесена была лампа. Там стены были увешаны фотографиями, стояла этажерка с нотами, письменный стол был завален бумагами и альбомами, а по ту сторону обеденного стола, покрытого вязаной скатертью, спала сидя девушка в кресле, обвив руками его спинку и прижавшись к ней щекой. Наверное, она смертельно устала, если шум и движение кругом не мешали ей спать.<br/> Их приезд был бессмыслицей, их дальнейшее присутствие здесь — неприличием.<br/> — Сейчас поедем, — еще раз повторил Александр Александрович. — Вот только Фадей Казимирович выйдет. Я прощусь с ним.<br/> Но вместо Фадея Казимировича из-за перегородки вышел кто-то другой. Это был плотный, бритый, осанистый и уверенный в себе человек. Над головою он нес лампу, вынутую из резервуара. Он прошел к столу, за которым спала девушка, и вставил лампу в резервуар. Свет разбудил девушку. Она улыбнулась вошедшему, прищурилась и потянулась.<br/> При виде незнакомца Миша весь встрепенулся и так и впился в него глазами. Он дергал Юру за рукав, пытаясь что-то сказать ему.<br/> — Как тебе не стыдно шептаться у чужих? Что о тебе подумают? — остановливал его Юра и не желал слушать.<br/> Тем временем между девушкой и мужчиной происходила немая сцена. Они не сказали друг другу ни слова и только обменивались взглядами. Но взаимное понимание их было пугающе волшебно, словно он был кукольником, а она послушною движениям его руки марионеткой.<br/> Улыбка усталости, появившаяся у нее на лице, заставляла девушку полузакрывать глаза и наполовину разжимать губы. Но на насмешливые взгляды мужчины она отвечала лукавым подмигиванием сообщницы. Оба были довольны, что все обошлось так благополучно, тайна не раскрыта и травившаяся осталась жива.<br/> Юра пожирал обоих глазами. Из полутьмы, в которой никто не мог его видеть, он смотрел не отрываясь в освещенный лампою круг. Зрелище порабощения девушки было неисповедимо таинственно и беззастенчиво откровенно. Противоречивые чувства теснились в груди у него. У Юры сжималось сердце от их неиспытанной силы.<br/> Это было то самое, о чем они так горячо год продолдонили с Мишей и Тоней под ничего не значащим именем пошлости, то пугающее и притягивающее, с чем они так легко справлялись на безопасном расстоянии на словах, и вот эта сила находилась перед Юриными глазами, досконально вещественная и смутная и снящаяся, безжалостно разрушительная и жалующаяся и зовущая на помощь, и куда девалась их детская философия и что теперь Юре делать?<br/> — Знаешь, кто этот человек? — спросил Миша, когда они вышли на улицу. Юра был погружен в свои мысли и не отвечал.<br/> — Это тот самый, который спаивал и погубил твоего отца. Помнишь, в вагоне, — я тебе рассказывал.<br/> Юра думал о девушке и будущем, а не об отце и прошлом. В первый момент он даже не понял, что говорит ему Миша. На морозе было трудно разговаривать.<br/> — Замерз, Семен? — спросил Александр Александрович. Они поехали.

