## ЧАСТЬ третья. ЕЛКА У СВЕНТИЦКИХ {-}

### 1 {-}

Как-то зимой Александр Александрович подарил Анне Ивановне старинный гардероб. Он купил его по случаю. Гардероб черного дерева был огромных размеров. Целиком он не входил ни в какую дверь. Его привезли в разобранном виде, внесли по частям в дом и стали думать, куда бы его поставить. В нижние комнаты, где было просторнее, он не годился по несоответствию назначения, а наверху не помещался вследствие тесноты. Для гардероба освободили часть верхней площадки на внутренней лестнице у входа в спальню хозяев.<br/> Собирать гардероб пришел дворник Маркел. Он привел с собой шестилетнюю дочь Маринку. Маринке дали палочку ячменного сахара. Маринка засопела носом и, облизывая леденец и заслюнявленные пальчики, насупленно смотрела на отцову работу.<br/> Некоторое время все шло как по маслу. Шкап постепенно вырастал на глазах у Анны Ивановны. Вдруг, когда только осталось наложить верх, ей вздумалось помочь Маркелу. Она стала на высокое дно гардероба и, покачнувшись, толкнула боковую стенку, державшуюся только на пазовых шипах.<br/> Распускной узел, которым Маркел стянул наскоро борта, разошелся. Вместе с досками, грохнувшимися на пол, упала на спину и Анна Ивановна и при этом больно расшиблась.<br/> — Эх, матушка-барыня, — приговаривал кинувшийся к ней Маркел, — и чего ради это вас угораздило, сердешная. Кость-то цела? Вы пощупайте кость. Главное дело кость, а мякиш наплевать, мякиш дело наживное и, как говорится, только для дамского блезиру. Да не реви ты, ирод, — напускался он на плакавшую Маринку. — Утри сопли да ступай к мамке. Эх, матушка-барыня, нужли б я без вас этой платейной антимонии не обосновал? Вот вы верно думаете, будто на первый взгляд я действительно дворник, а ежели правильно рассудить, то природная наша стать столярная, столярничали мы. Вы не поверите, что этой мебели, этих шкапов-буфетов, через наши руки прошло в смысле лака или, наоборот, какое дерево красное, какое орех. Или, например, какие, бывало, партии в смысле богатых невест так, извините за выражение, мимо носа и плывут, так и плывут. А всему причина — питейная статья, крепкие напитки.<br/> Анна Ивановна с помощью Маркела добралась до кресла, которое он ей подкатил, и села, кряхтя и растирая ушибленное место. Маркел принялся за восстановление разрушенного. Когда крышка была наложена, он сказал:<br/> — Ну, теперь только дверцы, и хоть на выставку.<br/> Анна Ивановна не любила гардероба. Видом и размерами он походил на катафалк или царскую усыпальницу. Он внушал ей суеверный ужас. Она дала гардеробу прозвище «Аскольдовой могилы». Под этим названием Анна Ивановна разумела Олегова коня, вещь, приносящую смерть своему хозяину. Как женщина беспорядочно начитанная, Анна Ивановна путала смежные понятия.<br/> С этого падения началось предрасположение Анны Ивановны к легочным заболеваниям.

