### 2 {-}

Весь ноябрь одиннадцатого года Анна Ивановна пролежала в постели. У нее было воспаление легких.<br/> Юра, Миша Гордон и Тоня весной следующего года должны были окончить университет и Высшие женские курсы. Юра кончал медиком, Тоня — юристкой, а Миша — филологом по философскому отделению.<br/> В Юриной душе все было сдвинуто и перепутано, и все резко самобытно — взгляды, навыки и предрасположения. Он был беспримерно впечатлителен, новизна его восприятий не поддавалась описанию.<br/> Но как ни велика была его тяга к искусству и истории, Юра не затруднялся выбором поприща. Он считал, что искусство не годится в призвание в том же самом смысле, как не может быть профессией прирожденная веселость или склонность к меланхолии.<br/> Он интересовался физикой, естествознанием и находил, что в практической жизни надо заниматься чем-нибудь общеполезным.<br/> Вот он и пошел по медицине.<br/> Будучи четыре года тому назад на первом курсе, он целый семестр занимался в университетском подземелье анатомией на трупах. Он по загибающейся лестнице спускался в подвал. В глубине анатомического театра группами и порознь толпились взлохмаченные студенты. Одни зубрили, обложившись костями и перелистывая трепаные, истлевшие учебники, другие молча анатомировали по углам, третьи балагурили, отпускали шутки и гонялись за крысами, в большом количестве бегавшими по каменному полу мертвецкой. В её полутьме светились, как фосфор, бросающиеся в глаза голизною трупы неизвестных, молодые самоубийцы с неустановленной личностью, хорошо сохранившиеся и еще не тронувшиеся утопленницы. Впрыснутые в них соли глинозема молодили их, придавая им обманчивую округлость. Мертвецов вскрывали, разнимали и препарировали, и красота человеческого тела оставалась верной себе при любом, сколь угодно мелком делении, так что удивление перед какой-нибудь целиком грубо брошенной на оцинкованный стол русалкою не проходило, когда переносилось с нее к её отнятой руке или отсеченной кисти. В подвале пахло формалином и карболкой, и присутствие тайны чувствовалось во всем, начиная с неизвестной судьбы всех этих простертых тел и кончая самой тайной жизни и смерти, располагавшейся здесь в подвале как у себя дома или как на своей штаб-квартире.<br/> Голос этой тайны, заглушая все остальное, преследовал Юру, мешая ему при анатомировании. Но точно так же мешало ему многое в жизни. Он к этому привык, и отвлекающая помеха не беспокоила его.<br/> Юра хорошо думал и очень хорошо писал. Он еще с гимназических лет мечтал о прозе, о книге жизнеописаний, куда бы он в виде скрытых взрывчатых гнезд мог вставлять самое ошеломляющее из того, что он успел увидать и передумать. Но для такой книги он был еще слишком молод, и вот он отделывался вместо нее писанием стихов, как писал бы живописец всю жизнь этюды к большой задуманной картине.<br/> Этим стихам Юра прощал грех их возникновения за их энергию и оригинальность. Эти два качества, энергии и оригинальности, Юра считал представителями реальности в искусствах, во всем остальном беспредметных, праздных и ненужных.<br/> Юра понимал, насколько он обязан дяде общими свойствами своего характера.<br/> Николай Николаевич жил в Лозанне. В книгах, выпущенных им там по-русски и в переводах, он развивал свою давнишнюю мысль об истории как о второй вселенной, воздвигаемой человечеством в ответ на явление смерти с помощью явлений времени и памяти.<br/> Душою этих книг было по-новому понятое христианство, их прямым следствием — новая идея искусства.<br/> Еще больше, чем на Юру, действовал круг этих мыслей на его приятеля. Под их влиянием Миша Гордон избрал своей специальностью философию. На своем факультете он слушал лекции по богословию и даже подумывал о переходе впоследствии в духовную академию.<br/> Юру дядино влияние двигало вперед и освобождало, а Мишу — сковывало. Юра понимал, какую роль в крайностях Мишиных увлечений играет его происхождение. Из бережной тактичности он не отговаривал Мишу от его странных планов. Но часто ему хотелось видеть Мишу эмпириком, более близким к жизни.

