### 3 {-}

Как-то вечером в конце ноября Юра вернулся из университета поздно, очень усталый и целый день не евши. Ему сказали, что днем была страшная тревога, у Анны Ивановны сделались судороги, съехалось несколько врачей, советовали послать за священником, но потом эту мысль оставили. Теперь ей лучше, она в сознании и велела, как только придет Юра, безотлагательно прислать его к ней.<br/> Юра послушался и, не переодеваясь, прошел в спальню.<br/> Комната носила следы недавнего переполоха. Сиделка бесшумными движениями перекладывала что-то на тумбочке. Кругом валялись скомканные салфетки и сырые полотенца из-под компрессов. Вода в полоскательнице была слегка розовата от сплюнутой крови. В ней валялись осколки стеклянных ампул с отломанными горлышками и взбухшие от воды клочки ваты.<br/> Больная плавала в поту и кончиком языка облизывала сухие губы. Она резко осунулась с утра, когда Юра видел её в последний раз.<br/> — Не ошибка ли в диагнозе? — подумал он. — Все признаки крупозного. Кажется, это кризис. Поздоровавшись с Анною Ивановной и сказав что-то ободряюще пустое, что говорится всегда в таких случаях, он выслал сиделку из комнаты. Взяв Анну Ивановну за руку, чтобы сосчитать пульс, он другой рукой полез в тужурку за стетоскопом. Движением головы Анна Ивановна показала, что это лишнее. Юра понял, что ей нужно от него что-то другое. Собравшись с силами, Анна Ивановна заговорила:<br/> — Вот, исповедывать хотели… Смерть нависла… Может каждую минуту… Зуб идешь рвать, боишься, больно, готовишься… А тут не зуб, всю, всю тебя, всю жизнь… хруп, и вон, как щипцами… А что это такое?.. Никто не знает… И мне тоскливо и страшно.<br/> Анна Ивановна замолчала. Слезы градом катились у нее по щекам. Юра ничего не говорил. Через минуту Анна Ивановна продолжала:<br/> — Ты талантливый… А талант, это… не как у всех… Ты должен что-то знать… Скажи мне что-нибудь… Успокой меня.<br/> — Ну что же мне сказать, — ответил Юра, беспокойно заерзал по стулу, встал, прошелся и снова сел. — Во-первых, завтра вам станет лучше — есть признаки, даю вам голову на отсечение. А затем — смерть, сознание, вера в воскресение…<br/> Вы хотите знать мое мнение естественника? Может быть, как-нибудь в другой раз? Нет? Немедленно? Ну как знаете.<br/> Только это ведь трудно так, сразу.<br/> И он прочел ей экспромтом целую лекцию, сам удивляясь, как это у него вышло.<br/> — Воскресение. В той грубейшей форме, как это утверждается для утешения слабейших, это мне чуждо. И слова Христа о живых и мертвых я понимал всегда по-другому. Где вы разместите эти полчища, набранные по всем тысячелетиям? Для них не хватит вселенной, и Богу, добру и смыслу придется убраться из мира.<br/> Их задавят в этой жадной животной толчее.<br/> Но все время одна и та же необъятно тождественная жизнь наполняет вселенную и ежечасно обновляется в неисчислимых сочетаниях и превращениях. Вот вы опасаетесь, воскреснете ли вы, а вы уже воскресли, когда родились, и этого не заметили.<br/> Будет ли вам больно, ощущает ли ткань свой распад? То есть, другими словами, что будет с вашим сознанием? Но что такое сознание? Рассмотрим. Сознательно желать уснуть — верная бессонница, сознательная попытка вчувствоваться в работу собственного пищеварения — верное расстройство его иннервации. Сознание яд, средство самоотравления для субъекта, применяющего его на самом себе. Сознание — свет, бьющий наружу, сознание освещает перед нами дорогу, чтоб не споткнуться. Сознание это зажженные фары впереди идущего паровоза. Обратите их светом внутрь и случится катастрофа.<br/> Итак, что будет с вашим сознанием? Вашим. Вашим. А что вы такое? В этом вся загвоздка. Разберемся. Чем вы себя помните, какую часть сознавали из своего состава? Свои почки, печень, сосуды? Нет, сколько ни припомните, вы всегда заставали себя в наружном, деятельном проявлении, в делах ваших рук, в семье, в других. А теперь повнимательнее. Человек в других людях и есть душа человека. Вот что вы есть, вот чем дышало, питалось, упивалось всю жизнь ваше сознание. Вашей душою, вашим бессмертием, вашей жизнью в других. И что же? В других вы были, в других и останетесь. И какая вам разница, что потом это будет называться памятью. Это будете вы, вошедшая в состав будущего.<br/> Наконец, последнее. Не о чем беспокоиться. Смерти нет.<br/> Смерть не по нашей части. А вот вы сказали талант, это другое дело, это наше, это открыто нам. А талант — в высшем широчайшем понятии есть дар жизни.<br/> Смерти не будет, говорит Иоанн Богослов, и вы послушайте простоту его аргументации. Смерти не будет, потому что прежнее прошло. Это почти как: смерти не будет, потому что это уже видали, это старо и надоело, а теперь требуется новое, а новое есть жизнь вечная.<br/> Он расхаживал по комнате, говоря это. «Усните», — сказал он, подойдя к кровати и положив руки на голову Анны Ивановны.<br/> Прошло несколько минут. Анна Ивановна стала засыпать.<br/> Юра тихо вышел из комнаты и сказал Егоровне, чтобы она послала в спальню сиделку. — Чорт знает что, — думал он, — я становлюсь каким-то шарлатаном. Заговариваю, лечу наложением рук. На другой день Анне Ивановне стало лучше.

