### 4 {-}

Анне Ивановне становилось все легче и легче. В середине декабря она попробовала встать, но была еще очень слаба. Ей советовали хорошенько вылежаться.<br/> Она часто посылала за Юрой и Тонею и часами рассказывала им о своем детстве, проведенном в дедушкином имении Варыкине, на уральской реке Рыньве. Юра и Тоня никогда там не бывали, но Юра легко со слов Анны Ивановны представлял себе эти пять тысяч десятин векового, непроходимого леса, черного как ночь, в который в двух-трех местах вонзается, как бы пырнув его ножом своих изгибов, быстрая река с каменистым дном и высокими кручами по Крюгеровскому берегу.<br/> Юре и Тоне в эти дни шили первые в их жизни выходные платья, Юре — черную сюртучную пару, а Тоне — вечерний туалет из светлого атласа с чуть-чуть открытой шеей. Они собирались обновить эти наряды двадцать седьмого, на традиционной ежегодной елке у Свентицких.<br/> Заказ из мужской мастерской и от портнихи принесли в один день. Юра и Тоня примерили, остались довольны и не успели снять обнов, как пришла Егоровна от Анны Ивановны и сказала, что она зовет их. Как были в новых платьях, Юра и Тоня прошли к Анне Ивановне.<br/> При их появлении она поднялась на локте, посмотрела на них сбоку, велела повернуться и сказала:<br/> — Очень хорошо. Просто восхитительно. Я совсем не знала, что уже готово. А ну-ка, Тоня, еще раз. Нет, ничего. Мне показалось, что мысок немного морщит. Знаете, зачем я вас звала? Но сначала несколько слов о тебе, Юра.<br/> — Я знаю, Анна Ивановна. Я сам велел показать вам это письмо. Вы, как Николай Николаевич, считаете, что мне не надо было отказываться. Минуту терпения. Вам вредно разговаривать.<br/> Сейчас я вам все объясню. Хоть ведь и вам все это хорошо известно.<br/> Итак, во-первых. Есть дело о Живаговском наследстве для прокормления адвокатов и взимания судебных издержек, но никакого наследства в действительности не существует, одни долги и путаница, да еще грязь, которая при этом всплывает.<br/> Если бы что-нибудь можно было обратить в деньги, неужто же я подарил бы их суду и ими не воспользовался? Но в том-то и дело, что тяжба — дутая, и чем во всем этом копаться, лучше было отступиться от своих прав на несуществующее имущество и уступить его нескольким подставным соперникам и завистливым самозванцам. О посягательствах некоей Madame Alice, проживающей с детьми под фамилией Живаго в Париже, я слышал давно. Но прибавились новые притязания, и не знаю, как вы, но мне все это открыли совсем недавно.<br/> Оказывается, еще при жизни мамы отец увлекался одной мечтательницей и сумасбродкой, княгиней Столбуновой-Энрици. У этой особы от отца есть мальчик, ему теперь десять лет, его зовут Евграф.<br/> Княгиня — затворница. Она безвыездно живет с сыном в своем особняке на окраине Омска на неизвестные средства. Мне показывали фотографию особняка. Красивый пятиоконный дом с цельными окнами и лепными медальонами по карнизу. И вот все последнее время у меня такое чувство, будто своими пятью окнами этот дом недобрым взглядом смотрит на меня через тысячи верст, отделяющие Европейскую Россию от Сибири, и рано или поздно меня сглазит. Так на что мне это все: выдуманные капиталы, искусственно созданные соперники, их недоброжелательство и зависть? И адвокаты.<br/> — И все-таки не надо было отказываться, — возразила Анна Ивановна. — Знаете, зачем я вас звала, — снова повторила она и тут же продолжала:<br/> — Я вспомнила его имя. Помните, я вчера про лесника рассказывала? Его звали Вакх. Не правда ли, бесподобно? Черное лесное страшилище, до бровей заросшее бородой, и — Вакх! Он был с изуродованным лицом, его медведь драл, но он отбился. И там все такие. С такими именами. Односложными. Чтобы было звучно и выпукло. Вакх. Или Лупп. Или, предположим, Фавст. Слушайте, слушайте. Бывало, доложат что-нибудь такое. Авкт или там Фрол какой-нибудь, как залп из обоих дедушкиных охотничьих стволов, и мы гурьбой моментально шмыг из детской на кухню. А там, можете себе представить, лесовик-угольщик с живым медвежонком или обходчик с дальнего кордона с пробой ископаемого. И дедушка всем по записочке. В контору. Кому денег, кому крупы, кому оружейных припасов. И лес перед окнами. А снегу, снегу! Выше дома! — Анна Ивановна закашлялась.<br/> — Перестань, мама, тебе вредно так, — предостерегла Тоня.<br/> Юра поддержал ее.<br/> — Ничего. Ерунда. Да, кстати. Егоровна насплетничала, будто бы вы сомневаетесь, ехать ли вам послезавтра на елку.<br/> Чтобы я больше этих глупостей не слышала! Как вам не стыдно. И какой ты, Юра, после этого врач? Итак, решено. Вы едете без разговоров. Но вернемся к Вакху. Этот Вакх был в молодости кузнецом. Ему в драке отбили внутренности. Он сделал себе другие, из железа. Какой ты чудак, Юра. Неужели я не понимаю? Понятно, не буквально. Но так народ говорил.<br/> Анна Ивановна снова закашлялась, на этот раз гораздо дольше. Приступ не проходил. Она все не могла продышаться.<br/> Юра и Тоня подбежали к ней в одну и ту же минуту. Они стали плечом к плечу у её постели. Продолжая кашлять, Анна Ивановна схватила их соприкоснувшиеся руки в свои и некоторое время продержала соединенными. Потом, овладев голосом и дыханием, сказала:<br/> — Если я умру, не расставайтесь. Вы созданы друг для друга. Поженитесь. Вот я и сговорила вас, — прибавила она и заплакала.

