### 5 {-}

Уже весной тысяча девятьсот шестого года, перед переходом в последний класс гимназии, шесть месяцев её связи с Комаровским превысили меру Лариного терпения. Он очень ловко пользовался её подавленностью, и когда ему бывало нужно, не показывая этого, тонко и незаметно напоминал ей о её поругании. Эти напоминания приводили Лару в то именно смятение, которое требуется сластолюбцу от женщины. Смятение это отдавало Лару во все больший плен чувственного кошмара, от которого у нее вставали волосы дыбом при отрезвлении. Противоречия ночного помешательства были необъяснимы, как чернокнижие. Тут все было шиворот-навыворот и противно логике, острая боль заявляла о себе раскатами серебряного смешка, борьба и отказ означали согласие, и руку мучителя покрывали поцелуями благодарности.<br/> Казалось, этому не будет конца, но весной, на одном из последних уроков учебного года, задумавшись о том, как участятся эти приставания летом, когда не будет занятий в гимназии, последнего Лариного прибежища против частых встреч с Комаровским, Лара быстро пришла к решению, надолго изменившему её жизнь.<br/> Было жаркое утро, собиралась гроза. В классе занимались при открытых окнах. Вдалеке гудел город, все время на одной ноте, как пчелы на пчельнике. Со двора доносился крик играющих детей. От травянистого запаха земли и молодой зелени болела голова, как на масленице от водки и блинного угара.<br/> Учитель истории рассказывал о Египетской экспедиции Наполеона. Когда он дошел до высадки во Фрежюсе, небо почернело, треснуло и раскололось молнией и громом, и в класс через окна вместе с запахом свежести ворвались столбы песку и пыли. Две школьные подлизы услужливо кинулись в коридор звать дядьку закрывать окна, и когда они отворили дверь, сквозняк поднял и понес со всех парт по классу промокашки из тетрадей.<br/> Окна закрыли. Хлынул грязный городской ливень, перемешанный с пылью. Лара вырвала листок из записной тетради и написала соседке по парте, Наде Кологривовой:<br/> «Надя, мне нужно устроить жизнь отдельно от мамы. Помоги мне найти несколько уроков повыгоднее. У вас много знакомств среди богатых».<br/> Надя ответила тем же способом:<br/> «Липе ищут воспитательницу. Поступи к нам. Вот было бы здорово! Ты ведь знаешь, как тебя любят папа и мама».

