### 6 {-}

Больше трех лет Лара прожила у Кологривовых как за каменной стеной. Ниоткуда на нее не покушались, и даже мать и брат, к которым она чувствовала большое отчуждение, не напоминали ей о себе.<br/> Лаврентий Михайлович Кологривов был крупный предприниматель-практик новейшей складки, талантливый и умный. Он ненавидел отживающий строй двойной ненавистью: баснословного, способного откупить государственную казну богача и сказочно далеко шагнувшего выходца из простого народа. Он прятал у себя нелегальных, нанимал обвиняемым на политических процессах защитников и, как уверяли в шутку, субсидируя революцию, сам свергал себя как собственника и устраивал забастовки на своей собственной фабрике. Лаврентий Михайлович был меткий стрелок и страстный охотник и зимой в девятьсот пятом году ездил по воскресеньям в Серебряный бор и на Лосиный остров обучать стрельбе дружинников.<br/> Это был замечательный человек. Серафима Филипповна, его жена, была ему достойной парой. Лара питала к обоим восхищенное уважение. Все в доме любили её как родную.<br/> На четвертый год Лариной беззаботности к ней пришел по делу братец Родя. Фатовато покачиваясь на длинных ногах и для пущей важности произнося слова в нос и неестественно растягивая их, он рассказал ей, что юнкера его выпуска собрали деньги на прощальный подарок начальнику училища, дали их Роде и поручили ему приискать и приобрести подарок. И вот эти деньги третьего дня он проиграл до копейки. Сказав это, Родя плюхнулся всей долговязой своей фигурой в кресло и заплакал.<br/> Лара похолодела, когда это услышала. Всхлипывая, Родя продолжал:<br/> — Вчера я был у Виктора Ипполитовича. Он отказался говорить со мной на эту тему, но сказал, что если бы ты пожелала… Он говорит, что, хотя ты разлюбила всех нас, твоя власть над ним еще так велика… Ларочка… Достаточно одного слова… Понимаешь ли ты, какой это позор и как это затрагивает честь юнкерского мундира?.. Сходи к нему, чего тебе стоит, попроси его… Ведь ты не допустишь, чтобы я смыл эту растрату своей кровью.<br/> — Смыл кровью… Честь юнкерского мундира, — с возмущением повторяла Лара, взволнованно расхаживая по комнате. — А я не мундир, у меня чести нет, и со мной можно делать что угодно. Понимаешь ли ты, о чем просишь, вник ли в то, что он предлагает тебе? Год за годом, сизифовыми трудами строй, возводи, недосыпай, а этот пришел, и ему все равно, что он дунет, плюнет и все разлетится вдребезги! Да ну тебя к чорту. Стреляйся, пожалуйста. Какое мне дело? Сколько тебе надо?<br/> — Шестьсот девяносто с чем-то рублей, скажем для ровного счета семьсот, — немного замявшись, сказал Родя.<br/> — Родя! Нет, ты с ума сошел! Соображаешь ли ты, что говоришь? Ты проиграл семьсот рублей? Родя! Родя! Знаешь ли ты, в какой срок обыкновенный человек, вроде меня, может честным трудом выколотить такую сумму?<br/> После некоторой паузы она прибавила, холодно и отчужденно:<br/> — Хорошо. Я попробую. Приходи завтра. И принеси с собой револьвер, из которого ты хотел застрелиться. Ты передашь его мне в мою собственность. С хорошим запасом патронов, помни.<br/> Эти деньги она достала у Кологривова.

