### 7 {-}

Служба у Кологривовых не помешала Ларе окончить гимназию, поступить на курсы, успешно пройти их и приблизиться к их окончанию, которое ей предстояло в будущем тысяча девятьсот двенадцатом году.<br/> Весной одиннадцатого кончила гимназию её питомица Липочка.<br/> У нее уже был жених, молодой инженер Фризенданк, из хорошей и состоятельной семьи. Родители одобряли Липочкин выбор, но были против того, чтобы она вступала в брак так рано, и советовали ей подождать. На этой почве происходили драмы. Избалованная и взбалмошная Липочка, любимица семьи, кричала на отца и мать, плакала и топала ногами.<br/> В богатом доме, где Лару считали родною, не помнили долга, сделанного ею для Роди, и о нем не напоминали.<br/> Этот долг Лара давным-давно вернула бы, если бы у нее не было постоянных расходов, назначение которых она скрывала.<br/> Она тайно от Паши посылала деньги его отцу, ссыльнопоселенцу Антипову, и помогала его часто хворавшей сварливой матери. Кроме того она под еще большим секретом сокращала расходы самого Паши, без его ведома приплачивая его квартирным хозяевам за его стол и комнату.<br/> Паша, бывший немного моложе Лары, любил её до безумия и во всем слушался. По её настояниям он по окончании реального засел за дополнительные латынь и греческий, чтобы попасть в университет филологом. Лара мечтала через год, когда они сдадут государственные, обвенчаться с Пашею и уехать, он — учителем мужской, а она — учительницей женской гимназии на службу в какой-нибудь из губернских городов Урала.<br/> Паша жил в комнате, которую Лара сама приискала и сняла ему у тихих квартирохозяев в новоотстроенном доме по Камергерскому, близ Художественного театра.<br/> Летом одиннадцатого года Лара в последний раз побывала с Кологривовыми в Дуплянке. Она любила это место до самозабвения, больше самих хозяев. Это хорошо знали, и относительно Лары существовал на случай этих летних поездок такой неписаный уговор. Когда привозивший их жаркий и черномазый поезд уходил дальше, и среди воцарившейся безбрежно-обалделой и душистой тишины взволнованная Лара лишалась дара речи, её отпускали одну пешком в имение, пока с полустанка таскали и клали на телегу багаж, а дуплянский кучер в безрукавом ямском казакине с выпущенными в проймы рукавами красной рубахи рассказывал господам, садившимся в коляску, местные новости истекшего сезона.<br/> Лара шла вдоль полотна по тропинке, протоптанной странниками и богомольцами, и сворачивала на луговую стежку, ведшую к лесу. Тут она останавливалась и, зажмурив глаза, втягивала в себя путано-пахучий воздух окрестной шири. Он был роднее отца и матери, лучше возлюбленного и умнее книги. На одно мгновение смысл существования опять открывался Ларе. Она тут, — постигала она, — для того, чтобы разобраться в сумасшедшей прелести земли и все назвать по имени, а если это будет ей не по силам, то из любви к жизни родить преемников, которые это сделают вместо нее.<br/> В это лето Лара приехала переутомленною от черезмерных трудов, которые она на себя взвалила. Она легко расстраивалась. В ней развилась мнительность, ранее ей не свойственная. Эта черта мельчила Ларин характер, который всегда отличала широта и отсутствие щепетильности.<br/> Кологривовы не отпускали ее. Она была окружена у них прежнею лаской. Но с тех пор как Липа стала на ноги, Лара считала себя в этом доме лишнею. Она отказывалась от жалованья. Ей его навязывали. Вместе с тем деньги требовались ей, а заниматься на звании гостьи самостоятельным заработком было неловко и практически неисполнимо.<br/> Лара считала свое положение ложным и невыносимым. Ей казалось, что все тяготятся ею и только не показывают. Она сама была в тягость себе. Ей хотелось бежать куда глаза глядят от себя самой и Кологривовых, но по понятиям Лары до этого надо было вернуть Кологривовым деньги, а взять их в данное время ей было неоткуда. Она чувствовала себя заложницей по вине этой глупой Родькиной растраты и не находила себе места от бессильного возмущения.<br/> Во всем ей чудились признаки небрежности. Оказывали ли ей повышенное внимание наезжавшие к Кологривовым знакомые, это значило, что к ней относятся как к безответной «воспитаннице» и легкой добыче. А когда её оставляли в покое, это доказывало, что её считают пустым местом и не замечают.<br/> Приступы ипохондрии не мешали Ларе разделять увеселения многочисленного общества, гостившего в Дуплянке. Она купалась и плавала, каталась на лодке, участвовала в ночных пикниках за реку, пускала вместе со всеми фейерверки и танцевала. Она играла в любительских спектаклях и с особенным увлечением состязалась в стрельбе в цель из коротких маузерных ружей, которым, однако, предпочитала легкий Родин револьвер. Она пристрелялась из него до большой меткости и в шутку жалела, что она женщина и ей закрыт путь дуэлянта-бретера. Но чем больше веселилась Лара, тем ей становилось хуже. Она сама не знала, чего хочет.<br/> Особенно это усилилось по возвращении в город. Тут к Лариным неприятностям примешались легкие размолвки с Пашею (серьезно ссориться с ним Лара остерегалась, потому что считала его своею последнею защитой). У Паши за последнее время появилась некоторая самоуверенность. Наставительные нотки в его разговоре смешили и огорчали Лару.<br/> Паша, Липа, Кологривовы, деньги — все это завертелось в голове у ней. Жизнь опротивела Ларе. Она стала сходить с ума.<br/> Ее тянуло бросить все знакомое и испытанное и начать что-то новое. В этом настроении она на Рождестве девятьсот одиннадцатого года пришла к роковому решению. Она решила немедленно расстаться с Кологривовыми и построить свою жизнь как-нибудь одиноко и независимо, а деньги, нужные для этого, попросить у Комаровского. Ларе казалось, что после всего случившегося и последовавших за этим лет её отвоеванной свободы он должен помочь ей по-рыцарски, не вступая ни в какие объяснения, бескорыстно и без всякой грязи.<br/> С этой целью она двадцать седьмого декабря вечером отправилась в Петровские линии и, уходя, положила в муфту заряженный Родин револьвер на спущенном предохранителе с намерением стрелять в Виктора Ипполитовича, если он ей откажет, превратно поймет или как-нибудь унизит.<br/> Она шла в страшном смятении по праздничным улицам и ничего кругом не замечала. Задуманный выстрел уже грянул в её душе, в совершенном безразличии к тому, в кого он был направлен. Этот выстрел был единственное, что она сознавала. Она его слышала всю дорогу, и это был выстрел в Комаровского, в себя самое, в свою собственную судьбу и в дуплянский дуб на лужайке с вырезанной в его стволе стрелковою мишенью.

