### 8 {-}

— Не трогайте муфты, — сказала она охавшей и ахавшей Эмме Эрнестовне, когда та протянула к Ларе руки, чтобы помочь ей раздеться.<br/> Виктора Ипполитовича не оказалось дома. Эмма Эрнестовна продолжала уговаривать Лару войти и снять шубку.<br/> — Я не могу. Я тороплюсь. Где он?<br/> Эмма Эрнестована сказала, что он в гостях на елке. С адресом в руках Лара сбежала по мрачной, живо ей все напомнившей лестнице с цветными гербами на окнах и направилась в Мучной городок к Свентицким.<br/> Только теперь, во второй раз выйдя на улицу, Лара толком осмотрелась по сторонам. Была зима. Был город. Был вечер.<br/> Была ледяная стужа. Улицы покрывал черный лед, толстый, как стеклянные донышки битых пивных бутылок. Было больно дышать.<br/> Воздух забит был серым инеем, и казалось, что он щекочет и покалывает своею косматою щетиной точно так же, как шерстил и лез Ларе в рот седой мех её обледенелой горжетки. С колотящимся сердцем Лара шла по пустым улицам. По дороге дымились двери чайных и харчевен. Из тумана выныривали обмороженные лица прохожих, красные, как колбаса, и бородатые морды лошадей и собак в ледяных сосульках. Покрытые толстым слоем льда и снега окна домов точно были замазаны мелом, и по их непрозрачной поверхности двигались цветные отсветы зажженных елок и тени веселящихся, словно людям на улице показывали из домов туманные картины на белых, развешанных перед волшебным фонарем простынях.<br/> В Камергерском Лара остановилась. — Я больше не могу, я не выдержу, — почти вслух вырвалось у ней. — Я подымусь и все расскажу ему, — овладев собою, подумала она, отворяя тяжелую дверь представительного подъезда.

