### 9 {-}

Красный от натуги Паша, подперев щеку языком, бился перед зеркалом, надевая воротник и стараясь проткнуть подгибающуюся запонку в закрахмаленные петли манишки. Он собирался в гости и был еще так чист и неискушен, что растерялся, когда Лара, войдя без стука, застала его с таким небольшим недочетом в костюме. Он сразу заметил её волнение. У нее подкашивались ноги. Она вошла, шагами расталкивая свое платье, словно переходя его вброд.<br/> — Что с тобой? Что случилось? — спросил он в тревоге, подбежав к ней навстречу.<br/> — Сядь рядом. Садись такой, как ты есть. Не принаряжайся.<br/> Я тороплюсь. Мне надо будет сейчас уйти. Не трогай муфты.<br/> Погоди. Отвернись на минуту.<br/> Он послушался. На Ларе был английский костюм. Она сняла жакет, повесила его на гвоздь и переложила Родин револьвер из муфты в карман жакета. Потом, вернувшись на диван, сказала:<br/> — Теперь можешь смотреть. Зажги свечу и потуши электричество.<br/> Лара любила разговаривать в полумраке при зажженных свечах.<br/> Паша всегда держал для нее про запас их нераспечатанную пачку.<br/> Он сменил огарок в подсвечнике на новую целую свечу, поставил на подоконник и зажег ее. Пламя захлебнулось стеарином, постреляло во все стороны трескучими звездочками и заострилось стрелкой. Комната наполнилась мягким светом. Во льду оконного стекла на уровне свечи стал протаивать черный глазок.<br/> — Слушай, Патуля, — сказала Лара. — У меня затруднения.<br/> Надо помочь мне выбраться из них. Не пугайся и не расспрашивай меня, но расстанься с мыслью, что мы, как все. Не оставайся спокойным. Я всегда в опасности. Если ты меня любишь и хочешь удержать меня от гибели, не надо откладывать, давай обвенчаемся скорее.<br/> — Но это мое постоянное желание, — перебил он ее. — Скорее назначай день, я рад в любой, какой ты захочешь. Но скажи мне проще и яснее, что с тобой, не мучай меня загадками.<br/> Но Лара отвлекла его в сторону, незаметно уклонившись от прямого ответа. Они еще долго разговаривали на темы, не имевшие никакого отношения к предмету Лариной печали.

