### 10 {-}

Этой зимою Юра писал свое ученое сочинение о нервных элементах сетчатки на соискание университетской золотой медали. Хотя Юра кончил по общей терапии, глаз он знал с доскональностью будущего окулиста.<br/> В этом интересе к физиологии зрения сказались другие стороны Юриной природы — его творческие задатки и его размышления о существе художественного образа и строении логической идеи.<br/> Тоня и Юра ехали в извозчичьих санках на елку к Свентицким.<br/> Оба прожили шесть лет бок о бок начало отрочества и конец детства. Они знали друг друга до мельчайших подробностей. У них были общие привычки, своя манера перекидываться короткими остротами, своя манера отрывисто фыркать в ответ. Так и ехали они сейчас, отмалчиваясь, сжав губы на холоде и обмениваясь короткими замечаниями. И думали каждый о своем.<br/> Юра вспоминал, что приближаются сроки конкурса и надо торопиться с сочинением, и в праздничной суматохе кончающегося года, чувствовавшейся на улицах, перескакивал с этих мыслей на другие.<br/> На гордоновском факультете издавали студенческий гектографированный журнал, Гордон был его редактором. Юра давно обещал им статью о Блоке. Блоком бредила вся молодежь обеих столиц, и они с Мишею больше других.<br/> Но и эти мысли ненадолго задерживались в Юрином сознании.<br/> Они ехали, уткнув подбородки в воротники и растирая отмороженные уши, и думали о разном. Но в одном их мысли сходились.<br/> Недавняя сцена у Анны Ивановны обоих переродила. Они словно прозрели и взглянули друг на друга новыми глазами.<br/> Тоня, этот старинный товарищ, эта понятная, не требующая объяснений очевидность, оказалась самым недосягаемым и сложным из всего, что мог себе представить Юра, оказалась женщиной.<br/> При некотором усилии фантазии Юра мог вообразить себя взошедшим на Арарат героем, пророком, победителем, всем чем угодно, но только не женщиной.<br/> И вот эту труднейшую и все превосходящую задачу взяла на свои худенькие и слабые плечи Тоня (она с этих пор вдруг стала казаться Юре худой и слабой, хотя была вполне здоровой девушкой). И он преисполнился к ней тем горячим сочувствием и робким изумлением, которое есть начало страсти.<br/> То же самое, с соответствующими изменениями, произошло по отношению к Юре с Тоней.<br/> Юра думал, что напрасно все-таки они уехали из дому. Как бы чего-нибудь не случилось в их отсутствие. И он вспомнил.<br/> Узнав, что Анне Ивановне хуже, они, уже одетые к выезду, прошли к ней и предложили, что останутся. Она с прежней резкостью восстала против этого и потребовала, чтобы они ехали на елку. Юра и Тоня зашли за гардину в глубокую оконную нишу посмотреть, какая погода. Когда они вышли из ниши, оба полотнища тюлевой занавеси пристали к необношенной материи их новых платьев. Легкая льнущая ткань несколько шагов проволоклась за Тонею, как подвенечная фата за невестой. Все рассмеялись, так одновременно без слов всем в спальне бросилось в глаза это сходство.<br/> Юра смотрел по сторонам и видел то же самое, что незадолго до него попадалось на глаза Ларе. Их сани поднимали неестественно громкий шум, пробуждавший неестественно долгий отзвук под обледенелыми деревьями в садах и на бульварах.<br/> Светящиеся изнутри и заиндевелые окна домов походили на драгоценные ларцы из дымчатого слоистого топаза. Внутри них теплилась святочная жизнь Москвы, горели елки, толпились гости и играли в прятки и колечко дурачащиеся ряженые.<br/> Вдруг Юра подумал, что Блок это явление Рождества во всех областях русской жизни, в северном городском быту и в новейшей литературе, под звездным небом современной улицы и вокруг зажженной елки в гостиной нынешнего века. Он подумал, что никакой статьи о Блоке не надо, а просто надо написать русское поклонение волхвов, как у голландцев, с морозом, волками и темным еловым лесом.<br/> Они проезжали по Камергерскому. Юра обратил внимание на черную протаявшую скважину в ледяном наросте одного из окон.<br/> Сквозь эту скважину просвечивал огонь свечи, проникавший на улицу почти с сознательностью взгляда, точно пламя подсматривало за едущими и кого-то поджидало.<br/> «Свеча горела на столе. Свеча горела…» — шептал Юра про себя начало чего-то смутного неоформившегося, в надежде, что продолжение придет само собой, без принуждения. Оно не приходило.

