### 11 {-}

С незапамятных времен елки у Свентицких устраивали по такому образцу. В десять, когда разъезжалась детвора, зажигали вторую для молодежи и взрослых, и веселились до утра. Более пожилые всю ночь резались в карты в трехстенной помпейской гостиной, которая была продолжением зала и отделялась от него тяжелою плотною занавесью на больших бронзовых кольцах. На рассвете ужинали всем обществом.<br/> — Почему вы так поздно? — на бегу спросил их племянник Свентицких Жорж, пробегая через переднюю внутрь квартиры к дяде и тете. Юра и Тоня тоже решили пройти туда поздороваться с хозяевами и мимоходом, раздеваясь, посмотрели в зал.<br/> Мимо жарко дышащей елки, опоясанной в несколько рядов струящимся сиянием, шурша платьями и наступая друг другу на ноги,двигалась черная стена прогуливающихся и разговаривающих, не занятых танцами.<br/> Внутри круга бешено вертелись танцующие. Их кружил, соединял в пары и вытягивал цепью сын товарища прокурора лицеист Кока Корнаков. Он дирижировал танцами и во все горло орал с одного конца зала на другой: «Grand rond! Chaine chinoise!»2— и все делалось по его слову. «Une valse s’il vous plait!»3— горланил он таперу и в голове первого тура вел свою даму a trois temps, a deux temps4все замедляя и суживая разбег до еле заметного переступают на одном месте, которое уже не было вальсом, а только его замирающим отголоском. И все аплодировали, и эту движущуюся, шаркающую и галдящую толпу обносили мороженым и прохладительными.<br/> Разгоряченные юноши и девушки на минуту переставали кричать и смеяться, торопливо и жадно глотали холодный морс и лимонад и, едва поставив бокал на поднос, возобновляли крик и смех в удесятеренной степени, словно хватив какого-то веселящего состава.<br/> Не заходя в зал, Тоня и Юра прошли к хозяевам на зады квартиры.

### 12 {-}

Внутренние комнаты Свентицких были загромождены лишними вещами, вынесенными из гостиной и зала для большего простора.<br/> Тут была волшебная кухня хозяев, их святочный склад. Здесь пахло краской и клеем, лежали свертки цветной бумаги и были грудами наставлены коробки с котильонными звездами и запасными елочными свечами.<br/> Старики Свентицкие расписывали номерки к подаркам, карточки с обозначением места за ужином и билетики к какой-то предполагавшейся лотерее. Им помогал Жорж, но часто сбивался в нумерации, и они раздраженно ворчали на него. Свентицкие страшно обрадовались Юре и Тоне. Они их помнили маленькими, не церемонились с ними и без дальних слов усадили за эту работу.<br/> — Фелицата Семеновна не понимает, что об этом надо было думать раньше, а не в самый разгар, когда гости. Ах ты Параскева-путаница, что ты, Жорж, опять натворил с номерами!<br/> Уговор был бонбоньерки с драже на стол, а пустые — на диван, а у вас опять шалды-балды и все шиворот-навыворот.<br/> — Я очень рада, что Анете лучше. Мы с Пьером так за нее беспокоились.<br/> — Да, но, милочка, ей как раз хуже, хуже, понимаешь, а у тебя всегда все dewant-derriere5.<br/> Юра и Тоня полвечера проторчали с Жоржем и стариками за их елочными кулисами.

