### 13 {-}

Все то время, что они сидели со Свентицкими, Лара была в зале. Хотя она была одета не по-бальному и никого тут не знала, она то давала безвольно, как во сне, кружить себя Коке Корнакову, то, как в воду опущенная, без дела слонялась кругом по залу.<br/> Лара уже один или два раза в нерешительности останавливалась и мялась на пороге гостиной, в надежде на то, что сидевший лицом к залу Комаровский заметит ее. Но он глядел в свои карты, которые держал в левой руке щитком перед собой, и либо действительно не видел ее, либо притворялся, что не замечает. У Лары дух захватило от обиды. В это время из зала в гостиную вошла незнакомая Ларе девушка. Комаровский посмотрел на вошедшую тем взглядом, который Лара так хорошо знала.<br/> Польщенная девушка улыбнулась Комаровскому, вспыхнула и просияла. При виде этого Лара чуть не вскрикнула. Краска стыда густо залила ей лицо, у нее покраснели лоб и шея. «Новая жертва», — подумала она. Лара увидела как в зеркале всю себя и всю свою историю. Но она еще не отказалась от мысли поговорить с Комаровским и, решив отложить попытку до более удобной минуты, заставила себя успокоиться и вернулась в зал.<br/> С Комаровским за одним столом играло еще три человека. Один из его партнеров, который сидел рядом с ним, был отец щеголя лицеиста, пригласившего Лару на вальс. Об этом Лара заключила из двух-трех слов, которыми она перекинулась с кавалером, кружась с ним по залу. А высокая брюнетка в черном с шалыми горящими глазами и неприятно по-змеиному напруженной шеей, которая поминутно переходила то из гостинной в зал на поле сыновней деятельности, то назад в гостиную к игравшему мужу, была мать Коки Корнакова. Наконец, случайно выяснилось, что девушка, подавшая повод к сложным Лариным чувствованиям, сестра Коки, и Ларины сближения не имели под собой никакой почвы.<br/> — Корнаков, — представился Кока Ларе в самом начале. Но тогда она не разобрала. — Корнаков, — повторил он на последнем скользящем кругу, подведя её к креслу, и откланялся.<br/> На этот раз Лара расслышала. — Корнаков, Корнаков, — призадумалась она. — Что-то знакомое. Что-то неприятное.<br/> Потом она вспомнила. Корнаков — товарищ прокурора московской судебной палаты. Он обвинял группу железнодорожников, вместе с которыми судился Тиверзин. Лаврентий Михайлович по Лариной просьбе ездил его умасливать, чтобы он не так неистовствовал на этом процессе, но не уломал. — Так вот оно что! Так, так, так. Любопытно. Корнаков. Корнаков.

### 14 {-}

Был первый или второй час ночи. У Юры стоял шум в ушах.<br/> После перерыва, в течение которого в столовой пили чай с птифурами, танцы возобновились. Когда свечи на елке догорали, их уже больше никто не сменял.<br/> Юра стоял в рассеянности посреди зала и смотрел на Тоню, танцевавшую с кем-то незнакомым. Проплывая мимо Юры, Тоня движением ноги откидывала небольшой трен слишком длинного атласного платья и, плеснув им, как рыбка, скрывалась в толпе танцующих.<br/> Она была очень разгорячена. В перерыве, когда они сидели в столовой, Тоня отказалась от чая и утоляла жажду мандаринами, которые она без счета очищала от пахучей легко отделявшейся кожуры. Она поминутно вынимала из-за кушака или из рукавчика батистовый платок, крошечный как цветы фруктового дерева, и утирала им струйки пота по краям губ и между липкими пальчиками. Смеясь и не прерывая оживленного разговора, она машинально совала платок назад за кушак или за оборку лифа.<br/> Теперь, танцуя с неизвестным кавалером и при повороте задевая за сторонившегося и хмурившегося Юру, Тоня мимоходом шаловливо пожимала ему руку и выразительно улыбалась. При одном из таких пожатий платок, который она держала в руке, остался на Юриной ладони. Он прижал его к губам и закрыл глаза. Платок издавал смешанный запах мандариновой кожуры и разгоряченной Тониной ладони, одинаково чарующий. Это было что-то новое в Юриной жизни, никогда не испытанное и остро пронизывающее сверху донизу. Детски-наивный запах был задушевно-разумен, как какое-то слово, сказанное шопотом в темноте. Юра стоял, зарыв глаза и губы в ладонь с платком и дыша им. Вдруг в доме раздался выстрел.<br/> Все повернули головы к занавеси, отделявшей гостиную от зала. Минуту длилось молчание. Потом начался переполох. Все засуетились и закричали. Часть бросилась за Кокой Корнаковым на место грянувшего выстрела. Оттуда уже шли навстречу, угрожали, плакали и, споря, перебивали друг друга.<br/> — Что она наделала, что она наделала, — в отчаянии повторял Комаровский.<br/> — Боря, ты жив? Боря, ты жив, — истерически выкрикивала госпожа Корнакова. — Говорили, что здесь в гостях доктор Дроков. Да, но где же он, где он? Ах, оставьте, пожалуйста!<br/> Для вас царапина, а для меня оправдание всей моей жизни. О мой бедный мученик, обличитель всех этих преступников! Вот она, вот она дрянь, я тебе глаза выцарапаю, мерзавка! Ну теперь ей не уйти! Что вы сказали, господин Комаровский? В вас? Она стреляла в вас? Нет, я не могу. У меня большое горе, господин Комаровский, опомнитесь, мне сейчас не до шуток. Кока, Кокочка, ну что ты скажешь! На отца твоего… Да… Но десница Божья… Кока! Кока!<br/> Толпа из гостиной вкатилась в зал. В середине, громко отшучиваясь и уверяя всех в своей совершенной невредимости, шел Корнаков, зажимая чистою салфеткою кровоточащую царапину на легко ссаженной левой руке. В другой группе несколько в стороне и позади вели за руки Лару.<br/> Юра обомлел, увидав ее. — Та самая! И опять при каких необычайных обстоятельствах! И снова этот седоватый. Но теперь Юра знает его. Это видный адвокат Комаровский, он имел отношение к делу об отцовском наследстве. Можно не раскланиваться, Юра и он делают вид, что незнакомы. А она…<br/> Так это она стреляла? В прокурора? Наверное, политическая.<br/> Бедная. Теперь ей не поздоровится. Как она горделиво хороша! А эти! Тащат ее, черти, выворачивая руки, как пойманную воровку.<br/> Но он тут же понял, что ошибается. У Лары подкашивались ноги. Ее держали за руки, чтобы она не упала, и с трудом дотащили до ближайщего кресла, в которое она и рухнула.<br/> Юра подбежал к ней, чтобы привести её в чувство, но для большего удобства решил сначала проявить интерес к мнимой жертве покушения. Он подошел к Корнакову и сказал:<br/> — Здесь просили врачебной помощи. Я могу подать ее.<br/> Покажите мне вашу руку… Ну, счастлив ваш Бог. Это такие пустяки, что я не стал бы перевязывать. Впрочем, немного йоду не помешает. Вот Фелицата Семеновна, мы попросим у нее.<br/> На Свентицкой и Тоне, быстро приблизившихся к Юре, не было лица. Они сказали, чтобы он все бросил и шел скорее одеваться, за ними приехали, дома что-то неладное. Юра испугался, предположив самое худшее, и, позабыв обо всем на свете, побежал одеваться.

