### 15 {-}

Они уже не застали Анну Ивановну в живых, когда с подъезда в Сивцевом сломя голову вбежали в дом. Смерть наступила за десять минут до их приезда. Ее причиной был долгий припадок удушья вследствие острого, вовремя не распознанного отека легких.<br/> Первые часы Тоня кричала благим матом, билась в судорогах и никого не узнавала. На другой день она притихла, терпеливо выслушивая, что ей говорили отец и Юра, но могла отвечать только кивками, потому что, едва она открывала рот, горе овладевало ею с прежнею силой и крики сами собой начинали вырываться из нее как из одержимой.<br/> Она часами распластывалась на коленях возле покойницы, в промежутках между панихидами обнимая большими красивыми руками угол гроба вместе с краем помоста, на котором он стоял, и венками, которые его покрывали. Она никого кругом не замечала.<br/> Но едва её взгляды встречались с глазами близких, она поспешно вставала с полу, быстрыми шагами выскальзывала из зала, сдерживая рыданье, стремительно взбегала по лесенке к себе наверх и, повалившись на кровать, зарывала в подушки взрывы бушевавшего в ней отчаяния.<br/> От горя, долгого стояния на ногах и недосыпания, от густого пения, и ослепляющего света свечей днем и ночью, и от простуды, схваченной на этих днях, у Юры в душе была сладкая неразбериха, блаженно-бредовая, скорбно-восторженная.<br/> Десять лет тому назад, когда хоронили маму, Юра был совсем еще маленький. Он до сих пор помнил, как он безутешно плакал, пораженный горем и ужасом. Тогда главное было не в нем. Тогда он едва ли даже соображал, что есть какой-то он, Юра, имеющийся в отдельности и представляющий интерес или цену.<br/> Тогда главное было в том, что стояло кругом, в наружном.<br/> Внешний мир обступал Юру со всех сторон, осязательный, непроходимый и бесспорный, как лес, и оттого-то был Юра так потрясен маминой смертью, что он с ней заблудился в этом лесу и вдруг остался в нем один, без нее. Этот лес составляли все вещи на свете — облака, городские вывески, и шары на пожарных каланчах, и скакавшие верхом перед каретой с божьей Матерью служки с наушниками вместо шапок на обнаженных в присутствии святыни головах. Этот лес составляли витрины магазинов в пассажах и недосягаемо высокое ночное небо со звездами, боженькой и святыми.<br/> Это недоступно высокое небо наклонялось низко-низко к ним в детскую макушкой в нянюшкин подол, когда няня рассказывала что-нибудь божественное, и становилось близким и ручным, как верхушки орешника, когда его ветки нагибают в оврагах и обирают орехи. Оно как бы окуналось у них в детской в таз с позолотой и, искупавшись в огне и золоте, превращалось в заутреню или обедню в маленькой переулочной церквушке, куда няня его водила. Там звезды небесные становились лампадками, боженька — батюшкой и все размещались на должности более или менее по способностям. Но главное был действительный мир взрослых и город, который подобно лесу, темнел кругом. Тогда всей своей полузвериной верой Юра верил в Бога этого леса, как в лесничего.<br/> Совсем другое дело было теперь. Все эти двенадцать лет школы, средней и высшей, Юра занимался древностью и законом Божьим, преданиями и поэтами, науками о прошлом и о природе, как семейною хроникой родного дома, как своею родословною.<br/> Сейчас он ничего не боялся, ни жизни ни смерти, все на свете, все вещи были словами его словаря. Он чувствовал себя стоящим на равной ноге со вселенною и совсем по-другому выстаивал панихиды по Анне Ивановне, чем в былое время по своей маме.<br/> Тогда он забывался от боли, робел и молился. А теперь он слушал заупокойную службу как сообщение, непосредственно к нему обращенное и прямо его касающееся. Он вслушивался в эти слова и требовал от них смысла, понятно выраженного, как это требуется от всякого дела, и ничего общего с набожностью не было в его чувстве преемственности по отношению к высшим силам земли и неба, которым он поклонялся как своим великим предшественникам.

