### 16 {-}

«Святый Боже, святый крепкий, святый бессмертный, помилуй нас». Что это? Где он? Вынос. Выносят. Надо проснуться. Он в шестом часу утра повалился одетый на этот диван. Наверное у него жар. Сейчас его ищут по всему дому, и никто не догадается, что он в библиотеке спит-не проснется в дальнем углу, за высокими книжными полками, доходящими до потолка.<br/> «Юра, Юра!» — зовет его где-то рядом дворник Маркел.<br/> Начался вынос, Маркелу надо тащить вниз на улицу венки, а он не может доискаться Юры, да вдобавок еще застрял в спальне, где венки сложены горою, потому что дверь из нее придерживает открывшаяся дверца гардероба и не дает Маркелу выйти.<br/> — Маркел! Маркел! Юра! — зовут их снизу.<br/> Маркел одним ударом расправляется с образовавшимся препятствием и сбегает с несколькими венками вниз по лестнице.<br/> «Святый Боже, святый крепкий, святый бессмертный» — тихим веянием проволакивается по переулку и остается в нем, как будто провели мягким страусовым пером по воздуху, и все качается: венки и встречные, головы лошадей с султанами, отлетающее кадило на цепочке в руке священника, белая земля под ногами.<br/> — Юра! Боже, наконец-то. Проснись, пожалуйста, — трясет его за плечо доискавшаяся его Шура Шлезингер. — Что с тобой?<br/> Выносят. Ты с нами?<br/> — Ну конечно.

### 17 {-}

Отпевание кончилось. Нищие, зябко переступая с ноги на ногу, теснее сдвинулись в две шеренги. Колыхнулись и чуть-чуть переместились похоронные дроги одноколка с венками, карета Крюгеров.<br/> Ближе к церкви подтянулись извозчики. Из храма вышла заплаканная Шура Шлезингер и, подняв отсыревшую от слез вуаль, скользнула испытующим взором вдоль линии извозчиков. Отыскав в их ряду носильщиков из бюро, она кивком подозвала их к себе и скрылась с ними в церкви. Из церкви валило все больше народу.<br/> — Вот и Анина-Иваннина очередь. Приказала кланяться, вынула, бедняжка, далекий билет.<br/> — Да, отпрыгалась, бедная. Поехала, стрекоза, отдыхать.<br/> — У вас извозчик или вы на одиннадцатом номере?<br/> — Застоялись ноги. Чуточку пройдемся и поедем.<br/> — Заметили, как Фуфков расстроен? На новопреставленную смотрел, слезы градом, сморкается, так бы и съел. А рядом муж.<br/> — Он всю жизнь на нее запускал глазенапа.<br/> С такими разговорами тащились на другой конец города на кладбище. В этот день отдало после сильных морозов. День был полон недвижной тяжести, день отпустившего мороза и отошедшей жизни, день, самой природой как бы созданный для погребения.<br/> Погрязневший снег словно просвечивал сквозь наброшенный креп, из-за оград смотрели темные, как серебро с чернью, мокрые елки и походили на траур.<br/> Это было то самое, памятное кладбище, место упокоения Марии Николаевны. Юра последние годы совсем не попадал на материнскую могилу. «Мамочка», — посмотрев издали в ту сторону, прошептал он почти губами тех лет.<br/> Расходились торжественно и даже картинно по расчищенным дорожкам, уклончивые извивы которых плохо согласовались со скорбной размеренностью их шага. Александр Александрович вел под руку Тоню. За ними следовали Крюгеры. Тоне очень шел траур.<br/> На купольных цепях крестов и на розовых монастырских стенах лохматился иней, бородатый, как плесень. В дальнем углу монастырского двора от стены к стене были протянуты веревки с развешенным для сушки стираным бельем — рубашки с тяжелыми, набрякшими рукавами, скатерти персикового цвета, кривые, плохо выжатые простыни. Юра вгляделся в ту сторону и понял, что это то место на монастырской земле, где тогда бушевала вьюга, измененное новыми постройками.<br/> Юра шел один, быстрой ходьбой опережая остальных, изредка останавливаясь и их поджидая. В ответ на опустошение, произведенное смертью в этом медленно шагавшем сзади обществе, ему с непреодолимостью, с какою вода, крутя воронки, устремляется в глубину, хотелось мечтать и думать, трудиться над формами, производить красоту. Сейчас, как никогда, ему было ясно, что искусство всегда, не переставая, занято двумя вещами. Оно неотступно размышляет о смерти и неотступно творит этим жизнь. Большое, истинное искусство, то, которое называется Откровением Иоанна, и то, которое его дописывает.<br/> Юра с вожделением предвкушал, как он на день-на два исчезнет с семейного и университетского горизонта и в свои заупокойные строки по Анне Ивановне вставит все, что ему к той минуте подвернется, все случайное, что ему подсунет жизнь: две-три лучших отличительных черты покойной; образ Тони в трауре; несколько уличных наблюдений по пути назад с кладбища; стираное белье на том месте, где давно когда-то ночью завывала вьюга и он плакал маленьким.

