## ЧАСТЬ четвертая. НАЗРЕВШИЕ НЕИЗБЕЖНОСТИ {-}

### 1 {-}

Лара лежала в полубреду в спальне на кровати Фелицаты Семеновны. Вокруг нее шептались Свентицкие, доктор Дроков, прислуга.<br/> Пустой дом Свентицких был погружен во тьму, и только в середине длинной анфилады комнат, в маленькой гостиной, горела на стене тусклая лампа, бросая свет вперед и назад вдоль этого сквозного, в одну линию вытянутого ряда.<br/> По этому пролету не как в гостях, а словно у себя дома злыми и решительными шагами расхаживал Виктор Ипполитович. Он то заглядывал в спальню, осведомляясь, что там делается, то направлялся в противоположный конец дома и мимо елки с серебряными бусами доходил до столовой, где стол ломился под нетронутым угощением и зеленые винные бокалы позвякивали, когда за окном по улице проезжала карета или по скатерти между тарелок прошмыгивал мышонок.<br/> Комаровский рвал и метал. Разноречивые чувства теснились в его груди. Какой скандал и безобразие! Он был в бешенстве. Его положение было в опасности. Случай подрывал его репутацию.<br/> Надо было любой ценой, пока не поздно, предупредить, пресечь сплетни, а если весть уже распространилась, замять, затушить слухи при самом возникновении. Кроме того, он снова испытал, до чего неотразима эта отчаянная, сумасшедшая девушка. Сразу было видно, что она не как все. В ней всегда было что-то необыкновенное. Однако как чувствительно и непоправимо, по-видимому, исковеркал он её жизнь! Как она мечется, как все время восстает и бунтует в стремлении переделать судьбу по-своему и начать существовать сызнова.<br/> Надо будет со всех точек зрения помочь ей, может быть, снять ей комнату, но ни в коем случае не трогать ее, напротив, совершенно устраниться, отойти в сторону, чтобы не бросать тени, а то вот ведь она какая, еще что-нибудь выкинет, чего доброго!<br/> А сколько еще хлопот впереди! Ведь за это по головке не погладят. Закон не дремлет. Еще ночь и не прошло двух часов с той минуты, как разыгралась эта история, а уже два раза являлись из полиции, и Комаровский выходил на кухню для объяснения с околоточным и все улаживал.<br/> А чем дальше, тем все будет сложнее. Потребуются доказательства, что Лара целилась в него, а не в Корнакова. Но и этим дело не ограничится. Часть ответственности будет с Лары снята, но она будет подлежать судебному преследованию за оставшуюся часть.<br/> Разумеется, он всеми силами этому воспрепятствует, а если дело будет возбуждено, достанет заключение психиатрической экспертизы о невменяемости Лары в момент совершения покушения и добьется прекращения дела.<br/> За этими мыслями Комаровский стал успокаиваться. Ночь прошла. Полосы света стали шнырять из комнаты в комнату, заглядывая под столы и диваны, как воры или ломбардные оценщики.<br/> Наведавшись в спальню и удостоверившись, что Ларе не стало лучше, Комаровский от Свентицких поехал к своей знакомой, юристке и жене политического эмигранта Руфине Онисимовне Войт-Войтковской. Квартира в восемь комнат была теперь выше её потребностей и ей не по средствам. Она сдавала внаймы две комнаты. Одну из них, недавно освободившуюся, Комаровский снял для Лары. Через несколько часов Лару перевезли туда в лихорадочном жару и полуобморочном состоянии. У нее была нервная горячка.

