### 3 {-}

Много горя было с Пашею. Пока Лара серьезно хворала, его не допускали к ней. Что должен был он почувствовать? Лара хотела убить человека, по Пашиным понятиям, безразличного ей, а потом очутилась под покровительством этого человека, жертвы своего неудавшегося убийства. И это все после памятного их разговора рождественскою ночью, при горящей свече! Если бы не этот человек, Лару бы арестовали и судили. Он отвел от нее грозившую ей кару. Благодаря ему она осталась на курсах, цела и невредима. Паша терзался и недоумевал.<br/> Когда ей стало лучше, Лара вызвала Пашу к себе. Она сказала:<br/> — Я плохая. Ты не знаешь меня, я когда-нибудь расскажу тебе. Мне трудно говорить, ты видишь, я захлебываюсь от слез, но брось, забудь меня, я тебя не стою.<br/> Пошли душераздирающие сцены, одна невыносимее другой.<br/> Войтковская, — потому что это происходило еще во время Лариного пребывания на Арбате, — Войтковская при виде заплаканного Паши кидалась из коридора на свою половину, валилась на диван и хохотала до колик, приговаривая: «Ой не могу, ой не могу! Вот это можно сказать действительно… Ха-ха-ха! Богатырь! Ха-ха-ха! Еруслан Лазаревич!»<br/> Чтобы избавить Пашу от пятнающей привязанности, вырвать её с корнем и положить конец мучениям, Лара объявила Паше, что на отрез отказывается от него, потому что не любит его, но так рыдала, произнося это отречение, что ей нельзя было поверить.<br/> Паша подозревал её во всех смертных грехах, не верил ни одному её слову, готов был проклясть и возненавидеть, и любил её дьявольски, и ревновал её к её собственным мыслям, к кружке, из которой она пила, и к подушке, на которой она лежала. Чтобы не сойти с ума, надо было действовать решительнее и скорее.<br/> Они решили пожениться, не откладывая, еще до окончания экзаменов. Было предположение венчаться на Красную горку.<br/> Свадьбу по Лариной просьбе опять отложили.<br/> Их венчали в Духов день, на второй день Троицы, когда с несомненностью выяснилась успешность их окончания. Всем распоряжалась Людмила Капитоновна Чепурко, мать Туси Чепурко, Лариной однокурсницы, вместе с ней окончившей. Людмила Капитоновна была красивая женщина с высокой грудью и низким голосом, хорошая певица и страшная выдумщица. В придачу к действительным примерам и поверьям, известным ей, она на ходу экспромтом сочиняла множество собственных.<br/> Была ужасная жара в городе, когда Лару «повезли под злат-венец», как цыганским Панинским басом мурлыкала себе под нос Людмила Капитоновна, убирая Лару перед выездом. Были пронзительно желты золотые купола церквей и свежий песочек на дорожках гуляний. Запылившаяся зелень березок, нарубленных накануне к Троицыну дню, понуро висла по оградам храмов, свернувшись в трубочку и словно обгорелая. Было трудно дышать, и в глазах рябило от солнечного блеска. И словно тысячи свадеб справляли кругом, потому что все девушки были завиты и в светлом, как невесты, и все молодые люди, по случаю праздника, напомажены и в черных парах в обтяжку. И все волновались, и всем было жарко.<br/> Лагодина, мать другой Лариной товарки, бросила Ларе горсть серебряной мелочи под ноги, когда Лара вступила на коврик к будущему богатству, а Людмила Капитоновна с тою же целью посоветовала Ларе, когда она станет под венец, креститься не голой, высунутой рукой, а полуприкрытой краешком газа или кружева. Потом она сказала, чтобы Лара держала свечу высоко, тогда она будет в доме верховодить. Но, жертвуя своей будущностью в пользу Пашиной, Лара опускала свечу как можно ниже, и всё понапрасну, потому что сколько она ни старалась, все выходило, что её свеча выше Пашиной.<br/> Из церкви вернулись прямо на пирушку в мастерскую художника, тогда же обновленную Антиповыми. Гости кричали «горько, не пьется», — а с другого конца согласным ревом ответствовали: «надо подсластить», — и молодые, конфузливо ухмыляясь, целовались. Людмила Капитоновна пропела им величание — «Виноград» с двойным припевом «Дай вам Бог любовь да совет» и песню «Расплетайся трубчата коса, рассыпайтесь русы волоса».<br/> Когда все разошлись и они остались одни, Паше стало не по себе от внезапно наступившей тишины. На дворе против Лариного окна горел фонарь на столбе, и, как ни занавешивалась Лара, узкая, как распиленная доска, полоса света проникала сквозь промежуток разошедшихся занавесок. Эта светлая полоса не давала Паше покою, словно кто-то за ними подсматривал. Паша с ужасом обнаруживал, что этим фонарем он занят больше, чем собою, Ларою и своей любовью к ней.<br/> За эту ночь, продолжительную как вечность, недавний студент Антипов, «Степанида» и «Красная Девица», как звали его товарищи, побывал на верху блаженства и на дне отчаяния. Его подозрительные догадки чередовались с Лариными признаниями. Он спрашивал, и за каждым Лариным ответом у него падало сердце, словно он летел в пропасть. Его израненное воображение не поспевало за новыми открытиями.<br/> Они проговорили до утра. В жизни Антипова не было перемены разительнее и внезапнее этой ночи. Утром он встал другим человеком, почти удивляясь, что его зовут по-прежнему.

