### 4 {-}

Через десять дней друзья устроили им проводы в той же комнате. Паша и Лара оба кончили, оба одинаково блестяще, оба получили предложения в один и тот же город на Урале, куда и должны были выехать на другой день утром.<br/> Опять пили, пели и шумели, но на этот раз только одна молодежь, без старших.<br/> За перегородкой, отделявшей жилые закоулки от большой мастерской, где собрались гости, стояла большая багажная и одна средняя корзины Лары, чемодан и ящик с посудою. В углу лежало несколько мешков. Вещей было много. Часть их уходила на другой день утром малою скоростью. Всё почти было уложено, но не до конца. Ящик и корзины стояли открытые, не доложенные доверху. Лара время от времени вспоминала про что-нибудь, переносила забытую вещь за перегородку и, положив в корзину, разравнивала неровности.<br/> Паша уже был дома с гостями, когда Лара, ездившая в канцелярию курсов за метрикой и бумагами, вернулась в сопровождении дворника с рогожею и большой связкою крепкой толстой веревки для увязывания завтрашней клади. Лара отпустила дворника и, обойдя гостей, с частью поздоровалась за руку, а с другими перецеловалась, а потом ушла за перегородку переодеваться. Когда она вышла переодетая, все захлопали, загалдели, стали рассаживаться, и начался шум, как несколько дней тому назад на свадьбе. Наиболее предприимчивые взялись разливать водку соседям, множество рук, вооружившись вилками, потянулось в центр стола за хлебом и к блюдам с кушаньями и закусками. Ораторствовали, крякали, промочивши горло, и наперебой острили. Некоторые стали быстро пьянеть.<br/> — Я смертельно устала, — сказала Лара, сидевшая рядом с мужем. — ты все успел, что хотел сделать?<br/> — Да.<br/> — И все-таки я замечательно себя чувствую. Я счастлива. А ты?<br/> — Я тоже. Мне хорошо. Но это долгий разговор.<br/> На вечеринку с молодою компанией в виде исключения был допущен Комаровский.<br/> В конце вечера он хотел сказать, что осиротеет после отъезда своих молодых друзей, что Москва станет для него пустынею, Сахарой, но так расчувствовался, что всхлипнул и должен был повторить прерванную от волнения фразу снова. Он просил Антиповых позволения переписываться с ними и наведаться к ним в Юрятин, место их нового жительства, если он не выдержит разлуки.<br/> — Это совершенно лишнее, — громко и невнимательно отозвалась Лара. — И вообще все это ни к чему — переписываться, Сахара и тому подобное. А приезжать туда и не думайте. Бог даст без нас уцелеете, не такая мы редкость, не правда ли, Паша? Авось найдется вашим молодым друзьям замена.<br/> И совершенно забыв, с кем и о чем она говорит, Лара что-то вспомнила и, торопливо встав, ушла за перегородку на кухню.<br/> Там она развинтила мясорубку и стала распихивать разобранные части по углам посудного ящика, подтыкая их клочьями сена. При этом она чуть не занозила себе руку отщепившейся от края острою лучиной.<br/> За этим занятием она упустила из виду, что у нее гости, перестав их слышать, как вдруг они напомнили о себе особенно громким взрывом галдежа из-за перегородки, и тогда Лара подумала, с какой старательностью пьяные всегда любят изображать пьяных, и с тем более бездарной, и любительской подчеркнутостью, чем они пьянее.<br/> В это время совсем другой, особенный звук привлек её внимание со двора сквозь открытое окно. Лара отвела занавеску и высунулась наружу.<br/> По двору хромающими прыжками передвигалась стреноженная лошадь. Она была неизвестно чья и забрела во двор, наверное, по ошибке. Было уже совершенно светло, но еще далеко до восхода солнца. Спящий и как бы совершенно вымерший город тонул в серо-лиловой прохладе раннего часа. Лара закрыла глаза. Бог знает в какую деревенскую глушь и прелесть переносило это отличительное и ни с чем не сравнимое конское кованое переступание.<br/> С лестницы позвонили. Лара навострила уши. Из-за стола пошли отворять. Это была Надя! Лара кинулась навстречу вошедшей. Надя была прямо с поезда, свежая, обворожительная и вся как бы благоухала дуплянскими ландышами. Подруги стояли, будучи не в силах сказать ни слова, и только ревели, обнимались и чуть не задушили друг друга.<br/> Надя привезла Ларе от всего дома поздравления и напутствия и в подарок от родителей драгоценность. Она вынула из саквояжа завернутую в бумагу шкатулку, развернула её и, отщелкнув крышку, передала Ларе редкой красоты ожерелье.<br/> Начались охи и ахи. Кто-то из пьяных, уже несколько протрезвившийся, сказал:<br/> — Розовый гиацинт. Да, да, розовый, вы что думаете. Камень не ниже алмаза.<br/> Но Надя спорила, что это желтые сапфиры.<br/> Усадив её рядом с собой и угощая, Лара положила ожерелье около своего прибора и смотрела на него, не отрываясь.<br/> Собранное в горсточку на фиолетовой подушке футляра, оно переливалось, горело и то казалось стечением по каплям набежавшей влаги, то кистью мелкого винограда.<br/> Кое-кто за столом тем временем успел прийти в чувство.<br/> Очнувшиеся снова пропустили по рюмочке за компанию с Надей.<br/> Надю быстро напоили.<br/> Скоро дом представлял сонное царство. Большинство, предвидя завтрашние вокзальные проводы, осталось ночевать. Половина давно уже храпела по углам вповалку. Лара сама не помнила, как очутилась одетая на диване рядом с уже спавшею Ирой Лагодиной.<br/> Лара проснулась от громкого разговора над самым ухом. Это были голоса чужих, пришедших с улицы во двор за пропавшею лошадью. Лара открыла глаза и удивилась: «Какой этот Паша, в самом деле, неугомонный, стоит верстой среди комнаты и все без конца что-то шарит». В это время предполагаемый Паша повернулся к ней лицом, и она увидала, что это совсем не Паша, а какое-то рябое страшилище с лицом, рассеченным шрамом от виска к подбородку. Тогда она поняла, что к ней забрался вор, грабитель, и хотела крикнуть, но оказалась не в состоянии издать ни звука. Вдруг она вспомнила про ожерелье и, украдкой поднявшись на локте, посмотрела искоса на обеденный стол.<br/> Ожерелье лежало на месте среди крошек хлеба и огрызков карамели, и недогадливый злоумышленник не замечал его в куче объедков, а только ворошил уложенное белье и приводил в беспорядок Ларину упаковку. Хмельной и полусонной Ларе, плохо сознававшей положение, стало особенно жалко своей работы. В негодовании она снова хотела крикнуть и снова не могла открыть рот и пошевелить языком. Тогда она с силой толкнула спавшую рядом Иру Лагодину коленом под ложечку, и когда та вскрикнула не своим голосом от боли, вместе с ней закричала и Лара. Вор уронил узел с накраденным и опрометью кинулся из комнаты.<br/> Кое-кто из повскакавших мужчин, насилу уяснив себе, в чем дело, бросились вдогонку, но грабителя и след простыл.<br/> Происшедший переполох и его дружное обсуждение послужили сигналом к общему вставанию. Остаток хмеля у Лары как рукой сняло. Неумолимая к их упрашиваниям дать им подремать и поваляться еще немного, Лара подняла всех спящих, наскоро напоила их кофе и разогнала по домам впредь до новой встречи на вокзале к моменту отхода их поезда.<br/> Когда все ушли, закипела работа. Лара со свойственною ей быстротой носилась от портпледа к портпледу, распихивала подушки, стягивала ремни и только умоляла Пашу и дворничиху не помогать, чтобы не мешать ей.<br/> Все произошло как следует, вовремя. Антиповы не опоздали.<br/> Поезд тронулся плавно, словно подражая движению шляп, которыми им махали на прощание. Когда перестали махать и троекратно рявкнули что-то издали (вероятно, «ура»), поезд пошел быстрее.

