### 5 {-}

Третий день стояла мерзкая погода. Это была вторая осень войны. Вслед за успехами первого года начались неудачи.<br/> Восьмая армия Брусилова, сосредоточенная в Карпатах, готова была спуститься с перевалов и вторгнуться в Венгрию, но вместо этого отходила, оттягиваемая назад общим отступлением. Мы очищали Галицию, занятую в первые месяцы военных действий.<br/> Доктор Живаго, которого звали прежде Юрою; а теперь один за другим звали всё чаще по имени-отчеству, стоял в коридоре акушерского корпуса гинекологической клиники, против двери палаты, в которую поместили только что привезенную им жену Антонину Александровну. Он с ней простился и дожидался акушерки, чтобы уговориться с ней о том, как она будет извещать его, в случае надобности, и как он будет у нее осведомляться о состоянии Тониного здоровья.<br/> Ему было некогда, он торопился к себе в больницу, а до этого должен был еще заехать к двум больным с визитом на дом, а он попусту терял драгоценное время, глазея в окно на косую штриховку дождя, струи которого ломал и отклонял в сторону порывистый осенний ветер, как валит и путает буря колосья в поле.<br/> Еще было не очень темно. Глазам Юрия Андреевича открывались клинические задворки, стеклянные террасы особняков на Девичьем поле, ветка электрического трамвая, проложенная к черному ходу одного из больничных корпусов.<br/> Дождь лил самым неутешным образом, не усиливаясь и не ослабевая, несмотря на неистовства ветра, казалось, обострявшиеся от невозмутимости низвергавшейся на землю воды.<br/> Порывы ветра терзали побеги дикого винограда, которыми была увита одна из террас. Ветер как бы хотел вырвать растение целиком, поднимал на воздух, встряхивал на весу и брезгливо кидал вниз, как дырявое рубище.<br/> Мимо террасы к клинике подошел моторный вагон с двумя прицепами. Из них стали выносить раненых.<br/> В московских госпиталях, забитых до невозможности, особенно после Луцкой операции, раненых стали класть на лестничных площадках и в коридорах. Общее переполнение городских больниц начало сказываться на состоянии женских отделений.<br/> Юрий Андреевич повернулся спиной к окну и зевал от усталости. Ему не о чем было думать. Неожиданно он вспомнил. В хирургическом отделении Крестовоздвиженской больницы, где он служил, умерла на днях больная. Юрий Андреевич утверждал, что у нее эхинококк печени. Все с ним спорили. Сегодня её вскроют. Вскрытие установит истину. Но прозектор их больницы — запойный пьяница. Бог его знает, как он за это примется.<br/> Быстро стемнело. Стало невозможно разглядеть что-нибудь за окном. Словно мановением волшебного жезла во всех окнах зажглось электричество.<br/> От Тони через маленький тамбурчик, отделявший палату от коридора, вышел главный врач отделения мастодонт-гинеколог, на все вопросы всегда отвечавший возведением глаз к потолку и пожиманием плеч. Эти движения на его мимическом языке означали, что, как ни велики успехи знания, есть, мой друг Горацио, загадки, перед которыми наука пасует.<br/> Он прошел мимо Юрия Андреевича, с улыбкой поклонившись ему, и произвел несколько плавательных движений пухлыми руками с толстыми ладонями в смысле того, что приходится ждать и смиряться, и направился по коридору покурить в приемную.<br/> Тогда к Юрию Андреевичу вышла ассистентка неразговорчивого гинеколога, по словоохотливости полная ему противоположность.<br/> — На вашем месте я поехала бы домой. Я вам завтра позвоню в Крестовоздвиженскую общину. Едва ли это начнется раньше. Я уверена, что роды будут естественные, без искусственного вмешательства. Но, с другой стороны, кое-какая узость таза, второе затылочное положение, в котором лежит плод, отсутствие у нее болей и незначительность сокращений вызывают некоторые опасения. Впрочем, рано предсказывать. Все зависит от того, какие она будет вырабатывать потуги, когда начнутся роды. А это покажет будущее.<br/> На другой день в ответ на его телефонный звонок подошедший к аппарату больничный сторож велел ему не вешать трубки, пошел справляться, протомил его минут десять и принес в грубой и несостоятельной форме следующие сведения: «Велено сказать, скажи, говорят, привез жену слишком рано, надо забирать обратно». Взбешенный Юрий Андреевич потребовал к телефону кого-нибудь более осведомленного. — «Симптомы обманчивы, — сказала ему сестра, — пусть доктор не тревожится, придется потерпеть сутки-другие».<br/> На третий день он узнал, что роды начались ночью, на рассвете прошли воды и с утра не прекращаются сильные схватки.<br/> Он сломя голову помчался в клинику и, когда шел по коридору, слышал через полуоткрытую по нечаянности дверь душераздирающие крики Тони, как кричат задавленные с отрезанными конечностями, извлеченные из-под колес вагона.<br/> Ему нельзя было к ней. Закусив до крови согнутый в суставе палец, он отошел к окну, за которым лил тот же косой дождь, как вчера и позавчера.<br/> Из палаты вышла больничная сиделка. Оттуда доносился писк новорожденного.<br/> — Спасена, спасена, — радостно повторял про себя Юрий Андреевич.<br/> — Сынок. Мальчик. С благополучным разрешением от бремени, — нараспев говорила сиделка. — Сейчас нельзя. Придет время — покажем. Тогда придется раскошелиться на родильницу.<br/> Намучилась. С первым. С первым завсегда мука.<br/> — Спасена, спасена, — радовался Юрий Андреевич, не понимая того, что говорила сиделка, и того, что она своими словами зачисляла его в участники совершившегося, между тем как при чем он тут? Отец, сын — он не видел гордости в этом даром доставшемся отцовстве, он не чувствовал ничего в этом с неба свалившемся сыновстве. Все это лежало вне его сознания.<br/> Главное была Тоня, Тоня, подвергшаяся смертельной опасности и счастливо её избегнувшая.<br/> У него был больной невдалеке от клиники. Он зашел к нему и через полчаса вернулся. Обе двери, из коридора в тамбур и дальше, из тамбура в палату, были опять приоткрыты. Сам не сознавая, что он делает, Юрий Андреевич прошмыгнул в тамбур.<br/> Растопырив руки, перед ним как из-под земли вырос мастодонт-гинеколог в белом халате.<br/> — Куда? — задыхающимся шёпотом, чтобы не слышала родильница, остановил он его. — Что вы, с ума сошли? Раны, кровь, антисептика, не говоря уж о психическом потрясении. Хорош! А еще врач.<br/> — Да разве я… Я только одним глазком. Отсюда. Сквозь щелку.<br/> — А, это другое дело. Так и быть. Но чтобы мне!.. Смотрите! Если заметит, убью, живого места не оставлю!<br/> В палате спиной к двери стояли две женщины в халатах, акушерка и нянюшка. На нянюшкниой руке жилился писклявый и нежный человеческий отпрыск, стягиваясь и растягиваясь, как кусок темно-красной резины. Акушерка накладывала лигатуры на пуповину, чтобы отделить ребенка от последа. Тоня лежала посередине палаты на хирургической койке с подъемною доскою. Она лежала довольно высоко. Юрию Андреевичу, который всё преувеличивал от волнения, показалось, что она лежит примерно на уровне конторок, за которыми пишут стоя.<br/> Поднятая к потолку выше, чем это бывает с обыкновенными смертными, Тоня тонула в парах выстраданного, она как бы дымилась от изнеможения. Тоня возвышалась посреди палаты, как высилась бы среди бухты только что причаленная и разгруженная барка, совершающая переходы через море смерти к материку жизни с новыми душами, переселяющимися сюда неведомо откуда. Она только что произвела высадку одной такой души и теперь лежала на якоре, отдыхая всей пустотой своих облегченных боков. Вместе с ней отдыхали ее надломленные и натруженные снасти и обшивка, и ее забвение, ее угасшая память о том, где она недавно была, что переплыла и как причалила.<br/> И так как никто не знал географии страны, под флагом которой она пришвартовалась, было неизвестно, на каком языке обратиться к ней.<br/> На службе все наперерыв поздравляли его. — Как быстро они узнали! — удивлялся Юрий Андреевич.<br/> Он прошел в ординаторскую, которую назвали кабаком и помойной ямой, потому что вследствие тесноты, вызванной загруженностью больницы, теперь в этой комнате раздевались, заходя в нее в калошах с улицы, забывали в ней посторонние предметы, занесенные из других помещений, сорили окурками и бумагой.<br/> У окна ординаторской стоял обрюзгший прозектор и, подняв руки, рассматривал на свет поверх очков какую-то мутную жидкость в склянке.<br/> — Поздравляю, — сказал он, продолжая смотреть в том же направлении и даже не удостоив Юрия Андреевича взглядом.<br/> — Спасибо. Я тронут.<br/> — Не стоит благодарности. Я тут ни при чем. Вскрывал Пичужкин. Но все поражены. Эхинококк. Вот это, говорят, диагност! Только и разговору.<br/> В это время в комнату вошел главный врач больницы. Он поздоровался с обоими и сказал:<br/> — Чорт знает что. Проходной двор, а не ординаторская, что за безобразие! Да, Живаго, представьте — эхинококк! Мы были не правы. Поздравляю. И затем — неприятность. Опять пересмотр вашей категории. На этот раз отстоять вас не удастся. Страшная нехватка военно-медицинского персонала. Придется вам понюхать пороху.

