### 6 {-}

Антиповы сверх ожидания очень хорошо устроились в Юрятине.<br/> Гишаров поминали тут добром. Это облегчило Ларе трудности, сопряженные с водворением на новом месте.<br/> Лара вся была в трудах и заботах. На ней были дом и их трехлетняя девчурка Катенька. Как ни старалась рыжая Марфутка, прислуживавшая у Антиповых, её помощь была недостаточна.<br/> Лариса Федоровна входила во все дела Павла Павловича. Она сама преподавала в женской гимназии. Лара работала не покладая рук и была счастлива. Это была именно та жизнь, о которой она мечтала.<br/> Ей нравилось в Юрятине. Это был её родной город. Он стоял на большой реке Рыньве, судоходной на своем среднем и нижнем течении, и находился на линии одной из уральских железных дорог.<br/> Приближение зимы в Юрятине ознаменовывалось тем, что владельцы лодок поднимали их с реки на телегах в город. Тут их развозили по своим дворам, где лодки зимовали до весны под открытым небом. Перевернутые лодки, белеющие на земле в глубине дворов, означали в Юрятине то же самое, что в других местах осенний перелет журавлей или первый снег.<br/> Такая лодка, под которою Катенька играла как под выпуклою крышею садового павильона, лежала белым крашеным дном вверх на дворе дома, арендованного Антиповыми.<br/> Ларисе Федоровне по душе были нравы захолустья, по-северному окающая местная интеллигенция в валенках и теплых кацавейках из серой фланели, их наивная доверчивость. Лару тянуло к земле и простому народу.<br/> По странности как раз сын московского железнодорожного рабочего Павел Павлович оказался неисправимым столичным жителем. Он гораздо строже жены относился к юрятинцам. Его раздражали их дикость и невежество.<br/> Теперь задним числом выяснилось, что у него была необычайная способность приобретать и сохранять знания, почерпнутые из беглого чтения. Он уже и раньше, отчасти с помощью Лары, прочел очень много. За годы уездного уединения начитанность его так возросла, что уже и Лара казалась ему недостаточно знающей. Он был головою выше педагогической среды своих сослуживцев и жаловался, что он среди них задыхается. В это военное время ходовой их патриотизм, казенный и немного квасной, не соответствовал более сложным формам того же чувства, которое питал Антипов.<br/> Павел Павлович кончил классиком. Он преподавал в гимназии латынь и древнюю историю. Но в нем, бывшем реалисте, вдруг проснулась заглохшая было страсть к математике, физике и точным наукам. Путем самообразования он овладел всеми этими предметами в университетском объеме. Он мечтал при первой возможности сдать по ним испытания при округе, переопределиться по какой-нибудь математической специальности и перевестись с семьею в Петербург. Усиленные ночные занятия расшатали здоровье Павла Павловича. У него появилась бессонница.<br/> С женой у него были хорошие, но слишком непростые отношения. Она подавляла его своей добротой и заботами, а он не позволял себе критиковать ее. Он остерегался, как бы в невиннейшем его замечании не послышался ей какой-нибудь мнимо затаенный упрек, в том, например, что она белой, а он — черной кости, или в том, что до него она принадлежала другому.<br/> Боязнь, чтобы она не заподозрила его в какой-нибудь несправедливо-обидной бессмыслице, вносила в их жизнь искусственность. Они старались переблагородничать друг друга и этим всё осложняли.<br/> У Антиповых были гости, несколько педагогов — товарищей Павла Павловича, начальница Лариной гимназии, один участник третейского суда, на котором Павел Павлович тут однажды выступал примирителем, и другие. Все они, с точки зрения Павла Павловича, были набитые дураки и дуры. Он поражался Ларе, любезной со всеми, и не верил, чтобы кто-нибудь тут мог искренне нравиться ей.<br/> Когда гости ушли, Лара долго проветривала, подметала комнаты, мыла с Марфуткою на кухне посуду. Потом, удостоверившись, что Катенька хорошо укрыта и Павел спит, быстро разделась, потушила лампу и легла рядом с мужем с естественностью ребенка, взятого в постель к матери.<br/> Но Антипов притворялся, что спит, — он не спал. У него был припадок обычной за последнее время бессонницы. Он знал, что проваляется еще так без сна часа три-четыре. Чтобы нагулять себе сон и избавиться от оставленного гостями табачного чада, он тихонько встал и в шапке и шубе поверх нижнего белья вышел на улицу.<br/> Была ясная осенняя ночь с морозом. Под ногами у Антипова звонко крошились хрупкие ледяные пластинки. Звездное небо, как пламя горящего спирта, озаряло голубым движущимся отсветом черную землю с комками замерзшей грязи.<br/> Дом, в котором жили Антиповы, находился в части города, противоположной пристани. Дом был последним на улице. За ним начиналось поле. Его пересекала железная дорога. Близ линии стояла сторожка. Через рельсы был проложен переезд.<br/> Антипов сел на перевернутую лодку и посмотрел на звезды.<br/> Мысли, к которым он привык за последние годы, охватили его с тревожною силой. Ему представилось, что их рано или поздно надо додумать до конца, и лучше это сделать сегодня.<br/> Так дальше не может продолжаться, — думал он. — Но ведь все это можно было предвидеть раньше, он поздно хватился.<br/> Зачем позволяла она ему ребенком так заглядываться на себя и делала из него, что хотела? Отчего не нашлось у него ума вовремя отказаться от нее, когда она сама на этом настаивала зимою перед их свадьбой? Разве он не понимает, что она любит не его, а свою благородную задачу по отношению к нему, свой олицетворенный подвиг? Что общего между этой вдохновенной и похвальною миссией и настоящей семейной жизнью? Хуже всего то, что он по сей день любит её с прежнею силой. Она умопомрачительно хороша. А может быть и у него это не любовь, а благодарная растерянность перед её красотою и великодушием?<br/> Фу ты, разберись-ка в этом! Тут сам чорт ногу сломит.<br/> Так что же в таком случае делать? Освободить Лару и Катеньку от этой подделки? Это даже важнее, чем освободиться самому. Да, но как? Развестись? Утопиться? — Фу, какая гадость, — возмутился он. — Ведь я никогда не пойду на это.<br/> Тогда зачем называть эти эффектные мерзости хотя бы в мыслях?<br/> Он посмотрел на звезды, словно спрашивая у них совета. Они мерцали, частые и редкие, крупные и мелкие, синие и радужно-переливчатые. Неожиданно их мерцание затмилось, и двор с домом, лодкою и сидящим на ней Антиповым озарился резким, мечущимся светом, словно кто-то бежал с поля к воротам, размахивая зажженным факелом. Это, выбрасывая в небо клубы желтого, огнем пронизанного дыма, шел мимо переезда на запад воинский поезд, как они без счету проходили тут днем и ночью начиная с прошлого года.<br/> Павел Павлович улыбнулся, встал с лодки и пошел спать.<br/> Желаемый выход нашелся.

