### 7 {-}

Лариса Федоровна обомлела и сначала не поверила своим ушам, когда узнала о Пашином решении. — Бессмыслица. Очередная причуда, — подумала она. — Не обращать внимания, и сам обо всем забудет.<br/> Но выяснилось, что приготовлениям мужа уже две недели давности, бумаги в воинском присутствии, в гимназии имеется заместитель, и из Омска пришло извещение о его приеме в тамошнее военное училище. Подошли сроки его отъезда.<br/> Лара завыла, как простая баба, и, хватая Антипова за руки, стала валяться у него в ногах.<br/> — Паша, Пашенька, — кричала она, — на кого ты меня и Катеньку оставляешь? Не делай этого, не делай! Ничего не поздно. Я все исправлю. Да ты ведь толком и доктору-то не показывался. С твоим-то сердцем. Стыдно? А приносить семью в жертву какому-то сумасшествию не стыдно? Добровольцем! Всю жизнь смеялся над Родькой пошляком и вдруг завидно стало!<br/> Самому захотелось саблей позвенеть, поофицерствовать. Паша, что с тобой, я не узнаю тебя! Подменили тебя, что ли, или ты белены объелся? Скажи мне на милость, скажи честно, ради Христа, без заученных фраз, это ли нужно России?<br/> Вдруг она поняла, что дело не в этом. Неспособная осмыслить частности, она уловила главное. Она угадала, что Патуля заблуждается насчет её отношения к нему. Он не оценил материнского чувства, которое она всю жизнь подмешивает в свою нежность к нему, и не догадывается, что такая любовь больше обыкновенной женской.<br/> Она закусила губы, вся внутренне съежилась, как побитая, и, ничего не говоря и молча глотая слезы, стала собирать мужа в дорогу.<br/> Когда он уехал, ей показалось, что стало тихо во всем городе и даже в меньшем количестве стали летать по небу вороны. «Барыня, барыня», — безуспешно окликала её Марфутка.<br/> «Мама, мамочка», — без конца лепетала Катенька, дергая её за рукав. Это было серьезнейшее поражение в её жизни. Лучшие, светлейшие её надежды рухнули.<br/> По письмам из Сибири Лара знала все о муже. Скоро у него наступило просветление. Он очень тосковал по жене и дочери.<br/> Через несколько месяцев Павла Павловича выпустили досрочно прапорщиком и так же неожиданно отправили с назначением в действующую армию. Он проехал в крайней экстренности далеко стороной мимо Юрятина и в Москве не имел времени с кем-либо повидаться.<br/> Стали приходить его письма с фронта, более оживленные и не такие печальные, как из Омского училища. Антипову хотелось отличиться, чтобы в награду за какую-нибудь военную заслугу или в результате легкого ранения отпроситься в отпуск на свидание с семьей. Возможность выдвинуться представилась.<br/> Вслед за недавно совершенным прорывом, который стал впоследствии известен под именем Брусиловского, армия перешла в наступление. Письма от Антипова прекратились. Вначале это не беспокоило Лару. Пашино молчание она объясняла развивающимися военными действиями и невозможностью писать на маршах.<br/> Осенью движение армии приостановилось. Войска окапывались.<br/> Но об Антипове по-прежнему не было ни слуху ни духу. Лариса Федоровна стала тревожиться и наводить справки, сначала у себя в Юрятине, а потом по почте в Москве и на фронте, по прежнему полевому адресу Пашиной части. Нигде ничего не знали, ниоткуда не приходило ответа.<br/> Как многие дамы-благотворительницы в уезде, Лариса Федоровна с самого начала войны оказывала посильную помощь в госпитале, развернутом при Юрятинской земской больнице.<br/> Теперь она занялась серьезно начатками медицины и сдала при больнице экзамен на звание сестры милосердия.<br/> В этом качестве она отпросилась на полгода со службы из гимназии, оставила квартиру в Юрятине на попечение Марфутки и с Катенькой на руках поехала в Москву. Тут она пристроила дочь у Липочки, муж которой, германский подданный Фризенданк, вместе с другими гражданскими пленными был интернирован в Уфе.<br/> Убедившись в бесполезности своих розысков на расстоянии, Лариса Федоровна решила перенести их на место недавних происшествий. С этою целью она поступила сестрой на санитарный поезд, отправлявшийся через город Лиски в Мезо-Лаборч, на границу Венгрии. Так называлось место, откуда Паша написал ей свое последнее письмо.

