### 8 {-}

На фронт в штаб дивизии пришел поезд-баня, оборудованный на средства жертвователей Татьянинским комитетом помощи раненым.<br/> В классном вагоне длинного поезда, составленного из коротких некрасивых теплушек, приехали гости, общественные деятели из Москвы, с подарками солдатам и офицерам. В их числе был Гордон. Он узнал, что дивизионный лазарет, в котором, по его сведениям, работал друг его детства Живаго, размещен в близлежащей деревне.<br/> Гордон достал разрешение, необходимое для движения по прифронтовой зоне, и с пропуском в руках поехал навестить приятеля на отправлявшейся в ту сторону фурманке.<br/> Возчик, белорус или литовец, говорил по-русски. Страх шпиономании сводил все слова к одному казенному, наперед известному образцу. Показная благонамеренность бесед не располагала к разговорам. Большую часть пути едущий и возница молчали.<br/> В штабе, где привыкли передвигать целые армии и меряли расстояния стоверстными переходами, уверяли, будто деревня где-то рядом, верстах в двадцати или двадцати пяти. На самом деле до нее оказалось больше восьмидесяти.<br/> Всю дорогу в части горизонта, приходившейся налево к направлению их движения, недружелюбно урчало и погромыхивало.<br/> Гордон ни разу в жизни не был свидетелем землетрясения. Но он правильно рассудил, что угрюмое и за отдаленностью еле различимое брюзжание вражеской артиллерии более всего сравнимо с подземными толчками и гулами вулканического происхождения.<br/> Когда завечерело, низ неба в той стороне вспыхнул розовым трепещущим огнем, который не потухал до самого утра.<br/> Возница вез Гордона мимо разрушенных деревень. Часть их была покинута жителями. В других — люди ютились в погребах глубоко под землею. Такие деревни представляли груды мусора и щебня, которые тянулись так же в линию, как когда-то дома. Эти сгоревшие селения были сразу обозримы из конца в конец, как пустыри без растительности. На их поверхности копошились старухи погорелки, каждая на своем собственном пепелище, что-то откапывая в золе и все время куда-то припрятывая, и воображали себя укрытыми от посторонних взоров, точно вокруг них были прежние стены. Они встречали и провожали Гордона взглядом, как бы вопрошавшим, скоро ли опомнятся на свете и вернутся в жизни покой и порядок.<br/> Ночью навстречу едущим попался разъезд. Им велели своротить с грунтовой дороги обратно и объезжать эти места кружным проселком. Возчик не знал новой дороги. Они часа два проплутали без толку. Перед рассветом путник с возницею приехали в селение, носившее требуемое название. В нем ничего не слыхали о лазарете. Скоро выяснилось, что в округе две одноименных деревни, эта и разыскиваемая. Утром они достигли цели. Когда Гордон проезжал околицей, издававшей запах аптекарской ромашки и йодоформа, он думал, что не будет заночевывать у Живаго, а, проведя день в его обществе, вечером выедет назад на железнодорожную станцию к оставшимся товарищам. Обстоятельства задержали его тут больше недели.

