### 9 {-}

В эти дни фронт зашевелился. На нем происходили внезапные перемены. К югу от местности, в которую заехал Гордон, одно из наших соединений удачной атакой отдельных составлявших его частей прорвало укрепленные позиции противника. Развивая свой удар, группа наступающих все глубже врезалась в его расположение. За нею следовали вспомогательные части, расширявшие прорыв. Постепенно отставая, они оторвались от головной группы. Это повело к её пленению. В этой обстановке взят был в плен прапорщик Антипов, вынужденный к этому сдачею своей полуроты.<br/> О нем ходили превратные слухи. Его считали погибшим и засыпанным землею во взрывной воронке. Так передавали со слов его знакомого, подпоручика одного с ним полка Галиуллина, якобы видевшего его гибель в бинокль с наблюдательного пункта, когда Антипов пошел со своими солдатами в атаку.<br/> Перед глазами Галиуллина было привычное зрелище атакующей части. Ей предстояло пройти быстрыми шагами, почти бегом, разделявшее обе армии осеннее поле, поросшее качающейся на ветру сухою полынью и неподвижно торчащим кверху колючим будяком. Дерзостью своей отваги атакующие должны были выманить на штыки себе или забросать гранатами и уничтожить засевших в противоположных окопах австрийцев. Поле казалось бегущим бесконечным. Земля ходила у них под ногами, как зыбкая болотная почва. Сначала впереди, а потом вперемежку вместе с ними бежал их прапорщик, размахивая над головой револьвером и крича во весь, до ушей разодранный рот «ура», которого ни он, ни бежавшие вокруг солдаты не слыхали. Через правильные промежутки бежавшие ложились на землю, разом подымались на ноги и с возобновленными криками бежали дальше. Каждый раз вместе с ними, но совсем по-другому, нежели они, падали во весь рост, как высокие деревья при валке леса, отдельные подбитые и больше не вставали.<br/> — Перелеты. Телефонируйте на батарею, — сказал встревоженный Галиуллин стоявшему рядом артиллерийскому офицеру. — Да нет. Они правильно делают, что перенесли огонь поглубже.<br/> В это время атакующие подошли на сближение с неприятелем.<br/> Огонь прекратили. В наставшей тишине у стоявших на наблюдательном заколотились сердца явственно и часто, словно они были на месте Антипова и, как он, подведя людей к краю австрийской щели, в следующую минуту должны были выказать чудеса находчивости и храбрости. В это мгновение впереди один за другим взорвались два немецких шестнадцатидюймовых снаряда.<br/> Черные столбы земли и дыма скрыли все последующее.<br/> — Йэ алла! Готово! Кончал базар! — побледневшими губами прошептал Галиуллин, считая прапорщика и солдат погибшими.<br/> Третий снаряд лег совсем около наблюдательного. Низко пригибаясь к земле, все поспешили убраться с него подальше.<br/> Галиуллин спал в одном блиндаже с Антиповым. Когда в полку примирились с мыслью, что он убит и больше не вернется, Галиуллину, хорошо знавшему Антипова, поручили взять на хранение его имущество для передачи в будущем его жене, фотографические карточки которой во множестве попадались среди вещей Антипова.<br/> Недавний прапорщик из вольноопределяющихся, механик Галиуллин, сын дворника Гимазетдина с тиверзинского двора и в далеком прошлом — слесарский ученик, которого избивал мастер Худолеев, своим возвышением обязан был своему былому истязателю.<br/> Выйдя в прапорщики, Галиуллин неизвестно как и помимо своей воли попал на теплое и укромное место в один из тыловых захолустных гарнизонов. Там он распоряжался командой полуинвалидов, с которыми такие же дряхлые инструктора-ветераны по утрам проходили забытый ими строй.<br/> Кроме того, Галиуллин проверял, правильно ли они расставляют караулы у интендантских складов. Это было беззаботное житье — больше ничего от него не требовалось. Как вдруг вместе с пополнением, состоявшим из ополченцев старых сроков и поступившим из Москвы в его распоряжение, прибыл слишком хорошо ему известный Петр Худолеев.<br/> — А, старые знакомые! — проговорил, хмуро усмехаясь, Галиуллин.<br/> — Так точно, ваше благородие, — ответил Худолеев, стал во фронт и откозырял.<br/> Так просто это не могло кончиться. При первой же строевой оплошности прапорщик наорал на нижнего чина, а когда ему показалось, что солдат смотрит не прямо во все глаза на него, а как-то неопределенно в сторону, хряснул его по зубам и отправил на двое суток на хлеб и воду на гауптвахту.<br/> Теперь каждое движение Галиуллина пахло отместкою за старое. А сводить счеты таким способом в условиях палочной субординации было игрой слишком беспроигрышной и неблагородной. Что было делать? Оставаться обоим в одном месте было дальше невозможно. Но под каким предлогом и куда мог офицер переместить солдата из назначенной ему части, кроме отдачи его в дисциплинарную? С другой стороны, какие основания мог придумать Галиуллин для просьбы о собственном переводе?<br/> Оправдываясь скукой и бесполезностью гарнизонной службы, Галиуллин отпросился на фронт. Это зарекомендовало его с хорошей стороны, а когда в ближайшем деле он показал другие свои качества, выяснилось, что это отличный офицер, и он быстро был произведен из прапорщиков в подпоручики.<br/> Галиуллин знал Антипова с тиверзинских времен. В девятьсот пятом году, когда Паша Антипов полгода прожил у Тиверзиных, Юсупка ходил к нему в гости и играл с ним по праздникам. Тогда же он раз или два видел у них Лару. С тех пор он ничего о них не слыхал. Когда в их полк попал Павел Павлович из Юрятина, Галиуллин поражен был происшедшею со старым приятелем переменой. Из застенчивого, похожего на девушку и смешливого чистюли-шалуна вышел нервный, все на свете знающий, презрительный ипохондрик. Он был умен, очень храбр, молчалив и насмешлив. Временами, глядя на него, Галиуллин готов был поклясться, что видит в тяжелом взгляде Антипова, как в глубине окна, кого-то второго, прочно засевшую в нем мысль, или тоску по дочери, или лицо его жены. Антипов казался заколдованным, как в сказке. И вот его не стало, и на руках Галиуллина остались бумаги и фотографии Антипова и тайна его превращения.<br/> Рано или поздно до Галиуллина должны были дойти Ларины запросы. Он собрался ответить ей. Но было горячее время.<br/> Ответить по-настоящему он был не в силах. А ему хотелось подготовить её к ожидавшему её удару. Так он все откладывал большое обстоятельное письмо к ней, пока не узнал, будто она сама где-то на фронте, сестрою. И было неизвестно, куда адресовать ей теперь письмо.

