### 10 {-}

— Ну как? Будут сегодня лошади? — спрашивал Гордон доктора Живаго, когда тот приходил днем домой обедать в галицийскую избу, в которой они стояли.<br/> — Да какие там лошади? И куда ты поедешь, когда ни вперед ни назад. Кругом страшная путаница. Никто ничего не понимает.<br/> На юге мы обошли или прорвали немцев в нескольких местах, причем, говорят, несколько наших распыленных единиц попали при этом в мешок, а на севере немцы перешли Свенту, считавшуюся в этом месте непроходимой. Это кавалерия, численностью до корпуса. Они портят железные дороги, уничтожают склады и, по-моему, окружают нас. Видишь, какая картина. А ты говоришь — лошади. Ну, живее, Карпенко, накрывай и поворачивайся. Что у нас сегодня? А, телячьи ножки. Великолепно.<br/> Санитарная часть с лазаретом и всеми подведомственными отделами была разбросана по деревне, которая чудом уцелела.<br/> Дома ее, поблескивавшие на западный манер узкими многостворчатыми окнами во всю стену, были до последнего сохранны.<br/> Стояло бабье лето, последние ясные дни жаркой золотой осени. Днем врачи и офицеры растворяли окна, били мух, черными роями ползавших по подоконникам и белой оклейке низких потолков, и, расстегнув кителя и гимнастерки, обливались потом, обжигаясь горячими щами или чаем, а ночью садились на корточки перед открытыми печными заслонками, раздували потухающие угли под неразгорающимися сырыми дровами и со слезящимися от дыма глазами ругали денщиков, не умеющих топить по-человечески.<br/> Была тихая ночь. Гордон и Живаго лежали друг против друга на лавках у двух противоположных стен. Между ними был обеденный стол и длинное, узенькое, от стены к стене тянувшееся окно. В комнате было жарко натоплено и накурено.<br/> Они открыли в окне две крайних оконницы и вдыхали ночную осеннюю свежесть, от которой потели стекла.<br/> По обыкновению они разговаривали, как все эти дни и ночи.<br/> Как всегда, розовато пламенел горизонт в стороне фронта, и когда в ровную, ни на минуту не прекращавшуюся воркотню обстрела падали более низкие, отдельно отличимые и увесистые удары, как бы сдвигавшие почву чуть-чуть в сторону, Живаго прерывал разговор из уважения к звуку, выдерживал паузу и говорил:<br/> — Это Берта, немецкое шестнадцатидюймовое, в шестьдесят пудов весом штучка, — и потом возобновлял беседу, забывая о чем был разговор.<br/> — Чем это так все время пахнет в деревне? — спрашивал Гордон. — Я с первого дня заметил. Так слащаво-приятно и противно. Как мышами.<br/> — А, я знаю, о чем ты. Это — конопля. Тут много конопляников. Конопля сама по себе издает томящий и назойливый запах падали. Кроме того, в районе военных действий, когда в коноплю заваливаются убитые, они долго остаются необнаруженными и разлагаются. Трупный запах очень распространен здесь, это естественно. Опять Берта. Ты слышишь?<br/> В течение этих дней они переговорили обо всем на свете.<br/> Гордон знал мысли приятеля о войне и о духе времени. Юрий Андреевич рассказал ему, с каким трудом он привыкал к кровавой логике взаимоистребления, к виду раненых, в особенности к ужасам некоторых современных ранений, к изуродованным выживающим, превращенным нынешнею техникой боя в куски обезображенного мяса.<br/> Каждый день Гордон куда-нибудь попадал, сопровождая Живаго, и благодаря ему что-нибудь видел. Он, понятно, сознавал всю безнравственность праздного разглядывания чужого мужества и того, как другие нечеловеческим усилием воли побеждают страх смерти и чем при этом жертвуют и как рискуют. Но бездеятельные и беспоследственные вздохи по этому поводу казались ему ничуть не более нравственными. Он считал, что нужно вести себя сообразно положению, в которое ставит тебя жизнь, честно и естественно.<br/> Что от вида раненых можно упасть в обморок, он проверил на себе при поездке в летучий отряд Красного Креста, который работал к западу от них, на полевом перевязочном пункте почти у самых позиций.<br/> Они приехали на опушку большого леса, наполовину срезанного артиллерийским огнем. В поломанном и вытоптанном кустарнике валялись вверх тормашками разбитые и покореженные орудийные передки. К дереву была привязана верховая лошадь. С деревянной постройки лесничества, видневшейся в глубине, была снесена половина крыши. Перевязочный пункт помещался в конторе лесничества и в двух больших серых палатках, разбитых через дорогу от лесничества, посреди леса.<br/> — Напрасно я взял тебя сюда, — сказал Живаго. — Окопы совсем рядом, верстах в полутора или двух, а наши батареи вон там, за этим лесом. Слышишь, что творится? Не изображай, пожалуйста, героя — не поверю. У тебя душа теперь в пятках, и это естественно. Каждую минуту может измениться положение. Сюда будут залетать снаряды.<br/> На земле у лесной дороги, раскинув ноги в тяжелых сапогах, лежали на животах и спинах запыленные и усталые молодые солдаты в пропотевших на груди и лопатках гимнастерках — остаток сильно поредевшего отделения. Их вывели из продолжающегося четвертые сутки боя и отправляли в тыл на короткий отдых. Солдаты лежали как каменные, у них не было сил улыбаться и сквернословить, и никто не повернул головы, когда в глубине леса на дороге загромыхало несколько быстро приближающихся таратаек. Это на рысях, в безрессорных тачанках, которые подскакивали кверху и доламывали несчастным кости и выворачивали внутренности, подвозили раненых к перевязочному пункту, где им подавали первую помощь, наспех бинтовали и в некоторых, особо экстренных случаях оперировали на скорую руку. Всех их полчаса тому назад, когда огонь стих на короткий промежуток, в ужасающем количестве вынесли с поля перед окопами. Добрая половина их была без сознания.<br/> Когда их подвезли к крыльцу конторы, с него спустились санитары с носилками и стали разгружать тачанки. Из палатки, придерживая её полости снизу рукою, выглянула сестра милосердия. Это была не её смена. Она была свободна. В лесу за палатками громко бранились двое. Свежий высокий лес гулко разносил отголоски их спора, но слов не было слышно. Когда привезли раненых, спорящие вышли на дорогу, направляясь к конторе. Горячащийся офицерик кричал на врача летучего отряда, стараясь добиться от него, куда переехал ранее стоявший тут в лесу артиллерийский парк. Врач ничего не знал, это его не касалось. Он просил офицера отстать и не кричать, потому что привезли раненых и у него есть дело, а офицерик не унимался и разносил Красный Крест и артиллерийское ведомство и всех на свете. К врачу подошел Живаго. Они поздоровались и поднялись в лесничество. Офицер с чуть-чуть татарским акцентом, продолжая громко ругаться, отвязал лошадь от дерева, вскочил на нее и ускакал по дороге в глубину леса. А сестра все смотрела и смотрела.<br/> Вдруг лицо её исказилось от ужаса.<br/> — Что вы делаете? Вы с ума сошли, — крикнула она двум легко раненным, которые шли без посторонней помощи между носилками на перевязку, и, выбежав из палатки, бросилась к ним на дорогу.<br/> На носилках несли несчастного, особенно страшно и чудовищно изуродованного. Дно разорвавшегося стакана, разворотившего ему лицо, превратившего в кровавую кашу его язык и зубы, но не убившего его, засело у него в раме челюстных костей, на месте вырванной щеки. Тоненьким голоском, не похожим на человеческий, изувеченный испускал короткие, обрывающиеся стоны, которые каждый должен был понять как мольбу поскорее прикончить его и прекратить его немыслимо затянувшиеся мучения.<br/> Сестре милосердия показалось, что под влиянием его стонов шедшие рядом легко раненные собираются голыми руками тащить из его щеки эту страшную железную занозу.<br/> — Что вы, разве можно так? Это хирург сделает, особыми инструментами. Если только придется. (Боже, Боже, прибери его, не заставляй меня сомневаться в твоем существовании!) В следующую минуту при поднятии на крыльцо изуродованный вскрикнул, содрогнулся всем телом и испустил дух.<br/> Скончавшийся изуродованный был рядовой запаса Гимазетдин, кричавший в лесу офицер — его сын, подпоручик Галиуллин, сестра была Лара, Гордон и Живаго — свидетели, все они были вместе, все были рядом, и одни не узнали друг друга, другие не знали никогда, и одно осталось навсегда неустановленным, другое стало ждать обнаружения до следующего случая, до новой встречи.

