### 11 {-}

В этой полосе чудесным образом сохранились деревни. Они составляли необъяснимо уцелевший островок среди моря разрушений. Гордон и Живаго возвращались вечером домой.<br/> Садилось солнце. В одной из деревень, мимо которой они проезжали, молодой казак при дружном хохоте окружающих подбрасывал кверху медный пятак, заставляя старого седобородого еврея в длинном сюртуке ловить его. Старик неизменно упускал монету. Пятак, пролетев мимо его жалко растопыренных рук, падал в грязь. Старик нагибался за медяком, казак шлепал его при этом по заду, стоявшие кругом держались за бока и стонали от хохота, В этом и состояло все развлечение. Пока что оно было безобидно, но никто не мог поручиться, что оно не примет более серьезного оборота. Из-за противоположной избы выбегала на дорогу, с криками протягивала руки к старику и каждый раз вновь боязливо скрывалась его старуха. В окно избы смотрели на дедушку и плакали две девочки.<br/> Ездовой, которому все это показалось черезвычайно уморительным, повел лошадей шагом, чтобы дать время господам позабавиться. Но Живаго, подозвав казака, выругал его и велел прекратить глумление.<br/> — Слушаюсь, ваше благородие, — с готовностью ответил тот.<br/> — Мы ведь не знамши, только так, для смеха.<br/> Всю остальную дорогу Гордон и Живаго молчали.<br/> — Это ужасно, — начал в виду их собственной деревни Юрий Андреевич. — Ты едва ли представляешь себе, какую чашу страданий испило в эту войну несчастное еврейское население.<br/> Ее ведут как раз в черте его вынужденной оседлости. И за изведанное, за перенесенные страдания, поборы и разорение ему еще вдобавок платят погромами, издевательствами и обвинением в том, что у этих людей недостаточно патриотизма. А откуда быть ему, когда у врага они пользуются всеми правами, а у нас подвергаются одним гонениям. Противоречива самая ненависть к ним, её основа. Раздражает как раз то, что должно было бы трогать и располагать. Их бедность и скученность, их слабость и неспособность отражать удары. Непонятно. Тут что-то роковое.<br/> Гордон ничего не отвечал ему.

