### 12 {-}

И вот опять они лежали по обе стороны длинного узкого окна, была ночь, и они разговаривали.<br/> Живаго рассказывал Гордону, как он видел на фронте государя. Он хорошо рассказывал.<br/> Это было в его первую весну на фронте. Штаб части, к которой он был прикомандирован, стоял в Карпатах, в котловине, вход в которую со стороны Венгерской долины запирала эта войсковая часть.<br/> На дне котловины была железнодорожная станция. Живаго описывал Гордону внешний вид местности, горы, поросшие могучими елями и соснами, с белыми клоками зацепившихся за них облаков и каменными отвесами серого шифера и графита, которые проступали среди лесов, как голые проплешины, вытертые в густой шкуре. Было сырое, серое, как этот шифер, темное апрельское утро, отовсюду спертое высотами и оттого неподвижное и душное. Парило. Пар стоял над котловиной, и все курилось, все струями дыма тянулось вверх — паровозный дым со станции, серая испарина лугов, серые горы, темные леса, темные облака.<br/> В те дни государь объезжал Галицию. Вдруг стало известно, что он посетит часть, расположенную тут, шефом которой он состоял.<br/> Он мог прибыть с минуты на минуту. На перроне выставили почетный караул для его встречи. Прошли час или два томительного ожидания. Потом быстро один за другим прошли два свитских поезда. Спустя немного подошел царский.<br/> В сопровождении великого князя Николая Николаевича государь обошел выстроившихся гренадер. Каждым слогом своего тихого приветствия он, как расплясавшуюся воду в качающихся ведрах, поднимал взрывы и всплески громоподобно прокатывавшегося ура.<br/> Смущенно улыбавшийся государь производил впечатление более старого и опустившегося, чем на рублях и медалях. У него было вялое, немного отекшее лицо. Он поминутно виновато косился на Николая Николаевича, не зная, что от него требуется в данных обстоятельствах, и Николай Николаевич, почтительно наклоняясь к его уху, даже не словами, а движением брови или плеча выводил его из затруднения.<br/> Царя было жалко в это серое и теплое горное утро, и было жутко при мысли, что такая боязливая сдержанность и застенчивость могут быть сущностью притеснителя, что этою слабостью казнят и милуют, вяжут и решают.<br/> — Он должен был произнесть что-нибудь такое вроде: я, мой меч и мой народ, как Вильгельм, или что-нибудь в этом духе. Но обязательно про народ, непременно. Но, понимаешь ли ты, он был по-русски естественен и трагически выше этой пошлости. Ведь в России немыслима эта театральщина. Потому что ведь это театральщина, не правда ли? Я еще понимаю, чем были народы при Цезаре, галлы там какие-нибудь, или свевы, или иллирийцы. Но ведь с тех пор это только выдумка, существующая для того, чтобы о ней произносили речи цари, и деятели, и короли: народ, мой народ.<br/> Теперь фронт наводнен корреспондентами и журналистами.<br/> Записывают «наблюдения», изречения народной мудрости, обходят раненых, строят новую теорию народной души. Это своего рода новый Даль, такой же выдуманный, лингвистическая графомания словесного недержания. Это один тип. А есть еще другой.<br/> Отрывистая речь, «штрихи и сценки», скептицизм, мизантропия. К примеру, у одного (я сам читал) такие сентенции: «Серый день, как вчера. С утра дождь, слякоть. Гляжу в окно на дорогу. По ней бесконечной вереницей тянутся пленные. Везут раненых. Стреляет пушка. Снова стреляет, сегодня, как вчера, завтра, как сегодня, и так каждый день и каждый час…» Ты подумай только, как проницательно и остроумно!<br/> Однако почему он обижается на пушку? Какая странная претензия требовать от пушки разнообразия! Отчего вместо пушки лучше не удивится он самому себе, изо дня в день стреляющему перечислениями, запятыми и фразами, отчего не прекратит стрельбы журнальным человеколюбием, торопливым, как прыжки блохи? Как он не понимает, что это он, а не пушка, должен быть новым и не повторяться, что из блокнотного накапливания большого количества бессмыслицы никогда не может получиться смысла, что фактов нет, пока человек не внес в них чего-то своего, какой-то доли вольничающего человеческого гения, какой-то сказки.<br/> — Поразительно верно, — прервал его Гордон. — Теперь я тебе отвечу по поводу сцены, которую мы сегодня видали. Этот казак, глумившийся над бедным патриархом, равно как и тысячи таких же случаев, это, конечно, примеры простейшей низости, по поводу которой не философствуют, а бьют по морде, дело ясно.<br/> Но к вопросу о евреях в целом философия приложима, и тогда она оборачивается неожиданной стороной. Но ведь тут я не скажу тебе ничего нового. Все эти мысли у меня, как и у тебя, от твоего дяди.<br/> Что такое народ? — спрашиваешь ты. Надо ли нянчиться с ним и не больше ли делает для него тот, кто, не думая о нем, самою красотой и торжеством своих дел увлекает его за собой во всенародность и, прославив, увековечивает? Ну конечно, конечно. Да и о каких народах может быть речь в христианское время? Ведь это не просто народы, а обращенные, претворенные народы, и все дело именно в превращении, а не в верности старым основаниям. Вспомним Евангелие. Что оно говорило на эту тему? Во-первых, оно не было утверждением: так-то, мол, и так-то. Оно было предложением наивным и несмелым. Оно предлагало: хотите существовать по-новому, как не бывало, хотите блаженства духа? И все приняли предложение, захваченные на тысячелетия.<br/> Когда оно говорило, в царстве Божием нет эллина и иудея, только ли оно хотело сказать, что перед Богом все равны? Нет, для этого оно не требовалось, это знали до него философы Греции, римские моралисты, пророки Ветхого завета. Но оно говорило: в том сердцем задуманном новом способе существования и новом виде общения, которое называется царством Божиим, нет народов, есть личности.<br/> Вот ты говорил, факт бессмысленен, если в него не внести смысла. Христианство, мистерия личности и есть именно то самое, что надо внести в факт, чтобы он приобрел значение для человека.<br/> И мы говорили о средних деятелях, ничего не имеющих сказать жизни и миру в целом, о второразрядных силах, заинтересованных в узости, в том, чтобы все время была речь о каком-нибудь народе, предпочтительно малом, чтобы он страдал, чтобы можно было судить и рядить и наживаться на жалости. Полная и безраздельная жертва этой стихии — еврейство. Национальной мыслью возложена на него мертвящая необходимость быть и оставаться народом и только народом в течение веков, в которые силою, вышедшей некогда из его рядов, весь мир избавлен от этой принижающей задачи. Как это поразительно! Как это могло случиться? Этот праздник, это избавление от чертовщины посредственности, этот взлет над скудоумием будней, все это родилось на их земле, говорило на их языке и принадлежало к их племени. И они видели и слышали это и это упустили? Как могли они дать уйти из себя душе такой поглощающей красоты и силы, как могли думать, что рядом с её торжеством и воцарением они останутся в виде пустой оболочки этого чуда, им однажды сброшенной. В чьих выгодах это добровольное мученичество, кому нужно, чтобы веками покрывалось осмеянием и истекало кровью столько ни в чем не повинных стариков, женщин и детей, таких тонких и способных к добру и сердечному общению! Отчего так лениво бездарны пишущие народолюбцы всех народностей? Отчего властители дум этого народа не пошли дальше слишком легко дающихся форм мировой скорби и иронизирующей мудрости? Отчего, рискуя разорваться от неотменимости своего долга, как рвутся от давления паровые котлы, не распустили они этого, неизвестно за что борющегося и за что избиваемого отряда? Отчего не сказали: «Опомнитесь. Довольно. Больше не надо. Не называйтесь, как раньше. Не сбивайтесь в кучу, разойдитесь. Будьте со всеми. Вы первые и лучшие христиане мира. Вы именно то, чему вас противопоставляли самые худшие и слабые из вас».

