### 13 {-}

На другой день, придя к обеду, Живаго сказал:<br/> — Вот тебе не терпится уехать, вот ты и накликал. Не могу сказать «твое счастье», ибо какое же это счастье, что нас опять теснят или поколотили? Дорога на восток свободна, а с запада нас жмут. Приказ всем военно-санитарным учреждениям сворачиваться. Снимаемся завтра или послезавтра. Куда — неизвестно. А белье Михаила Григорьевича, Карпенко, конечно, не стирано. Вечная история. Кума, кума, а спроси его толком, какая это кума, так он сам не знает, болван.<br/> Он не слушал, что плел в свое оправдание денщик-санитар, и не обращал внимания на Гордона, огорченного тем, что он заносил живаговское белье и уезжает в его рубашке. Живаго продолжал:<br/> — Эх, походное наше житье, цыганское кочевье. Когда сюда въезжали, все было не по мне — и печь не тут, и низкий потолок, и грязь, и духота. А теперь, хоть убей, не могу вспомнить, где мы до этого стояли. И, кажется, век бы тут прожил, глядя на этот угол печи с солнцем на изразцах и движущейся по ней тенью придорожного дерева.<br/> Они стали, не торопясь, укладываться.<br/> Ночью их разбудили шум и крики, стрельба и беготня. Деревня была зловеще озарена. Мимо окна мелькали тени. За стеной проснулись и задвигались хозяева.<br/> — Сбегай на улицу, Карпенко, спроси, по какому случаю содом, — сказал Юрий Андреевич.<br/> Скоро все стало известно. Сам Живаго, наскоро одевшись, ходил в лазарет, чтобы проверить слухи, которые оказались правильными. Немцы сломили на этом участке сопротивление.<br/> Линия обороны передвинулась ближе к деревне и все приближалась. Деревня была под обстрелом. Лазарет и учреждения спешно вывозили, не дожидаясь приказа об эвакуации. Всё предполагали закончить до рассвета.<br/> — Ты поедешь с первым эшелоном, линейка сейчас отходит, но я сказал, чтобы тебя подождали. Ну прощай. Я провожу тебя и посмотрю, как тебя усадят.<br/> Они бежали на другой конец деревни, где снаряжали отряд.<br/> Пробегая мимо домов, они нагибались и прятались за их выступами. По улице пели и жужжали пули. С перекрестков, пересекаемых дорогами в поле, было видно, как над ним зонтами пламени раскидывались разрывы шрапнели.<br/> — А ты как же? — на бегу спрашивал Гордон.<br/> — Я потом. Надо будет еще вернуться домой, за вещами. Я со второй партией.<br/> Они простились у околицы. Несколько телег и линейка, из которых состоял обоз, двинулись, наезжая друг на друга и постепенно выравниваясь. Юрий Андреевич помахал рукой уезжающему товарищу. Их освещал огонь загоревшегося сарая.<br/> Так же стараясь идти вдоль изб, под прикрытием их углов, Юрий Андреевич быстро направился к себе назад. За два дома до его крыльца его свалила с ног воздушная волна разрыва и ранила шрапнельная пулька. Юрий Андреевич упал посреди дороги, обливаясь кровью, и потерял сознание.

