### 14 {-}

Эвакуационный госпиталь был затерян в одном из городков Западного края у железной дороги, по соседству со ставкою.<br/> Стояли теплые дни конца февраля. В офицерской палате для выздоравливающих по просьбе Юрия Андреевича, находившегося тут на излечении, было отворено окно близ его койки.<br/> Приближался час обеда. Больные коротали оставшееся до него время кто чем мог. Им сказали, что в госпиталь поступила новая сестра и сегодня в первый раз будет их обходить. Лежавший против Юрия Андреевича Галиуллин просматривал только что полученные «Речь» и «Русское слово» и возмущался пробелами, оставленными в печати цензурою. Юрий Андреевич читал письма от Тони, доставленные полевою почтой сразу в том количестве, в каком они там накопились. Ветер шевелил страницами писем и листами газеты. Послышались легкие шаги. Юрий Андреевич поднял от письма глаза. В палату вошла Лара.<br/> Юрий Андреевич и подпоручик каждый порознь, не зная этого друг о друге, её узнали. Она не знала никого из них. Она сказала:<br/> — Здравствуйте. Зачем окно открыто? Вам не холодно? — и подошла к Галиуллину.<br/> — На что жалуетесь? — спросила она и взяла его за руку, чтобы сосчитать пульс, но в ту же минуту выпустила её и села на стул у его койки, озадаченная.<br/> — Какая неожиданность, Лариса Федоровна, — сказал Галиуллин. — Я служил в одном полку с вашим мужем и знал Павла Павловича. У меня для вас собраны его вещи.<br/> — Не может быть, не может быть, — повторяла она. — Какая поразительная случайность. Так вы его знали? Расскажите же скорее, как все было? Ведь он погиб, засыпан землей? Ничего не скрывайте, не бойтесь. Ведь я все знаю.<br/> У Галиуллина не хватило духу подтвердить её сведения, почерпнутые из слухов. Он решил соврать ей, чтобы её успокоить.<br/> — Антипов в плену, — сказал он. — Он забрался слишком далеко вперед со своей частью во время наступления и очутился в одиночестве. Его окружили. Он был вынужден сдаться.<br/> Но Лара не поверила Галиуллину. Ошеломляющая внезапность разговора взволновала ее. Она не могла справиться с нахлынувшими слезами и не хотела плакать при посторонних. Она быстро встала и вышла из палаты, чтобы овладеть собою в коридоре.<br/> Через минуту она вернулась внешне спокойная. Она нарочно не глядела в угол на Галиуллина, чтобы снова не расплакаться.<br/> Подойдя прямо к койке Юрия Андреевича, она сказала рассеянно и заученно:<br/> — Здравствуйте. На что жалуетесь?<br/> Юрий Андреевич наблюдал её волнение и слезы, хотел спросить ее, что с ней, хотел рассказать ей, как дважды в жизни видел ее, гимназистом и студентом, но он подумал, что это выйдет фамильярно и она поймет его не правильно. Потом он вдруг вспомнил мертвую Анну Ивановну в гробу и Тонины крики тогда в Сивцевом, и сдержался, и вместо всего этого сказал:<br/> — Благодарю вас. Я сам врач и лечу себя собственными силами. Я ни в чем не нуждаюсь.<br/> — За что он на меня обиделся? — подумала Лара и удивленно посмотрела на этого курносого, ничем не замечательного незнакомца.<br/> Несколько дней была переменная, неустойчивая погода, теплый, заговаривающийся ветер ночами, которые пахли мокрой землею.<br/> И все эти дни поступали странные сведения из ставки, приходили тревожные слухи из дому, изнутри страны. Прерывалась телеграфная связь с Петербургом. Всюду, на всех углах заводили политические разговоры.<br/> В каждое дежурство сестра Антипова производила два обхода, утром и вечером, и перекидывалась ничего не значащими замечаниями с больными из других палат, с Галиуллиным, с Юрием Андреевичем. — Странный любопытный человек, — думала она. — Молодой и нелюбезный. Курносый и нельзя сказать, чтобы очень красивый. Но умный в лучшем смысле слова, с живым, подкупающим умом. Но дело не в этом. А дело в том, что надо поскорее заканчивать свои обязанности здесь и переводиться в Москву, поближе к Катеньке. А в Москве надо подавать на увольнение из сестер милосердия и возвращаться к себе в Юрятин на службу в гимназии. Ведь про бедного Патулечку все ясно, никакой надежды, тогда больше не к чему и оставаться в полевых героинях, ради его розысков только и было это нагорожено.<br/> Что теперь там с Катенькой? Бедная сиротка (тут она принималась плакать). Замечаются очень резкие перемены в последнее время. Недавно были святы долг перед родиной, военная доблесть, высокие общественные чувства. Но война проиграна, это — главное бедствие, и от этого всё остальное, все развенчано, ничто не свято.<br/> Вдруг все переменилось, тон, воздух, неизвестно как думать и кого слушаться. Словно водили всю жизнь за руку, как маленькую, и вдруг выпустили, учись ходить сама. И никого кругом, ни близких, ни авторитетов. Тогда хочется довериться самому главному, силе жизни или красоте или правде, чтобы они, а не опрокинутые человеческие установления управляли тобой, полно и без сожаления, полнее, чем бывало в мирной привычной жизни, закатившейся и упраздненной. Но в её случае, — вовремя спохватилась Лара, — такой целью и безусловностью будет Катенька. Теперь, без Патулечки, Лара только мать и отдаст все силы Катеньке, бедной сиротке.<br/> Юрию Андреевичу писали, что Гордон и Дудоров без его разрешения выпустили его книжку, что её хвалят и пророчат ему большую литературную будущность, и что в Москве сейчас очень интересно и тревожно, нарастает глухое раздражение низов, мы накануне чего-то важного, близятся серьезные политические события.<br/> Была поздняя ночь. Юрия Андреевича одолевала страшная сонливость. Он дремал с перерывами и воображал, что, наволновавшись за день, он не может уснуть, что он не спит. За окном позевывал и ворочался сонный, сонно дышащий ветер. Ветер плакал и лепетал: «Тоня, Шурочка, как я по вас соскучился, как мне хочется домой, за работу!» И под бормотание ветра Юрий Андреевич спал, просыпался и засыпал в быстрой смене счастья и страданья, стремительной и тревожной, как эта переменная погода, как эта неустойчивая ночь.<br/> Лара подумала: «Он проявил столько заботливости, сохранив эту память, эти бедные Патулечкины вещи, а я, такая свинья, даже не спросила, кто он и откуда».<br/> В следующий же утренний обход, восполняя упущенное и заглаживая след своей неблагодарности, она расспросила обо всем этом Галиуллина и заохала и заахала.<br/> «Господи, святая твоя воля! Брестская двадцать восемь, Тиверзины, революционная зима тысяча девятьсот пятого года!<br/> Юсупка? Нет. Юсупки не знала или не помню, простите. Но год-то, год-то и двор! Ведь это правда, ведь действительно были такой двор и такой год! О как живо она вдруг все это опять ощутила! И стрельбу тогда, и (как это, дай Бог памяти) «Христово мнение»! О с какою силою, как проницательно чувствуют в детстве, впервые! Простите, простите, как вас, подпоручик? Да, да, вы мне раз уже сказали. Спасибо, о какое спасибо вам, Осип Гимазетдинович, какие воспоминания, какие мысли вы во мне пробудили!»<br/> Весь день она ходила с «тем двором» в душе и все охала и почти вслух размышляла.<br/> Подумать только, Брестская, двадцать восемь! И вот опять стрельба, но во сколько раз страшней! Это тебе не «мальчики стреляют». А мальчики выросли и все тут, в солдатах, весь простой народ с тех дворов и из таких же деревень.<br/> Поразительно! Поразительно!<br/> В помещение, стуча палками и костылями, вошли, вбежали и приковыляли инвалиды и не носилочные больные из соседних палат, и наперебой закричали:<br/> — События чрезвычайной важности. В Петербурге уличные беспорядки. Войска петербургского гарнизона перешли на сторону восставших. Революция.

