## ЧАСТЬ пятая. ПРОЩАНЬЕ СО СТАРЫМ {-}

### 1 {-}

Городок назывался Мелюзеевым. Он стоял на черноземе. Тучей саранчи висела над его крышами черная пыль, которую поднимали валившие через него войска и обозы. Они двигались с утра до вечера в обоих направлениях, с войны и на войну, и нельзя было толком сказать, продолжается ли она, или уже кончилась.<br/> Каждый день без конца, как грибы, вырастали новые должности. И на все их выбирали. Его самого, поручика Галиуллина, и сестру Антипову, и еще несколько человек из их компании, наперечет жителей больших городов, людей сведущих и видавших виды.<br/> Они замещали посты в городском самоуправлении, служили комиссарами на мелких местах в армии и по санитарной части и относились к чередованию этих занятий, как к развлечению на открытом воздухе, как к игре в горелки. Но все чаще им хотелось с этих горелок домой, к своим постоянным занятиям.<br/> Работа часто и живо сталкивала Живаго с Антиповой.

### 2 {-}

В дожди черная пыль в городе превращалась в темно-коричневую слякоть кофейного цвета, покрывавшую его улицы, в большинстве немощеные.<br/> Городок был невелик. С любого места в нем тут же за поворотом открывалась хмурая степь, темное небо, просторы войны, просторы революции.<br/> Юрий Андреевич писал жене:<br/> «Развал и анархия в армии продолжаются. Предпринимают меры к поднятию у солдат дисциплины и боевого духа. Объезжал расположенные поблизости части.<br/> Наконец вместо постскриптума, хотя об этом я мог бы написать тебе гораздо раньше, — работаю я тут рука об руку с некоей Антиповой, сестрой милосердия из Москвы, уроженкой Урала.<br/> Помнишь, на елке в страшную ночь кончины твоей мамы девушка стреляла в прокурора? Ее, кажется, потом судили. Помнится, я тогда же сказал тебе, что эту курсистку, когда она еще была гимназисткою, мы с Мишей видели в одних дрянных номерах, куда ездили с твоим папой, не помню с какою целью, ночью в трескучий мороз, как мне теперь кажется, во время вооруженного восстания на Пресне. Это и есть Антипова.<br/> Несколько раз порывался домой. Но это не так просто.<br/> Задерживают главным образом не дела, которые мы без ущерба могли бы передать другим. Трудности заключаются в самой поездке. Поезда то не ходят совсем, то проходят до такой степени переполненные, что сесть на них нет возможности.<br/> Однако, разумеется, так не может продолжаться до бесконечности, и потому несколько человек вылечившихся, ушедших со службы и освобожденных, в том числе я, Галиуллин и Антипова, решили во что бы то ни стало разъезжаться с будущей недели, а для удобства посадки отправляться в разные дни поодиночке.<br/> В любой день могу нагрянуть как снег на голову. Впрочем, постараюсь дать телеграмму».<br/> Но еще до отъезда Юрий Андреевич успел получить ответное письмо Антонины Александровны.<br/> В этом письме, в котором рыдания нарушали построения периодов, а точками служили следы слез и кляксы, Антонина Александровна убеждала мужа не возвращаться в Москву, а проследовать прямо на Урал за этой удивительной сестрою, шествующей по жизни в сопровождении таких знамений и стечений обстоятельств, с которыми не сравняться ее, Тониному, скромному жизненному пути.<br/> «О Сашеньке и его будущем не беспокойся, — писала она. — Тебе не придется за него стыдиться. Обещаю воспитать его в тех правилах, пример которых ты ребенком видел в нашем доме».<br/> «Ты с ума сошла, Тоня, — бросился отвечать Юрий Андреевич, — какие подозрения! Разве ты не знаешь, или знаешь недостаточно хорошо, что ты, мысль о тебе и верность тебе и дому спасали меня от смерти и всех видов гибели в течение этих двух лет войны, страшных и уничтожающих? Впрочем, к чему слова. Скоро мы увидимся, начнется прежняя жизнь, все объяснится.<br/> Но то, что ты мне могла ответить так, пугает меня совсем по-другому. Если я подал повод для такого ответа, может быть, я веду себя действительно двусмысленно, и тогда виноват также перед этой женщиной, которую ввожу в заблуждение и перед которой должен буду извиниться. Я это сделаю, как только она вернется из объезда нескольких близлежащих деревень. Земство, прежде существовавшее только в губерниях и уездах, теперь вводят в более мелких единицах, в волостях. Антипова уехала помогать своей знакомой, которая работает инструкторшей как раз по этим законодательным нововведениям.<br/> Замечательно, что живя с Антиповой в одном доме, я до сих пор не знаю, где её комната, и никогда этим не интересовался».

