### 3 {-}

Из Мелюзеева на восток и запад шли две большие дороги.<br/> Одна, грунтовая, лесом, вела в торговавшее хлебом местечко Зыбушино, административно подчиненное Мелюзееву, но во всех отношениях его обогнавшее. Другая, насыпная из щебня, была проложена через высыхавшие летом болотистые луга и шла к Бирючам, узловой станции двух, скрещивавшихся невдалеке от Мелюзеева, железных дорог.<br/> В июне в Зыбушине две недели продолжалась независимая Зыбушинская республика, провозглашенная зыбушинским мукомолом Блажейко.<br/> Республика опиралась на дезертиров из двести двенадцатого пехотного полка, с оружием в руках покинувших позиции и через Бирючи пришедших в Зыбушино к моменту переворота.<br/> Республика не признавала власти Временного правительства и отделилась от остальной России. Сектант Блажейко, в юности переписывавшийся с Толстым, объявил новое тысячелетнее зыбушинское царство, общность труда и имущества и переименовал волостное правление в апостолат.<br/> Зыбушино всегда было источником легенд и преувеличений. Оно стояло в дремучих лесах, упоминалось в документах Смутного времени, и его окрестности кишели разбойниками в более позднюю пору. Притчей во языцех были состоятельность его купечества и фантастическое плодородие его почвы. Некоторые поверья, обычаи и особенности говора, отличавшие эту, западную, часть прифронтовой полосы, шли именно из Зыбушина.<br/> Теперь такие же небылицы рассказывали про главного помощника Блажейко. Утверждали, будто это глухонемой от рождения, под влиянием вдохновения обретающий дар слова и по истечении озарения его снова теряющий.<br/> В июле Зыбушинская республика пала. В местечко вошла верная Временному правительству часть. Дезертиров выбили из Зыбушина, и они отошли к Бирючам.<br/> Там за путями на несколько верст кругом тянулись лесные вырубки, на которых торчали заросшие земляникою пни, стояли наполовину растащенные штабеля старых невывезенных дров и разрушались землянки работавших тут когда-то сезонников лесорубов. Здесь и засели дезертиры.

### 4 {-}

Госпиталь, в котором лежал, а потом служил, и который собирался теперь покинуть доктор, помещался в особняке графини Жабринской, с начала войны пожертвованном владелицей в пользу раненых.<br/> Двухэтажный особняк занимал одно из лучших мест в Мелюзееве. Он стоял на скрещении главной улицы с центральной площадью города, так называемым плацем, на котором раньше производили учение солдат, а теперь вечерами происходили митинги.<br/> Положение на перекрестке с нескольких сторон открывало из особняка хорошие виды. Кроме главной улицы и площади, из него был виден двор соседей, к которому он примыкал, — бедное провинциальное хозяйство, ничем не отличавшееся от деревенского. Открывался также из него старый графинин сад, куда дом выходил заднею стеной.<br/> Особняк никогда не представлял для Жабринской самостоятельной ценности. Ей принадлежало в уезде большое имение «Раздольное», и дом в городе служил только опорным пунктом для деловых наездов в город, а также сборным местом для гостей, съезжавшихся летом со всех сторон в имение.<br/> Теперь в доме был госпиталь, а владелица была арестована в Петербурге, месте своего постоянного жительства.<br/> Из прежней челяди в особняке оставались две любопытные женщины, старая гувернантка графининых дочерей, ныне замужних, мадемуазель Флери, и бывшая белая кухарка графини, Устинья.<br/> Седая и румяная старуха, мадемуазель Флери, шаркая туфлями, в просторной поношенной кофте, неряхой и растрепой расхаживала по всему госпиталю, с которым была теперь на короткой ноге, как когда-то с семейством Жабринских, и ломаным языком что-нибудь рассказывала, проглатывая окончанья русских слов на французский лад. Она становилась в позу, размахивала руками и к концу болтовни разражалась хриплым хохотом, кончавшимся затяжным, неудержимым кашлем.<br/> Мадемуазель знала подноготную сестры Антиповой. Ей казалось, что доктор и сестра должны друг другу нравиться.<br/> Подчиняясь страсти к сводничанью, глубоко коренящейся в романской природе, мадемуазель радовалась, заставая обоих вместе, многозначительно грозила им пальчиком и шаловливо подмигивала. Антипова недоумевала, доктор сердился, но мадемуазель, как все чудачки, больше всего ценила свои заблуждения и ни за что с ними не расставалась.<br/> Еще более любопытную натуру представляла собою Устинья. Это была женщина с нескладно суживавшеюся кверху фигурою, которая придавала ей сходство с наседкой. Устинья была суха и трезва до ехидства, но с этой рассудительностью сочетала фантазию, необузданную по части суеверий.<br/> Устинья знала множество народных заговоров и не ступала шагу, не зачуравшись от огня в печи и не зашептав замочной скважины от нечистой силы при уходе из дому. Она была родом зыбушинская. Говорили, будто она дочь сельского колдуна.<br/> Устинья могла молчать годами, но до первого приступа, пока её не прорывало. Тут уж нельзя было её остановить. Ее страстью было вступаться за правду.<br/> После падения Зыбушинской республики Мелюзеевский исполком стал проводить кампанию по борьбе с анархическими веяниями, шедшими из местечка. Каждый вечер на плацу сами собой возникали мирные и малолюдные митинги, на которые незанятые мелюзеевцы стекались, как в былое время летом на посиделки под открытым небом у ворот пожарной части. Мелюзеевский культпросвет поощрял эти собрания и посылал на них своих собственных или приезжих деятелей в качестве руководителей бесед. Те считали наиболее вопиющей нелепостью в россказнях о Зыбушине говорящего глухонемого, и особенно часто сводили на него речь в своих разоблачениях. Но мелкие мелюзеевские ремесленники, солдатки и бывшая барская прислуга были другого мнения. Говорящий глухонемой не казался им верхом бессмыслицы.<br/> За него вступались.<br/> Среди разрозненных возгласов, раздавшихся из толпы в его защиту, часто слышался голос Устиньи. Сначала она не решалась вылезать наружу, бабий стыд удерживал ее. Но постепенно, набираясь храбрости, она начала все смелее наскакивать на ораторов с неугодными в Мелюзееве мнениями. Так незаметно стала она заправской говоруньей с трибуны.<br/> Из особняка в открытые окна было слышно слитное гудение голосов на площади, а в особенно тихие вечера и обрывки отдельных выступлений. Часто, когда говорила Устинья, в комнату вбегала мадемуазель, уговаривала присутствующих прислушаться и, коверкая слова, добродушно передразнивала:<br/> — Распу! Распу! Сарск брийан! Зыбуш! Глюконемой! Измен! Измен!<br/> Втайне мадемуазель гордилась этой острой на язык бой-бабой. Женщины были нежно привязаны друг к другу и без конца друг на друга ворчали.

