### 5 {-}

Постепенно Юрий Андреевич стал готовиться к отъезду, обходил дома и учреждения, где надо было с кем-нибудь проститься, и выправлял необходимые бумаги.<br/> В это время проездом в армию в городе остановился новый комиссар этой части фронта. Про него рассказывали, будто он еще совершенный мальчик.<br/> То были дни подготовки нового большого наступления.<br/> Старались добиться перелома в настроениях солдатских масс.<br/> Войска подтягивали. Были учреждены военно-революционные суды и восстановлена смертная казнь, недавно отмененная.<br/> Перед отъездом доктору надо было отметиться у коменданта, должность которого в Мелюзееве исполнял воинский начальник, «уездный», как его звали для краткости.<br/> Обычно у него бывала страшная толчея. Столпотворение не умещалось в сенях и на дворе и занимало пол-улицы перед окнами присутствия. К столам нельзя было протиснуться. За гулом сотни голосов никто ничего не понимал.<br/> В этот день не было приема. В пустой и тихой канцелярии писаря, недовольные всё усложняющимся делопроизводством, молча писали, иронически переглядываясь. Из кабинета начальника доносились веселые голоса, точно там, расстегнув кителя, освежались чем-то прохладительным.<br/> Оттуда на общую половину вышел Галиуллин, увидал Живаго и движением всего корпуса, словно собираясь разбежаться, поманил доктора разделить царившее там оживление.<br/> Доктору все равно надо было в кабинет за подписью начальника. Там нашел он все в самом художественном беспорядке.<br/> Сенсация городка и герой дня, новый комиссар, вместо следования к цели своего назначения находился тут, в кабинете, никакого отношения не имеющем к жизненным разделам штаба и вопросам оперативным, находился перед администраторами военно-бумажного царства, стоял перед ними и ораторствовал.<br/> — А вот еще одна наша звезда, — сказал уездный, представляя доктора комиссару, который и не посмотрел на него, всецело поглощенный собою, а уездный, изменив позу только для того, чтобы подписать протянутую доктором бумагу, вновь её принял и любезным движением руки показал Живаго на стоявший посередине комнаты низкий мягкий пуф.<br/> Из присутствующих только один доктор расположился в кабинете по-человечески. Остальные сидели один другого чуднее и развязнее. Уездный, подперев рукой голову, по-печорински полулежал возле письменного стола, его помощник громоздился напротив на боковом валике дивана, подобрав под себя ноги, как в дамском седле, Галиуллин сидел верхом на стуле, поставленном задом наперед, обняв спинку и положив на нее голову, а молоденький комиссар то подтягивался на руках в проем подоконника, то с него соскакивал и, как запущенный волчок, ни на минуту не умолкая и все время двигаясь, маленькими частыми шагами расхаживал по кабинету. Он говорил не переставая. Речь шла о бирючевских дезертирах.<br/> Слухи о комиссаре оправдались. Это был тоненький и стройный, совсем еще неоперившийся юноша, который как свечечка, горел самыми высшими идеалами. Говорили, будто он из хорошей семьи, чуть ли не сын сенатора, и в феврале один из первых повел свою роту в Государственную думу. Фамилия его была Гинце или Гинц, доктору его назвали неясно, когда их знакомили. У комиссара был правильный петербургский выговор, отчетливый-преотчетливый, чуть-чуть остзейский.<br/> Он был в тесном френче. Наверное, ему было неловко, что он еще так молод, и, чтобы казаться старше, он брюзгливо кривил лицо и напускал на себя деланную сутулость. Для этого он запускал руки глубоко в карманы галифе и подымал углами плечи в новых, негнущихся погонах, отчего его фигура становилась действительно по-кавалерийски упрощенной, так что от плеч к ногам её можно было вычертить с помощью двух книзу сходящихся линий.<br/> — На железной дороге, в нескольких перегонах отсюда стоит казачий полк. Красный, преданный. Их вызовут, бунтовщиков окружат и дело с концом. Командир корпуса настаивает на их скорейшем разоружении, — осведомлял уездный комиссара.<br/> — Казаки? Ни в коем случае! — вспыхивал комиссар. — Какой-то девятьсот пятый год, дореволюционная реминисценция! Тут мы на разных полюсах с вами, тут ваши генералы перемудрили.<br/> — Ничего еще не сделано. Все еще только в плане, в предположении.<br/> — Имеется соглашение с военным командованием не вмешиваться в оперативные распоряжения. Я казаков не отменяю. Допустим. Но я со своей стороны предприму шаги, подсказанные благоразумием. У них там бивак?<br/> — Как сказать. Во всяком случае, лагерь. Укрепленный.<br/> — Прекрасно. Я хочу к ним поехать. Покажите мне эту грозу, этих лесных разбойников. Пусть бунтовщики, пусть даже дезертиры, но это народ, господа, вот что вы забываете. А народ ребенок, надо его знать, надо знать его психику, тут требуется особый подход. Надо уметь задеть за его лучшие, чувствительнейшие струны так, чтобы они зазвенели. Я к ним поеду на вырубки и по душам с ними потолкую. Вы увидите, в каком образцовом порядке они вернутся на брошенные позиции. Хотите пари? Вы не верите?<br/> — Сомнительно. Но дай Бог!<br/> — Я скажу им: «Братцы, поглядите на меня. Вот я, единственный сын, надежда семьи, ничего не пожалел, пожертвовал именем, положением, любовью родителей, чтобы завоевать вам свободу, равной которой не пользуется ни один народ в мире. Это сделал я и множество таких же молодых людей, не говоря уж о старой гвардии славных предшественников, о каторжанах-народниках и народовольцах-шлиссельбуржцах. Для себя ли мы старались? Нам ли это было нужно? Теперь вы больше не рядовые, как были раньше, а воины первой в мире революционной армии. Спросите себя честно, оправдали ли вы это высокое звание? В то время как родина, истекая кровью, последним усилием старается сбросить с себя гидрою обвившегося вокруг нее врага, вы дали одурманить себя шайке безвестных проходимцев и превратились в несознательный сброд, в скопище разнузданных негодяев, обожравшихся свободой, которым, что ни дай, им все мало, вот уж подлинно, пусти свинью за стол, а она и ноги на стол» — о, я пройму, я пристыжу их!<br/> — Нет, нет, это рискованно, — пробовал возразить уездный, украдкой многозначительно переглядываясь с помощником.<br/> Галиуллин отговаривал комиссара от его безумной затеи. Он знал сорви-голов из двести двенадцатого по дивизии, куда полк входил, и где он раньше служил. Но комиссар его не слушал.<br/> Юрий Андреевич все время порывался встать и уйти. Наивность комиссара конфузила его. Но немногим выше была и лукавая искушенность уездного и его помощника, двух насмешливых и скрытых проныр. Эта глупость и эта хитрость друг друга стоили.<br/> И все это извергалось потоком слов, лишнее, несуществующее, неяркое, без чего сама жизнь так жаждет обойтись.<br/> О как хочется иногда из бездарно-возвышенного, беспросветного человеческого словоговорения в кажущееся безмолвие природы, в каторжное беззвучие долгого, упорного труда, в бессловесность крепкого сна, истинной музыки и немеющего от полноты души тихого сердечного прикосновения!<br/> Доктор вспомнил, что ему предстоит объяснение с Антиповой, как бы то ни было, неприятное. Он был рад необходимости её увидеть, пусть и такой ценой. Но едва ли она уже приехала.<br/> Воспользовавшись первою удобной минутой, доктор встал и незаметно вышел из кабинета.

