### 6 {-}

Оказалось, что она уже дома. О её приезде доктору сообщила мадемуазель и прибавила, что Лариса Федоровна вернулась усталою, наспех поужинала и ушла к себе, попросив её не беспокоить.<br/> — Впрочем, постучитесь к ней, — посоветовала мадемуазель. — Она, наверное, еще не спит.<br/> — А как к ней пройти? — спросил доктор, несказанно удивив вопросом мадемуазель.<br/> Выяснилось, что Антипова помещается в конце коридора наверху, рядом с комнатами, куда под ключом был сдвинут весь здешний инвентарь Жабринской, и куда доктор никогда не заглядывал.<br/> Между тем быстро темнело. На улицах стало теснее. Дома и заборы сбились в кучу в вечерней темноте. Деревья подошли из глубины дворов к окнам, под огонь горящих ламп. Была жаркая и душная ночь. От каждого движения бросало в пот. Полосы керосинового света, падавшие во двор, струями грязной испарины стекали по стволам деревьев.<br/> На последней ступеньке доктор остановился. Он подумал, что даже стуком наведываться к человеку, утомленному дорогой, неудобно и навязчиво. Лучше разговор отложить до следующего дня. В рассеянности, всегда сопровождающей передуманные решения, он прошел по коридору до другого конца. Там в стене было окно, выходившее в соседний двор. Доктор высунулся в него.<br/> Ночь была полна тихих, таинственных звуков. Рядом в коридоре капала вода из рукомойника, мерно, с оттяжкою. Где-то за окном шептались. Где-то, где начинались огороды, поливали огурцы на грядках, переливая воду из ведра в ведро, и гремели цепью, набирая её из колодца.<br/> Пахло всеми цветами на свете сразу, словно земля днем лежала без памяти, а теперь этими запахами приходила в сознание. А из векового графининого сада, засоренного сучьями валежника так, что он стал непроходим, заплывало во весь рост деревьев огромное, как стена большого здания, трущобно-пыльное благоуханье старой зацветающей липы.<br/> Справа из-за забора с улицы неслись крики. Там буянил отпускной, хлопали дверью, бились крыльями обрывки какой-то песни.<br/> За вороньими гнездами графининого сада показалась чудовищных размеров исчерна-багровая луна. Сначала она была похожа на кирпичную паровую мельницу в Зыбушине, а потом пожелтела, как бирючевская железнодорожная водокачка.<br/> А внизу под окном во дворе к запаху ночной красавицы примешивался душистый, как чай с цветком, запах свежего сена.<br/> Сюда недавно привели корову, купленную в дальней деревне. Ее вели весь день, она устала, тосковала по оставленному стаду и не брала корма из рук новой хозяйки, к которой еще не привыкла.<br/> — Но-но, не балуй, тпрусеня, я те дам, дьявол, бодаться, — шопотом уламывала её хозяйка, но корова то сердито мотала головой из стороны в сторону, то, вытянув шею, мычала надрывно и жалобно, а за черными мелюзеевскими сараями мерцали звезды, и от них к корове протягивались нити невидимого сочувствия, словно то были скотные дворы других миров, где её жалели.<br/> Всё кругом бродило, росло и всходило на волшебных дрожжах существования. Восхищение жизнью, как тихий ветер, широкой волной шло не разбирая куда по земле и городу, через стены и заборы, через древесину и тело, охватывая трепетом все по дороге. Чтобы заглушить действие этого тока, доктор пошел на плац послушать разговоры на митинге.

