### 7 {-}

Луна стояла уже высоко на небе. Все было залито её густым, как пролитые белила, светом.<br/> У порогов казенных каменных зданий с колоннами, окружавших площадь, черными коврами лежали на земле их широкие тени.<br/> Митинг происходил на противоположной стороне площади. При желании, вслушавшись, можно было различить через плац все, что там говорилось. Но великолепие зрелища захватило доктора. Он присел на лавочку у ворот пожарной части без внимания к голосам, слышавшимся через дорогу, и стал смотреть по сторонам.<br/> С боков площади на нее вливались маленькие глухие улочки. В глубине их виднелись ветхие, покосившиеся домишки. На этих улицах была непролазная грязь, как в деревне. Из грязи торчали длинные, плетенные из ивовых прутьев изгороди, словно то были закинутые в пруд верши, или затонувшие корзины, которыми ловят раков.<br/> В домишках подслеповато поблескивали стекла в рамах растворенных окошек. Внутрь комнат из палисадников тянулась потная русоголовая кукуруза с блестящими, словно маслом смоченными метелками и кистями. Из-за провисающих плетней одиночками смотрели вдаль бледные, худощавые мальвы, похожие на хуторянок в рубахах, которых жара выгнала из душных хат подышать свежим воздухом.<br/> Озаренная месяцем ночь была поразительна, как милосердие или дар ясновиденья, и вдруг в тишину этой светлой, мерцающей сказки стали падать мерные, рубленые звуки чьего-то знакомого, как будто только что слышанного голоса. Голос был красив, горяч и дышал убеждением. Доктор прислушался и сразу узнал, кто это. Это был комиссар Гинц. Он говорил на площади.<br/> Власти, наверное, просили его поддержать их своим авторитетом, и он с большим чувством упрекал мелюзеевцев в дезорганизованности, в том, что они так легко поддаются растлевающему влиянию большевиков, истинных виновников, как уверял он, зыбушинских событий. В том же духе, как он говорил у воинского, он напоминал о жестоком и могущественном враге и пробившем для родины часе испытаний. С середины речи его начали перебивать.<br/> Просьбы не прерывать оратора чередовались с выкриками несогласия. Протестующие заявления учащались и становились громче. Кто-то, сопровождавший Гинца и в эту минуту взявший на себя задачу председателя, кричал, что замечания с места не допускаются, и призывал к порядку. Одни требовали, чтобы гражданке из толпы дали слово, другие шикали и просили не мешать.<br/> К перевернутому вверх дном ящику, служившему трибуной, через толпу пробиралась женщина. Она не имела намерения влезать на ящик, а, протиснувшись к нему, стала возле сбоку.<br/> Женщину знали. Наступила тишина. Женщина овладела вниманием толпившихся. Это была Устинья.<br/> — Вот вы говорите Зыбушино, товарищ комиссар, и потом насчет глаз, глаза, говорите, надо иметь и не попадаться в обман, а между прочим сами, я вас послушала, только знаете большевиками-меньшевиками шпыняться, большевики и меньшевики, ничего другого от вас не услышишь. А чтобы больше не воевать и всё как между братьями, это называется по-божески, а не меньшевики, и чтобы фабрики и заводы бедным, это опять не большевики, а человеческая жалость. А глухонемым и без вас нам глаза кололи, надоело слушать. Дался он вам, право! И чем это он вам не угодил? Что ходил-ходил немой, да вдруг, не спросясь, и заговорил? Подумаешь, невидаль. То ли еще бывает!<br/> Ослица эта, например, известная. «Валаам, Валаам, говорит, честью прошу, не ходи туда, сам пожалеешь». Ну, известное дело, он не послушал, пошел. Вроде того как вы: «Глухонемой».<br/> Думает, что её слушать — ослица, животное. Побрезговал скотиной. А как потом каялся. Небось сами знаете, чем кончилось.<br/> — Чем? — полюбопытствовали из публики.<br/> — Ладно, — огрызнулась Устинья. — Много будешь знать, скоро состаришься.<br/> — Нет, так не годится. Ты скажи, чем, — не унимался тот же голос.<br/> — Чем да чем, репей неотвязчивый! В соляной столб обратился.<br/> — Шалишь, кума! Это Лот. Лотова жена, — раздались выкрики.<br/> Все засмеялись. Председатель призывал собрание к порядку.<br/> Доктор пошел спать.

