### 8 {-}

На другой день вечером он увиделся с Антиповой. Он её нашел в буфетной. Перед Ларисой Федоровной лежала груда катаного белья. Она гладила.<br/> Буфетная была одной из задних комнат верха и выходила в сад. В ней ставили самовары, раскладывали по тарелкам кушанья, поднятые из кухни на ручном подъемнике, спускали грязную посуду судомойке. В буфетной хранилась материальная отчетность госпиталя. В ней проверяли посуду и белье по спискам, отдыхали в часы досуга и назначали друг другу свидания.<br/> Окна в сад были отворены. В буфетной пахло липовым цветом, тминной горечью сухих веток, как в старых парках, и легким угаром от двух духовых утюгов, которыми попеременно гладила Лариса Федоровна, ставя то один, то другой в вытяжную трубу, чтобы они разгорелись.<br/> — Что же вы вчера не постучались? Мне мадемуазель рассказывала. Впрочем, вы поступили правильно. Я прилегла уже и не могла бы вас впустить. Ну, здравствуйте. Осторожно, не запачкайтесь. Тут уголь просыпан.<br/> — Видно, вы на весь госпиталь белье гладите?<br/> — Нет, тут много моего. Вот вы всё меня дразнили, что я никогда отсюда не выберусь. А на этот раз я всерьез. Видите, вот собираюсь, укладываюсь. Уложусь — и айда. Я на Урал, вы в Москву. А потом спросят когда-нибудь Юрия Андреевича: «Вы про такой городишко Мелюзеев не слыхали?» — «Что-то не помню». — «А кто такая Антипова?» — «Понятия не имею».<br/> — Ну, это положим. — Как вам по волостям ездилось? Хорошо в деревне?<br/> — Так в двух словах не расскажешь. — Как быстро утюги стынут! Новый мне, пожалуйста, если вам нетрудно. Вон в вытяжной трубе торчит. А этот назад, в вытяжку. Так. Спасибо.<br/> — Разные деревни. Все зависит от жителей. В одних население трудолюбивое, работящее. Там ничего. А в некоторых, верно, одни пьяницы. Там запустение. На те страшно смотреть.<br/> — Глупости. Какие пьяницы? Много вы понимаете. Просто нет никого, мужчины все забраны в солдаты. Ну хорошо. А земство как новое революционное?<br/> — Насчет пьяниц вы не правы, я с вами поспорю. А земство?<br/> С земством долго будет мука. Инструкции неприложимы, в волости не с кем работать. Крестьян в данную минуту интересует только вопрос о земле. Заезжала в Раздольное. Вот красота! Вы бы съездили. Весной немного пожгли, пограбили. Сгорел сарай, фруктовые деревья обуглены, часть фасада попорчена копотью. А в Зыбушино не попала, не удалось. Однако везде уверяют, будто глухонемой не выдумка. Описывают наружность. Говорят — молодой, образованный.<br/> — Вчера за него на плацу Устинья распиналась. — Только приехала, из Раздольного опять целый воз хламу. Сколько раз просила, чтобы оставили в покое. Мало у нас своего! А сегодня утром сторожа из комендантского с запиской от уездного. Чайное серебро и винный хрусталь графини им до зареза. Только на один вечер, с возвратом. Знаем мы этот возврат. Половины вещей не доищешься. Говорят, вечеринка. Какой-то приезжий.<br/> — А, догадываюсь. Приехал новый комиссар фронта. Я его случайно видел. За дезертиров собирается взяться, оцепить и разоружить. Комиссар совсем еще зеленый, в делах младенец.<br/> Здешние предлагают казаков, а он думает взять слезой. Народ, говорит, это ребенок и так далее и думает, что все это детские игрушки. Галиуллин упрашивает, не будите, говорит, задремавшего зверя, предоставьте это нам, но разве такого уговоришь, когда ему втемяшится. Слушайте. На минуту оставьте утюги и слушайте. Скоро тут произойдет невообразимая свалка.<br/> Предотвратить её не в наших силах. Как бы я хотел, чтобы вы уехали до этой каши!<br/> — Ничего не будет. Вы преувеличиваете. Да ведь я и уезжаю.<br/> Но нельзя же так: шик-брык — и будьте здоровы. Надо сдать инвентарь по описи, а то похоже будет, будто я что-то украла.<br/> А кому его сдать? Вот ведь вопрос. Сколько я настрадалась с этим инвентарем, а в награду одни попреки. Я записала имущество Жабринской на госпиталь, потому что таков был смысл декрета. А теперь выходит, будто я это сделала притворно, чтобы таким способом сберечь вещи владелице. Какая гадость!<br/> — Ах, да плюньте вы на эти ковры и фарфор, пропади они пропадом. Есть из-за чего расстраиваться! Да, да, в высшей степени досадно, что мы вчера с вами не свиделись. Я в таком ударе был! Я бы вам всю небесную механику объяснил, на все проклятые вопросы ответил! Нет, не шутя, меня так и подмывало выговориться. Про жену свою рассказать, про сына, про свою жизнь. Чорт возьми, неужели нельзя взрослому мужчине заговорить со взрослой женщиной, чтобы тотчас не заподозрили какую-то «подкладку»? Брр! Чорт бы драл все эти материи и подкладки!<br/> Вы гладьте, гладьте, пожалуйста, то есть белье гладьте, и не обращайте на меня внимания, а я буду говорить. Я буду говорить долго.<br/> Вы подумайте, какое сейчас время! И мы с вами живем в эти дни! Ведь только раз в вечность случается такая небывальщина.<br/> Подумайте: со всей России сорвало крышу, и мы со всем народом очутились под открытым небом. И некому за нами подглядывать.<br/> Свобода! Настоящая, не на словах и в требованиях, а с неба свалившаяся, сверх ожидания. Свобода по нечаянности, по недоразумению.<br/> И как все растерянно-огромны! Вы заметили? Как будто каждый подавлен самим собою, своим открывшимся богатырством.<br/> Да вы гладьте, говорю я. Молчите. Вам не скучно? Я вам утюг сменю.<br/> Вчера я ночной митинг наблюдал. Поразительное зрелище.<br/> Сдвинулась Русь матушка, не стоится ей на месте, ходит не находится, говорит не наговорится. И не то чтоб говорили одни только люди. Сошлись и собеседуют звезды и деревья, философствуют ночные цветы и митингуют каменные здания. Что-то евангельское, не правда ли? Как во времена апостолов. Помните, у Павла? «Говорите языками и пророчествуйте. Молитесь о даре истолкования».<br/> — Про митингующие деревья и звезды мне понятно. Я знаю, что вы хотите сказать. У меня самой бывало.<br/> — Половину сделала война, остальное довершила революция.<br/> Война была искусственным перерывом жизни, точно существование можно на время отсрочить (какая бессмыслица!). Революция вырвалась против воли, как слишком долго задержанный вздох.<br/> Каждый ожил, переродился, у всех превращения, перевороты.<br/> Можно было бы сказать: с каждым случилось по две революции, одна своя, личная, а другая общая. Мне кажется, социализм — это море, в которое должны ручьями влиться все эти свои, отдельные революции, море жизни, море самобытности. Море жизни, сказал я, той жизни, которую можно видеть на картинах, жизни гениализированной, жизни, творчески обогащенной. Но теперь люди решили испытать её не в книгах, а на себе, не в отвлечении, а на практике.<br/> Неожиданное дрожание голоса выдало начинающееся волнение доктора. Прервав на минуту глаженье, Лариса Федоровна посмотрела на него серьезно и удивленно. Он смешался и забыл, о чем он говорил. После короткой паузы он заговорил снова.<br/> Очертя голову он понес Бог знает что. Он сказал:<br/> — В эти дни так тянет жить честно и производительно! Так хочется быть частью общего одушевления! И вот среди охватившей всех радости я встречаю ваш загадочно невеселый взгляд, блуждающий неве домо где, в тридевятом царстве, в тридесятом государстве. Что бы я дал за то, чтобы его не было, чтобы на вашем лице было написано, что вы довольны судьбой и вам ничего ни от кого не надо. Чтобы какой-нибудь близкий вам человек, ваш друг или муж (самое лучшее, если бы это был военный) взял меня за руку и попросил не беспокоиться о вашей участи и не утруждать вас своим вниманием. А я вырвал бы руку, размахнулся, и… Ах, я забылся! Простите, пожалуйста.<br/> Голос опять изменил доктору. Он махнул рукой и с чувством непоправимой неловкости встал и отошел к окну. Он стал спиной к комнате, подпер щеку ладонью, облокотясь о подоконник, и устремил вглубь покрытого темнотою сада рассеянный, ищущий умиротворения, невидящий взгляд.<br/> Обойдя гладильную доску, «перекинутую со стола на край другого окна, Лариса Федоровна остановилась в нескольких шагах от доктора позади него, в середине комнаты.<br/> — Ах, как я всегда этого боялась! — тихо, как бы про себя сказала она. — Какое роковое заблуждение! Перестаньте, Юрий Андреевич, не надо. Ах, смотрите, что я из-за вас наделала! — громко воскликнула она и подбежала к доске, где под забытым на белье утюгом тонкой струйкой едкого дыма курилась прожженная кофточка. — Юрий Андреевич, — продолжала она, с сердитым стуком опуская утюг на конфорку. — Юрий Андреевич, будьте умницей, выйдите на минуту к мадемуазель, выпейте воды, голубчик, и возвращайтесь сюда таким, каким я вас привыкла и хотела бы видеть. Слышите, Юрий Андреевич? Я знаю, это в ваших силах. Сделайте это, я прошу вас.<br/> Больше таких объяснений между ними не повторялось. Через неделю Лариса Федоровна уехала.

