### 9 {-}

Еще через некоторое время стал собираться в дорогу Живаго.<br/> Ночью перед его отъездом в Мелюзееве была страшная буря.<br/> Шум урагана сливался с шумом ливня, который то отвесно обрушивался на крыши, то под напором изменившегося ветра двигался вдоль улицы, как бы отвоевывая шаг за шагом своими хлещущими потоками.<br/> Раскаты грома следовали один за другим без перерыва, переходя в одно ровное рокотание. При сверкании частых молний показывалась убегающая вглубь улица с нагнувшимися и бегущими в ту же сторону деревьями.<br/> Ночью мадемуазель Флери разбудил тревожный стук в парадное.<br/> Она в испуге присела на кровати и прислушалась. Стук не прекращался.<br/> Неужели во всем госпитале не найдется ни души, чтобы выйти и отпереть, подумала она, и за всех должна отдуваться она одна, несчастная старуха, только потому, что природа сделала её честной и наделила чувством долга?<br/> Ну хорошо. Жабринские были богачи, аристократы. Но госпиталь, это ведь их собственное, народное. На кого же они его бросили? Например, куда, интересно знать, провалились санитары? Все разбежались, ни начальства, ни сестер, ни докторов. А в доме есть еще раненые, два безногих наверху в хирургической, где прежде была гостиная, да полная кладовая дизентериков внизу, рядом с прачешной. И чертовка Устинья ушла куда-то в гости. Видит, дура, что гроза собирается, нет, понесла нелегкая. Теперь хороший предлог ночевать у чужих.<br/> Ну, слава Богу, перестали, угомонились. Видят — не отпирают, и ушли, махнули рукой. Тоже носит чорт в такую погоду. А может быть, это Устинья? Нет, у той свой ключ. Боже мой, как страшно, опять стучат!<br/> Но ведь все-таки какое свинство! Допустим, с Живаго нечего взять. Он завтра уезжает, и мыслями уже в Москве или в дороге.<br/> Но каков Галиуллин! Как может он дрыхнуть или спокойно лежать, слыша такой стук, в расчете, что в конце концов подымется она, слабая и беззащитная старуха, и пойдет отпирать неизвестно кому в эту страшную ночь в этой страшной стране.<br/> Галиуллин! — вдруг спохватилась она. — Какой Галиуллин?<br/> Нет, такая нелепость могла прийти ей в голову только спросонья! Какой Галиуллин, когда его и след простыл? И не сама ли она вместе с Живаго прятала и переодевала его в штатское, а потом объясняла, какие дороги и деревни в округе, чтобы он знал, куда ему бежать, когда случился этот страшный самосуд на станции и убили комиссара Гинца, а за Галиуллиным гнались из Бирючей до самого Мелюзеева, стреляя вдогонку, и шарили по всему городу. Галиуллин!<br/> Если бы тогда не эти самокатчики, камня на камне не осталось бы от города. Броневой дивизион проходил по случайности через город. Заступились за жителей, обуздали негодяев.<br/> Гроза слабела, удалялась. Гром гремел реже и глуше, издали.<br/> Дождь переставал временами, а вода с тихим плеском продолжала стекать вниз по листве и желобам. Бесшумные отсветы молний западали в комнату мадемуазель, озаряли её и задерживались в ней лишний миг, словно что-то разыскивая.<br/> Вдруг надолго прекратившийся стук в дверь возобновился.<br/> Кто-то нуждался в помощи и стучался в дом отчаянно и учащенно.<br/> Снова поднялся ветер. Опять хлынул дождь.<br/> — Сейчас! — неизвестно кому крикнула мадемуазель и сама испугалась своего голоса.<br/> Неожиданная догадка осенила ее. Спустив ноги с кровати и сунув их в туфли, она накинула халат и побежала будить Живаго, чтобы не было так страшно одной. Но он тоже слышал стук и сам спускался со свечою навстречу. У них были одинаковые предположения.<br/> — Живаго, Живаго! Стучат в наружную дверь, я боюсь отпереть одна, — кричала она по-французски и по-русски прибавила:<br/> — Вы увийт, это Лар или поручик Гайуль.<br/> Юрия Андреевича тоже разбудил этот стук, и он подумал, что это непременно кто-то свой, либо остановленный каким-то препятствием Галиуллин, вернувшийся в убежище, где его спрячут, либо возвращенная какими-то трудностями из путешествия сестра Антипова.<br/> В сенях доктор дал мадемуазель подержать свечу, а сам повернул ключ в двери и отодвинул засов. Порыв ветра вырвал дверь из его рук, задул свечу и обдал обоих с улицы холодными брызгами дождя.<br/> — Кто там? Кто там? Есть ли тут кто-нибудь? — кричали наперерыв во тьму мадемуазель и доктор, но им никто не отвечал.<br/> Вдруг они услышали прежний стук в другом месте, со стороны черного хода или, как им стало теперь казаться, в окно из сада.<br/> — По-видимому, это ветер, — сказал доктор. — Но для очистки совести сходите все-таки на черный, удостоверьтесь, а я тут подожду, чтобы нам не разминуться, если это действительно кто-нибудь, а не какая-нибудь другая причина.<br/> Мадемуазель удалилась вглубь дома, а доктор вышел наружу под навес подъезда. Глаза его, привыкнув к темноте, различили признаки занимающегося рассвета.<br/> Над городом, как полоумные, быстро неслись тучи, словно спасаясь от погони. Их клочья пролетали так низко, что почти задевали за деревья, клонившиеся в ту же сторону, так что похоже было, будто ими, как гнущимися вениками, подметают небо. Дождь охлестывал деревянную стену дома, и она из серой становилась черною.<br/> — Ну как? — спросил доктор вернувшуюся мадемуазель.<br/> — Вы прав. Никого. — И она рассказала, что обошла весь дом. В буфетной выбито окно обломком липового сука, бившегося о стекло, и на полу огромные лужи, и то же самое в комнате, оставшейся от Лары, море, форменное море, целый океан.<br/> — А тут ставня оторвалась и бьется о наличник. Видите? Вот и все объяснение.<br/> Они поговорили еще немного, заперли дверь и разошлись спать, оба сожалея, что тревога оказалась ложной.<br/> Они были уверены, что отворят парадное и в дом войдет так хорошо им известная женщина, до нитки вымокшая и иззябшая, которую они засыплют расспросами, пока она будет отряхиваться.<br/> А потом она придет, переодевшись, сушиться у вчерашнего не остывшего жара в печи на кухне и будет им рассказывать о своих бесчисленных злоключениях, поправлять волосы, и смеяться.<br/> Они были так уверены в этом, что когда они заперли дверь, след этой уверенности остался за углом дома на улице, в виде водяного знака этой женщины или её образа, который продолжал им мерещиться за поворотом.

