### 10 {-}

Косвенным виновником солдатских волнений на станции считали бирючевского телеграфиста Колю Фроленко.<br/> Коля был сыном известного мелюзеевского часовщика. В Мелюзееве его знали с пеленок. Мальчиком он гостил у кого-то из раздольненской дворни и играл под наблюдением мадемуазель с двумя её питомицами, дочерьми графини. Мадемуазель хорошо знала Колю. Тогда же он стал немного понимать по-французски.<br/> В Мелюзееве привыкли видеть Колю в любую погоду налегке, без шапки, в летних парусиновых туфлях, на велосипеде. Не держась за руль, откинувшись и скрестив на груди руки, он катил по шоссе и городу и поглядывал на столбы и провода, проверяя состояние сети.<br/> Ответвлением железнодорожного телефона некоторые дома в городе были соединены со станцией. Управление веткой находилось в Колиных руках в аппаратной вокзала.<br/> Там у него работы было по горло: железнодорожный телеграф, телефон, а иногда, в моменты недолгих отлучек начальника станции Поварихина, также и сигнализация и блокировка, приборы к которым тоже помещались в аппаратной.<br/> Необходимость следить сразу за действием нескольких механизмов выработала у Коли особую манеру речи, темную, отрывистую и полную загадок, к которой Коля прибегал, когда не желал кому-нибудь отвечать или не хотел вступать с кем-нибудь в разговоры. Передавали, что он слишком широко пользовался этим правом в день беспорядков.<br/> Своими умолчаниями он и правда лишил силы все добрые намерения Галиуллина, звонившего из города, и, может быть, против воли дал роковой ход последовавшим событиям.<br/> Галиуллин просил подозвать к аппарату комиссара, находившегося где-то на вокзале или поблизости, чтобы сказать ему, что он выезжает сейчас к нему на вырубки, и попросить, чтобы он подождал его и без него ничего не предпринимал. Коля отказал Галиуллину в вызове Гинца под тем предлогом, что линия у него занята передачей сигналов идущему к Бирючам поезду, а сам в это время всеми правдами и не правдами задерживал на соседнем разъезде этот поезд, который вез в Бирючи вызванных казаков.<br/> Когда эшелон все же прибыл, Коля не мог скрыть неудовольствия.<br/> Паровоз медленно подполз под темный навес дебаркадера и остановился как раз против огромного окна аппаратной. Коля широко отдернул тяжелую вокзальную занавеску из темно-синего сукна с вытканными по бортам инициалами железной дороги. На каменном подоконнике стоял огромный графин с водой и стакан толстого стекла с простыми гранями на большом подносе. Коля налил воды в стакан, отпил несколько глотков и посмотрел в окно.<br/> Машинист заметил Колю и дружески кивнул ему из будки. «У, дрянь вонючая, древесный клоп!» — с ненавистью подумал Коля, высунул машинисту язык и погрозил ему кулаком. Машинист не только понял Колину мимику, но сумел и сам пожатием плеч и поворотом головы в сторону вагонов дать понять: «А что делать? Сам попробуй. Его сила». «Все равно, дрянь и гадина», — мимически ответил Коля.<br/> Лошадей стали выводить из вагонов. Они упирались, не шли. Глухой стук копыт по деревянному настилу сходней сменился звяканьем подков по камню перрона. Взвивающихся на дыбы лошадей перевели через рельсы нескольких путей.<br/> Они кончались двумя рядами вагонного брака, на двух ржавых, заросших травой колеях. Разрушение дерева, с которого дожди смывали краску и которое точили червь и сырость, возвращало разбитым теплушкам былое родство с сырым лесом, начинавшимся по ту сторону составов, с грибом трутовиком, которым болела береза, с облаками, которые над ним громоздились.<br/> На опушке казаки по команде сели в седла и поскакали на вырубки. Непокорных из двести двенадцатого окружили. Верховые среди деревьев всегда кажутся выше и внушительнее, чем на открытом месте. Они произвели впечатление на солдат, хотя у них самих были винтовки в землянках. Казаки вынули шашки.<br/> Внутри конной цепи на сложенные дрова, которые утрясли и выровняли, вскочил Гинц и обратился с речью к окруженным.<br/> Опять он по своему обыкновению говорил о воинском долге, о значении родины и многих других высоких предметах. Здесь эти понятия не находили сочувствия. Сборище было слишком многочисленно. Люди, составлявшие его, натерпелись многого за войну, огрубели и устали. Слова, которые произносил Гинц, давно навязли у них в ушах. Четырехмесячное заискивание справа и слева развратило эту толпу. Простой народ, из которого она состояла, расхолаживала нерусская фамилия оратора и его остзейский выговор.<br/> Гинц чувствовал, что говорит длинно, и досадовал на себя, но думал, что делает это ради большей доступности для слушателей, которые вместо благодарности платят ему выражением равнодушия и неприязненной скуки. Раздражаясь все больше, он решил заговорить с этой публикой более твердым языком и пустить в ход угрозы, которые держал в запасе. Не слыша поднявшегося ропота, он напомнил солдатам, что военно-революционные суды введены и действуют, и под страхом смерти требовал сложения оружия и выдачи зачинщиков. Если они этого не сделают, говорил Гинц, то докажут, что они подлые изменники, несознательная сволочь, зазнавшиеся хамы. От такого тона эти люди отвыкли.<br/> Поднялся рев нескольких сот голосов. «Поговорил. Будет. ропота,он Ладно», — кричали одни басом и почти беззлобно. Но раздавались истерические выкрики на надсаженных ненавистью дискантах. К ним прислушивались. Эти кричали:<br/> — Слыхали, товарищи, как обкладывает? По-старому! Не вывелись офицерские повадки! Так это мы изменники? А сам ты из каковских, ваше благородие? Да что с ним хороводиться. Не видишь что ли, немец, подосланный. Эй ты, предъяви документ, голубая кровь! А вы чего рот разинули, усмирители? Нате, вяжите, ешьте нас!<br/> Но и казакам неудачная речь Гинца нравилась все меньше и меньше. «Все хамы да свиньи. Экой барин!» — перешептывались они. Сначала поодиночке, а потом все в большем количестве они стали вкладывать шашки в ножны. Один за другим слезали с лошади. Когда их спешилось достаточно, они беспорядочно двинулись на середину прогалины навстречу двести двенадцатому.<br/> Все перемешалось. Началось братание.<br/> «Вы должны исчезнуть как-нибудь незаметно, — говорили Гинцу встревоженные казачьи офицеры. — У переезда ваша машина. Мы пошлем сказать, чтобы её подвели поближе. Уходите скорее».<br/> Гинц так и поступил, но так как удирать потихоньку казалось ему недостойным, он без требующейся осторожности, почти открыто направился к станции. Он шел в страшном волнении, из гордости заставляя себя идти спокойно и неторопливо.<br/> До станции было уже близко, лес примыкал к ней. На опушке, уже в виду путей, он в первый раз оглянулся. За ним шли солдаты с ружьями. «Что им надо?» — подумал Гинц и прибавил шагу.<br/> То же самое сделали его преследователи. Расстояние между ним и погоней не изменилось. Впереди показалась двойная стена поломанных вагонов. Зайдя за них, Гинц пустился бежать.<br/> Доставивший казаков поезд отведен был в парк. Пути были свободны. Гинц бегом пересек их.<br/> Он вскочил с разбега на высокий перрон. В это время из-за разбитых вагонов выбежали гнавшиеся за ним солдаты. Поварихин и Коля что-то кричали Гинцу и делали знаки, приглашая внутрь вокзала, где они спасли бы его.<br/> Но опять поколениями воспитанное чувство чести, городское, жертвенное и здесь неприменимое, преградило ему дорогу к спасению. Нечеловеческим усилием воли он старался сдержать трепет расходившегося сердца. — Надо крикнуть им: «Братцы, опомнитесь, какой я шпион?» — подумал он. — Что-нибудь отрезвляющее, сердечное, что их бы остановило.<br/> В последние месяцы ощущение подвига, крика души бессознательно связалось у него с помостами и трибунами, со стульями, вскочив на которые можно было бросить толпящимся какой-нибудь призыв, что-нибудь зажигательное.<br/> У дверей вокзала под станционным колоколом стояла высокая пожарная кадка. Она была плотно прикрыта. Гинц вскочил на её крышку и обратил к приближающимся несколько за душу хватающих слов, нечеловеческих и бессвязных. Безумная смелость его обращения, в двух шагах от распахнутых вокзальных дверей, куда он так легко мог бы забежать, ошеломила и приковала их к месту. Солдаты опустили ружья.<br/> Но Гинц стал на край крышки и перевернул ее. Одна нога провалилась у него в воду, другая повисла на борту кадки. Он оказался сидящим верхом на её ребре.<br/> Солдаты встретили эту неловкость взрывом хохота, и первый спереди выстрелом в шею убил наповал несчастного, а остальные бросились штыками докалывать мертвого.

