### 11 {-}

Мадемуазель звонила Коле по телефону, чтобы он устроил доктора в поезде поудобнее, угрожая в противном случае неприятными для Коли разоблачениями.<br/> Отвечая мадемуазель, Коля по обыкновению вел какой-то другой телефонный разговор и, судя по десятичным дробям, пестрившим его речь, передавал в третье место по телеграфу что-то шифрованное.<br/> — Псков, комосев, слушаешь меня? Каких бунтовщиков? Какую руку? Да что вы, мамзель? Вранье, хиромантия. Отстаньте, положите трубку, вы мне мешаете. Псков, комосев, Псков.<br/> Тридцать шесть запятая ноль ноль пятнадцать. Ах, чтоб вас собаки съели, обрыв ленты. А? А? Не слышу. Это опять вы, мамзель? Я вам сказал русским языком, нельзя, не могу.<br/> Обратитесь к Поварихину. Вранье, хиромантия. Тридцать шесть… а, чорт… отстаньте, не мешайте, мамзель.<br/> А мадемуазель говорила:<br/> — Ты мне не пускай пыль в глаз кироман, Псков, Псков, кироман, я тебя насквозь буду водить на чистую воду, ты будешь завтра сажать доктора в вагон, и больше я не разговариваю со всяких убийц и маленький Иуда предатель.

### 12 {-}

Парило, когда уезжал Юрий Андреевич. Опять собиралась гроза, как третьего дня.<br/> Глиняные мазанки и гуси в заплеванной подсолнухами привокзальной слободе испуганно белели под неподвижным взглядом черного грозового неба.<br/> К зданию станции прилегала широкая, далеко в обе стороны тянувшаяся поляна. Трава на ней была вытоптана, и всю её покрывала несметная толпа народа, неделями дожидавшегося поездов в разных, нужных каждому, направлениях.<br/> В толпе были старики в серых сермягах, на палящем солнце переходившие от кучки к кучке за слухами и сведениями.<br/> Молчаливые подростки лет четырнадцати лежали, облокотившись, на боку, с каким-нибудь очищенным от листьев прутом в руке, словно пасли скотину. Задирая рубашонки, под ногами шмыгали их младшие розовозадые братишки и сестренки. Вытянув плотно сдвинутые ноги, на земле сидели их матери с замотанными за пазуху криво стянутых коричневых зипунов грудными детьми.<br/> — Как бараны кинулись врассыпную, когда пальба началась. Не понравилось! — неприязненно говорил начальник станции Поварихин, ломаными обходами пробираясь с доктором через ряды тел, лежавшие вповалку снаружи перед дверьми и внутри на полу вокзала.<br/> — Вдруг газон опростался! Опять увидали, какая земля бывает. Обрадовались! Четыре месяца ведь не видали под этим табором, — забыли. — Вот тут он лежал. Удивительное дело, навидался я за войну всяких ужасов, пора бы привыкнуть. А тут такая жалость взяла! Главное — бессмыслица. За что? Что он им сделал плохого? Да разве это люди? Говорят, любимец семьи. А теперь направо, так, так, сюда, пожалуйста, в мой кабинет. На этот поезд и не думайте, затолкают насмерть. Я вас на другой устрою, местного сообщения. Мы его сами составляем, сейчас начнем формировать. Только вы до посадки молчок, никому! А то на части разнесут до сцепки, если проговоритесь. Ночью в Сухиничах вам будет пересадка.

