### 13 {-}

Когда хранимый в секрете поезд составили и стали из-за здания депо задом подавать к станции, всё что было народу на лужайке, толпой бросились наперерез к медленно пятящемуся составу. Люди горохом скатывались с пригорков и взбегали на насыпь. Оттесняя друг друга, одни скакали на ходу на буфера и подножки, а другие лезли в окна и на крыши вагонов. Поезд вмиг и еще в движении наполнился до отказа, и когда его подали к перрону, был набит битком, и сверху донизу увешан едущими.<br/> Чудом доктор протиснулся на площадку и потом еще более необъяснимым образом проник в коридор вагона.<br/> В коридоре он и остался в продолжение всей дороги, и путь до Сухиничей совершил, сидя на полу на своих вещах.<br/> Грозовые тучи давно разошлись. По полям, залитым жгучими лучами солнца, перекатывалось из края в край несмолкаемое, заглушавшее ход поезда стрекотание кузнечиков.<br/> Пассажиры, стоявшие у окна, застили свет остальным. От них на пол, на лавки и на перегородки падали длинные, вдвое и втрое сложенные тени. Эти тени не умещались в вагоне. Их вытесняло вон через противоположные окна, и они бежали вприпрыжку по другой стороне откоса вместе с тенью всего катящегося поезда.<br/> Кругом галдели, горланили песни, ругались и резались в карты. На остановках к содому, стоявшему внутри, присоединялся снаружи шум осаждавшей поезд толпы. Гул голосов достигал оглушительности морской бури. И как на море, в середине стоянки наступала вдруг необъяснимая тишина. Становились слышны торопливые шаги по платформе вдоль всего поезда, беготня и спор у багажного вагона, отдельные слова провожающих вдалеке, тихое квохтанье кур и шелестение деревьев в станционном палисаднике.<br/> Тогда, как телеграмма, поданная в дороге, или как поклон из Мелюзеева, вплывало в окно знакомое, точно к Юрию Андреевичу адресующееся благоухание. Оно с тихим превосходством обнаруживало себя где-то в стороне и приходило с высоты, для цветов в полях и на клумбах необычной.<br/> Доктор не мог подойти к окну вследствие давки. Но он и не глядя видел в воображении эти деревья. Они росли, наверно, совсем близко, спокойно протягивая к крышам вагонов развесистые ветки с пыльной от железнодорожной толкотни и густой, как ночь, листвой, мелко усыпанной восковыми звездочками мерцающих соцветий.<br/> Это повторялось весь путь. Всюду шумела толпа. Всюду цвели липы.<br/> Вездесущее веяние этого запаха как бы опережало шедший к северу поезд, точно это был какой-то все разъезды, сторожки и полустанки облетевший слух, который едущие везде заставали на месте, распространившимся и подтвержденным.

