### 14 {-}

Ночью в Сухиничах услужливый носильщик старого образца, пройдя с доктором по неосвещенным путям, посадил его с задней стороны в вагон второго класса какого-то, только что подошедшего и расписанием не предусмотренного поезда.<br/> Едва носильщик, отомкнув кондукторским ключом заднюю дверцу, вскинул на площадку докторские вещи, как должен был выдержать короткий бой с проводником, который мгновенно стал их высаживать, но, будучи умилостивлен Юрием Андреевичем, стушевался и провалился как сквозь землю.<br/> Таинственный поезд был особого назначения и шел довольно быстро, с короткими остановками, под какой-то охраной. В вагоне было совсем свободно.<br/> Купе, куда вошел Живаго, ярко освещалось оплывшею свечой на столике, пламя которой колыхала струя воздуха из приспущенного окна.<br/> Свеча принадлежала единственному пассажиру в купе. Это был белокурый юноша, наверное, очень высокого роста, судя по его длинным рукам и ногам. Они слишком легко ходили у него на сгибах, как плохо скрепленные составные части складных предметов. Молодой человек сидел на диване у окна, непринужденно откинувшись. При появлении Живаго он вежливо приподнялся и переменил свою полулежачую позу на более приличную сидячую.<br/> У него под диваном валялось что-то вроде половой тряпки.<br/> Вдруг кончик ветоши зашевелился, и из-под дивана с хлопотливою вознею вылезла вислоухая лягавая собака. Она обнюхала и оглядела Юрия Андреевича и стала бегать по купе из угла в угол, раскидывая лапы так же гибко, как закидывал ногу на ногу её долговязый хозяин. Скоро по его требованию она хлопотливо залезла под диван и приняла свой прежний вид скомканной полотерной суконки.<br/> Тут только Юрий Андреевич заметил двустволку в чехле, кожаный патронташ и туго набитую настрелянной птицей охотничью сумку, висевшие на крюках в купе.<br/> Молодой человек был охотник.<br/> Он отличался чрезвычайной разговорчивостью и поспешил с любезной улыбкой вступить с доктором в беседу. При этом он не в переносном, а в самом прямом смысле все время смотрел доктору в рот.<br/> У молодого человека оказался неприятный высокий голос, на повышениях впадавший в металлический фальцет. Другая странность: по всему русский, он одну гласную, а именно «у», произносил мудреннейшим образом. Он её смягчал наподобие французского «u» или немецкого «u Umlaut». Мало того, это испорченное «у» стоило ему больших трудов, он со страшной натугой, несколько взвизгивая, выговаривал этот звук громче всех остальных. Почти в самом начале он огорошил Юрия Андреевича такой фразой:<br/> «Еще только вчера utrom я охотился на utok».<br/> Минутами, когда, видимо, он больше следил за собой, он преодолевал эту не правильность, но стоило ему забыться, как она вновь проскальзывала.<br/> «Что за чертовщина? — подумал Живаго, — что-то читанное, знакомое. Я, как врач, должен был бы это знать, да вот вылетело из головы. Какое-то мозговое явление, вызывающее дефект артикуляции. Но это подвывание так смешно, что трудно оставаться серьезным. Совершенно невозможно разговаривать. Лучше полезу наверх и лягу».<br/> Так доктор и сделал. Когда он стал распологаться на верхней полке, молодой человек спросил, не потушить ли ему свечу, которая, пожалуй, будет мешать Юрию Андреевичу. Доктор с благодарностью принял предложение. Сосед погасил огонь. Стало темно. Оконная рама в купе была наполовину спущена.<br/> — Не закрыть ли нам окно? — спросил Юрий Андреевич. — Вы воров не боитесь?<br/> Сосед ничего не ответил. Юрий Андреевич очень громко повторил вопрос, но тот опять не отозвался.<br/> Тогда Юрий Андреевич зажег спичку, чтобы посмотреть, что с его соседом, не вышел ли он из купе в такое короткое мгновение и не спит ли, что было бы еще невероятнее.<br/> Но нет, тот сидел с открытыми глазами на своем месте и улыбнулся свесившемуся сверху доктору.<br/> Спичка потухла. Юрий Андреевич зажег новую и при её свете в третий раз повторил, что ему желательно было выяснить.<br/> — Поступайте, как знаете, — без замедления ответил охотник. — У меня нечего красть. Впрочем, лучше было бы не закрывать. Душно.<br/> «Вот так фунт! — подумал Живаго. — Чудак, по-видимому, привык разговаривать только при полном освещении. И как он чисто все сейчас произнес, без своих не правильностей! Уму непостижимо!»

