### 15 {-}

Доктор чувствовал себя разбитым событиями прошедшей недели, предотъездными волнениями, дорожными сборами и утренней посадкой на поезд. Он думал, что уснет, чуть растянется на удобном месте. Но не тут-то было. Чрезмерное переутомление нагнало на него бессонницу. Он заснул только на рассвете.<br/> Как ни хаотичен был вихрь мыслей, роившихся в его голове в течение этих долгих часов, их, собственно говоря, было два круга, два неотвязных клубка, которые то сматывались, то разматывались.<br/> Один круг составляли мысли о Тоне, доме и прежней налаженной жизни, в которой все до мельчайших подробностей было овеяно поэзией и проникнуто сердечностью и чистотою.<br/> Доктор тревожился за эту жизнь и желал ей целости и сохранности и, летя в ночном скором поезде, нетерпеливо рвался к этой жизни обратно, после более чем двухлетней разлуки.<br/> Верность революции и восхищение ею были тоже в этом круге.<br/> Это была революция в том смысле, в каком принимали её средние классы, и в том понимании, какое придавала ей учащаяся молодежь девятьсот пятого года, поклонявшаяся Блоку.<br/> В этот круг, родной и привычный, входили также те признаки нового, те обещания и предвестия, которые показались на горизонте перед войной, между двенадцатым и четырнадцатым годами, в русской мысли, русском искусстве и русской судьбе, судьбе общероссийской и его собственной, Живаговской.<br/> После войны хотелось обратно к этим веяниям, для их возобновления и продолжения, как тянуло из отлучки назад домой.<br/> Новое было также предметом мыслей второго круга, но насколько другое, насколько отличное новое! Это было не свое, привычное, старым подготовленное новое, а непроизвольное, неотменимое, реальностью предписанное новое, внезапное, как потрясение.<br/> Таким новым была война, её кровь и ужасы, её бездомность и одичание. Таким новым были её испытания и житейская мудрость, которой война учила. Таким новым были захолустные города, куда война заносила, и люди, с которыми она сталкивала. Таким новым была революция, не по-университетски идеализированная под девятьсот пятый год, а эта, нынешняя, из войны родившаяся, кровавая, ни с чем не считающаяся солдатская революция, направляемая знатоками этой стихии, большевиками.<br/> Таким новым была сестра Антипова, войной заброшенная Бог знает куда, с совершенно ему неведомой жизнью, никого ни в чем не укоряющая и почти жалующаяся своей безгласностью, загадочно немногословная и такая сильная своим молчанием. Таким новым было честное старание Юрия Адреевича изо всех сил не любить ее, так же как всю жизнь он старался относиться с любовью ко всем людям, не говоря уже о семье и близких.<br/> Поезд несся на всех парах. Встречный ветер через опущенное окно трепал и пылил волосы Юрия Андреевича. На ночных остановках творилось то же самое, что на дневных, бушевала толпа и шелестели липы.<br/> Иногда из глубины ночи к станциям со стуком подкатывали телеги и таратайки. Голоса и гром колес смешивались с шумом деревьев.<br/> В эти минуты казалось понятным, что заставляло шелестеть и клониться друг к другу эти ночные тени, и что они шепчут друг другу, еле ворочая сонными отяжелевшими листьями, как заплетающимися шепелявыми языками. Это было то же самое, о чем думал, ворочаясь у себя на верхней полке, Юрий Адреевич, весть об охваченной все ширящимися волнениями России, весть о революции, весть о её роковом и трудном часе, о её вероятном конечном величии.

