### 16 {-}

На другой день доктор проснулся поздно. Был двенадцатый час. «Маркиз, Маркиз!» — вполголоса сдерживал сосед свою разворчавшуюся собаку. К удивлению Юрия Андреевича, они с охотником оставались одни в купе, никто не подсел дорогой.<br/> Названия станций попадались с детства знакомые. Поезд, оставив Калужскую губернию, врезался в глубь Московской.<br/> Совершив свой дорожный туалет с довоенным удобством, доктор вернулся в купе к утреннему завтраку, который предложил ему его любопытный спутник. Теперь Юрий Андреевич лучше к нему присмотрелся.<br/> Отличительными чертами этой личности были крайняя разговорчивость и подвижность. Неизвестный любил поговорить, причем главным для него было не общение и обмен мыслей, а самая деятельность речи, произнесение слов и издавание звуков.<br/> Разговаривая, он как на пружинах подскакивал на диване, оглушительно и беспричинно хохотал, быстро-быстро потирал от удовольствия руки, а когда и этого оказывалось недостаточно для выражения его восторга, бил себя ладонями по коленкам, смеясь до слез.<br/> Разговор возобновился со всеми вчерашними странностями.<br/> Незнакомец был удивительно непоследователен. Он то вдавался в признания, на которые никто не толкал его, то, и ухом не ведя, оставлял без ответа самые невинные вопросы.<br/> Он вывалил целую кучу сведений о себе, самых фантастических и бессвязных. Грешным делом он, наверное, привирал. Он с несомненностью бил на эффект крайностями своих взглядов и отрицанием всего общепризнанного.<br/> Все это напоминало что-то давно знакомое. В духе такого радикализма говорили нигилисты прошлого века и немного спустя некоторые герои Достоевского, а потом совсем еще недавно их прямые продолжения, то есть вся образованная русская провинция, часто идущая впереди столиц, благодаря сохранившейся в глуши основательности, в столицах устаревшей и вышедшей из моды.<br/> Молодой человек рассказал, что он племянник одного известного революционера, родители же его, напротив, неисправимые ретрограды, зубры, как он выразился. У них в одной из прифронтовых местностей было порядочное имение. Там молодой человек и вырос. Его родители были с дядей всю жизнь на ножах, но он не злопамятен и теперь своим влиянием избавляет их от многих неприятностей.<br/> Сам он по своим убеждениям в дядю, сообщил словоохотливый субъект, — экстремист-максималист во всем: в вопросах жизни, политики и искусства. Опять запахло Петенькой Верховенским, не в смысле левизны, а в смысле испорченности и пустозвонства.<br/> «Сейчас он футуристом отрекомендуется», — подумал Юрий Андреевич, и действительно, речь шла о футуристах. «А сейчас о спорте заговорит, — продолжал загадывать вперед доктор, — о рысаках, или скетинг-рингах, или о французской борьбе». И правда, разговор перешел на охоту.<br/> Молодой человек сказал, что в родных местах он и охотился, и похвастал, что он великолепный стрелок, и если бы не его физический порок, помешавший ему попасть в солдаты, он на войне бы выделился меткостью.<br/> Уловив вопрошающий взгляд Живаго, он воскликнул:<br/> — Как? Разве вы ничего не заметили? Я думал, вы догадались о моем недостатке.<br/> И он достал из кармана и протянул Юрию Андреевичу две карточки. Одна была его визитная. У него была двойная фамилия.<br/> Его звали Максим Аристархович Клинцов-Погоревших, или просто Погоревших, как он просил звать в честь его, так именно называвшего себя дяди.<br/> На другой карточке была разграфленная на клетки таблица с изображением разнообразно соединенных рук со сложенными по-разному пальцами. Это была ручная азбука глухонемых. Вдруг все объяснилось.<br/> Погоревших был феноменально способным воспитанником школы Гартмана или Остроградского, то есть глухонемым, с невероятным совершенством выучившимся говорить не по слуху, а на глаз, по движению горловых мышц учителя, и таким же образом понимавшим речь собеседника.<br/> Тогда, сопоставив в уме, откуда он и в каких местах охотился, доктор спросил:<br/> — Простите за нескромность, но вы можете не отвечать, — скажите, вы не имели отношения к Зыбушинской республике и её созданию?<br/> — А откуда… Позвольте… Так вы знали Блажейко?.. Имел, имел! Конечно, имел, — радостно затараторил Погоревших, хохоча, раскачиваясь всем корпусом из стороны в сторону и неистово колотя себя по коленям. И опять пошла фантасмагория.<br/> Погоревших сказал, что Блажейко был для него поводом, а Зыбушино безразличной точкой приложения его собственных идей.<br/> Юрию Андреевичу трудно было следить за их изложением.<br/> Философия Погоревших наполовину состояла из положений анархизма, а наполовину из чистого охотничьего вранья.<br/> Погоревших невозмутимым тоном оракула предсказывал гибельные потрясения на ближайшее время. Юрий Андреевич внутренне соглашался, что, может быть, они неотвратимы, но его взрывало авторитетное спокойствие, с каким цедил свои предсказания этот неприятный мальчишка.<br/> — Постойте, постойте, — несмело возражал он. — Все это так, может статься. Но, по-моему, не время таким рискованным экспериментам среди нашего хаоса и развала, перед лицом напирающего врага. Надо дать стране прийти в себя и отдышаться от одного переворота, прежде чем отваживаться на другой. Надо дождаться какого-нибудь, хотя бы относительного успокоения и порядка.<br/> — Это наивно, — говорил Погоревших. — То, что вы зовете развалом, такое же нормальное явление, как хваленый ваш и излюбленный порядок. Эти разрушения — закономерная и предварительная часть более широкого созидательного плана.<br/> Общество развалилось еще недостаточно. Надо, чтобы оно распалось до конца, и тогда настоящая революционная власть по частям соберет его на совершенно других основаниях.<br/> Юрию Андреевичу стало не по себе. Он вышел в коридор.<br/> Поезд, набирая скорость, несся подмосковными. Каждую минуту навстречу к окнам подбегали и проносились мимо березовые рощи с тесно расставленными дачами. Пролетали узкие платформы без навесов с дачниками и дачницами, которые отлетали далеко в сторону в облаке пыли, поднятой поездом, и вертелись как на карусели. Поезд давал свисток за свистком, и его свистом захлебывалось, далеко разнося его, полое, трубчатое и дуплистое лесное эхо.<br/> Вдруг в первый раз за все эти дни Юрий Андреевич с полной ясностью понял, где он, что с ним и что его встретит через какой-нибудь час или два с лишним.<br/> Три года перемен, неизвестности, переходов, война, революция, потрясения, обстрелы, сцены гибели, сцены смерти, взорванные мосты, разрушения, пожары — все это вдруг превратилось в огромное пустое место, лишенное содержания.<br/> Первым истинным событием после долгого перерыва было это головокружительное приближение в поезде к дому, который цел и есть еще на свете, и где дорог каждый камушек. Вот что было жизнью, вот что было переживанием, вот за чем гонялись искатели приключений, вот что имело в виду искусство — приезд к родным, возвращение к себе, позобновление существования.<br/> Рощи кончились. Поезд вырвался из лиственных теснин на волю. Отлогая поляна широким бугром уходила вдаль, подымаясь из оврага. Вся она была покрыта продольными грядами темно-зеленой картошки. На вершине поляны, в конце картофельного поля, лежали на земле стеклянные рамы, вынутые из парников. Против поляны за хвостом идущего поезда в полнеба стояла огромная черно-лиловая туча. Из-за нее выбивались лучи солнца, расходясь колесом во все стороны, и по пути задевали за парниковые рамы, зажигая их стекла нестерпимым блеском.<br/> Вдруг из тучи косо посыпался крупный, сверкающий на солнце грибной дождь. Он падал торопливыми каплями в том же самом темпе, в каком стучал колесами и громыхал болтами разбежавшийся поезд, словно стараясь догнать его или боясь от него отстать.<br/> Не успел доктор обратить на это внимание, как из-за горы показался храм Христа Спасителя и в следующую минуту — купола, крыши, дома и трубы всего города.<br/> — Москва, — сказал он, возвращаясь в купе. — Пора собираться.<br/> Погоревших вскочил, стал рыться в охотничьей сумке и выбрал из нее утку покрупнее.<br/> — Возьмите, — сказал он. — На память. Я провел целый день в таком приятном обществе.<br/> Как ни отказывался доктор, ничего не помогало.<br/> — Ну хорошо, — вынужден он был согласиться, — я принимаю это от вас в подарок жене.<br/> — Жене! Жене! В подарок жене, — радостно повторял Погоревших, точно слышал это слово впервые, и стал дергаться всем телом и хохотать так, что выскочивший Маркиз принял участие в его радости.<br/> Поезд подходил к дебаркадеру. В вагоне стало темно, как ночью. Глухонемой протягивал доктору дикого селезня, завернутого в обрывок какого-то печатного воззвания.

