## ЧАСТЬ шестая. МОСКОВСКОЕ СТАНОВИЩЕ {-}

### 1 {-}

В дороге, благодаря неподвижному сидению в тесном купе, казалось, что идет только поезд, а время стоит, и что все еще пока полдень.<br/> Но уже вечерело, когда извозчик с доктором и его вещами с трудом выбрался шагом из несметного множества народа, толпившегося на Смоленском.<br/> Может быть, так оно и было, а может быть, на тогдашние впечатления доктора наслоился опыт позднейших лет, но потом в воспоминаниях ему казалось, что уже и тогда на рынке сбивались в кучу только по привычке, а толпиться на нем не было причины, потому что навесы на пустых ларях были спущены и даже не прихвачены замками, и торговать на загаженной площади, с которой уже не сметали нечистот и отбросов, было нечем.<br/> И ему казалось, что уже и тогда он видел жавшихся на тротуаре худых, прилично одетых старух и стариков, стоявших немой укоризною мимоидущим, и безмолвно предлагавших на продажу что-нибудь такое, чего никто не брал и что никому не было нужно: искусственные цветы, круглые спиртовые кипятильники для кофе со стеклянной крышкой и свистком, вечерние туалеты из черного газа, мундиры упраздненных ведомств.<br/> Публика попроще торговала вещами более насущными: колючими, быстро черствевшими горбушками черного пайкового хлеба, грязными, подмокшими огрызками сахара и перерезанными пополам через всю обертку пакетиками махорки в пол-осьмушки.<br/> И по всему рынку шел в оборот какой-то неведомый хлам, который рос в цене по мере того, как обходил все руки.<br/> Извозчик свернул в один из прилегавших к площади переулков.<br/> Сзади садилось солнце и било им в спину. Перед ними громыхал ломовик на подскакивавшей порожней подводе. Он подымал столбы пыли, горевшей бронзою в лучах заката.<br/> Наконец им удалось объехать ломового, преграждавшего им дорогу. Они поехали быстрее. Доктора поразили валявшиеся всюду на мостовых и тротуарах вороха старых газет и афиш, сорванных с домов и заборов. Ветер тащил их в одну сторону, а копыта, колеса и ноги встречных едущих и идущих — в другую.<br/> Скоро после нескольких пересечений показался на углу двух переулков родной дом. Извозчик остановился.<br/> У Юрия Андреевича захватило дыхание и громко забилось сердце, когда, сойдя с пролетки, он подошел к парадному и позвонил в него. Звонок не произвел действия. Юрий Андреевич дал новый. Когда ни к чему не привела и эта попытка, он с поднявшимся беспокойством стал с небольшими перерывами звонить раз за разом. Только на четвертый внутри загремели крюком и цепью, и вместе с отведенной вбок входною дверью он увидел державшую её на весь отлет Антонину Александровну. От неожиданности оба в первое мгновение остолбенели и не слышали, что вскрикнули. Но так как настежь откинутая дверь в руке Антонины Александровны наполовину представляла настежь раскрытое объятие, то это вывело их из столбняка, и они как безумные бросились друг другу на шею. Через минуту они заговорили одновременно, друг друга перебивая.<br/> — Первым делом: все ли здоровы?<br/> — Да, да, успокойся. Всё в порядке. Я тебе написала глупости. Прости. Но надо будет поговорить. Отчего ты не телеграфировал? Сейчас Маркел тебе вещи снесет. А, я понимаю, тебя встревожило, что не Егоровна дверь отворила? Егоровна в деревне.<br/> — А ты похудела. Но какая молодая и стройная! Сейчас я извозчика отпущу.<br/> — Егоровна за мукой уехала. Остальных распустили. Сейчас только одна новая, ты её не знаешь, Нюша, девчонка при Сашеньке, и больше никого. Всех предупредили, что ты должен приехать, все в нетерпении. Гордон, Дудоров, все.<br/> — Сашенька как?<br/> — Ничего, слава Богу. Только что проснулся. Если бы ты не с дороги, можно было бы сейчас пройти к нему.<br/> — Папа дома?<br/> — Разве тебе не писали? С утра до поздней ночи в районной думе. Председателем. Да, представь себе. Ты расплатился с извозчиком? Маркел! Маркел!<br/> Они стояли с корзиной и чемоданом посреди тротуара, загородив дорогу, и прохожие, обходя их, оглядывали их с ног до головы и долго глазели на отъезжающего извозчика и на широко растворенное парадное, ожидая, что будет дальше.<br/> Между тем от ворот уже бежал к молодым господам Маркел в жилетке поверх ситцевой рубахи, с дворницким картузом в руке и на бегу кричал:<br/> — Силы небесные, никак Юрочка? Ну как же! Так и есть, он, соколик! Юрий Андреевич, свет ты наш, не забыл нас, молитвенников, припожаловал на родимое запечье! А вам чего надо? Ну? Чего не видали? — огрызался он на любопытных. — Проходите, достопочтенные. Вылупили белки!<br/> — Здравствуй, Маркел, давай обнимемся. Да надень ты, чудак, картуз. Что нового, хорошенького? Как жена, дочки?<br/> — Что им делается. Произрастают. Благодарствуем. А нового — покамест ты там богатырствовал, и мы, видишь, не зевали.<br/> Такой кабак и бедлант развели, что чертям, брат, тошно, не разбери-бери — что! Улицы не метены, дома-крыши не чинены, в животах, что в пост, чистота, без анекцый и контрибуцый.<br/> — Я на тебя Юрию Андреевичу пожалуюсь, Маркел. Вот всегда он так, Юрочка. Терпеть не могу его дурацкого тона. И наверное он ради тебя старается, думает тебе угодить. А сам, между тем, себе на уме. Оставь, оставь, Маркел, не оправдывайся. Темная ты личность, Маркел. Пора бы поумнеть. Чай, живешь не у лабазников.<br/> Когда Маркел внес вещи в сени и захлопнул парадное, он продолжал тихо и доверительно:<br/> — Антонина Александровна серчают, слыхал вот. И так завсегда. Говорят, ты, говорит, Маркел, весь черный изнутре, вот все равно как сажа в трубе. Теперь, говорит, не то что дитя малое, теперь, может, мопс, болонка комнатная и то стали понимающие со смыслом. Это, конечно, кто спорит, ну только, Юрочка, хошь верь, хошь не верь, а только знающие люди книгу видали, масон грядущий, сто сорок лет под камнем пролежала, и теперь мое такое мнение, продали нас, Юрочка, понимаешь, продали, продали ни за грош, ни за полушку, ни за понюшку табаку. Не дадут, смотри, мне Антонина Александровна слово сказать, опять, видишь, машут ручкой.<br/> — А как не махать. Ну хорошо. Поставь вещи на пол и спасибо, ступай, Маркел. Надо будет, Юрий Андреевич опять кликнет.

