### 2 {-}

— Отстал, наконец, отвязался. Ты верь ему, верь. Чистейший балаган один. При других всё дурачком, дурачком, а сам втайне на всякий случай ножик точит. Да вот не решил еще, на кого, казанская сирота.<br/> — Ну, это ты хватила! По-моему, просто он пьян, вот и паясничает, больше ничего.<br/> — А ты скажи, когда он трезв бывает? Да ну его, право, к чорту. Я чего боюсь, как бы Сашенька опять не уснул. Если бы не этот тиф железнодорожный… На тебе нет вшей?<br/> — Думаю, что нет. Я ехал с комфортом, как до войны. Разве немного умыться? Кое-как, наскоро. А потом поосновательней. Но куда ты? Почему не через гостиную? Вы теперь по-другому подымаетесь?<br/> — Ах да! Ты ведь ничего не знаешь. Мы с папой думали, думали, и часть низа отдали Сельскохозяйственной академии. А то зимой самим не отопить. Да и верх слишком поместительный.<br/> Предлагаем им. Пока не берут. У них тут кабинеты ученые, гербарии, коллекции семян. Не развели бы крыс. Все-таки — зерно. Но пока содержат комнаты в опрятности. Теперь это называется жилой площадью. Сюда, сюда. Какой несообразительный! В обход по черной лестнице. Понял? Иди за мной, я покажу.<br/> — Очень хорошо сделали, что уступили комнаты. Я работал в госпитале, который был тоже размещен в барском особняке. Бесконечные анфилады, кое-где паркет уцелел. Пальмы в кадках по ночам над койками пальцы растопыривали, как привидения. Раненые, бывалые, из боев, пугались и со сна кричали. Впрочем, не вполне нормальные, контуженные. Пришлось вынести. Я хочу сказать, что в жизни состоятельных было, правда, что-то нездоровое. Бездна лишнего. Лишняя мебель и лишние комнаты в доме, лишние тонкости чувств, лишние выражения. Очень хорошо сделали, что потеснились. Но еще мало. Надо больше.<br/> — Что это у тебя из свертка высовывается? Птичий клюв, голова утиная. Какая красота! Дикий селезень! Откуда? Глазам своим не верю! По нынешним временам это целое состояние!<br/> — В вагоне подарили. Длинная история, потом расскажу. Как ты советуешь, развернуть и оставить на кухне?<br/> — Да, конечно. Сейчас пошлю Нюшу ощипать и выпотрошить. К зиме предсказывают всякие ужасы, голод, холод.<br/> — Да, об этом везде говорят. Сейчас смотрел я в окно вагона и думал. Что может быть выше мира в семье и работы?<br/> Остальное не в нашей власти. Видимо, правда, многих ждут несчастья. Некоторые думают спастись на юг, на Кавказ, пробуют пробраться куда-нибудь подальше. Это не в моих правилах.<br/> Взрослый мужчина должен, стиснув зубы, разделять судьбу родного края. По-моему, это очевидность. Другое дело вы. Как бы мне хотелось уберечь вас от бедствий, отправить куда-нибудь в место понадежнее, в Финляндию, что ли. Но если мы так по полчаса будем стоять на каждой ступеньке, мы никогда не доберемся доверху.<br/> — Постой. Слушай. Новость. И какая! А я и забыла. Николай Николаевич приехал.<br/> — Какой Николай Николаевич?<br/> — Дядя Коля.<br/> — Тоня! Быть не может! Какими судьбами?<br/> — Да вот, как видишь. Из Швейцарии. Кружным путем на Лондон. Через Финляндию.<br/> — Тоня! Ты не шутишь? Вы его видали? Где он? Нельзя ли его раздобыть немедленно, сию минуту?<br/> — Какое нетерпение! Он за городом у кого-то на даче.<br/> Обещал послезавтра вернуться. Очень изменился, ты разочаруешься. Проездом застрял в Петербурге, обольшевичился.<br/> Папа с ним до хрипоты спорит. Но почему мы, правда, останавливаемся на каждом шагу? Пойдем. Значит, ты тоже слышал, что впереди ничего хорошего, трудности, опасности, неизвестность?<br/> — Я и сам так думаю. Ну что же. Будем бороться. Не всем же обязательно конец. Посмотрим, как другие.<br/> — Говорят, без дров будем сидеть, без воды, без света.<br/> Отменят деньги. Прекратится подвоз. И опять мы стали. Пойдем.<br/> Слушай. Хвалят плоские железные печурки в мастерской на Арбате. На огне газеты обед можно сварить. Мне достали адрес.<br/> Надо купить, пока не расхватали.<br/> — Правильно. Купим. Умница, Тоня! Но дядя Коля, дядя Коля!<br/> Ты подумай! Не могу опомниться!<br/> — У меня такой план. Выделить наверху с краю какой-нибудь угол, поселиться нам с папой, Сашенькой и Нюшей, скажем, в двух или трех комнатах, непременно сообщающихся, где-нибудь в конце этажа, и совершенно отказаться от остального дома.<br/> Отгородиться, как от улицы. Одну такую железную печурку в среднюю комнату, трубку в форточку, стирку, варку пищи, обеды, прием гостей, всё сюда же, чтобы оправдать топку, и, как знать, может, Бог даст, перезимуем.<br/> — А то как же? Разумеется, перезимуем. Вне всякого сомнения. Ты это превосходно придумала. Молодчина. И знаешь что? Отпразднуем принятие твоего плана. Зажарим мою утку и позовем дядю Колю на новоселье.<br/> — Великолепно. А Гордона попрошу спирту принести. Он в какой-то лаборатории достает. А теперь погляди. Вот комната, о которой я говорила. Вот что я выбрала. Одобряешь? Поставь на пол чемодан и спустись за корзиной. Кроме дяди и Гордона, можно также попросить Иннокентия и Шуру Шлезингер. Не возражаешь? Ты не забыл еще, где наша умывальная? Побрызгайся там чем-нибудь дезинфицирующим. А я пройду к Сашеньке, пошлю Нюшу вниз и, когда можно будет, позову тебя.

