### 3 {-}

Главной новостью в Москве был для него этот мальчик. Едва Сашенька родился, как Юрия Андреевича призвали. Что он знал о сыне?<br/> Однажды, будучи уже мобилизованным, Юрий Андреевич перед отъездом пришел в клинику проведать Тоню. Он пришел к моменту кормления детей. Его к ней не пустили.<br/> Он сел дожидаться в прихожей. В это время дальний детский коридор, шедший под углом к акушерскому, вдоль которого лежали матери, огласился плаксивым хором десяти или пятнадцати младенческих голосов, и нянюшки стали поспешно, чтобы не простудить спеленутых новорожденных, проносить их по двое под мышками, как большие свертки с какими-то покупками, матерям на кормление.<br/> — Уа, уа, — почти без чувства, как по долгу службы, пищали малютки на одной ноте, и только один голос выделялся из этого унисона. Ребенок тоже кричал «уа, уа», и тоже без оттенка страдания, но, как казалось, не по обязанности, а с каким-то впадающим в бас, умышленным, угрюмым недружелюбием.<br/> Юрий Андреевич тогда уже решил назвать сына в честь тестя Александром. Неизвестно почему он вообразил, что так кричит его мальчик, потому что это был плач с физиономией, уже содержавший будущий характер и судьбу человека, плач со звуковой окраской, заключавшей в себе имя мальчика, имя Александр, как вообразил Юрий Андреевич.<br/> Юрий Андреевич не ошибся. Как потом выяснилось, это действительно плакал Сашенька. Вот то первое, что он знал о сыне.<br/> Следующее знакомство с ним Юрий Андреевич составил по карточкам, которые в письмах посылали ему на фронт. На них веселый хорошенький бутуз с большой головой и губами бантиком стоял раскорякой на разостланном одеяле и, подняв обе ручки кверху, как бы плясал вприсядку. Тогда ему был год, он учился ходить, теперь исполнялся второй, он начинал говорить.<br/> Юрий Андреевич поднял чемодан с полу и, распустив ремни, разложил его на ломберном столе у окна. Что это была в прошлом за комната? Доктор не узнавал ее. Видно, Тоня вынесла из нее мебель или переклеила её как-нибудь по-новому.<br/> Доктор раскрыл чемодан, чтобы достать из него бритвенный прибор. Между колонками церковной колокольни, высившейся как раз против окна, показалась ясная, полная луна. Когда её свет упал внутрь чемодана на разложенное сверху белье, книги и туалетные принадлежности, комната озарилась как-то по-другому и доктор узнал ее.<br/> Это была освобожденная кладовая покойной Анны Ивановны. Она в былое время сваливала в нее поломанные столы и стулья, ненужное канцелярское старье. Тут был её семейный архив, тут же и сундуки, в которые прятали на лето зимние вещи. При жизни покойной углы комнаты были загромождены до потолка, и обыкновенно в нее не пускали. Но по большим праздникам, в дни многолюдных детских сборищ, когда им разрешали беситься и бегать по всему верху, отпирали и эту комнату, и они играли в ней в разбойников, прятались под столами, мазались жженой пробкой и переодевались по-маскарадному.<br/> Некоторое время доктор стоял, все это припоминая, а потом сошел в нижние сени за оставленной там корзиною.<br/> Внизу на кухне Нюша, робкая и застенчивая девушка, став на корточки, чистила перед плитою утку над разостланным листом газеты. При виде Юрия Андреевича с тяжестью в руках она вспыхнула, как маков цвет, гибким движением выпрямилась, сбивая с передника приставшие перья, и, поздоровавшись, предложила свою помощь. Но доктор поблагодарил и сказал, что сам донесет корзину.<br/> Едва вошел он в бывшую кладовую Анны Ивановны, как из глубины второй или третьей комнаты жена позвала его:<br/> — Можно, Юра!<br/> Он отправился к Сашеньке.<br/> Теперешняя детская помещалась в прежней его и Тониной классной. Мальчик в кроватке оказался совсем не таким красавчиком, каким его изображали снимки, зато это была вылитая мать Юрия Андреевича, покойная Мария Николаевна Живаго, разительная её копия, похожая на нее больше всех сохранившихся после нее изображений.<br/> — Это папа, это твой папа, сделай папочке ручкой, — твердила Антонина Александровна, опуская сетку кроватки, чтобы отцу было удобнее обнять мальчика и взять его на руки.<br/> Сашенька близко подпустил незнакомого и небритого мужчину, который, может быть, пугал и отталкивал его, и когда тот наклонился, порывисто встал, ухватился за мамину кофточку и злобно с размаху шлепнул его по лицу. Собственная смелость так ужаснула Сашеньку, что он тут же бросился к матери на грудь, зарыл лицо в её платье и заплакал навзрыд горькими и безутешными детскими слезами.<br/> — Фу, фу, — журила его Антонина Александровна. — Нельзя так, Сашенька. Папа подумает, Саша нехороший, Саша бяка.<br/> Покажи, как ты целуешься, поцелуй папу. Не плачь, не надо плакать, о чем ты, глупый?<br/> — Оставь его в покое, Тоня, — попросил доктор. — Не мучь его и не расстраивайся сама. Я знаю, какая дурь лезет тебе в голову. Что это неспроста, что это дурной знак. Это такие пустяки. И так естественно. Мальчик никогда не видал меня.<br/> Завтра присмотрится, водой не разольешь.<br/> Но он и сам вышел из комнаты как в воду опущенный, с чувством недоброго предзнаменования.

