### 5 {-}

Прошел август, кончался сентябрь. Нависало неотвратимое.<br/> Близилась зима, а в человеческом мире то, похожее на зимнее обмирание, предрешенное, которое носилось в воздухе и было у всех на устах.<br/> Надо было готовиться к холодам, запасать пищу, дрова. Но в дни торжества материализма материя превратилась в понятие, пищу и дрова заменил продовольственный и топливный вопрос.<br/> Люди в городах были беспомощны, как дети перед лицом близящейся неизвестности, которая опрокидывала на своем пути все установленные навыки и оставляла по себе опустошение, хотя сама была детищем города и созданием горожан.<br/> Кругом обманывались, разглагольствовали. Обыденщина еще хромала, барахталась, колченого плелась куда-то по старой привычке. Но доктор видел жизнь неприкрашенной. От него не могла укрыться её приговоренность. Он считал себя и свою среду обреченными. Предстояли испытания, может быть, даже гибель.<br/> Считанные дни, оставшиеся им, таяли на его глазах.<br/> Он сошел бы с ума, если бы не житейские мелочи, труды, и заботы. Жена, ребенок, необходимость добывать деньги были его спасением, — насущное, смиренное, бытовой обиход, служба, хожденье по больным.<br/> Он понимал, что он пигмей перед чудовищной махиной будущего, боялся его, любил это будущее и втайне им гордился, и в последний раз, как на прощание, жадными глазами вдохновения смотрел на облака и деревья, на людей, идущих по улице, на большой, перемогающийся в несчастиях русский город, и был готов принести себя в жертву, чтобы стало лучше, и ничего не мог.<br/> Это небо и прохожих он чаще всего видел с середины мостовой, переходя Арбат у аптеки русского общества врачей, на углу Староконюшенного.<br/> Он опять поступил на службу в свою старую больницу. Она по старой памяти называлась Крестовоздвиженской, хотя община этого имени была распущена. Но больнице еще не придумали подходящего названия:<br/> В ней уже началось расслоение. Умеренным, тупоумие которых возмущало доктора, он казался опасным, людям, политически ушедшим далеко, недостаточно красным. Так очутился он ни в тех, ни в сих, от одного берега отстал, к другому не пристал.<br/> В больнице, кроме его прямых обязанностей, директор возложил на него наблюдение над общей статистической отчетностью. Каких только анкет, опросных листов и бланков ни просматривал он, каких требовательных ведомостей ни заполнял!<br/> Смертность, рост заболеваемости, имущественное положение служащих, высота их гражданской сознательности и степень участия в выборах, неудовлетворимая нужда в топливе, продовольствии, медикаментах, всё интересовало центральное статистическое управление, на всё требовался ответ.<br/> Доктор занимался всем этим за своим старым столом у окна ординаторской. Графленая бумага разных форм и образцов кипами лежала перед ним, отодвинутая в сторону. Иногда урывками, кроме периодических записей для своих медицинских трудов, он писал здесь свою «Игру в людей», мрачный дневник или журнал тех дней, состоявший из прозы, стихов и всякой всячины, внушенной сознанием, что половина людей перестала быть собой и неизвестно что рызыгрывает.<br/> Светлая солнечная ординаторская со стенами, выкрашенными в белую краску, была залита кремовым светом солнца золотой осени, отличающим дни после Успения, когда по утрам ударяют первые заморозки и в пестроту и яркость поределых рощ залетают зимние синицы и сороки. Небо в такие дни подымается в предельную высоту и сквозь прозрачный столб воздуха между ним и землей тянет с севера ледяной темно-синею ясностью.<br/> Повышается видимость и слышимость всего на свете, чего бы ни было. Расстояния передают звук в замороженной звонкости, отчетливо и разъединенно. Расчищаются дали, как бы открывши вид через всю жизнь на много лет вперед. Этой разреженности нельзя было бы вынести, если бы она не была так кратковременна и не наступала в конце короткого осеннего дня на пороге ранних сумерек.<br/> Такой свет озарял ординаторскую, свет рано садящегося осеннего солнца, сочный, стеклянный и водянистый, как спелое яблоко белый налив.<br/> Доктор сидел у стола, обмакивая перо в чернила, задумывался и писал, а мимо больших окон ординаторской близко пролетали какие-то тихие птицы, забрасывая в комнату бесшумные тени, которые покрывали движущиеся руки доктора, стол с бланками, пол и стены ординаторской и так же бесшумно исчезали.<br/> — Клен опадает, — сказал вошедший прозектор, плотный когда-то мужчина, на котором кожа от похудания висела теперь мешками. — Поливали его ливни, ветры трепали и не могли одолеть. А что один утренник сделал!<br/> Доктор поднял голову. Действительно, сновавшие мимо окна загадочные птицы оказались винно-огненными листьями клена, которые отлетали прочь, плавно держась в воздухе, и оранжевыми выгнутыми звездами ложились в стороне от деревьев на траву больничного газона.<br/> — Окна замазали? — спросил прозектор.<br/> — Нет, — сказал Юрий Андреевич и продолжал писать.<br/> — Что так? Пора.<br/> Юрий Андреевич ничего не отвечал, поглощенный писанием.<br/> — Эх, Тарасюка нет, — продолжал прозектор. — Золотой был человек. И сапоги починит. И часы. И всё сделает. И всё на свете достанет. А замазывать пора. Надо самим.<br/> — Замазки нет.<br/> — А вы сами. Вот рецепт. — И прозектор объяснил, как приготовить замазку из олифы и мела. — Впрочем, ну вас. Я вам мешаю.<br/> Он отошел к другому окну и занялся своими склянками и препаратами. Стало темнеть. Через минуту он сказал:<br/> — Глаза испортите. Темно. А огня не дадут. Пойдемте домой.<br/> — Еще немного поработаю. Минут двадцать.<br/> — Его жена тут в больничных няньках.<br/> — Чья?<br/> — Тарасюка.<br/> — Знаю.<br/> — А сам он неизвестно где. По всей земле рыщет. Летом два раза проведывал. В больницу заходил. Теперь где-нибудь в деревне. Основывает новую жизнь. Это из тех солдат-большевиков, которых вы на бульварах видите и в поездах. А хотите знать разгадку? Тарасюка, например? Слушайте. Это мастер на все руки. Ничего не может делать плохо. За что ни возьмется, дело в руках горит. То же самое случилось с ним на войне. Изучил и ее, как всякое ремесло. Оказался чудным стрелком. В окопах, в секрете. Глаз, рука — первый сорт! Все знаки отличия не за лихость, а за бой без промаха. Ну. Всякое дело становится у него страстью. Полюбил и военное. Видит, оружие это сила, вывозит его. Самому захотелось стать силою. Вооруженный человек это уже не просто человек. В старину такие шли из стрельцов в разбойники. Отыми у него теперь винтовку, попробуй. И вдруг подоспевает клич: «Повернуть штык» и так далее. Он и повернул. Вот вам и весь сказ. И весь марксизм.<br/> — И притом пренастоящий, из самой жизни. А вы что думали?<br/> Прозектор отошел к своему подоконнику, покопался над пробирками. Потом спросил:<br/> — Ну как печник?<br/> — Спасибо, что рекомендовали. Преинтересный человек. Около часа беседовали о Гегеле и Бенедетто Кроче.<br/> — Ну как же! Доктор философии гейдельбергского университета. А печка?<br/> — И не говорите.<br/> — Дымит?<br/> — Одно горе.<br/> — Трубу не туда вывел. Надо вмазать в печь, а он верно выпустил в форточку.<br/> — Да он в голландку вставил. А дымит.<br/> — Значит дымового рукава не нашел, повел вентиляционным каналом. А то в отдушину. Эх, Тарасюка нет! А вы потерпите. Не в один день Москва построилась. Печку топить это вам не на рояли играть. Надо поучиться. Дров запасли?<br/> — А где их взять?<br/> — Я вам церковного сторожа пришлю. Дровяной вор. Разбирает заборы на топливо. Но предупреждаю. Надо торговаться. Запрашивает. Или бабу-морильщицу.<br/> Они спустились в швейцарскую, оделись, вышли на улицу.<br/> — Зачем морильщицу? — сказал доктор. — У нас клопов не водится.<br/> — При чем тут клопы? Я про Фому, а вы про Ерему. Не клопы, а дрова. У этой всё поставлено на коммерческую ногу. Дома и срубы скупает на топливо. Серьезная поставщица. Смотрите, не оступитесь, темь какая. Бывало, я с завязанными глазами мог по этому району пройти. Каждый камушек знал. Пречистенский уроженец. А стали заборы валить, и с открытыми глазами ничего не узнаю, как в чужом городе. Зато какие уголки обнажились!<br/> Ампирные домики в кустарнике, круглые садовые столы, полусгнившие скамейки. На днях прохожу мимо такого пустырька, на пересечении трех переулков. Смотрю, столетняя старуха клюкой землю ковыряет. «Бог в помощь, — говорю, — бабушка. Червей копаешь, рыболовствуешь?» Разумеется, в шутку. А она пресерьезнейше: «Никак нет, батюшка, — шампиньоны». И, правда, стало в городе, как в лесу. Пахнет прелым листом, грибами.<br/> — Я знаю это место. Это между Серебряным и Молчановкой, не правда ли? Со мной там мимоходом всё неожиданности. То кого-нибудь встречу, кого двадцать лет не видал, то что-нибудь найду. И говорят, грабят на углу. Да и неудивительно. Место сквозное. Целая сеть ходов к сохранившимся притонам Смоленского. Оберут, разденут, и фюить, ищи ветра в поле.<br/> — А фонари как слабо светят. Не зря синяки фонарями зовут. Как раз нашибешь.

