### 6 {-}

Действительно, всевозможные случайности преследовали доктора в названном месте. Поздней осенью, незадолго до октябрьских боев, темным холодным вечером он на этом углу наткнулся на человека, лежавшего без памяти поперек тротуара.<br/> Человек лежал, раскинув руки, приклонив голову к тумбе и свесив ноги на мостовую. Изредка с перерывами он слабо постанывал. В ответ на громкие вопросы доктора, пробовавшего привести его в чувство, он пробормотал что-то несвязное и снова на некоторое время потерял сознание. Голова его была разбита и окровавлена, но черепные кости при беглом осмотре оказались целы. Лежавший был несомненно жертвой вооруженного грабежа. «Портфель. Портфель», — два-три раза прошептал он.<br/> По телефону из ближней арбатской аптеки доктор вызвал прикомандированного к Крестовоздвиженской старика извозчика и отвез неизвестного в больницу.<br/> Потерпевший оказался видным политическим деятелем. Доктор вылечил его и в его лице приобрел на долгие годы покровителя, избавлявшего его в это полное подозрений и недоверчивое время от многих недоразумений.

### 7 {-}

Было воскресенье. Доктор был свободен. Ему не надо было на службу. В Сивцевом уже разместились по-зимнему в трех комнатах, как предполагала Антонина Александровна.<br/> Был холодный ветреный день с низкими снеговыми облаками, темный-претемный.<br/> С утра затопили. Стало дымить. Антонина Александровна, ничего не понимавшая в топке, давала Нюше, бившейся с сырыми неразгоравшимися дровами, бестолковые и вредные советы.<br/> Доктор, видевший это и понимавший, что надо сделать, пробовал вмешаться, но жена тихо брала его за плечи и выпроваживала из комнаты со словами:<br/> — Ступай к себе. Когда голова и без того кругом и всё мешается, у тебя привычка непременно говорить под руку. Как ты не понимаешь, что твои замечания только подливают масла в огонь.<br/> — О, масло, Тонечка, это было бы превосходно! Печка мигом бы запылала. То-то и горе, что не вижу я ни масла, ни огня.<br/> — И для каламбуров не время. Бывают, понимаешь, моменты, когда не до них.<br/> Неудачная топка разрушила воскресные планы. Все надеялись, исполнив необходимые дела до темноты, освободиться к вечеру, а теперь это отпадало. Оттягивался обед, чье-то желание помыть горячей водой голову, какие-то другие намерения.<br/> Скоро задымило так, что стало невозможно дышать. Сильный ветер загонял дым назад в комнату. В ней стояло облако черной копоти, как сказочное чудище посреди дремучего бора.<br/> Юрий Андреевич разогнал всех по соседним комнатам и отворил форточку. Половину дров из печки он выкинул вон, а между оставшимися проложил дорожку из мелких щепок и берестяной растопки.<br/> В форточку ворвался свежий воздух. Колыхнувшаяся оконная занавесь взвилась вверх. С письменного стола слетело несколько бумажек. Ветер хлопнул какою-то дальнею дверью и, кружась по всем углам, стал, как кошка за мышью, гоняться за остатками дыма.<br/> Разгоревшиеся дрова вспыхнули и затрещали. Печурка захлебнулась пламенем. В её железном корпусе пятнами чахоточного румянца зарделись кружки красного накала. Дым в комнате поредел и потом исчез совсем.<br/> В комнате стало светлее. Заплакали окна, недавно замазанные Юрием Андреевичем по наставлениям прозектора. Волною хлынул теплый жирный запах замазки. Запахло сушащимися около печки мелко напиленными дровами: горькой, дерущей горло гарью еловой коры и душистой, как туалетная вода, сырой свежею осиной.<br/> В это время в комнату так же стремительно, как воздух в форточку, ворвался Николай Николаевич с сообщением:<br/> — На улицах бой. Идут военные действия между юнкерами, поддерживающими Временное правительство, и солдатами гарнизона, стоящими за большевиков. Стычки чуть ли не на каждом шагу, очагам восстания нет счета. По дороге к вам я два или три раза попал в переделку, раз на углу Большой Дмитровки и другой — у Никитских ворот. Прямого пути уже нет, приходится пробираться обходом. Живо, Юра! Одевайся и пойдем.<br/> Это надо видеть. Это история. Это бывает раз в жизни.<br/> Но сам же он заболтался часа на два, потом сели обедать, а когда, собравшись домой, он потащил с собой доктора, их предупредил приход Гордона. Этот влетел так же, как Николай Николаевич, с теми же самыми сообщениями.<br/> Но события за это время подвинулись вперед. Имелись новые подробности. Гордон говорил об усилившейся стрельбе и убитых прохожих, случайно задетых шальною пулею. По его словам, движение в городе приостановилось. Он чудом проник к ним в переулок, но путь назад закрылся за его спиной.<br/> Николай Николаевич не послушался и попробовал сунуть нос на улицу, но через минуту вернулся. Он сказал, что из переулка нет выхода, по нему свищут пули, отбивая с углов кусочки кирпича и штукатурки. На улице ни души, сообщение по тротуару прервано.<br/> В эти дни Сашеньку простудили.<br/> — Я сто раз говорил, чтобы ребенка не подносили к топящейся печке, — сердился Юрий Андреевич. — Перегрев в сорок раз вреднее выстуживания.<br/> У Сашеньки разболелось горло и появился сильный жар. Его отличительным свойством был сверхъестественный, мистический страх перед тошнотой и рвотой, приближение которых ему ежеминутно мерещилось.<br/> Он отталкивал руку Юрия Андреевича с ларингоскопом, не давал ввести его в горло, закрывал рот, кричал и давился.<br/> Никакие уговоры и угрозы не действовали. Вдруг по неосторожности Сашенька широко и сладко зевнул, и этим воспользовался доктор, чтобы молниеносным движением сунуть сыну в рот ложечку, придержать его язык и успеть разглядеть малиновую гортань Сашеньки и его осыпанные налетами опухшие миндалины. Их вид встревожил Юрия Андреевича.<br/> Немного погодя, путем таких же манипуляций, доктору удалось снять у Сашеньки мазок. У Александра Александровича был свой микроскоп. Юрий Андреевич взял его и с грехом пополам сам произвел исследование. По счастью, это не был дифтерит.<br/> Но на третью ночь у Сашеньки сделался припадок ложного крупа. Он горел и задыхался. Юрий Андреевич не мог смотреть на бедного ребенка, бессильный избавить его от страданий.<br/> Антонине Александровне казалось, что мальчик умирает. Его брали на руки, носили по комнате, и ему становилось легче.<br/> Надо было достать молока, минеральной воды или соды для его отпаиванья. Но это был разгар уличных боев. Пальба, также и орудийная, ни на минуту не прекращалась. Если бы даже Юрий Андреевич с опасностью для жизни отважился пробраться за пределы простреливаемой полосы, он и за чертою огня не встретил бы жизни, которая замерла во всем городе, пока положение не определится окончательно.<br/> Но оно было уже ясно. Отовсюду доходили слухи, что рабочие берут перевес. Бились еще отдельные кучки юнкеров, разобщенные между собой и потерявшие связь со своим командованием.<br/> Район Сивцева входил в круг действий солдатских частей, наседавших на центр с Дорогомилова. Солдаты германской войны и рабочие подростки, сидевшие в окопе, вырытом в переулке, уже знали население окрестных домов и по-соседски перешучивались с их жителями, выглядывавшими из ворот или выходившими на улицу.<br/> Движенье в этой части города восстанавливалось.<br/> Тогда ушли из своего трехдневного плена Гордон и Николай Николаевич, застрявшие у Живаго на трое суток. Юрий Андреевич был рад их присутствию в трудные дни Сашенькиной болезни, а Антонина Александровна прощала им ту бестолочь, которую вносили они в придачу к общему беспорядку. Но в благодарность за гостеприимство оба считали долгом занимать хозяев неумолкаемыми разговорами, и Юрий Андреевич так устал от троесуточного переливания из пустого в порожнее, что был счастлив расстаться с ними.

