### 8 {-}

Были сведения, что они добрели домой благополучно, хотя именно при этой проверке оказалось, что толки об общем замирении преждевременны. В разных местах военные действия еще продолжались, через некоторые районы нельзя было пройти, и доктор все не мог пока попасть к себе в больницу, по которой успел соскучиться и где в ящике стола в ординаторской лежали его «Игра» и ученые записи.<br/> Лишь внутри отдельных околотков люди выходили по утрам на небольшое расстояние от дома за хлебом, останавливали встречных, несших молоко в бутылках, и толпой расспрашивали, где они его достали.<br/> Иногда возобновлялась перестрелка по всему городу, снова разгоняя публику. Все догадывались, что между сторонами идут какие-то переговоры, успешный или неуспешный ход которых отражается на усилении или ослаблении шрапнельной стрельбы.<br/> Как-то в конце старого октября, часов в десять вечера Юрий Андреевич быстро шел по улице, направляясь без особой надобности к одному близко жившему сослуживцу. Места эти, обычно бойкие, были малолюдны. Встречных почти не попадалось.<br/> Юрий Андреевич шел быстро. Порошил первый реденький снежок с сильным и все усиливающимся ветром, который на глазах у Юрия Андреевича превращался в снежную бурю.<br/> Юрий Андреевич загибал из одного переулка в другой и уже утерял счет сделанным поворотам, как вдруг снег повалил густо-густо и стала разыгрываться метель, та метель, которая в открытом поле с визгом стелется по земле, а в городе мечется в тесном тупике, как заблудившаяся.<br/> Что-то сходное творилось в нравственном мире и в физическом, вблизи и вдали, на земле и в воздухе. Где-то, островками, раздавались последние залпы сломленного сопротивления. Где-то на горизонте пузырями вскакивали и лопались слабые зарева залитых пожаров. И такие же кольца и воронки гнала и завивала метель, дымясь под ногами у Юрия Андреевича на мокрых мостовых и панелях.<br/> На одном из перекрестков с криком «Последние известия!» его обогнал пробегавший мимо мальчишка газетчик с большой кипой свежеотпечатанных оттисков под мышкой.<br/> — Не надо сдачи, — сказал доктор. Мальчик еле отделил прилипший к кипе сырой листок, сунул его доктору в руки и канул в метель так же мгновенно, как из нее вынырнул.<br/> Доктор подошел к горевшему в двух шагах от него уличному фонарю, чтобы тут же, не откладывая, пробежать главное.<br/> Экстренный выпуск, покрытый печатью только с одной стороны, содержал правительственное сообщение из Петербурга об образовании Совета Народных Комиссаров, установлении в России советской власти и введении в ней диктатуры пролетариата.<br/> Далее следовали первые декреты новой власти и публиковались разные сведения, переданные по телеграфу и телефону.<br/> Метель хлестала в глаза доктору и покрывала печатные строчки газеты серой и шуршащей снежной крупою. Но не это мешало его чтению. Величие и вековечность минуты потрясли его и не давали опомниться.<br/> Чтобы все же дочитать сообщения, он стал смотреть по сторонам в поисках какого-нибудь освещенного места, защищенного от снега. Оказалось, что он опять очутился на своем заколдованном перекрестке и стоит на углу Серебряного и Молчановки, у подъезда высокого пятиэтажного дома со стеклянным входом и просторным, освещенным электричеством, парадным.<br/> Доктор вошел в него и в глубине сеней под электрической лампочкой углубился в телеграммы.<br/> Наверху над его головой послышались шаги. Кто-то спускался по лестнице, часто останавливаясь, словно в какой-то нерешительности. Действительно, спускавшийся вдруг раздумал, повернул назад и взбежал наверх. Где-то отворили дверь, и волною разлились два голоса, обесформленные гулкостью до того, что нельзя было сказать, какие они, мужские или женские. После этого хлопнула дверь, и ранее спускавшийся стал сбегать вниз гораздо решительнее.<br/> Глаза Юрия Андреевича, с головой ушедшего в чтение, были опущены в газету. Он не собирался подымать их и разглядывать постороннего. Но, добежав донизу, тот с разбега остановился.<br/> Юрий Андреевич поднял голову и посмотрел на спускавшегося.<br/> Перед ним стоял подросток лет восемнадцати в негнущейся оленьей дохе, мехом наружу, как носят в Сибири, и такой же меховой шапке. У мальчика было смуглое лицо с узкими киргизскими глазами. Было в этом лице что-то аристократическое, та беглая искорка, та прячущаяся тонкость, которая кажется занесенной издалека и бывает у людей со сложной, смешанной кровью.<br/> Мальчик находился в явном заблуждении, принимая Юрия Андреевича за кого-то другого. Он с дичливою растерянностью смотрел на доктора, как бы зная, кто он, и только не решаясь заговорить. Чтобы положить конец недоразумению, Юрий Андреевич смерил его взглядом и обдал холодом, отбивающим охоту к сближению.<br/> Мальчик смешался и, не сказав ни слова, направился к выходу. Здесь, оглянувшись еще раз, он отворил тяжелую, расшатанную дверь и, с лязгом её захлопнув, вышел на улицу.<br/> Минут через десять последовал за ним и Юрий Андреевич. Он забыл о мальчике и о сослуживце, к которому собирался. Он был полон прочитанного и направился домой. По пути другое обстоятельство, бытовая мелочь, в те дни имевшая безмерное значение, привлекла и поглотила его внимание.<br/> Немного не доходя до своего дома, он в темноте наткнулся на огромную кучу досок и бревен, сваленную поперек дороги на тротуаре у края мостовой. Тут в переулке было какое-то учреждение, которому, вероятно, привезли казенное топливо в виде какого-то разобранного на окраине бревенчатого дома.<br/> Бревна не умещались во дворе и загромождали прилегавшую часть улицы. Эту гору стерег часовой с ружьем, ходивший по двору и от времени до времени выходивший в переулок.<br/> Юрий Андреевич, не задумываясь, улучил минуту, когда часовой завернул во двор, а налетевший вихрь закрутил в воздухе особенно густую тучу снежинок. Он зашел к куче балок с той стороны, где была тень и куда не падал свет фонаря, и медленным раскачиванием высвободил лежавшую с самого низа тяжелую колоду. С трудом вытащив её из-под кучи и взвалив на плечо, он перестал чувствовать её тяжесть (своя ноша не тянет) и украдкой вдоль затененных стен притащил к себе в Сивцев.<br/> Это было кстати, дома кончились дрова. Колоду распилили и накололи из нее гору мелких чурок. Юрий Андреевич присел на корточки растапливать печь. Он молча сидел перед вздрагивавшей и дребезжавшей дверцей. Александр Александрович подкатил к печке кресло и подсел греться. Юрий Андреевич вытащил из бокового кармана пиджака газету и протянул тестю со словами:<br/> — Видали? Полюбуйтесь. Прочтите.<br/> Не вставая с корточек и ворочая дрова в печке маленькой кочережкой, Юрий Андреевич громко разговаривал с собой.<br/> — Какая великолепная хирургия! Взять и разом артистически вырезать старые вонючие язвы! Простой, без обиняков, приговор вековой несправедливости, привыкшей, чтобы ей кланялись, расшаркивались перед ней и приседали.<br/> В том, что это так без страха доведено до конца, есть что-то национально-близкое, издавна знакомое. Что-то от безоговорочной светоносности Пушкина, от невиляющей верности фактам Толстого.<br/> — Пушкина? Что ты сказал? Погоди. Сейчас я кончу. Не могу же я сразу и читать и слушать, — прерывал зятя Александр Александрович, ошибочно относя к себе монолог, произносимый Юрием Андреевичем себе под нос.<br/> — Главное, что гениально? Если бы кому-нибудь задали задачу создать новый мир, начать новое летоисчисление, он бы обязательно нуждался в том, чтобы ему сперва очистили соответствующее место. Он бы ждал, чтобы сначала кончились старые века, прежде чем он приступит к постройке новых, ему нужно было бы круглое число, красная строка, неисписанная страница.<br/> А тут, нате пожалуйста. Это небывалое, это чудо истории, это откровение ахнуто в самую гущу продолжающейся обыденщины, без внимания к её ходу. Оно начато не с начала, а с середины, без наперед подобранных сроков, в первые подвернувшиеся будни, в самый разгар курсирующих по городу трамваев. Это всего гениальнее. Так неуместно и несвоевременно только самое великое.

