### 9 {-}

Настала зима, какую именно предсказывали. Она еще не так пугала, как две наступившие вслед за нею, но была уже из их породы, темная, голодная и холодная, вся в ломке привычного и перестройке всех основ существования, вся в нечеловеческих усилиях уцепиться за ускользающую жизнь.<br/> Их было три подряд, таких страшных зимы, одна за другой, и не всё, что кажется теперь происшедшим с семнадцатого на восемнадцатый год, случилось действительно тогда, а произошло, может статься, позже. Эти следовавшие друг за другом зимы слились вместе, и трудно отличимы одна от другой.<br/> Старая жизнь и молодой порядок еще не совпадали. Между ними не было ярой вражды, как через год, во время гражданской войны, но недоставало и связи. Это были стороны, расставленные отдельно, одна против другой, и не покрывавшие друг друга.<br/> Производили перевыборы правлений везде: в домовладениях, в организациях, на службе, в обслуживающих население учреждениях. Состав их менялся. Во все места стали назначать комиссаров с неограниченными полномочиями, людей железной воли, в черных кожаных куртках, вооруженных мерами устрашения и наганами, редко брившихся и еще реже спавших.<br/> Они хорошо знали порождение мещанства, среднего держателя мелких государственных бумаг, пресмыкающегося обывателя, и, ничуть не щадя его, с мефистофельской усмешкой разговаривали с ним, как с пойманным воришкой.<br/> Эти люди ворочали всем, как приказывала программа, и начинание за начинанием, объединение за объединением становились большевицкими.<br/> Крестовоздвиженская больница теперь называлась Второй преобразованной. В ней произошли перемены. Часть персонала уволили, а многие ушли сами, найдя, что им служить невыгодно.<br/> Это были хорошо зарабатывавшие доктора с модной практикой, баловни света, фразеры и краснобаи. Свой уход по корыстным соображениям они не преминули выдать за демонстративный, по мотивам гражданственности, и стали относиться пренебрежительно к оставшимся, чуть ли не бойкотировать их. В числе этих оставшихся, презираемых был и Живаго.<br/> Вечерами между мужем и женою происходили такие разговоры:<br/> — В среду не забудь в подвал общества врачей за мороженой картошкой. Там два мешка. Я выясню точно, в котором часу я освобождаюсь, чтобы помочь. Надо будет вдвоем на салазках.<br/> — Хорошо. Успеется, Юрочка. Ты бы скорее лег. Поздно. Всех дел все равно не переделаешь. Надо тебе отдохнуть.<br/> — Повальная эпидемия. Общее истощение ослабляет сопротивляемость. На тебя и папу страшно смотреть. Надо что-то предпринять. Да, но что именно? Мы недостаточно бережемся. Надо быть осторожнее. Слушай. Ты не спишь?<br/> — Нет.<br/> — Я за себя не боюсь, я двужильный, но если бы, паче чаяния, я свалился, не глупи, пожалуйста, и дома не оставляй. Моментально в больницу.<br/> — Что ты, Юрочка! Господь с тобой. Зачем каркать раньше времени?<br/> — Помни, больше нет ни честных, ни друзей, ни тем более знающих. Если бы что-нибудь случилось, доверяй только Пичужкину. Разумеется, если сам он уцелеет. Ты не спишь?<br/> — Нет.<br/> — Сами, черти, ушли на лучший паек, а теперь, оказывается, это были гражданские чувства, принципиальность. Встречают, едва руку подают. «Вы у них служите?» И подымают брови. «Служу, — говорю, — и прошу не прогневаться: нашими лишениями я горжусь, и людей, которые делают нам честь, подвергая нас этим лишениям, уважаю».

