### 10 {-}

На долгий период постоянной пищей большинства стало пшено на воде и уха из селедочных головок. Туловище селедки в жареном виде шло на второе. Питались немолотою рожью и пшеницей в зерне. Из них варили кашу.<br/> Знакомая профессорша учила Антонину Александровну печь заварной хлеб на поду комнатной голландки, частью на продажу, чтобы припеком и выручкой оправдать пользование кафельной печью, как в старые годы. Это позволило бы отказаться от мучительницы времянки, которая дымила, плохо грела и совсем не держала тепла.<br/> Хлеб хорошо выпекался у Антонины Александровны, но из её торговли ничего не вышло. Пришлось пожертвовать несбыточными планами и опять ввести в действие оставленную печурку. Живаго бедствовали.<br/> Однажды утром Юрий Андреевич по обыкновению ушел по делам.<br/> Дров в доме оставалось два полена. Надевши шубку, в которой она зябла от слабости даже в теплую погоду, Антонина Александровна вышла «на добычу».<br/> Она с полчаса пробродила по ближайшим переулкам, куда иногда заворачивали мужички с овощами и картошкой из пригородных деревень. Их надо было ловить. Крестьян с кладью задерживали.<br/> Скоро она напала на цель своих розысков. Молодой здоровенный детина в армяке, шагая в сопровождении Антонины Александровны рядом с легкими, как игрушка, санями, осторожно отвел их за угол во двор к Громекам.<br/> В лубяном кузове саней под рогожей лежала небольшая кучка березового кругляку, не толще старомодных усадебных перилец на фотографиях прошлого века. Антонина Александровна знала им цену, — одно званье, что береза, а то сырье худшего сорта, свежей резки, непригодное для топки. Но выбора не было, рассуждать не приходилось.<br/> Молодой крестьянин в пять-шесть приемов снес ей дровишки на жилой верх, а в обмен на них поволок на себе вниз и уложил в сани малый зеркальный шкал Антонины Александровны, в подарок своей молодке. Мимоходом, договариваясь на будущее время о картошке, он приценился к стоявшему у дверей пианино.<br/> Вернувшись, Юрий Андреевич не стал обсуждать жениной покупки. Разрубить отданный шкап на щепки было выгодней и целесообразней, но у них рука не поднялась бы на это.<br/> — Ты видел записку на столе? — спросила жена.<br/> — От заведующего больницей? Мне говорили, я знаю. Это приглашение к больной. Непременно пойду. Вот отдохну немного и пойду. Но порядочная даль. Где-то у Триумфальных ворот. У меня записан адрес.<br/> — Странный гонорар предлагают. Ты видел? Ты все-таки прочти. Бутылку германского коньяку или пару дамских чулок за визит. Чем заманивают. Кто это может быть? Какой-то дурной тон и полное неведение о нашей современной жизни. Нувориши какие-нибудь.<br/> — Да, это к заготовщику.<br/> Таким именем, вместе с концессионерами и уполномоченными, назывались мелкие частные предприниматели, которым государственная власть, уничтожив частную торговлю, делала в моменты хозяйственных обострений маленькие послабления, заключая с ними договоры и сделки на разные поставки.<br/> В их число уже не попадали сваленные главы старых фирм, собственники крупного почина. От полученного удара они уже не оправлялись. В эту категорию шли дельцы однодневки, поднятые со дна войной и революцией, новые и пришлые люди без корня.<br/> Выпив забеленного молоком кипятку с сахарином, доктор направился к больной.<br/> Тротуары и мостовые были погребены под глубоким снегом, покрывавшим улицы от одного ряда домов до другого. Снежный покров местами доходил до окон первых этажей. Во всю ширину этого пространства двигались молчаливые полуживые тени, тащившие на себе или везшие на салазках какое-нибудь тощее продовольствие. Едущих почти не попадалось.<br/> На домах кое-где еще оставались прежние вывески.<br/> Размещенные под ними без соответствия с их содержанием потребиловки и кооперативы стояли запертые, с окнами под решеткою, или заколоченные, и пустовали.<br/> Они были заперты и пустовали не только вследствие отсутствия товаров, но также оттого, что переустройство всех сторон жизни, охватившее и торговлю, совершалось еще в самых общих чертах и этих заколоченных лавок, как мелких частностей, еще не коснулось.

