### 11 {-}

Дом, куда был приглашен доктор, оказался в конце Брестской, близ Тверской заставы.<br/> Это было кирпичное казарменное здание допотопной стройки, с двором внутри и деревянными галереями, шедшими в три яруса вдоль задних надворных стен строения.<br/> У жильцов происходило ранее назначенное общее собрание при участии представительницы из райсовета, как вдруг в дом явилась с обходом военная комиссия, проверявшая разрешения на хранение оружия и изымавшая неразрешенное. Руководивший обходом начальник просил делегатку не удаляться, уверив, что обыск не займет много времени, освобождаемые квартиранты постепенно сойдутся, и прерванное заседание можно будет скоро возобновить.<br/> Обход приближался к концу и на очереди была как раз та квартира, куда ждали доктора, когда он подошел к воротам дома.<br/> Солдат с винтовкой на веревочке, который стоял на часах у одной из лестниц, ведших на галереи, наотрез отказался пропустить Юрия Андреевича, но в их спор вмешался начальник отряда. Он не велел чинить препятствий доктору и согласился подождать с обыском квартиры, пока он осмотрит больную.<br/> Доктора встретил хозяин квартиры, вежливый молодой человек с матовым смуглым лицом и темными меланхолическими глазами. Он был взволнован многими обстоятельствами: болезнью жены, нависавшим обыском и сверхъестественным уважением, которое он питал к медицине и её представителям.<br/> Чтобы сократить доктору труд и время, хозяин старался говорить как можно короче, но именно эта торопливость делала его речь длинной и сбивчивой.<br/> Квартира со смесью роскоши и дешевки обставлена была вещами, наспех скупленными с целью помещения денег во что-нибудь устойчивое. Мебель из расстроенных гарнитуров дополняли единичные предметы, которым до полноты комплекта недоставало парных.<br/> Хозяин квартиры считал, что у его жены какая-то болезнь нервов от перепуга. Со многими не идущими к делу околичностями он рассказал, что им продали за бесценок старинные испорченные куранты с музыкой, давно уже не шедшие. Они купили их только как достопримечательность часового мастерства, как редкость (муж больной повел доктора в соседнюю комнату показывать их).<br/> Сомневались даже, можно ли их починить. И вдруг часы, годами не знавшие завода, пошли сами собой, пошли, вызвонили на колокольчиках свой сложный менуэт и остановились. Жена пришла в ужас, рассказывал молодой человек, решив, что это пробил её последний час, и вот теперь лежит, бредит, не ест, не пьет, не узнает его.<br/> — Так вы думаете, что это нервное потрясение? — с сомнением в голосе спросил Юрий Андреевич. — Проводите меня к больной.<br/> Они вошли в соседнюю комнату с фарфоровой люстрой и двумя тумбочками красного дерева по бокам широкой двуспальной кровати. На её краю, натянув одеяло выше подбородка, лежала маленькая женщина с большими черными глазами. При виде вошедших она погнала их прочь взмахом выпростанной из-под одеяла руки, с которой скользнул к подмышке широкий рукав халата. Она не узнавала мужа и, словно никого не было в комнате, тихим голосом запела начало какой-то грустной песенки, которая так её разжалобила, что она расплакалась и, всхлипывая по-детски, стала проситься куда-то домой. С какого бока ни заходил к ней доктор, она противилась осмотру, каждый раз поворачиваясь к нему спиной.<br/> — Надо бы посмотреть ее, — сказал Юрий Андреевич. — Но всё равно, мне и так ясно. Это сыпняк, и притом в довольно тяжелой форме. Она порядком мучится, бедняжка. Я бы советовал поместить её в больницу. Дело не в удобствах, которых вы ей предоставите, а в постоянном врачебном присмотре, который необходим в первые недели болезни. Можете ли вы обеспечить что-нибудь перевозочное, раздобыть извозчика, или в крайнем случае ломовые дровни, чтобы отвезти больную, разумеется, предварительно хорошо закутав? Я вам выпишу направление.<br/> — Могу. Постараюсь. Но погодите. Неужели правда это тиф? Какой ужас!<br/> — К сожалению.<br/> — Я боюсь потерять ее, если отпущу от себя. Вы никак не могли бы лечить её дома, по возможности участив посещения? Я предложил бы вам какое угодно вознаграждение.<br/> — Я ведь объяснил вам. Важно непрерывное наблюдение за ней. Послушайте. Я даю вам хороший совет. Хоть из-под земли достаньте извозчика, а я составлю ей препроводительную записку. Лучше всего сделать это в вашем домовом комитете. Под направлением потребуется печать дома и еще кое-какие формальности.

