### 13 {-}

Уже совсем стемнело. Кругом была ночь. Только белый кружок света из карманного фонарика Деминой шагах в пяти перед ними скакал с сугроба на сугроб и больше сбивал с толку, чем освещал идущим дорогу. Кругом была ночь, и дом остался позади, где столько людей знало ее, где она бывала девочкой, где, по рассказам, мальчиком воспитывался её будущий муж, Антипов.<br/> Демина покровительственно-шутливо обращалась к нему:<br/> — Вы правда дальше без фонарика дойдете? А? А то бы я дала, товарищ доктор. Да. Я когда-то не на шутку в нее врезамшись была, любила без памяти, когда девочками мы были. У них швейное заведение было, мастерская. Я у них в ученицах жила. Нынешний год видались с ней. Проезжала. Проездом в Москве была. Я ей говорю, куда ты, дура? Оставалась бы. Вместе бы жили, нашлась бы тебе работа. Куда там! Не хочет. Ее дело.<br/> Головой она за Пашку вышла, а не сердцем, с тех пор и шалая.<br/> Уехала.<br/> — Что вы о ней думаете?<br/> — Осторожно. Скользко тут. Сколько раз говорила, чтобы не выливали помоев перед дверью, — как об стену горох. Что о ней думаю? Как это думаю? А чего тут думать. Некогда. Вот тут я живу. Я от нее скрыла, брата ее, военного, похоже, расстреляли. А мать ее, прежнюю мою хозяйку, я наверное выручу, хлопочу за нее. Ну, мне сюда, до свидания.<br/> И вот они расстались. Свет Деминского фонарика ткнулся внутрь узкой каменной лестницы и побежал вперед, освещая испачканные стены грязного подъема, а доктора обступила тьма.<br/> Направо легла Садовая-Триумфальная, налево Садовая-Каретная. В черной дали на черном снегу это уже были не улицы в обычном смысле слова, а как бы две лесные просеки в густой тайге тянущихся каменных зданий, как в непроходимых дебрях Урала или Сибири.<br/> Дома были свет, тепло.<br/> — Что так поздно? — спросила Антонина Александровна и, не дав ему ответить, продолжала:<br/> — А тут без тебя курьез произошел. Необъяснимая странность. Я забыла тебе сказать. Вчера папа будильник сломал и был в отчаянии. Последние часы в доме. Стал чинить, ковырял, ковырял, ничего не выходит. Часовщик на углу три фунта хлеба запросил, неслыханная цена. Что тут делать? Папа совсем голову повесил. И вдруг, представь, час тому назад пронзительный, оглушительный звон. Будильник! Взял, понимаешь, и пошел!<br/> — Это мой тифозный час пробил, — пошутил Юрий Андреевич и рассказал родным про больную с курантами.

