### 14 {-}

Но тифом он заболел гораздо позднее. В промежутке бедствия семьи Живаго достигли крайности. Они нуждались и погибали.<br/> Юрий Андреевич разыскал спасенного однажды партийца, жертву ограбления. Тот делал что мог для доктора. Однако началась гражданская война. Его покровитель все время был в разъездах.<br/> Кроме того, в согласии со своими убеждениями этот человек считал тогдашние трудности естественными и скрывал, что сам голодает.<br/> Пробовал Юрий Андреевич обратиться к заготовщику близ Тверской заставы. Но за истекшие месяцы того и след простыл, и о его выздоровевшей жене тоже не было ни слуху, ни духу.<br/> Состав жильцов в доме переменился. Демина была на фронте, управляющей Галиуллиной Юрий Андреевич не застал.<br/> Однажды он по ордеру получил по казенной цене дрова, которые надо было вывезти с Виндавского вокзала. По бесконечной Мещанской он конвоировал возчика и клячу, тащившую это нежданное богатство. Вдруг доктор заметил, что Мещанская немного перестает быть Мещанской, что его шатает и ноги не держат его. Он понял, что он готов, дело дрянь, и это — тиф.<br/> Возчик подобрал упавшего. Доктор не помнил, как его довезли до дому, кое-как примостивши на дровах.

### 15 {-}

У него был бред две недели с перерывами. Ему грезилось, что на его письменный стол Тоня поставила две Садовые, слева Садовую Каретную, а справа Садовую Триумфальную и придвинула близко к ним его настольную лампу, жаркую, вникающую, оранжевую. На улицах стало светло. Можно работать. И вот он пишет.<br/> Он пишет с жаром и необыкновенной удачей то, что он всегда хотел и должен был давно написать, но никогда не мог, а вот теперь оно выходит. И только иногда мешает один мальчик с узкими киргизскими глазами в распахнутой оленьей дохе, какие носят в Сибири или на Урале.<br/> Совершенно ясно, что мальчик этот — дух его смерти или, скажем просто, его смерть. Но как же может он быть его смертью, когда он помогает ему писать поэму, разве может быть польза от смерти, разве может быть в помощь смерть?<br/> Он пишет поэму не о воскресении и не о положении во гроб, а о днях, протекших между тем и другим. Он пишет поэму «Смятение».<br/> Он всегда хотел написать, как в течение трех дней буря черной червивой земли осаждает, штурмует бессмертное воплощение любви, бросаясь на него своими глыбами и комьями, точь-в-точь как налетают с разбега и хоронят под собою берег волны морского прибоя. Как три дня бушует, наступает и отступает черная земная буря. И две рифмованные строчки преследовали его:<br/> Рады коснуться и Надо проснуться.<br/> Рады коснуться и ад, и распад, и разложение, и смерть, и, однако, вместе с ними рада коснуться и весна, и Магдалина, и жизнь. И — надо проснуться. Надо проснуться и встать. Надо воскреснуть.

