### 16 {-}

Он стал выздоравливать. Сначала, как блаженный, он не искал между вещами связи, все допускал, ничего не помнил, ничему не удивлялся. Жена кормила его белым хлебом с маслом и поила чаем с сахаром, давала ему кофе. Он забыл, что этого не может теперь быть, и радовался вкусной пище, как поэзии и сказке, законным и полагающимся при выздоровлении. Но в первый же раз, что он стал соображать, он спросил жену:<br/> — Откуда это у тебя?<br/> — Да всё твой Граня.<br/> — Какой Граня?<br/> — Граня Живаго.<br/> — Граня Живаго?<br/> Ну да, твой омский брат Евграф. Сводный брат твой. Ты без сознания лежал, он нас всё навещал.<br/> — В оленьей дохе?<br/> — Да, да. Ты сквозь беспамятство, значит, замечал? Он в каком-то доме на лестнице с тобой столкнулся, я знаю, он рассказывал. Он знал, что это ты, и хотел представиться, но ты на него такого страху напустил! Он тебя обожает, тобой зачитывается. Он из-под земли такие вещи достает! Рис, изюм, сахар. Он уехал опять к себе. И нас зовет. Он такой чудной, загадочный. По-моему, у него какой-то роман с властями. Он говорит, что на год, на два надо куда-нибудь уехать из больших городов, «на земле посидеть». Я с ним советовалась насчет Крюгеровских мест. Он очень рекомендует. Чтобы можно было огород развести, и чтобы лес был под рукой. А то нельзя же погибать так покорно, по-бараньи.<br/> В апреле того же года Живаго всей семьей выехали на далекий Урал, в бывшее имение Варыкино, близ города Юрятина.

