## ЧАСТЬ седьмая. В ДОРОГЕ {-}

### 1 {-}

Настали последние дни марта, дни первого в году тепла, ложные предвестники весны, за которыми каждый год наступает сильное похолодание.<br/> В доме Громеко шли спешные сборы в дорогу. Перед многочисленными жильцами, которых в уплотненном доме теперь было больше, чем воробьев на улице, эти хлопоты выдавали за генеральную уборку перед Пасхой.<br/> Юрий Андреевич был против поездки. Он не мешал приготовлениям, потому что считал затею неосуществимой и надеялся, что в решающую минуту она провалится. Но дело подвигалось вперед и близилось к завершению. Пришло время поговорить серьезно.<br/> Он еще раз высказал жене и тестю свои сомнения на устроенном для этого семейном совете.<br/> — Итак, вы считаете, что я не прав, и, следовательно, мы едем? — закончил он свои возражения. Слово взяла жена:<br/> — Ты говоришь, перебиться год-другой, тем временем упорядочатся новые земельные отношения, можно будет испросить полоску под Москвой, развести огород. А как продержаться в промежутке, ты не советуешь. Между тем это самое интересное, вот что именно желательно было бы услышать.<br/> — Абсолютный бред, — поддержал дочь Александр Александрович.<br/> — Хорошо, я сдаюсь, — соглашался Юрий Андреевич. — Меня останавливает только полная неизвестность.<br/> Мы пускаемся, зажмурив глаза, неведомо куда, не имея о месте ни малейшего представления. Из трех человек, живших в Варыкине, двух, мамы и бабушки, нет в живых, а третий, дедушка Крюгер, если он только и жив, в заложниках и за решеткой.<br/> В последний год войны он что-то проделал с лесами и заводом, для видимости продал какому-то подставному лицу или банку или на кого-то условно переписал. Что мы знаем об этой сделке? Чьи это теперь земли, не в смысле собственности, пропади она пропадом, а кто за них отвечает? За каким они ведомством? Рубят ли лес? Работают ли заводы? Наконец, какая там власть, и какая будет, пока мы туда доберемся?<br/> Для вас якорь спасения в Микулицыне, имя которого вы так любите повторять. Но кто вам сказал, что этот старый управляющий жив и по-прежнему в Варыкине? Да и что мы знаем о нем, кроме того, что дедушка с трудом выговаривал эту фамилию, отчего мы её и запомнили?<br/> Однако к чему спорить? Вы решили ехать. Я присоединяюсь. Надо выяснить, как это теперь делают. Нечего откладывать.

### 2 {-}

Для того чтобы об этом справиться, Юрий Андреевич пошел на Ярославский вокзал.<br/> Поток уезжающих сдерживали мостки с перилами, протянутые через залы, на каменных полах которых лежали люди в серых шинелях, ворочались с боку на бок, кашляли и сплевывали, а когда заговаривали друг с другом, то каждый раз несоответственно громко, не рассчитавши силы, с какой отдавались голоса под гулкими сводами.<br/> В большинстве это были больные, перенесшие сыпной тиф. Ввиду переполнения больниц, их выписывали на другой день после кризиса. Как врач, Юрий Андреевич сам сталкивался с такой необходимостью, но он не знал, что этих несчастных так много и что приютом им служат вокзалы.<br/> — Добывайте командировку, — говорил ему носильщик в белом фартуке. Надо каждый день наведываться. Поезда теперь редкость, дело случая. И само собой разумеется… (носильщик потер большой палец о два соседних)… Мучицы там или чего-нибудь. Не подмажешь — не поедешь. Ну, а это самое… (он щелкнул себя по горлу)… совсем святое дело.

