### 3 {-}

Около этого времени Александра Александровича пригласили на несколько разовых консультаций в Высший Совет Народного Хозяйства, а Юрия Андреевича — к тяжело заболевшему члену правительства. Обоим выдали вознаграждение в наилучшей по тому времени форме — ордерами в первый учрежденный тогда закрытый распределитель.<br/> Он помещался в каких-то гарнизонных складах у Симонова монастыря. Доктор с тестем пересекли два проходных двора, церковный и казарменный и прямо с земли, без порога, вошли под каменные своды глубокого, постепенно понижавшегося подвала.<br/> Расширяющийся конец его был перегорожен длинной поперечной стойкой, у которой, изредка отлучаясь в кладовую за товаром, развешивал и отпускал продовольствие спокойный неторопливый кладовщик, по мере выдачи вычеркивая широким взмахом карандаша выданное из списка.<br/> Получающих было немного.<br/> — Вашу тару, — сказал кладовщик профессору и доктору, беглым взглядом окинув их накладные. У обоих глаза вылезли на лоб, когда в подставленные чехлы от дамских подушечек, называемых думками, и более крупные наволочки им стали сыпать муку, крупу, макароны и сахар, насовали сала, мыла и спичек и положили каждому еще по куску чего-то завернутого в бумагу, что потом, дома, оказалось кавказским сыром.<br/> Зять и тесть торопились увязать множество своих мелких узелков в два больших заплечных мешка как можно скорее, чтобы своей неблагодарной возней не мозолить глаза кладовщику, который подавил их своим великодушием.<br/> Они поднялись из подвала на воздух пьяные не от животной радости, а от сознания того, что и они не зря живут на свете и, не коптя даром неба, заслужат дома, у молодой хозяйки Тони, похвалу и признание.

### 4 {-}

Тем временем как мужчины пропадали по учреждениям, выхлопатывая командировки и закрепительные бумаги на оставляемые комнаты, Антонина Александровна занималась отбором вещей для упаковки.<br/> Она озабоченно похаживала по трем комнатам, числившимся теперь в доме за семьей Громеко, и без конца взвешивала на руке каждую мелочь, перед тем как отложить её в общую кучу вещей, подлежавших укладке.<br/> Только незначительная часть добра шла в личный багаж едущих, остальное предназначалось в запас меновых средств, нужных в дороге и по прибытии на место.<br/> В растворенную форточку тянуло весенним воздухом, отзывавшимся свеженадкушенной французской булкой. На дворе пели петухи и раздавались голоса играющих детей. Чем больше проветривали комнату, тем яснее становился в ней запах нафталина, которым пахла вынутая из сундуков зимняя рухлядь.<br/> Насчет того, что следует брать с собой и от чего воздерживаться существовала целая теория, разработанная ранее уехавшими, наблюдения которых распространялись в кругу их оставшихся знакомых.<br/> Эти наставления, отлившиеся в краткие, непререкаемые указания, с такой отчетливостью стояли в голове у Антонины Александровны, что она воображала, будто слышит их со двора вместе с чириканьем воробьев и шумом играющей детворы, словно их подсказывал ей с улицы какой-то тайный голос.<br/> «Ткани, ткани, — гласили эти соображения, — лучше всего в отрезе, но по дороге досматривают, и это опасно. Благоразумнее в кусках, для вида сшитых на живуху. Вообще материи, мануфактуру, можно одежду, предпочтительно верхнюю, не очень ношенную. Поменьше хламу, никаких тяжестей. При частой надобности перетаскивать все на себе, забыть о корзинах и чемоданах. Немногое, сто раз просмотренное, увязывать в узлы, посильные женщине и ребенку. Целесообразны соль и табак, как показала практика, при значительном, однако, риске. Деньги в керенках. Самое трудное — документы». И так далее, и так далее.

