### 5 {-}

Накануне отъезда поднялась снежная буря. Ветер взметал вверх к поднебесью серые тучи вертящихся снежинок, которые белым вихрем возвращались на землю, улетали в глубину темной улицы и устилали её белой пеленою.<br/> Все в доме было уложено. Надзор за комнатами и остающимся в них имуществом поручили пожилой супружеской чете, московским родственникам Егоровны, с которыми Антонина Александровна познакомилась истекшею зимою, когда она через них пристраивала для сбыта старье, тряпки и ненужную мебель в обмен на дрова и картошку.<br/> На Маркела нельзя было положиться. В милиции, которую он избрал себе в качестве политического клуба, он не жаловался, что бывшие домовладельцы Громеко пьют его кровь, но задним числом упрекал их в том, что все прошедшие годы они держали его в темноте неведения, намеренно скрывая от него происхождение мира от обезьяны.<br/> Эту пару, родню Егоровны, бывшего торгового служащего и его жену, Антонина Александровна в последний раз водила по комнатам, показывала, какие ключи к каким замкам и куда что положено, отпирала и запирала вместе с ними дверцы шкапов, выдвигала и вдвигала ящики, всему их учила и все объясняла.<br/> Столы и стулья в комнатах были сдвинуты к стенам, дорожные узлы оттащены в сторону, со всех окон сняты занавески. Снежная буря беспрепятственнее, чем в обрамлении зимнего уюта, заглядывала в опустелые комнаты сквозь оголенные окна. Каждому она что-нибудь напоминала. Юрию Андреевичу — детство и смерть матери, Антонине Александровне и Александру Александровичу — кончину и похороны Анны Ивановны. Всё им казалось, что это их последняя ночь в доме, которого они больше не увидят. В этом отношении они ошибались, но под влиянием заблуждения, которого они не поверяли друг другу, чтобы друг друга не огорчать, каждый про себя пересматривал жизнь, протекшую под этим кровом, и боролся с навертывавшимися на глаза слезами.<br/> Это не мешало Антонине Александровне соблюдать перед посторонними светские приличия. Она поддерживала несмолкаемую беседу с женщиной, надзору которой всё поручала. Антонина Александровна преувеличивала значение оказываемой ей услуги.<br/> Чтобы не платить за одолжение черной неблагодарностью, она каждую минуту с извинениями отлучалась в соседнюю комнату, откуда тащила этой особе в подарок то какой-нибудь платок, то блузку, то кусок ситцу или полушифона. И все материи были темные в белую клетку или горошком, как в белую крапинку была темная снежная улица, смотревшая в этот прощальный вечер в незанавешенные голые окна.

### 6 {-}

На вокзал уходили рано на рассвете. Население дома в этот час еще не подымалось. Жилица Зевороткина, обычная застрельщица всяких дружных действий миром и навалом, обежала спящих квартирантов, стуча в двери и крича:<br/> — Внимание, товарищи! Прощаться! Веселее, веселее! Бывшие Гарумековы уходят.<br/> Прощаться высыпали в сени и на крыльцо черной лестницы (парадное стояло теперь круглый год заколоченным) и облепили его ступеньки амфитеатром, словно собираясь сниматься группой.<br/> Зевающие жильцы нагибались, чтобы накинутые на плечи тощие пальтишки, под которыми они ежились, не сползли с них, и зябко перебирали голыми ногами, наспех сунутыми в широченные валенки.<br/> Маркел умудрился нахлестаться чего-то смертоубийственного в это безалкогольное время, валился как подкошенный на перила и грозил их обрушить. Он вызывался нести вещи на вокзал и обижался, что отвергают его помощь. Насилу от него отвязались.<br/> На дворе еще было темно. Снег в безветренном воздухе валил гуще, чем накануне. Крупные мохнатые хлопья падали, ленясь, и невдалеке от земли как бы еще задерживались, словно колеблясь, ложиться ли им на землю, или нет.<br/> Когда из переулка вышли на Арбат, немного посветлело.<br/> Снегопад завешивал улицу до полу своим белым сползающим пологом, бахромчатые концы которого болтались и путались в ногах у пешеходов. так что пропадало ощущение движения и им казалось, что они топчутся на месте.<br/> На улице не было ни души. Путникам из Сивцева никто не подался навстречу. Скоро их обогнал, весь в снегу, точно вывалянный в жидком тесте, извозчик порожняком на убеленной снегом кляче, и за баснословную, копейки не стоившую сумму тех лет, усадил всех с вещами в пролетку, кроме Юрия Андреевича, которого по его просьбе отпустили налегке, без вещей, на вокзал пешком.

