### 7 {-}

На вокзале Антонина Александровна с отцом уже занимали место в несметной очереди, стиснутой барьерами деревянного ограждения. Посадку производили теперь не с перронов, а с добрых полверсты от них вглубь путей у выходного семафора, потому что на расчистку подходов к дебаркадеру не хватало рук, половина вокзальной территории была покрыта льдом и нечистотами, и паровозы не доезжали до этой границы.<br/> Нюши и Шурочки не было в толпе с матерью и дедом. Они прогуливались на воле под огромным навесом наружного входа, лишь изредка наведываясь из вестибюля, не пора ли им присоединиться к старшим. От них сильно пахло керосином, которым, в предохранение от тифозных вшей, были густо смазаны у них щиколотки, запястья и шеи.<br/> Завидев подоспевшего мужа, Антонина Александровна поманила его рукою, но не дав ему приблизиться, прокричала ему издали, в какой кассе компостируют командировочные мандаты. Он туда направился.<br/> — Покажи, какие печати тебе поставили, — спросила она его по возвращении. Доктор протянул пучок сложенных бумажек за загородку.<br/> — Это литер в делегатский, — сказал сосед Антонины Александровны сзади, разобрав через её плечо штамп, поставленный на удостоверении. Ее сосед спереди, из формалистов-законников, знающих при любых обстоятельствах все правила на свете, пояснил подробнее:<br/> — С этой печатью вы вправе требовать места в классном, другими словами в пассажирском вагоне, если таковые окажутся в составе.<br/> Случай подвергся обсуждению всей очереди. Раздались голоса:<br/> — Поди вперед найди их, классные. Больно жирно будет. Теперь сел на товарный буфер, скажи спасибо.<br/> — Вы их не слушайте, командировочный. Вы послушайте, что я вам объясню. Как в настоящее время отдельные поезда аннулированные, а имеется один сборный, он тебе и воинский, он и арестантский, он и для скотины, он и людской. Говорить что угодно можно, язык — место мягкое, а чем человека с толку сбивать, надо объяснить, чтоб было ему понятно.<br/> — Ты-то объяснил. Какой умник нашелся. Это полдела, что у них литер в делегатский. Ты вперед на них погляди, а тогда толкуй. Нешто можно с такой бросающею личностью в делегатский?<br/> В делегатском полно братишков. У моряка наметанный глаз, и притом наган на шнуре. Он сразу видит — имущий класс и тем более — доктор, из бывших господ. Матрос хвать наган, и хлоп его как муху.<br/> Неизвестно куда завело бы сочувствие к доктору и его семье, если бы не новое обстоятельство.<br/> Из толпы давно бросали взгляды вдаль за широкие вокзальные окна из толстого зеркального стекла. Длинные, тянущиеся вдаль, навесы дебаркадера до последней степени удаляли зрелище падающего над путями снега. В таком отдалении казалось, что снежинки, почти не двигаясь, стоят в воздухе, медленно оседая в нем, как тонут в воде размокшие крошки хлеба, которым кормят рыбу.<br/> В эту глубину давно кучками и поодиночке направлялись какие-то люди. Пока они проходили в небольшом количестве, эти фигуры, неотчетливые за дрожащею сеткою снега, принимали за железнодорожников, по своей обязанности расхаживающих по шпалам. Но вот они повалили кучею. В глубине, куда они направлялись, задымил паровоз.<br/> — Отпирай двери, мошенники! — заорали в очереди. Толпа всколыхнулась и подалась к дверям. Задние стали напирать на передних.<br/> — Гляди, что делается! Тут стеной загородили, а там лезут без очереди в обход! Набьют вагоны доверху, а мы стой тут, как бараны! Отпирай, дьяволы, — выломаем! Эй, ребята, навались, нажми!<br/> — Кому, дурачье, завидуют, — говорил всезнающий законник.<br/> — Мобилизованные это, привлеченные к трудовой повинности из Петрограда. Их было в Вологду на Северный направили, а теперь гонят на Восточный фронт. Не своей волей. Под конвоем. На рытье окопов.

