### 8 {-}

В пути были уже три дня, но недалеко отъехали от Москвы.<br/> Дорожная картина была зимняя: рельсы путей, поля, леса, крыши деревень — всё под снегом.<br/> Семье Живаго посчастливилось попасть в левый угол верхних передних нар, к тусклому продолговатому окошку под самым потолком, где они и разместились своим домашним кругом, не дробя компании.<br/> Антонина Александровна в первый раз путешествовала в товарном вагоне. При погрузке в Москве Юрий Андреевич на руках поднял женщин на высоту вагонного пола, по краю которого ходила тяжелая выдвижная дверца. Дальше в пути женщины приноровились и взбирались в теплушку сами.<br/> Вагоны на первых порах показались Антонине Александровне хлевами на колесах. Эти клетушки должны были, по её мнению, развалиться при первом толчке или сотрясении. Но вот уже третий день их бросало вперед и назад и валило на бок при перемене движения и на поворотах, и третий день под полом часто-часто перестукивались колесные оси, как палочки заводного игрушечного барабанчика, а поездка протекала благополучно, и опасения Антонины Александровны не оправдывались.<br/> Вдоль станций с короткими платформами длинный эшелон, состоявший из двадцати трех вагонов (Живаго сидели в четырнадцатом), вытягивался только одной какой-нибудь частью, головой, хвостом или середкой.<br/> Передние вагоны были воинские, в средних ехала вольная публика, в задних — мобилизованные на трудовую повинность.<br/> Пассажиров этого разряда было человек до пятисот, люди всех возрастов и самых разнообразных званий и занятий.<br/> Восемь вагонов, занятых этой публикой, представляли пестрое зрелище. Рядом с хорошо одетыми богачами, петербургскими биржевиками и адвокатами можно было видеть отнесенных к эксплуататорскому классу лихачей-извозчиков, полотеров, банщиков, татар-старьевщиков, беглых сумасшедших из распущенных желтых домов, мелочных торговцев и монахов.<br/> Первые сидели вокруг докрасна раскаленных печурок без пиджаков на коротко спиленных чурках, поставленных стоймя, наперерыв друг другу что-то рассказывали и громко хохотали.<br/> Это были люди со связями. Они не унывали. За них дома хлопотали влиятельные родственники. В крайнем случае дальше в пути они могли откупиться.<br/> Вторые, в сапогах и расстегнутых кафтанах или в длинных распоясанных рубахах поверх портов и босиком, бородатые и без бород, стояли у раздвинутых дверей душных теплушек, держась за косяки и наложенные поперек пролетов перекладины, угрюмо смотрели на придорожные места и их жителей и ни с кем не разговаривали. У этих не было нужных знакомств. Им не на что было надеяться.<br/> Не все эти люди помещались в отведенных им вагонах. Часть рассовали в середине состава вперемешку с вольной публикой.<br/> Люди этого рода имелись и в четырнадцатой теплушке.

