### 9 {-}

Обыкновенно, когда поезд приближался к какой-нибудь станции, лежавшая наверху Антонина Александровна приподымалась в неудобной позе, к которой принуждал низкий, не позволявший разогнуться потолок, свешивала голову с полатей и через щелку приотодвинутой двери определяла, представляет ли место интерес с точки зрения товарообмена и стоит ли спускаться с нар и выходить наружу.<br/> Так было и сейчас. Замедлившийся ход поезда вывел её из дремоты. Многочисленность переводных стрелок, на которых подскакивала теплушка с учащающимся стуком, говорила о значительности станции и продолжительности предстоящей остановки.<br/> Антонина Александровна села согнувшись, протерла глаза, поправила волосы и, запустив руку в глубину вещевого мешка, вытащила, до дна перерыв его, вышитое петухами, парубками, дугами и колесами полотенце.<br/> Тем временем проснулся доктор, первым соскочил вниз с полатей и помог жене спуститься на пол.<br/> Между тем мимо растворенной вагонной дверцы вслед за будками и фонарями уже плыли станционные деревья, отягченные целыми пластами снега, который они как хлеб-соль протягивали на выпрямленных ветвях навстречу поезду, и с поезда первыми на скором еще ходу соскакивали на нетронутый снег перрона матросы, и бегом, опережая всех, бежали за угол станционного строения, где обыкновенно, под защитой боковой стены, прятались торговки запрещенным съестным.<br/> Черная форма моряков, развевающиеся ленты их бескозырок и их раструбом книзу расширяющиеся брюки придавали их шагу натиск и стремительность, и заставляли расступаться перед ними, как перед разбежавшимися лыжниками или несущимися во весь дух конькобежцами.<br/> За углом станции, прячась друг за друга и волнуясь, как на гадании, выстраивались гуськом крестьянки ближних деревень с огурцами, творогом, вареной говядиной и ржаными ватрушками, хранившими на холоде дух и тепло под стегаными покрышками, под которыми их выносили. Бабы и девки в заправленных под полушубки платках вспыхивали, как маков цвет, от иных матросских шуток, и в то же время боялись их пуще огня, потому что из моряков, преимущественно, формировались всякого рода отряды по борьбе со спекуляцией и запрещенною свободною торговлей.<br/> Смущение крестьянок продолжалось недолго. Поезд останавливался. Прибывали остальные пассажиры. Публика перемешивалась. Закипала торговля.<br/> Антонина Александровна производила обход торговок, перекинув через плечо полотенце с таким видом, точно шла на станционные задворки умыться снегом. Ее уже несколько раз окликнули из рядов:<br/> — Эй, эй, городская, что просишь за ширинку?<br/> Но Антонина Александровна, не останавливаясь, шла с мужем дальше.<br/> В конце ряда стояла женщина в черном платке с пунцовыми разводами. Она заметила полотенце с вышивкой. Ее дерзкие глаза разгорелись. Она поглядела по бокам, удостоверилась, что опасность не грозит ниоткуда, быстро подошла вплотную к Антонине Александровне и, откинув попонку со своего товара, прошептала горячей скороговоркой:<br/> — Эвона что. Небось такого не видала? Не соблазнишься? Ну, долго не думай — отымут.<br/> Отдай полотенце за полоток.<br/> Антонина Александровна не разобрала последнего слова. Ей подумалось, что речь о каком-то платке. Она переспросила:<br/> — Ты что, голубушка?<br/> Полотком крестьянка назвала пол-зайца, разрубленного пополам и целиком зажаренного от головы до хвоста, которого она держала в руках. Она повторила:<br/> — Отдай, говорю, полотенце за полоток. Ты что глядишь?<br/> Чай, не собачина. Муж у меня охотник. Заяц это, заяц.<br/> Мена состоялась. Каждой стороне казалось, что она в великом барыше, а противная в таком же большом накладе. Антонине Александровне было стыдно так нечестно объегоривать бедную крестьянку. Та же, довольная сделкой, поспешила скорее прочь от греха и, кликнув расторговавшуюся соседку, зашагала вместе с нею домой по протоптанной в снегу, вдаль уводившей стежке.<br/> В это время в толпе произошел переполох. Где-то закричала старуха:<br/> — Куда, кавалер? А деньги? Когда ты мне дал их, бессовестный? Ах ты, кишка ненасытная, ему кричат, а он идет, не оглядывается. Стой, говорю, стой, господин товарищ! Караул!<br/> Разбой! Ограбили! Вон он, вон он, держи его!<br/> — Это какой же?<br/> — Вон, голомордый, идет, смеется.<br/> — Это который драный локоть?<br/> — Ну да, ну да. Держи его, басурмана!<br/> — Это который на рукаве заплатка?<br/> — Ну да, ну да. Ай, батюшки, ограбили!<br/> — Что тут попритчилось?<br/> — Торговал у бабки пироги да молоко, набил брюхо и фьють.<br/> Вот, плачет, убивается.<br/> — Нельзя этого так оставить. Поймать надо.<br/> — Поди поймай. Весь в ремнях и патронах. Он тебе поймает.

