### 10 {-}

В четырнадцатой теплушке следовало несколько набранных в трудармию. Их стерег конвойный Воронюк. Из них по разным причинам выделялись трое. Это были: бывший кассир петроградской казенной винной лавки Прохор Харитонович Притульев, кАстер, как его звали в теплушке; шестнадцатилетний Вася Брыкин, мальчик из скобяной лавки, и седой революционер-кооператор Костоед-Амурский, перебывавший на всех каторгах старого времени и открывший новый ряд их в новое время.<br/> Все эти завербованные были люди друг другу чужие, нахватанные с бору да с сосенки и постепенно знакомившиеся друг с другом только в дороге. Из таких вагонных разговоров выяснилось, что кассир Притульев и торговый ученик Вася Брыкин — земляки, оба — вятские и, кроме того, уроженцы мест, которые поезд должен был миновать по прошествии некоторого времени.<br/> Мещанин города Малмыжа Притульев был приземистый, стриженный бобриком, рябой, безобразный мужчина. Серый, до черноты пропотевший под мышками китель плотно облегал его, как охватывает мясистый бюст женщины надставка сарафана. Он был молчалив, как истукан, и, часами о чем-то задумываясь, расковыривал до крови бородавки на своих веснущатых руках, так что они начинали гноиться.<br/> Год тому назад он как-то шел осенью по Невскому и на углу Литейного угодил в уличную облаву. У него спросили документы.<br/> Он оказался держателем продовольственной карточки четвертой категории, установленной для нетрудового элемента и по которой никогда ничего не выдавали. Его задержали по этому признаку и вместе со многими, остановленными на улице на том же основании, отправили под стражею в казармы. Собранную таким образом партию, по примеру ранее составленной, рывшей окопы на Архангельском фронте, вначале предполагали двинуть в Вологду, но с дороги вернули, и через Москву направили на Восточный фронт.<br/> У Притульева была жена в Луге, где он работал в предвоенные годы, до своей службы в Петербурге. Стороной узнав о его несчастии, жена кинулась разыскивать его в Вологду, чтобы вызволить из труд-армии. Но пути отряда разошлись с её розысками. Ее труды пропали даром. Всё перепуталось.<br/> В Петербурге Притульев проживал с сожительницей Пелагеей Ниловной Тягуновой. Его остановили на перекрестке Невского как раз в ту минуту, когда он простился с нею на углу, собравшись идти по делу в другую сторону, и среди мелькавших по Литейному пешеходов видел еще вдалеке её спину, вскоре скрывшуюся.<br/> Эта Тягунова, полнотелая осанистая мещанка с красивыми руками и толстою косой, которую она с глубокими вздохами перебрасывала то через одно, то через другое плечо себе на грудь, сопровождала по доброй воле Притульева в эшелоне.<br/> Непонятно было, что хорошего находили в таком идоле, как Притульев, липнувшие к нему женщины. Кроме Тягуновой, в другой теплушке эшелона, несколькими вагонами ближе к паровозу, ехала неведомо как очутившаяся в поезде другая знакомая Притульева, белобрысая и худая девица Огрызкова, «ноздря» и «спрынцовка», как, наряду с другими оскорбительными кличками, бранно называла её Тягунова.<br/> Соперницы были на ножах и остерегались попадаться на глаза друг другу. Огрызкова никогда не показывалась в теплушке. Было загадкою, где ухитрялась она видеться с предметом своего обожания. Может быть, она довольствовалась его лицезрением издали на общих погрузках дров и угля силами всех едущих.

