### 11 {-}

История Васи была иная. Его отца убили на войне. Мать послала Васю из деревни в учение к дяде в Питер.<br/> Зимой дядю, владельца скобяной лавки в Апраксином дворе, вызвали для объяснений в Совет. Он ошибся дверью и вместо комнаты, указанной в повестке, попал в другую, соседнюю.<br/> Случайно это была приемная комиссия по трудовой повинности. В ней было очень людно. Когда народу, явившегося в этот отдел по вызову, набралось достаточно, пришли красноармейцы, окружили собравшихся и отвели их ночевать в Семеновские казармы, а утром препроводили на вокзал для погрузки в Вологодский поезд.<br/> Весть о задержании такого большого числа жителей распространилась в городе. На другой день множество домашних потянулось прощаться с родственниками на вокзал. В их числе пошли провожать дядю и Вася с теткой.<br/> На вокзале дядя стал просить часового выпустить его на минутку за решетку к жене. Часовым этим был ныне сопровождавший группу в четырнадцатой теплушке Воронюк. Без верного ручательства, что дядя вернется, Воронюк не соглашался отпустить его. В виде такого ручательства дядя с тетей предложили оставить под стражей племянника. Воронюк согласился. Васю ввели в ограду, дядю из нее вывели. Больше дядя с тетей не возвращались.<br/> Когда подлог обнаружился, не подозревавший обмана Вася заплакал. Он валялся в ногах у Воронюка и целовал ему руки, умоляя освободить его, но ничего не помогало. Конвойный был неумолим не по жестокости характера. Время было тревожное, порядки суровые. Конвойный жизнью отвечал за численность вверенных ему сопровождаемых, установленную перекличкой. Так Вася и попал в труд-армию.<br/> Кооператор Костоед-Амурский, пользовавшийся уважением всех тюремщиков при царском и нынешнем правительстве и всегда сходившийся с ними на короткую ногу, не раз обращал внимание начальника конвоя на нетерпимое положение с Васей. Тот признавал, что это действительно вопиющее недоразумение, но говорил, что формальные затруднения не позволяют касаться этой путаницы в дороге, и он надеется распутать её на месте.<br/> Вася был хорошенький мальчик с правильными чертами лица, как пишут царских рынд и Божьих ангелов. Он был на редкость чист и неиспорчен. Излюбленным развлечением его было, сев на пол в ногах у старших, охватив переплетенными руками колени и закинув голову, слушать, что они говорят или рассказывают.<br/> Тогда по игре его лицевых мускулов, которыми он сдерживал готовые хлынуть слезы или боролся с душившим его смехом, можно было восстановить содержание сказанного. Предмет беседы отражался на лице впечатлительного мальчика, как в зеркале.

