### 12 {-}

Кооператор Костоед сидел наверху в гостях у Живаго и со свистом обсасывал заячью лопатку, которой его угощали. Он боялся сквозняков и простуды. — «Как тянет! Откуда это?» — спрашивал он, и все пересаживался, ища защищенного места.<br/> Наконец он уселся так, чтоб на него не дуло, сказал: «Теперь хорошо», доглодал лопатку, облизал пальцы, обтер их носовым платком и, поблагодарив хозяев, заметил:<br/> — Это у вас из окна. Необходимо заделать. Однако вернемся к предмету спора. Вы не правы, доктор. Жареный заяц — вещь великолепная. Но выводить отсюда, что деревня благоденствует, это, простите, по меньшей мере смело, это скачок весьма рискованный.<br/> — Ах, оставьте, — возражал Юрий Андреевич. — Посмотрите на эти станции. Деревья не спилены. Заборы целы. А эти рынки!<br/> Эти бабы! Подумайте, какое удовлетворение! Где-то есть жизнь.<br/> Кто-то рад. Не все стонут. Этим всё оправдано.<br/> — Хорошо, кабы так. Но ведь это неверно. Откуда вы это взяли? Отъезжайте на сто верст в сторону от полотна. Всюду непрекращающиеся крестьянские восстания. Против кого, спросите вы? Против белых и против красных, смотря по тому, чья власть утвердилась. Вы скажете, ага, мужик враг всякого порядка, он сам не знает, чего хочет. Извините, погодите торжествовать. Он знает это лучше вас, но хочет он совсем не того, что мы с вами.<br/> Когда революция пробудила его, он решил, что сбывается его вековой сон о жизни особняком, об анархическом хуторском существовании трудами рук своих, без зависимости и обязательств кому бы то ни было. А он из тисков старой, свергнутой государственности попал под еще более тяжкий пресс нового революционного сверхгосударства. И вот деревня мечется и нигде не находит покоя. А вы говорите, крестьянство благоденствует. Ничего вы, батенька, не знаете и, сколько вижу, и знать не хотите.<br/> — А что ж, и правда не хочу. Совершенно верно. Ах, подите вы! Зачем мне всё знать и за всё распинаться? Время не считается со мной и навязывает мне что хочет. Позвольте и мне игнорировать факты. Вы говорите, мои слова не сходятся с действительностью. А есть ли сейчас в России действительность?<br/> По-моему, её так запугали, что она скрывается. Я хочу верить, что деревня выиграла и процветает. Если и это заблуждение, то что мне тогда делать? Чем мне жить, кого слушаться? А жить мне надо, я человек семейный.<br/> Юрий Андреевич махнул рукой и, предоставив Александру Александровичу доводить до конца спор с Костоедом, придвинулся к краю полатей и, свесив голову, стал смотреть, что делается внизу.<br/> Там шел общий разговор между Притульевым, Воронюком, Тягуновой и Васей. В виду приближения родных мест, Притульев припоминал способ сообщения с ними, до какой станции доезжают, где сходят и как движутся дальше, пешком или на лошадях, а Вася при упоминании знакомых сел и деревень вскакивал с горящими глазами и восхищенно повторял их названия, потому что их перечисление звучало для него волшебной сказкой.<br/> — На Сухом броде слезаете? — захлебываясь, переспрашивал он. — Ну как же! Наш разъезд! Наша станция! А потом, небось, берете на Буйское?<br/> — Потом — Буйским проселком.<br/> — Я и то говорю — Буйским. Село Буйское. Как не знать!<br/> Наш поворот. Оттеда пойдет к нам всё вправо, вправо. К Веретенникам. А к вам, дядя Харитоныч, видать, влево, прочь от реки? Реку Пелгу слыхали? Ну как же! Наша река. А к нам будет берегом, берегом. И на этой самой реке, на реке Пелге повыше, наши Веретенники, наша деревня! На самом яру! Берег кру-у-той!<br/> По-нашему — залавок. Станешь наверху, страшно вниз взглянуть, такая круть. Как бы не свалиться: ей-Богу правда. Камень ломают. Жернова. И в тех Веретенниках маменька моя. И две сестренки. Сестра Аленка. И Аришка сестра. Маменька моя, тетя Палаша, Пелагея Ниловна, вроде сказать как вы, молодая, белая.<br/> Дядя Воронюк! Дядя Воронюк! Христом Богом молю вас… Дядя Воронюк!<br/> — Ну шо? Шо ты задолбыв, як зозуля: «дядя Воронюк, дядя Воронюк»? Хиба я не знаю, шо я не тетя? Шо ты хочешь, шо тоби треба? Шоб я пустив тебе тикать? Шо ты, сказивсь? Ты дашь винта, а мни за то будет аминь, стенка?<br/> Пелагея Тягунова рассеянно глядела куда-то вдаль, в сторону, и молчала. Она гладила Васю по голове и, о чем-то думая, перебирала его русые волосы. Изредка она наклонениями головы, глазами и улыбками делала мальчику знаки, смысл которых был таков, чтобы он не глупил и вслух при всех не заговаривал с Воронюком о таких вещах. Дай, мол, срок, всё устроится само собой, будь покоен.

