### 13 {-}

Когда от Среднерусской полосы удалились на восток, посыпались неожиданности. Стали пересекать неспокойные местности, области хозяйничанья вооруженных банд, места недавно усмиренных восстаний.<br/> Участились остановки поезда среди поля, обход вагонов заградительными отрядами, досмотр багажа, проверка документов.<br/> Однажды поезд застрял где-то ночью. В вагоны не заглядывали, никого не подымали. Полюбопытствовав, не случилось ли несчастья, Юрий Андреевич спрыгнул вниз с теплушки.<br/> Была темная ночь. Поезд без видимой причины стоял на какой-то случайной версте обыкновенного, обсаженного ельником полевого перегона. Соскочившие ранее Юрия Андреевича соседи, топтавшиеся перед теплушкой, сообщили, что по их сведениям ничего не случилось, а, кажется, машинист сам остановил поезд под тем предлогом, что данная местность — угрожаемая, и пока исправность перегона не будет удостоверена на дрезине, отказывается вести состав дальше. Представители пассажиров, говорят, отправились его упрашивать и, в случае необходимости, подмазать. По слухам, в дело вмешались матросы. Эти уломают.<br/> Пока это объясняли Юрию Андреевичу, снежная гладь впереди полотна возле паровоза, словно дышащим отблеском костра, озарялась огненными вспышками из трубы и подтопочного зольника паровоза. Вдруг один из таких языков ярко осветил кусок снежного поля, паровоз и несколько пробежавших по краю паровозной рамы черных фигур.<br/> Впереди промелькнул, видимо, машинист. Добежав до конца мостков, он подпрыгнул вверх и, перелетев через буферный брус, скрылся из виду. Те же движения проделали гнавшиеся за ним матросы. Они тоже пробежали до конца решетки, прыгнули, мелькнули в воздухе и провалились как сквозь землю.<br/> Привлеченный виденным, Юрий Андреевич вместе с несколькими любопытными прошел вперед к паровозу.<br/> В свободной, открывшейся перед поездом части пути им представилось следующее зрелище. В стороне от полотна в цельном снегу торчал до половины провалившийся машинист. Как загонщики — зверя, его полукругом обступали так же, как он, по пояс застрявшие в снегу матросы.<br/> Машинист кричал:<br/> — Спасибо, буревестнички! Дожил! С наганом на своего брата, рабочего! Зачем я сказал, состав дальше не пойдет.<br/> Товарищи пассажиры, будьте свидетели, какая это сторона. Кто хочет шляется, отвинчивают гайки. Я, мать вашу пополам с бабушкой, об чем, мне что? Я, сифон вам под ребра, не об себе, об вас, чтоб вам чего не сделалось. И вот мне что за мое попечение. Ну что ж, стреляй меня, минная рота! Товарищи пассажиры, будьте свидетели, вот он — я, не хоронюсь.<br/> Из кучки на железнодорожной насыпи слышались разнообразные голоса. Одни восклицали оторопело:<br/> — Да что ты?.. Опомнись… Да нешто… Да кто им даст? Это они так… Для острастки…<br/> Другие громко подзадоривали:<br/> — Так их, гаврилка! Не сдавай, паровая тяга!<br/> Матрос, первым высвободившийся из снега и оказавшийся рыжим великаном с такой огромной головой, что лицо его казалось плоским, спокойно повернулся к толпе и тихим басом, с украинизмами, как Воронюк, сказал несколько слов, смешных своим совершенным спокойствием в необычайной ночной обстановке:<br/> — Звиняюсь, шо це за гормидор? Як бы вы не занедужили на витру, громадяне. Ать с холоду до вагонив!<br/> Когда начавшая разбредаться толпа постепенно разошлась по теплушкам, рыжий матрос приблизился к машинисту, который еще не совсем пришел в себя, и сказал:<br/> — Фатит катать истерику, товарищ механик. Вылазть з ямы.<br/> Даешь поихалы.

