### 14 {-}

На другой день на тихом ходу с поминутными замедлениями, опасаясь схода со слегка завеянных метелью и неразметенных рельс, поезд остановился на покинутом жизнью пустыре, в котором не сразу узнали остатки разрушенной пожаром станции.<br/> На её закоптелом фасаде можно было различить надпись «Нижний Кельмес».<br/> Не только железнодорожное здание хранило следы пожара.<br/> Позади за станцией виднелось опустелое и засыпанное снегом селение, видимо разделившее со станцией её печальную участь.<br/> Крайний дом в селении был обуглен, в соседнем несколько бревен было подшиблено с угла и повернуто торцами внутрь, всюду на улице валялись обломки саней, поваленных заборов, рваного железа, битой домашней утвари. Перепачканный гарью и копотью снег чернел насквозь выжженными плешинами и залит был обледенелыми помоями со вмерзшими головешками, следами огня и его тушения.<br/> Безлюдие в селении и на станции было неполное. Тут и там имелись отдельные живые души.<br/> — Всей слободой горели? — участливо спрашивал соскочивший на перрон начальник поезда, когда из-за развалин навстречу вышел начальник станции.<br/> — Здравствуйте. С благополучным прибытием. Гореть горели, да дело похуже пожара будет.<br/> — Не понимаю.<br/> — Лучше не вникать.<br/> — Неужели Стрельников?<br/> — Он самый.<br/> — В чем же вы провинились?<br/> — Да не мы. Дорога сбоку припеку. Соседи. Нам заодно досталось. Видите, селение в глубине? Вот виновники. Село Нижний Кельмес Усть-Немдинской волости. Всё из-за них.<br/> — А те что?<br/> — Да без малого все семь смертных грехов. Разогнали у себя комитет бедноты, это вам раз; воспротивились декрету о поставке лошадей в Красную армию, а заметьте, поголовно татары — лошадники, это два; и не подчинились приказу о мобилизации, это — три, как видите.<br/> — Так, так. Тогда всё понятно. И за это получили из артиллерии?<br/> — Вот именно.<br/> — С бронепоезда?<br/> — Разумеется.<br/> — Прискорбно. Достойно сожаления. Впрочем, это не нашего ума дело.<br/> — Притом дело минувшее. Новым мне нечем вас порадовать.<br/> Сутки-другие у нас простоите.<br/> — Бросьте шутки. У меня — не что-нибудь: маршевые пополнения на фронт. Я привык — чтоб без простоя.<br/> — Да какие тут шутки. Снежный занос, сами видите. Неделю буран свирепствовал по всему перегону. Замело. А разгребать некому. Половина села разбежалась. Ставлю остальных, не справляются.<br/> — Ах, чтоб вам пусто было! Пропал, пропал! Ну что теперь делать?<br/> — Как-нибудь расчистим, поедете.<br/> — Большие завалы?<br/> — Нельзя сказать, чтобы очень. Полосами. Буран косяком шел, под углом к полотну. Самый трудный участок в середине.<br/> Три километра выемки. Тут действительно промучаемся. Место основательно забито. А дальше ничего, тайга, — лес предохранил. Также до выемки, открытая полоса, не страшно.<br/> Ветром передувало.<br/> — Ах, чтоб вас чорт побрал. Что за наваждение! Я поезд поставлю на ноги, пусть помогают.<br/> — Я и сам так думал.<br/> — Только матросов не трогайте и красногвардейцев. Целый эшелон трудармии. Вместе с вольноедущими человек до семисот.<br/> — Более чем достаточно. Вот только лопаты привезут, и поставим. Нехватка лопат. В соседние деревни послали.<br/> Раздобудемся.<br/> — Вот беда, ей-Богу! Думаете, осилим?<br/> — А как же. Навалом, — говорится, — города берут.<br/> Железная дорога. Артерия. Помилуйте.

