### 15 {-}

Расчистка пути заняла трое суток. Все Живаго, до Нюши включительно, приняли в ней деятельное участие. Это было лучшее время их поездки.<br/> В местности было что-то замкнутое, недосказанное. От нее веяло пугачевщиной в преломлении Пушкина, азиатчиной Аксаковских описаний.<br/> Таинственность уголка довершали разрушения и скрытность немногих оставшихся жителей, которые были запуганы, избегали пассажиров с поезда и не сообщались друг с другом из боязни доносов.<br/> На работы водили по категориям, не все роды публики одновременно. Территорию работ оцепляли охраной.<br/> Линию расчищали со всех концов сразу, отдельными в разных местах расставленными бригадами. Между освобождаемыми участками до самого конца оставались горы нетронутого снега, отгораживавшие соседние группы друг от друга. Эти горы убрали только в последнюю минуту, по завершении расчистки на всем требующемся протяжении.<br/> Стояли ясные морозные дни. Их проводили на воздухе, возвращаясь в вагон только на ночевку. Работали короткими сменами, не причинявшими усталости, потому что лопат не хватало, а работающих было слишком много. Неутомительная работа доставляла одно удовольствие.<br/> Место, куда ходили копать Живаго, было открытое, живописное. Местность в этой точке сначала опускалась на восток от полотна, а потом шла волнообразным подъемом до самого горизонта.<br/> На горе стоял одинокий, отовсюду открытый дом. Его окружал сад, летом, вероятно, разраставшийся, а теперь не защищавший здания своей узорной, заиндевелой редизной.<br/> Снеговая пелена всё выравнивала и закругляла. Но судя по главным неровностям склона, которые она была бессильна скрыть своими увалами, весной наверное сверху в трубу виадука под железнодорожной насыпью сбегал по извилистому буераку ручей, плотно укрытый теперь глубоким снегом, как прячется под горою пухового одеяла с головой укрытый ребенок.<br/> Жил ли кто-нибудь в доме, или он стоял пустым и разрушался, взятый на учет волостным или уездным земельным комитетом? Где были его прежние обитатели и что с ними сталось? Скрылись ли они заграницу? Погибли ли от руки крестьян? Или, заслужив добрую память, пристроились в уезде образованными специалистами? Пощадил ли их Стрельников, если они оставались тут до последнего времени, или их вместе с кулаками затронула его расправа?<br/> Дом дразнил с горы любопытство и печально отмалчивался. Но вопросов тогда не задавали и никто на них не отвечал. А солнце зажигало снежную гладь таким белым блеском, что от белизны снега можно было ослепнуть. Какими правильными кусками взрезала лопата его поверхность! Какими сухими, алмазными искрами рассыпался он на срезах! Как напоминало эти дни далекого детства, когда в светлом галуном обшитом башлыке и тулупчике на крючках, туго вшитых в курчавую, черными колечками завивавшуюся овчину, маленький Юра кроил на дворе из такого же ослепительного снега пирамиды и кубы, сливочные торты, крепости и пещерные города! Ах как вкусно было тогда жить на свете, какое всё кругом было заглядение и объяденье!<br/> Но и эта трехдневная жизнь на воздухе производила впечатление сытости. И не без причины. Вечерами работающих оделяли горячим сеяным хлебом свежей выпечки, который неведомо откуда привозили неизвестно по какому наряду. Хлеб был с обливной, лопающейся по бокам вкусною горбушкой и толстой, великолепно пропеченной нижней коркой со впекшимися в неё маленькими угольками.

