### 16 {-}

Развалины станции полюбили, как можно привязаться к кратковременному пристанищу в экскурсии по снеговым горам.<br/> Запомнилось её расположение, внешний облик постройки, особенности некоторых повреждений.<br/> На станцию возвращались вечерами, когда садилось солнце.<br/> Как бы из верности прошлому, оно продолжало закатываться на прежнем месте, за старою березой, росшей у самого окна перед дежурной комнатой телеграфиста.<br/> Наружная стена в этом месте обрушилась внутрь и завалила комнату. Но обвал не задел заднего угла помещения, против уцелевшего окна. Там всё сохранилось: обои кофейного цвета, изразцовая печь с круглою отдушиной под медной крышкой на цепочке, и опись инвентаря в черной рамке на стене.<br/> Опустившись до земли, солнце точь-в-точь как до несчастия, дотягивалось до печных изразцов, зажигало коричневым жаром кофейные обои и вешало на стену, как женскую шаль, тень березовых ветвей.<br/> В другой части здания имелась заколоченная дверь в приемный покой с надписью такого содержания, сделанной, вероятно, в первые дни февральской революции или незадолго до нее:<br/> «Ввиду медикаментов и перевязочных средств просят господ больных временно не беспокоиться. По наблюдающейся причине дверь опечатываю, о чем до сведения довожу старший фельдшер Усть-Немды такой-то».<br/> Когда отгребли последний снег, буграми остававшийся между расчищенными пролетами, открылся весь насквозь и стал виден ровный, стрелою вдаль разлетевшийся рельсовый путь. По бокам его тянулись белые горы откинутого снега, окаймленные во всю длину двумя стенами черного бора.<br/> Насколько хватал глаз, в разных местах на рельсах стояли кучки людей с лопатами. Они в первый раз увидали друг друга в полном сборе и удивились своему множеству.

### 17 {-}

Стало известно, что поезд отойдет через несколько часов, несмотря на позднее время и близость ночи. Перед его отправлением Юрий Андреевич и Антонина Александровна пошли в последний раз полюбоваться красотой расчищенной линии. На полотне уже никого не было. Доктор с женой постояли, посмотрели вдаль, обменялись двумя-тремя замечаниями и повернули назад к своей теплушке.<br/> На обратном пути они услышали злые, надсаженные выкрики двух бранящихся женщин. Они в них тотчас узнали голоса Огрызковой и Тягуновой. Обе женщины шли в том же направлении, что и доктор с женою, от головы к хвосту поезда, но вдоль его противоположной стороны, обращенной к станции, между тем как Юрий Андреевич и Антонина Александровна шагали по задней, лесной стороне. Между обеими парами, закрывая их друг от друга, тянулась непрерывная стена вагонов. Женщины почти не попадали в близость к доктору и Антонине Александровне, а намного обгоняли их или сильно отставали.<br/> Обе они были в большом волнении. Им поминутно изменяли силы. Вероятно, на ходу у них проваливались в снег или подкашивались ноги, судя по голосам, которые вследствие неровности походки то подскакивали до крика, то спадали до шопота. Видимо, Тягунова гналась за Огрызковой и, настигая ее, может быть, пускала в ход кулаки. Она осыпала соперницу отборной руганью, которая в мелодических устах такой павы и барыни звучала во сто раз бесстыднее грубой и немузыкальной мужской брани.<br/> — Ах ты шлюха, ах ты задрёпа, — кричала Тягунова. — Шагу ступить некуда, тут как тут она, юбкой пол метет, глазолупничает! Мало тебе, суке, колпака моего, раззевалась на детскую душеньку, распустила хвост, малолетнего ей надо испортить.<br/> — А ты, знать, и Васеньке законная?<br/> — Я те покажу законную, хайло, зараза! Ты живой от меня не уйдешь, не доводи меня до греха!<br/> — Но, но размахалась! Убери руки-то, бешеная! Чего тебе от меня надо?<br/> — А надо чтобы сдохла ты, гнида-шеламура, кошка шелудивая, бесстыжие глаза!<br/> — Обо мне какой разговор. Я, конечно, сука и кошка, дело известное. Ты вот у нас титулованная. Из канавы рожденная, в подворотне венчанная, крысой забрюхатела, ежом разродилась…<br/> Караул, караул, люди добрые! Ай убьет меня до смерти лиходейка-пагуба. Ай спасите девушку, заступитесь за сироту…<br/> — Пойдем скорее. Не могу этого слышать, так противно, — стала торопить мужа Антонина Александровна. — Не кончится это добром.

