### 18 {-}

Вдруг все изменилось, места и погода. Равнина кончилась, дорога пошла между гор, — холмами и возвышенностями.<br/> Прекратился северный ветер, дувший все последнее время. С юга, как из печки, пахнуло теплом.<br/> Леса росли тут уступами по горным склонам. Когда железнодорожное полотно их пересекало, поезду сначала приходилось брать большой подъем, сменявшийся с середины отлогим спуском. Поезд кряхтя вползал в чащу и еле тащился по ней, точно это был старый лесник, который пешком вел за собой толпу пассажиров, осматривавшихся по сторонам и все замечавших.<br/> Но смотреть еще было не на что. В глубине леса был сон и покой, как зимой. Лишь изредка некоторые кусты и деревья с шорохом высвобождали нижние сучья из постепенно оседавшего снега, как из снятых ошейников или расстегнутых воротников.<br/> На Юрия Андреевича напала сонливость. Все эти дни он пролеживал у себя наверху, спал, просыпался, размышлял и прислушивался. Но слушать пока еще было нечего.

### 19 {-}

Пока отсыпался Юрий Андреевич, весна плавила и перетапливала всю ту уйму снега, которая выпала в Москве в день отъезда и продолжала падать всю дорогу; весь тот снег, который они трое суток рыли и раскапывали в Усть-Немде, и который необозримыми и толстыми пластами лежал на тысячеверстных пространствах.<br/> Первое время снег подтаивал изнутри, тихомолком и вскрытную. Когда же половина богатырских трудов была сделана, их стало невозможно долее скрывать. Чудо вышло наружу. Из-под сдвинувшейся снеговой пелены выбежала вода и заголосила.<br/> Непроходимые лесные трущобы встрепенулись. Все в них пробудилось.<br/> Воде было где разгуляться. Она летела вниз с отвесов, прудила пруды, разливалась вширь. Скоро чаща наполнилась её гулом, дымом и чадом. По лесу змеями расползались потоки, увязали и грузли в снегу, теснившем их движение, с шипением текли по ровным местам и, обрываясь вниз, рассыпались водяною пылью. Земля влаги уже больше не принимала. Ее с головокружительных высот, почти с облаков пили своими корнями вековые ели, у подошв которых сбивалась в клубы обсыхающая белобурая пена, как пивная пена на губах у пьющих.<br/> Весна ударяла хмелем в голову неба, и оно мутилось от угара и покрывалось облаками. Над лесом плыли низкие войлочные тучи с отвисающими краями, через которые скачками низвергались теплые, землей и потом пахнувшие ливни, смывавшие с земли последние куски пробитой черной ледяной брони.<br/> Юрий Андреевич проснулся, подтянулся к квадратному оконному люку, из которого вынули раму, подперся локтем и стал слушать.<br/> С приближением к горнозаводскому краю местность стала населеннее, перегоны короче, станции чаще. Едущие сменялись не так редко. Больше народу садилось и выходило на небольших промежуточных остановках. Люди, совершавшие переезды на более короткие расстояния, не обосновывались надолго и не заваливались спать, а примащивались ночью где-нибудь у дверей в середине теплушки, толковали между собой вполголоса о местных, только им понятных делах и высаживались на следующем разъезде или полустанке.<br/> Из обмолвок здешней публики, чередовавшейся в теплушке последние три дня, Юрий Андреевич вывел заключение, что на севере белые берут перевес и захватили или собираются взять Юрятин. Кроме того, если его не обманывал слух и это не был какой-нибудь однофамилец его товарища по Мелюзеевскому госпиталю, силами белых в этом направлении командовал хорошо известный Юрию Андреевичу Галиуллин.<br/> Юрий Андреевич ни слова не сказал своим об этих толках, чтобы не беспокоить их понапрасну, пока слухи не подтвердятся.

