### 21 {-}

Юрий Андреевич проснулся в начале ночи от смутно переполнявшего его чувства счастья, которое было так сильно, что разбудило его. Поезд стоял на какой-то ночной остановке.<br/> Станцию обступал стеклянный сумрак белой ночи. Эту светлую тьму пропитывало что-то тонкое и могущественное. Оно было свидетельством шири и открытости места. Оно подсказывало, что разъезд расположен на высоте с широким и свободным кругозором.<br/> По платформе, негромко разговаривая, проходили мимо теплушки неслышно ступающие тени. Это тоже умилило Юрия Андреевича. Он усмотрел в осторожности шагов и голосов уважение к ночному часу и заботу о спящих в поезде, как это могло быть в старину, до войны.<br/> Доктор ошибался. На платформе галдели и громыхали сапогами, как везде. Но в окрестности был водопад. Он раздвигал границы белой ночи веяньем свежести и воли. Он внушил доктору чувство счастья во сне. Постоянный, никогда не прекращающийся шум его водяного обвала царил над всеми звуками на разъезде и придавал им обманчивую видимость тишины.<br/> Не разгадав его присутствия, но усыпленный неведомой упругостью здешнего воздуха, доктор снова крепко заснул.<br/> Внизу в теплушке разговаривали двое. Один спрашивал другого:<br/> — Ну как, угомонили своих? Доломали хвосты им?<br/> — Это лавочников, что ли?<br/> — Ну да, лабазников.<br/> — Утихомирили. Как шелковые. Из которых для примеру вышибли дух, ну остальные и присмирели. Забрали контрибуцию.<br/> — Много сняли с волости?<br/> — Сорок тысяч.<br/> — Врешь!<br/> — Зачем мне врать?<br/> — Ядрена репа, сорок тысяч!<br/> — Сорок тысяч пудов.<br/> — Ну, бей вас кобыла задом, молодцы! Молодцы!<br/> — Сорок тысяч мелкого помола.<br/> — А положим какое диво. Места — первый сорт. Самая мучная торговля. Тут по Рыньве пойдет теперь вверх к Юрятину, село к селу, пристанЯ, ссыпные пункты. Братья Шерстобитовы, Перекатчиков с сыновьями, оптовик на оптовике!<br/> — Тише ори. Народ разбудишь.<br/> — Ладно.<br/> Говоривший зевнул. Другой предложил:<br/> — Залечь подремать, что ли? Похоже, поедем.<br/> В это время сзади, стремительно разрастаясь, накатил оглушительный шум, перекрывший грохот водопада, и по второму пути разъезда мимо стоящего без движения эшелона промчался на всех парах и обогнал его курьерский старого образца, отгудел, отгрохотал и, мигнув в последний раз огоньками, бесследно скрылся впереди.<br/> Разговор внизу возобновился.<br/> — Ну, теперь шабаш. Настоимся.<br/> — Теперь не скоро.<br/> — Надо быть, Стрельников. Броневой особого назначения.<br/> — Стало быть, он.<br/> — Насчет контры это зверь.<br/> — Это он на Галеева побежал.<br/> — Это на какого же?<br/> — Атаман Галеев. Сказывают, стоит с чехом заслоном у Юрятина. Забрал, ядрена репа, под себя пристанЯ и держит.<br/> Атаман Галеев.<br/> — А може князь Галилеев. Запамятовал.<br/> — Не бывает таких князьев. Видно, Али Курбан. Перепутал ты. — Може и Курбан.<br/> — Это другое дело.

