### 22 {-}

Ближе к утру Юрий Андреевич проснулся в другой раз. Опять ему снилось что-то приятное. Чувство блаженства и освобождения, преисполнившее его, не прекращалось. Опять поезд стоял, может статься на новом полустанке, а может быть и на старом. Опять шумел водопад, скорее всего тот самый, а возможно и другой.<br/> Юрий Андреевич тут же стал засыпать, и сквозь дрему ему мерещились беготня и суматоха. Костоед сцепился с начальником конвоя, и оба кричали друг на друга. Наружи стало еще лучше, чем было. Веяло чем-то новым, чего не было прежде. Чем-то волшебным, чем-то весенним, черняво-белым, редким, неплотным, таким, как налет снежной бури в мае, когда мокрые, тающие хлопья, упав на землю, не убеляют ее, а делают еще чернее.<br/> Чем-то прозрачным, черняво-белым, пахучим. «Черемуха!» — угадал Юрий Андреевич во сне.

### 23 {-}

Утром Антонина Александровна говорила:<br/> — Удивительный ты, все-таки, Юра. Весь соткан из противоречий. Бывает, муха пролетит, ты проснешься и до утра глаз не сомкнешь, а тут шум, споры, переполох, а тебя не добудиться. Ночью бежали кассир Притульев и Вася Брыкин. Да, подумай! И Тягунова и Огрызкова. Погоди, это еще не всё. И Воронюк. Да, да, бежал, бежал. Да, представь себе. Теперь слушай. Как они скрылись, вместе или врозь, и в каком порядке — абсолютная загадка. Ну, допустим, Воронюк, этот, естественно, решил спастись от ответственности, обнаружив побег остальных. А остальные? Все ли именно исчезли по доброй воле, или кто-нибудь устранен насильственно? Например, подозрение падает на женщин. Но кто кого убил, Тягунова ли Огрызкову или Огрызкова Тягунову, никому неизвестно. Начальник конвоя бегает с одного конца поезда на другой. «Как вы смеете, — кричит, — давать свисток к отправлению. Именем закона требую задержать эшелон до поимки бежавших». А начальник эшелона не сдается. «Вы с ума, говорит, сошли, У меня маршевые пополнения на фронт, срочная первоочередность. Дожидаться вашей вшивой команды! Ишь что выдумали!» И оба, понимаешь, с упреками на Костоеда. Как это он, кооператор, человек с понятиями, был тут рядом и не удержал солдата, темное, несознательное существо, от рокового шага. «А еще народник», — говорят. Ну, Костоед, конечно, в долгу не остается.<br/> «Интересно! — говорит. — Значит, по-вашему, за конвойным арестант должен смотреть? Вот уж действительно когда курица петухом запела». Я тебя и в бок, и за плечо. «Юра, — кричу, — вставай, побег!» Какое! Из пушки не добудиться… Но прости, об этом потом. А пока… Не могу!.. Папа, Юра, смотрите, какая прелесть!<br/> Перед отверстием окна, у которого, вытянув головы, они лежали, раскинулась местность, без конца и краю затянутая разливом. Где-то вышла из берегов река, и вода её бокового рукава подступила близко к насыпи. В укорочении, получившемся при взгляде с высоты полатей, казалось, что плавно идущий поезд скользит прямо по воде.<br/> Ее гладь в очень немногих местах была подернута железистой синевой. По остальной поверхности жаркое утро гоняло зеркальные маслянистые блики, как мажет стряпуха перышком, смоченным в масле, корочку горячего пирога.<br/> В этой заводи, казавшейся безбрежной, вместе с лугами, ямами и кустами, были утоплены столбы белых облаков, сваями уходившие на дно.<br/> Где-то в середине этой заводи виднелась узкая полоска земли с двойными, вверх и вниз между небом и землей висевшими деревьями.<br/> — Утки! Выводок! — вскрикнул Александр Александрович, глядя в ту сторону.<br/> — Где?<br/> — У острова. Не туда смотришь. Правее, правее. Эх, чорт, полетели, спугнули.<br/> — Ах да, вижу. Мне надо будет кое о чем поговорить с вами, Александр Александрович. Как-нибудь в другой раз. — А наши трудармейцы и дамы, молодцы, что удрали. И, я думаю, — мирно, никому не сделавши зла. Просто бежали, как вода бежит.

