### 24 {-}

Кончалась северная белая ночь. Всё было видно, но стояло словно не веря себе, как сочиненное: гора, рощица и обрыв.<br/> Рощица едва зазеленела. В ней цвело несколько кустов черемухи. Роща росла под отвесом горы, на неширокой, так же обрывавшейся поодаль площадке.<br/> Невдалеке был водопад. Он был виден не отовсюду, а только по ту сторону рощицы, с края обрыва. Вася устал ходить туда глядеть на водопад, чтобы испытывать ужас и восхищение.<br/> Водопаду не было кругом ничего равного, ничего под пару. Он был страшен в этой единственности, превращавшей его в нечто одаренное жизнью и сознанием, в сказочного дракона или змея-полоза этих мест, собиравшего с них дань и опустошавшего окрестность.<br/> В полувысоте падения водопад обрушивался на выдавшийся зубец утеса и раздваивался. Верхний столб воды почти не двигался, а в двух нижних ни на минуту не прекращались еле уловимое движение из стороны в сторону, точно водопад всё время поскальзывался и выпрямлялся, поскальзывался и выпрямлялся, и сколько ни пошатывался, всё время оставался на ногах.<br/> Вася, подостлав кожух, лежал на опушке рощи. Когда рассвет стал заметнее, с горы слетела вниз большая, тяжелокрылая птица, плавным кругом облетела рощу и села на вершину пихты возле места, где лежал Вася. Он поднял голову, посмотрел на синее горло и серо-голубую грудь сизоворонки и зачарованно прошептал вслух: «Роньжа» — её уральское имя. Потом он встал, поднял с земли кожух, накинул его на себя и, перейдя полянку, подошел к своей спутнице. Он сказал:<br/> — Пойдемте, тетя. Ишь озябли, зуб на зуб не попадает. Ну что вы глядите, чисто пуганая? Говорю вам человеческим языком, надо итить. Войдите в положение, к деревням надо держать. В деревне своих не обидят, схоронют. Эдаким манером, два дня не евши, мы с голоду помрем. Небось дядя Воронюк какой содом поднял, кинулись искать. Уходить нам надо, тетя Палаша, просто скажем, драть. Беда мне с вами, тетя, хушь бы вы слово сказали за цельные сутки! Это вы с тоски без языка, ей-Богу. Ну об чем вы тужите? Тетю Катю, Катю Огрызкову, вы без зла толканули с вагона, задели бочком, я сам видал. Встала она потом с травы целехонька, встала и побежала. И тоже самое дядя Прохор, Прохор Харитоныч. Догонют они нас, все опять вместе будем, вы что думаете? Главная вещь, не надо себя кручинить, тогда и язык у вас в действие произойдет.<br/> Тягунова поднялась с земли и, подав руку Васе, тихо сказала:<br/> — Пойдем, касатик.

