### 25 {-}

Скрипя всем корпусом, вагоны шли в гору по высокой насыпи.<br/> Под ней рос молодой мешаный лес, вершинами не достигавший её уровня. Внизу были луга, с которых недавно сошла вода. Трава, перемешанная с песком, была покрыта шпальными бревнами, в беспорядке лежавшими в разных направлениях. Вероятно их заготовили для сплава на какой-нибудь ближней деляне, откуда их смыло и принесло сюда полою водой.<br/> Молодой лес под насыпью был почти еще гол, как зимой.<br/> Только в почках, которыми он был сплошь закапан, как воском, завелось что-то лишнее, какой-то непорядок, вроде грязи или припухлости, и этим лишним, этим непорядком и грязью была жизнь, зеленым пламенем листвы охватившая первые распустившиеся в лесу деревья.<br/> Там и сям мученически прямились березы, пронзенные зубчиками и стрелами парных раскрывшихся листиков. Чем они пахли, можно было определить на глаз. Они пахли тем же, чем блистали. Они пахли древесными спиртами, на которых варят лаки.<br/> Скоро дорога поровнялась с местом, откуда могли быть смытые бревна. На повороте в лесу показалась прогалина, засыпанная дровяной трухой и щепками, с кучей бревен тройника посредине.<br/> У лесосеки машинист затормозил. Поезд дрогнул и остановился в том положении, какое он принял, легко наклонившись на высокой дуге большого закругления.<br/> С паровоза дали несколько коротких лающих свистков и что-то прокричали. Пассажиры и без сигналов знали: машинист остановил поезд, чтобы запастись топливом.<br/> Дверцы теплушек раздвинулись. На полотно высыпало доброе население небольшого города, кроме мобилизованных из передних вагонов, которые всегда освобождались от авральной работы и сейчас не приняли в ней участия.<br/> Груды швырка на прогалине не могло хватить для загрузки тендера. В придачу требовалось распилить некоторое количество длинного тройника.<br/> В хозяйстве паровозной бригады имелись пилы. Их распределили между желающими, разбившимися на пары. Получили пилу и профессор с зятем.<br/> Из воинских теплушек в раздвинутые дверцы высовывались веселые рожи. Не бывавшие в огне подростки, старшие ученики мореходных классов, казалось, по ошибке затесавшиеся в вагон к суровым семейным рабочим, тоже не нюхавшим пороху и едва прошедшим военную подготовку, нарочно шумели и дурачились вместе с более взрослыми матросами, чтобы не задумываться. Все чувствовали, что час испытания близок.<br/> Шутники провожали пильщиков и пильщиц раскатистым зубоскальством:<br/> — Эй, дедушка! Скажи, — я грудной, меня мамка не отлучила, я к физическому труду неспособный. Эй, Мавра! Мотри пилой подола не отпили, продувать будет. — Эй, молодая! Не ходи в лес, лучше поди за меня замуж.

