### 26 {-}

В лесу торчало несколько козел, сделанных из связанных крест на крест кольев, концами вбитых в землю. Одни оказались свободными. Юрий Андреевич и Александр Александрович расположились пилить на них.<br/> Это была та пора весны, когда земля выходит из-под снега почти в том виде, в каком полгода тому назад она ушла под снег. Лес обдавал сыростью и весь был завален прошлогодним листом, как неубранная комната, в которой рвали на клочки квитанции, письма и повестки за много лет жизни, и не успели подмести.<br/> — Не так часто, устанете, — говорил доктор Александру Александровичу, направляя движение пилы реже и размереннее, и предложил отдохнуть.<br/> По лесу разносился хриплый звон других пил, ходивших взад и вперед то в лад у всех, то вразнобой. Где-то далеко-далеко пробовал силы первый соловей. С еще более долгими перерывами свистал, точно продувая засоренную флейту, черный дрозд. Даже пар из паровозного клапана подымался к небу с певучей воркотнею, словно это было молоко, закипающее в детской на спиртовке.<br/> — Ты о чем-то хотел побеседовать, — напомнил Александр Александрович. — Ты не забыл? Дело было так: мы разлив проезжали, утки летели, ты задумался и сказал: «Мне надо будет поговорить с вами».<br/> — Ах да. Не знаю, как бы это выразить покороче. Видите, мы всё больше углубляемся… Тут весь край в брожении. Мы скоро приедем. Неизвестно, что мы застанем у цели. На всякий случай надо бы сговориться. Я не об убеждениях. Было бы нелепостью выяснять или устанавливать их в пятиминутной беседе в весеннем лесу. Мы знаем друг друга хорошо. Мы втроем, вы, я и Тоня, вместе со многими в наше время составляем один мир, отличаясь друг от друга только степенью его постижения. Я не об этом.<br/> Это азбука. Я о другом. Нам надо уговориться заранее, как нам вести себя при некоторых обстоятельствах, чтобы не краснеть друг за друга и не накладывать друг на друга пятна позора.<br/> — Довольно. Я понял. Мне нравится твоя постановка вопроса.<br/> Ты нашел именно нужные слова. Вот что я скажу тебе. Помнишь ночь, когда ты принес листок с первыми декретами, зимой в метель. Помнишь, как это было неслыханно безоговорочно. Эта прямолинейность покоряла. Но такие вещи живут в первоначальной чистоте только в головах создателей и то только в первый день провозглашения. Иезуитство политики на другой же день выворачивает их наизнанку. Что мне сказать тебе? Эта философия чужда мне. Эта власть против нас. У меня не спрашивали согласия на эту ломку. Но мне поверили, а мои поступки, даже если я совершил их вынужденно, меня обязывают.<br/> Тоня спрашивает, не опоздаем ли мы к огородным срокам, не прозеваем ли времени посадки. Что ей ответить? Я не знаю здешней почвы. Каковы климатические условия? Слишком короткое лето. Вызревает ли тут вообще что-нибудь?<br/> Да, но разве мы едем в такую даль огородничать? Тут нельзя даже скаламбурить «за семь верст киселя хлебать», потому что верст этих, к сожалению, три или четыре тысячи. Нет, откровенно говоря, тащимся мы так далеко совсем с другой целью. Едем мы попробовать прозябать по современному, и как-нибудь примазаться к разбазариванию бывших дедушкиных лесов, машин и инвентаря. Не к восстановлению его собственности, а к её расточению, к обобществленному просаживанию тысяч, чтобы просуществовать на копейку, и непременно как все, в современной, не укладывающейся в сознании, хаотической форме. Озолоти меня, я на старых началах не приму завода даже в подарок. Это было бы так же дико, как начать бегать голышом, или перезабыть грамоту. Нет, история собственности в России кончилась. А лично мы, Громеко, расстались со страстью стяжательства уже в прошлом поколении.

