### 27 {-}

Спать не было возможности от духоты и спертого воздуха.<br/> Голова доктора плавала в поту на промокшей от пота подушке.<br/> Он осторожно спустился с края полатей и тихонько, чтобы никого не будить, приотодвинул вагонную дверь.<br/> В лицо ему пахнуло сыростью, липкой, как когда в погребе лицом попадешь в паутину. «Туман», — догадался он. — «Туман.<br/> День наверное будет знойный, палящий. Вот почему так трудно дышать и на душе такая давящая тяжесть».<br/> Перед тем как сойти на полотно, доктор постоял в дверях, вслушиваясь кругом.<br/> Поезд стоял на какой-то очень большой станции, разряда узловых. Кроме тишины и тумана, вагоны были погружены еще в какое-то небытие и заброшенность, точно о них забыли, — знак того, что состав стоял на самых задворках, и что между ним и далеким вокзальным зданием было большое расстояние, занятое бесконечною сетью путей.<br/> Два рода звуков слабо раздавались в отдалении.<br/> Сзади, откуда они приехали, слышалось мерное шлепанье, словно там полоскали белье, или ветер щелкал о древко флагштока мокрым полотнищем флага.<br/> Спереди доносился рокот, заставивший доктора, побывавшего на войне, вздрогнуть и напречь слух.<br/> «Дальнобойные орудия», — решил он, прислушавшись к ровному, спокойно прокатывающемуся гулу на низкой, сдержанной ноте.<br/> «Вот как. К самому фронту подъехали», — подумал доктор, покачал головой и спрыгнул с вагона вниз на землю.<br/> Он прошел несколько шагов вперед. За двумя следующими вагонами поезд обрывался. Состав стоял без паровоза, который куда-то ушел вместе с отцепленными передними вагонами.<br/> «То-то они вчера храбрились, — подумал доктор. — Чувствовали видно, что лишь довезут их, с места бросят в самый огонь».<br/> Он обошел конец поезда в намерении пересечь пути и разыскать дорогу на станцию. За углом вагона как из-под земли вырос часовой с ружьем. Он негромко отрезал:<br/> — Куда? Пропуск!<br/> — Какая это станция?<br/> — Станция никакая. Сам ты кто такой?<br/> — Я доктор из Москвы. Следую с семьей в этом эшелоне. Вот мой документ.<br/> — Лыковое кульё твой документ. Дурак я впотьмах бумажки читать, глаза портить. Видишь, туман. Тебя без документа за версту видно, какой ты есть доктор. Вон доктора твои из двенадцатидюймовых содют. По-настоящему стукнуть бы тебя, да рано. Марш назад, пока цел.<br/> «Меня за кого-то принимают», — подумал доктор. Вступать в пререкания с часовым было бессмысленно. Лучше, правда, было удалиться, пока не поздно. Доктор повернул в противоположную сторону.<br/> Орудийная стрельба смолкла за его спиной. В том направлении был восток. Там в дымке тумана взошло солнце и тускло проглядывало между обрывками проплывающей мглы, как мелькают голые в бане в облаках мыльного пара.<br/> Доктор шел вдоль вагонов поезда. Он миновал их все и продолжал идти дальше. Ноги его с каждым шагом уходили всё глубже в рыхлый песок.<br/> Звуки равномерного шлепанья приближались. Местность отлого спускалась. Через несколько шагов доктор остановился перед неясными очертаниями, которым туман придавал несоответственно большие размеры. Еще шаг, и навстречу Юрию Андреевичу вынырнули из мглы кормовые выступы вытащенных на берег лодок.<br/> Он стоял на берегу широкой реки, медленно и устало шлепавшей ленивой зыбью в борта рыбачьих баркасов и доски береговых причальных мостков.<br/> — Тебе кто тут позволил шляться? — спросил, отделившись от берега, другой часовой.<br/> — Какая это река? — против воли выпалил доктор, хотя всеми силами души не хотел ничего спрашивать после недавнего опыта.<br/> Вместо ответа часовой сунул в зубы свисток, но не успел им воспользоваться. Первый часовой, которого он хотел подозвать свистком и который, как оказалось, незаметно шел по пятам за Юрием Андреевичем, сам подошел к товарищу. Оба заговорили.<br/> — Тут и думать нечего. Видно птицу по полету. «Это какая станция, это какая река?» Чем вздумал глаза отводить.<br/> По-твоему как, прямо на мысок, или вперед в вагон?<br/> — Я полагаю, в вагон. Как начальник скажет. — Удостоверение личности, — рявкнул второй часовой и схватил в горсть пачку протянутых доктором свидетельств.<br/> — Постереги, земляк, — неизвестно кому сказал он и вместе с первым часовым пошел вглубь путей к станции.<br/> Тогда для уяснения положения крякнул и задвигался лежавший на песке человек, видимо, рыбак:<br/> — Твое счастье, что они тебя к самому хотят. Может, милый человек, тут твое спасение. А только ты их не вини. Такая у них должность. Время народное. Может, оно и к лучшему. А пока, и не говори. Они, видишь, обознались. Они лавят, лавят одного.<br/> Ну, думают, — ты. Думают, вот он, злодей рабочей власти, — поймали. Ошибка. Ты, в случае чего, добивайся главного. А этим не давайся. Эти — сознательные, беда, не приведи Бог.<br/> Порешить тебя это им полкопейки не стоит. Они скажут, — пойдем, а ты не ходи. Ты говори — мне чтобы главного.<br/> От рыбака Юрий Андреевич узнал, что река, перед которой он стоял, — знаменитая судоходная Рыньва, что железнодорожная станция близ реки — Развилье, речное фабричное предместье города Юрятина. Он узнал, что самый Юрятин, лежащий в двух или трех верстах выше, все время отбивали и, кажется, уже отбили от белых. Рыбак рассказал ему, что и в Развилье были беспорядки и тоже, кажется, подавлены и что кругом царит такая тишина, потому что прилегающая к станции полоса очищена от гражданского населения и окружена строжайшим кордоном. Он узнал, наконец, что среди поездов, стоящих на путях с размещенными в них военными учреждениями, находится особый поезд краевого военкома Стрельникова, в вагон которого понесли докторовы бумаги.<br/> Оттуда за доктором через некоторое время явился новый часовой, отличавшийся от предшественников тем, что волочил ружье прикладом по земле или переставлял его перед собой, точно тащил под руку выпившего приятеля, который без него свалился бы наземь. Он повел доктора в вагон к военкому.

