### 28 {-}

В одном из двух, соединенных между собою крытых кожаным переходом салон-вагонов, в который, сказав караулу пропуск, поднялся часовой с доктором, слышались смех и движение, мгновенно смолкшие при их появлении.<br/> Часовой по узкому коридору провел доктора в широкое среднее отделение. Тут были тишина и порядок. В чистом удобном помещении работали опрятные, хорошо одетые люди. Совсем другой представлял себе доктор штабквартиру беспартийного военспеца, ставшего в короткое время славой и грозой целой области.<br/> Но наверное центр его деятельности лежал не тут, а где-нибудь впереди, в штабе фронта, ближе к месту военных действий, здесь же находилась его личная часть, его небольшая домашняя канцелярия и его передвижная походная койка.<br/> Вот отчего тут было покойно, как в коридорах горячих морских купален, устланных пробкою и ковриками, по которым неслышно ступают служащие в мягких туфлях.<br/> Среднее отделение вагона представляло бывший обеденный зал, покрытый ковром и превращенный в экспедиторскую. В нем стояло несколько столов.<br/> «Сейчас», — сказал молодой военный, сидевший всего ближе ко входу. После этого все за столами сочли себя вправе забыть о докторе и перестали обращать на него внимание. Этот же военный рассеянным наклоном головы отпустил часового, и тот удалился, гремя ружейным прикладом по металлическим поперечинам коридора.<br/> Доктор с порога увидал свои бумаги. Они лежали на краю последнего стола перед более пожилым военным старой полковничьей складки. Это был какой-то военный статистик.<br/> Мурлыча что-то под нос, он заглядывал в справочники, рассматривал военные карты, что-то сличал, сближал, вырезывал и наклеивал. Он обвел взглядом все окна в помещении, одно за другим, и сказал: «Жарко будет сегодня», точно получил этот вывод из обзора всех окон, и это не было одинаково ясно из каждого.<br/> По полу между столами ползал военный техник, восстанавливая какую-то нарушенную проводку. Когда он подполз под стол молодого военного, тот встал, чтобы не мешать ему. Рядом билась над испорченной пишущей машинкой переписчица в мужской защитной куртке. Движущаяся каретка заскочила у нее слишком вбок и её защемило в раме. Молодой военный стал за её табуретом и исследовал вместе с нею причину поломки сверху. К машинистке переполз военный техник и рассматривал рычажки и передачу снизу. Встав со своего места, к ним перешел командир полковничьей складки. Все занялись машинкой.<br/> Это успокаивало доктора. Нельзя было предположить, чтобы люди, лучше его посвященные в его вероятную участь, так беспечно предавались пустякам в присутствии человека обреченного.<br/> «Впрочем, кто их знает?» — думал он. — «Откуда их безмятежность? Рядом ухают пушки, гибнут люди, а они составляют прогноз жаркого дня не в смысле жаркой схватки, а жаркой погоды. Или они столького насмотрелись, что все в них притупилось?»<br/> И от нечего делать он стал со своего места смотреть через все помещение в противоположные окна.

