### 29 {-}

Перед поездом с этой стороны тянулся остаток путей и виднелась станция Развилье на горе в одноименном предместье.<br/> С путей к станции вела некрашеная деревянная лестница с тремя площадками.<br/> Рельсовые пути с этой стороны представляли большое паровозное кладбище. Старые локомотивы без тендеров с трубами в форме чаш и сапожных голенищ стояли обращенные труба к трубе среди груд вагонного лома.<br/> Паровозное кладбище внизу и кладбище пригорода, мятое железо на путях и ржавые крыши и вывески окраины сливались в одно зрелище заброшенности и ветхости под белым небом, обваренным раннею утреннею жарою.<br/> В Москве Юрий Андреевич забыл, как много в городах попадалось вывесок, и какую большую часть фасада они закрывали. Здешние вывески ему об этом напомнили. Половину надписей по величине букв можно было прочесть с поезда. Они так низко налезали на кривые оконца покосившихся одноэтажных строений, что приземистые домишки под ними исчезали, как головы крестьянских ребятишек в низко надвинутых отцовских картузах.<br/> К этому времени туман совершенно рассеялся. Следы его оставались только в левой стороне неба, вдали на востоке. Но вот и они шевельнулись, двинулись и разошлись, как полы театрального занавеса.<br/> Там, верстах в трех от Развилья, на горе, более высокой, чем предместье, выступил большой город, окружной или губернский. Солнце придавало его краскам желтоватость, расстояние упрощало его линии. Он ярусами лепился на возвышенности, как гора Афон или скит пустынножителей на дешевой лубочной картинке, дом на доме и улица над улицей, с большим собором посередине на макушке.<br/> «Юрятин!» — взволнованно сообразил доктор. — «Предмет воспоминаний покойницы Анны Ивановны и частых упоминаний сестры Антиповой! Сколько раз я слышал от них название города и при каких обстоятельствах вижу его впервые!»<br/> В эту минуту внимание военных, склонившихся над машинкой, было привлечено чем-то за окном. Они повернули туда головы.<br/> Последовал за их взглядом и доктор.<br/> По лестнице на станцию вели несколько захваченных в плен или арестованных, среди них гимназиста, раненного в голову.<br/> Его где-то уже перевязали, но из-под повязки сочилась кровь, которую он раз мазывал ладонью по загорелому, потному лицу.<br/> Гимназист между двумя красноармейцами, замыкавший шествие, останавливал внимание не только решительностью, которою дышало его красивое лицо, и жалостью, которую вызывал такой молодой мятежник. Он и двое его сопровождающих притягивали взгляды бестолковостью своих действий. Они все время делали не то, что надо было делать.<br/> С обмотанной головы гимназиста поминутно сваливалась фуражка. Вместо того чтобы снять её и нести в руках, он то и дело поправлял её и напяливал ниже, во вред перевязанной ране, в чем ему с готовностью помогали оба красноармейца.<br/> В этой нелепости, противной здравому смыслу, было что-то символическое. И уступая её многозначительности, доктору тоже хотелось выбежать на площадку и остановить гимназиста готовым, рвавшимся наружу изречением. Ему хотелось крикнуть и мальчику, и людям в вагоне что спасение не в верности формам, а в освобождении от них.<br/> Доктор nepевел взгляд в сторону. Посреди помещения стоял Стрельников, только что сюда вошедший прямыми, стремительными шагами.<br/> Как мог он, доктор, среди такой бездны неопределенных знакомств, не знать до сих пор такой определенности, как этот человек? Как не столкнула их жизнь? Как их пути не скрестились?<br/> Неизвестно почему, сразу становилось ясно, что этот человек представляет законченное явление воли. Он до такой степени был тем, чем хотел быть, что и всё на нем и в нем неизбежно казалось образцовым. И его соразмерно построенная и красиво поставленная голова, и стремительность его шага, и его длинные ноги в высоких сапогах, может быть грязных, но казавшихся начищенными, и его гимнастерка серого сукна, может быть мятая, но производившая впечатление глаженой, полотняной.<br/> Так действовало присутствие одаренности, естественной, не знающей натянутости, чувствующей себя, как в седле, в любом положении земного существования.<br/> Этот человек должен был обладать каким-то даром, не обязательно самобытным. Дар, проглядывавший во всех его движениях, мог быть даром подражания. Тогда все кому-нибудь подражали. Прославленным героям истории. Фигурам, виденным на фронте или в дни волнений в городах, и поразившим воображение.<br/> Наиболее признанным народным авторитетам. Вышедшим в первые ряды товарищам. Просто друг другу.<br/> Он из вежливости не показал, что присутствие постороннего удивляет его или стесняет. Наоборот, он обратился ко всем с таким видом, точно он и доктора относил к их обществу. Он сказал:<br/> — Поздравляю. Мы их отогнали. Это кажется военною игрою, а не делом, потому что они такие же русские, как мы, только с дурью, с которой они сами не желают расстаться и которую нам придется выбивать силой. Их командующий был моим другом. Он еще более пролетарского происхождения, чем я. Мы росли на одном дворе. Он много в жизни для меня сделал, я ему обязан. А я рад, что отбросил его за реку, а может быть, и дальше.<br/> Скорей налаживайте связь, Гурьян. Нет возможности держаться на одних вестовых и телеграфе. Вы обратили внимание, какая жара?<br/> Часа полтора я все-таки поспал. Ах да… — спохватился он и повернулся к доктору. Ему вспомнилась причина его пробуждения.<br/> Его разбудили какой-то чепухой, в силу которой стоит тут этот задержанный.<br/> «Этот?» — подумал Стрельников, смерив доктора с головы до ног испытующим взгядом. — «Ничего похожего. Вот дураки!» — Он рассмеялся и обратился к Юрию Андреевичу.<br/> — Простите, товарищ. Вас приняли за другого. Мои часовые напутали. Вы свободны. Где трудовая книжка товарища? Ага, вот ваши документы. Извините за нескромность, мимоходом позволю себе заглянуть. Живаго… Живаго… Доктор Живаго… Что-то московское… Пройдемте, знаете, все же на минуту ко мне. Это — секретариат, а мой вагон рядом. Пожалуйте. Я вас долго не задержу.

