### 30 {-}

Кто же был, однако, этот человек? Удивительно, как на такие посты выдвинулся и мог на них удержаться беспартийный, которого никто не знал, потому что, будучи родом из Москвы, он по окончании университета уехал учительствовать в провинцию, а с войны попал надолго в плен, до недавнего времени отсутствовал и считался погибшим.<br/> Передовой железнодорожник Тиверзин, в семье которого Стрельников воспитывался мальчиком, рекомендовал его и за него поручился. Люди, от которых зависели назначения того времени, ему поверили. В дни неумеренного пафоса и самых крайних взглядов, революционность Стрельникова, тоже ни перед чем не останавливавшегося, выделялась своей подлинностью, фанатизмом, не напетым с чужого голоса, а подготовленным всею его жизнью и не случайным.<br/> Стрельников оправдал оказанное ему доверие.<br/> Его послужной список последнего периода содержал Усть-Немдинское и Нижне-Кельмесское дела, дело Губасовских крестьян, оказавших вооруженное сопротивление продовольственному отряду, и дело о разграблении маршрута с продовольствием четырнадцатым пехотным полком на станции Медвежья пойма. В его формуляр входило дело о солдатах-разинцах, поднявших восстание в городе Туркатуе и с оружием в руках перешедших на сторону белогвардейцев, и дело о военном мятеже на речной пристани Чиркин ус, с убийством командира, оставшегося верным советской власти.<br/> Во все эти места он сваливался, как снег на голову, судил, приговаривал, приводил приговоры в исполнение, быстро, сурово, бестрепетно.<br/> Разъездами его поезда был положен предел повальному дезертирству в крае. Ревизия рекрутирующих организаций все изменила. Набор в Красную армию пошел успешно. Приемочные комиссии заработали лихорадочно.<br/> Наконец, в последнее время, когда белые стали наседать с севера и положение было признано угрожающим, на Стрельникова возложили новые задачи, непосредственно военные, стратегические и оперативные. Результаты его вмешательства не замедлили сказаться.<br/> Стрельников знал, что молва дала ему прозвище Расстрельникова. Он спокойно перешагнул через это, он ничего не боялся.<br/> Он был родом из Москвы и был сыном рабочего, принимавшего в девятьсот пятом году участие в революции и за это пострадавшего. Сам он остался в эти годы в стороне от революционного движения по причине малолетства, а в последующие годы, когда он учился в университете, вследствие того, что молодые люди из бедной среды, попадая в высшую школу, дорожат ею больше и занимаются прилежнее, чем дети богатых. Брожение обеспеченного студенчества его не затронуло.<br/> Из университета он вышел с огромными познаниями. Свое историко-филологическое образование он собственными силами пополнил математическим.<br/> По закону он не обязан был идти в армию, но пошел на войну добровольцем, в чине прапорщика взят был в плен и бежал в конце семнадцатого года на родину, узнав, что в России революция.<br/> Две черты, две страсти отличали его.<br/> Он мыслил незаурядно ясно и правильно. И он в редкой степени владел даром нравственной чистоты и справедливости, он чувствовал горячо и благородно.<br/> Но для деятельности ученого, пролагающего новые пути, его уму недоставало дара нечаянности, силы, непредвиденными открытиями нарушающей бесплодную стройность пустого предвидения.<br/> А для того чтобы делать добро, его принципиальности недоставало беспринципности сердца, которое не знает общих случаев, а только частные, и которое велико тем, что делает малое.<br/> Стрельников с малых лет стремился к самому высокому и светлому. Он считал жизнь огромным ристалищем, на котором, честно соблюдая правила, люди состязаются в достижении совершенства.<br/> Когда оказалось, что это не так, ему не пришло в голову, что он не прав, упрощая миропорядок. Надолго загнав обиду внутрь, он стал лелеять мысль стать когда-нибудь судьей между жизнью и коверкающими её темными началами, выйти на её защиту и отомстить за нее.<br/> Разочарование ожесточило его. Революция его вооружила.

