### 31 {-}

— Живаго, Живаго, — продолжал повторять Стрельников у себя в вагоне, куда они перешли. — Что-то купеческое. Или дворянское. Ну да: доктор из Москвы. В Варыкино. Страшно. Из Москвы и вдруг в такой медвежий угол.<br/> — Именно с этой целью. В поисках тишины. В глушь, в неизвестность.<br/> — Скажите, какая поэзия. Варыкино? Здешние места мне знакомы. Бывшие Крюгеровские заводы. Часом не родственнички?<br/> Наследники?<br/> — К чему этот насмешливый тон? Причем тут «наследники»?<br/> Хотя жена действительно…<br/> — Ага, вот видите. По белым стосковались? Разочарую.<br/> Опоздали. Округ очищен.<br/> — Вы продолжаете издеваться?<br/> — И затем — доктор. Военный. А время военное. Это уже прямо по моей части. Дезертир. Зеленые тоже уединяются в лесах. Ищут тишины. Основание?<br/> — Дважды ранен и освобожден вчистую по негодности.<br/> — Сейчас вы представите записку Наркомпроса или Наркомздрава, рекомендующую вас как «вполне советского человека». Сейчас страшный суд на земле, милостивый государь, существа из апокалипсиса с мечами и крылатые звери, а не вполне сочувствующие и лояльные доктора. Впрочем, я сказал вам, что вы свободны, и не изменю своему слову. Но только на этот раз. Я предчувствую, что мы еще встретимся, и тогда разговор будет другой, берегитесь.<br/> Угроза и вызов не смутили Юрия Андреевича. Он сказал:<br/> — Я знаю все, что вы обо мне думаете. Со своей стороны вы совершенно правы. Но спор, в который вы хотите втянуть меня, я мысленно веду всю жизнь с воображаемым обвинителем и, надо думать, имел время притти к какому-то заключению. В двух словах этого не скажешь. Позвольте мне удалиться без объяснений, если я действительно свободен, а если нет — распоряжайтесь мною. Оправдываться мне перед вами не в чем.<br/> Их прервало верещанье гудка. Телефонная связь была восстановлена.<br/> — Спасибо, Гурьян, — сказал Стрельников, подняв трубку и дунув в нее несколько раз. — Пришлите, голубчик, какого-нибудь провожатого товарищу Живаго. Как бы опять чего-нибудь не случилось. И развильевскую уточку мне, пожалуйста, управление транспортным чека в Развилье.<br/> Оставшись один, Стрельников протелефонировал на вокзал:<br/> — Мальчика тут провели, насовывает шапку на уши, а голова забинтована, безобразие. Да. Подать медицинскую помощь, если нужно. Да, как зеницу ока, лично будете отвечать передо мной.<br/> Паек, если потребуется. Так. А теперь о делах. Я говорю, я не кончил. Ах, чорт, кто-то третий затесался. Гурьян! Гурьян!<br/> Разъединили.<br/> «Может быть из моих приготовишек», — думал он, на минуту отложив попытку докончить разговор с вокзалом. — «Вырос и бунтует против нас». — Стрельников мысленно подсчитал года своего учительства и войны и плена, сойдется ли сумма с возрастом мальчика. Потом через вагонное окно стал разыскивать в видневшейся на горизонте панораме тот район над рекой, у выезда из Юрятина, где была их квартира. А вдруг жена и дочь до сих пор там! Вот бы к ним! Сейчас, сию минуту! Да, но разве это мыслимо? Это ведь из совсем другой жизни. Надо сначала кончить эту, новую, прежде чем вернуться к той, прерванной.<br/> Это будет когда-нибудь, когда-нибудь. Да, но когда, когда?

