# ВТОРАЯ КНИГА {-}

## ЧАСТЬ восьмая. ПРИЕЗД {-}

### 1 {-}

Поезд, довезший семью Живаго до этого места, еще стоял на задних путях станции, заслоненный другими составами, но чувствовалось, что связь с Москвою, тянувшаяся всю дорогу, в это утро порвалась, кончилась.<br/> Начиная отсюда открывался другой территориальный пояс, иной мир провинции, тяготевший к другому, своему, центру притяжения.<br/> Здешние люди знали друг друга ближе, чем столичные. Хотя железнодорожная зона Юрятин-Развилье была очищена от посторонних и оцеплена красными войсками, местные пригородные пассажиры непонятным образом проникали на пути, «просачивались», как сейчас бы сказали. Они уже набились в вагон, ими полны были дверные пролеты теплушек, они ходили по путям вдоль поезда и стояли на насыпи у входов в свои вагоны.<br/> Эти люди были поголовно между собою знакомы, переговаривались издали, здоровались, поровнявшись друг с другом. Они немного иначе одевались и разговаривали, чем в столицах, ели не одно и то же, имели другие привычки.<br/> Занимательно было узнать, чем они жили, какими нравственными и материальными запасами питались, как боролись с трудностями, как обходили законы?<br/> Ответ не замедлил явиться в самой живой форме.

### 2 {-}

В сопровождении часового, тащившего ружье по земле и подпиравшегося им, как посохом, доктор возвращался к своему поезду.<br/> Парило. Солнце раскаляло рельсы и крыши вагонов. Черная от нефти земля горела желтым отливом, как позолотой.<br/> Часовой бороздил прикладом пыль, оставляя на песке след за собой. Ружье со стуком задевало за шпалы. Часовой говорил:<br/> — Установилась погода. Яровые сеять, овес, белотурку или, скажем, просо, самое золотое время. А гречиху рано. Гречиху у нас на Акулину сеют. Моршанские мы, Тамбовской губернии, нездешние, Эх, товарищ доктор! Кабы сейчас не эта гидра гражданская, моровая контра, нешто я стал бы в такую пору на чужой стороне пропадать? Черной кошкой классовою она промеж нас пробежала, и вишь, что делает!

