### 3 {-}

— Спасибо. Я сам, — отказывался Юрий Андреевич от предложенной помощи. Из теплушки нагибались, протягивали ему руки, чтобы подсадить. Он подтянулся, прыжком поднялся в вагон, стал на ноги и обнялся с женою.<br/> — Наконец-то. Ну слава, слава Богу, что все так кончилось, — твердила Антонина Александровна. — Впрочем, этот счастливый исход для нас не новость.<br/> — Как не новость?<br/> — Мы всё знали.<br/> — Откуда?<br/> — Часовые доносили. А то разве вынесли бы мы неизвестность? Мы и так с папой чуть с ума не сошли. Вон спит, не добудишься. Как сноп повалился от перенесенного волнения, — не растолкать. Есть новые пассажиры. Сейчас я тебя кое с кем познакомлю. Но вперед послушай, что кругом говорят. Весь вагон поздравляет тебя со счастливым избавлением. — Вот он у меня какой! — неожиданно переменила она разговор, повернула голову — и через плечо представила мужа одному из вновь насевших пассажиров сдавленному соседями, сзади, в глубине теплушки.<br/> — Самдевятов, — послышалось оттуда, над скоплением чужих голов поднялась мягкая шляпа и назвавшийся стал протискиваться через гущу сдавивших его тел к доктору.<br/> «Самдевятов», — размышлял Юрий Андреевич тем временем. — «Я думал, что-то старорусское, былинное, окладистая борода, поддевка, ремешок наборный. А это общество любителей художеств какое-то, кудри с проседью, усы, эспаньолка».<br/> — Ну что, задал вам страху Стрельников? Сознайтесь.<br/> — Нет, отчего же? Разговор был серьезный. Во всяком случае человек сильный, значительный.<br/> — Еще бы. Имею представление об этой личности. Не наш уроженец. Ваш, московский. Равно как и наши новшества последнего времени. Тоже ваши столичные, завозные. Своим умом бы не додумались.<br/> — Это Анфим Ефимович, Юрочка, — всевед — всезнайка. Про тебя слыхал, про твоего отца, дедушку моего знает, всех, всех.<br/> Знакомьтесь. — И Антонина Александровна спросила мимоходом, без выражения:<br/> — Вы наверное и учительницу здешнюю Антипову знаете? — На что Самдевятов ответил так же невыразительно:<br/> — А на что вам Антипова? — Юрий Андреевич слышал это и не поддержал разговора, Антонина Александровна продолжала:<br/> — Анфим Ефимович — большевик. Берегись, Юрочка. Держи с ним ухо востро.<br/> — Нет, правда? Никогда бы не подумал. По виду скорее что-то артистическое.<br/> — Отец постоялый двор держал. Семь троек в разгоне ходило.<br/> А я с высшим образованием. И, действительно, социал-демократ.<br/> — Послушай, Юрочка, что Анфим Ефимович говорит. Между прочим, не во гнев вам будь сказано, имя отчество у вас — язык сломаешь. — Да, так слушай, Юрочка, что я тебе скажу.<br/> Нам ужасно повезло. Юрятин-город нас не принимает. В городе пожары и мост взорван, нельзя проехать. Поезд передадут обходом по соединительной ветке на другую линию, и как раз на ту, которая нам требуется, на которой стоит Торфяная. Ты подумай! И не надо пересаживаться и с вещами тащиться через город с вокзала на вокзал. Зато нас здорово помотают из стороны в сторону, пока по-настоящему поедем. Будем долго маневрировать. Мне это все Анфим Ефимович объяснил.

