### 4 {-}

Предсказания Антонины Александровны сбылись. Перецепляя свои вагоны и добавляя новые, поезд без конца разъезжал взад и вперед по забитым путям, вдоль которых двигались и другие составы, долго заграждавшие ему выход в открытое поле.<br/> Город наполовину терялся вдали, скрытый покатостями местности. Он лишь изредка показывался над горизонтом крышами домов, кончиками фабричных труб, крестами колоколен. В нем горело одно из предместий. Дым пожара относило ветром. Он развевающейся конскою гривою тянулся по всему небу.<br/> Доктор и Самдевятов сидели на полу теплушки с краю, свесив за порог ноги. Самдевятов все время что-то объяснял Юрию Андреевичу, показывая вдаль рукою. Временами грохот раскатившейся теплушки заглушал его, так что нельзя было расслышать. Юрий Андреевич переспрашивал. Анфим Ефимович приближал лицо к доктору и, надрываясь от крика, повторял сказанное прямо ему в уши.<br/> — Это иллюзион «Гигант» зажгли. Там юнкеры засели. Но они раньше сдались. Вообще, бой еще не кончился. Видите черные точки на колокольне. Это наши. Чеха снимают.<br/> — Ничего не вижу. Как это вы все различаете?<br/> — А это Хохрики горят, ремесленная окраина. А Колодеево, где находятся торговые ряды, в стороне. Меня почему это интересует. В рядах двор наш. Пожар небольшой. Центр пока не затронут.<br/> — Повторите. Не слышу.<br/> — Я говорю, — центр, центр города. Собор, библиотека.<br/> Наша фамилия, Самдевятовы, это переделанное на русский лад Сан Донато. Будто из Демидовых мы.<br/> — Опять ничего не разобрал.<br/> — Я говорю, — Самдевятовы это видоизмененное Сан Донато.<br/> Будто из Демидовых мы. Князья Демидовы Сан Донато. А может, так, вранье. Семейная легенда. А эта местность называется Спирькин низ. Дачи, места увеселительных прогулок. Правда, странное название?<br/> Перед ними простиралось поле. Его в разных направлениях перерезали ветки железных дорог. По нему семимильными шагами удалялись, уходя за небосклон, телеграфные столбы. Широкая мощеная дорога извивалась лентою, соперничая красотою с рельсовым путем.<br/> Она то скрывалась за горизонтом, то на минуты выставлялась волнистою дугой поворота. И пропадала вновь.<br/> — Тракт наш знаменитый. Через всю Сибирь проложен.<br/> Каторгой воспет. Плацдарм партизанщины нынешней. Вообще, ничего у нас. Обживетесь, привыкнете. Городские курьезы полюбите. Водоразборные будки наши. На перекрестках. Зимние клубы женские под открытым небом.<br/> — Мы не в городе поселимся. В Варыкине.<br/> — Знаю. Мне жена ваша говорила. Все равно. По делам будете в город ездить. Я с первого взгляда догадался, кто она. Глаза.<br/> Нос. Лоб. Вылитый Крюгер. Вся в дедушку. В этих краях все Крюгера помнят.<br/> По концам поля краснели высокие круглостенные нефтехранилища. Торчали промышленные рекламы на высоких столбах. Одна из них, два раза попавшаяся на глаза доктору, была со словами:<br/> «Моро и Ветчинкин. Сеялки. Молотилки».<br/> — Солидная фирма была. Отличные сельскохозяйственные орудия производила.<br/> — Не слышу. Что вы сказали?<br/> — Фирма, говорю. Понимаете, — фирма. Сельскохозяйственные орудия выпускала. Товарищество на паях. Отец акционером состоял.<br/> — А вы говорили, — двор постоялый.<br/> — Двор двором. Одно другому не мешает. А он, не будь дурак, в лучшие предприятия деньги помещал. В иллюзион «Гигант» были вложены.<br/> — Вы, кажется, этим гордитесь?<br/> — Смекалкой отцовой? Еще бы!<br/> — А как же социал-демократия ваша?<br/> — А она при чем, помилуйте? Где это сказано, что человек, рассуждающий по-марксистски, должен размазнею быть и слюни распускать? Марксизм — положительная наука, учение о действительности, философия исторической обстановки.<br/> — Марксизм и наука? Спорить об этом с человеком мало знакомым по меньшей мере неосмотрительно. Но куда ни шло.<br/> Марксизм слишком плохо владеет собой, чтобы быть наукою. Науки бывают уравновешеннее. Марксизм и объективность? Я не знаю течения, более обособившегося в себе и далекого от фактов, чем марксизм. Каждый озабочен проверкою себя на опыте, а люди власти ради басни о собственной непогрешимости всеми силами отворачиваются от правды. Политика ничего не говорит мне. Я не люблю людей, безразличных к истине.<br/> Самдевятов считал слова доктора выходками чудака-острослова. Он только посмеивался и не возражал ему.<br/> Тем временем поезд маневрировал. Каждый раз, как он доезжал до выходной стрелки у семафора, пожилая стрелочница с привязанным к кушаку молочным бидоном, перекладывала вязание, которым была занята, из одной руки в другую, нагибалась, перекидывала диск переводной стрелки и возвращала поезд задним ходом обратно. Пока он мало-по-малу откатывался, она выпрямлялась и грозила кулаком вслед ему.<br/> Самдевятов принимал её движение на собственный счет. «Кому это она?» — задумывался он. — «Что-то знакомое. Не Тунцева ли? Похоже — она. Впрочем, что я? Едва ли. Больно стара для Глашки. И при чем я тут? На Руси-матушке перевороты, бестолочь на железных дорогах, ей, сердяге, наверное трудно, а я виноват и мне кулаком. А ну её к чорту, из-за нее еще голову ломать!»<br/> Наконец, помахав флагом и что-то крикнув машинисту, стрелочница пропустила поезд за семафор, на простор пути его следования, и когда мимо нее пронеслась четырнадцатая теплушка, показала язык намозолившим ей глаза болтунам на полу вагона. И опять Самдевятов задумался.

