### 5 {-}

Когда окрестности горящего города, цилиндрические баки, телеграфные столбы и торговые рекламы отступили в даль и скрылись, и пошли другие виды, перелески, горки, между которыми часто показывались извивы тракта, Самдевятов сказал:<br/> — Встанем и разойдемся. Мне скоро слезать. Да и вам через перегон. Смотрите не прозевайте.<br/> — Здешние места вы, верно, знаете основательно?<br/> — До умопомрачения. На сто верст в окружности. Я ведь юрист. Двадцать лет практики. Дела. Разъезды.<br/> — И до настоящего времени?<br/> — А как же.<br/> — Какого порядка дела могут совершаться сейчас?<br/> — А какие пожелаете. Старых незавершенных сделок, операций, невыполненных обязательств — по горло, до ужаса.<br/> — Разве отношения такого рода не аннулированы?<br/> — По имени, разумеется. А на деле в одно и то же время требуются вещи, друг друга исключающие. И национализация предприятий, и топливо горсовету, и гужевая тяга губсовнархозу. И вместе с тем всем хочется жить. Особенности переходного периода, когда теория еще не сходится с практикой.<br/> Тут и нужны люди сообразительные, оборотистые, с характером, вроде моего. Блажен муж, иже не йде, возьму куш, ничего не видя. А часом и по мордасам, как отец говаривал. Полгубернии мною кормится. К вам буду наведываться, по делам лесоснабжения. На лошади, разумеется, только выходится.<br/> Последняя охромела. А то, была бы здорова, стал бы я на этой завали трястись! Ишь чорт, тащится, а еще машиной называется.<br/> В наезды свои в Варыкино вам пригожусь. Микулицыных ваших знаю как свои пять пальцев.<br/> — Известна вам цель нашего путешествия, наши намерения?<br/> — Приблизительно. Догадываюсь. Имею представление.<br/> Извечная тяга человека к земле. Мечта пропитаться своими руками.<br/> — И что же? Вы, кажется, не одобряете? Что вы скажете?<br/> — Мечта наивная, идиллическая. Но отчего же? Помоги вам Бог. Но не верю. Утопично. Кустарщина.<br/> — Не пустит на порог, выгонит помелом и будет прав. Тут у него и без вас содом, тысяча и одна ночь, бездействующие заводы, разбежавшиеся рабочие, в смысле средств к существованию ни хрена, бескормица, и вдруг вы, извольте радоваться, принесла нелегкая. Да ведь если он и убьет вас, я его оправдаю.<br/> — Вот видите, вы — большевик и сами не отрицаете, что это не жизнь, а нечто беспримерное, фантасмагория, несуразица.<br/> — Разумеется. Но ведь это историческая неизбежность. Через нее надо пройти.<br/> — Почему же неизбежность?<br/> — Что вы, маленький, или притворяетесь? С луны вы свалились, что ли? Обжоры тунеядцы на голодающих тружениках ездили, загоняли до смерти и так должно было оставаться? А другие виды надругательства и тиранства? Неужели непонятна правомерность народного гнева, желание жить по справедливости, поиски правды? Или вам кажется, что коренная ломка была достижима в думах, путем парламентаризма, и что можно обойтись без диктатуры?<br/> — Мы говорим о разном и, хоть век проспорь, ни о чем не столкуемся. Я был настроен очень революционно, а теперь думаю, что насильственностью ничего не возьмешь. К добру надо привлекать добром. Но дело не в этом. Вернемся к Микулицыну.<br/> Если таковы ожидающие нас вероятия, то зачем нам ехать? Нам надо повернуть оглобли.<br/> — Какой вздор. Во-первых, разве только и свету в окошке, что Микулицыны? Во-вторых, Микулицын преступно добр, добр до крайности. Пошумит, покобенится и размякнет, рубашку с себя снимет, последнею коркою поделится. — И Самдевятов рассказал.

