### 6 {-}

Двадцать пять лет тому назад Микулицын студентом Технологического института приехал из Петербурга. Он был выслан сюда под надзор полиции. Микулицын приехал, получил место управляющего у Крюгера и женился. Тут у нас были четыре сестры Тунцевы, на одну больше, чем у Чехова, — за ними ухаживали все Юрятинские учащиеся, — Агриппина, Евдокия, Глафира и Серафима Севериновны. Перефразируя их отчество, девиц прозвали северянками. На старшей северянке Микулицын и женился.<br/> Скоро у супругов родился сын. Из поклонения идее свободы дурак отец окрестил мальчика редким именем Ливерий. Ливерий, в просторечии Ливка, рос сорванцом, обнаруживая разносторонние и незаурядные способности. Грянула война. Ливка подделал года в метрике и пятнадцатилетним юнцом удрал добровольцем на фронт.<br/> Аграфена Севериновна, вообще болезненная, не вынесла удара, слегла, больше не вставала и умерла позапрошлой зимой, перед самой революцией.<br/> Кончилась война. Вернулся Ливерий. Кто он? Это герой прапорщик с тремя крестами и, ну конечно, в лоск распропагандированный фронтовой делегат-большевик. Про «Лесных братьев» вы слыхали?<br/> — Нет, простите.<br/> — Ну тогда нет смысла рассказывать. Половина эффекта пропадает. Тогда незачем вам из вагона на тракт глазеть. Чем он замечателен? В настоящее время — партизанщиной. Что такое партизаны? Это главные кадры гражданской войны. Два начала участвовали в создании этой силы. Политическая организация, взявшая на себя руководство революцией, и низовая солдатчина, после проигранной войны отказывающая в повиновении старой власти. Из соединения этих двух вещей — получилось партизанское воинство. Состав его пестрый. В основном это крестьяне-середняки. Но наряду с этим вы встретите в нем кого угодно. Есть тут и бедняки, и монахи расстриги, и воюющие с папашами кулацкие сынки. Есть анархисты идейные, и беспаспортные голоштанники, и великовозрастные, выгнанные из средних учебных заведений женихи оболтусы. Есть австрогерманские военнопленные, прельщенные обещанием свободы и возвращения на родину. И вот, одною из частей этой многотысячной народной армии, именуемой «Лесными братьями», командует товарищ Лесных, Ливка, Ливерий Аверкиевич, сын Аверкия Степановича Микулицына.<br/> — Что вы говорите?<br/> — То, что вы слышите. Однако, продолжаю. После смерти жены Аверкий Степанович женился вторично. Новая жена, Елена Прокловна — гимназистка, прямо со школьной скамьи привезенная под венец. Наивная от природы, но и с расчетом наивничающая, молоденькая, но уже и молодящаяся. В этих видах трещит, щебечет, корчит из себя невинность, дурочку, полевого жаворонка. Только вас увидит, начнет экзаменовать. «В каком году родился Суворов?», «Перечислите случаи равенства треугольников». И будет ликовать, срезав вас и посадив в калошу. Но через несколько часов вы сами её увидите и проверите мое описание.<br/> У «самого» другие слабости: трубка и семинарская славянщина: «ничтоже сумняшеся, еже и понеже». Его поприщем должно было быть море. В институте он шел по кораблестроительной части. Это осталось во внешности, в привычках. Бреется, по целым дням не вынимает трубки изо рта, цедит слова сквозь зубы любезно, неторопливо. Выступающая нижняя челюсть курильщика, холодные серые глаза. Да чуть не забыл подробности: эсер, выбран от края в Учредительное собрание.<br/> — Так ведь это очень важно. Значит, отец и сын на ножах?<br/> Политические противники?<br/> — Номинально, разумеется. А в действительности тайга с Варыкиным не воюет. Однако, продолжаю. Остальные Тунцевы, свояченицы Аверкия Степановича, по сей день в Юрятине. Девы вековуши. Переменились времена, переменились и девушки.<br/> Старшая из оставшихся, Авдотья Севериновна — библиотекаршей в городской читальне. Милая, черненькая барышня, конфузливая до чрезвычайности. Ни с того ни с сего зардеется как пион. Тишина в читальном зале могильная, напряженная. Нападет хронический насморк, расчихается раз до двадцати, со стыда готова сквозь землю провалиться. А что вы поделаете? От нервности.<br/> Средняя, Глафира Севериновна, благословение сестер.<br/> Бой-девка, чудо-работница. Никаким трудом не гнушается. Общее мнение, в один голос, что партизанский вожак Лесных в эту тетку. Вот её видели в швейной артели или чулочницей. Не успеешь оглянуться, ан она уже парикмахерша. Вы обратили внимание, на юрятинских путях стрелочница нам кулаком грозила?<br/> Вот те фунт, думаю, в сторожихи на дорогу Глафира определилась. Но, кажется, не она. Слишком стара.<br/> Младшая, Симушка, — крест семьи, испытание. Ученая девушка начитанная. Занималась философией, любила стихи. И вот в годы революции, под влиянием общей приподнятости, уличных шествий, речей на площадях с трибуны, тронулась, впала в религиозное помешательство. Уйдут сестры на службу, дверь на ключ, а она шасть в окно и пойдет махать по улицам, публику собирает, второе пришествие проповедует, конец света. Но я заговорился, к своей станции подъезжаю. Вам на следующей. Готовьтесь.<br/> Когда Анфим Ефимович сошел с поезда, Антонина Александровна сказала:<br/> — Я не знаю, как ты на это смотришь, но по-моему человек этот послан нам судьбой. Мне кажется, он сыграет какую-то благодетельную роль в нашем существовании.<br/> — Очень может быть, Тонечка. Но меня не радует, что тебя узнают по сходству с дедушкой, и что его тут так хорошо помнят. Вот и Стрельников, едва я назвал Варыкино, ввернул язвительно: «Варыкино, заводы Крюгера. Часом не родственнички?<br/> Не наследники?»<br/> Я боюсь, что тут мы будем больше на виду, чем в Москве, откуда бежали в поисках незаметности.<br/> Конечно, делать теперь нечего. Снявши голову, по волосам не плачут. Но лучше не выказываться, скрадываться, держаться скромнее. Вообще у меня недобрые предчувствия. Давай будить наших, уложим вещи, стянем ремнями и приготовимся к высадке.

