### 7 {-}

Антонина Александровна стояла на перроне в Торфяной, в несчетный раз пересчитывая людей и вещи, чтобы убедиться, что в вагоне ничего не забыли. Она чувствовала утоптанный песок платформы под ногами, а между тем страх, как бы не проехать остановки, не покинул ее, и стук идущего поезда продолжал шуметь в её ушах, хотя глазами она убеждалась, что он стоит перед нею у перрона без движения. Это мешало ей что-либо видеть, слышать и соображать.<br/> Дальние попутчики прощались с нею сверху, с высоты теплушки. Она их не замечала. Она не заметила, как ушел поезд, и обнаружила его исчезновение только после того, как обратила внимание на открывшиеся по его отбытии вторые пути с зеленым полем и синим небом по ту сторону.<br/> Здание станции было каменное. У входа в него стояли по обеим сторонам две скамейки. Московские путники из Сивцева были единственными пассажирами, высадившимися в Торфяной. Они положили вещи и сели на одну из скамеек.<br/> Приезжих поражала тишина на станции, безлюдие, опрятность.<br/> Им казалось непривычным, что кругом не толпятся, не ругаются. Жизнь по-захолустному отставала тут от истории, запаздывала. Ей предстояло еще достигнуть столичного одичания.<br/> Станция пряталась в березовой роще. В поезде стало темно, когда он к ней подходил. По рукам и лицам, по чистому, сыровато-желтому песочку платформы, по земле и крышам сновали движущиеся тени, отбрасываемые её едва колышащимися вершинами.<br/> Птичий свист в роще соответствовал её свежести. Неприкрыто чистые, как неведение, полные звуки раздавались на весь лес и пронизывали его. Рощу прорезали две дороги, железная и проселочная, и она одинаково завешивала обе своими разлетающимися, книзу клонящимися ветвями, как концами широких, до полу ниспадающих рукавов.<br/> Вдруг у Антонины Александровны открылись глаза и уши. До её сознания дошло все сразу. Звонкость птиц, чистота лесного уединения, безмятежность разлитого кругом покоя. У нее в уме была составлена фраза: «Мне не верилось, что мы доедем невредимыми. Он мог, понимаешь ли, твой Стрельников, свеликодушничать перед тобой и отпустить тебя, а сюда дать телеграфное распоряжение, чтобы всех нас задержали при высадке. Не верю я, милый мой, в их благородство. Все только показное». Вместо этих заготовленных слов она сказала другое.<br/> — Какая прелесть! — вырвалось у нее при виде окружающего очарования. Больше она не могла ничего выговорить. Ее стали душить слезы. Она громко расплакалась.<br/> Заслышав её всхлипывания, из здания вышел старичок начальник станции. Он мелкими шажками просеменил к скамейке, вежливо приложил руку к козырьку красноверхой форменной фуражки и спросил:<br/> — Может быть, успокаивающих капель барышне? Из вокзальной аптечки.<br/> — Пустяки. Спасибо. Обойдется.<br/> — Путевые заботы, тревоги. Вещь известная, распространенная. Притом жара африканская, редкая в наших широтах. И вдобавок события в Юрятине.<br/> — Мимоездом пожар из вагона наблюдали.<br/> — Стало быть сами из России будете, если не ошибаюсь.<br/> — Из Белокаменной.<br/> — Московские? Тогда нечего удивляться, что нервы не в порядке у сударыни. Говорят, камня на камне не осталось?<br/> — Преувеличивают. Но, правда, всего навидались. Вот это дочь моя, это зять. Вот малыш их. А это нянюшка наша молодая, Нюша.<br/> — Здравствуйте. Здравствуйте. Очень приятно. Отчасти предуведомлен. Самдевятов Анфим Ефимович с разъезда Сакмы по дорожному телефону навертел. Доктор Живаго с семьей из Москвы, прошу, говорит, окажите всемерное содействие. Этот самый доктор, стало быть, вы и будете?<br/> — Нет, доктор Живаго это он вот, мой зять, а я по другой части, по сельскому хозяйству, профессор агроном Громеко.<br/> — Виноват, обознался. Извините. Очень рад познакомиться.<br/> — Значит, судя по вашим словам, вы знаете Самдевятова?<br/> — Как не знать его, волшебника. Надежа наша и кормилец.<br/> Без него давно бы мы тут ноги протянули. Да, говорит, окажи всемерное содействие. Слушаюсь, говорю. Пообещал. Так что лошадку, если потребуется, или иным чем поспособствовать. Вы куда намерены?<br/> — Нам в Варыкино. Это как, далеко отсюда?<br/> — В Варыкино? То-то я никак ума не приложу, кого ваша дочь напоминает так. А вам в Варыкино! Тогда все объясняется. Ведь мы с Иваном Эрнестовичем дорогу эту вместе строили. Сейчас похлопочу, снарядим. Человека кликну, раздобудем подводу.<br/> Донат! Донат! Вещи снеси вот, пока суд да дело, в пассажирский зал, в ожидальную. Да как бы насчет лошади? Сбегай, брат, в чайную, спроси, нельзя ли? Словно бы утром Вакх тут маячил.<br/> Спроси, может не уехал? Скажи, в Варыкино свезти четверых, поклажи все равно что никакой. Новоприезжие. Живо. А вам отеческий совет, сударыня. Я намеренно не спрашиваю вас о степени вашего родства с Иваном Эрнестовичем, но поосторожнее на этот счет. Не со всеми нараспашку. Времена какие, сами подумайте.<br/> При имени Вакх приезжие изумленно переглянулись. Они еще помнили рассказы покойной Анны Ивановны о сказочном кузнеце, выковавшем себе неразрушающиеся внутренности из железа, и прочие местные россказни и небылицы.

