### 8 {-}

Их вез на белой ожеребившейся кобыле лопоухий, лохматый, белый, как лунь, старик. Все на нем было белое по разным причинам. Новые его лапти не успели потемнеть от носки, а порты и рубаха вылиняли и побелели от времени.<br/> За белою кобылой, вскидывая хрящеватые, неокостеневшие ноги, бежал вороной, черный, как ночь, жеребенок с курчавой головкой, похожий на резную кустарную игрушку.<br/> Сидя по краям подскакивавшей на колдобинах телеги, путники держались за грядки, чтобы не свалиться. Мир был на душе у них. Их мечта сбывалась, они приближались к цели путешествия.<br/> Со щедрой широтой и роскошью медлили, задерживались предвечерние часы чудесного, ясного дня.<br/> Дорога шла то лесом, то открытыми полями. В лесу толчки от коряг сбивали едущих в кучу, они горбились, хмурились, тесно прижимались друг к другу. На открытых местах, где само пространство от полноты души как бы снимало шапку, путники разгибали спины, располагались просторнее, встряхивали головами.<br/> Места были гористые. У гор, как всегда, был свой облик, своя физиономия. Они могучими, высокомерными тенями темнели вдали, молчаливо рассматривая едущих. Отрадно розовый свет следовал по полю за путешественниками, успокаивая, обнадеживая их.<br/> Все нравилось им, все их удивляло, и больше всего неумолчная болтовня их старого чудаковатого возницы, в которой следы исчезнувших древнерусских форм, татарские наслоения и областные особенности перемешивались с невразумительностями его собственного изобретения.<br/> Когда жеребенок отставал, кобыла останавливалась и поджидала его. Он плавно нагонял её волнообразными, плещущими скачками. Неумелым шагом длинных, сближенных ног он подходил сбоку к телеге и, просунув крошечную головку на длинной шее за оглоблю, сосал матку.<br/> — Я все-таки не понимаю, — стуча зубами от тряски, с расстановкою, чтобы при непредвиденном толчке не откусить себе кончик языка, кричала мужу Антонина Александровна. — Возможно ли, чтобы это был тот самый Вакх, о котором рассказывала мама.<br/> Ну, помнишь, белиберда всякая. Кузнец, кишки в драке отбили, он смастерил себе новые. Одним словом, кузнец Вакх Железное брюхо. Я понимаю, что все это сказки. Но неужели это сказка о нем? Неужели этот тот самый?<br/> — Конечно, нет. Во-первых, ты сама говоришь, что это сказка, фольклор. Во-вторых, и фольклору-то в мамины годы, как она говорила, было уже лет за сто. Но к чему так громко?<br/> Старик услышит, обидится.<br/> — Ничего он не услышит, — туг на ухо. А и услышит, не возьмет в толк, — с придурью.<br/> — Эй, Федор Нефедыч! — неизвестно почему, мужским величаньем понукал старик кобылу, прекрасно, и лучше седоков, сознавая, что она кобыла. — Инно жара кака анафемска! Яко во пещи авраамстии отроци персидстей! Но, чорт, непасёный! Тебе говорят, мазепа!<br/> Неожиданно он затягивал обрывки частушек, в былые времена сложенных на здешних заводах.

