### 9 {-}

Первая встреча приехавших с хозяевами произошла на дворе директорского домика. Разыгралась томительная, по началу молчаливая, а потом — сбивчиво-шумная, бестолковая сцена.<br/> Елена Прокловна возвращалась по двору из лесу с вечерней про гулки. Вечерние лучи солнца тянулись по её следам через весь лес от дерева к дереву почти того же цвета, что её золотистые волосы. Елена Прокловна одета была легко, по-летнему. Она раскраснелась и утирала платком разгоряченное ходьбою лицо. Ее открытую шею перехватывала спереди резинка, на которой болталась её скинутая на спину соломенная шляпа.<br/> Ей навстречу шел с ружьем домой её муж, поднявшийся из оврага и предполагавший тотчас же заняться прочисткой задымленных стволов, в виду замеченных при разрядке недочетов.<br/> Вдруг, откуда ни возьмись, по камням мощеного въезда во двор лихо и громко вкатил Вакх со своим подарком.<br/> Очень скоро, слезши с телеги со всеми остальными, Александр Александрович, с запинками, то снимая, то надевая шляпу, дал первые объяснения.<br/> Несколько мгновений длилось истинное, не показное остолбенение поставленных втупик хозяев, и непритворная, искренняя потерянность сгорающих со стыда несчастных гостей.<br/> Положение было понятно без разъяснений не только участникам, Вакху, Нюше и Шурочке. Ощущение тягостности передавалось кобыле и жеребенку, золотистым лучам солнца и комарам, вившимся вокруг Елены Прокловны и садившимся на её лицо и шею.<br/> — Не понимаю, — прервал, наконец, молчание Аверкий Степанович. — Не понимаю, ничего не понимаю, и никогда не пойму. Что у нас юг, белые, хлебная губерния? Почему именно на нас пал выбор, почему вас сюда, сюда, к нам угораздило?<br/> — Интересно, подумали ли вы, какая это ответственность для Аверкия Степановича?<br/> — Леночка, не мешай. Да, вот именно. Она совершенно права.<br/> Подумали ли вы, какая это для меня обуза?<br/> — Бог с вами. Вы нас не поняли. О чем речь? Об очень малом, ничтожном. Никакого покушения на вас, на ваш покой.<br/> Угол какой-нибудь в пустой развалившейся постройке. Клинушек никому не нужной, даром пропадающей земли под огород. Да возик дровец из лесу, когда никто не увидит. Неужели это так много, такое посягательство?<br/> — Да, но свет широк. Причем мы тут? Почему этой чести удостоились именно мы, а не кто-нибудь другой?<br/> — Мы о вас знаем и надеялись, что и вы о нас слышали. Что мы не чужие для вас и сами попадем не к чужим.<br/> — А, так дело в Крюгере, в том, что вы его родня? Да как у вас язык поворачивается признаваться в таких вещах в наше время?<br/> Аверкий Степанович был человек с правильными чертами лица, откидывавший назад волосы, широко ступавший на всю ногу и летом тесьмяным снурком с кисточкой подпоясывавший косоворотку. В древности такие люди ходили в ушкуйниках, в новое время они сложили тип вечного студента, учительствующего мечтателя.<br/> Свою молодость Аверкий Степанович отдал освободительному движению, революции, и только боялся, что он не доживет до нее или, что разразившись, она своей умеренностью не удовлетворит его радикальных и кровавых вожделений. И вот она пришла, перевернув вверх дном все самые смелые его предположения, а он, прирожденный и постоянный рабочелюбец, один из первых учредивший на «Святогоре Богатыре» фабрично-заводский комитет и установивший на нем рабочий контроль, очутился на бобах, не у дел, в опустевшем поселке, из которого разбежались рабочие, частью шедшие тут за меньшевиками. И теперь эта нелепость, эти непрошенные крюгеровские последыши казались ему насмешкою судьбы, её намеренной каверзой, и переполняли чашу его терпения.<br/> — Нет, это чудеса в решете. Уму непостижимо. Понимаете ли вы какая вы для меня опасность, в какое положение вы меня ставите? Я, видно, право, с ума сошел. Не понимаю, ничего не понимаю и никогда не пойму.<br/> — Интересно, постигаете ли вы, на каком мы тут и без вас вулкане?<br/> — Погоди, Леночка. Жена совершенно права. И без вас не сладко. Собачья жизнь, сумасшедший дом. Все время меж двух огней, никакого выхода. Одни собак вешают, отчего такой красный сын, большевик, народный любимец. Другим не нравится, зачем самого выбрали в Учредительное собрание. Ни на какого не угодишь, вот и барахтайся. А тут еще вы. Очень весело будет за вас под расстрел идти.<br/> — Да что вы! Опомнитесь! Бог с вами! Через некоторое время, переложив гнев на милость, Микулицын говорил:<br/> — Ну, полаялись на дворе и ладно. Можно в доме продолжать. Хорошего, конечно, впереди ничего не вижу, но сие есть темна вода во облацех, сеннописаный мрак гаданий. Одначе, не янычары мы, не басурмане. В лес на съедение Михайло Потапычу не погоним. Я думаю, Ленок, лучше всего их в пальмовую, рядом с кабинетом. А там потолкуем, где им обосноваться, мы их, я думаю, в парке водворим. Пожалуйте в дом. Милости просим. Вноси вещи, Вакх. Пособи приезжим.<br/> Исполняя приказание, Вакх только вздыхал:<br/> — Мати безневестная! Добра, что у странников. Одни узелки. Ни единого чумадала!

