### 10 {-}

Наступила холодная ночь. Приезжие умылись. Женщины занялись устройством ночлега в отведенной комнате. Шурочка, бессознательно привыкший к тому, что его ребяческие изречения на детском языке принимаются взрослыми восторженно, и потому, подлаживаясь под их вкус, с увлечением и охотно несший околесину, был не в своей тарелке. Сегодня его болтовня не имела успеха, на него не обращали внимания. Он был недоволен, что в дом не взяли черного жеребеночка, а когда на него прикрикнули, чтобы он угомонился, он разревелся, опасаясь, как бы его, как плохого и неподходящего мальчика, не отправили назад в детишный магазин, откуда, по его представлениям, его при появлении на свет доставили на дом родителям. Свои искренние страхи он громко выражал окружающим, но его милые нелепости не производили привычного впечатления. Стесненные пребыванием в чужом доме, старшие двигались торопливее обычного и были молчаливо погружены в свои заботы. Шурочка обижался и квелился, как говорят няни. Его накормили и с трудом уложили спать. Наконец, он уснул. Нюшу увела к себе кормить ужином и посвящать в тайны дома Микулицынская Устинья.<br/> Антонину Александровну и мужчин попросили к вечернему чаю.<br/> Александр Александрович и Юрий Андреевич попросили разрешения отлучиться на минуту и вышли на крыльцо подышать свежим воздухом.<br/> — Сколько звезд! — сказал Александр Александрович.<br/> Было темно. Стоя на расстоянии двух шагов на крыльце, зять и тесть не видели друг друга. А сзади из-за угла дома падал свет лампы из окна в овраг. В его столбе туманились на сыром холоде кусты, деревья и еще какие-то неясные предметы. Светлая полоса не захватывала беседовавших, и еще больше сгущала темноту вокруг них.<br/> — Завтра надо будет с утра осмотреть пристройку, которую он нам наметил, и если она пригодна для жилья, разом за её починку. Тем временем как будем приводить угол в порядок, почва отойдет, земля согреется. Тогда, не теряя ни минуты, за грядки. Мне послышалось, будто он между слов, в разговоре обещал помочь семенною картошкой. Или я ослышался?<br/> — Обещал, обещал. И другими семенами. Я своими ушами слышал. А угол, который он предлагает, мы видели проездом, когда пересекали парк. Знаете, где? Это зады господского дома, утонувшие в крапиве. Деревянные, а сам он каменный. Я вам с телеги показывал, помните? Там бы стал я рыть и грядки.<br/> По-моему, там остатки цветника. Так мне показалось издали.<br/> Может быть, я ошибаюсь. Дорожки надо будет обходить, пропускать, а земля старых клумб наверное основательно унаваживалась и богата перегноем.<br/> — Завтра посмотрим. Не знаю. Грунт наверное страшно затравянел и тверд, как камень. При усадьбе был, должно быть, огород. Может быть, участок сохранился и пустует. Все это выяснится завтра. По утрам тут еще наверное заморозки. Ночью мороз будет наверняка. Какое счастье, что мы уже здесь, на месте. С этим можно поздравить друг друга. Тут хорошо. Мне нравится.<br/> — Очень приятные люди. В особенности он. Она немного ломака. Она чем-то недовольна собой, ей что-то в себе самой не нравится. Отсюда эта неутомимая, притворно-вздорная говорливость. Она как бы торопится отвлечь внимание от своей внешности, предупредить невыгодное впечатление. И то, что она шляпу забывает снять и на плечах таскает, тоже не рассеянность. Это действительно к лицу ей.<br/> — Пойдем однако в комнаты. Мы слишком тут застряли.<br/> Неудобно.<br/> По пути в освещенную столовую, где за круглым столом под висячею лампой сидели за самоваром и распивали чай хозяева с Антониной Александровной, зять и тесть прошли через темный директорский кабинет.<br/> В нем было широкое цельного стекла окно во всю стену, возвышавшееся над оврагом. Из окна, насколько успел заметить доктор еще вначале, пока было светло, открывался вид на далекое заовражье и равнину, по которой провозил их Вакх. У окна стоял широкий, также во всю стену, стол проектировщика или чертежника. Вдоль него лежало, в длину положенное, охотничье ружье, оставляя свободные борта слева и справа, и тем оттеняя большую ширину стола.<br/> Теперь, минуя кабинет, Юрий Андреевич снова с завистью отметил окно с обширным видом, величину и положение стола и поместительность хорошо обставленной комнаты, и это было первое, что в виде восклицания хозяину вырвалось у Юрия Андреевича, когда он и Александр Александрович подошли к чайному столу, войдя в столовую.<br/> — Какие у вас замечательные места. И какой у вас кабинет превосходный, побуждающий к труду, вдохновляющий.<br/> — Вам в стакане или в чашке? И какой вы любите, слабый или крепкий?<br/> — Смотри, Юрочка, какой стереоскоп сын Аверкия Степановича смастерил, когда был маленький.<br/> — Он до сих пор еще не вырос, не остепенился, хотя отвоевывает Советской власти область за областью у Комуча.<br/> — Как вы сказали?<br/> — Комуч.<br/> — Что это такое?<br/> — Это войска Сибирского правительства, стоящие за восстановление власти Учредительного собрания.<br/> — Мы весь день, не переставая, слышим похвалы вашему сыну.<br/> Можете по всей справедливости им гордиться.<br/> — Эти виды Урала, двойные, стереоскопические, тоже его работа и сняты его самодельным объективом.<br/> — На сахарине лепешки? Замечательное печенье.<br/> — О что вы! Такая глушь и сахарин! Куда нам! Честнейший сахар. Ведь я вам в чай из сахарницы клала. Неужели не заметили.<br/> — Да, действительно. Я фотографии рассматривала. И, кажется, чай натуральный?<br/> — С цветком. Само собой.<br/> — Откуда?<br/> — Скатерть самобранка такая. Знакомый. Современный деятель. Очень левых убеждений. Официальный представитель Губсовнархоза. От нас лес возит в город, а нам по знакомству крупу, масло, муку. Сиверка (так она звала своего Аверкия), Сиверка, пододвинь мне сухарницу. А теперь интересно, ответьте, в котором году умер Грибоедов?<br/> — Родился, кажется, в тысяча семьсот девяносто пятом. А когда убит, в точности не помню.<br/> — Еще чаю.<br/> — Нет, спасибо.<br/> — А теперь такая штука. Скажите, когда и между какими странами заключен Нимвегенский мир?<br/> — Да не мучай их, Леночка. Дай людям очухаться с дороги.<br/> — Теперь вот что мне интересно. Перечислите, пожалуйста, каких видов бывают увеличительные стекла, и в каких случаях получаются изображения действительные, обращенные, прямые и мнимые?<br/> — Откуда у вас такие познания по физике?<br/> — Великолепный математик был у нас в Юрятине. В двух гимназиях преподавал, в мужской и у нас. Как объяснял, как объяснял! Как бог! Бывало, все разжует и в рот положит.<br/> Антипов. На здешней учительнице был женат. Девочки были без ума от него, все в него влюблялись. Пошел добровольцем на войну и больше не возвращался, был убит. Утверждают, будто бич божий наш и кара небесная, комиссар Стрельников, это оживший Антипов. Легенда, конечно. И непохоже. А впрочем, кто его знает. Все может быть. Еще чашечку.

