### 2 {-}

Несколько позднее доктор записал:<br/> «Мы поселились в задней части старого барского дома, в двух комнатах деревянной пристройки, в детские годы Анны Ивановны предназначавшейся Крюгером для избранной челяди, для домашней портнихи, экономки и отставной няни.<br/> Этот угол порядком обветшал. Мы довольно быстро починили его. С помощью понимающих мы переложили выходящую в обе комнаты печку по-новому. С теперешним расположением оборотов она дает больше нагрева.<br/> В этом месте парка следы прежней планировки исчезли под новой растительностью, все заполнившей. Теперь, зимой, когда всё кругом помертвело и живое не закрывает умершего, занесенные снегом черты былого выступают яснее.<br/> Нам посчастливилось. Осень выдалась сухая и теплая.<br/> Картошку успели выкопать до дождей и наступления холодов. За вычетом задолженной и возвращенной Микулицыным, её у нас до двадцати мешков, и вся она в главном закроме погреба, покрытая сверху, поверх пола, сеном и старыми рваными одеялами. Туда же в подполье спустили две бочки огурцов, которые засолила Тоня, и столько же бочек наквашенной ею капусты. Свежая развешана по столбам крепления, вилок с вилком, связанная попарно. В сухой песок зарыты запасы моркови. Здесь же достаточное количество собранной редьки, свеклы и репы, а наверху в доме множество гороху и бобов. Навезенных дров в сарае хватит до весны. Я люблю зимою теплое дыхание подземелья, ударяющее в нос кореньями, землей и снегом, едва подымешь опускную дверцу погреба, в ранний час, до зимнего рассвета, со слабым, готовым угаснуть и еле светящимся огоньком в руке.<br/> Выйдешь из сарая, день еще не занимается. Скрипнешь дверью, или нечаянно чихнешь, или просто снег хрустнет под ногою, и с дальней огородной гряды с торчащими из-под снега капустными кочерыжками порснут и пойдут улепетывать зайцы, размашистыми следами которых вдоль и поперек изборожден снег кругом. И в окрестностях, одна за другой, надолго разлаются собаки.<br/> Последние петухи пропели уже раньше, им теперь не петь. И начнет светать.<br/> Кроме заячьих следов, необозримую снежную равнину пересекают рысьи, ямка к ямке, тянущиеся аккуратно низанными нитками. Рысь ходит как кошка, лапка за лапку, совершая, как утверждают, за ночь многоверстные переходы.<br/> На них ставят капканы, слопцы, как их тут называют. Вместо рысей в ловушки попадают бедные русаки, которых вынимают из капканов морожеными, окоченелыми и полузанесенными снегом.<br/> Вначале, весною и летом, было очень трудно. Мы выбивались из сил. Теперь, зимними вечерами, отдыхаем. Собираемся, благодаря Анфиму, снабжающему нас керосином, вокруг лампы.<br/> Женщины шьют или вяжут, я или Александр Александрович читаем вслух. Топится печка, я, как давний признанный истопник, слежу за ней, чтобы вовремя закрыть вьюшку и не упустить жару. Если недогоревшая головешка задерживает топку, выношу ее, бегом, всю в дыму, за порог и забрасываю подальше в снег. Рассыпая искры, она горящим факелом перелетает по воздуху, озаряя край черного спящего парка с белыми четырехугольниками лужаек, и шипит и гаснет, упав в сугроб.<br/> Без конца перечитываем «Войну и мир», «Евгения Онегина» и все поэмы, читаем в русском переводе «Красное и Черное» Стендаля, «Повесть о двух городах» Диккенса и коротенькие рассказы Клейста».

