### 3 {-}

Ближе к весне доктор записал:<br/> «Мне кажется, Тоня в положении. Я ей об этом сказал. Она не разделяет моего предположения, а я в этом уверен. Меня до появления более бесспорных признаков не могут обмануть предшествующие, менее уловимые.<br/> Лицо женщины меняется. Нельзя сказать, чтобы она подурнела.<br/> Но её внешность, раньше всецело находившаяся под её наблюдением, уходит из-под её контроля. Ею распоряжается будущее, которое выйдет из неё и уже больше не есть она сама.<br/> Этот выход облика женщины из-под её надзора носит вид физической растерянности, в которой тускнеет её лицо, грубеет кожа и начинают по другому, не так, как ей хочется, блестеть глаза, точно она всем этим не управилась и запустила.<br/> Мы с Тоней никогда не отдалялись друг от друга. Но этот трудовой год нас сблизил еще тесней. Я наблюдал, как расторопна, сильна и неутомима Тоня, как сообразительна в подборе работ, чтобы при их смене терялось как можно меньше времени.<br/> Мне всегда казалось, что каждое зачатие непорочно, что в этом догмате, касающемся Богоматери, выражена общая идея материнства.<br/> На всякой рожающей лежит тот же отблеск одиночества, оставленности, предоставленности себе самой. Мужчина до такой степени не у дел сейчас, в это существеннейшее из мгновений, что точно его и в заводе не было и все как с неба свалилось.<br/> Женщина сама производит на свет свое потомство, сама забирается с ним на второй план существования, где тише, и куда без страха можно поставить люльку. Она сама в молчаливом смирении вскармливает и выращивает его.<br/> Богоматерь просят: «Молися прилежно Сыну и Богу Твоему». Ей вкладывают в уста отрывки псалма: «И возрадовася дух мой о Бозе Спасе моем. Яко воззри на смирение рабы своея, се бо отныне ублажат мя вси роди». Это она говорит о своем младенце, он возвеличит её («Яко сотвори мне величие сильный»), он — её слава. Так может сказать каждая женщина. Ее бог в ребенке.<br/> Матерям великих людей должно быть знакомо это ощущение. Но все решительно матери — матери великих людей, и не их вина, что жизнь потом обманывает их».

