### 4 {-}

«Без конца перечитываем Евгения Онегина и поэмы. Вчера был Анфим, навез подарков. Лакомимся, освещаемся. Бесконечные разговоры об искусстве.<br/> Давнишняя мысль моя, что искусство не название разряда или области, обнимающей необозримое множество понятий и разветвляющихся явлений, но наоборот, нечто узкое и сосредоточенное, обозначение начала, входящего в состав художественного произведения, название примененной в нем силы или разработанной истины. И мне искусство никогда не казалось предметом или стороною формы, но скорее таинственной и скрытой частью содержания. Мне это ясно, как день, я это чувствую всеми своими фибрами, но как выразить и сформулировать эту мысль?<br/> Произведения говорят многим: темами, положениями, сюжетами, героями. Но больше всего говорят они присутствием содержащегося в них искусства. Присутствие искусства на страницах «Преступления и наказания» потрясает больше, чем преступление Раскольникова.<br/> Искусство первобытное, египетское, греческое, наше, это, наверное, на протяжении многих тысячелетий одно и то же, в единственном числе остающееся искусство. Это какая-то мысль, какое-то утверждение о жизни, по всеохватывающей своей широте на отдельные слова не разложимое, и когда крупица этой силы входит в состав какой-нибудь более сложной смеси, примесь искусства перевешивает значение всего остального и оказывается сутью, душой и основой изображенного».

### 5 {-}

«Немного простужен, кашель и, наверное, небольшой жар. Весь день перехватывает дыхание где-то у гортани, комком подкатывая к горлу. Плохо мое дело. Это аорта. Первые предупреждения наследственности со стороны бедной мамочки, пожизненной сердечницы. Неужели правда? Так рано? Не долгий я в таком случае жилец на белом свете.<br/> В комнате легкий угар. Пахнет глаженым. Гладят и, то и дело, из непротопившейся печки подкладывают жаром пламенеющий уголь в ляскающий крышкой, как зубами, духовой утюг. Что-то напоминает. Не могу вспомнить, что. Забывчив по нездоровью.<br/> На радостях, что Анфим привез ядрового мыла, закатили генеральную стирку, и Шурочка два дня без присмотра.<br/> Забирается, когда я пишу, под стол, садится на перекладину между ножками и, подражая Анфиму, который в каждый приезд катает его на санях, изображает, будто тоже вывозит меня в розвальнях.<br/> Как выздоровею, надо будет поездить в город, почитать кое-что по этнографии края, по истории. Уверяют, будто здесь замечательная городская библиотека, составленная из нескольких богатых пожертвований. Хочется писать. Надо торопиться. Не оглянешься, и весна. Тогда будет не до чтения и писания.<br/> Все усиливается головная боль. Я плохо спал. Я видел сумбурный сон, один из тех, которые забываются тут же на месте, по пробуждении. Сон вылетел из головы, в сознании осталась только причина пробуждения. Меня разбудил женский голос, который слышался во сне, которым во сне оглашался воздух. Я запомнил его звук и, воспроизводя его в памяти, перебирал мысленно знакомых женщин, доискиваясь, какая из них могла быть обладательницей этого грудного, тихого от тяжести, влажного голоса. Он не принадлежал ни одной. Я подумал, что, может быть, чрезмерная привычка к Тоне стоит между нами и притупляет у меня слух по отношению к ней. Я попробовал забыть, что она моя жена, и отнес её образ на расстояние, достаточное для выяснения истины. Нет, это был также не её голос. Так это и осталось невыясненным.<br/> Кстати о снах. Принято думать, что ночью снится обыкновенно то, что днем, в бодрствовании, произвело сильнейшее впечатление. У меня как раз обратные наблюдения.<br/> Я не раз замечал, что именно вещи, едва замеченные днем, мысли, не доведенные до ясности, слова, сказанные без души и оставленные без внимания, возвращаются ночью, облеченные в плоть и кровь, и становятся темами сновидений, как бы в возмещение за дневное к ним пренебрежение».

