### 6 {-}

«Ясная морозная ночь. Необычайная яркость и цельность видимого. Земля, воздух, месяц, звезды скованы вместе, склепаны морозом. В парке поперек аллей лежат отчетливые тени деревьев, кажущиеся выточенными и выпуклыми. Все время кажется, будто какие-то черные фигуры в разных местах без конца переходят через дорогу. Крупные звезды синими слюдяными фонарями висят в лесу между ветвями. Мелкими, как летние луга ромашками, усеяно все небо.<br/> Продолжающиеся по вечерам разговоры о Пушкине. Разбирали лицейские стихотворения первого тома. Как много зависело от выбора стихотворного размера!<br/> В стихах с длинными строчками пределом юношеского честолюбия был Арзамас, желание не отстать от старших, пустить дядюшке пыль в глаза мифологизмами, напыщенностью, выдуманной испорченностью и эпикурейством, преждевременным, притворным здравомыслием.<br/> Но едва с подражаний Оссиану или Парни или с «Воспоминаний в Царском Селе» молодой человек нападал на короткие строки «Городка» или «Послания к сестре» или позднейшего кишиневского «К моей чернильнице», или на ритмы «Послания к Юдину», в подростке пробуждался весь будущий Пушкин.<br/> В стихотворение, точно через окно в комнату, врывались с улицы свет и воздух, шум жизни, вещи, сущности. Предметы внешнего мира, предметы обихода, имена существительные, теснясь и наседая, завладевали строчками, вытесняя вон менее определенные части речи. Предметы, предметы, предметы рифмованной колонною выстраивались по краям стихотворения.<br/> Точно этот, знаменитый впоследствии, Пушкинский четырехстопник явился какой-то измерительной единицей русской жизни, её линейной мерой, точно он был меркой, снятой со всего русского существования подобно тому, как обрисовывают форму ноги для сапожной выкройки, или называют номер перчатки для приискания её по руке, впору.<br/> Так позднее ритмы говорящей России, распевы её разговорной речи были выражены в величинах длительности Некрасовским трехдольником и Некрасовской дактилической рифмой».

### 7 {-}

«Как хотелось бы наряду со службой, сельским трудом или врачебной практикой вынашивать что-нибудь остающееся, капитальное, писать какую-нибудь научную работу или что-нибудь художественное.<br/> Каждый родится Фаустом, чтобы все обнять, все испытать, все выразить. О том, чтобы Фаусту быть ученым, позаботились ошибки предшественников и современников. Шаг вперед в науке делается по закону отталкивания, с опровержения царящих заблуждений и ложных теорий.<br/> О том, чтобы Фаусту быть художником, позаботились заразительные примеры учителей. Шаг вперед в искусстве делается по закону притяжения, с подражания, следования и поклонения любимым предтечам.<br/> Что же мешает мне служить, лечить и писать? Я думаю, не лишения и скитания, не неустойчивость и частые перемены, а господствующий в наши дни дух трескучей фразы, получивший такое распространение, — вот это самое: заря грядущего, построение нового мира, светочи человечества. Послушать это, и по началу кажется, — какая широта фантазии, какое богатство!<br/> А на деле оно именно и высокопарно по недостатку дарования.<br/> Сказочно только рядовое, когда его коснется рука гения.<br/> Лучший урок в этом отношении Пушкин. Какое славословие честному труду, долгу, обычаям повседневности! Теперь у нас стало звучать укорительно мещанин, обыватель. Этот упрек предупрежден строками из «Родословной».<br/> «Я мещанин, я мещанин».<br/> И из «Путешествия Онегина»:

