### 9 {-}

«Весна. Готовимся к сельским работам. Стало не до дневника.<br/> А приятно было вести эти записки. Придется отложить их до зимы.<br/> На днях, на этот раз действительно на маслянице, в распутицу, въезжает на санях во двор, по воде и грязи больной крестьянин. Понятно, отказываюсь принять. «Не взыщи, милый, перестал этим заниматься, — ни настоящего подбора лекарств, ни нужных приспособлений». Да разве так отвяжешься. «Помоги. Кожею скудаем. Помилосердствуй. Телесная болезнь».<br/> Что делать? Сердце не камень. Решил принять. «Раздевайся».<br/> Осматриваю. «У тебя волчанка». Вожусь с ним, искоса поглядывая в окно, на бутыль с карболкой. (Боже правый, не спрашивайте, откуда она у меня, и еще кое-что, самое необходимое! Все это — Самдевятов.) Смотрю, — на двор другие сани, с новым больным, как мне кажется в первую минуту. И сваливается, как с облаков, брат Евграф. На некоторое время он поступает в распоряжение дома, Тони, Шурочки, Александра Александровича.<br/> Потом, когда я освобождаюсь, присоединяюсь к остальным.<br/> Начинаются расспросы, — как, откуда? По обыкновению увертывается, уклоняется, ни одного прямого ответа, улыбки, чудеса, загадки.<br/> Он прогостил около двух недель, часто отлучаясь в Юрятин, и вдруг исчез, как сквозь землю провалился. За это время я успел отметить, что он еще влиятельнее Самдевятова, а дела и связи его еще менее объяснимы. Откуда он сам? Откуда его могущество?<br/> Чем он занимается? Перед исчезновением обещал облегчить нам ведение хозяйства, так, чтобы у Тони освобождалось время для воспитания Шуры, а у меня — для занятий медициной и литературой. Полюбопытствовали, что он для этого собирается сделать. Опять отмалчиванье и улыбки. Но он не обманул.<br/> Имеются признаки, что условия жизни у нас действительно переменятся.<br/> Удивительное дело! Это мой сводный брат. Он носит одну со мною фамилию. А знаю я его, собственно говоря, меньше всех.<br/> Вот уже второй раз вторгается он в мою жизнь добрым гением, избавителем, разрешающим все затруднения. Может быть, состав каждой биографии наряду со встречающимися в ней действующими лицами требует еще и участия тайной неведомой силы, лица почти символического, являющегося на помощь без зова, и роль этой благодетельной и скрытой пружины играет в моей жизни мой брат Евграф?»<br/> На этом кончались записи Юрия Андреевича. Больше он их не продолжал.

