### 10 {-}

Юрий Андреевич просматривал в зале Юрятинской городской читальни заказанные книги. Многооконный читальный зал на сто человек был уставлен несколькими рядами длинных столов, узенькими концами к окнам. С наступлением темноты читальня закрывалась. В весеннее время город по вечерам не освещался.<br/> Но Юрий Андреевич и так никогда не досиживал до сумерек и не задерживался в городе позже обеденного времени. Он оставлял лошадь, которую ему давали Микулицыны, на постоялом дворе у Самдевятова, читал все утро, и с середины дня возвращался верхом домой в Варыкино.<br/> До этих наездов в библиотеку Юрий Андреевич редко бывал в Юрятине. У него не было никаких особенных дел в городе. Доктор плохо знал его. И когда на его глазах зал постепенно наполнялся юрятинскими жителями, садившимися то поодаль от него, то совсем по соседству, у Юрия Андреевича являлось чувство, будто он знакомится с городом, стоя на одном из его людных скрещений, и будто в зал стекаются не читающие юрятинцы, а стягиваются дома и улицы, на которых они проживают.<br/> Однако и действительный Юрятин, настоящий и невымышленный, виднелся в окнах зала. У среднего, самого большого окна стоял бак с кипяченою водой. Читающие в виде отдыха выходили покурить на лестницу, окружали бак, пили воду, сливая остатки в полоскательницу, и толпились у окна, любуясь видами города.<br/> Читающих было два рода, старожилы из местной интеллигенции, — их было большинство, — и люди из простого народа.<br/> У первых, среди которых преобладали женщины, бедно одетые, переставшие следить за собой и опустившиеся, были нездоровые, вытянувшиеся лица, обрюзгшие по разным причинам, — от голода, от разлития желчи, от отеков водянки. Это были завсегдатаи читальни, лично-знакомые с библиотечными служащими и чувствовавшие себя здесь, как дома.<br/> Люди из народа с красивыми здоровыми лицами, одетые опрятно, по праздничному, входили в зал смущенно и робко, как в церковь, и появлялись шумнее, чем было принято, не от незнания порядков, а вследствие желания войти совершенно бесшумно и неумения соразмерить свои здоровые шаги и голоса.<br/> Напротив окон в стене было углубление. В этой нише на возвышении, отделенные высокою стойкой от остального зала, занимались своим делом служащие читальни, старший библиотекарь и две его помощницы. Одна из них, сердитая, в шерстяном платке, без конца снимала и напяливала на нос пенсне, руководствуясь, по-видимому, не надобностями зрения, а переменчивостью своих душевных состояний. Другая, в черной шелковой кофте, вероятно, страдала грудью, потому что почти не отнимала носового платка от рта и носа, говорила и дышала в платок.<br/> У библиотечных служащих были такие же опухшие, книзу удлиненные, оплывшие лица, как у половины читающих, та же дряблая, обвислая кожа, землистая с празеленью, цвета соленого огурца и серой плесени, и все они втроем делали попеременно одно и то же, шопотом разъясняли новичкам правила пользования книгами, разбирали билетики с требованиями, выдавали и принимали обратно возвращаемые книги и в промежутках трудились над составлением каких-то годовых отчетов.<br/> И странно, по непонятному сцеплению идей, перед лицом действительного города за окном и воображаемого в зале, а также по какому-то сходству, вызываемому всеобщей мертвенной одутловатостью, точно все заболели зобами, Юрий Андреевич вспомнил недовольную стрелочницу на железнодорожных путях Юрятина в утро их приезда и общую панораму города вдали, и Самдевятова рядом на полу вагона, и его объяснения. И эти объяснения, данные далеко за пределами местности на большом расстоянии, Юрию Андреевичу хотелось связать с тем, что он видел теперь вблизи, в сердцевине картины. Но он не помнил обозначений Самдевятова, и у него ничего не выходило.<br/> Юрий Андреевич сидел в дальнем конце зала, обложившись книгами. Перед ним лежали журналы по местной земской статистике и несколько работ по этнографии края. Он попробовал затребовать еще два труда по истории Пугачева, но библиотекарша в шелковой кофте шопотом через прижатый к губам платок заметила ему, что так много книг не выдают сразу в одни руки и что для получения интересующих его исследований он должен вернуть часть взятых справочников и журналов.

