### 12 {-}

Первое намерение Юрия Андреевича было встать и подойти к Ларисе Федоровне. Но затем чуждые его природе, но установившиеся у него по отношению к ней принужденность и отсутствие простоты взяли верх. Он решил не мешать ей, а также не прерывать собственной работы. Чтобы защитить себя от искушения глядеть в её сторону, он поставил стул боком к столу, почти задом к занимающимся, и углубился в свои книги, держа одну в руке перед собой, а другую развернутою на коленях.<br/> Однако мысли его витали за тридевять земель от предмета его занятий. Вне всякой связи с ними он вдруг понял, что голос, который однажды он слышал зимнею ночью во сне в Варыкине, был голосом Антиповой. Его поразило это открытие и, привлекая внимание окружающих, он порывисто переставил стул в прежнее положение, так чтобы с его места было видно Антипову, и стал смотреть на нее.<br/> Он видел её со спины, вполоборота, почти сзади. Она была в светлой клетчатой блузе, перехваченной кушаком, и читала увлеченно, с самозабвением, как дети, склонив голову немного набок, к правому плечу. Иногда она задумывалась, поднимая глаза к потолку, или, щурясь, заглядывалась куда-то перед собой, а потом снова облокачивалась, подпирала голову рукой, и быстрым размашистым движением записывала карандашом в тетрадь выноски из книги.<br/> Юрий Андреевич проверял и подтверждал свои старые мелюзеевские наблюдения. «Ей не хочется нравиться, — думал он, — быть красивой, пленяющей. Она презирает эту сторону женской сущности и как бы казнит себя за то, что так хороша. И эта гордая враждебность к себе удесятеряет её неотразимость.<br/> Как хорошо все, что она делает. Она читает так, точно это не высшая деятельность человека, а нечто простейшее, доступное животным. Точно она воду носит или чистит картошку».<br/> За этими размышлениями доктор успокоился. Редкий мир сошел ему в душу. Мысли его перестали разбегаться и перескакивать с предмета на предмет. Он невольно улыбнулся. Присутствие Антиповой оказывало на него такое же действие, как на нервную библиотекаршу.<br/> Не заботясь о том, как стоит его стул, и не боясь помех и рассеянии, он час или полтора проработал еще усидчивей и сосредоточенней, чем до прихода Антиповой. Он перерыл высившуюся перед ним гору книг, отобрал самое нужное и даже попутно успел проглотить две встретившиеся в них существенные статьи. Решив удовольствоваться сделанным, он стал собирать книги, чтобы отнести их к столу выдач. Всякие посторонние соображения, порочащие сознание, покинули его. С чистою совестью и совершенно без задних мыслей он подумал, что честно отработанным уроком он заслужил право встретиться со старой доброю знакомою и на законном основании позволить себе эту радость. Но когда, поднявшись, он окинул взглядом читальню, он не обнаружил Антиповой, в зале её больше не было.<br/> На стойке, куда доктор перенес свои тома и брошюры, еще лежала неубранною литература, возвращенная Антиповой. Все это были руководства по марксизму. Вероятно, как бывшая, вновь переопределяющаяся учительница, она своими силами на дому проходила политическую переподготовку.<br/> В книжки заложены были требования Ларисы Федоровны в каталожную. Билетики торчали концами наружу. В них проставлен был адрес Ларисы Федоровны. Его легко можно было прочесть.<br/> Юрий Андреевич списал его, удивившись странности обозначения.<br/> «Купеческая, против дома с фигурами».<br/> Тут же, у кого-то осведомившись, Юрий Андреевич узнал, что выражение «дом с фигурами» в Юрятине настолько же ходячее, как наименование околотков по церковным приходам в Москве или название «у пяти углов» в Петербурге.<br/> Так назывался темно-серый стального цвета дом с кариатидами и статуями античных муз с бубнами, лирами и масками в руках, выстроенный в прошлом столетии купцом театралом для своего домашнего театра. Наследники купца продали дом Купеческой управе, давшей название улице, угол которой дом занимал. По этому дому с фигурами обозначали всю прилегавшую к нему местность. Теперь в доме с фигурами помещался Горком партии, и на стене его косого, спускавшегося под гору и понижавшегося фундамента, где в прежние времена расклеивали театральные и цирковые афиши, теперь вывешивали декреты и постановления правительства.

