### 13 {-}

Был холодный ветреный день начала мая. Потолкавшись по делам в городе, и на минуту заглянув в библиотеку, Юрий Андреевич неожиданно отменил все планы и пошел разыскивать Антипову.<br/> Ветер часто останавливал его в пути, преграждая ему дорогу облаками поднятого песку и пыли. Доктор отворачивался, жмурился, нагибал голову, пережидая, пока пыль пронесется мимо, и отправлялся дальше.<br/> Антипова жила на углу Купеческой и Новосвалочного переулка, против темного, впадавшего в синеву дома с фигурами, теперь впервые увиденного доктором. Дом действительно отвечал своему прозвищу и производил странное, тревожное впечатление.<br/> Он по всему верху был опоясан женскими мифологическими кариатидами в полтора человеческих роста. Между двумя порывами ветра, скрывшими его фасад, доктору на мгновение почудилось, что из дома вышло всё женское население на балкон и, перегнувшись через перила, смотрит на него и на расстилающуюся внизу Купеческую.<br/> К Антиповой было два хода, через парадное с улицы и двором с переулка. Не зная о существовании первого пути, Юрий Андреевич избрал второй.<br/> Когда он свернул из переулка в ворота, ветер взвил к небу землю и мусор со всего двора, завесив двор от доктора. За эту черную завесу с квохтаньем бросились куры из-под его ног, спасаясь от догонявшего их петуха.<br/> Когда облако рассеялось, доктор увидел Антипову у колодца.<br/> Вихрь застиг её с уже набранной водой в обоих ведрах, с коромыслом на левом плече. Она была наскоро повязана косынкой, чтобы не пылить волос, узлом на лоб, «кукушкой», и зажимала коленями подол пузырившегося капота, чтобы ветер не подымал его. Она двинулась было с водою к дому, но остановилась, удержанная новым порывом ветра, который сорвал с её головы платок, стал трепать ей волосы и понес платок к дальнему концу забора, ко всё еще квохтавшим курам.<br/> Юрий Андреевич побежал за платком, поднял его и у колодца подал опешившей Антиповой. Постоянно верная своей естественности, она ни одним возгласом не выдала, как она изумлена и озадачена. У нее только вырвалось:<br/> — Живаго!<br/> — Лариса Федоровна!<br/> — Каким чудом? Какими судьбами?<br/> — Опустите ведра наземь. Я снесу.<br/> — Никогда не сворачиваю с полдороги, никогда не бросаю начатого. Если вы ко мне, пойдемте.<br/> — А то к кому же?<br/> — Кто вас знает.<br/> — Всё же позвольте я переложу коромысло с вашего плеча на свое. Не могу я оставаться в праздности, когда вы трудитесь.<br/> — Подумаешь, труд. Не дам. Лестницу заплещете. Лучше скажите, каким вас ветром занесло? Больше года тут, и все не могли собраться, удосужиться?<br/> — Откуда вы знаете?<br/> — Слухом земля полнится. Да и видела я вас, наконец, в библиотеке.<br/> — Что же вы меня не окликнули?<br/> — Вы не заставите меня поверить, что сами меня не видели.<br/> За слегка покачивавшейся под качавшимися ведрами Ларисой Федоровной доктор прошел под низкий свод. Это были черные сени нижнего этажа. Тут, быстро опустившись на корточки, Лариса Федоровна поставила ведра на земляной пол, высвободила плечо из-под коромысла, выпрямилась и стала утирать руки неизвестно откуда взявшимся крошечным платочком.<br/> — Пойдемте, я вас внутренним ходом на парадную выведу. Там светло. Там подождете. А я воду с черного хода внесу, немного приберу наверху, приоденусь. Видите, какая у нас лестница.<br/> Чугунные ступени с узором. Сверху сквозь них все видно. Старый дом. Тряхнуло его слегка в дни обстрела. Из пушек ведь.<br/> Видите, камни разошлись. Между кирпичами дыры, отверстия. Вот в эту дыру мы с Катенькой квартирный ключ прячем и кирпичом закладываем, когда уходим. Имейте это в виду. Может быть, как-нибудь наведаетесь, меня не застанете, тогда милости просим, отпирайте, входите, будьте как дома. А я тем временем подойду. Вот он и сейчас тут, ключ. Но мне не нужно, я сзади войду и отворю дверь изнутри. Одно горе — крысы. Тьма тьмущая, отбою нет. По головам скачут. Ветхая постройка, стены расшатанные, везде щели. Где могу, заделываю, воюю с ними.<br/> Мало помогает. Может быть, как-нибудь зайдете, поможете?<br/> Вместе забьем полы, плинтусы. А? Ну, оставайтесь на площадке, пораздумайте о чем-нибудь. Я недолго протомлю вас, скоро кликну.<br/> В ожидании зова Юрий Андреевич стал блуждать глазами по облупленным стенам входа и литым чугунным плитам лестницы. Он думал: «В читальне я сравнивал увлеченность её чтения с азартом и жаром настоящего дела, с физической работой. И наоборот, воду она носит, точно читает, легко, без труда. Эта плавность у нее во всем. Точно общий разгон к жизни она взяла давно, в детстве, и теперь всё совершается у нее с разбегу, само собой, с легкостью вытекающего следствия. Это у нее и в линии её спины, когда она нагибается, и в её улыбке, раздвигающей её губы и округляющей подбородок, и в её словах и мыслях».<br/> — Живаго! — раздалось с порога квартиры на верхней площадке. Доктор поднялся по лестнице.

