### 14 {-}

— Дайте руку и покорно следуйте за мной. Тут будут две комнаты, где темно и вещи навалены до потолка. Наткнетесь и ушибетесь.<br/> — Правда, лабиринт какой-то. Я не нашел бы дороги. Почему это? В квартире ремонт?<br/> — О нет, нисколько. Дело не в этом. Квартира чужая. Я даже не знаю, чья. У нас была своя, казенная, в здании гимназии.<br/> Когда гимназию занял жилотдел Юрсовета, меня с дочерью переселили в часть этой, покинутой. Здесь была обстановка старых хозяев. Много мебели. Я в чужом добре не нуждаюсь. Я их вещи составила в эти две комнаты, а окна забелила. Не выпускайте моей руки, а то заблудитесь. Ну так. Направо.<br/> Теперь дебри позади. Вот дверь ко мне. Сейчас станет светлее.<br/> Порог. Не оступитесь.<br/> Когда Юрий Андреевич с провожатой вошел в комнату, в стене против двери оказалось окно. Доктора поразило, что он в нем увидел. Окно выходило на двор дома, на зады соседних и на городские пустыри у реки. На них паслись и точно полами расстегнутых шуб подметали пыль своей длиннорунной шерстью овцы и козы. На них, кроме того, торчала на двух столбах, лицом к окну, знакомая доктору вывеска: «Моро и Ветчинкин. Сеялки. Молотилки».<br/> Под влиянием увиденной вывески доктор с первых же слов стал описывать Ларисе Федоровне свой приезд с семьей на Урал. Он забыл о том отождествлении, которое проводила молва между Стрельниковым и её мужем, и не задумываясь, рассказал о своей встрече с комиссаром в вагоне. Эта часть рассказа произвела особенное впечатление на Ларису Федоровну.<br/> — Вы видали Стрельникова?! — живо переспросила она. — Я пока вам больше ничего не скажу. Но как знаменательно! Просто какое-то предопределение, что вы должны были встретиться. Я вам после когда-нибудь объясню, вы просто ахнете. Если я вас правильно поняла, он произвел на вас скорее благоприятное, чем невыгодное впечатление?<br/> — Да, пожалуй. Он должен был бы меня оттолкнуть. Мы проезжали места его расправ и разрушений. Я ждал встретить карателя солдафона или революционного маниака душителя, и не нашел ни того, ни другого. Хорошо, когда человек обманывает ваши ожидания, когда он расходится с заранее составленным представлением о нем. Принадлежность к типу есть конец человека, его осуждение. Если его не подо что подвести, если он не показателен, половина требующегося от него налицо. Он свободен от себя, крупица бессмертия достигнута им.<br/> — Говорят, он беспартийный.<br/> — Да, мне кажется. Чем он располагает к себе? Это обреченный. Я думаю, он плохо кончит. Он искупит зло, которое он принес. Самоуправцы революции ужасны не как злодеи, а как механизмы без управления, как сошедшие с рельсов машины.<br/> Стрельников такой же сумасшедший, как они, но он помешался не на книжке, а на пережитом и выстраданном. Я не знаю его тайны, но уверен, что она у него есть. Его союз с большевиками случаен. Пока он им нужен, его терпят, им по пути. Но по первом миновении надобности его отшвырнут без сожаления прочь и растопчут, как многих военных специалистов до него.<br/> — Вы думаете?<br/> — Обязательно.<br/> — А нет ли для него спасения? В бегстве, например?<br/> — Куда, Лариса Федоровна? Это прежде, при царях водилось.<br/> А теперь попробуйте.<br/> — Жалко. Своим рассказом вы пробудили во мне сочувствие к нему. А вы изменились. Раньше вы судили о революции не так резко, без раздражения.<br/> — В том-то и дело, Лариса Федоровна, что всему есть мера.<br/> За это время пора было прийти к чему-нибудь. А выяснилось, что для вдохновителей революции суматоха перемен и перестановок единственная родная стихия, что их хлебом не корми, а подай им что-нибудь в масштабе земного шара. Построения миров, переходные периоды это их самоцель. Ничему другому они не учились, ничего не умеют. А вы знаете, откуда суета этих вечных приготовлений? От отсутствия определенных готовых способностей, от неодаренности. Человек рождается жить, а не готовиться к жизни. И сама жизнь, явление жизни, дар жизни так захватывающе нешуточны! Так зачем подменять её ребяческой арлекинадой незрелых выдумок, этими побегами чеховских школьников в Америку? Но довольно. Теперь моя очередь спрашивать. Мы подъезжали к городу в утро вашего переворота.<br/> Вы были тогда в большой переделке?<br/> — О, еще бы! Конечно. Кругом пожары. Сами чуть не сгорели.<br/> Дом, я вам говорила, как покачнуло! На дворе до сих пор неразорвавшийся снаряд у ворот. Грабежи, бомбардировка, безобразия. Как при всякой смене властей. К той поре мы уже были ученые, привычные. Не впервой было. А во время белых что творилось! Убийства из-за угла по мотивам личной мести, вымогательства, вакханалия! Да, но ведь я главного вам не сказала. Галиуллин-то наш! Преважною шишкой тут оказался при чехах. Чем-то вроде генерал-губернатора.<br/> — Знаю. Слышал. Вы с ним видались?<br/> — Очень часто. Скольким я жизнь спасла благодаря ему!<br/> Скольких укрыла! Надо отдать ему справедливость. Держал он себя безупречно, по-рыцарски, не то что всякая мелкая сошка, казачьи там есаулы и полицейские урядники. Но ведь тогда тон задавала именно эта мелкота, а не порядочные люди. Галиуллин мне во многом помог, спасибо ему. Мы ведь старые знакомые. Я часто девочкой на дворе бывала, где он рос. В доме жили рабочие с железной дороги. Я в детстве близко видела бедность и труд. От этого мое отношение к революции иное, чем у вас.<br/> Она ближе мне. В ней для меня много родного. И вдруг он полковником становится, этот мальчик, сын дворника. Или даже белым генералом. Я из штатской среды и плохо разбираюсь в чинах. А по специальности я учительница историчка. Да, так вот как, Живаго. Многим я помогла. Ходила к нему. Вас вспоминали.<br/> У меня ведь во всех правительствах связи и покровители, и при всех порядках огорчения и потери. Это ведь только в плохих книжках живущие разделены на два лагеря и не соприкасаются. А в действительности все так переплетается! Каким непоправимым ничтожеством надо быть, чтобы играть в жизни только одну роль, занимать одно лишь место в обществе, значить всего только одно и то же!<br/> — А, так ты здесь, оказывается?<br/> В комнату вошла девочка лет восьми с двумя мелкозаплетенными косичками. Узко разрезанные, уголками врозь поставленные глаза придавали ей шаловливый и лукавый вид.<br/> Когда она смеялась, она их приподнимала. Она уже за дверью обнаружила, что у матери гость, но показавшись на пороге, сочла нужным изобразить на лице нечаянное удивление, сделала книксен и устремила на доктора немигающий, безбоязненный взгляд рано задумывающегося, одиноко вырастающего ребенка.<br/> — Моя дочь Катенька. Прошу любить и жаловать.<br/> — Вы в Мелюзееве карточки показывали. Как выросла и изменилась!<br/> — Так ты, оказывается, дома? А я думала, — гуляешь. Я и не слышала, как ты вошла.<br/> — Вынимаю из дыры ключ, а там вот такой величины крысина!<br/> Я закричала и в сторону! Думала, умру со страху.<br/> Катенька говорила, корча премилые рожицы, тараща плутовские глаза и растягивая кружком ротик, как вытащенная из воды рыбка.<br/> — Ну ступай к себе. Вот уговорю дядю к обеду остаться, выну кашу из духовой и позову тебя.<br/> — Спасибо, но вынужден отказаться. У нас вследствие моих наездов в город стали в шесть обедать. Я привык не опаздывать, а езды три часа с чем-то, если не все четыре. Потому-то я к вам так рано, — простите, — и скоро подымусь.<br/> — Только полчаса еще.<br/> — С удовольствием.

