### 15 {-}

— А теперь, — откровенность за откровенность.<br/> Стрельников, о котором вы рассказывали, это муж мой Паша, Павел Павлович Антипов, которого я ездила разыскивать на фронт, и в мнимую смерть которого с такою правотой отказывалась верить.<br/> — Я не поражен и подготовлен. Я слышал эту басню и считаю её вздорной. Оттого-то я и забылся до такой степени, что со всей свободой и неосторожностью говорил с вами о нем, точно этих толков не существует. Но эти слухи бессмыслица. Я видел этого человека. Как могут вас связывать с ним? Что между вами общего?<br/> — И всё же это так, Юрий Андреевич. Стрельников это Антипов, муж мой. Я согласна с общим мнением. Катенька это тоже знает и гордится своим отцом. Стрельников это его подставное имя, псевдоним, как у всех революционных деятелей.<br/> Из каких-то соображений он должен жить и действовать под чужим именем.<br/> Вот он Юрятин брал, забрасывал нас снарядами, знал, что мы тут, и ни разу не осведомился, живы ли мы, чтобы не нарушить своей тайны. Это был его долг, разумеется. Если бы он спросил, как ему быть, мы бы ему то же посоветовали. Вы также скажете, что моя неприкосновенность, сносность жилищных условий, предоставленных горсоветом и прочая, — косвенные доказательства его тайной заботы о нас! всё равно вы мне этого не втолкуете. Быть тут рядом и устоять против искушения повидать нас! Это в моем мозгу не укладывается, это выше моего разумения. Это нечто мне недоступное, не жизнь, а какая-то римская гражданская доблесть, одна из нынешних премудростей.<br/> Но я подпадаю под ваше влияние и начинаю петь с вашего голоса.<br/> Я бы этого не хотела. Мы с вами не единомышленники. Что-то неуловимое, необязательное мы понимаем одинаково. Но в вещах широкого значения, в философии жизни лучше будем противниками.<br/> Но вернемся к Стрельникову.<br/> Теперь он в Сибири, и вы правы, до меня тоже доходили сведения о нареканиях на него, от которых у меня холодеет сердце. Теперь он в Сибири, на одном из сильно продвинувшихся наших участков, наносит поражение своему дворовому дружку и впоследствии фронтовому товарищу, бедняжке Галиуллину, от которого не скрыт секрет его имени и моего супружества, и который по неоценимой тонкости никогда не давал мне этого почувствовать, хотя при имени Стрельникова рвет и мечет и выходит из себя. Да, так, значит, теперь он в Сибири.<br/> А когда он тут был (он тут долго пробыл и жил всё время на путях в вагоне, где вы его видели), я всё порывалась столкнуться с ним как-нибудь случайно, непредвиденно. Иногда он в штаб ездил, помещавшийся там, где прежде находилось Военное управление Комуча, войск Учредительного собрания. И странная игра судьбы. Вход в штаб был в том же флигеле, где меня раньше Галиуллин принимал, когда я приходила за других хлопотать. Например, была нашумевшая история в кадетском корпусе, кадеты стали неугодных преподавателей подстерегать и пристреливать под предлогом их приверженности большевизму. Или когда начались преследования и избиения евреев. Кстати. Если мы городские жители и люди умственного труда, половина наших знакомых из их числа. И в такие погромные полосы, когда начинаются эти ужасы и мерзости, помимо возмущения, стыда и жалости, нас преследует ощущение тягостной двойственности, что наше сочувствие наполовину головное, с неискренним неприятным осадком.<br/> Люди, когда-то освободившие человечество от ига идолопоклонства и теперь в таком множестве посвятившие себя освобождению его от социального зла, бессильны освободиться от самих себя, от верности отжившему допотопному наименованию, потерявшему значение, не могут подняться над собою и бесследно раствориться среди остальных, религиозные основы которых они сами заложили и которые были бы им так близки, если бы они их лучше знали.<br/> Наверное, гонения и преследования обязывают к этой бесполезной и гибельной позе, к этой стыдливой, приносящей одни бедствия, самоотверженной обособленности, но есть в этом и внутреннее одряхление, историческая многовековая усталость.<br/> Я не люблю их иронического самоподбадривания, будничной бедности понятий, несмелого воображения. Это раздражает, как разговоры стариков о старости и больных о болезни. Вы согласны?<br/> — Я об этом не думал. У меня есть товарищ, некий Гордон, он тех же взглядов.<br/> — Так вот сюда я Пашу стеречь ходила. В надежде на его приезд или выход. Когда-то во флигеле была канцелярия генерал-губернатора. Теперь на двери табличка: «Бюро претензий». Вы, может быть, видели? Это красивейшее место в городе. Площадь перед дверью вымощена брусчаткой. Перейдя площадь, городской сад. Калина, клен, боярышник. Становилась на тротуаре в кучке просителей и поджидала. Разумеется, не ломилась на прием, не говорила, что жена. Фамилии-то ведь разные. Да и при чем тут голос сердца? У них совсем другие правила. Например, родной его отец Павел Ферапонтович Антипов, бывший политический ссыльный, из рабочих, где-то тут совсем недалеко на тракте в суде работает. В месте своей прежней ссылки. И друг его, Тиверзин. Члены революционного трибунала.<br/> Так что вы думаете? Сын отцу тоже не открывается, и тот принимает это как должное, не обижается. Раз сын зашифрован, значит, нельзя. Это кремни, а не люди. Принципы. Дисциплина.<br/> Да, наконец, если бы и доказала я, что жена, подумаешь, важность! До жен ли было тут? Такие ли были времена? Мировой пролетариат, переделка вселенной, это другой разговор, это я понимаю. А отдельное двуногое вроде жены там какой-то, это так, тьфу, последняя блоха или вошь.<br/> Адъютант обходил, опрашивал. Некоторых впускал. Я не называла фамилии, на вопрос о деле отвечала, что по личному.<br/> Наперед можно было сказать, что штука пропащая, отказ.<br/> Адъютант пожимал плечами, оглядывал подозрительно. Так ни разу и не видала.<br/> И вы думаете, он гнушается нами, разлюбил, не помнит? О, напротив! Я так его знаю! У него от избытка чувств такое задумано! Ему надо все эти военные лавры к нашим ногам положить, чтобы не с пустыми руками вернуться, а во всей славе, победителем! Обессмертить, ослепить нас! Как ребенок!<br/> В комнату снова вошла Катенька, Лариса Федоровна подхватила недоумевающую девочку на руки, стала раскачивать ее, щекотать, целовать и душить в объятиях.

