### 16 {-}

Юрий Андреевич возвращался верхом из города в Варыкино. Он в несчетный раз проезжал эти места. Он привык к дороге, стал нечувствителен к ней, не замечал ее.<br/> Он приближался к лесному перекрестку, где от прямого пути на Варыкино ответвлялась боковая дорога в рыбачью слободу Васильевское на реке Сакме. В месте их раздвоения стоял третий в окрестностях столб с сельскохозяйственной рекламою. Близ этого перепутья застигал доктора обыкновенно закат. Сейчас тоже вечерело.<br/> Прошло более двух месяцев с тех пор, как в одну их своих поездок в город он не вернулся к вечеру домой и остался у Ларисы Федоровны, а дома сказал, что задержался по делу в городе и заночевал на постоялом дворе у Самдевятова. Он давно был на ты с Антиповой и звал её Ларою, а она его — Живаго.<br/> Юрий Андреевич обманывал Тоню и скрывал от нее вещи, всё более серьезные и непозволительные. Это было неслыханно.<br/> Он любил Тоню до обожания. Мир её души, её спокойствие были ему дороже всего на свете. Он стоял горой за её честь, больше чем её родной отец и чем она сама. В защиту её уязвленной гордости он своими руками растерзал бы обидчика. И вот этим обидчиком был он сам.<br/> Дома в родном кругу он чувствовал себя неуличенным преступником. Неведение домашних, их привычная приветливость убивали его. В разгаре общей беседы он вдруг вспоминал о своей вине, цепенел и переставал слышать что-либо кругом и понимать.<br/> Если это случалось за столом, проглоченный кусок застревал в горле у него, он откладывал ложку в сторону, отодвигал тарелку. Слезы душили его. «Что с тобой?» — недоумевала Тоня.<br/> — «Ты, наверное, узнал в городе что-нибудь нехорошее?<br/> Кого-нибудь посадили? Или расстреляли? Скажи мне. Не бойся меня расстроить. Тебе будет легче».<br/> Изменил ли он Тоне, кого-нибудь предпочтя ей? Нет, он никого не выбирал, не сравнивал. Идеи «свободной любви», слова вроде «прав и запросов чувства» были ему чужды. Говорить и думать о таких вещах казалось ему пошлостью. В жизни он не срывал «цветов удовольствия», не причислял себя к полубогам и сверхчеловекам, не требовал для себя особых льгот и преимуществ. Он изнемогал под тяжестью нечистой совести.<br/> Что будет дальше? — иногда спрашивал он себя, и не находя ответа, надеялся на что-то несбыточное, на вмешательство каких-то непредвиденных, приносящих разрешение, обстоятельств.<br/> Но теперь было не так. Он решил разрубить узел силою. Он вез домой готовое решение. Он решил во всем признаться Тоне, вымолить у нее прощение и больше не встречаться с Ларою.<br/> Правда, тут не всё было гладко. Осталось, как ему теперь казалось, недостаточно ясным, что с Ларою он порывает навсегда, на веки вечные. Он объявил ей сегодня утром о желании во всем открыться Тоне и о невозможности их дальнейших встреч, но теперь у него было такое чувство, будто сказал он это ей слишком смягченно, недостаточно решительно.<br/> Ларисе Федоровне не хотелось огорчать Юрия Андреевича тяжелыми сценами. Она понимала, как он мучится и без того. Она постаралась выслушать его новость как можно спокойнее. Их объяснение происходило в пустой, необжитой Ларисой Федоровной комнате прежних хозяев, выходившей на Купеческую. По Лариным щекам текли неощутимые, несознаваемые ею слезы, как вода шедшего в это время дождя по лицам каменных статуй напротив, на доме с фигурами. Она искренне, без напускного великодушия, тихо приговаривала: «Делай, как тебе лучше, не считайся со мною. Я всё переборю». И не знала, что плачет, и не утирала слез.<br/> При мысли о том, что Лариса Федоровна поняла его превратно и что он оставил её в заблуждении, с ложными надеждами, он готов был повернуть и скакать обратно в город, чтобы договорить оставшееся недосказанным, а главное распроститься с ней гораздо горячее и нежнее, в большем соответствии с тем, чем должно быть настоящее расставание на всю жизнь, навеки. Он едва пересилил себя и продолжал путь.<br/> По мере того, как низилось солнце, лес наполнялся холодом и темнотой. В нем запахло лиственною сыростью распаренного веника, как при входе в предбанник. В воздухе, словно поплавки на воде, недвижно распластались висячие рои комаров, тонко нывшие в унисон, все на одной ноте. Юрий Андреевич без числа хлопал их на лбу и шее, и звучным шлепкам ладони по потному телу удивительно отвечали остальные звуки верховой езды: скрип седельных ремней, тяжеловесные удары копыт наотлет, вразмашку, по чмокающей грязи, и сухие лопающиеся залпы, испускаемые конскими кишками. Вдруг вдали, где застрял закат, защелкал соловей.<br/> «Очнись! Очнись!» — звал и убеждал он, и это звучало почти как перед Пасхой: «Душе моя, душе моя! Восстани, что спиши!»<br/> Вдруг простейшая мысль осенила Юрия Андреевича. К чему торопиться? Он не отступит от слова, которое он дал себе самому. Разоблачение будет сделано. Однако, где сказано, что оно должно произойти сегодня? Еще Тоне ничего не объявлено.<br/> Еще не поздно отложить объяснение до следующего раза. Тем временем он еще раз съездит в город. Разговор с Ларой будет доведен до конца, с глубиной и задушевностью, искупающей все страдания. О как хорошо! Как чудно! Как удивительно, что это раньше не пришло ему в голову!<br/> При допущении, что он еще увидит Антипову, Юрий Андреевич обезумел от радости. Сердце часто забилось у него. Он всё снова пережил в предвосхищении.<br/> Бревенчатые закоулки окраины, деревянные тротуары. Он идет к ней. Сейчас, в Новосвалочном, пустыри и деревянная часть города кончится, начнется каменная. Домишки пригорода мелькают, проносятся мимо, как страницы быстро перелистываемой книги, не так, как когда их переворачиваешь указательным пальцем, а как когда мякишем большого по их обрезу с треском прогоняешь их все. Дух захватывает! Вот там живет она, в том конце. Под белым просветом к вечеру прояснившегося дождливого неба. Как он любит эти знакомые домики по пути к ней! Так и подхватил бы их с земли на руки и расцеловал! Эти, поперек крыш нахлобученные одноглазые мезонины! Ягодки отраженных в лужах огоньков и лампад! Под той белой полосой дождливого уличного неба. Там он опять получит в дар из рук творца эту Богом созданную белую прелесть. Дверь отворит в темное закутанная фугура. И обещание её близости, сдержанной, холодной, как светлая ночь севера, ничьей, никому не принадлежащей, подкатит навстречу, как первая волна моря, к которому подбегаешь в темноте по песку берега.<br/> Юрий Андреевич бросил поводья, подался вперед с седла, обнял коня за шею, зарыл лицо в его гриве. Приняв эту нежность за обращение ко всей его силе, конь пошел вскачь.<br/> На плавном полете галопа, в промежутке между редкими, еле заметными прикосновениями коня к земле, которая все время отрывалась от его копыт и отлетала назад, Юрий Андреевич, кроме ударов сердца, бушевавшего от радости, слышал еще какие-то крики, которые, как он думал, мерещились ему.<br/> Близкий выстрел оглушил его. Доктор поднял голову, схватившись за поводья, и натянул их. Конь с разбега сделал раскорякой несколько скачков вбок, попятился и стал садиться на круп, собираясь стать на дыбы.<br/> Впереди дорога разделялась надвое. Около нее в лучах зари горела вывеска «Моро и Ветчинкин. Сеялки, Молотилки». Поперек дороги, преграждая ее, стояли три вооруженных всадника.<br/> Реалист в форменной фуражке и поддевке, перекрещенной пулеметными лентами, кавалерист в офицерской шинели и кубанке и странный, как маскарадный ряженый, толстяк в стеганых штанах, ватнике и низко надвинутой поповской шляпе с широкими полями.<br/> — Ни с места, товарищ доктор, — ровно и спокойно сказал старший между троими, кавалерист в кубанке. — В случае повиновения гарантируем вам полную невредимость. В противном случае, не прогневайтесь, пристрелим. У нас убит фельдшер в отряде. Принудительно вас мобилизуем, как медицинского работника. Слезьте с лошади и передайте поводья младшему товарищу. Напоминаю. При малейшей мысли о побеге церемониться не будем.<br/> — Вы сын Микулицына Ливерий, товарищ Лесных?<br/> — Нет, я его начальник связи Каменнодворский.

