## ЧАСТЬ десятая. НА БОЛЬШОЙ ДОРОГЕ {-}

### 1 {-}

Стояли города, села, станки. Город Крестовоздвиженск, станица Омельчино, Пажинск, Тысяцкое, починок Яглинское, Звонарская слобода, станок Вольное, Гуртовщики, Кежемская заимка, станица Казеево, слобода Кутейный посад, село Малый Ермолай.<br/> Тракт пролегал через них, старый-престарый, самый старый в Сибири, старинный почтовый тракт. Он, как хлеб, разрезал города пополам ножом главной улицы, а села пролетал не оборачиваясь, раскидав далеко позади шпалерами выстроившиеся избы, или выгнув их дугой или крюком внезапного поворота.<br/> В далеком прошлом, до прокладки железной дороги через Ходатское, проносились по тракту почтовые тройки. Тянулись в одну сторону обозы с чаями, хлебом и железом фабричной выделки, а в другую прогоняли под конвоем по этапу пешие партии арестантов. Шагали в ногу, все разом позвякивая железом накандальников, пропащие, отчаянные головушки, страшные, как молнии небесные. И леса шумели кругом, темные, непроходимые.<br/> Тракт жил одной семьей. Знались и роднились город с городом, селенье с селеньем. В Ходатском, на его пересечении с железною дорогой были паровозоремонтные мастерские, механические заведения, подсобные железной дороге, мыкала горе голытьба, скученная в казармах, болела, мерла. Отбывшие каторгу политические ссыльные с техническими познаниями выходили сюда в мастера, оставались тут на поселении.<br/> Вдоль всей этой линии первоначальные Советы давно были свергнуты. Некоторое время держалась власть Сибирского временного правительства, а теперь сменена была по всему краю властью верховного правителя Колчака.

### 2 {-}

На одном из перегонов дорога долго подымалась в гору. Обзор открывавшихся далей все расширялся. Казалось, конца не будет подъему и росту кругозора. И когда лошади и люди уставали и останавливались, чтобы перевести дыхание, подъем кончался.<br/> Впереди под дорожный мост бросалась быстрая река Кежма.<br/> За рекой на еще более крутой высоте показывалась кирпичная стена Воздвиженского монастыря. Дорога низом огибала монастырский косогор и в несколько поворотов между задними дворами окраины пробиралась внутрь города.<br/> Там она еще раз захватывала край монастырского владения на главной площади, куда растворялись железные, крашенные в зеленую краску монастырские ворота. Вратную икону на арке входа полувенком обрамляла надпись золотом: «Радуйся живоносный кресте, благочестия непобедимая победа».<br/> Была зима в исходе, Страстная, конец великого поста. Снег на дорогах чернел, обличая начавшееся таяние, а на крышах был еще бел и нависал плотными высокими шапками.<br/> Мальчишкам, лазившим к звонарям на Воздвиженскую колокольню, дома внизу казались сдвинутыми в кучу маленькими ларцами и ковчежцами. К домам подходили величиной в точечку маленькие черные человечки. Некоторых с колокольни узнавали по движениям. Подходившие читали расклеенный по стенам указ Верховного правителя о призыве в армию трех очередных возрастов.

