### 3 {-}

Ночь принесла много непредвиденного. Стало тепло, необычно для такого времени. Моросил бисерный дождь, такой воздушный, что казалось, он не достигал земли, и дымкой водяной пыли расплывался в воздухе. Но это была видимость. Его теплых, ручьями растекавшихся вод было достаточно, чтобы смыть дочиста снег с земли, которая теперь вся чернела, лоснясь, как от пота.<br/> Малорослые яблони, все в почках, чудесным образом перекидывали из садов ветки через заборы на улицу. С них, недружно перестукиваясь, падали капли на деревянные тротуары.<br/> Барабанный разнобой их раздавался по всему городу.<br/> Лаял и скулил во дворе фотографии до утра посаженный на цепь щенок Томик. Может быть, раздраженная его лаем, на весь город каркала ворона в саду у Галузиных.<br/> В нижней части города купцу Любезнову привезли три телеги клади. Он отказывался её принять, говоря, что это ошибка и он такого товару никогда не заказывал. Ссылаясь на поздний час, молодцы ломовики просились к нему на ночлег. Купец ругался с ними, гнал их прочь и не отворял им ворот. Перебранка их тоже была слышна во всем городе.<br/> В час седьмЫй по церковному, а по общему часоисчислению в час ночи, от самого грузного, чуть шевельнувшегося колокола у Воздвиженья отделилась и поплыла, смешиваясь с темною влагой дождя, волна тихого, темного и сладкого гудения. Она оттолкнулась от колокола, как отрывается от берега и тонет, и растворяется в реке отмытая половодьем земляная глыба.<br/> Это была ночь на Великий четверг, день Двенадцати евангелий. В глубине за сетчатою пеленою дождя двинулись и поплыли еле различимые огоньки и озаренные ими лбы, носы, лица. Говеющие прошли к утрене.<br/> Через четверть часа от монастыря послышались приближающиеся шаги по мосткам тротуара. Это возвращалась к себе домой лавочница Галузина с едва начавшейся заутрени. Она шла неровною походкою, то разбегаясь, то останавливаясь, в накинутом на голову платке и расстегнутой шубе. Ей стало нехорошо в духоте церкви и она вышла на воздух, а теперь стыдилась и сожалела, что не достояла службы и второй год не говеет. Но не в этом была причина её печали. Днем её огорчил расклеенный всюду приказ о мобилизации, действию которого подлежал её бедный дурачок сын Тереша. Она гнала это неудовольствие из головы, но всюду белевший в темноте клок объявления напоминал ей о нем.<br/> Дом был за углом, рукой подать, но на воле ей было лучше.<br/> Ей хотелось побыть на воздухе, её не тянуло домой, в духоту.<br/> Грустные мысли обуревали ее. Если бы она взялась продумать их вслух по порядку, у нее не хватило бы слов и времени до рассвета. А тут, на улице, эти нерадостные соображения налетали целыми комками, и со всеми ими можно было разделаться в несколько минут, в два-три конца от угла монастыря до угла площади.<br/> Светлый праздник на носу, а в доме ни живой души, все разъехались, оставили её одну. А что, разве не одну? Конечно, одну. Воспитанница Ксюша не в счет. Да и кто она? Чужая душа потемки. Может, она друг, может, враг, может, тайная соперница. Перешла она в наследство от первого мужнина брака, Власушкина приемная дочь. А может, не приемная, а незаконная?<br/> А может, и вовсе не дочь, а совсем из другой оперы! Разве в мужскую душу влезешь? А впрочем, ничего не скажешь против девушки. Умная, красивая, примерная. Куда умнее дурачка Терешки и отца приемного.<br/> Вот и одна она на пороге Святой, покинули, разлетелись, кто куда.<br/> Муж Власушка вдоль по тракту пустился новобранцам речи говорить, напутствовать призванных на ратный подвиг. А лучше бы, дурак, о родном сыне позаботился, выгородил от смертельной опасности.<br/> Сын Тереша тоже не утерпел, бросился наутек, накануне великого праздника. В Кутейный посад укатил к родне, развлечься, утешиться после перенесенного. Исключили малого из реального. В половине классов по два года высидел без последствий, а в восьмом не пожалели, выперли.<br/> Ах какая тоска! О Господи! Отчего стало так плохо, просто руки опускаются. Всё из рук валится, не хочется жить! Отчего это так сделалось? В том ли сила, что революция? Нет, ах нет!<br/> От войны это всё. Перебили на войне весь цвет мужской, и осталась одна гниль никчемная, никудышная.<br/> То ли было в батюшкином дому, у отца подрядчика? Отец был непьющий, грамотный, дом был полная чаша. И две сестры Поля и Оля. И так имена складно сходились, такие же обе они были согласные, под пару красавицы. И плотничьи десятники к отцу ходили видные, статные, авантажные. Или вдруг вздумали они, — нужды в доме не знали — вздумали шести шерстей шарфы вязать, затейницы. И что же, такие оказались вязальщицы, по всему уезду шарфы славились. И всё, бывало, радовало густотой и стройностью, — церковная служба, танцы, люди, манеры, даром что из простых была семья, мещане, из крестьянского и рабочего звания. И Россия тоже была в девушках, и были у ней настоящие поклонники, настоящие защитники, не чета нынешним. А теперь сошел со всего лоск, одна штатская шваль адвокатская, да жидова день и ночь без устали слова жует, словами давится.<br/> Власушка со приятели думает замануть назад золотое старое времячко шампанским и добрыми пожеланиями. Да разве так потерянной любви добиваются? Камни надо ворочать для этого, горы двигать, землю рыть!

