### 4 {-}

Галузина уже не раз доходила до привоза, торговой площади Крестовоздвиженска. Отсюда в дом к ней было налево. Но каждый раз она передумывала, поворачивала назад и опять углублялась в прилегавшие к монастырю закоулки.<br/> Привозная площадь была величиной с большое поле. В прежнее время по базарным дням крестьяне уставляли её всю своими телегами. Одним концом она упиралась в конец Еленинской.<br/> Другая сторона по кривой дуге была застроена небольшими домами в один этаж или два. Все они были заняты амбарами, конторами, торговыми помещениями, мастерскими ремесленников.<br/> Здесь, в спокойные времена, бывало, за чтением газеты-копейки восседал на стуле у порога своей широченной, на четыре железных раствора раскидывавшейся двери, грубиян-медведь в очках и длиннополом сюртуке, женоненавистник Брюханов, торговавший кожами, дегтем, колесами, конской сбруей, овсом и сеном.<br/> Здесь на выставке маленького тусклого оконца годами пылилось несколько картонных коробок с парными, убранными лентами и букетиками, свадебными свечами. За оконцем в пустой комнатке без мебели и почти без признаков товара, если не считать нескольких наложенных один на другой вощаных кругов, совершались тысячные сделки на мастику, воск и свечи неведомыми доверенными неведомо где проживавшего свечного миллионера.<br/> Здесь в середине уличного ряда находилась большая в три окна колониальная лавка Галузиных. В ней три раза в день подметали щепяшийся некрашеный пол спитым чаем, который пили без меры весь день приказчики и хозяин. Здесь молодая хозяйка охотно и часто сиживала за кассой. Любимый её цвет был лиловый, фиолетовый, цвет церковного, особо торжественного облачения, цвет нераспустившейся сирени, цвет лучшего бархатного её платья, цвет её столового винного стекла. Цвет счастья, цвет воспоминаний, цвет закатившегося дореволюционного девичества России казался ей тоже светлосиреневым. И она любила сидеть в лавке за кассой, потому что благоухавший крахмалом, сахаром и темнолиловой черносмородинной карамелью в стеклянной банке фиолетовый сумрак помещения подходил под её излюбленный цвет.<br/> Здесь на углу, рядом с лесным складом стоял старый, рассевшийся на четыре стороны, как подержанный рыдван, двухэтажный дом из серого теса. Он состоял из четырёх квартир.<br/> В них было два входа, по обоим углам фасада. Левую половину низа занимал аптекарский магазин Залкинда, правую — контора нотариуса. Над аптекарским магазином проживал старый многосемейный дамский портной Шмулевич. Против портного, над нотариусом, ютилось много квартирантов, о профессиях которых говорили покрывавшие всю входную дверь вывески и таблички.<br/> Здесь производилась починка часов и принимал заказы сапожник.<br/> Здесь держали фотографию компаньоны Жук и Штродах, здесь помещалась гравировальня Каминского.<br/> Ввиду тесноты переполненной квартиры молодые помощники фотографов, ретушер Сеня Магидсон и студент Блажеин соорудили себе род лаборатории во дворе, в проходной конторке дровяного сарая. Они и сейчас там, по-видимому, занимались, судя по злому глазу красного проявительного фонаря, подслеповато мигавшего в оконце конторки. Под этим оконцем и сидел на цепи повизгивавший на всю Еленинскую песик Томка.<br/> «Сбились всем кагалом», — подумала Галузина, проходя мимо серого дома. — «Притон нищеты и грязи». Но тут же она рассудила, что не прав Влас Пахомович в своем юдофобстве. Не велика спица в колеснице эти люди, чтобы что-то значить в судьбах державы. Впрочем, спроси старика Шмулевича, отчего непорядок и смута, изогнется, скривит рожу и скажет, осклабившись: «Лейбочкины штучки».<br/> Ах, но о чем, но о чем она думает, чем забивает голову?<br/> Разве в этом дело? В том ли беда? Беда в городах. Не ими Россия держится. Польстившись на образованность, потянулись за городскими и не вытянули. От своего берега отстали, к чужому не пристали.<br/> А, может быть, наоборот, весь грех в невежестве. Ученый сквозь землю видит, обо всем заранее догадается. А мы когда голову снимут, тогда шапки хватимся. Как в темном лесу. Оно положим не сладко теперь и образованным. Вон из городов погнало бесхлебье. Ну вот и разберись. Сам чорт ногу сломит.<br/> А все-таки то ли дело наша родня деревенская? Селитвины, Шелабурины, Памфил Палых, братья Нестор и Панкрат Модых? Своя рука владыка, себе головы, хозяева. Дворы по тракту новые, залюбуешься. Десятин по пятнадцати засева у каждого, лошади, овцы, коровы, свиньи. Хлеба запасено вперед года на три.<br/> Инвентарь — загляденье. Уборочные машины. Перед ними Колчак лебезит, к себе зазывает, комиссары в лесное ополчение сманивают. С войны пришли в Георгиях, и сразу нарасхват в инструктора. Хушь ты с погонами, хушь без погон. Коли ты человек знающий, везде на тебя спрос. Не пропадешь.<br/> Однако пора домой. Просто неприлично так долго женщине разгуливать. Добро бы у себя в саду. Да там развезло, увязнешь в грязи. Как будто маленько отлегло.<br/> И окончательно запутавшись в рассуждениях и потеряв их нить, Галузина подошла к дому. Но перед тем как переступить его порог, она в минуту топтания перед крыльцом еще охватила мысленным взором много всякой всячины.<br/> Она вспомнила теперешних верховодов в Ходатском, о которых имела близкое представление, политических ссыльных из столиц, Тиверзина, Антипова, анархиста Вдовиченко-Черное знамя, здешнего слесаря Горшеню Бешеного. Всё это были люди себе на уме. Много они на своем веку перебаламутили, что-то верно опять замышляют, готовят. Без этого не могут. Жизнь провели при машинах и сами безжалостные, холодные, как машины. Ходят в коротких, поверх фуфаек, пиджаках, папиросы курят в костяных мундштуках, чтобы чем не заразиться, пьют кипяченую воду.<br/> Ничего не выйдет у Власушки, эти всё перевернут по-своему, всегда поставят на своем.<br/> И она задумалась о себе. Она знала, что она женщина славная и самобытная, хорошо сохранившаяся и умная, не плохой человек.<br/> Ни одно из этих качеств не встречало признания в этой захолустной дыре, да и нигде, может быть. И непристойные куплеты о дуре Сентетюрихе, известные по всему Зауралью, из которых можно было привести только начальные строчки:

