### 5 {-}

Не останавливаясь в передней, она прошла в шубе к себе в спальню. Окна комнаты выходили в сад. Теперь, ночью, нагромождения теней перед окном внутри, и за окном снаружи, почти повторяли друг друга. Обвисавшие мешки оконных драпировок были почти как обвисающие мешки деревьев на дворе, голых и черных, с неясными очертаниями. Тафтяную ночную тьму кончавшейся зимы в саду согревал пробившийся сквозь землю чернолиловый жар надвинувшейся весны. В комнате приблизительно в такое же сочетание вступали два сходных начала, и пыльную духоту плохо выбитых занавесей смягчал и скрашивал темнофиолетовый жар приближающегося праздника.<br/> Богородица на иконе выпрастывала из серебряной ризы оклада узкие, кверху обращенные, смуглые ладони. Она держала в каждой как бы по две начальных и конечных греческих буквы своего византийского наименования: метер неу, Матерь Божия. Вложенная в золотой подлампадник темная, как чернильница, лампада гранатового стекла разбрасывала по ковру спальни звездообразное, зубчиками чашки расщепленное мерцание.<br/> Скидывая платок и шубу, Галузина неловко повернулась и её опять кольнуло в бок и стало подпирать лопатку. Она вскрикнула, испугалась, стала лепетать: «Великое заступление печальным, Богородице чистая, скорая помощница, миру покров», — и заплакала. Потом, выждав, когда боль улеглась, стала раздеваться. Задние крючки воротника и на спинке лифа выскальзывали из-под её рук и зарывались в морщинки дымчатой ткани. Она с трудом нашаривала их.<br/> В комнату вошла разбуженная её приходом воспитанница Ксюша.<br/> — Что же вы в потемках, маменька? Хотите, я лампу принесу?<br/> — Не надо. И так видно.<br/> — Мамочка Ольга Ниловна, дайте я расстегну. Не надо мучиться.<br/> — Не слушаются пальцы, хоть плачь. Не хватило ума у порхатого крючки пришить по-человечески, слепая курица.<br/> Спороть донизу и всей кромкой в рожу.<br/> — Хорошо пели у Воздвиженья. Ночь тихая. Сюда доносило воздухом.<br/> — Пели-то хорошо. Да мне, мать моя, плохо. Опять колотье и тут и тут. Везде. Вот какой грех. Не знаю, что делать.<br/> — Гомеопат Стыдобский вам помогал.<br/> — Всегда советы неисполнимые. Коновал твой гомеопат оказался. Ни в дудочку, ни в сопелочку. Это во-первых. А во-вторых, уехал он. Уехал, уехал. Да не он один. Перед праздником все кинулись из города. Землетрясение ли какое предвидится?<br/> — Ну тогда пленный доктор венгерский хорошо вас пользовал.<br/> — Опять ерунда с горохом. Говорю тебе, никого не осталось, все разбрелись. Очутился Керени Лайош с другими мадьярами за демаркационной линией. Служить заставили голубчика. Взяли в Красную армию.<br/> — Ведь это у вас одна мнительность. Сердечный невроз.<br/> Простое внушение народное здесь чудеса производит. Помните, солдатка шептунья вас с успехом заговаривала. Как рукой снимало. Забыла, как ее, солдатку. Имя забыла.<br/> — Нет, ты положительно считаешь меня темною дурой. Еще чего доброго про меня за глаза Сентетюриху поешь.<br/> — Побойтесь Бога! Грех вам, маменька. Лучше напомните, как солдатку зовут. На языке вертится. Не успокоюсь, пока не вспомню.<br/> — А у нее больше имен, чем юбок. Не знаю, какое тебе.<br/> Кубарихой её зовут и Медведихой, и Злыдарихой. И еще прозвищ с десяток. Нет поблизости и ее. Кончились гастроли, ищи ветра в поле. Заперли рабу Божию в Кежемскую тюрьму. За вытравление плода и порошки какие-то. А она, вишь, чем в остроге скучать, из тюрьмы дала драла куда-то на Дальний Восток. Я ведь тебе говорю, все разбежались. Влас Пахомыч, Тереша, тетя Поля сердце податливое. Честных женщин одни мы с тобой две дуры во всем городе, разве я шучу. И никакой врачебной помощи. Случись что, и конец, никого не докличешься. Говорили, знаменитость из Москвы в Юрятине, профессор, сын самоубийцы купца сибирского.<br/> Пока я раздумывала выписать, двадцать красных кордонов на дороге наставили, чихнуть некуда. А теперь о другом. Ступай спать и я лечь попробую. Тебе студент Блажеин голову кружит.<br/> Зачем отпираться. Всё равно не ухоронишься, покраснела как рак. Трудится твой студент несчастный над карточками во святую ночь, карточки мои проявляет и печатает. Сами не спят и другим спать не дают. Томик у них на весь город заливается. И ворона стерьва раскаркалась у нас на яблоне, видно опять не уснуть мне всю ночь. Да что ты, право, обижаешься, недотрога ты этакая? На то и студенты, чтобы девушкам нравиться.

