## ЧАСТЬ одиннадцатая. ЛЕСНОЕ ВОИНСТВО {-}

### 1 {-}

Юрий Андреевич второй год пропадал в плену у партизан.<br/> Границы этой неволи были очень неотчетливы. Место пленения Юрия Андреевича не было обнесено оградой. Его не стерегли, не наблюдали за ним. Войско партизан все время передвигалось.<br/> Юрий Андреевич совершал переходы вместе с ним. Это войско не отделялось, не отгораживалось от остального народа, через поселения и области которого оно двигалось. Оно смешивалось с ним, растворялось в нем.<br/> Казалось, этой зависимости, этого плена не существует, доктор на свободе, и только не умеет воспользоваться ей.<br/> Зависимость доктора, его плен ничем не отличались от других видов принуждения в жизни, таких же незримых и неосязаемых, которые тоже кажутся чем-то несуществующим, химерой и выдумкой. Несмотря на отсутствие оков, цепей и стражи, доктор был вынужден подчиняться своей несвободе, с виду как бы воображаемой.<br/> Три попытки уйти от партизан кончились его поимкой. Они сошли ему даром, но это была игра с огнем. Больше он их не повторял.<br/> Ему мироволил партизанский начальник Ливерий Микулицын, клал его ночевать в свою палатку, любил его общество. Юрий Андреевич тяготился этой навязанной близостью.

