### 2 {-}

Это был период почти непрерывного отхода партизан на восток. Временами это перемещение являлось частью общего наступательного плана при оттеснении Колчака из Западной Сибири. Временами, при заходе белых партизанам в тыл и попытке их окружения, движение в том же направлении превращалось в отступление. Доктор долго не мог постигнуть этой премудрости.<br/> Городишки и села по тракту, чаще всего параллельно которому, а иногда и по которому совершалось это отхождение, были разные, смотря по переменам военного счастья, белые и красные. Редко по внешнему их виду можно было определить, какая в них власть.<br/> В момент прохождения через эти городки и селения крестьянского ополчения, главным в них становилась именно эта тянущаяся через них армия. Дома по обеим сторонам дороги словно вбирались и уходили в землю, а месящие грязь всадники, лошади, пушки и толпящиеся рослые стрелки в скатках, казалось, вырастали на дороге выше домов.<br/> Однажды в одном таком городке доктор принимал захваченный в виде военной добычи склад английских медикаментов, брошенный при отступлении офицерским каппелевским формированием.<br/> Был темный дождливый день в две краски. Всё освещенное казалось белым, всё неосвещенное — черным. И на душе был такой же мрак упрощения, без смягчающих переходов и полутеней.<br/> В конец разбитая частыми военными передвижениями дорога представляла поток черной слякоти, через который не везде можно было перейти вброд. Улицу переходили в нескольких, очень удаленных друг от друга местах, к которым по обеим сторонам приходилось делать большие обходы. В таких условиях встретил доктор в Пажинске былую железнодорожную попутчицу Пелагею Тягунову.<br/> Она узнала его первая. Он не сразу установил, кто эта женщина со знакомым лицом, бросающая ему через дорогу, как с одной набережной канала на другую, двойственные взгляды, то полные решимости поздороваться с ним, если он её узнает, то выражающие готовность отступить.<br/> Через минуту он всё вспомнил. Вместе с образами переполненного товарного вагона, толпы согнанных на трудовую повинность, их конвойных, и пассажирки с перекинутыми на грудь косами, он увидел своих в середине картины. Подробности позапрошлогоднего семейного переезда с яркостью обступили его.<br/> Родные лица, по которым он истосковался смертельно, живо возникли перед ним.<br/> Кивком головы он подал знак, чтобы Тягунова поднялась немного вверх по улице, к месту, где её переходили по выступающим из грязи камням, сам достиг этого места, переправился к Тягуновой и поздоровался с ней.<br/> Она ему много рассказала. Напомнив ему о незаконно забранном в партию трудобязанных красивом неиспорченном мальчике Васе, ехавшем вместе с ними в одной теплушке, Тягунова описала доктору свою жизнь в деревне Веретенниках у Васиной мамы. Ей было у них очень хорошо. Но деревня колола ей глаза тем, что она в веретенниковском обществе чужая, пришлая.<br/> Ее попрекали сочиненной её якобы близостью с Васею. Пришлось ей уехать, чтобы окончательно её не заклевали. Она поселилась в городе Крестовоздвиженске у сестры Ольги Галузиной. Слухи о виденном будто в Пажинске Притульеве её сюда сманили. Сведения оказались ложными, а она тут застряла на жительство, получив работу.<br/> Тем временем случились несчастия с людьми, милыми её сердцу. Из Веретенников дошли известия, что деревня подверглась военной экзекуции за неповиновение закону о продразверстке. Видимо, дом Брыкиных сгорел и кто-то из Васиной семьи погиб. В Крестовоздвиженске у Галузиных отняли дом и имущество. Зятя посадили в тюрьму или расстреляли.<br/> Племянник пропал без вести. Первое время разорения сестра Ольга бедствовала и голодала, а теперь прислуживает за харчи крестьянской родне в Звонарской слободе.<br/> По случайности Тягунова работала судомойкой в Пажинской аптеке, имущество которой предстояло реквизировать доктору.<br/> Всем кормившимся при аптеке, в том числе Тягуновой, реквизиция приносила разорение. Но не во власти доктора было отменить ее.<br/> Тягунова присутствовала при операции передачи товара.<br/> Телегу Юрия Андреевича подали на задний двор аптеки к дверям склада. Из помещения выносили тюки, оплетенные ивовыми прутьями бутыли и ящики.<br/> Вместе с людьми на погрузку грустно смотрела из стойла тощая и запаршивевшая кляча аптекаря. Дождливый день клонился к вечеру. На небе чуть расчистило. На минуту показалось стиснутое тучами солнце. Оно садилось. Его лучи темной бронзою брызнули во двор, зловеще золотя лужи жидкого навоза. Ветер не шевелил их. Навозная жижа не двигалась от тяжести. Зато налитая дождями вода на шоссе забилась на ветру и рябила киноварью.<br/> А войско шло и шло по краям дороги, обходя и объезжая самые глубокие озера и колдобины. В захваченной партии лекарств оказалась целая банка кокаину, нюханьем которого грешил в последнее время партизанский начальник.

