### 3 {-}

Работ у доктора среди партизан было по горло. Зимой — сыпной тиф, летом — дизентерия и, кроме того, усиливавшееся поступление раненых в боевые дни возобновлявшихся военных действий.<br/> Несмотря на неудачи и преобладающее отступление, ряды партизан непрерывно пополнялись новыми восстающими в местах, по которым проходили крестьянские полчища, и перебежчиками из неприятельского лагеря. За те полтора года, что доктор пробыл у партизан, их войско удесятерилось. Когда на заседании подпольного штаба в Крестовоздвиженске Ливерий Микулицын называл численность своих сил, он преувеличил их примерно вдесятеро. Теперь они достигли указанных размеров.<br/> У Юрия Андреевича были помощники, несколько новоиспеченных санитаров с подходящим опытом. Правою его рукою по лечебной части были венгерский коммунист и военный врач из пленных Керени Лайош, которого в лагере звали товарищем Лающим, и фельдшер хорват Ангеляр, тоже австрийский военнопленный. С первым Юрий Андреевич объяснялся по-немецки, второй, родом из славянских Балкан, с грехом пополам понимал по-русски.

### 4 {-}

По международной конвенции о Красном кресте военные врачи и служащие санитарных частей не имеют права вооруженно участвовать в боевых действиях воюющих. Но однажды доктору против воли пришлось нарушить это правило. Завязавшаяся стычка застала его на поле и заставила разделить судьбу сражающихся и отстреливаться.<br/> Партизанская цепь, в которой застигнутый огнем доктор залег рядом с телеграфистом отряда, занимала лесную опушку. За спиною партизан была тайга, впереди — открытая поляна, оголенное незащищенное пространство, по которому шли белые, наступая.<br/> Они приближались и были уже близко. Доктор хорошо их видел, каждого в лицо. Это были мальчики и юноши из невоенных слоев столичного общества и люди более пожилые, мобилизованные из запаса. Но тон задавали первые, молодежь, студенты первокурсники и гимназисты восьмиклассники, недавно записавшиеся в добровольцы.<br/> Доктор не знал никого из них, но лица половины казались ему привычными, виденными, знакомыми. Одни напоминали ему былых школьных товарищей. Может статься, это были их младшие братья?<br/> Других он словно встречал в театральной или уличной толпе в былые годы. Их выразительные, привлекательные физиономии казались близкими, своими.<br/> Служение долгу, как они его понимали, одушевляло их восторженным молодечеством, ненужным, вызывающим. Они шли рассыпным редким строем, выпрямившись во весь рост, превосходя выправкой кадровых гвардейцев и, бравируя опасностью, не прибегали к перебежке и залеганию на поле, хотя на поляне были неровности, бугорки и кочки, за которыми можно было укрыться.<br/> Пули партизан почти поголовно выкашивали их.<br/> Посреди широкого голого поля, по которому двигались вперед белые, стояло мертвое обгорелое дерево. Оно было обуглено молнией или пламенем костра, или расщеплено и опалено предшествующими сражениями. Каждый наступающий добровольческий стрелок бросал на него взгляды, борясь с искушением зайти за его ствол для более безопасного и выверенного прицела, но пренебрегал соблазном и шел дальше.<br/> У партизан было ограниченное число патронов. Их следовало беречь. Имелся приказ, поддержанный круговым уговором, стрелять с коротких дистанций, из винтовок, равных числу видимых мишеней.<br/> Доктор лежал без оружия в траве и наблюдал за ходом боя.<br/> Все его сочувствие было на стороне героически гибнувших детей.<br/> Он от души желал им удачи. Это были отпрыски семейств, вероятно, близких ему по духу, его воспитания, его нравственного склада, его понятий.<br/> Шевельнулась у него мысль выбежать к ним на поляну и сдаться, и таким образом обрести избавление. Но шаг был рискованный, сопряженный с опасностью.<br/> Пока он добежал бы до середины поляны, подняв вверх руки, его могли бы уложить с обеих сторон, поражением в грудь и спину, свои — в наказание за совершенную измену, чужие — не разобрав его намерений. Он ведь не раз бывал в подобных положениях, продумал все возможности и давно признал эти планы спасения непригодными. И мирясь с двойственностью чувств, доктор продолжал лежать на животе, лицом к поляне и без оружия следил из травы за ходом боя.<br/> Однако созерцать и пребывать в бездействии среди кипевшей кругом борьбы не на живот, а на смерть было немыслимо и выше человеческих сил. И дело было не в верности стану, к которому приковала его неволя, не в его собственной самозащите, а в следовании порядку совершавшегося, в подчинении законам того, что разыгрывалось перед ним и вокруг него. Было против правил оставаться к этому в безучастии. Надо было делать то же, что делали другие. Шел бой. В него и товарищей стреляли. Надо было отстреливаться.<br/> И когда телефонист рядом с ним в цепи забился в судорогах и потом замер и вытянулся, застыв в неподвижности, Юрий Андреевич ползком подтянулся к нему, снял с него сумку, взял его винтовку и, вернувшись на прежнее место, стал разряжать её выстрел за выстрелом.<br/> Но жалость не позволяла ему целиться в молодых людей, которыми он любовался и которым сочувствовал. А стрелять сдуру в воздух было слишком глупым и праздным занятием, противоречившим его намерениям. И выбирая минуты, когда между ним и его мишенью не становился никто из нападающих, он стал стрелять в цель по обгорелому дереву. У него были тут свои приемы.<br/> Целясь и по мере всё уточняющейся наводки незаметно и не до конца усиливая нажим собачки, как бы без расчета когда-нибудь выстрелить, пока спуск курка и выстрел не следовали сами собой как бы сверх ожидания, доктор стал с привычной меткостью разбрасывать вокруг помертвелого дерева сбитые с него нижние отсохшие сучья.<br/> Но о ужас! Как ни остерегался доктор, как бы не попасть в кого-нибудь, то один, то другой наступающий вдвигались в решающий миг между ним и деревом, и пересекали прицельную линию, в момент ружейного разряда. Двух он задел и ранил, а третьему несчастливому, свалившемуся недалеко от дерева, это стоило жизни.<br/> Наконец, белое командование, убедившись в бесполезности попытки, отдало приказ отступить.<br/> Партизан было мало. Их главные силы частью находились на марше, частью отошли в сторону, завязав дело с более крупными силами противника. Отряд не преследовал отступавших, чтобы не выдать своей малочисленности.<br/> Фельдшер Ангеляр привел на опушку двух санитаров с носилками. Доктор велел им заняться ранеными, а сам подошел к лежавшему без движения телефонисту. Он смутно надеялся, что тот, может быть, еще дышит и его можно будет вернуть к жизни.<br/> Но телефонист был мертв. Чтобы в этом удостовериться окончательно, Юрий Андреевич расстегнул на груди у него рубашку и стал слушать его сердце. Оно не работало.<br/> На шее у убитого висела ладанка на снурке. Юрий Андреевич снял ее. В ней оказалась зашитая в тряпицу, истлевшая и стершаяся по краям сгибов бумажка. Доктор развернул её наполовину распавшиеся и рассыпающиеся доли.<br/> Бумажка содержала извлечения из девяностого псалма с теми изменениями и отклонениями, которые вносит народ в молитвы, постепенно удаляющиеся от подлинника от повторения к повторению. Отрывки церковно-славянского текста были переписаны в грамотке по-русски.<br/> В псалме говорится: Живый в помощи Вышнего. В грамотке это стало заглавием заговора: «Живые помощи». Стих псалма: «Не убоишися… от срелы летящия во дни (днем)» превратился в слова ободрения: «Не бойся стрелы летящей войны». «Яко позна имя мое», — говорит псалом. А грамотка: «Поздно имя мое». «С ним есмь в скорби, изму его…» стало в грамотке «Скоро в зиму его».<br/> Текст псалма считался чудодейственным, оберегающим от пуль.<br/> Его в виде талисмана надевали на себя воины еще в прошлую империалистическую войну. Прошли десятилетия и гораздо позднее его стали зашивать в платье арестованные и твердили про себя заключенные, когда их вызывали к следователям на ночные допросы.<br/> От телефониста Юрий Андреевич перешел на поляну к телу убитого им молодого белогвардейца. На красивом лице юноши были написаны черты невинности и всё простившего страдания. «Зачем я убил его?» — подумал доктор.<br/> Он расстегнул шинель убитого и широко раскинул её полы. На подкладке по каллиграфической прописи, старательно и любящею рукою, наверное, материнскою, было вышито: Сережа Ранцевич, — имя и фамилия убитого.<br/> Сквозь пройму Сережиной рубашки вывалились вон и свесились на цепочке наружу крестик, медальон и еще какой-то плоский золотой футлярчик или тавлинка с поврежденной, как бы гвоздем вдавленной крышкой. Футлярчик был полураскрыт. Из него вывалилась сложенная бумажка. Доктор развернул её и глазам своим не поверил. Это был тот же девяностый псалом, но в печатном виде и во всей своей славянской подлинности.<br/> В это время Сережа застонал и потянулся. Он был жив. Как потом обнаружилось, он был оглушен легкой внутренней контузией. Пуля на излете ударилась в стенку материнского амулета, и это спасло его. Но что было делать с лежавшим без памяти?<br/> Озверение воюющих к этому времени достигло предела. Пленных не доводили живыми до места назначения, неприятельских раненых прикалывали на поле.<br/> При текучем составе лесного ополчения, в которое то вступали новые охотники, то уходили и перебегали к неприятелю старые участники, Ранцевича, при строгом сохранении тайны, можно было выдать за нового, недавно примкнувшего союзника.<br/> Юрий Андреевич снял с убитого телефониста верхнюю одежду и с помощью Ангеляра, которого доктор посвятил в свои замыслы, переодел не приходившего в сознание юношу.<br/> Он и фельдшер выходили мальчика. Когда Ранцевич вполне оправился, они отпустили его, хотя он не таил от своих избавителей, что вернется в ряды колчаковских войск и будет продолжать борьбу с красными.

