### 5 {-}

Осенью лагерь партизан стоял в Лисьем отоке, небольшом лесу на высоком бугре, под которым неслась, обтекая его с трех сторон и подрывая берега водороинами, стремительная пенистая речка.<br/> Перед партизанами тут зимовали каппелевцы. Они укрепили лес своими руками и трудами окрестных жителей, а весною его оставили. Теперь в их невзорванных блиндажах, окопах и ходах сообщения разместились партизаны.<br/> Свою землянку Ливерий Аверкиевич делил с доктором. Вторую ночь он занимал его разговорами, не давая ему спать.<br/> — Хотел бы я знать, что теперь поделывает мой достопочтенный родитель, уважаемый фатер — папахен мой.<br/> — Господи, до чего не выношу я этого паяснического тона, — про себя вздыхал доктор. — И ведь вылитый отец!<br/> — Насколько я заключил из наших прошлых бесед, вы Аверкия Степановича достаточно узнали. И, как мне кажется, — довольно неплохого мнения о нем. А, милостивый государь?<br/> — Ливерий Аверкиевич, завтра у нас предвыборная сходка на буйвище. Кроме того, на носу суд над санитарами самогонщиками.<br/> У меня с Лайошем по этому поводу еще не готовы материалы. Мы для этой цели с ним завтра соберемся. А я две ночи не спал.<br/> Отложим собеседование. Помилосердствуйте.<br/> — Нет — всё же, возвращаясь к Аверкию Степановичу. Что вы скажете о старикане?<br/> — У вас еще совсем молодой отец, Ливерий Аверкиевич. Зачем вы так о нем отзываетесь. А теперь я отвечу вам. Я часто говорил вам, что плохо разбираюсь в отдельных градациях социалистического настоя, и особой разницы между большевиками и другими социалистами не вижу. Отец ваш из разряда людей, которым Россия обязана волнениями и беспорядками последнего времени. Аверкий Степанович тип и характер революционный. Так же как и вы, он представитель русского бродильного начала.<br/> — Что это, похвала или порицание?<br/> — Я еще раз прошу отложить спор до более удобного времени.<br/> Кроме того, обращаю ваше внимание на кокаин, который вы опять нюхаете без меры. Вы его самовольно расхищаете из подведомственных мне запасов. Он нам нужен для других целей, не говоря о том, что это яд и я отвечаю за ваше здоровье.<br/> — Опять вы не были на вчерашних занятиях. У вас атрофия общественной жилки, как у неграмотных баб и у заматерелого косного обывателя. Между тем вы — доктор, начитанный и даже, кажется, сами что-то пишете. Объясните, как это вяжется?<br/> — Не знаю, как. Наверное, никак не вяжется, ничего не поделаешь. Я достоин жалости.<br/> — Смирение паче гордости. А чем усмехаться так язвительно, ознакомились бы лучше с программой наших курсов и признали бы свое высокомерие неуместным.<br/> — Господь с вами, Ливерий Аверкиевич! Какое тут высокомерие! Я преклоняюсь перед вашей воспитательной работой.<br/> Обзор вопросов повторяется на повестках. Я читал его. Ваши мысли о духовном развитии солдат мне известны. Я от них в восхищении. Все, что у вас сказано об отношении воина народной армии к товарищам, к слабым, к беззащитным, к женщине, к идее чистоты и чести, это ведь почти то же, что сложило духоборческую общину, это род толстовства, это мечта о достойном существовании, этим полно мое отрочество. Мне ли смеяться над такими вещами?<br/> Но, во-первых, идеи общего совершенствования так, как они стали пониматься с октября, меня не воспламеняют. Во-вторых, это всё еще далеко от существования, а за одни еще толки об этом заплачено такими морями крови, что, пожалуй, цель не оправдывает средства. В-третьих, и это главное, когда я слышу о переделке жизни, я теряю власть над собой и впадаю в отчаяние.<br/> Переделка жизни! Так могут рассуждать люди, хотя может быть и видавшие виды, но ни разу не узнавшие жизни, не почувствовавшие её духа, души ее. Для них существование это комок грубого, не облагороженного их прикосновением материала, нуждающегося в их обработке. А материалом, веществом, жизнь никогда не бывает. Она сама, если хотите знать, непрерывно себя обновляющее, вечно себя перерабатывающее начало, она сама вечно себя переделывает и претворяет, она сама куда выше наших с вами тупоумных теорий.<br/> — И всё же посещение собраний и общение с чудесными, великолепными нашими людьми подняло бы, смею заметить, ваше настроение. Вы не стали бы предаваться меланхолии. Я знаю, откуда она. Вас угнетает, что нас колотят, и вы не видите впереди просвета. Но никогда, друже, не надо впадать в панику.<br/> Я знаю вещи гораздо более страшные, лично касающиеся меня, — временно они не подлежат огласке, — и то не теряюсь. Наши неудачи временного свойства. Гибель Колчака неотвратима.<br/> Попомните мое слово. Увидите. Мы победим. Утешьтесь.<br/> «Нет, это неподражаемо! — думал доктор. — Какое младенчество! Какая близорукость! Я без конца твержу ему о противоположности наших взглядов, он захватил меня силой и силой держит при себе, и он воображает, что его неудачи должны расстраивать меня, а его расчеты и надежды вселяют в меня бодрость. Какое самоослепление! Интересы революции и существование солнечной системы для него одно и то же».<br/> Юрия Андреевича передернуло. Он ничего не ответил и только пожал плечами, нисколько не пытаясь скрыть, что наивность Ливерия переполняет меру его терпения и он насилу сдерживается. От Ливерия это не укрылось.<br/> — Юпитер, ты сердишься, значит ты не прав, — сказал он.<br/> — Поймите, поймите, наконец, что всё это не для меня.<br/> «Юпитер», «не поддаваться панике», «кто сказал а, должен сказать бе», «Мор сделал свое дело, Мор может уйти», — все эти пошлости, все эти выражения не для меня. Я скажу а, а бе не скажу, хоть разорвитесь и лопните. Я допускаю, что вы светочи и освободители России, что без вас она пропала бы, погрязши в нищете и невежестве, и тем не менее мне не до вас и наплевать на вас, я не люблю вас и ну вас всех к чорту.<br/> Властители ваших дум грешат поговорками, а главную забыли, что насильно мил не будешь, и укоренились в привычке освобождать и осчастливливать особенно тех, кто об этом не просит. Наверное, вы воображаете, что для меня нет лучшего места на свете, чем ваш лагерь и ваше общество. Наверное, я еще должен благословлять вас и спасибо вам говорить за свою неволю, за то, что вы освободили меня от семьи, от сына, от дома, от дела, ото всего, что мне дорого и чем я жив.<br/> Дошли слухи о нашествии неизвестной нерусской части в Варыкино. Говорят, оно разгромлено и разграблено.<br/> Каменнодворский этого не отрицает. Будто моим и вашим удалось бежать. Какие-то мифические косоглазые в ватниках и папахах в страшный мороз перешли Рыньву по льду, не говоря худого слова перестреляли всё живое в поселке, и затем сгинули так же загадочно, как появились. Что вам об этом известно? Это правда?<br/> — Чушь. Вымыслы. Подхваченные сплетниками непроверенные бредни.<br/> — Если вы так добры и великодушны, как в ваших наставлениях о нравственном воспитании солдат, отпустите меня на все четыре стороны. Я отправлюсь на розыски своих, относительно которых я даже не знаю, живы ли они, и где они. А если нет, то замолчите, пожалуйста, и оставьте меня в покое, потому что всё остальное неинтересно мне, и я за себя не отвечаю. И, наконец, имею же я, чорт возьми, право просто напросто хотеть спать!<br/> Юрий Андреевич лег ничком на койку, лицом в подушку. Он всеми силами старался не слушать оправдывавшегося Ливерия, который продолжал успокаивать его, что к весне белые будут обязательно разбиты. Гражданская война кончится, настанет свобода, благоденствие и мир. Тогда никто не посмеет держать доктора. А до тех пор надо потерпеть. После всего вынесенного, и стольких жертв, и такого ожидания ждать уже осталось недолго. Да и куда пошел бы теперь доктор. Ради его собственного блага нельзя его сейчас отпускать никуда одного.<br/> «Завел шарманку, дьявол! Заработал языком! Как ему не стыдно столько лет пережевывать одну и ту же жвачку?» — вздыхал про себя и негодовал Юрий Андреевич. «Заслушался себя, златоуст, кокаинист несчастный. Ночь ему не в ночь, ни сна, ни житья с ним, проклятым. О, как я его ненавижу! Видит бог, я когда-нибудь убью его.<br/> О, Тоня, бедная девочка моя! Жива ли ты? Где ты? Господи, да ведь она должна была родить давно! Как прошли твои роды?<br/> Кто у нас, мальчик или девочка? Милые мои все, что с вами?<br/> Тоня, вечный укор мой и вина моя! Лара, мне страшно назвать тебя, чтобы вместе с именем не выдохнуть души из себя.<br/> Господи! Господи! А этот все ораторствует, не унимается, ненавистное, бесчувственное животное! О, я когда-нибудь не выдержу и убью его, убью его».

