### 6 {-}

Бабье лето прошло. Стояли ясные дни золотой осени. В западном углу Лисьего отока из земли выступала деревянная башенка сохранившегося добровольческого блокгауза. Здесь Юрий Андреевич условился встретиться и обсудить с доктором Лайошом, своим ассистентом, кое-какие общие дела. В назначенный час Юрий Андреевич пришел сюда. В ожидании товарища он стал расхаживать по земляной бровке обвалившегося окопа, поднимался и заходил в караулку и смотрел сквозь пустующие бойницы пулеметных гнезд на простиравшиеся за рекою лесные дали.<br/> Осень уже резко обозначила в лесу границу хвойного и лиственного мира. Первый сумрачною, почти черною стеною щетинился в глубине, второй винноогненными пятнами светился в промежутках, точно древний городок с детинцем и златоверхими теремами, срубленный в гуще леса из его бревен.<br/> Земля во рву, под ногами у доктора и в колеях лесной, утренниками прохваченной и протвердевшей дороги была густо засыпана и забита сухим, мелким, как бы стриженым, в трубку свернувшимся листом опавшей ивы. Осень пахла этим горьким коричневым листом и еще множеством других приправ. Юрий Андреевич с жадностью вдыхал сложную пряность ледяного моченого яблока, горькой суши, сладкой сырости и синего сентябрьского угара, напоминающего горелые пары обданного водою костра и свежезалитого пожара.<br/> Юрий Андреевич не заметил, как сзади подошел к нему Лайош.<br/> — Здравствуйте, коллега, — сказал он по-немецки. Они занялись делами.<br/> — У нас три пункта. О самогонщиках, о реорганизации лазарета и аптеки, и третий, по моему настоянию, о лечении душевных болезней амбулаторно, в походных условиях. Может быть, вы не видите в этом необходимости, но по моим наблюдениям мы сходим с ума, дорогой Лайош, и виды современного помешательства имеют форму инфекции, заразы.<br/> — Очень интересный вопрос. Я потом перейду к нему. Сейчас вот о чем. В лагере брожение. Судьба самогонщиков вызывает сочувствие. Многих также волнует судьба семейств, бегущих из деревень от белых. Часть партизан отказывается выступать из лагеря ввиду приближения обоза с их женами, детьми и стариками.<br/> — Да, их придется подождать.<br/> — И всё это перед выборами единого командования, общего над другими, нам не подчиненными отрядами. Я думаю, — единственный кандидат товарищ Ливерий. Группа молодежи выдвигает другого, Вдовиченку. За него стоит чуждое нам крыло, которое примыкало к кругу самогонщиков, дети кулаков и лавочников, колчаковские дезертиры. Они особенно расшумелись.<br/> — Что по-вашему будет с санитарами, варившими и продававшими самогон?<br/> — По-моему их приговорят к расстрелу и помилуют, обратив приговор в условный.<br/> — Однако мы с вами заболтались. Займемся делами.<br/> Реорганизация лазарета. Вот что я хотел бы рассмотреть в первую голову.<br/> — Хорошо. Но я должен сказать, что в вашем предложении о психиатрической профилактике не нахожу ничего удивительного. Я сам того же мнения. Появились и распространяются душевные заболевания самого типического свойства, носящие определенные черты времени, непосредственно вызванные историческими особенностями эпохи. У нас есть солдат царской армии, очень сознательный, с прирожденным классовым инстинктом, Памфил Палых. Он именно на этом помешался, на страхе за своих близких, в случае если он будет убит, а они попадут в руки белых и должны будут за него отвечать. Очень сложная психология. Его домашние, кажется, следуют в беженском обозе и нас догоняют. Недостаточное знание языка мешает мне толком расспросить его. Узнайте у Ангеляра или Каменнодворского. Надо бы осмотреть его.<br/> — Я очень хорошо знаю Палых. Как мне не знать его. Одно время вместе сталкивались в армейском совете. Такой черный, жестокий, с низким лбом. Не понимаю, что вы в нем нашли хорошего. Всегда за крайние меры, строгости, казни. И всегда меня отталкивал. Ладно. Я займусь им.

