### 7 {-}

Был ясный солнечный день. Стояла тихая сухая, как всю предшествующую неделю, погода.<br/> Из глубины лагеря катился смутный, похожий на отдаленный рокот моря, гул большого людского становища. Попеременно слышались шаги слоняющихся по лесу, голоса людей, стук топоров, звон наковален, ржанье лошадей, тявканье собак и пенье петухов. По лесу двигались толпы загорелого, белозубого, улыбающегося люда. Одни знали доктора и кланялись ему, другие, незнакомые с ним, проходили мимо, не здороваясь.<br/> Хотя партизаны не соглашались уходить из Лисьего отока, пока их не нагонят бегущие за ними следом на телегах партизанские семьи, последние были уже в немногих переходах от лагеря и в лесу шли приготовления к скорому снятию стоянки и перенесению её дальше на восток. Что-то чинили, чистили, заколачивали ящики, пересчитывали подводы и осматривали их исправность.<br/> В середине леса была большая вытоптанная прогалина, род кургана или городища, носившая местное название буйвища. На нем обыкновенно созывали войсковые сходки. Сегодня тут тоже было назначено общее сборище для оглашения чего-то важного.<br/> В лесу было много непожелтевшей зелени. В самой глубине он почти весь еще был свеж и зелен. Низившееся послеобеденное солнце пронизывало его сзади своими лучами. Листья пропускали солнечный свет и горели с изнанки зеленым огнем прозрачного бутылочного стекла.<br/> На открытой лужайке близ своего архива начальник связи Каменнодворский жег просмотренный и ненужный бумажный хлам доставшейся ему каппелевской полковой канцелярии вместе с грудами своей собственной, партизанской отчетности. Огонь костра был разложен так, что приходился против солнца. Оно просвечивало сквозь прозрачное пламя, как сквозь зелень леса.<br/> Огня не было видно, и только по зыбившимся слюдяным струям горячего воздуха можно было заключить, что что-то горит и раскаляется.<br/> Там и сям лес пестрел всякого рода спелыми ягодами: нарядными висюльками сердечника, кирпично-бурой дряблой бузиной, переливчатыми бело-малиновыми кистями калины.<br/> Позванивая стеклянными крылышками, медленно проплывали по воздуху рябые и прозрачные, как огонь и лес, стрекозы.<br/> Юрий Андреевич с детства любил сквозящий огнем зари вечерний лес. В такие минуты точно и он пропускал сквозь себя эти столбы света. Точно дар живого духа потоком входил в его грудь, пересекал все его существо, и парой крыльев выходил из-под лопаток наружу. Тот юношеский первообраз, который на всю жизнь складывается у каждого, и потом навсегда служит и кажется ему его внутренним лицом, его личностью, во всей первоначальной силе пробуждался в нем, и заставлял природу, лес, вечернюю зарю и всё видимое преображаться в такое же первоначальное и всеохватывающее подобие девочки. «Лара»! — закрыв глаза, полушептал или мысленно обращался он ко всей своей жизни, ко всей божьей земле, ко всему расстилавшемуся перед ним, солнцем озаренному пространству.<br/> Но очередное, злободневное продолжалось, в России была Октябрьская революция, он был в плену у партизан. И, сам того не замечая, он подошел к костру Каменнодворского.<br/> — Делопроизводство уничтожаете? До сих пор не сожгли?<br/> — Куда там! Этого добра еще надолго хватит.<br/> Доктор носком сапога спихнул и разрознил одну из сваленных куч. Это была телеграфная штабная переписка белых. Смутное предположение, что среди бумажек он натолкнется на имя Ранцевича, мелькнуло у него, но обмануло его. Это было неинтересное собрание прошлогодних шифрованных сводок в невразумительных сокращениях вроде следующего: «Омск генкварверх первому копия Омск наштаокр омского карта сорок верст Енисейского не поступало». Он разгреб ногой другую кучку. Из нее расползлись врозь протоколы старых партизанских собраний. Сверху легла бумажка: «Весьма срочно. Об отпусках.<br/> Перевыборы членов ревизионной комиссии. Текущее. Ввиду недоказанности обвинений учительницы села Игнатодворцы, армейский совет полагает…<br/> В это время Каменнодворский вынул что-то из кармана, подал доктору и сказал:<br/> — Вот расписание вашей медицинской части на случай выступления из лагеря. Телеги с партизанскими семьями уже близко. Лагерные разногласия сегодня будут улажены. Со дня на день можно ждать, что мы снимемся.<br/> Доктор бросил взгляд на бумажку и ахнул.<br/> — Это меньше, чем мне дали в последний раз. А сколько раненых прибавилось! Ходячие и перевязочные пешком пойдут. Но их ничтожное количество. А на чем я тяжелых повезу? А медикаменты, а койки, оборудование!<br/> — Как-нибудь сожмитесь. Надо применяться к обстоятельствам. Теперь о другом. Общая ото всех просьба к вам. Тут есть товарищ, закаленный, проверенный, преданный делу и прекрасный боец. Что-то с ним творится неладное.<br/> — Палых? Мне Лайош говорил.<br/> — Да. Сходите к нему. Исследуйте.<br/> — Что-то психическое?<br/> — Предполагаю. Какие-то бегунчики, как он выражается.<br/> По-видимому, галлюцинации. Бессонница. Головные боли.<br/> — Хорошо. Пойду не откладывая. Сейчас у меня свободное время. Когда начало сходки?<br/> — Думаю, уже собираются. Но на что вам? Видите, вот и я не пошел. Обойдутся без нас.<br/> — Тогда я пойду к Памфилу. Хотя я с ног валюсь, так спать хочу. Ливерий Аверкиевич любит по ночам философствовать, заговорил меня. Как пройти к Памфилу? Где он помещается?<br/> — Молодой березнячок за бутовой ямой знаете? Березовый молоднячок.<br/> — Найду.<br/> — Там на полянке командирские палатки. Мы одну Памфилу предоставили. В ожидании семьи. К нему ведь жена и дети едут в обозе. Да, так вот он в одной из командирских палаток. На правах батальонного. За свои революционные заслуги.

