### 8 {-}

По пути к Памфилу доктор почувствовал, что не в силах идти дальше. Его одолевала усталость. Он не мог победить сонливости, следствия накопленного за несколько ночей недосыпания. Можно было бы вернуться подремать в блиндаж. Но туда Юрий Андреевич боялся идти. Туда каждую минуту мог прийти Ливерий и помешать ему.<br/> Он прилег на одном из незаросших мест в лесу, сплошь усыпанном золотыми листьями, налетевшими на лужайку с окаймлявших её деревьев. Листья легли в клетку, шашками, на лужайку. Так же ложились лучи солнца на их золотой ковер. В глазах рябило от этой двойной, скрещивающейся пестроты. Она усыпляла, как чтение мелкой печати или бормотание чего-нибудь однообразного.<br/> Доктор лег на шелковисто шуршавшую листву, положив подложенную под голову руку на мох, подушкой облегавший бугристые корни дерева. Он мгновенно задремал. Пестрота солнечных пятен, усыпившая его, клетчатым узором покрыла его вытянувшееся на земле тело, и сделала его необнаружимым, неотличимым в калейдоскопе лучей и листьев, точно он надел шапку невидимку.<br/> Очень скоро излишняя сила, с какой он желал сна и нуждался в нем, разбудила его. Прямые причины действуют только в границах соразмерности. Отклонения от меры производят обратное действие. Не находящее отдыха, недремлющее сознание лихорадочно работало на холостом ходу. Обрывки мыслей неслись вихрем и крутились колесом, почти стуча, как испорченная машина. Эта душевная сумятица мучила и сердила доктора.<br/> «Сволочь Ливерий», — возмущался он. «Мало ему, что на свете сейчас сотни поводов рехнуться человеку. Своим пленом, своей дружбой и дурацкой болтовней он без нужды превращает здорового в неврастеника. Я когда-нибудь убью его».<br/> Цветным складывающимся и раскрывающимся лоскутком пролетела с солнечной стороны коричнево-крапчатая бабочка. Доктор сонными глазами проследил за её полетом. Она села на то, что больше всего походило на её окраску, на коричнево-крапчатую кору сосны, с которою она и слилась совершенно неотличимо.<br/> Бабочка незаметно стушевалась на ней, как бесследно терялся Юрий Андреевич для постороннего глаза под игравшей на нем сеткой солнечных лучей и теней.<br/> Привычный круг мыслей овладел Юрием Андреевичем. Он во многих работах по медицине косвенно затрагивал его. О воле и целесообразности, как следствии совершенствующегося приспособления. О мимикрии, о подражательной и предохранительной окраске. О выживании наиболее приспособленных, о том, что, может быть, путь, откладываемый естественным отбором, и есть путь выработки и рождения сознания. Что такое субъект? Что такое объект? Как дать определение их тождества? В размышлениях доктора Дарвин встречался с Шеллингом, а пролетевшая бабочка с современной живописью, с импрессионистическим искусством. Он думал о творении, твари, творчестве и притворстве.<br/> И он снова уснул, и через минуту опять проснулся. Его разбудил тихий заглушенный говор невдалеке. Достаточно было нескольких долетевших слов, чтобы Юрий Андреевич понял, что уславливаются о чем-то тайном, противозаконном. Очевидно, сговаривающиеся не заметили его, не подозревали его соседства.<br/> Если бы он теперь пошевельнулся и выдал свое присутствие, это стоило бы ему жизни. Юрий Андреевич притаился, замер и стал прислушиваться.<br/> Часть голосов он знал. Это была мразь, подонки партизанщины, примазавшиеся к ней мальчишки Санька Пафнуткин, Гоша Рябых, Коська Нехваленых и тянувшийся за ними Терентий Галузин, коноводы всех пакостей и безобразий. Был с ними также Захар Гораздых, тип еще более темный, причастный к делу о варке самогона, но временно не привлеченный к ответу, как выдавший главных виновников. Юрия Андреевича удивило присутствие партизана из «серебряной роты» Сивоблюя, состоявшего в личной охране начальника. По преемственности, шедшей от Разина и Пугачева, этого приближенного, за доверие, оказываемое ему Ливерием, звали атамановым ухом. Он, значит, тоже был участником заговора.<br/> Заговорщики сговаривались с подосланными из неприятельских передовых разъездов. Парламентеров совсем не было слышно, так тихо они уславливались с изменниками, и только по перерывам, наступавшим в шопоте сообщников, Юрий Андреевич догадывался, что теперь говорят представители противника.<br/> Больше всего говорил, поминутно матерясь, хриплым сорванным голосом, пьяница Захар Гораздых. Он был, наверное, главным зачинщиком.<br/> — Теперь, которые прочие, слухай. Главное, — втихаря, потаюхой. Ежели кто ушатнется, съябедничает, видал финку?<br/> Энтою финкой выпущу кишки. Понятно? Теперь нам ни туды, ни сюды, как ни повернись, осиновая вышка. Надо заслужить прощение. Надо исделать штуку, чего свет не видал, из ряду вон. Они требуют его живого, в веревках. Теперь слышишь к энтим лесам подходит ихний сотник Гулевой. (Ему подсказали, как правильно, он не расслышал и поправился: «генерал Галеев».) Такого случая другой раз не будет. Вот ихние делегаты. Они вам всё докажут. Они говорят, беспременно чтобы связанного, живьем. Сами спросите товарищей. Говори, которые прочие. Скажи им что-нибудь, братва.<br/> Стали говорить чужие, подосланные. Юрий Андреевич не мог уловить ни одного слова. По продолжительности общего молчания можно было вообразить обстоятельность сказанного. Опять заговорил Гораздых.<br/> — Слыхали, братцы? Теперь вы сами видите, какое нам попало золотце, какое зельецо. За такого ли платиться? Рази это человек? Это порченый, блаженный вроде как бы недоросток или скитник. Я те дам ржать, Терешка! Ты чего зубы скалишь, содомский грех? Не тебе на зубки говорится. Да. Вроде как во отрочестве скитник. Ты ему поддайся, он тебя в конец обмонашит, охолостит. Какие его речи? Изгоним в среде, долой сквернословие, борьба с пьянством, отношение к женщине. Нешто можно так жить? Окончательное слово. Седни в вечер у речной переправы, где камни сложены. Я его выманю на елань. Кучей навалимся. С ним сладить какая хитрость? Это раз плюнуть. В чем кавычка? Они хочут надо живьем. Связать. А увижу, не выходит по-нашему, сам расправлюсь, пристукну своими руками.<br/> Они своих вышлют, помогут.<br/> Говоривший продолжал развивать план заговора, но вместе с остальными стал удаляться, и доктор перестал их слышать.<br/> «Ведь это они Ливерия, мерзавцы!» — с ужасом и возмущением думал Юрий Андреевич, забывая, сколько раз сам он проклинал своего мучителя и желал ему смерти. — «Негодяи собираются выдать его белым или убить его. Как предотвратить это? Подойти как бы случайно к костру и, никого не называя, поставить в известность Каменнодворского. И как-нибудь предостеречь Ливерия об опасности».<br/> Каменнодворского на прежнем месте не оказалось. Костер догорал. За огнем следил, чтобы он не распространился, помощник Каменнодворского.<br/> Но покушение не состоялось. Оно было пресечено. О заговоре, как оказалось, знали. В этот день он был раскрыт до конца и заговорщики схвачены. Сивоблюй играл тут двойственную роль сыщика и совратителя. Доктору стало еще противнее.

