### 9 {-}

Стало известно, что беженки с детьми уже в двух переходах.<br/> В Лисьем отоке готовились к скорому свиданию с домашними и назначенному вслед за этим снятию лагеря и выступлению. Юрий Андреевич пошел к Памфилу Палых.<br/> Доктор застал его у входа в палатку с топором в руке. Перед палаткой высокой кучей были навалены срубленные на жерди молодые березки. Памфил их еще не обтесал. Одни тут и были срублены и, рухнув всею тяжестью, остриями подломившихся сучьев воткнулись в сыроватую почву. Другие он притащил с недалекого расстояния и наложил сверху. Вздрагивая и покачиваясь на упругих подмятых ветвях, березы не прилегали ни к земле, ни одна к другой. Они как бы руками отбивались от срубившего их Памфила и целым лесом живой зелени загораживали ему вход в палатку.<br/> — В ожидании дорогих гостей, — сказал Памфил, объясняя, чем он занят. — Жене, детишкам будет палатка низка. И заливает в дождь. Хочу кольями верх подпереть. Нарубил слег.<br/> — Ты напрасно, Памфил, думаешь, что семью пустят к тебе жить в палатку. Чтобы невоенным, женщинам и детям в самом войске стоять, где это видано? Их где-нибудь на краю в обозе поставят. В свободное время ходи к ним на свидание, сделай одолжение. А чтобы в воинскую палатку, это едва ли. Да не в этом дело. Говорили, худеешь ты, пить-есть перестал, не спишь?<br/> А на вид ничего. Только немного оброс.<br/> Памфил Палых был здоровенный мужик с черными всклокоченными волосами и бородой, и шишковатым лбом, производившим впечатление двойного, вследствие утолщения лобной кости, подобием кольца или медного обруча обжимавшего его виски. Это придавало Памфилу недобрый и зловещий вид человека косящегося и глядящего исподлобья.<br/> В начале революции, когда по примеру девятьсот пятого года опасались, что и на этот раз революция будет кратковременным событием в истории просвещенных верхов, а глубоких низов не коснется и в них не упрочится, народ всеми силами старались распропагандировать, революционизировать, переполошить, взбаламутить и разъярить.<br/> В эти первые дни люди, как солдат Памфил Палых, без всякой агитации, лютой озверелой ненавистью ненавидевшие интеллигентов, бар и офицерство, казались редкими находками восторженным левым интеллигентам и были в страшной цене. Их бесчеловечность представлялась чудом классовой сознательности, их варварство — образцом пролетарской твердости и революционного инстинкта. Такова была утвердившаяся за Памфилом слава. Он был на лучшем счету у партизанских главарей и партийных вожаков.<br/> Юрию Андреевичу этот мрачный и необщительный силач казался не совсем нормальным выродком вследствие общего своего бездушия, и однообразия и убогости того, что было ему близко и могло его занимать.<br/> — Войдем в палатку, — пригласил Памфил.<br/> — Нет, зачем. И не влезть мне. На воздухе лучше.<br/> — Ладно. Будь по-твоему. И впрямь нора. Побалакаем на должиках (так назвал он сваленные в длину деревья).<br/> И они уселись на ходивших и пружинившихся под ними березовых стволах.<br/> — Скоро, говорят, сказка сказывается, да не скоро дело делается. А и сказку мою не скоро сказать. В три года не выложить. Не знаю, с чего и начать.<br/> Ну, так, что ли. Жили мы с хозяйкой моей. Молодые.<br/> Домовничала она. Не жаловался, крестьянствовал я. Дети. Взяли в солдаты. Погнали фланговым на войну. Ну, война. Что мне об ней тебе рассказывать. Ты её видал, товарищ медврач. Ну, революция. Прозрел я. Открылись глаза у солдата. Не тот немец, который германец, чужой, а который свой. Солдаты мировой революции, штыки в землю, домой с фронта, на буржуёв! И тому подобное. Ты это все сам знаешь, товарищ военный медврач. И так далее. Гражданская. Вливаюсь в партизаны. Теперь много пропущу, а то никогда не кончить. Теперь, долго ли, коротко ли, что я вижу в текущий момент? Он, паразит, с Российского фронта первый и второй Ставропольский снял и первый Оренбургский казачий. Нешто я маленький, не понимаю? Нешто я в армии не служил? Плохо наше дело, военный доктор, наше дело табак. Он что, сволочь, хочет? Он всей этой прорвой на нас навалиться хочет. Он нас хочет взять в кольцо.<br/> Теперь в настоящее время жена у меня, детишки. Ежели он теперь одолеет, куда они от него уйдут? Разве он возьмет в толк, что они всему неповинные, делу сторона? Не станет он на это смотреть. За меня жене руки скрутит, запытает, за меня жену и детей замучит, по суставчикам, по косточкам переберет.<br/> Вот и спи и ешь тут, изволь. Даром что чугунный, сказишься, тронешься.<br/> — Чудак ты, Памфил. Не понимаю тебя. Годы без них обходился, ничего про них не знал, не тужил. А теперь не сегодня-завтра с ними свидишься, и чем радоваться, панихиду по них поешь.<br/> — То прежде, а то теперь, большая разница. Одолевает нас белопогонная гадина. Да не обо мне речь. Мое дело гроб. Туда, видно, мне и дорога. Да ведь своих-то родименьких я с собой на тот свет не возьму. Достанутся они в лапы поганому. Всю-то кровь он из них выпустит по капельке.<br/> — И от этого бегунчики? Говорят, бегунчики тебе какие-то являются.<br/> — Ну ин ладно, доктор. Я не всё тебе сказал. Не сказал главного. Ну, ладно, слушай мою правду колкую, не взыщи, я тебе всё в глаза скажу.<br/> Много я вашего брата в расход пустил, много на мне крови господской, офицерской, и хоть бы что. Числа, имени не помню, вся вода растеклась. Оголец у меня один из головы нейдет, огольца одного я стукнул, забыть не могу. За что я парнишку погубил? Рассмешил, уморил он меня. Со смеху застрелил, сдуру.<br/> Ни за что.<br/> В февральскую было. При Керенском. Бунтовали мы. На чугунке было дело. Послали к нам мальчишку агитаря, языком нас в атаку подымать. Чтобы воевали мы до победного конца. Приехал кадетик нас языком усмирять. Такой щупленький. Был у него лозунг до победного конца. Вскочил он с этим лозунгом на пожарный ушат, пожарный ушат стоял на станции. Вскочил он, значит, на ушат, чтобы оттуда призывать в бой ему повыше, и вдруг крышка у него под ногами подвернись, и он в воду. Оступился. Ой смехота! Я так и покатился. Думал, помру. Ой умора! А у меня в руках ружье. А я хохочу-хохочу, и все тут, хоть ты что хошь. Ровно он меня защекотал. Ну, приложился я и хлоп его на месте. Сам не понимаю, как это вышло. Точно меня кто под руку толкнул.<br/> Вот, значит, и бегунчики мои. По ночам станция мерещится.<br/> Тогда было смешно, а теперь жалко.<br/> — В городе Мелюзееве было, станция Бирючи?<br/> — Запамятовал.<br/> — С зыбушинскими жителями бунтовали?<br/> — Запамятовал.<br/> — Фронт-то какой был? На каком фронте? На Западном?<br/> — Вроде Западный. Все может быть. Запамятовал.

