## ЧАСТЬ двенадцатая. РЯБИНА В САХАРЕ {-}

### 1 {-}

Семьи партизан давно следовали на телегах за общим войском, с детьми и пожитками. За хвостом беженского обоза, совсем позади, гнали несметные гурты скота, преимущественно коров, числом в несколько тысяч голов.<br/> Вместе с женами партизан в лагере появилось новое лицо, солдатка Злыдариха или Кубариха, скотья лекарка, ветеринарка, а в тайне также и ворожея.<br/> Она ходила в шапочке пирожком, надетой набекрень, и гороховой шинели шотландских королевских стрелков из английских обмундировочных поставок Верховному правителю, и уверяла, что эти вещи она перешила из арестантского колпака и халата, и что будто бы красные освободили её из Кежемской централки, где её неизвестно за что держал Колчак.<br/> В это время партизаны стояли на новом месте.<br/> Предполагалось, что это будет стоянка кратковременная, пока не разведают окрестностей и не подыщут места для более долгой и устойчивой зимовки. Но в дальнейшем обстоятельства сложились иначе и заставили партизан остаться тут и зазимовать.<br/> Это новое стойбище ничем не было похоже на недавно покинутый Лисий оток. Это был лес сплошной, непроходимый, таежный. В одну сторону, прочь от дороги и лагеря, ему конца не было. В первые дни, пока войско разбивало новый бивак, и в нем устраивалось на жительство, у Юрия Андреевича было больше досуга. Он углубился в лес в нескольких направлениях с целью его обследования и убедился, как в нем легко заблудиться. Два уголка привлекли его внимание и запомнились ему на этом первом обходе.<br/> У выхода из лагеря и из леса, который был теперь по-осеннему гол и весь виден насквозь, точно в его пустоту растворили ворота, росла одинокая, красивая единственная изо всех деревьев сохранившая неопавшую листву ржавая рыжелистая рябина. Она росла на горке над низким топким кочкарником и протягивала ввысь, к самому небу, в темный свинец предзимнего ненастья плоско расширяющиеся щитки своих твердых разордевшихся ягод. Зимние пичужки с ярким, как морозные зори, оперением, снегири и синицы, садились на рябину, медленно, с выбором клевали крупные ягоды и, закинув кверху головки и вытянув шейки, с трудом их проглатывали.<br/> Какая-то живая близость заводилась между птицами и деревом. Точно рябина всё это видела, долго упрямилась, а потом сдавалась и, сжалившись над птичками, уступала, расстегивалась и давала им грудь, как мамка младенцу. «Что, мол, с вами поделаешь. Ну, ешьте, ешьте меня. Кормитесь». И усмехалась.<br/> Другое место в лесу было еще замечательнее.<br/> Оно было на возвышенности. Возвышенность эта, род шихана, с одного края круто обрывалась. Казалось, внизу под обрывом предполагалось что-то другое, чем наверху, — река или овраг или глухой, некошеной травой поросший луг. Однако под ним было повторение того же самого, что наверху, но только на головокружительной глубине, на другом, вершинами деревьев под ноги ушедшем, опустившемся уровне. Вероятно, это было следствие обвала.<br/> Точно этот суровый, подоблачный, богатырский лес, как-то споткнувшись, весь как есть, полетел вниз и должен был провалиться в тартарары, сквозь землю, но в решительный момент чудом удержался на земле и вот, цел и невредим, виднеется и шумит внизу.<br/> Но не этим, другой особенностью была замечательна лесная возвышенность. Всю её по краю запирали отвесные, ребром стоявшие гранитные глыбы. Они были похожи на плоские отесанные плиты доисторических дольменов. Когда Юрий Андреевич в первый раз попал на эту площадку, он готов был поклясться, что это место с камнями совсем не природного происхождения, а носит следы рук человеческих. Здесь могло быть в древности какое-нибудь языческое капище неизвестных идолопоклонников, место их священнодействий и жертвоприношений.<br/> На этом месте холодным пасмурным утром приведен был в исполнение смертный приговор одиннадцати наиболее виновным по делу о заговоре и двум санитарам самогонщикам.<br/> Человек двадцать преданнейших революции партизан с ядром из особой охраны штаба привели их сюда. Конвой сомкнулся полукольцом вокруг приговоренных и, взяв винтовки на руку, быстрым теснящим шагом затолкал, загнал их в скалистый угол площадки, откуда им не было выхода, кроме прыжков в пропасть.<br/> Допросы, долгое пребывание под стражей и испытанные унижения лишили их человеческого облика. Они обросли, почернели, были измождены и страшны, как призраки.<br/> Их обезоружили в самом начале следствия. Никому не пришло в голову ощупывать их вторично перед казнью. Это представлялось излишней подлостью, глумленьем над людьми перед близкой смертью.<br/> Вдруг шедший рядом с Вдовиченкой друг его и такой же, как он, старый идейный анархист Ржаницкий дал три выстрела по цепи конвойных, целясь в Сивоблюя. Ржаницкий был превосходный стрелок, но рука у него дрожала от волнения, и он промахнулся.<br/> Опять та же деликатность и жалость к былым товарищам не позволила караулу наброситься на Ржаницкого или ответить преждевременным залпом, до общей команды, на его покушение. У Ржаницкого оставалось еще три неистраченных заряда, но, в возбуждении, может быть, забыв о них, и раздосадованный промахом, он шваркнул браунинг о камни. От удара браунинг разрядился в четвертый раз, ранив в ногу приговоренного Пачколю.<br/> Санитар Пачколя вскрикнул, схватился за ногу и упал, часто-часто взвизгивая от боли. Ближайшие к нему Пафнуткин и Гораздых подняли, подхватили его под руки и потащили, чтобы в переполохе его не затоптали товарищи, потому что больше себя никто не помнил. Пачколя шел к каменистому краю, куда теснили смертников, подпрыгивая, хромая, будучи не в состоянии ступить на перешибленную ногу и безостановочно кричал. Его нечеловеческие вопли были заразительны.<br/> Как по сигналу, все перестали владеть собой. Началось нечто невообразимое. Посыпалась ругань, послышались мольбы, жалобы, раздались проклятия.<br/> Подросток Галузин, скинув с головы желтокантовую фуражку peaлиста, которую он еще носил, опустился на колени и так, не вставая с них, ползком пятился дальше в толпе к страшным камням. Он часто часто кланялся до земли конвойным, плакал навзрыд и умолял их полубеспамятно, нараспев:<br/> — Виноват, братцы, помилуйте, больше не буду. Не губите.<br/> Не убивайте. Не жил я еще, молод умирать. Пожить бы мне еще, маменьку, маменьку свою еще один разочек увидать. Простите, братцы, помилуйте. Ноги ваши буду целовать. Воду вам буду на себе возить. Ой беда, беда, — пропал, маменька, маменька.<br/> Из середины причитали, не видно было кто:<br/> — Товарищи миленькие, хорошие! Как же это? Опомнитесь.<br/> Вместе на двух войнах кровь проливали. За одно дело стояли, боролись. Пожалейте, отпустите. Мы добра вашего век не забудем, заслужим, делом докажем. Аль вы оглохли, что не отвечаете? Креста на вас нет!<br/> Сивоблюю кричали:<br/> — Ах ты. Иуда христопродавец! Какие мы против тебя изменники? Сам ты, собака, трижды изменник, чтоб тя удавили!<br/> Царю своему присягал, убил царя своего законного, нам клялся в верности, предал. Целуйся с чортом своим Лесным, пока не предал. Предашь.<br/> Вдовиченко на краю могилы остался верным себе. Высоко держа голову с седыми развевающимися волосами, он громко, во всеуслышание, как коммунар к коммунару, обращался к Ржаницкому.<br/> — Не унижайся, Бонифаций! Твой протест не дойдет до них.<br/> Тебя не поймут эти новые опричники, эти заплечные мастера нового застенка. Но не падай духом. История всё разберет.<br/> Потомство пригвоздит к позорному столбу бурбонов комиссародержавия и их черное дело. Мы умираем мучениками идеи на заре мировой революции. Да здравствует революция духа. Да здравствует всемирная анархия.<br/> Залп двадцати ружей, произведенный по какой-то беззвучной, одними стрелками уловленной команде, скосил половину осужденных, большинство насмерть. Остальных пристрелили вторым залпом. Дольше всех дергался мальчик, Тереша Галузин, но и он в конце концов замер, вытянувшись без движения.

