### 2 {-}

От мысли перенести стан на зиму в другое место, подальше на восток отказались не сразу. Долго продолжались разведки и объезды местности по ту сторону тракта вдоль Вытско-Кежемского водораздела. Ливерий часто отлучался из лагеря в тайгу, оставляя доктора одного.<br/> Но перебираться куда-нибудь было уже поздно и некуда. Это было время наибольших партизанских неудач. Перед окончательным своим крушением белые решили одним ударом раз навсегда покончить с лесными нерегулярными отрядами и общими усилиями всех фронтов окружили их. Партизан теснили со всех сторон. Это было бы для них катастрофой, если бы радиус окружения был меньше. Их спасала неощутимая широта охвата. В преддверии зимы неприятель был не в состоянии стянуть свои фланги по непроходимой беспредельной тайге и обложить крестьянские полчища теснее.<br/> Во всяком случае двигаться куда бы то ни было стало невозможно. Конечно, если бы имелся план перемещения, обещающий определенные военные преимущества, можно было бы пробиться, пройти с боями через черту окружения на новую позицию.<br/> Но такого разработанного замысла не было. Люди выбились из сил. Младшие командиры, и сами упавшие духом, потеряли влияние на подчиненных. Старшие ежевечерне собирались на военный совет, предлагая противоречивые решения.<br/> Надо было оставить поиски другого зимовья и укрепиться на зиму в глубине занятой чащи. В зимнее время по глубокому снегу она становилась непроходимой для противника, плохо снабженного лыжами. Надо было окопаться и заложить большие запасы продовольствия.<br/> Партизан хозяйственник Бисюрин докладывал об остром недостатке муки и картошки. Скота было вдоволь, и Бисюрин предвидел, что зимой главною пищей будет мясо и молоко.<br/> Не хватало зимней одежи. Часть партизан ходила полуодетая.<br/> Передавили всех собак в лагере. Сведущие в скорняжном деле шили партизанам тулупы из собачьих шкур шерстью наружу.<br/> Доктору отказывали в перевозочных средствах. Телеги требовались теперь для более важных надобностей. На последнем переходе самых тяжелых больных несли сорок верст пешком на носилках.<br/> Из медикаментов у Юрия Андреевича оставались только хина, иод и глауберова соль. Иод, требовавшийся для операций и перевязок, был в кристаллах. Их надо было распускать в спирту.<br/> Пожалели об уничтоженном производстве самогона и обратились к наименее виновным, в свое время оправданным винокурам, с поручением починить сломанную перегонную аппаратуру или соорудить новую. Упраздненную фабрикацию самогона снова наладили для врачебных целей В лагере только перемигивались и покачивали головами. Возобновилось пьянство, способствуя развивающемуся развалу в стане.<br/> Выгонку вещества довели почти до ста градусов. Жидкость такой крепости хорошо растворяла кристаллические препараты.<br/> Этим же самогоном, настоенным на хинной корке, Юрий Андреевич позднее, в начале зимы, лечил возобновившиеся с холодами случаи сыпного тифа.

