### 3 {-}

В эти дни доктор видел Памфила Палых с семьею. Жена и дети его всё истекшее лето провели в бегах по пыльным дорогам, под открытым небом. Они были напуганы пережитыми ужасами и ждали новых. Скитания наложили неизгладимый след на них. У жены и троих детей Памфила, сынишки и двух дочерей были светлые, выгоревшие на солнце, льняные волосы и белые, строгие брови на черных, обветренных загорелых лицах. Дети были слишком малы, чтобы носить еще какие-нибудь знаки перенесенного, а с лица матери испытанные потрясения и опасности согнали всякую игру жизни, и оставили только сухую правильность черт, сжатые губы в ниточку, напряженную неподвижность страдания, готового к самозащите.<br/> Памфил любил их всех, в особенности детишек, без памяти, и с ловкостью, изумлявшей доктора, резал им уголком остро отточенного топора игрушки из дерева, зайцев, медведей, петухов.<br/> Когда они приехали, Памфил повеселел, воспрянул духом, стал оправляться. Но вот стало известно, что ввиду вредного влияния, которое оказывало присутствие семей на лагерные настроения, партизан обязательно разлучат с их присными, лагерь освободят от ненужного невоенного придатка и беженский обоз под достаточной охраной поставят табором куда-нибудь подальше на зимовочную стоянку. Толков об этом разделении было больше, чем действительных приготовлений. Доктор в исполнимость этой меры не верил. Но Памфил помрачнел и к нему вернулись его прежние бегунчики.

