### 4 {-}

На пороге зимы несколько причин охватили лагерь долгой полосой беспокойств, неизвестности, грозных и запутанных положений, странных несообразностей.<br/> Белые завершили намеченное обложение повстанцев. Во главе законченной операции стояли генералы Вицин, Квадри и Басалыго.<br/> Эти генералы славились твердостью и непреклонной решительностью. Одни имена их наводили ужас на жен повстанцев в лагере и на мирное население, еще не покинувшее родных мест, и остававшееся в своих деревнях позади, за неприятельскою цепью.<br/> Как уже было сказано, нельзя было предвидеть способов, какими мог бы сузиться круг вражеского оцепления. На этот счет можно было быть спокойными. Однако и оставаться безучастными к окружению не было возможности. Покорность обстоятельствам нравственно усиливала противника. Из ловушки, хотя бы и безопасной, надо было постараться вырваться с целью военной демонстрации.<br/> Для этого выделили большие партизанские силы и сосредоточили их против западной дуги круга. В результате многодневных жарких боев партизаны нанесли неприятелю поражение и, прорвав в этом месте его линию, зашли ему в тыл.<br/> Через свободное пространство, образованное прорывом, открылся доступ в тайгу к повстанцам. На соединение с ними хлынули новые толпы бегущих. Прямой партизанской родней этот приток мирного деревенского люда не исчерпывался. Устрашенное карательными мерами белых всё окрестное крестьянство сдвинулось с места, покидало свои пепелища и естественно тяготело к крестьянскому лесному войску, в котором видело свою защиту.<br/> Но в лагере было стремление избавиться от собственных нахлебников. Партизанам было не до чужих и новых. К бегущим выезжали навстречу, останавливали их в дороге и направляли в сторону, к мельнице в Чилимской росчисти, на речке Чилимке.<br/> Это место на кулиге, образовавшееся из разросшихся при мельнице усадеб, называлось Дворы. В этих Дворах предположено было разбить беженское зимовье и расположить склад выделенного для них продовольствия.<br/> Между тем как принимались такие решения, дела шли своим чередом, и лагерное командование за ними не поспевало.<br/> Одержанная над неприятелем победа осложнилась. Пропустив разбившую их партизанскую группу внутрь, края белые сомкнули и восстановили свою прорванную линию. Забравшемуся к ним в тыл и оторвавшемуся отряду возвращение к своим в тайгу из набега было отрезано. С беженками тоже творилось неладное. В густой непроходимой чаще легко было разминуться. Высланные навстречу не нападали на след бегущих и возвращались, разъехавшись с ними, а женщины стихийным потоком двигались вглубь тайги, совершая по пути чудеса находчивости, валили по обе стороны лес, наводили мосты и гати, прокладывали дороги.<br/> Все это противоречило намерениям лесного штаба и переворачивало вверх дном планы Ливерия и его предначертания.

