### 5 {-}

По этому поводу и бушевал он, стоя вместе со Свиридом, невдалеке от тракта, который на небольшом протяжении проходил в этом месте тайгою. На дороге стояли его начальники споря, резать или нет провода тянувшегося вдоль дороги телеграфа.<br/> Последнее решающее слово принадлежало Ливерию, а он забалтывался с бродягой-звероловом. Ливерий махал им рукой, что он сейчас к ним подойдет, чтобы они подождали, не уходили.<br/> Свирид долгое время не мог перенести осуждения и расстрела Вдовиченки, ни в чем неповинного, кроме только того, что его влияние, соперничавшее с авторитетом Ливерия, вносило раскол в лагерь. Свирид хотел уйти от партизан, чтобы жить опять своей волей на особицу, по-прежнему. Да не тут-то было. Нанялся, продался, — его ждала участь расстрелянных, если бы он теперь ушел от лесных братьев.<br/> Погода была самая ужасная, какую только можно придумать.<br/> Резкий порывистый ветер нес низко над землею рваные клочья туч, черные, как хлопья летящей копоти. Вдруг из них начинал сыпать снег, в судорожной поспешности какого-то белого помешательства.<br/> В минуту даль заволакивалась белым саваном, земля устилалась белой пеленою. В следующую минуту пелена сгорала, истаивала дотла. Выступала черная, как уголь, земля, черное небо, обданное сверху косыми отеками вдалеке пролившихся ливней. Земля воды больше в себя не принимала. В минуты просветления тучи расходились, точно, проветривая небо, наверху растворяли окна, отливающие холодною стеклянной белизной. Стоячая, невпитываемая почвою, вода отвечала с земли такими же распахнутыми оконницами луж и озер, полными того же блеска.<br/> Ненастье дымом скользило по скипидарно-смолистым иглам хвойного бора, не проникая в них, как не проходит вода в клеенку. Телеграфные провода, как бисером, были унизаны каплями дождя. Они висели тесно-тесно, одна к другой и не отрывались.<br/> Свирид был из числа отправленных вглубь тайги навстречу беженкам. Он хотел рассказать начальнику о том, чему он был свидетелем. О бестолочи, получавшейся из взаимостолкновения разных, равно неисполнимых приказов. Об изуверствах, учиняемых наиболее слабою, изверившеюся частью женских скопищ.<br/> Двигавшиеся пешком с узлами, мешками и грудными детьми на себе, лишившиеся молока, сбившиеся с ног и обезумевшие молодые матери бросали детей на дороге, вытрясали муку из мешков и сворачивали назад. Лучше де скорая смерть, чем долгая от голоду. Лучше врагу в руки, чем лесному зверю в зубы.<br/> Другие, наиболее сильные, являли образцы выдержки и храбрости, неведомые мужчинам. У Свирида было еще множество других сообщений. Он хотел предупредить начальника о нависающей над лагерем опасности нового восстания, более угрожающего, чем подавленное, и не находил слов, потому что нетерпеливость Ливерия, раздраженно торопившего его, окончательно лишала его дара речи. А Ливерий поминутно обрывал Свирида не только оттого, что его ждали на дороге и кивали и кричали ему, но потому, что две последние недели к нему сплошь обращались с такими соображениями, и Ливерию всё это было известно.<br/> — Ты не гони меня, товарищ начальник. Я и так не речист. У меня слово в зубах застреват, я словом подавлюсь. Я те что говорю? Сходи в беженский обоз, скажи женкам чалдонским закон да дело. Ишь какая у них непуть пошла. Я те спрашиваю, что у нас, «все на Колчака!» или бабье побоище?<br/> — Короче, Свирид. Видишь, кличут меня. Не накручивай.<br/> — Теперь эта лешачиха дейманка Злыдариха, пес её знат, кто она есть, бабенка. Сказывала, припишите меня, говорит, к скотине бабой ветренянкой…<br/> — Ветеринаркой, Свирид.<br/> — А я про что? Я и говорю, — бабой ветренянкой животные поветрия лечить. А ныне куда там тебе твоя скотина, маткой беспоповкой, столоверкой, оборотилась, коровьи обедни служит, новых женок беженских с пути совращат. Вот, говорит, на себя пеняйте, до чего доводит за красным флаком задрамши подол.<br/> Другой раз не бегайте.<br/> — Я не понимаю, про каких ты беженок? Про наших, партизанских, или еще про каких-нибудь других?<br/> — Вестимо про других. Про новых, чужеместных.<br/> — Так ведь было им распоряжение в сельцо Дворы, на Чилимскую мельницу. Как они здесь очутились?<br/> — Эва, сельцо Дворы. От твоих Дворов одно огнище стоит, погорелище. И мельница и вся кулижка в угольках. Они, пришедши на Чилимку, видят, пустошь голая. Половина ума решилась, воймя воет и назад к белякам. А другие оглобли наоборот и сюда всем обозом.<br/> — Через глухую чащу, через топи?<br/> — А топоры-пилы на что? Им мужиков наших послали, охранять, — пособили. Тридцать, говорят, верст дороги прорубили. С мостами, бестии. Говори после этого, — бабы.<br/> Такое сделают, злыдни, не сообразишь в три дни.<br/> — Хорош гусь! Чего же ты радуешься, кобыла, тридцать верст дороги. Это ведь Вицину и Квадри на руку. Открыли проезд в тайгу. Хоть артиллерию кати.<br/> — Заслон. Заслон. Выставь заслон и дело с концом.<br/> — Бог даст без тебя додумаюсь.

