### 6 {-}

Дни сократились. В пять часов темнело. Ближе к сумеркам Юрий Андреевич перешел тракт в том месте, где на днях Ливерий пререкался со Свиридом. Доктор направлялся в лагерь. Близ поляны и горки, на которой росла рябина, считавшаяся пограничной вехой лагеря, он услышал озорной задорный голос Кубарихи, своей соперницы, как он в шутку звал лекариху-знахарку. Его конкурентка с крикливым подвизгиванием выводила что-то веселое, разухабистое, наверное какие-то частушки. Ее слушали. Ее прерывали взрывы сочувственного смеха, мужского и женского. Потом всё смолкло. Все наверное разошлись.<br/> Тогда Кубариха запела по-другому, про себя и вполголоса, считая себя в полном одиночестве. Остерегаясь оступиться в болото, Юрий Андреевич в потемках медленно пробирался по стежке, огибавшей топкую полянку перед рябиной, и остановился, как вкопанный. Кубариха пела какую-то старинную русскую песню.<br/> Юрий Андреевич не знал ее. Может быть, это была её импровизация?<br/> Русская песня, как вода в запруде. Кажется, она остановилась и не движется. А на глубине она безостановочно вытекает из вешняков и спокойствие её поверхности обманчиво.<br/> Всеми способами, повторениями, параллелизмами, она задерживает ход постепенно развивающегося содержания. У какого-то предела оно вдруг сразу открывается и разом поражает нас. Сдерживающая себя, властвующая над собою тоскующая сила выражает себя так.<br/> Это безумная попытка словами остановить время.<br/> Кубариха наполовину пела, наполовину говорила:

