### 7 {-}

Солдатка Кубариха заговаривала больную корову Палихи, Памфиловой жены Агафьи Фотиевны, в просторечии ФатЕвны. Корову вывели из стада и поставили в кустарник, привязав за рога к дереву. У передних ног коровы на пеньке села хозяйка, у задних — на доильной скамеечке, солдатка ворожея.<br/> Остальное несметное стадо теснилось на небольшой прогалине.<br/> Темный бор отовсюду обступал его стеною высоких, как горы, треугольных елей, которые как бы сидели на земле на толстых задах своих врозь растопыренных нижних ветвей.<br/> В Сибири разводили какую-то одну премированную швейцарскую породу. Почти все в одну масть, черные с белыми подпалинами, коровы не меньше людей были измучены лишениями, долгими переходами, нестерпимой теснотой. Прижатые боками одна к другой, они чумели от давки. В своем одурении они забывали о своем поле и с ревом, по-бычьи налезали одна на другую, с трудом взволакивая вверх тяжелые оттянутые вымена. Покрытые ими телицы, задрав хвост, вырывались из-под них и, обламывая кусты и сучья, убегали в чащу, куда за ними с криком бросались старики пастухи и дети подпаски.<br/> И точно запертые в тесном кружке, который вычерчивали еловые верхушки в зимнем небе, так же бурно и беспорядочно теснились, становились на дыбы и громоздились друг на друга снеговые черно-белые облака над лесною прогалиной.<br/> Стоявшие кучкою поодаль любопытные мешали знахарке. Она недобрым взглядом смеривала их с головы до ног. Но было ниже её достоинства признаваться, что они её стесняют. Самолюбие артистки останавливало ее. И она делала вид, что не замечает их. Доктор наблюдал её из задних рядов, скрытый от нее.<br/> Он в первый рай толком разглядел ее. Она была в неизменной английской своей пилотке и гороховой интервентской шинели с небрежно отогнутыми отворотами. Впрочем, высокомерными чертами глухой страстности, молодо вычернившей глаза и брови этой немолодой женщины, на лице её было ясно написано, до чего ей всё равно, в чем и без чего быть ей.<br/> Но вид Памфиловой жены удивил Юрия Андреевича. Он почти не узнал ее. За несколько дней она страшно постарела. Выпученные глаза её готовы были выйти из впадин. На шее, вытянувшейся оглоблей, бился вздувшийся живчик. Вот что сделали с ней её тайные страхи.<br/> — Не доится, милая, — говорила Агафья. — Думала — межмолок, да нет, давно пора бы молоку, а всё безмолочнеет.<br/> — Чего межмолок. Вон на соске у ней болячка антракс.<br/> Травку дам на сале, смазывать. И само собой, нашепчу.<br/> — Другая моя беда — муж.<br/> — Приворожу, чтоб не гулял. Это можно. Пойдет липнуть, не оторвешь. Третью беду сказывай.<br/> — Да не гуляет. Добро бы гулял. То-то и беда, что наоборот, пуще мочи ко мне, к детям прирос, душой по нас сохнет. Знаю я, что он думает. Вот думает, — лагеря разделят, зашлют нас в разные стороны. Достанемся мы басалыжским, а его с нами не будет. Некому будет за нас постоять. Замучат они нас, нашим мукам порадуются. Знаю я его думы. Как бы чего над собой не сделал.<br/> — Подумаем. Уймем печаль. Третью беду сказывай.<br/> — Да нет ее, третьей. Вот и все они, корова да муж.<br/> — Ну и бедна ж ты бедами, мать! Гляди, как Бог тебя милует. Днем с огнем таких поискать. Две беды горести у бедной головушки, а и одна — жалостливый муж. Что дашь за корову?<br/> Начнем отчитывать.<br/> — А ты что хошь?<br/> — Ситного ковригу да мужа.<br/> Кругом захохотали.<br/> — Смеешься, что ли?<br/> — Ну, коли больно дорого, ковригу скину. На одном муже сойдемся.<br/> Хохот кругом удесятерился.<br/> — Как кличка-то? Да не мужняя, — коровы.<br/> — Красава.<br/> — Тут почитай полстада всё красавы. Ну ладно.<br/> Благословясь.<br/> И она начала заговаривать корову. Вначале её ворожба действительно относилась к скотине. Потом она сама увлеклась и прочла Агафье целое наставление о колдовстве и его применениях. Юрий Андреевич как завороженный слушал эту бредовую вязь, как когда-то при переезде из Европейской России в Сибирь прислушивался к цветистой болтовне возницы Вакха.<br/> Солдатка говорила:<br/> — «Тетка Моргосья, приди к нам в гости. Овторник середу, сыми порчу вереду. Сойди восца с коровья сосца. Стой смирно, Красавка, не переверни лавку. Стой горой, дой рекой. Страфила, страшила, слупи наскрозь струп шелудовый в крапиву брось.<br/> Крепко, что царско, слово знахарско.<br/> Всё надоть знать, Агафьюшка, отказы, наказы, слово обежное, слово обережное. Ты вот смотришь и думаешь, лес. А это нечистая сила с ангельским воинством сошлась, рубятся, вот что ваши с басалыжскими.<br/> Или к примеру погляди, куда я кажу. Не туда смотришь, милая. Ты глазами гляди, а не затылком, и гляди куда я пальцем тыкаю. Во, во. Ты думаешь это что? Думаешь, птица гнездо вить задумала? Как бы не так. Это самая настоящая затея бесовская.<br/> Русалка это дочке своей венок плела. Слышит, люди мимо идут, — бросила. Спугнули. Ночью кончит, доплетет, увидишь.<br/> Или опять это ваше знамя красное. Ты что думаешь? Думаешь, это флак? Ан вот видишь совсем оно не флак, а это девки моровухи манкой малиновый платок, манкой, говорю, а отчего манкой? Молодым ребятам платком махать подмигивать, молодых ребят манить на убой, на смерть, насылать мор. А вы поверили, — флак, сходись ко мне всех стран пролета и беднота.<br/> Теперь все надоть знать, мать Агафья, всё, всё, ну как есть всё. Кака птица, какой камень, кака трава. Теперь к примеру птица это будет птица стратим скворец. Зверь будет барсук.<br/> Теперь к примеру вздумаешь с кем полюбавиться, только скажи. Я тебе кого хошь присушу. Хошь твоего над вами начальника, Лесного вашего, хошь Колчака, хошь Ивана царевича.<br/> Думаешь, хвастаю, вру? А вот и не вру. Ну, смотри, слушай.<br/> Придет зима, пойдет метелица в поле вихри толпить, кружить столбунки. И я тебе в тот столб снеговой, в тот снеговорот нож залукну, вгоню нож в снег по самый черенок, и весь красный в крови из снега выну. Что, видала? Ага? А думала, вру. А откеда, скажи, из завирухи буранной кровь? Ветер ведь эта, воздух, снеговая пыль. А то-то и есть, кума, не ветер это буран, а разведенка оборотенка детеныша ведьменочка своего потеряла, ищет в поле, плачет, не может найтить. И в нее мой нож угодит. Оттого кровь. И я тебе тем ножом чей хошь след выну, вырежу и шолком к подолу пришью. И пойдет хошь Колчак, хошь Стрельников, хошь новый царь какой-нибудь по пятам за тобой, куда ты, туда и он. А ты думала — вру, думала — сходись ко мне всех стран босота и пролета.<br/> Или тоже, например, теперь камни с неба падают, падают яко дождь. Выйдет человек за порог из дому, а на него камни. Или иные видеху конники проезжали верхом по небу, кони копытами задевали за крыши. Или какие кудечники в старину открывали: сия жена в себе заключает зерно или мед или куний мех. И латники тем занагощали плечо, яко отмыкают скрынницу, и вынимали мечом из лопатки у какой пшеницы меру, у какой белку, у какой пчелиный сот».<br/> Иногда встречается на свете большое и сильное чувство. К нему всегда примешивается жалость. Предмет нашего обожания тем более кажется нам жертвою, чем более мы любим. У некоторых сострадание к женщине переходит все мыслимые пределы. Их отзывчивость помещает её в несбыточные, не находимые на свете, в одном воображении существующие положения, и они ревнуют её к окружающему воздуху, к законам природы, к протекшим до нее тысячелетиям.<br/> Юрий Андреевич был достаточно образован, чтобы в последних словах ворожеи заподозрить начальные места какой-то летописи, Новгородской или Ипатьевской, наслаивающимися искажениями превращенные в апокриф. Их целыми веками коверкали знахари и сказочники, устно передавая их из поколения в поколения. Их еще раньше путали и перевирали переписчики.<br/> Отчего же тирания предания так захватила его? Отчего к невразумительному вздору, к бессмыслице небылицы отнесся он так, точно это были положения реальные?<br/> Ларе приоткрыли левое плечо. Как втыкают ключ в секретную дверцу железного, вделанного в шкап тайничка, поворотом меча ей вскрыли лопатку. В глубине открывшейся душевной полости показались хранимые её душою тайны. Чужие посещенные города, чужие улицы, чужие дома, чужие просторы потянулись лентами, раскатывающимися мотками лент, вываливающимися свертками лент наружу.<br/> О как он любил ее! Как она была хороша! Как раз так, как ему всегда думалось и мечталось, как ему было надо! Но чем, какой стороной своей? Чем-нибудь таким, что можно было назвать или выделить в разборе? О нет, о нет! Но той бесподобно простой и стремительной линией, какою вся она одним махом была обведена кругом сверху донизу творцом, и в этом божественном очертании сдана на руки его душе, как закутывают в плотно накинутую простыню выкупанного ребенка.<br/> А теперь где он и что с ним? Лес, Сибирь, партизаны. Они окружены, и он разделит общую участь. Что за чертовщина, что за небывальщина. И опять у Юрия Андреевича стало мутиться в глазах и голове. Всё поплыло перед ним. В это время вместо ожидаемого снега начал накрапывать дождь. Как перекинутый над городской улицей от дома к дому плакат на большущем полотнище, протянулся в воздухе с одной стороны лесной прогалины на другую расплывчатый, во много раз увеличенный призрак одной удивительной боготворимой головы. И голова плакала, а усилившийся дождь целовал и поливал ее.<br/> — Ступай, — говорила ворожея Агафья, — корову твою отчитала я, — выздоровеет. Молись Божьей Матери. Се бо света чертог и книга слова животного.

