### 8 {-}

Шли бои у западных границ тайги. Но она была так велика, что на глаз её это разыгрывалось как бы на далеких рубежах государства, а затерявшийся в её дебрях стан был так многолюден, что сколько ни уходило из него народу в бой, еще больше всегда оставалось и он никогда на пустовал.<br/> Гул отдаленного сражения почти не достигал гущи лагеря.<br/> Вдруг в лесу раскатилось несколько выстрелов. Они последовали один за другим совсем близко, и разом перешли в частую беспорядочную стрельбу. Застигнутые пальбою в том же месте, где она слышалась, шарахнулись врассыпную. Люди из вспомогательных лагерных резервов побежали к своим телегам.<br/> Поднялся переполох. Все стали приводить себя в боевую готовность.<br/> Скоро переполох улегся. Тревога оказалась ложной. Но вот опять к тому месту, где стреляли, стал стекаться народ. Толпа росла. К стоявшим подходили новые.<br/> Толпа окружала лежавший на земле окровавленный человеческий обрубок. Изувеченный еще дышал. У него были отрублены правая рука и левая нога. Было уму непостижимо, как на оставшейся другой руке и ноге несчастный дополз до лагеря. Отрубленная рука и нога страшными кровавыми комками были привязаны к его спине с длинной надписью на дощечке, где между отборными ругательствами было сказано, что это сделано в отплату за зверства такого-то и такого-то красного отряда, к которому партизаны из лесного братства не имели отношения. Кроме того, присовокуплялось, что так будет поступлено со всеми, если к названному в надписи сроку партизаны не покорятся и не сдадут оружия представителям войск Вицынского корпуса.<br/> Истекая кровью, прерывающимся, слабым голосом и заплетающимся языком, поминутно теряя сознание, страдалец-калека рассказал об истязаниях и пытках в тыловых военно-следственных и карательных частях у генерала Вицина.<br/> Повешение, к которому его приговорили, ему заменили, в виде милости, отсечением руки и ноги, чтобы в этом изуродованном виде пустить к партизанам в лагерь для их устрашения. До первых подходов к лагерной сторожевой линии его несли на руках, а потом положили на землю и велели ползти самому, подгоняя его издали выстрелами в воздух.<br/> Замученный еле шевелил губами. Чтобы разобрать его невнятный лепет, его слушали, согнув поясницы и низко наклонившись к нему. Он говорил:<br/> — Берегитесь, братцы. Прорвал он вас.<br/> — Заслон послали. Там великая драка. Задержим.<br/> — Прорыв. Прорыв. Он хочет нечаянно. Я знаю. Ой, не могу, братцы. Видите, кровью исхожу, кровью кашляю. Сейчас кончусь.<br/> — А ты полежи, отдышись. Ты помолчи. Да не давайте говорить ему, ироды. Видите, вредно ему.<br/> — Живого места во мне не оставил, кровопийца, собака.<br/> Кровью, говорит, своей будешь у меня умываться, сказывай, кто ты есть такой. А как я, братцы, это скажу, когда я самый, как есть, настоящий дизельтер. Да. Я от него к вашим перебег.<br/> — Вот ты говоришь, — он. Это кто ж у них над тобой орудовал?<br/> — Ой, братцы, нутро займается. Дайте малость дух переведу.<br/> Сейчас скажу. Атаман Бекешин. Штрезе полковник. Вицинские. Вы тут в лесу ничего не знаете. В городу стон. Из живых людей железо варят. Из живых режут ремни. Втащут за шиворот незнамо куда, тьма кромешная. Обтрогаешься кругом, — клетка, вагон. В клетке человек больше сорока в одном нижнем. И то и знай отпирают клетку, и лапища в вагон. Первого попавшего. Наружу.<br/> Все равно как курей резать. Ей Богу. Кого вешать, кого под шомпола, кого на допрос. Излупцуют в нитку, посыпают раны солью, поливают кипятком. Когда скинет или сделает под себя на низ, заставляют, — жри. А с детишками, а по женскому делу, о Господи!<br/> Несчастный был уже при последнем издыхании. Он не договорил, вскрикнул и испустил дух. Как-то все сразу это поняли, стали снимать шапки, креститься.<br/> Вечером другая новость, куда страшнее этого случая, облетела весь лагерь.<br/> Памфил Палых был в толпе, стоявшей вокруг умиравшего. Он его видел, слышал его рассказ, прочел полную угроз надпись на дощечке.<br/> Его постоянный страх за судьбу своих в случае его смерти охватил его в небывалых размерах. В воображении он уже видел их отданными на медленную пытку, видел их мукою искаженные лица, слышал их стоны и зовы на помощь. Чтобы избавить их от будущих страданий и сократить свои собственные, он в неистовстве тоски сам их прикончил. Он зарубил жену и трех детей тем самым, острым, как бритва, топором, которым резал им, девочкам и любимцу сыну Фленушке, из дерева игрушки.<br/> Удивительно, что он не наложил на себя рук тотчас после совершенного. О чем он думал? Что у него могло быть впереди?<br/> Какие виды, намерения? Это был явный умопомешанный, бесповоротно конченное существование.<br/> Пока Ливерий, доктор и члены армейского совета заседали, обсуждая, что с ним делать, он бродил на свободе по лагерю, с упавшею на грудь головою, ничего не видя мутно-желтыми, глядящими исподлобья глазами. Тупо блуждающая улыбка нечеловеческого, никакими силами непобедимого страдания не сходила с его лица.<br/> Никто не жалел его. Все от него отшатывались. Раздавались голоса, призывавшие к самосуду над ним. Их не поддерживали.<br/> Больше на свете ему было делать нечего. На рассвете он исчез из лагеря, как бежит от самого себя больное водобоязнью бешеное животное.

