### 9 {-}

Давно настала зима. Стояли трескучие морозы. Разорванные звуки и формы без видимой связи появлялись в морозном тумане, стояли, двигались, исчезали. Не то солнце, к которому привыкли на земле, а какое-то другое, подмененное, багровым шаром висело в лесу. От него туго и медленно, как во сне, или в сказке, растекались лучи густого, как мед, янтарно-желтого света, и по дороге застывали в воздухе и примерзали к деревьям.<br/> Едва касаясь земли круглой стопою и пробуждая каждым шагом свирепый скрежет снега, по всем направлениям двигались незримые ноги в валенках, а дополняющие их фигуры в башлыках и полушубках отдельно проплывали по воздуху, как кружащиеся по небесной сфере светила.<br/> Знакомые останавливались, вступали в разговор. Они приближали друг к другу по-банному побагровевшие лица с обледенелыми мочалками бород и усов. Клубы плотного, вязкого пара облаками вырывались из их ртов и по громадности были несоизмеримы со скупыми, как бы отмороженными, словами их немногосложной речи.<br/> На тропинке столкнулись Ливерий с доктором.<br/> — А, это вы? Сколько лет, сколько зим! Вечером прошу в мою землянку. Ночуйте у меня. Тряхнем стариной, поговорим. Есть сообщение.<br/> — Нарочный вернулся? Есть сведения о Варыкине?<br/> — О моих и о ваших в донесении ни звука. Но отсюда я как раз черпаю утешительные выводы. Значит, они вовремя спаслись.<br/> А то бы о них имелось упоминание. Впрочем, обо всем при встрече. Итак, я жду вас.<br/> В землянке доктор повторил свой вопрос:<br/> — Ответьте только, что вы знаете о наших семьях?<br/> — Опять вы не желаете глядеть дальше своего носа. Наши, по-видимому, живы, в безопасности. Но не в них дело.<br/> Великолепнейшие новости. Хотите мяса? Холодная телятина.<br/> — Нет, спасибо. Не разбрасывайтесь. Ближе к делу.<br/> — Напрасно. А я пожую. Цынга в лагере. Люди забыли, что такое хлеб, зелень. Надо было осенью организованнее собирать орехи и ягоды, пока здесь были беженки. Я говорю, дела наши в наивеликолепнейшем состоянии. То, что я всегда предсказывал, совершилось. Лед тронулся. Колчак отступает на всех фронтах.<br/> Это полное, стихийно развивающееся поражение. Видите? Что я говорил? А вы ныли.<br/> — Когда это я ныл?<br/> — Постоянно. Особенно, когда нас теснил Вицин.<br/> Доктор вспомнил недавно минувшую осень, расстрел мятежников, детоубийство и женоубийство Палых, кровавую колошматину и человекоубоину, которой не предвиделось конца.<br/> Изуверства белых и красных соперничали по жестокости, попеременно возрастая одно в ответ на другое, точно их перемножали. От крови тошнило, она подступала к горлу и бросалась в голову, ею заплывали глаза. Это было совсем не нытье, это было нечто совсем другое. Но как было объяснить это Ливерию?<br/> В землянке пахло душистым угаром. Он садился на нёбо, щекотал в носу и горле. Землянка освещалась тонко в листик нащепленными лучинками в треногом железном таганце. Когда одна догорала, обгорелый кончик падал в подставленный таз с водой, и Ливерий втыкал в кольцо новую, зажженную.<br/> — Видите, что жгу. Масло вышло. Пересушили полено. Быстро догорает лучина. Да, цынга в лагере. Вы категорически отказываетесь от телятины? Цынга. А вы что смотрите, доктор?<br/> Нет того, чтобы собрать штаб, осветить положение, прочесть руководству лекцию о цынге и мерах борьбы с нею.<br/> — Не томите, ради Бога. Что вам известно в точности о наших близких?<br/> — Я уже сказал вам, что никаких точных сведений о них нет.<br/> Но я не договорил того, что знаю из последних общевоенных сводок. Гражданская война окончена. Колчак разбит на голову.<br/> Красная армия гонит его по железнодорожной магистрали на восток, чтобы сбросить в море. Другая часть Красной армии спешит на соединение с нами, чтобы общими силами заняться уничтожением его многочисленных, повсюду рассеянных тылов. Юг России очищен. Что же вы не радуетесь? Вам этого мало?<br/> — Не правда. Я радуюсь. Но где наши семьи?<br/> — В Варыкине их нет, и это большое счастье. Хотя летние легенды Каменнодворского, как я предполагал, не подтвердились, — помните эти глупые слухи о нашествии в Варыкино какой-то загадочной народности? — но поселок совершенно опустел. Там, видимо, что-то было все-таки, и очень хорошо, что обе семьи заблаговременно оттуда убрались. Будем верить, что они спасены. Таковы, по словам моей разведки, предположения немногих оставшихся.<br/> — А Юрятин? Что там? В чьих он руках?<br/> — Тоже нечто несообразное. Несомненная ошибка.<br/> — А именно?<br/> — Будто в нем еще белые. Это безусловный абсурд, явная невозможность. Сейчас я вам это докажу с очевидностью.<br/> Ливерий вставил в светец новую лучину и, сложив мятую трепаную двухверстку нужными делениями наружу, а лишние края подвернув внутрь, стал объяснять по карте с карандашом в руке.<br/> — Смотрите. На всех этих участках белые отброшены назад.<br/> Вот тут, тут и тут по всему кругу. Вы следите внимательно?<br/> — Да.<br/> — Их не может быть в Юрятинском направлении. Иначе, при отрезанных коммуникациях, они неизбежно попадают в мешок.<br/> Этого не могут не понимать их генералы, как бы они ни были бездарны. Вы надели шубу? Куда вы?<br/> — Простите, я на минуту. Я вернусь сейчас. Тут начажено махоркой и лучинной гарью. Мне нехорошо. Я отдышусь на воздухе.<br/> Поднявшись из землянки наружу, доктор смел рукавицей снег с толстой колоды, положенной вдоль для сидения у выхода. Он сел на нее, нагнулся и, подперев голову обеими руками, задумался.<br/> Зимней тайги, лесного лагеря, восемнадцати месяцев, проведенных у партизан, как не бывало. Он забыл о них. В его воображении стояли одни близкие. Он строил догадки о них одну другой ужаснее.<br/> Вот Тоня идет полем во вьюгу с Шурочкой на руках. Она кутает его в одеяло, её ноги проваливаются в снег, она через силу вытаскивает их, а метель заносит ее, ветер валит её наземь, она падает и подымается, бессильная устоять на ослабших, подкашивающихся ногах. О, но ведь он все время забывает, забывает. У нее два ребенка, и меньшого она кормит.<br/> Обе руки у нее заняты, как у беженок на Чилимке, от горя и превышавшего их силы напряжения лишавшихся рассудка.<br/> Обе руки её заняты и никого кругом, кто бы мог помочь.<br/> Шурочкин папа неизвестно где. Он далеко, всегда далеко, всю жизнь в стороне от них, да и папа ли это, такими ли бывают настоящие папы? А где её собственный папа? Где Александр Александрович? Где Нюша? Где остальные? О, лучше не задавать себе этих вопросов, лучше не думать, лучше не вникать.<br/> Доктор поднялся с колоды в намерении спуститься назад в землянку. Внезапно мысли его приняли новое направление. Он передумал возвращаться вниз к Ливерию.<br/> Лыжи, мешок с сухарями и все нужное для побега было давно запасено у него. Он зарыл эти вещи в снег за сторожевою чертою лагеря, под большою пихтою, которую для верности еще отметил особою зарубкою. Туда, по проторенной среди сугробов пешеходной стежке он и направился. Была ясная ночь. Светила полная луна. Доктор знал, где расставлены на ночь караулы и с успехом обошел их. Но у поляны с обледенелою рябиной часовой издали окликнул его и, стоя прямо на сильно разогнанных лыжах, скользком подъехал к нему.<br/> — Стой! Стрелять буду! Кто такой? Говори порядок.<br/> — Да что ты, братец, очумел? Свой. Аль не узнал? Доктор ваш Живаго.<br/> — Виноват! Не серчай, товарищ Желвак. Не признал. А хоша и Желвак, дале не пущу. Надо всё следом правилом.<br/> — Ну, изволь. Пароль Красная Сибирь, отзыв долой интервентов.<br/> — Это другой разговор. Ступай куда хошь. За каким шайтаном ночебродишь? Больные?<br/> — Не спится и жажда одолела. Думал, пройдусь, поглотаю снега. Увидел рябину в ягодах мороженых, хочу пойти, пожевать.<br/> — Вот она, дурь барская, зимой по ягоду. Три года колотим, колотим, не выколотишь. Никакой сознательности. Ступай по свою рябину, ненормальный. Аль мне жалко?<br/> И так же разгоняясь все скорее и скорее, часовой с сильно взятого разбега, стоя отъехал в сторону на длинных свистящих лыжах, и стал уходить по цельному снегу все дальше и дальше за тощие, как поредевшие волосы, голые зимние кусты. А тропинка, по которой шел доктор, привела его к только что упомянутой рябине.<br/> Она была наполовину в снегу, наполовину в обмерзших листьях и ягодах, и простирала две заснеженные ветки вперед навстречу ему. Он вспомнил большие белые руки Лары, круглые, щедрые и, ухватившись за ветки, притянул дерево к себе. Словно сознательным ответным движением рябина осыпала его снегом с ног до головы. Он бормотал, не понимая, что говорит и сам себя не помня:<br/> — Я увижу тебя, красота моя писаная, княгиня моя рябинушка, родная кровинушка.<br/> Ночь была ясная. Светила луна. Он пробрался дальше в тайгу к заветной пихте, откопал свои вещи и ушел из лагеря.

