## ЧАСТЬ тринадцатая. ПРОТИВ ДОМА С ФИГУРАМИ {-}

### 1 {-}

По кривой горке к Малой Спасской и Новосвалочному спускалась Большая Купеческая. На нее заглядывали дома и церкви более возвышенных частей города.<br/> На углу стоял темносерый дом с фигурами. На огромных четырехугольных камнях его наклонно скошенного фундамента чернели свежерасклеенные номера правительственных газет, правительственные декреты и постановления. Надолго застаиваясь на тротуаре, литературу в безмолвии читали небольшие кучки прохожих.<br/> Было сухо после недавней оттепели. Подмораживало. Мороз заметно крепчал. Было совсем светло в часы, в которые еще недавно темнело. Недавно ушла зима. Пустоту освободившегося места наполнил свет, который не уходил и задерживался вечерами. Он волновал, влек вдаль, пугал и настораживал.<br/> Недавно из города ушли белые, сдав его красным. Кончились обстрелы, кровопролитие, военные тревоги. Это тоже пугало и настораживало, как уход зимы и прирост весеннего дня.<br/> Извещения, которые при свете удлинившегося дня читали уличные прохожие, гласили:<br/> «К сведению населения. Рабочие книжки для состоятельных получаются за 50 рублей штука в Продотделе Юрсовета, Октябрьская, бывшая Генералгубернаторская, 5, комната 137.<br/> Неимение рабочей книжки или не правильное, а тем более лживое ведение записей карается по всем строгостям военного времени. Точная инструкция к пользованию рабочими книжками распубликована в И. Ю. И. К. № 86 (1013) текущего года и вывешена в Продотделе Юрсовета, комната 137».<br/> В другом объявлении сообщалось о достаточности имеющихся в городе продовольственных запасов, которые якобы только прячет буржуазия, чтобы дезорганизовать распределение и посеять хаос в продовольственном деле. Объявление кончалось словами:<br/> «Уличенные в хранении и сокрытии продовольственных запасов расстреливаются на месте».<br/> Третье объявление предлагало:<br/> «В интересах правильной постановки продовольственного дела непринадлежащие к эксплуататорским элементам объединяются в потребительские коммуны. О подробностях справиться в Продотделе Юрсовета, Октябрьская, бывшая Генералгубернаторская, 5, комната 137».<br/> Военных предупреждали:<br/> «Несдавшие оружие или носящие без соответствующего разрешения нового образца преследуются по всей строгости закона. Разрешения обмениваются в Юрревкоме, Октябрьская, 6, комната 63».

