### 2 {-}

К группе читавших подошел исхудалый, давно не мывшийся и оттого казавшийся смуглым человек одичалого вида с котомкой за плечами и палкой. В сильно отросших его волосах еще не было седины, а темнорусая борода, которою он оброс, стала седеть.<br/> Это был доктор Юрий Андреевич Живаго. Шубу, наверное, давно сняли с него дорогою, или он сбыл её в обмен на пищу. Он был в вымененных короткорукавых обносках с чужого плеча, не гревших его.<br/> В мешке у него оставалась недоеденная краюшка хлеба, поданная в последней пройденной подгородной деревне, и кусок сала. Около часу назад он вошел в город со стороны железной дороги, и ему понадобился целый час, чтобы добрести от городской заставы до этого перекрестка, так он был измучен ходьбою последних дней и слаб. Он часто останавливался и еле сдерживался, чтобы не упасть на землю и не целовать каменьев города, которого он больше не чаял когда-нибудь увидеть, и виду которого радовался, как живому существу.<br/> Очень долго, половину своего пешего странствия он шел вдоль линии железной дороги. Она вся находилась в забросе и бездействии, и вся была заметена снегом. Его путь лежал мимо целых белогвардейских составов, пассажирских и товарных, застигнутых заносами, общим поражением Колчака и истощением топлива. Эти, застрявшие в пути, навсегда остановившиеся и погребенные под снегом поезда тянулись почти непрерывною лентою на многие десятки верст. Они служили крепостями шайкам вооруженных, грабившим по дорогам, пристанищем скрывающимся уголовным и политическим беглецам, невольным бродягам того времени, но более всего братскими могилами и сборными усыпальницами умершим от мороза и от сыпняка, свирепствовавшего по линии и выкашивавшего в окрестностях целые деревни.<br/> Это время оправдало старинное изречение: человек человеку волк. Путник при виде путника сворачивал в сторону, встречный убивал встречного, чтобы не быть убитым. Появились единичные случаи людоедства. Человеческие законы цивилизации кончились.<br/> В силе были звериные. Человеку снились доисторические сны пещерного века.<br/> Одиночные тени, кравшиеся иногда по сторонам, боязливо перебегавшие тропинку далеко впереди и которые Юрий Андреевич, когда мог, старательно обходил, часто казались ему знакомыми, где-то виденными. Ему чудилось, что все они из партизанского лагеря. В большинстве случаев это были ошибки, но однажды глаз не обманул его. Подросток, выползший из снеговой горы, скрывавшей корпус международного спального вагона, и по совершении нужды заюркнувший обратно в сугроб, действительно был из лесных братьев. Это был мнимо насмерть расстрелянный Терентий Галузин. Его недострелили, он пролежал в долгом обмороке, пришел в себя, уполз с места казни, скрывался в лесах, оправился от ран и теперь тайком под другой фамилией пробирался к своим в Крестовоздвиженск, хоронясь по пути от людей в засыпанных поездах.<br/> Эти картины и зрелища производили впечатление чего-то нездешнего, трансцендентного. Они представлялись частицами каких-то неведомых, инопланетных существований, по ошибке занесенных на землю. И только природа оставалась верна истории и рисовалась взору такою, какой изображали её художники новейшего времени.<br/> Выдавались тихие зимние вечера, светлосерые, темнорозовые.<br/> По светлой заре вычерчивались черные верхушки берез, тонкие, как письмена. Текли черные ручьи под серой дымкой легкого обледенения, в берегах из белого, горами лежащего, снизу подмоченного темною речною водою снега. И вот такой вечер, морозный, прозрачно серый, сердобольный, как пушинки вербы, через час-другой обещал наступить против дома с фигурами в Юрятине.<br/> Доктор подошел было к доске Центропечати на каменной стене дома, чтобы просмотреть казенные оповещения. Но взгляд его поминутно падал на противоположную сторону, устремленный вверх, в несколько окон второго этажа в доме напротив. Эти выходившие на улицу окна были забелены мелом когда-то. В находившихся за ними двух комнатах была сложена хозяйская мебель. Хотя мороз подернул низы оконниц тонкой хрустальной коркой, было видно, что окна теперь прозрачны и отмыты от мела. Что означала эта перемена? Вернулись ли хозяева? Или Лара выехала, в квартире новые жильцы, и теперь там все по-другому?<br/> Неизвестность волновала доктора. Он не мог совладать с волнением. Он перешел через дорогу, вошел с парадного подъезда в сени и стал подниматься по знакомой и такой дорогой его сердцу парадной лестнице. Как часто в лесном лагере до последней завитушки вспоминал он решетчатый узор литых чугунных ступеней. На каком-то повороте подъема, при взгляде сквозь решетку под ноги, внизу открывались сваленные под лестницей худые ведра, лохани и поломанные стулья. Так повторилось и сейчас. Ничего не изменилось, все было по-прежнему. Доктор был почти благодарен лестнице за верность прошлому.<br/> Когда-то в двери был звонок. Но он испортился и бездействовал уже в прежние времена, до лесного пленения доктора. Он хотел постучаться в дверь, но заметил, что она заперта по-новому, тяжелым висячим замком, продетым в кольца, грубо ввинченные в облицовку старинной дубовой двери с хорошей и местами выпавшей отделкою. Прежде такого варварства не допускали. Пользовались врезными дверными замками, хорошо запиравшимися, а если они портились, на то были слесаря, чтобы чинить их. Ничтожная эта мелочь по-своему говорила об общем, сильно подвинувшемся вперед ухудшении.<br/> Доктор был уверен, что Лары и Катеньки нет в доме, а может быть, и в Юрятине, а может быть, даже и на свете. Он готов был к самым страшным разочарованиям. Только для очистки совести решил он пошарить в дыре, которой так боялись он и Катенька, и постучал ногой по стене, чтобы не наткнуться рукой на крысу в отверстии. У него не было надежды найти что-нибудь в условном месте. Дыра была заложена кирпичом. Юрий Андреевич вынул кирпич и сунул в углубление руку. О чудо! Ключ и записка.<br/> Записка довольно длинная, на большом листе. Доктор подошел к лестничному окошку на площадке. Еще большее чудо, еще более невероятное! Записка написана ему! Он быстро прочел:<br/> «Господи, какое счастье! Говорят, ты жив и нашелся. Тебя видели в окрестностях, прибежали и сказали мне. Предполагая, что первым делом ты поспешишь в Варыкино, отправляюсь к тебе сама туда с Катенькой. На всякий случай ключ в обычном месте.<br/> Дожидайся моего возвращения, никуда не уходи. Да, ты этого не знаешь, я теперь в передней части квартиры, в комнатах, выходящих на улицу. Впрочем, сам догадаешься. В доме простор, запустение, пришлось продать часть хозяйской мебели. Оставляю немного еды, главным образом, вареной картошки. Придавливай крышку кастрюли утюгом или чем-нибудь тяжелым, как я сделала, в предохранение от крыс. Без ума от радости».<br/> Тут кончалась лицевая сторона записки. Доктор не обратил внимания, что бумажка исписана и с другой стороны. Он поднес разложенный на ладони листок к губам, а потом, не глядя, сложил и сунул его вместе с ключом в карман. Страшная, ранящая боль примешалась к его безумной радости. Раз она не обинуясь, без всяких оговорок направляется в Варыкино, следовательно, его семьи там нет. Кроме тревоги, которую вызывала эта частность, ему нестерпимо больно и грустно было за своих.<br/> Отчего она ни словом не обмолвилась о них и о том, где они, точно их и вообще не существовало.<br/> Но раздумывать было некогда. На улице начинало темнеть.<br/> Множество дел надо было успеть сделать засветло. Не последнею заботою было ознакомление с развешанными на улице декретами.<br/> Время было нешуточное. Можно было по незнанию заплатить жизнью за нарушение какого-нибудь обязательного постановления. И не отпирая квартиры и не снимая котомки с натруженного плеча, он сошел вниз на улицу и подошел к стене, на большом пространстве сплошь облепленной разнообразною печатью.

