### 3 {-}

Эта печать состояла из газетных статей, протоколов речей на заседаниях и декретов. Юрий Андреевич бегло просматривал заглавия. «О порядке реквизиции и обложении имущих классов. О рабочем контроле. О фабрично-заводских комитетах». Это были распоряжения новой, вошедшей в город власти в отмену застигнутых тут предшествующих порядков. Она напоминала о неукоснительности своих устоев, может быть, забытых жителями при временном правлении белых. Но у Юрия Андреевича закружилась голова от нескончаемости этих однообразных повторов. Каких лет были эти заголовки? Времен первого переворота, или последующих периодов, после нескольких белогвардейских восстаний в промежутке? Что это за надписи?<br/> Прошлогодние? Позапрошлогодние? Один раз в жизни он восхищался безоговорочностью этого языка и прямотою этой мысли. Неужели за это неосторожное восхищение он должен расплачиваться тем, чтобы в жизни больше уже никогда ничего не видеть, кроме этих на протяжении долгих лет не меняющихся шалых выкриков и требований, чем дальше, тем более нежизненных, неудобопонятных и неисполнимых? Неужели минутою слишком широкой отзывчивости он навеки закабалил себя?<br/> Откуда-то вырванный кусок отчета попался ему. Он читал:<br/> «Сведения о голоде показывают невероятную бездеятельность местных организаций. Факты злоупотребления очевидны, спекуляция чудовищна, но что сделало бюро местных профоргов, что сделали городские и краевые фабзавкомы? Пока мы не произведем массовых обысков в пакгаузах Юрятина-товарного, на участке Юрятин-Развилье и Развилье-Рыбалка, пока не применим суровых мер террора вплоть до расстрела на месте к спекулянтам, не будет спасения от голода».<br/> «Какое завидное ослепление! — думал доктор. О каком хлебе речь, когда его давно нет в природе? Какие имущие классы, какие спекулянты, когда они давно уничтожены смыслом предшествующих декретов? Какие крестьяне, какие деревни, когда их больше не су шествует? Какое забвение своих собственных предначертаний и мероприятий, давно не оставивших в жизни камня на камне! Кем надо быть, чтобы с таким неостывающим горячешным жаром бредить из года в год на несуществующие, давно прекратившиеся темы, и ничего не знать, ничего кругом не видеть!»<br/> У доктора закружилась голова. Он лишился чувств и упал на тротуар без памяти. Когда он пришел в сознание и ему помогли встать, ему предложили отвести его, куда он укажет. Он поблагодарил и отказался от помощи, объяснив, что ему только через дорогу, напротив.

