### 4 {-}

Он еще раз поднялся наверх и стал отпирать дверь в Ларину квартиру. На площадке лестницы было еще совсем светло, ничуть не темнее, чем в первый его подъем. Он с признательной радостью отметил, что солнце не торопит его.<br/> Щелкание отмыкаемой двери произвело переполох внутри.<br/> Пустующее в отсутствие людей помещение встретило его лязгом и дребезжанием опрокидываемых и падающих жестянок. Всем телом шлепались на пол и врассыпную разбегались крысы. Доктору стало не по себе от чувства беспомощности перед этой мерзостью, которой тут наверное расплодилась тьма тьмущая.<br/> И до какой бы то ни было попытки водворения на ночевку сюда, он первым делом решил оградиться от этой напасти и, укрывшись в какой-нибудь легко отделимой и хорошо затворяющейся комнате, заделать битым стеклом и обрезками железа все крысиные ходы.<br/> Из передней он повернул налево, в неизвестную ему часть квартиры. Миновав темную проходную комнату, он очутился в светлой, двумя окнами выходившей на улицу. Прямо против окон на другой стороне темнел дом с фигурами. Низ стены его был покрыт расклеенными газетами. Стоя спиною к окнам, газеты читали прохожие.<br/> Свет в комнате и снаружи был один и тот же, молодой, невыстоявшийся вечерний свет ранней весны. Общность света внутри и снаружи была так велика, точно комната не отделялась от улицы. Только в одном была небольшая разница. В Лариной спальне, где стоял Юрий Андреевич, было холоднее, чем снаружи на Купеческой.<br/> Когда Юрий Андреевич приближался к городу на своем последнем переходе и час или два тому назад шел по нему, безмерно увеличившаяся его слабость казалась ему признаком грозящего близкого заболевания и пугала его.<br/> Сейчас же однородность освещения в доме и на воле так же беспричинно радовала его. Столб выхоложенного воздуха, один и тот же, что на дворе, что в жилище, роднил его с вечерними уличными прохожими, с настроениями в городе, с жизнью на свете. Страхи его рассеялись. Он уже не думал, что заболеет.<br/> Вечерняя прозрачность весеннего, всюду проникающего света казалась ему залогом далеких и щедрых надежд. Ему верилось, что все к лучшему, и он всего добьется в жизни, всех разыщет и примирит, все додумает и выразит. И радости свидания с Ларою он ждал как ближайшего доказательства.<br/> Безумное возбуждение и необузданная суетливость сменили его предшествующий упадок сил. Это оживление было более верным симптомом начинающейся болезни, чем недавняя слабость. Юрию Андреевичу не сиделось. Его снова тянуло на улицу, и вот по какому поводу.<br/> Перед тем, как обосноваться тут, ему хотелось постричься и снять бороду. В этих видах он уже проходя через город заглядывал в витрины бывших парикмахерских. Часть помещений пустовала или была занята под другие надобности. Другие, отвечавшие прежнему назначению, были под замком. Постричься и побриться было негде. Своей бритвы у Юрия Андреевича не было.<br/> Ножницы, если бы таковые нашлись у Лары, могли бы вывести его из затруднения. Но в беспокойной торопливости, с какой он перерыл все у нее на туалетном столике, ножниц он не обнаружил.<br/> Он вспомнил, что на Малой Спасской находилась когда-то швейная мастерская. Он подумал, что если заведение не прекратило своего существования и там до сих пор работают, и если он поспеет к ним до часа их закрытия, ножницы можно будет попросить у какой-нибудь из мастериц. И он еще раз вышел на улицу.

