### 5 {-}

Воспоминание его не обмануло. Мастерская осталась на старом месте, в ней работали. Мастерская занимала торговое помещение на уровне тротуара с витринным окном во всю ширину и выходом на улицу. В окно было видно внутрь до противоположной стены.<br/> Мастерицы работали на виду у идущих по улице.<br/> В комнате была страшная теснота. В придачу к настоящим работницам, на работу, наверное, пристроились швеи-любительницы, стареющие дамы из юрятинского общества, для получения рабочих книжек, о которых говорилось в декрете на стене дома с фигурами.<br/> Их движения сразу были отличимы от расторопности действительных портних. В мастерской шили одно военное, ватные штаны, стеганки и куртки, а также сметывали, как Юрий Андреевич это уже видел в партизанском лагере, сборные шутовского вида тулупы из разномастных собачьих шкур.<br/> Неловкими пальцами подсовывая подогнутые для подрубания полы под пробивные иглы швейных машин, швеи-любительницы еле справлялись с непривычною, наполовину скорняжною работой.<br/> Юрий Андреевич постучал в окно и сделал знак рукою, чтобы его впустили. Такими же знаками ему ответили, что от частных людей заказов не берут. Юрий Андреевич не отступал и, повторяя те же движения, настаивал, чтобы его впустили внутрь и выслушали. Отнекивающимися движениями ему дали понять, что у них спешное дело, чтобы он отстал, не мешал и шел дальше. Одна из мастериц изобразила на лице недоумение и в знак досады выставила ладошку лодочкой вперед, глазами спрашивала, что ему, собственно, нужно. Двумя пальцами, указательным и средним, он изобразил чикающее движение ножниц. Его движения не поняли. Решили, что это какая-то непристойность, что он передразнивает их и с ними заигрывает. Оборванным видом и странным поведением он производил впечатление больного или сумасшедшего. В мастерской хихикали, пересмеивались и махали на него руками, гоня его прочь от окна. Наконец он догадался поискать пути через двор дома, нашел его и, отыскав дверь в мастерскую, постучался в нее с черного хода.

