### 6 {-}

Дверь отворила пожилая темноликая портниха в темном платье, строгая, может быть, старшая в заведении.<br/> — Вот какой, привязался! Наказание в самом деле. Ну, скорее, что вам? Некогда.<br/> — Ножницы мне требуются, не удивляйтесь. Хочу попросить на минуту на подержание. Я тут же при вас сниму бороду и верну с благодарностью.<br/> В глазах портнихи показалось недоверчивое удивление. Было нескрываемо ясно, что она усомнилась в умственных способностях собеседника.<br/> — Я издалека. Только сейчас прибыл в город, оброс. Хотел бы постричься. И ни одной парикмахерской. Так вот, я бы, пожалуй, и сам, только ножниц нету. Одолжите, пожалуйста.<br/> — Хорошо. Я постригу вас. Только смотрите. Если у вас что-нибудь другое на уме, хитрости какие-нибудь, изменение внешности для маскировки, что-нибудь политическое, уж не взыщите. Жизнью ради вас не будем жертвовать, пожалуемся, куда следует. Не такое теперь время.<br/> — Помилуйте, что за опасения!<br/> Портниха впустила доктора, ввела в боковую комнату не шире чуланчика, и через минуту он сидел на стуле, как в цирюльне, весь обвязанный туго стягивавшей шею, заткнутой за ворот простыней.<br/> Портниха отлучилась за инструментами и немного спустя вернулась с ножницами, гребенкою, несколькими, разных номеров, машинками, ремнем и бритвой.<br/> — Всё в жизни перепробовала, — пояснила она, заметив, как изумлен доктор, что это все оказалось наготове. — Парикмахершей работала. На той войне, в сестрах милосердия, стричь и брить научилась. Бороду предварительно отхватим ножницами, а потом пробреем вчистую.<br/> — Волосы будете стричь, пожалуйста, покороче.<br/> — Постараемся. Такие интеллигентные, а притворяетесь незнающими. Сейчас счет не по неделям, а на декады. Сегодня у нас семнадцатое, а по числам с семеркой парикмахеры выходные.<br/> Будто это вам неизвестно.<br/> — Да честное слово. Зачем мне притворяться? Я ведь сказал.<br/> Я — издалека. Нездешний.<br/> — Спокойнее. Не дергайтесь. Недолго порезаться. Значит, — приезжий? На чем ехали?<br/> — На своих двоих.<br/> — Трактом шли?<br/> — Часть трактом, а остальную по линии. Поездов, поездов под снегом! Всякие, люксы, экстренные.<br/> — Ну вот еще кусочек остался. Отсюда снимем, и готово. По семейным надобностям?<br/> — Какое там по семейным! По делам бывшего союза кредитных товариществ. Инспектором я разъездным. Послали в объезд с ревизией. Чорт знает куда. Застрял в Восточной Сибири. А назад никак. Поездов-то ведь нет. Пришлось пешком, ничего не попишешь. Полтора месяца шел. Такого навидался, в жизни не пересказать.<br/> — А и не надо рассказывать. Я вас научу уму-разуму. А сейчас погодите. Вот вам зеркало. Выпростайте руку из-под простыни и возьмите его. Полюбуйтесь на себя. Ну как находите?<br/> — По-моему, мало сняли. Можно бы покороче.<br/> — Прическа не будет держаться. Я говорю, ничего и не надо рассказывать. Обо всем самое лучшее молчок теперь. Кредитные товарищества, поезда люкс под снегом, инспектора и ревизоры, лучше вам даже слова эти забыть. Еще в такое с ними влопаетесь! Не по внучке онучки, не по сезону это. Лучше врите, что доктор вы или учитель. Ну вот, бороду начерно отхватила, сейчас будем набело брить. Намылимся, чик-чик, и лет на десять помолодеем. Я за кипятком схожу, воды нагрею.<br/> «Кто она, эта женщина!» — между тем думал доктор в её отсутствие. «Какое-то ощущение, будто у нас могут быть точки соприкосновения и я должен её знать. Что-то виденное или слышанное. Вероятно, она кого-то напоминает. Но чорт побери, кого именно?»<br/> Портниха вернулась.<br/> — А теперь, значит, побреемся. Да, стало быть, лучше никогда не говорить лишнего. Это истина вечная. Слово серебро, а молчание золото. Поезда там литерные и кредитные товарищества. Лучше что-нибудь выдумайте, будто доктор или учитель. А что видов навидались, держите про себя. Кого теперь этим удивишь? Не беспокоит бритва-то?<br/> — Немного больно.<br/> — Дерет, должна драть, сама знаю. Потерпите, миленький.<br/> Без этого нельзя. Волос отрос и погрубел, отвыкла кожа. Да.<br/> Видами теперь никого не удивишь. Искусились люди. Хлебнули и мы горюшка. Тут в атамановщину такое творилось! Похищения, убийства, увозы. За людьми охотились. Например, мелкий сатрап один, сапуновец, невзлюбил, понимаете, поручика. Посылает солдат устроить засаду близ Загородной рощи, против дома Крапульского. Обезоруживают и под конвоем в Развилье. А Развилье у нас было тогда то же самое, что теперь губчека.<br/> Лобное место. Что это вы головой мотаете? Дерет? Знаю, милый, знаю. Ничего не поделаешь. Тут подчищать приходится прямо против волоса, да и волос как щетина. Жесткий. Такое место.<br/> Жена, значит, в истерике. Жена поручика. Коля! Коля мой! И прямо к главному. То есть это только так говорится, что прямо.<br/> Кто её пустит. Протекция. Тут одна особа на соседней улице знала ходы к главному и за всех заступалась. Исключительно гуманный был человек, не чета другим, отзывчивый. Генерал Галиуллин. А кругом самосуды, зверства, драмы ревности.<br/> Совершенно как в испанских романах.<br/> «Это она о Ларе, — догадывался доктор, но из предосторожности молчал и не вступал в более подробные расспросы. — А когда она сказала: „как в испанских романах“, она опять кого-то страшно напомнила. Именно этим неподходящим словом, сказанным ни к селу ни к городу».<br/> — Теперь, конечно, совсем другой разговор. Оно, положим, расследований, доносов, расстрелов и теперь хоть отбавляй. Но в идее это совсем другое. Во-первых, власть новая. Еще без году неделя правит, не вошли во вкус. Во-вторых, что там ни говори, они за простой народ, в этом их сила. Нас, считая со мной, было четыре сестры. И все трудящиеся. Естественно, мы склоняемся к большевикам. Одна сестра умерла, замужем была за политическим. Ее муж управляющим служил на одном из здешних заводов. Их сын, мой племянник, — главарь наших деревенских повстанцев, можно сказать, знаменитость.<br/> «Так вот оно что!» — осенило Юрия Андреевича. — «Это тетка Ливерия, местная притча во языцех и свояченица Микулицына, парикмахерша, швея, стрелочница, всем известная здесь мастерица на все руки. Буду, однако, по-прежнему отмалчиваться, чтобы себя не выдать».<br/> — Тяга к народу у племянника с детства. У отца среди рабочих рос, на Святогоре Богатыре. Варыкинские заводы, может быть, слыхали? Это что же мы такое с вами делаем! Ах я дура беспамятная! Полподбородка гладкие, другая половина небрита.<br/> Вот что значит заговорились. А вы что смотрели, не остановили?<br/> Мыло на лице высохло. Пойду подогрею воду. Остыла.<br/> Когда Тунцева вернулась, Юрий Андреевич спросил:<br/> — Варыкино ведь это какая-то глушь богоспасаемая, дебри, куда не доходят никакие потрясения?<br/> — Ну, как сказать, богоспасаемая. Этим дебрям, пожалуй, посолоней нашего пришлось. Через Варыкино какие-то шайки проходили, неизвестно чьи. По нашему не говорили. Дом за домом на улицу выводили и расстреливали. И уходили не говоря худого слова. Так тела неубранными на снегу и оставались. Зимой ведь было дело. Что же это вы все дергаетесь? Я вас чуть бритвой по горлу не полоснула.<br/> — Вот вы говорили, зять ваш, варыкинский житель. Его тоже не миновали эти ужасы?<br/> — Нет, зачем. Бог милостив. Он с женой вовремя оттуда выбрался. С новой, со второй. Где они, неизвестно, но достоверно, что спаслись. Там в самое последнее время новые люди завелись. Московская семья, приезжие. Те еще раньше уехали. Младший из мужчин, доктор, глава семьи, без вести пропал. Ну что значит без вести! Это ведь только так говорится, что без вести, чтобы не огорчать. А по настоящему, надо полагать, умер, убит. Искали, искали его — не нашли. Тем временем другого, старшего, вытребовали на родину. Профессор он. По сельскому хозяйству. Вызов, я слышала, получил от самого правительства. Через Юрятин они проехали еще до вторых белых. Опять вы за свое, товарищ дорогой? Ежели так под бритвой ерзать и дергаться, недолго и зарезать клиента.<br/> Слишком много вы требуете от парикмахера.<br/> «Значит в Москве они!»

