### 7 {-}

«В Москве! В Москве», с каждым шагом отдавалось в душе у него, пока он в третий раз подымался по чугунной лестнице.<br/> Пустая квартира снова встретила его содомом скачущих, падающих, разбегающихся крыс. Юрию Андреевичу было ясно, что рядом с этою гадостью он не сомкнет глаз ни на минуту, как бы он ни был измучен. Приготовления к ночлегу он начал с заделки крысиных дыр. По счастью в спальне их оказалось не так много, гораздо меньше, чем в остальной квартире, где и самые полы и основания стен были в меньшей исправности. Но надо было торопиться. Ночь приближалась. Правда, в кухне на столе его ждала, может быть, в расчете на его приход, снятая со стены и наполовину заправленная лампа, и около нее в незадвинутом спичечном коробке лежало несколько спичек, счетом десять, как насчитал Юрий Андреевич. Но и то и другое, керосин и спички, лучше следовало беречь. В спальне еще обнаружилась ночная плошка со светильней и следами лампадного масла, которое почти до дна, наверное, выпили крысы.<br/> В некоторых местах ребра плинтусов отставали от пола. Юрий Андреевич вбил в щели несколько слоев плашмя положенных стеклянных осколков, остриями внутрь. Дверь спальни хорошо приставала к порогу. Ее можно было плотно притворить и, заперев, наглухо отделить комнату с заделанными скважинами от остальной квартиры. В час с небольшим Юрий Андреевич со всем этим справился.<br/> Угол спальни скашивала кафельная печь с изразцовым, до потолка не доходящим карнизом. В кухне припасены были дрова, вязанок десять. Юрий Андреевич решил ограбить Лару охапки на две и, став на одно колено, стал набирать дрова на левую руку.<br/> Он перенес их в спальню, сложил у печи, ознакомился с её устройством и наскоро проверил, в каком она состоянии. Он хотел запереть комнату на ключ, но дверной замок оказался в неисправности и потому, приперев дверь тугой бумажной затычкой, чтобы она не отворялась, Юрий Андреевич стал не спеша растапливать печку.<br/> Накладывая поленья в топку, он увидал метку на брусовом срезе одной из плах. С удивлением он узнал ее. Это были следы старого клеймления, две начальные буквы «ка» и «де», обозначавшие на нераспиленных деревьях, с какого они склада.<br/> Этими буквами когда-то при Крюгере клеймили концы бревен из Кулабышевской деляны в Варыкине, когда заводы торговали излишками ненужного топливного леса.<br/> Наличие дров этого сорта в хозяйстве у Лары доказывало, что она знает Самдевятова и что он о ней заботится, как когда-то снабжал всем нужным доктора с его семьею. Открытие это было нож в сердце доктору. Его и прежде тяготила помощь Анфима Ефимовича. Теперь стеснительность этих одолжений осложнялась другими ощущениями.<br/> Едва ли Анфим благодетельствует Ларисе Федоровне ради её прекрасных глаз. Юрий Андреевич представил себе свободные манеры Анфима Ефимовича и Ларину женскую опрометчивость. Не может быть, чтобы между ними ничего не было.<br/> В печке с дружным треском бурно разгорались сухие Кулабышевские дрова, и по мере того, как они занимались, ревнивое ослепление Юрия Андреевича, начавшись со слабых предположений, достигло полной уверенности.<br/> Но душа у него была истерзана вся кругом, и одна боль вытесняла другую. Он мог не гнать этих подозрений. Мысли сами, без его усилий, перескакивали у него с предмета на предмет.<br/> Размышления о своих, с новою силой набежавшие на него, заслонили на время его ревнивые выдумки.<br/> «Итак, вы в Москве, родные мои?» Ему уже казалось, что Тунцева удостоверила его в их благополучном прибытии. «Вы снова, значит, без меня повторили этот долгий, тяжелый путь?<br/> Как вы доехали? Какого рода эта командировка Александра Александровича, этот вызов? Наверное, приглашение из Академии возобновить в ней преподавание? Что нашли вы дома? Да полно, существует ли он еще, этот дом? О как трудно и больно, Господи! О, не думать, не думать! Как путаются мысли! Что со мною, Тоня? Я, кажется, заболеваю. Что будет со мною и всеми вами, Тоня, Тонечка, Тоня, Шурочка, Александр Александрович?<br/> Вскую отринул мя еси от лица Твоего, свете незаходимый? Отчего вас всю жизнь относит прочь, в сторону от меня? Отчего мы всегда врозь? Но мы скоро соединимся, съедемся, не правда ли?<br/> Я пешком доберусь до вас, если никак нельзя иначе. Мы увидимся. Всё снова пойдет на лад, не правда ли?<br/> Но как земля меня носит, если я всё забываю, что Тоня должна была родить и, вероятно, родила? Уже не в первый раз я проявляю эту забывчивость. Как прошли её роды? Как родила она?<br/> По пути в Москву они были в Юрятине. Хотя, правда, Лара незнакома с ними, но вот швее и парикмахерше, совершенно посторонней, их судьбы не остались неизвестны, а Лара ни словом не заикается о них в записке. Какая странная, отдающая безучастием, невнимательность! Такая же необъяснимая, как её умалчивание о её отношениях с Самдевятовым».<br/> Тут Юрий Андреевич другим разборчивым взглядом окинул стены спальни. Он знал, что из стоящих и развешанных кругом вещей нет ни одной, принадлежащей Ларе, и что обстановка прежних неведомых и скрывающихся хозяев ни в какой мере не может свидетельствовать о Лариных вкусах.<br/> Но все равно, как бы то ни было, ему вдруг стало не по себе среди глядевших со стен мужчин и женщин на увеличенных фотографиях. Духом враждебности пахнуло на него от аляповатой меблировки. Он почувствовал себя чужим и лишним в этой спальне.<br/> А он-то, дурень, столько раз вспоминал этот дом, соскучился по нем, и входил в эту комнату не как в помещение, а как в свою тоску по Ларе! Как этот способ чувствования, наверное, смешон со стороны! Так ли живут, ведут и выражают себя люди сильные, практики вроде Самдевятова, красавцы-мужчины? И почему Лара должна предпочитать его бесхарактерность и темный нереальный язык его обожания? Так ли нуждается она в этом сумбуре? Хочется ли ей самой быть тем, чем она для него является?<br/> А чем является она для него, как он только что выразился?<br/> О, на этот вопрос ответ всегда готов у него.<br/> Вот весенний вечер на дворе. Воздух весь размечен звуками.<br/> Голоса играющих детей разбросаны в местах разной дальности, как бы в знак того, что пространство все насквозь живое. И эта даль — Россия, его несравненная, за морями нашумевшая, знаменитая родительница, мученица, упрямица, сумасбродка, шалая, боготворимая, с вечно величественными и гибельными выходками, которых никогда нельзя предвидеть! О как сладко существовать! Как сладко жить на свете и любить жизнь! О как всегда тянет сказать спасибо самой жизни, самому существованию, сказать это им самим в лицо!<br/> Вот это-то и есть Лара. С ними нельзя разговаривать, а она их представительница, их выражение, дар слуха и слова, дарованный безгласным началом существования.<br/> И не правда, тысячу раз не правда все, что он наговаривал тут о ней в минуту сомнения. Как именно совершенно и безупречно всё в ней!<br/> Слезы восхищения и раскаяния застлали ему взор. Он открыл печную заслонку и помешал печь кочергой. Опламенившийся чистый жар он задвинул в самый зад топки, а недогоревшие головешки подгреб к переду, где была сильнее тяга. Некоторое время он не притворял дверцы. Ему доставляло наслаждение чувствовать игру тепла и света на лице и руках. Движущийся отблеск пламени окончательно отрезвил его. О как ему сейчас недоставало ее, как нуждался он в этот миг в чем-нибудь, осязательно исходящем от нее!<br/> Он вынул из кармана её смятую записку. Он извлек её в перевернутом виде, не в том, в каком читал прежде, и только теперь установил, что листок исписан и с нижней стороны.<br/> Разгладив скомканную бумажку, он при пляшущем свете топящейся печки прочел:<br/> «О ваших ты знаешь. Они в Москве. Тоня родила дочку».<br/> Дальше шло несколько вымаранных строк. Потом следовало:<br/> «Зачеркнула, потому что глупо в записке. Наговоримся с глазу на глаз. Тороплюсь, бегу доставать лошадь. Не знаю, что придумать, если не достану. С Катенькой будет трудно…» Конец фразы стерся и был неразборчив.<br/> «Лошадь она побежала просить у Анфима, и наверное выпросила, раз уехала», — спокойно соображал Юрий Андреевич.<br/> «Если бы совесть её не была совершенно чиста на этот счет, она не упоминала бы об этой подробности».

