### 8 {-}

Когда печка истопилась, доктор закрыл трубу и немного закусил. После еды им овладел приступ непреодолимой сонливости. Он лег, не раздеваясь, на диван и крепко заснул.<br/> Он не слышал оглушительного и беззастенчивого крысиного содома, поднявшегося за дверью и стенами комнаты. Два тяжелых сна приснились ему подряд, один вслед за другим.<br/> Он находился в Москве, в комнате перед запертою на ключ стеклянною дверью, которую он еще для верности притягивал на себя, ухватившись за дверную ручку. За дверью бился, плакал и просился внутрь его мальчик Шурочка в детском пальто, матросских брюках и шапочке, хорошенький и несчастный. Позади ребенка, обдавая его и дверь брызгами, с грохотом и гулом обрушивался водопад испорченного ли водопровода или канализации, бытового явления той эпохи, или, может быть, в самом деле здесь кончалась и упиралась в дверь какая-то дикая горная теснина, с бешено мчащимся по ней потоком и веками скопившимися в ущелье холодом и темнотою.<br/> Обвал и грохот низвергающейся воды пугали мальчика до смерти. Не было слышно, что кричал он, гул заглушал крики мальчика. Но Юрий Андреевич видел, что губами он складывал слова: «Папочка! Папочка!»<br/> У Юрия Андреевича разрывалось сердце. Всем существом своим он хотел схватить мальчика на руки, прижать к груди и бежать с ним без оглядки куда глаза глядят.<br/> Но обливаясь слезами, он тянул на себя ручку запертой двери и не пускал мальчика, принося его в жертву ложно понятым чувствам чести и долга перед другой женщиной, которая не была матерью мальчика и с минуты на минуту могла войти с другой стороны в комнату.<br/> Юрий Андреевич проснулся в поту и слезах. «У меня жар. Я заболеваю», — тотчас подумал он. — «Это не тиф. Это какая-то тяжкая, опасная, форму нездоровья принявшая усталость, какая-то болезнь с кризисом, как при всех серьезных инфекциях, и весь вопрос в том, что возьмет верх, жизнь или смерть. Но как хочется спать!» И он опять уснул.<br/> Ему приснилось темное зимнее утро при огнях на какой-то людной улице в Москве, по всем признакам, до революции, судя по раннему уличному оживлению, по перезвону первых вагонов трамвая, по свету ночных фонарей, желтыми полосами испещрявших серый предрассветный снег мостовых.<br/> Ему снилась длинная вытянувшаяся квартира во много окон, вся на одну сторону, невысоко над улицей, вероятно, во втором этаже, с низко опущенными до полу гардинами. В квартире спали в разных позах по-дорожному нераздетые люди, и был вагонный беспорядок, лежали объедки провизии на засаленных развернутых газетах, обглоданные неубранные кости жареных кур, крылышки и ножки, и стояли снятые на ночь и составленные парами на полу ботинки недолго гостящих родственников и знакомых, проезжих и бездомных. По квартире вся в хлопотах торопливо и бесшумно носилась из конца в конец хозяйка, Лара, в наскоро подпоясанном утреннем халате, и по пятам за ней надоедливо ходил он, что-то все время бездарно и некстати выясняя, а у нее уже не было для него ни минуты, и на его объяснения она на ходу отзывалась только поворотами головы в его сторону, тихими недоумевающими взглядами и невинными взрывами своего бесподобного серебристого смеха, единственными видами близости, которые для них еще остались. И так далека, холодна и притягательна была та, которой он все отдал, которую всему предпочел и противопоставлением которой все низвел и обесценил!

