### 9 {-}

Не сам он, а что-то более общее, чем он сам, рыдало и плакало в нем нежными и светлыми, светящимися в темноте, как фосфор, словами. И вместе со своей плакавшей душой плакал он сам. Ему было жаль себя.<br/> «Я заболеваю, я болен», — соображал он в минуты просветления, между полосами сна, жарового бреда и беспамятства. — «Это все же какой-то тиф, не описанный в руководствах, которого мы не проходили на медицинском факультете. Надо бы что-нибудь приготовить, надо поесть, а то я умру от голода».<br/> Но при первой же попытке приподняться на локте он убеждался, что у него нет сил пошевельнуться, и лишался чувств или засыпал.<br/> «Сколько времени я лежу тут, одетый?» — обдумывал он в один из таких проблесков. «Сколько часов? Сколько дней? Когда я свалился, начиналась весна. А теперь иней на окне. Такой рыхлый и грязный, что от него темно в комнате».<br/> На кухне крысы гремели опрокинутыми тарелками, выбегали с той стороны вверх по стене, тяжелыми тушами сваливались на пол, отвратительно взвизгивали контральтовыми плачущими голосами.<br/> И опять он спал и просыпался, и обнаруживал, что окна в снежной сетке инея налиты розовым жаром зари, которая рдеет в них, как красное вино, разлитое по хрустальным бокалам. И он не знал, и спрашивал себя, какая это заря, утренняя или вечерняя?<br/> Однажды ему почудились человеческие голоса где-то совсем близко и он упал духом, решив, что это начало помешательства.<br/> В слезах от жалости к себе, он беззвучным шопотом роптал на небо, зачем оно отвернулось от него, и оставило его. «Вскую отринул мя еси от лица Твоего, свете незаходимый, и покрыла мя есть чуждая тьма окаянного!»<br/> И вдруг он понял, что он не грезит и это полнейшая правда, что он раздет, и умыт, и лежит в чистой рубашке не на диване, а на свеже постланной постели, и что, мешая свои волосы с его волосами и его слезы со своими, с ним вместе плачет, и сидит около кровати и нагибается к нему Лара. И он потерял сознание от счастья.

