### 10 {-}

В недавнем бреду он укорял небо в безучастии, а небо всею ширью опускалось к его постели, и две большие, белые до плеч, женские руки протягивались к нему. У него темнело в глазах от радости и, как впадают в беспамятство, он проваливался в бездну блаженства.<br/> Всю жизнь он что-нибудь да делал, вечно бывал занят, работал по дому, лечил, мыслил, изучал, производил. Как хорошо было перестать действовать, добиваться, думать, и на время предоставить этот труд природе, самому стать вещью, замыслом, произведением в её милостивых, восхитительных, красоту расточающих руках!<br/> Юрий Андреевич быстро поправлялся. Его выкармливала, выхаживала Лара своими заботами, своей лебедино-белой прелестью, влажно дышащим горловым шопотом своих вопросов и ответов.<br/> Их разговоры вполголоса, даже самые пустые, были полны значения, как Платоновы диалоги.<br/> Еще более, чем общность душ, их объединяла пропасть, отделявшая их от остального мира. Им обоим было одинаково немило все фатально типическое в современном человеке, его заученная восторженность, крикливая приподнятость и та смертная бескрылость, которую так старательно распространяют неисчислимые работники наук и искусств для того, чтобы гениальность продолжала оставаться большою редкостью.<br/> Их любовь была велика. Но любят все, не замечая небывалости чувства.<br/> Для них же, — и в этом была их исключительность, — мгновения, когда подобно веянью вечности, в их обреченное человеческое существование залетало веяние страсти, были минутами откровения и узнавания все нового и нового о себе и жизни.

### 11 {-}

— Ты должен непременно вернуться к своим. Я тебя лишнего дня не продержу. Но ты видишь, что делается. Едва мы слились с Советской Россией, как нас поглотила её разруха. Сибирью и Востоком затыкают её дыры. Ведь ты ничего не знаешь. За твою болезнь в городе так много изменилось! Запасы с наших складов перевозят в центр, в Москву. Для нее это капля в море, эти грузы исчезают в ней, как в бездонной бочке, а мы остаемся без продовольствия. Почта не ходит, прекратилось пассажирское сообщение, гонят одни маршруты с хлебом. Опять в городе ропот, как перед восстанием Гайды, опять в ответ на проявления недовольства бушует чрезвычайка.<br/> Ну куда ты пустишься такой, кожа да кости, еле душа в теле?<br/> Неужто опять пешком? Да ведь не дойдешь ты! Окрепни, наберись сил, тогда другое дело.<br/> Не смею советовать, но на твоем месте, до отправки к своим, я бы немного послужила, непременно по специальности, это ценят, я пошла бы в наш губздрав, например. Он остался в прежней врачебной управе.<br/> А то сам посуди. Сын застрелившегося сибирского миллионера, жена — дочь здешнего фабриканта и помещика. Был у партизан и бежал. Как там ни толкуй, это уход из военно-революционных рядов, дезертирство. Тебе ни в коем случае нельзя оставаться не у дел, лишенцем. Мое положение тоже не тверже. И я пойду на работу, поступлю в губоно. И подо мною почва горит.<br/> — Как горит? А Стрельников?<br/> — Оттого-то и горит, что Стрельников. Я еще прежде говорила тебе, как много у него врагов. Красная армия победила. Теперь беспартийным военным, которые стояли близко к верхам и слишком много знают, дадут по шапке. Да хорошо, если по шапке, а не под обух, чтобы не оставлять следов. Среди них Паша в первом ряду. Он в большой опасности. Он был на Дальнем Востоке. Я слышала, он бежал, скрывается. Говорят, его разыскивают. Но довольно о нем. Я не люблю плакать, а если прибавлю о нем еще хоть слово, то чувствую, что разревусь.<br/> — Ты любила, ты еще до сих пор очень любишь его?<br/> — Но ведь я пошла за него замуж, он муж мой, Юрочка. Это высокий, светлый характер. Я глубоко виновата перед ним. Я не сделала ему ничего дурного, сказать так было бы не правдой. Но он огромного значения, большой, большой прямоты человек, а я — дрянь, я ничто в сравнении с ним. Вот моя вина. Но пожалуйста, довольно об этом. Как-нибудь в другой раз я сама к этому вернусь, обещаю тебе. Какая она чудная у тебя, эта Тоня твоя. Боттичеллиевская. Я была при её родах. Я с ней страшно сошлась. Но и об этом как-нибудь потом, прошу тебя. Да, так вот давай вместе служить. Будем оба ходить на службу. Каждый месяц получать жалованье миллиардами. У нас до последнего переворота были в ходу сибирские кредитки. Их аннулировали совсем недавно, и долгое время, всю твою болезнь, жили без денежных знаков. Да. Представь себе. Трудно поверить, но как-то обходились. Теперь в бывшее казначейство привезли целый маршрут бумажных денег, говорят, вагонов сорок, не меньше. Они отпечатаны большими листами двух цветов, синего и красного, как почтовые марки, и разбиты на мелкие графы. Синие по пяти миллионов клетка, красные достоинством в десять миллионов каждая. Линючие, плохая печать, краска расплывается.<br/> — Я видел эти деньги. Их ввели перед самым нашим отъездом из Москвы.

