### 12 {-}

— Что ты так долго делала в Варыкине? Ведь там никого нет, пусто? Что тебя там задержало?<br/> — Я убирала с Катенькой ваш дом. Я боялась, что ты первым делом наведаешься туда. Мне не хотелось, чтобы ты застал ваше жилище в таком виде.<br/> — В каком? Что же там, развал, беспорядок?<br/> — Беспорядок. Грязь. Я убрала.<br/> — Какая уклончивая односложность. Ты недоговариваешь, ты что-то скрываешь. Но твоя воля, не стану выведывать. Расскажи мне о Тоне. Как крестили девочку?<br/> — Машей. В память твоей матери.<br/> — Расскажи мне о них.<br/> — Позволь как-нибудь потом. Я ведь сказала тебе, я еле сдерживаю слезы.<br/> — Самдевятов этот, который тебе лошадь давал, интересная фигура. Как по-твоему?<br/> — Преинтереснейшая.<br/> — Я ведь очень хорошо знаю Анфима Ефимовича. Он был нашим другом дома здесь, в новых для нас местах, помогал нам.<br/> — Я знаю. Он мне рассказывал.<br/> — Вы наверное дружны? Он и тебе старается быть полезным?<br/> — Он меня просто осыпает благодеяниями. Я не знаю, что бы я стала без него делать.<br/> — Легко представляю себе. У вас наверное короткие, товарищеские отношения, обхождение запросто? Он наверное во всю приударяет за тобою.<br/> — Еще бы. Неотступно.<br/> — А ты? Но виноват. Я захожу за границы дозволенного. По какому праву я расспрашиваю тебя? Прости. Это нескромно.<br/> — О, пожалуйста. Тебя, наверное, интересует другое, — род наших отношений? Ты хочешь знать, не закралось ли в наше доброе знакомство что-нибудь более личное? Нет, конечно. Я обязана Анфиму Ефимовичу неисчислимо многим, я кругом в долгу перед ним, но если бы он и озолотил меня, если бы отдал жизнь за меня, это бы ни на шаг меня к нему не приблизило. У меня от рождения вражда к людям этого неродственного склада. В делах житейских эти предприимчивые, уверенные в себе, повелительные люди незаменимы. В делах сердечных петушащееся усатое мужское самодовольство отвратительно. Я совсем по-другому понимаю близость и жизнь. Но мало того. В нравственном отношении Анфим напоминает мне другого, гораздо более отталкивающего человека, виновника того, что я такая, благодаря которому я то, что я есть.<br/> — Я не понимаю. А какая ты? Что ты имеешь в виду?<br/> Объяснись. Ты лучше всех людей на свете.<br/> — Ах, Юрочка, можно ли так? Я с тобою всерьез, а ты с комплиментами, как в гостиной. Ты спрашиваешь, какая я. Я — надломленная, я с трещиной на всю жизнь. Меня преждевременно, преступно рано сделали женщиной, посвятив в жизнь с наихудшей стороны, в ложном, бульварном толковании самоуверенного пожилого тунеядца прежнего времени, всем пользовавшегося, все себе позволявшего.<br/> — Я догадываюсь. Я что-то предполагал. Но погоди. Легко представить себе твою недетскую боль того времени, страх напуганной неопытности, первую обиду невзрослой девушки. Но ведь это дело прошлого. Я хочу сказать, — горевать об этом сейчас не твоя печаль, а людей, любящих тебя, вроде меня. Это я должен рвать на себе волосы и приходить в отчаяние от опоздания, от того, что меня не было уже тогда с тобою, чтобы предотвратить случившееся, если оно правда для тебя горе.<br/> Удивительно. Мне кажется, сильно, смертельно, со страстью я могу ревновать только к низшему, далекому. Соперничество с высшим вызывает у меня совсем другие чувства. Если бы близкий по духу и пользующийся моей любовью человек полюбил ту же женщину, что и я, у меня было бы чувство печального братства с ним, а не спора и тяжбы. Я бы, конечно, ни минуты не мог делиться с ним предметом моего обожания. Но я бы отступил с чувством совсем другого страдания, чем ревность, не таким дымящимся и кровавым. То же самое случилось бы у меня при столкновении с художником, который покорил бы меня превосходством своих сил в сходных со мною работах. Я, наверное, отказался бы от своих поисков, повторяющих его попытки, победившие меня.<br/> Но я уклонился в сторону. Я думаю, я не любил бы тебя так сильно, если бы тебе не на что было жаловаться и не о чем сожалеть. Я не люблю правых, не падавших, не оступавшихся. Их добродетель мертва и малоценна. Красота жизни не открывалась им.<br/> — А я именно об этой красоте. Мне кажется, чтобы её увидеть, требуется нетронутость воображения, первоначальность восприятия. А это как раз у меня отнято. Может быть, у меня сложился бы свой взгляд на жизнь, если бы с первых шагов я не увидела её в чуждом опошляющем отпечатке. Но мало того. Из-за вмешательства в мою начинавшуюся жизнь одной безнравственной самоуслаждавшейся заурядности не сладился мой последующий брак с большим и замечательным человеком, сильно любившим меня и которому я отвечала тем же.<br/> — Погоди. О муже расскажешь мне потом. Я сказал тебе, что ревность вызывает во мне обыкновенно низший, а не равный. К мужу я тебя не ревную. А тот?<br/> — Какой «тот»?<br/> — Тот прожигатель жизни, который погубил тебя. Кто он такой?<br/> — Довольно известный московский адвокат. Он был товарищем моего отца, и после папиной смерти материально поддерживал маму, пока мы бедствовали. Холостой, с состоянием. Наверное, я придаю ему чрезмерный интерес и несвойственную значительность тем, что так черню его. Очень обыкновенное явление. Если хочешь, я назову тебе фамилию.<br/> — Не надо. Я знаю. Я раз его видел.<br/> — В самом деле?<br/> — Однажды в номерах, когда травилась твоя мать. Поздно вечером. Мы были еще детьми, гимназистами.<br/> — А, я помню этот случай. Вы приехали и стояли в темноте, в номерной прихожей. Может быть, сама я никогда не вспомнила бы этой сцены, но ты мне помог уже раз извлечь её из забвения.<br/> Ты мне её напомнил, по-моему, в Мелюзееве.<br/> — Комаровский был там.<br/> — Разве? Вполне возможно. Меня легко было застать с ним.<br/> Мы часто бывали вместе.<br/> — Отчего ты покраснела?<br/> — От звука «Комаровский» в твоих устах. От непривычности и неожиданности.<br/> — Вместе со мною был мой товарищ, гимназист одноклассник.<br/> Вот что тогда же в номерах он мне сообщил. Он узнал в Комаровском человека, которого он раз видел случайно, при непредвиденных обстоятельствах. Однажды в дороге этот мальчик, гимназист Михаил Гордон, был очевидцем самоубийства моего отца, — миллионера промышленника. Миша ехал в одном поезде с ним. Отец бросился на ходу с поезда в намерении покончить с собой и разбился. Отца сопровождал Комаровский, его юрисконсульт. Комаровский спаивал отца, запутал его дела и, доведя его до банкротства, толкнул на путь гибели. Он виновник его самоубийства и того, что я остался сиротой.<br/> — Не может быть! Какая знаменательная подробность! Неужели правда! Так он был и твоим злым гением? Как это роднит нас!<br/> Просто предопределение какое-то!<br/> — Вот к кому я тебя ревную безумно, непоправимо.<br/> — Что ты? Ведь я не только не люблю его. Я его презираю.<br/> — Так ли хорошо ты всю себя знаешь? Человеческая, в особенности женская природа так темна и противоречива!<br/> Каким-то уголком своего отвращения ты, может быть, в большем подчинении у него, чем у кого бы то ни было другого, кого ты любишь по доброй воле, без принуждения.<br/> — Как страшно то, что ты сказал. И, по обыкновению, сказал так метко, что эта противоестественность кажется мне правдой.<br/> Но тогда как это ужасно!<br/> — Успокойся. Не слушай меня. Я хотел сказать, что ревную тебя к темному, бессознательному, к тому, о чем немыслимы объяснения, о чем нельзя догадаться. Я ревную тебя к предметам твоего туалета, к каплям пота на твоей коже, к носящимся в воздухе заразным болезням, которые могут пристать к тебе и отравить твою кровь. И как к такому заражению я ревную тебя к Комаровскому, который отымет тебя когда-нибудь, как когда-нибудь нас разлучит моя или твоя смерть. Я знаю, тебе это должно казаться нагромождением неясностей. Я не могу сказать это стройнее и понятнее. Я без ума, без памяти, без конца люблю тебя.

