### 13 {-}

Расскажи мне побольше о муже. «Мы в книге рока на одной строке», — как говорит Шекспир.<br/> — Откуда это?<br/> — Из «Ромео и Джульетты».<br/> — Я много говорила тебе о нем в Мелюзееве, когда разыскивала его. И потом тут, в Юрятине, в наши первые встречи с тобою, когда с твоих слов узнала, что он хотел арестовать тебя в своем вагоне. Я по-моему рассказывала тебе, а может быть и нет, и мне только так кажется, что я его однажды видела издали, когда он садился в машину. Но можешь себе представить, как его охраняли? Я нашла, что он почти не изменился. То же красивое, честное, решительное лицо, самое честное изо всех лиц, виденных мною на свете. Ни тени рисовки, мужественный характер, полное отсутствие позы. Так всегда было и так осталось. И все же одну перемену я отметила, и она встревожила меня.<br/> Точно что-то отвлеченное вошло в этот облик и обесцветило его. Живое человеческое лицо стало олицетворением, принципом, изображением идеи. У меня сердце сжалось при этом наблюдении.<br/> Я поняла, что это следствие тех сил, в руки которых он себя отдал, сил возвышенных, но мертвящих и безжалостных, которые и его когда-нибудь не пощадят. Мне показалось, что он отмеченный, и что это перст обречения. Но может быть, я путаюсь. Может быть, в меня запали твои выражения, когда ты мне описывал вашу встречу. Помимо общности наших чувств я ведь так много от тебя перенимаю!<br/> — Нет, расскажи мне о вашей жизни до революции.<br/> — Я рано в детстве стала мечтать о чистоте. Он был её осуществлением. Ведь мы с одного двора почти. Я, он, Галиуллин. Я была его детским увлечением. Он обмирал, холодел при виде меня. Наверное, нехорошо, что я это говорю и знаю. Но было бы еще хуже, если бы я прикидывалась незнающей. Я была его детской пассией, той порабощающей страстью, которую скрывают, которую детская гордость не позволяет обнаружить, и которая без слов написана на лице и видна каждому. Мы дружили.<br/> Мы с ним люди настолько же разные, насколько я одинаковая с тобою. Я тогда же сердцем выбрала его. Я решила соединить жизнь с этим чудесным мальчиком, чуть только мы оба выйдем в люди, и мысленно тогда же помолвилась с ним.<br/> И подумай, каких он способностей! Необычайных! Сын простого стрелочника или железнодорожного сторожа, он одною своей одаренностью и упорством труда достиг, — я чуть не сказала уровня, а должна была бы сказать — вершин современного университетского знания по двум специальностям, математической и гуманитарной. Это ведь не шутка!<br/> — В таком случае, что расстроило ваш домашний лад, если вы так любили друг друга?<br/> — Ах как трудно на это ответить. Я сейчас тебе это расскажу. Но удивительно. Мне ли, слабой женщине, объяснять тебе, такому умному, что делается сейчас с жизнью вообще, с человеческой жизнью в России, и почему рушаться семьи, в том числе твоя и моя? Ах, как будто дело в людях, в сходстве и несходстве характеров, в любви и нелюбви. Все производное, налаженное, все относящееся к обиходу, человеческому гнезду и порядку, все это пошло прахом вместе с переворотом всего общества и его переустройством. Все бытовое опрокинуто и разрушено. Осталась одна небытовая, неприложенная сила голой, до нитки обобранной душевности, для которой ничего не изменилось, потому что она все время зябла, дрожала и тянулась к ближайшей рядом, такой же обнаженной и одинокой. Мы с тобой как два первых человека Адам и Ева, которым нечем было прикрыться в начале мира, и мы теперь так же раздеты и бездомны в конце его. И мы с тобой последнее воспоминание обо всем том неисчислимо великом, что натворено на свете за многие тысячи лет между ними и нами, и в память этих исчезнувших чудес мы дышим и любим, и плачем, и держимся друг за друга и друг к другу льнем.

