### 14 {-}

После некоторого перерыва она продолжала гораздо спокойнее:<br/> — Я скажу тебе. Если бы Стрельников стал снова Пашенькой Антиповым. Если бы он перестал безумствовать и бунтовать. Если бы время повернуло вспять. Если бы где-то вдали, на краю света, чудом затеплилось окно нашего дома с лампою и книгами на Пашином письменном столе, я бы, кажется, на коленях ползком приползла туда. Все бы встрепенулось во мне. Я бы не устояла против зова прошлого, зова верности. Я пожертвовала бы всем.<br/> Даже самым дорогим. Тобою. И моей близостью с тобой, такой легкой, невынужденной, саморазумеющейся. О прости. Я не то говорю. Это не правда.<br/> Она бросилась на шею к нему и разрыдалась. Очень скоро она пришла в себя. Утирая слезы, она говорила:<br/> — Но ведь это тот же голос долга, который гонит тебя к Тоне. Господи, какие мы бедные! Что с нами будет? Что нам делать?<br/> Когда она совсем оправилась, она продолжала:<br/> — Я все-таки не ответила тебе, почему расстроилось наше счастье. Я так ясно это потом поняла. Я расскажу тебе. Это будет рассказ не только о нас. Это стало судьбой многих.<br/> — Говори, моя умница.<br/> — Мы женились перед самой войною, за два года до её начала. И только мы зажили своим умом, устроили дом, объявили войну. Я теперь уверена, что она была виною всего, всех последовавших, доныне постигающих наше поколение несчастий. Я хорошо помню детство. Я еще застала время, когда были в силе понятия мирного предшествующего века. Принято было доверяться голосу разума. То, что подсказывала совесть, считали естественным и нужным. Смерть человека от руки другого была редкостью, чрезвычайным, из ряду вон выходящим явлением.<br/> Убийства, как полагали, встречались только в трагедиях, романах из мира сыщиков и в газетных дневниках происшествий, но не в обыкновенной жизни.<br/> И вдруг этот скачок из безмятежной, невинной размеренности в кровь и вопли, повальное безумие и одичание каждодневного и ежечасного, узаконенного и восхваляемого смертоубийства.<br/> Наверное, никогда это не проходит даром. Ты лучше меня, наверное, помнишь, как сразу все стало приходить в разрушение.<br/> Движение поездов, снабжение городов продовольствием, основы домашнего уклада, нравственные устои сознания.<br/> — Продолжай. Я знаю, что ты скажешь дальше. Как ты во всем разбираешься! Какая радость тебя слушать.<br/> — Тогда пришла не правда на русскую землю. Главной бедой, корнем будущего зла была утрата веры в цену собственного мнения. Вообразили, что время, когда следовали внушениям нравственного чутья, миновало, что теперь надо петь с общего голоса и жить чужими, всем навязанными представлениями. Стало расти владычество фразы, сначала монархической — потом революционной.<br/> Это общественное заблуждение было всеохватывающим, прилипчивым. Все подпадало под его влияние. Не устоял против его пагубы и наш дом. Что-то пошатнулось в нем. Вместо безотчетной живости, всегда у нас царившей, доля дурацкой декламации проникла и в наши разговоры, какое-то показное, обязательное умничанье на обязательные мировые темы. Мог ли такой тонкий и требовательный к себе человек, как Паша, так безошибочно отличавший суть от видимости, пройти мимо этой закравшейся фальши и её не заметить?<br/> И тут он совершил роковую, все наперед предрешившую ошибку.<br/> Знамение времени, общественное зло он принял за явление домашнее. Неестественность тона, казенную натянутость наших рассуждений отнес к себе, приписал тому, что он — сухарь, посредственность, человек в футляре. Тебе, наверное, кажется невероятным, чтобы такие пустяки могли что-то значить в совместной жизни. Ты не можешь себе представить, как это было важно, сколько глупостей натворил Паша из-за этого ребячества.<br/> Он пошел на войну, чего никто от него не требовал. Он это сделал, чтобы освободить нас от себя, от своего воображаемого гнета. С этого начались его безумства. С каким-то юношеским, ложно направленным самолюбием он разобиделся на что-то такое в жизни, на что не обижаются. Он стал дуться на ход событий, на историю. Пошли его размолвки с ней. Он ведь и по сей день сводит с ней счеты. Отсюда его вызывающие сумасбродства. Он идет к верной гибели из-за этой глупой амбиции. О если бы я могла спасти его!<br/> — Как неимоверно чисто и сильно ты его любишь! Люби, люби его. Я не ревную тебя к нему, я не мешаю тебе.

