### 15 {-}

Незаметно пришло и ушло лето. Доктор выздоровел. Временно, в чаянии предполагаемоего отъезда в Москву, он поступил на три места. Быстро развивающееся обесценение денег заставляло ловчиться на нескольких службах.<br/> Доктор вставал с петухами, выходил на Купеческую и спускался по ней мимо иллюзиона «Гигант» к бывшей типографии Уральского казачьего войска, ныне переименованной в «Красного наборщика». На углу Городской, на двери Управления делами, его встречала дощечка «Бюро претензий». Он пересекал площадь наискось и выходил на Малую Буяновку. Миновав завод Стенгопа, он через задний двор больницы проходил в амбулаторию Военного госпиталя, место своей главной службы.<br/> Половина его пути лежала под тенистыми, перевешивавшимися над улицей деревьями, мимо замысловатых, в большинстве деревянных домишек с круто заломленными крышами, решетчатыми оградами, узорными воротами и резными наличниками на ставнях.<br/> По соседству с амбулаторией, в бывшем наследственном саду купчихи Гореглядовой, стоял любопытный невысокий дом в старорусском вкусе. Он был облицован гранеными изразцами с глазурью, пирамидками граней наружу, наподобие старинных московских боярских палат.<br/> Из амбулатории Юрий Андреевич раза три-четыре в декаду отправлялся в бывший дом Лигетти на Старой Миасской, на заседания помещавшегося там Юрятинского Облздрава.<br/> Совсем в другом, отдаленном районе стоял дом, пожерствованный городу отцом Анфима, Ефимом Самдевятовым, в память покойной жены, которая умерла в родах, дав жизнь Анфиму. В доме помещался основанный Самдевятовым Институт гинекологии и акушерства. Теперь в нем были размещены ускоренные медико-хирургические курсы имени Розы Люксембург.<br/> Юрий Андреевич читал на них общую патологию и несколько необязательных предметов.<br/> Он возвращался со всех этих должностей к ночи измученный и проголодавшийся, и заставал Ларису Федоровну в разгаре домашних хлопот, за плитою или перед корытом. В этом прозаическом и будничном виде, растрепанная, с засученными рукавами и подоткнутым подолом, она почти пугала своей царственной, дух захватывающей притягательностью, более, чем если бы он вдруг застал её перед выездом на бал, ставшею выше и словно выросшею на высоких каблуках, в открытом платье с вырезом и широких шумных юбках.<br/> Она готовила или стирала, и потом оставшеюся мыльной водой мыла полы в доме. Или спокойная и менее разгоряченная, гладила и чинила свое, его и Катенькино белье. Или, справившись со стряпней, стиркой и уборкой, учила Катеньку. Или, уткнувшись в руководства, занималась собственным политическим переобучением перед обратным поступлением учительницею в новую преобразованную школу.<br/> Чем ближе были ему эта женщина и девочка, тем менее осмеливался он воспринимать их по-семейному, тем строже был запрет, наложенный на род его мыслей долгом перед своими и его болью о нарушенной верности им. В этом ограничении для Лары и Катеньки не было ничего обидного. Напротив, этот несемейный способ чувствования заключал целый мир почтительности, исключавший развязность и амикошонство.<br/> Но это раздвоение всегда мучило и ранило, и Юрий Андреевич привык к нему, как можно привыкнуть к незажившей, часто вскрывающейся ране.

