### 16 {-}

Так прошло месяца два или три. Как-то в октябре Юрий Андреевич сказал Ларисе Федоровне:<br/> — Знаешь, кажется, мне придется уйти со службы. Старая вечно повторяющаяся история. Начинается как нельзя лучше. «Мы всегда рады честной работе. А мыслям, в особенности новым, и того более. Как их не приветствовать. Добро пожаловать.<br/> Работайте, боритесь, ищите».<br/> Но на поверку оказывается, что под мыслями разумеется одна их видимость, словесный гарнир к возвеличению революции и властей предержащих. Это утомительно и надоедает. И я не мастер по этой части.<br/> И, наверное, действительно они правы. Конечно, я не с ними.<br/> Но мне трудно примириться с мыслью, что они герои, светлые личности, а я — мелкая душонка, стоящая за тьму и порабощение человека. Слышала ты когда-нибудь имя Николая Веденяпина?<br/> — Ну конечно. До знакомства с тобой, и потом, по частым твоим рассказам. О нем часто упоминает Симочка Тунцева. Она его последовательница. Но книг его, к стыду своему, я не читала. Я не люблю сочинений, посвященных целиком философии.<br/> По-моему философия должна быть скупою приправой к искусству и жизни. Заниматься ею одною так же странно, как есть один хрен.<br/> Впрочем, прости, своими глупостями я отвлекла тебя.<br/> — Нет, напротив. Я согласен с тобою. Это очень близкий мне образ мыслей. Да, так о дяде. Может быть, я действительно испорчен его влиянием. Но ведь сами они в один голос кричат: гениальный диагност, гениальный диагност. И правда, я редко ошибаюсь в определении болезни. Но ведь это и есть ненавистная им интуиция, которой якобы я грешу, цельное, разом охватывающее картину познание.<br/> Я помешан на вопросе о мимикрии, внешнем приспособлении организмов к окраске окружающей среды. Тут в этом цветовом подлаживании скрыт удивительный переход внутреннего во внешнее.<br/> Я осмелился коснуться этого на лекциях. И пошло! «Идеализм, мистика. Натурфилософия Гёте, неошеллингианство».<br/> Надо уходить. Из губздрава и института я уволюсь по собственному прошению, а в больнице постараюсь продержаться, пока меня не выгонят. Я не хочу пугать тебя, но временами у меня ощущение, будто не сегодня-завтра меня арестуют.<br/> — Сохрани Бог, Юрочка. До этого, по счастью, еще далеко.<br/> Но ты прав. Не мешает быть осторожнее. Насколько я заметила, каждое водворение этой молодой власти проходит через несколько этапов. В начале это торжество разума, критический дух, борьба с предрассудками.<br/> Пока наступает второй период. Получают перевес темные силы «примазавшихся», притворносочувствующих. Растут подозрительность, доносы, интриги, ненавистничество. И ты прав, мы находимся в начале второй фазы.<br/> За примером далеко ходить не приходится. Сюда в коллегию ревтрибунала перевели из Ходатского двух старых политкаторжан, из рабочих, некоего Тиверзина и Антипова.<br/> Оба великолепно меня знают, а один даже просто отец мужа, свекор мой. Но собственно только с перевода их, совсем недавно, я стала дрожать за свою и Катенькину жизнь. От них всего можно ждать. Антипов недолюбливает меня. С них станется, что в один прекрасный день они меня и даже Пашу уничтожат во имя высшей революционной справедливости.<br/> Продолжение этого разговора состоялось довольно скоро. К этому времени произведен был ночной обыск в доме номер сорок восемь по Малой Буяновке, рядом с амбулаторией, у вдовы Гореглядовой. В доме нашли склад оружия и раскрыли контрреволюционную организацию. Было арестовано много людей в городе, обыски и аресты продолжались. По этому поводу перешептывались, что часть подозреваемых ушла за реку.<br/> Высказывались такие соображения: «А что это им поможет? Река реке рознь. Бывают, надо сказать, реки. В Благовещенске на Амуре, например, на одном берегу советская власть, на другом — Китай. Прыгнул в воду, переплыл, и адью, поминай как звали.<br/> Вот это, можно сказать, река. Совсем другой разговор».<br/> — Атмосфера сгущается, — говорила Лара. — Время нашей безопасности миновало. Нас несомненно арестуют, тебя и меня.<br/> Что тогда будет с Катенькой? Я мать. Я должна предупредить несчастье и что-то придумать. У меня должно быть готово решение на этот счет. Я лишаюсь рассудка при этой мысли.<br/> — Давай подумаем. Чем тут можно помочь? В силах ли мы предотвратить этот удар? Это ведь вещь роковая.<br/> — Бежать нельзя и некуда. Но можно отступить куда-нибудь в тень, на второй план. Например, уехать в Варыкино. Я подумываю о Варыкинском доме. Это порядочная даль и там все заброшено.<br/> Но там мы никому не мозолили бы глаз, как тут. Приближается зима. Я взяла бы на себя труд перезимовать там. Пока бы до нас добрались, мы отвоевали бы год жизни, а это выигрыш.<br/> Поддерживать сношения с городом помог бы Самдевятов. Может быть, согласился бы прятать нас. А? Что ты скажешь? Правда, там теперь ни души, жуть, пустота. По крайней мере, так было в марте, когда я ездила туда. И, говорят, волки. Страшно. Но люди, особенно люди вроде Антипова или Тиверзина, теперь страшнее волков.<br/> — Я не знаю, что сказать тебе. Ведь ты сама меня все время гонишь в Москву, убеждаешь не откладывать поездки. Сейчас это стало легче. Я справлялся на вокзале. На мешочничество, видимо, махнули рукой. Не всех зайцев, видимо, снимают с маршрутов. Устали расстреливать, расстреливают реже.<br/> Меня беспокоит, что все мои письма в Москву остаются без ответа. Надо добраться туда и выяснить, что с домашними. Ты мне сама это твердишь. Но тогда как понять твои слова о Варыкине? Неужели ты одна без меня пустишься в эту страшную глушь?<br/> — Нет, без тебя, конечно, это немыслимо.<br/> — А сама отправляешь меня в Москву?<br/> — Да, это необходимо.<br/> — Послушай. Знаешь что? У меня замечательный план. Поедем в Москву. Отправляйся с Катенькой вместе со мною.<br/> — В Москву? Да ты с ума сошел. С какой радости? Нет, я должна остаться. Я должна быть наготове где-нибудь поблизости.<br/> Здесь решатся Пашенькины судьбы. Я должна дождаться их развязки, чтобы в случае надобности оказаться под рукою.<br/> — Тогда давай подумаем о Катеньке.<br/> — Ко мне захаживает по временам Симушка, Сима Тунцева. На днях мы с тобой о ней говорили.<br/> — Ну как же. Я часто вижу её у тебя.<br/> — Я тебе удивляюсь. Где у мужчин глаза? На твоем месте я непременно бы в нее влюбилась. Такая прелесть! Какая внешность! Рост. Стройность. Ум. Начитанность. Доброта.<br/> Ясность суждения.<br/> — В день возвращения сюда из плена меня брила её сестра, швея, Глафира.<br/> — Я знаю. Сестры живут вместе со старшею, Авдотьей, библиотекаршей. Честная работящая семья. Я хочу упросить их в случае крайности, если нас с тобой заберут, взять Катеньку на свое попечение. Я еще не решила.<br/> — Но действительно только в случае безвыходности. А до такого несчастья, Бог даст, авось еще далеко.<br/> — Говорят, Сима немного того, не в себе. Действительно, её нельзя признать женщиной вполне нормальной. Но это вследствие её глубины и оригинальности. Она феноменально образована, но не по интеллигентски, а по народному. Твои и её взгляды поразительно сходны. Я с легким сердцем доверила бы Катю её воспитанию.

