### 17 {-}

Опять он ходил на вокзал и вернулся ни с чем, не солоно хлебавши. Все осталось нерешенным. Его и Лару ожидала неизвестность. День был холодный и темный, как перед первым снегом. Небо над перекрестками, где оно простиралось шире, чем над вытянутыми в длину улицами, имело зимний вид.<br/> Когда Юрий Андреевич пришел домой, он застал в гостях у Лары Симушку. Между обеими происходила беседа, носившая характер лекции, которую гостья читала хозяйке. Юрий Андреевич не хотел мешать им. Кроме того, ему хотелось побыть немного одному. Женщины разговаривали в соседней комнате. Дверь к ним была приотворена. С притолоки опускалась до полу портьера, из-за которой были слышны от слова до слова их разговоры.<br/> — Я буду шить, но вы не обращайте на это внимания, Симочка. Я вся превратилась в слух. Я на курсах в свое время слушала историю и философию. Построения вашей мысли очень по душе мне. Кроме того слушать вас для меня такое облегчение. Мы последние ночи недосыпаем вследствие разных забот. Мой долг матери перед Катенькой обезопасить её на случай возможных неприятностей с нами. Надо трезво о ней подумать. Я не особенно сильна в этом. Мне грустно это сознавать. Мне грустно от усталости и недосыпания. Ваши разговоры успокаивают меня.<br/> Кроме того с минуты на минуту должен пойти снег. В снег такое наслаждение слушать длинные умные рассуждения. Если покоситься в окно, когда снег идет, то правда, кажется, будто кто-то направляется двором к дому? Начинайте, Симочка. Я слушаю.<br/> — На чем мы прошлый раз остановились?<br/> Юрию Андреевичу не было слышно, что ответила Лара. Он стал следить за тем, что говорила Сима.<br/> — Можно пользоваться словами: культура, эпохи. Но их понимают так по-разному. Ввиду сбивчивости их смысла не будем прибегать к ним. Заменим их другими выражениями.<br/> Я сказала бы, что человек состоит из двух частей. Из Бога и работы. Развитие человеческого духа распадается на огромной продолжительности отдельные работы. Они осуществлялись поколениями и следовали одна за другою. Такою работою был Египет, такою работой была Греция, такой работой было библейское богопознание пророков. Такая, последняя по времени, ничем другим пока не смененная, всем современным вдохновением совершаемая работа — христианство.<br/> Чтобы во всей свежести, неожиданно, не так, как вы сами знаете и привыкли, а проще, непосредственнее представить вам то новое, небывалое, что оно принесло, я разберу с вами несколько отрывков из богослужебных текстов, самую малость их и то в сокращениях.<br/> Большинство стихир образуют соединение рядом помещенных ветхозаветных и новозаветных представлений. С положениями старого мира, неопалимой купиной, исходом Израиля из Египта, отроками в печи огненной, Ионой во чреве китовом и так далее, сопоставляются положения нового, например, представления о зачатии Богородицы и о воскресении Христове.<br/> В этом частом, почти постоянном совмещении, старина старого, новизна нового и их разница выступают особенно отчетливо.<br/> В целом множестве стихов непорочное материнство Марии сравнивается с переходом иудеями Красного моря. Например, в стихе: «В мори Чермнем неискусобрачные невесты образ написася иногда» говорится: «Море по прошествии Израилеве пребысть непроходно, непорочная по рожестве Еммануилеве пребысть нетленна». То есть море после перехода Израиля стало снова непроходимо, а дева, родив Господа, осталась нетронутой.<br/> Какого рода происшествия поставлены тут в параллель? Оба события сверхъестественны, оба признаны одинаковым чудом. В чем же видели чудо эти разные времена, время древнейшее первобытное, и время новое, послеримское, далеко подвинувшееся вперед?<br/> В одном случае по велению народного вождя, патриарха Моисея и по взмаху его волшебного жезла расступается море, пропускает через себя целую народность, несметное, из сотен тысяч состоящее многолюдство, и когда проходит последний, опять смыкается и покрывает и топит преследователей египтян. Зрелище в духе древности, стихия послушная голосу волшебника, большие толпящиеся численности, как римские войска в походах, народ и вождь, вещи видимые и слышимые, оглушающие.<br/> В другом случае девушка — обыкновенность, на которую древний мир не обратил бы внимания, — тайно и втихомолку дает жизнь младенцу, производит на свет жизнь, чудо жизни, жизнь всех, «Живота всех», как потом его называют. Ее роды незаконны не только с точки зрения книжников, как внебрачные. Они противоречат законам природы. Девушка рожает не в силу необходимости, а чудом, по вдохновению. Это то самое вдохновение, на котором Евангелие, противопоставляющее обыкновенности исключительность и будням праздник, хочет построить жизнь, наперекор всякому принуждению.<br/> Какого огромного значения перемена! Каким образом небу (потому что глазами неба надо это оценивать, перед лицом неба, в священной раме единственности все это совершается) — каким образом небу частное человеческое обстоятельство, с точки зрения древности ничтожное, стало равноценно целому переселению народа?<br/> Что-то сдвинулось в мире. Кончился Рим, власть количества, оружием вмененная обязанность жить всей поголовностью, всем населением. Вожди и народы отошли в прошлое.<br/> Личность, проповедь свободы пришли им на смену. Отдельная человеческая жизнь стала Божьей повестью, наполнила своим содержанием пространство вселенной. Как говорится в одном песнопении на Благовещение, Адам хотел стать Богом и ошибся, не стал им, а теперь Бог становится человеком, чтобы сделать Адама Богом («человек бывает Бог, да Бога Адама соделает»).<br/> Сима продолжала:<br/> — Сейчас я вам еще кое-что скажу на ту же тему. А пока небольшое отступление. В отношении забот о трудящихся, охраны матери, борьбы с властью наживы, наше революционное время — небывалое, незабвенное время с надолго, навсегда остающимися приобретениями. Что же касается до понимания жизни, до философии счастья, насаждаемой сейчас, просто не верится, что это говорится всерьез, такой это смешной пережиток. Эти декламации о вождях и народах могли бы вернуть нас к ветхозаветным временам скотоводческих племен и патриархов, если бы обладали силой повернуть жизнь вспять и отбросить историю назад на тысячелетия. По счастью это невозможно.<br/> Несколько слов о Христе и Магдалине. Это не из евангельского рассказа о ней, а из молитв на Страстной неделе, кажется, в Великий вторник или среду. Но вы все это и без меня хорошо знаете, Лариса Федоровна. Я просто хочу кое-что напомнить вам, а совсем не собираюсь поучать вас.<br/> Страсть по-славянски, как вы прекрасно знаете, значит прежде всего страдание, страсти Господни, «грядый Господь к вольной страсти» (Господь, идучи на добровольную муку). Кроме того, это слово употребляется в позднейшем русском значении пороков и вожделений. «Страстем поработив достоинство души моея, скот бых», «Изринувшеся из рая, воздержанием страстей потщимся внити», и т. д. Наверное, я очень испорченная, но я не люблю предпасхальных чтений этого направления, посвященных обузданию чувственности и умерщвлению плоти. Мне всегда кажется, что эти грубые, плоские моления, без присущей другим духовным текстам поэзии, сочиняли толстопузые лоснящиеся монахи. И дело не в том, что сами они жили не по правилам и обманывали других. Пусть бы жили они и по совести. Дело не в них, а в содержании этих отрывков. Эти сокрушения придают излишнее значение разным немощам тела и тому, упитано ли оно или измождено. Это противно. Тут какая-то грязная, несущественная второстепенность возведена на недолжную, несвойственную ей высоту. Извините, что я так оттягиваю главное. Сейчас я вознагражу вас за свое промедление.<br/> Меня всегда занимало, отчего упоминание о Магдалине помещают в самый канун Пасхи, на пороге Христовой кончины и его воскресения. Я не знаю причины, но напоминание о том, что такое есть жизнь, так своевременно в миг прощания с нею и в преддверии её возвращения. Теперь послушайте, с какой действительной страстью, с какой ни с чем не считающейся прямотой делается это упоминание.<br/> Существует спор, Магдалина ли это, или Мария Египетская, или какая-нибудь другая Мария. Как бы то ни было, она просит Господа: «Разреши долг, якоже и аз власы». То есть: «отпусти мою вину, как я распускаю волосы». Как вещественно выражена жажда прощения, раскаяния! Можно руками дотронуться.<br/> И сходное восклицание в другом тропаре на тот же день, более подробном, и где речь с большею несомненностью идет о Магдалине.<br/> Здесь она со страшной осязательностью сокрушается о прошлом, о том, что каждая ночь разжигает её прежние закоренелые замашки. «Яко нощь мне есть разжение блуда невоздержанна, мрачное же и безлунное рачение греха». Она просит Христа принять её слезы раскаяния и склониться к её воздыханиям сердечным, чтобы она могла отереть пречистые его ноги волосами, в шум которых укрылась в раю оглушенная и пристыженная Ева. «Да облобыжу пречистые Твои нозе и отру сия паки главы моея власы, их же Ева в рай, пополудни шумом уши огласивше, страхом скрыся». И вдруг вслед за этими волосами, вырывающееся восклицание: «Грехов моих множества, судеб твоих бездны кто исследит?» Какая короткость, какое равенство Бога и жизни, Бога и личности, Бога и женщины!

