### 18 {-}

Юрий Андреевич пришел с вокзала усталый. Это был его ежедекадный выходной день. Обыкновенно он по этим числам отсыпался за всю неделю. Он сидел, откинувшись на диване, временами принимая полулежачее положение или совсем растягиваясь на нем. Хотя Симу он слушал сквозь приступы набегающей дремоты, её рассуждения доставляли ему наслаждение.<br/> «Конечно, все это от дяди Коли, — думал он. — Но какая талантливая и умница!»<br/> Он соскочил с дивана и подошел к окну. Оно выходило во двор, как в комнате рядом, где Лара с Симушкой теперь невнятно шептались.<br/> Погода портилась. На дворе темнело. На двор залетели и стали летать, высматривая, где им сесть, две сороки. Ветер слегка пушил и раздувал их перья. Сороки опустились на крышу мусорного ящика, перелетели на забор, слетели на землю и стали ходить по двору.<br/> «Сороки к снегу», — подумал доктор. В ту же минуту он услышал из-за портьеры:<br/> — Сороки к вестям, — обращалась Сима к Ларе. — К вам гости собираются. Или письмо получите.<br/> Спустя немного снаружи позвонили в дверной колокольчик на проволоке, который незадолго перед тем починил Юрий Андреевич.<br/> Из-за портьеры вышла Лариса Федоровна и быстрыми шагами пошла отпирать в переднюю. По её разговору у входной двери Юрий Андреевич понял, что пришла сестра Симы, Глафира Севериновна.<br/> — Вы за сестрою? — спросила Лариса Федоровна. — Симушка у нас.<br/> — Нет, не за ней. А впрочем, что же. Вместе пойдем, если она домой собирается. Нет, я совсем не за тем. Письмо вашему приятелю. Пусть спасибо скажет, что я когда-то на почте служила. Через сколько рук прошло, и по знакомству в мои попало. Из Москвы. Пять месяцев шло. Не могли разыскать адресата. А я ведь знаю, кто он. Брился как-то у меня.<br/> Письмо, длинное, на многих страницах, смятое, замасленное, в распечатанном и истлевшем конверте, было от Тони. До сознания доктора не дошло, как оно у него очутилось, он не заметил, как Лара вручила ему конверт. Когда доктор начал читать письмо, он еще помнил, в каком он городе и у кого в доме, но по мере чтения утрачивал это понимание. Вышла, поздоровалась и стала с ним прощаться Сима. Машинально он отвечал, как полагается, но не обратил на нее внимания. Ее уход выпал из его сознания. Постепенно он все более полно забывал, где он и что кругом него.<br/> «Юра, — писала ему Антонина Александровна, — знаешь ли ты, что у нас есть дочь? Ее крестили Машей, в память мамы покойницы Марии Николаевны.<br/> Теперь совсем о другом. Несколько видных общественных деятелей, профессоров из кадетской партии и правых социалистов, Мельгунова, Кизеветтера, Кускову, некоторых других, а также дядю Николая Александровича Громеко, папу и нас, как членов его семьи, высылают из России за границу.<br/> Это — несчастие, в особенности в отсутствии тебя, но надо подчиниться и благодарить Бога за такую мягкую форму изгнания в такое страшное время, могло ведь быть гораздо хуже. Если бы ты нашелся и был тут, ты поехал бы с нами. Но где ты теперь? Я посылаю это письмо по адресу Антиповой, она передаст его тебе, если разыщет. Меня мучит неизвестность, распространят ли на тебя, как на члена нашей семьи, впоследствии, когда ты, если это суждено, найдешься, разрешение на выезд, полученное всеми нами. Мне верится, что ты жив и отыщешься. Это мне подсказывает мое любящее сердце и я доверяюсь его голосу.<br/> Возможно, к тому времени, когда ты обнаружишься, условия жизни в России смягчатся, ты сам сможешь исхлопотать себе отдельное разрешение на заграничную поездку, и все мы опять окажемся в сборе в одном месте. Но я пишу это и сама не верю в сбыточность такого счастья.<br/> Все горе в том, что я люблю тебя, а ты меня не любишь. Я стараюсь найти смысл этого осуждения, истолковать его, оправдать, роюсь, копаюсь в себе, перебираю всю нашу жизнь и всё, что я о себе знаю, и не вижу начала и не могу вспомнить, что я сделала и чем навлекла на себя это несчастье. Ты как-то превратно, недобрыми глазами смотришь на меня, ты видишь меня искаженно, как в кривом зеркале.<br/> А я люблю тебя. Ах как я люблю тебя, если бы ты только мог себе представить! Я люблю всё особенное в тебе, всё выгодное и невыгодное, все обыкновенные твои стороны, дорогие в их необыкновенном соединении, облагороженное внутренним содержанием лицо, которое без этого, может быть, казалось бы некрасивым, талант и ум, как бы занявшие место начисто отсутствующей воли. Мне все это дорого, и я не знаю человека лучше тебя.<br/> Но слушай, знаешь, что я скажу тебе? Если бы даже ты не был так дорог мне, если бы ты не нравился мне до такой степени, все равно прискорбная истина моего холода не открылась бы мне, все равно я думала бы, что люблю тебя. Из одного страха перед тем, какое унизительное, уничтожающее наказание нелюбовь, я бессознательно остереглась бы понять, что не люблю тебя. Ни я ни ты никогда этого бы не узнали. Мое собственное сердце скрыло бы это от меня, потому что нелюбовь почти как убийство, и я никому не в силах была бы нанести этого удара.<br/> Хотя ничего не решено еще окончательно, мы, наверное, едем в Париж. Я попаду в далекие края, куда тебя возили мальчиком и где воспитывались папа и дядя. Папа кланяется тебе. Шура вырос, не взял красотой, но стал большим крепким мальчиком и при упоминании о тебе всегда горько безутешно плачет. Не могу больше. Сердце надрывается от слез. Ну прощай. Дай перекрещу тебя на всю нескончаемую разлуку, испытания, неизвестность, на весь твой долгий, долгий, темный путь. Ни в чем не виню, ни одного упрека, сложи жизнь свою так, как тебе хочется, только бы тебе было хорошо.<br/> Перед отъездом с этого страшного и такого рокового для нас Урала я довольно коротко узнала Ларису Федоровну. Спасибо ей, она была безотлучно при мне, когда мне было трудно, и помогла мне при родах. Должна искренне признать, она хороший человек, но не хочу кривить душой, — полная мне противоположность. Я родилась на свет, чтобы упрощать жизнь и искать правильного выхода, а она, чтобы осложнять её и сбивать с дороги.<br/> Прощай, надо кончать. Пришли за письмом и пора укладываться. О Юра, Юра, милый, дорогой мой, муж мой, отец детей моих, да что же это такое? Ведь мы больше никогда, никогда не увидимся. Вот я написала эти слова, уясняешь ли ты себе их значение? Понимаешь ли ты, понимаешь ли ты? Торопят, и это точно знак, что пришли за мной, чтобы вести на казнь. Юра!<br/> Юра!»<br/> Юрий Андреевич поднял от письма отсутствующие бесслезные глаза, никуда не устремленные, сухие от горя, опустошенные страданием. Он ничего не видел кругом, ничего не сознавал.<br/> За окном пошел снег. Ветер нес его по воздуху вбок, все быстрее и все гуще, как бы этим все время что-то наверстывая, и Юрий Андреевич так смотрел перед собой в окно, как будто это не снег шел, а продолжалось чтение письма Тони и проносились и мелькали не сухие звездочки снега, а маленькие промежутки белой бумаги между маленькими черными буковками, белые, белые, без конца, без конца.<br/> Юрий Андреевич непроизвольно застонал и схватился за грудь.<br/> Он почувствовал, что падает в обморок, сделал несколько ковыляющих шагов к дивану и повалился на него без сознания.

