## ЧАСТЬ четырнадцатая. ОПЯТЬ В ВАРЫКИНЕ {-}

### 1 {-}

Установилась зима. Валил снег крупными хлопьями. Юрий Андреевич пришел домой из больницы.<br/> — Комаровский приехал, — упавшим хриплым голосом сказала вышедшая навстречу ему Лара. Они стояли в передней. У нее был потерянный вид, точно у побитой.<br/> — Куда? К кому? Он у нас?<br/> — Нет, конечно. Он был утром и хотел прийти вечером. Он скоро заявится. Ему надо поговорить с тобой.<br/> — Зачем он приехал?<br/> — Я не все поняла из его слов. Говорит, будто он тут проездом на Дальний Восток, и нарочно дал крюку и своротил к нам в Юрятин, чтобы повидаться. Главным образом, ради тебя и Паши. Он много говорил о вас обоих. Он уверяет, что все мы втроем, то есть ты, Патуля и я в смертельной опасности, и что только он может спасти нас, если мы его послушаемся.<br/> — Я уйду. Я не желаю его видеть.<br/> Лара расплакалась, попыталась упасть перед доктором на колени и, обняв его ноги, прижаться к ним головою, но он помешал ей, насильно удержав ее.<br/> — Останься ради меня, умоляю тебя. Я ни с какой стороны не боюсь очутиться с глазу на глаз с ним. Но это тягостно. Избавь меня от встречи с ним наедине. Кроме того, это человек практический, бывалый. Может быть, он действительно посоветует что-нибудь. Твое отвращение к нему естественно. Но прошу тебя, пересиль себя. Останься.<br/> — Что с тобою, ангел мой? Успокойся. Что ты делаешь? Не бросайся на колени. Встань. Развеселись. Прогони преследующее тебя наваждение. Он на всю жизнь запугал тебя. Я с тобою. Если нужно, если ты мне прикажешь, я убью его.<br/> Через полчаса наступил вечер. Стало совершенно темно. Уже с полгода дыры в полу были везде заколочены. Юрий Андреевич следил за образованием новых и во-время забивал их. В квартире завели большого пушистого кота, проводившего время в неподвижной загадочной созерцательности. Крысы не ушли из дому, но стали осторожнее.<br/> В ожидании Комаровского Лариса Федоровна нарезала черного пайкового хлеба и поставила на стол тарелку с несколькими вареными картофелинами. Гостя собирались принять в бывшей столовой старых хозяев, оставшейся в прежнем назначении. В ней стояли больших размеров дубовый обеденный стол и большой тяжелый буфет того же темного дуба. На столе горела касторка в пузырьке с опущенным в нее фитилем, — переносная докторская светильня.<br/> Комаровский пришел из декабрьской темноты весь осыпанный валившим на улице снегом. Снег слоями отваливался от его шубы, шапки и калош и пластами таял, разводя на полу лужи. От налипшего снега мокрые усы и борода, которые Комаровский раньше брил, а теперь отпустил, казались шутовскими, скоморошьими. На нем была хорошо сохранившаяся пиджачная пара и полосатые брюки в складку. Перед тем, как поздороваться и что-нибудь сказать, он долго расчесывал карманною гребенкой влажные примятые волосы и утирал и приглаживал носовым платком мокрые усы и брови. Потом с выражением молчаливой многозначительности одновременно протянул обе руки, левую — Ларисе Федоровне, а правую — Юрию Андреевичу.<br/> — Будем считать, что мы знакомы, — обратился он к Юрию Андреевичу. — Я ведь так хорош был с вашим отцом, — вы, наверное, знаете. На моих руках дух испустил. Все вглядываюсь в вас, ищу сходства. Нет, видимо, вы не в батюшку. Широкой натуры был человек. Порывистый, стремительный. Судя по внешности, вы скорее в матушку. Мягкая была женщина.<br/> Мечтательница.<br/> — Лариса Федоровна просила выслушать вас. По её словам, у вас ко мне какое-то дело. Я уступил её просьбе. Наш разговор поневоле вынужденный. По своей охоте я не искал бы знакомства с нами, и не считаю, что мы познакомились. Поэтому ближе к делу. Что вам угодно?<br/> — Здравствуйте, хорошие мои. Всё, решительно всё чувствую и насквозь, до конца всё понимаю. Простите за смелость, вы страшно друг к другу подходите. В высшей степени гармоническая пара.<br/> — Должен остановить вас. Прошу не вмешиваться в вещи, вас не касающиеся. У вас не спрашивают сочувствия. Вы забываетесь.<br/> — А вы не вспыхивайте так сразу, молодой человек. Нет, пожалуй, вы все же скорее в отца. Такой же пистолет и порох.<br/> Да, так с вашего позволения, поздравляю вас, дети мои. К сожалению однако вы не только по моему выражению, но и на самом деле дети, ничего не ведающие, ни о чем не задумывающиеся. Я тут только два дня и узнал больше о вас, чем вы сами подозреваете. Вы, не помышляя о том, ходите по краю пропасти. Если чем-нибудь не предотвратить опасности, дни вашей свободы, а может быть, и жизни сочтены.<br/> Есть некоторый коммунистический стиль. Мало кто подходит под эту мерку. Но никто так явно не нарушает этой манеры жить и думать, как вы, Юрий Андреевич. Не понимаю, зачем гусей дразнить. Вы — насмешка над этим миром, его оскорбление.<br/> Добро бы это было вашей тайной. Но тут есть влиятельные люди из Москвы. Нутро ваше им известно досконально. Вы оба страшно не по вкусу здешним жрецам Фемиды. Товарищи Антипов и Тиверзин точат зубы на Ларису Федоровну и на вас.<br/> Вы мужчина, вы — вольный казак, или как это там называется. Сумасбродствовать, играть своею жизнью ваше священное право. Но Лариса Федоровна человек несвободный. Она мать. На руках у нее детская жизнь, судьба ребенка.<br/> Фантазировать, витать за облаками ей не положено.<br/> Я всё утро потерял на уговоры, убеждая её отнестись серьезнее к здешней обстановке. Она не желает меня слушать.<br/> Употребите свой авторитет, повлияйте на Ларису Федоровну. Она не вправе шутить безопасностью Катеньки, не должна пренебрегать моими соображениями.<br/> — Я никогда никого в жизни не убеждал и не неволил. В особенности близких. Лариса Федоровна вольна слушать вас или нет. Это её дело. Кроме того, ведь я совсем не знаю о чем речь. То, что вы называете вашими соображениями, неизвестно мне.<br/> — Нет, вы мне все больше и больше напоминаете вашего отца.<br/> Такой же несговорчивый. Итак, перейдем к главному. Но так как это довольно сложная материя, запаситесь терпением. Прошу слушать и не перебивать.<br/> Наверху готовятся большие перемены. Нет, нет, это у меня из самого достоверного источника, можете не сомневаться. Имеется в виду переход на более демократические рельсы, уступка общей законности, и это дело самого недалекого будущего.<br/> Но именно вследствие этого, подлежащие отмене карательные учреждения будут под конец тем более свирепствовать и тем торопливее сводить свои местные счеты. Ваше уничтожение на очереди, Юрий Андреевич. Ваше имя в списке. Говорю это не шутя, я сам видел, можете мне поверить. Подумайте о вашем спасении, а то будет поздно.<br/> Но все это было пока предисловием. Перехожу к существу дела.<br/> В Приморье, на Тихом океане, происходит стягивание политических сил, оставшихся верными свергнутому Временному правительству и распущенному Учредительному собранию.<br/> Съезжаются думцы, общественные деятели, наиболее видные из былых земцев, дельцы, промышленники. Добровольческие генералы сосредоточивают тут остатки своих армий.<br/> Советская власть сквозь пальцы смотрит на возникновение Дальневосточной республики. Существование такого образования на окраине ей выгодно в качестве буфера между Красной Сибирью и внешним миром. Правительство республики будет смешанного состава. Больше половины мест из Москвы выговорили коммунистам, с тем, чтобы с их помощью, когда это будет удобно, совершить переворот и прибрать республику к рукам.<br/> Замысел совершенно прозрачный, и дело только в том, чтобы суметь воспользоваться остающимся временем.<br/> Я когда-то до революции вел дела братьев Архаровых, Меркуловых и других торговых и банкирских домов во Владивостоке. Меня там знают. Негласный эмиссар составляющегося правительства, наполовину тайно, наполовину при официальном советском попустительстве, привез мне приглашение войти министром юстиции в Дальневосточное правительство. Я согласился и еду туда. Все это, как я только что сказал, происходит с ведома и молчаливого согласия Советской власти, однако не так откровенно, и об этом не надо шуметь.<br/> Я могу взять вас и Ларису Федоровну с собой. Оттуда вы легко проберетесь морем к своим. Вы, конечно, уже знаете об их высылке. Громкая история, об этом говорит вся Москва. Ларисе Федоровне я обещал отвести удар, нависающий над Павлом Павловичем. Как член самостоятельного и признанного правительства я разыщу Стрельникова в Восточной Сибири и буду способствовать его переходу в нашу автономную область. Если ему не удастся бежать, я предложу, чтобы его выдали в обмен на какое-нибудь лицо, задержанное союзниками и представляющее ценность для Московской центральной власти.<br/> Лариса Федоровна с трудом следила за содержанием разговора, смысл которого часто ускользал от нее. Но при последних словах Комаровского, касавшихся безопасности доктора и Стрельникова, Она вышла из состояния задумчивой непричастности, насторожилась и, чуть-чуть покраснев, вставила:<br/> — Ты понимаешь, Юрочка, как эти затеи важны в отношении тебя и Паши?<br/> — Ты слишком доверчива, мой дружок. Нельзя едва задуманное принимать за совершившееся. Я не говорю, что Виктор Ипполитович сознательно нас водит за нос. Но ведь все это вилами на воде писано! А теперь, Виктор Ипполитович, несколько слов от себя. Благодарю вас за внимание к моей судьбе, но неужели вы думаете, что я дам вам устраивать ее? Что же касается вашей заботы о Стрельникове, Ларе следует об этом подумать.<br/> — К чему клонится вопрос? Ехать ли нам с ним, как он предлагает, или нет. Ты прекрасно знаешь, что без тебя я не поеду.<br/> Комаровский часто прикладывался к разведенному спирту, который принес из амбулатории и поставил на стол Юрий Андреевич, жевал картошку и постепенно хмелел.

