### 2 {-}

Было уже поздно. Освобождаемый временами от нагара фитилек светильни с треском разгорался, ярко освещая комнату. Потом всё снова погружалось во мрак. Хозяевам хотелось спать и надо было поговорить наедине. А Комаровский всё не уходил. Его присутствие томило, как давил вид тяжелого дубового буфета и как угнетала ледяная декабрьская темнота за окном.<br/> Он смотрел не на них, а куда-то поверх их голов, уставив пьяные округлившиеся глаза в эту далекую точку, и сонным заплетающимся языком молол и молол что-то нескончаемо скучное всё про одно и то же. Его коньком был теперь Дальний Восток.<br/> Об этом он и жевал свою жвачку, развивая Ларе и доктору свои соображения о политическом значении Монголии.<br/> Юрий Андреевич и Лариса Федоровна не уследили, в каком месте разговора он на эту Монголию напал. То, что они прозевали, как он к ней перескочил, увеличивало докучность чуждой посторонней темы.<br/> Комаровский говорил:<br/> — Сибирь, это поистине Новая Америка, как её называют, таит в себе богатейшие возможности. Это колыбель великого русского будущего, залог нашей демократизации, процветания, политического оздоровления. Еще более чревато манящими возможностями будущее Монголии, Внешней Монголии, нашей великой дальневосточной соседки. Что вы о ней знаете? Вы не стыдитесь зевать и без внимания хлопаете глазами, а между тем это поверхность в полтора миллиона квадратных верст, неизведанные ископаемые, страна в состоянии доисторической девственности, к которой тянутся жадные руки Китая, Японии и Америки, в ущерб нашим русским интересам, признаваемым всеми соперниками, при любом разделе сфер влияния в этом далеком уголке земного шара.<br/> Китай извлекает пользу из феодально-теократической отсталости Монголии, влияя на её лам и хутухт. Япония опирается на тамошних князей крепостников, по-монгольски — хошунов. Красная коммунистическая Россия находит союзника в лице хамджилса, иначе говоря, революционной ассоциации восставших пастухов Монголии. Что касается меня, я хотел бы видеть Монголию действительно благоденствующею, под управлением свободно избранного хурултая. Лично нас должно занимать следующее. Шаг через монгольскую границу, и мир у ваших ног, и вы — вольная птица.<br/> Многословные умствования на назойливую, никакого отношения к ним не имеющую тему раздражали Ларису Федоровну. Доведенная скукой затянувшегося посещения до изнеможения, она решительно протянула Комаровскому руку для прощания и без обиняков, с нескрываемой неприязнью, сказала:<br/> — Поздно. Вам пора уходить. Я хочу спать.<br/> — Надеюсь, вы не будете так негостеприимны, и не выставите меня за дверь в такой час. Я не уверен, найду ли дорогу ночью в чужом неосвещенном городе.<br/> — Надо было раньше об этом думать и не засиживаться. Никто вас не удерживал.<br/> — О, зачем вы говорите со мною так резко? Вы даже не спросили, располагаю ли я тут каким-нибудь пристанищем?<br/> — Решительно неинтересно. Авось себя в обиду не дадите.<br/> Если же вы напрашиваетесь на ночевку, то в общей комнате, где мы спим вместе с Катенькой, я вас не положу. А в остальных с крысами не будет сладу.<br/> — Я не боюсь их.<br/> — Ну, как знаете.

