### 3 {-}

— Что с тобою, ангел мой? Которую уже ночь ты не спишь, не дотрагиваешься за столом до пищи, весь день ходишь как шальная. И все думаешь, думаешь. Что преследует тебя? Нельзя давать такой воли тревожным мыслям.<br/> — Опять был из больницы сторож Изот. У него тут в доме шуры-муры с прачкою. Вот он мимоходом и завернул, утешил.<br/> Страшный, говорит, секрет. Не миновать твоему темной. Так и ждите, не сегодня-завтра упекут. А следом и тебя, горемычную.<br/> Откуда, говорю, Изот, ты это взял? Уж положись, будь покойна, говорит. Из полкана сказывали. Под полканом, как ты, может быть, догадываешься, надо в его парафразе понимать исполком.<br/> Лариса Федоровна и доктор рассмеялись.<br/> — Он совершенно прав. Опасность назрела и уже у порога.<br/> Надо немедленно исчезнуть. Вопрос только в том, куда именно.<br/> Пытаться уехать в Москву нечего и думать. Это слишком сложные сборы, и они привлекут внимание. А надо шито-крыто, чтобы никто ничего не увидел. Знаешь что, моя радость? Пожалуй, воспользуемся твоей мыслью. На какое-то время нам надо провалиться сквозь землю. Пускай этим местом будет Варыкино.<br/> Уедем туда недели на две, на месяц.<br/> — Спасибо, родной, спасибо. О как я рада. Я понимаю, как все в тебе должно быть против этого решения. Но речь ведь не о вашем доме. Жизнь в нем была бы для тебя действительно немыслима. Вид опустелых комнат, укоры, сравнения. Разве я не понимаю? Строить счастье на чужом страдании, топтать то, что душе дорого и свято. Я никогда не приняла бы от тебя такой жертвы. Но дело не в этом. Ваш дом в таком разрушении что едва ли можно было бы привести комнаты в жилое состояние. Я скорее имела в виду покинутое Микулицынское жилище.<br/> — Все это правда. Спасибо за чуткость. Но погоди минуту. Я все время хочу спросить и все забываю. Где Комаровский? Он еще тут или уже уехал? С моей ссоры с ним и после того, как я спустил его с лестницы, я больше ничего о нем не слышал.<br/> — Я тоже ничего не знаю. А Бог с ним. На что он тебе?<br/> — Я все больше прихожу к мысли, что нам по разному надо было отнестись к его предложению. Мы не в одинаковом положении. На твоем попечении дочь. Даже если бы ты хотела разделить мою гибель, ты не вправе себе это позволить.<br/> Но перейдем к Варыкину. Разумеется, забираться в эту одичалую глушь суровой зимой без запасов, без сил, без надежд — безумие из безумий. Но давай и безумствовать, сердце мое, если ничего, кроме безумства, нам не осталось. Унизимся еще раз. Выклянчим у Анфима лошадь. Попросим у него, или даже не у него, а у состоящих под его начальством спекулянтов, муки и картошки в некий, никакою верою не оправдываемый долг.<br/> Уговорим его не сразу, не тотчас возмещать своим приездом оказанное нам благодеяние, а приехать только к концу, когда лошадь понадобится ему обратно. Побудем немного одни. Поедем, сердце мое. Сведем и спалим в неделю лесной косяк, которого хватило бы на целый год более совестливого хозяйничанья.<br/> И еще и еще раз. Прости меня за прорывающееся в моих словах смятение. Как бы мне хотелось говорить с тобою без этого дурацкого пафоса! Но ведь у нас действительно нет выбора.<br/> Называй её как хочешь, гибель действительно стучится в наши двери. Только считанные дни в нашем распоряжении.<br/> Воспользуемся же ими по своему. Потратим их на проводы жизни, на последнее свидание перед разлукою. Простимся со всем, что нам было дорого, с нашими привычными понятиями, с тем, как мы мечтали жить и чему нас учила совесть, простимся с надеждами, простимся друг с другом. Скажем еще раз друг другу наши ночные тайные слова, великие и тихие, как название азиатского океана.<br/> Ты недаром стоишь у конца моей жизни, потаенный, запретный мой ангел, под небом войн и восстаний, ты когда-то под мирным небом детства так же поднялась у её начала.<br/> Ты тогда ночью, гимназисткой последних классов в форме кофейного цвета, в полутьме за номерной перегородкой, была совершенно тою же, как сейчас, и так же ошеломляюще хороша.<br/> Часто потом в жизни я пробовал определить и назвать тот свет очарования, который ты заронила в меня тогда, тот постепенно тускнеющий луч и замирающий звук, которые с тех пор растеклись по всему моему существованию и стали ключом проникновения во все остальное на свете, благодаря тебе.<br/> Когда ты тенью в ученическом платье выступила из тьмы номерного углубления, я, мальчик, ничего о тебе не знавший, всей мукой отозвавшейся тебе силы понял: эта щупленькая, худенькая девочка заряжена, как электричеством, до предела, всей мыслимою женственностью на свете. Если подойти к ней близко или дотронуться до нее пальцем, искра озарит комнату и либо убьет на месте, либо на всю жизнь наэлектризует магнетически влекущейся, жалующейся тягой и печалью. Я весь наполнился блуждающими слезами, весь внутренне сверкал и плакал. Мне было до смерти жалко себя, мальчика, и еще более жалко тебя, девочку. Все мое существо удивлялось и спрашивало: если так больно любить и поглощать электричество, как, вероятно, еще больнее быть женщиной, быть электричеством, внушать любовь.<br/> Вот, наконец, я это высказал. От этого можно с ума сойти. И я весь в этом.<br/> Лариса Федоровна лежала на краю кровати, одетая и недомогающая. Она свернулась калачиком и накрылась платком.<br/> Юрий Андреевич сидел на стуле рядом и говорил тихо, с большими перерывами. Иногда Лариса Федоровна приподнималась на локте, подпирала подбородок ладонью и, разинув рот, смотрела на Юрия Андреевича. Иногда прижималась к его плечу и, не замечая своих слез, плакала тихо и блаженно. Наконец она потянулась к нему, перевесившись за борт кровати, и радостно прошептала:<br/> — Юрочка! Юрочка! Какой ты умный. Ты всё знаешь, обо всем догадываешься. Юрочка, ты моя крепость и прибежище и утверждение, да простит Господь мое кощунство. О как я счастлива! Едем, едем, дорогой мой. Там на месте я скажу тебе, что меня беспокоит.<br/> Он решил, что она намекает на свои предположения о беременности, вероятно, мнимой, и сказал:<br/> — Я знаю.

