### 4 {-}

Они выехали из города утром серого зимнего дня. День был будничный. Люди шли по улицам по своим делам. Часто попадались знакомые. На бугристых перекрестках, у старых водоразборных будок вереницами стояли бесколодезные жительницы с отставленными в сторону ведрами и коромыслами, дожидаясь очереди за водою. Доктор сдерживал рвавшуюся вперед Самдевятовскую Савраску, желтовато-дымчатую курчавую вятку, которою он правил, осторожно объезжая толпившихся хозяек.<br/> Разогнавшиеся сани скатывались боком с горбатой, заплесканной водою и обледенелой мостовой и наезжали на тротуары, стукаясь санными отводами о фонари и тумбы.<br/> На всем скаку нагнали шедшего по улице Самдевятова, пролетели мимо и не оглянулись, чтобы удостовериться, узнал ли он их и свою лошадь и не кричит ли чего-нибудь вдогонку. В другом месте таким же образом, не здороваясь, обогнали Комаровского, попутно установив, что он еще в Юрятине.<br/> Глафира Тунцева прокричала через всю улицу с противоположного тротуара:<br/> — А говорили, вы вчера уехали. Вот и верь после этого людям. За картошкой? — и, выразив рукою, что она не слышит ответа, она помахала ею вслед напутственно.<br/> Ради Симы попробовали задержаться на горке, в неудобном месте, где трудно было остановиться. Лошадь и без того все время приходилось осаживать, туго натягивая возжи. Сима сверху донизу была обмотана двумя или тремя платками, придававшими окоченелость круглого полена её фигуре. Прямыми негнущимися шагами она подошла к саням на середину мостовой и простилась, пожелав им счастливо доехать.<br/> — Когда воротитесь, надо будет поговорить, Юрий Андреевич.<br/> Наконец, выехали из города. Хотя Юрий Андреевич, бывало, ездил по этой дороге зимою, он преимущественно помнил её в летнем виде и теперь не узнавал.<br/> Мешки с провизией и остальную кладь засунули глубоко в сено, к переду саней, под головки, и там надежно приторочили.<br/> Юрий Андреевич правил, либо стоя на коленях на дне развалистых пошевней, по местному — кошовки, либо сидя боком на ребре кузова и свесив ноги в Самдевятовских валенках наружу.<br/> После полудня, когда с зимней обманчивостью задолго до заката стало казаться, что день клонится к концу, Юрий Андреевич стал немилосердно нахлестывать Савраску. Она понеслась стрелою. Кошовка лодкою взлетала вверх и вниз, ныряя по неровностям разъезженной дороги. Катя и Лара были в шубах, сковывавших движения. На боковых наклонах и ухабах они вскрикивали и смеялись до колик, перекатываясь с одного края саней на другой и неповоротливыми кулями зарываясь в сено.<br/> Иногда доктор нарочно, для смеху, переворачивал сани набок и, без всякого вреда для них, вываливал Лару и Катю в снег. Сам он, протащившись несколько шагов на возжах по дороге, останавливал Савраску, выравнивал и ставил сани на оба полоза и получал нахлобучку от Лары и Кати, которые отряхивались, садились в сани, смеялись и сердились.<br/> — Я покажу вам место, где меня остановили партизаны, — пообещал им доктор, когда отъехали достаточно от города, но не мог сделать обещанного, потому что зимняя голизна лесов, мертвый покой и пустота кругом меняли местность до неузнаваемости. — Вот! — вскоре воскликнул он, по ошибке приняв первый дорожный столб Моро и Ветчинкина, стоявший в поле, за второй, в лесу, у которого его захватили. Когда же они промчались мимо этого второго, остававшегося на прежнем месте, в чаще у Сакминского распутья, столба нельзя было распознать сквозь рябившую в глазах решетку густого инея, филигранно разделявшего лес под серебро с чернью. И столба не заметили.<br/> В Варыкино влетели засветло и стали у старого Живаговского дома, так как по дороге он был первым, ближе Микулицынского.<br/> Ворвались в дом торопливо, как грабители, — скоро должно было стемнеть. Внутри было уже темно. Половины разрушений и мерзости Юрий Андреевич второпях не разглядел. Часть знакомой мебели была цела. В пустом Варыкине уже некому было доводить до конца начатое разрушение. Из домашнего имущества Юрий Андреевич ничего не обнаружил. Но его ведь не было при отъезде семьи, он не знал, что они взяли с собою, что оставили. Лара между тем говорила:<br/> — Надо торопиться. Сейчас настанет ночь. Некогда раздумывать. Если располагаться тут, то — лошадь в сарай, провизию в сени, а нам сюда, в эту комнату. Но я противница такого решения. Мы достаточно об этом говорили. Тебе, а значит и мне, будет тяжело. Что тут такое, ваша спальня? Нет, детская. Кроватка твоего сына. Для Кати будет мала. С другой стороны, — окна целы, стены и потолок без щелей. Кроме того, великолепная печь, я уже восхищалась ею в прошлый приезд. И если ты настаиваешь, чтобы все-таки тут, хотя я против этого, тогда я — шубу долой и мигом за дело. И первым делом за топку. Топить, топить и топить. Первые сутки день и ночь не переставая. Но что с тобою, мой милый. Ты ничего не отвечаешь.<br/> — Сейчас. Ничего. Прости пожалуйста. Нет, знаешь, действительно посмотрим лучше у Микулицыных.<br/> И они проехали дальше.

