### 5 {-}

Дом Микулицыных был заперт на висячий замок, навешенный в уши дверного засова. Юрий Андреевич долго отбивал его и вырвал с мясом, вместе с оставшеюся на винтах отщепившейся древесиной. Как и в предшествующий дом, внутрь ввалились второпях, не раздеваясь, и в шубах, шапках и валенках прошли вглубь комнат.<br/> В глаза сразу бросилась печать порядка, лежавшая на вещах в некоторых углах дома, например, в кабине Аверкия Степановича.<br/> Тут кто-то жил, и совсем еще недавно. Но кто именно? Если хозяева или кто-нибудь один из них, то куда они девались и почему наружную дверь заперли не на врезанный в нее замок, а приделанный висячий? Кроме того, если бы это были хозяева и жили тут долго и постоянно, дом убран был бы весь сплошь, а не отдельными частями. Что-то говорило вторгшимся, что это не Микулицыны. В таком случае кто же? Доктора и Лару неизвестность не беспокоила. Они не стали ломать над этим голову. Мало ли было теперь брошенных жилищ с наполовину растащенной движимостью? Мало укрывающихся преследуемых?<br/> «Какой-нибудь разыскиваемый белый офицер», — единодушно решили они. — «Придет, уживемся, столкуемся».<br/> И опять, как когда-то, Юрий Андреевич застыл, как вкопанный, на пороге кабинета, любуясь его поместительностью и удивляясь ширине и удобству рабочего стола у окна. И опять подумал, как располагает, наверное, и приохочивает такой строгий уют к терпеливой, плодотворной работе.<br/> Среди служб во дворе у Микулицыных имелась вплотную к сараю пристроенная конюшня. Но она была на запоре, Юрий Андреевич не знал, в каком она состоянии. Чтобы не терять времени, он решил на первую ночь поставить лошадь в легко отворившийся незапертый сарай. Он распряг Савраску, и когда она остыла, напоил её принесенною из колодца водою. Юрий Андреевич хотел задать ей сена со дна саней, но оно стерлось под седоками в труху, и в корм лошади не годилось. По счастью, на широком, помещавшемся над сараем и конюшнею, сеновале нашлось достаточно сена вдоль стен и по углам.<br/> Ночь проспали под шубами, не раздеваясь, блаженно, крепко и сладко, как спят дети после целого дня беготни и проказ.

