### 6 {-}

Когда встали, Юрий Андреевич стал с утра заглядываться на соблазнительный стол у окна. У него так и чесались руки засесть за бумагу. Но это право он облюбовал себе на вечер, когда Лара и Катенька лягут спать. А до тех пор, чтобы привести хотя две комнаты в порядок, дела было по уши.<br/> В мечтах о вечерней работе он не задавался важными целями.<br/> Простая чернильная страсть, тяга к перу и письменным занятиям владела им.<br/> Ему хотелось помарать, построчить что-нибудь. На первых порах он удовлетворился бы припоминаньем и записью чего-нибудь старого, незаписанного, чтобы только размять застоявшиеся от бездействия и, в перерыве дремлющие, способности. А там, — надеялся он, — ему и Ларе удастся задержаться тут подольше и времени будет вволю приняться за что-нибудь новое, значительное.<br/> — Ты занят? Что ты делаешь?<br/> — Топлю и топлю. А что?<br/> — Корыто мне.<br/> — Дров по такой топке здесь больше, чем на три дня не хватит. Надо наведаться в наш бывший Живаговский сарай. А ну как там есть еще? Если их осталось порядочно, я в несколько заездов перетащу их сюда. Займусь этим завтра. Ты просила корыто. Представь, попалось где-то на глаза, а где, — из головы вон, ума не приложу.<br/> — И у меня то же самое. Где-то видела и забыла. Верно где-нибудь не на месте, оттого и забывается. Но Бог с ним.<br/> Имей в виду, я много воды грею для уборки. Оставшеюся постираю кое-что для себя и Кати. Давай заодно и всё свое грязное.<br/> Вечером, когда уберемся и уясним ближайшие виды, все перед сном помоемся.<br/> — Сейчас соберу белье. Спасибо. Шкафы и тяжести везде от стен отодвинуты, как ты просила.<br/> — Хорошо. Вместо корыта прополощу в посудной лохани.<br/> Только очень сальная. Надо отмыть жир со стенок.<br/> — Как печка протопится, закрою и вернусь к разборке остальных ящиков. Что ни шаг, то новые находки в столе и комоде. Мыло, спички, карандаши, бумага, письменные принадлежности. И открыто на виду такие же неожиданности.<br/> Например, лампа на столе, налитая керосином. Это не Микулицынское, я ведь знаю. Это из какого-то другого источника.<br/> — Удивительная удача! Это всё он, жилец таинственный. Как из Жюль Верна. Ах, ну что ты скажешь в самом деле! Опять мы заболтались и точим лясы, а у меня бак перекипает.<br/> Они суетились, бросаясь туда и сюда по комнатам, с несвободными, занятыми руками, и набегу натыкались друг на друга или налетали на Катеньку, которая торчала поперек дороги и вертелась под ногами. Девочка слонялась из угла в угол, мешая уборке, и дулась в ответ на замечания. Она зябла и жаловалась на холод.<br/> «Бедные современные дети, жертвы нашей цыганщины, маленькие безропотные участники наших скитаний», — думал доктор, а сам говорил девочке:<br/> — Ну, извини, милая. Нечего ежиться. Вранье и капризы.<br/> Печка раскалена докрасна.<br/> — Печке, может быть, тепло, а мне холодно.<br/> — Тогда потерпи Катюша. Вечером я вытоплю её жарко-прежарко во второй раз, а мама говорит, к тому же искупает еще тебя, ты слышала? А пока на вот, лови. — И он валил в кучу на пол старые Ливериевы игрушки из выхоложенной кладовой, целые и поломанные, кирпичики и кубики, вагоны и паровозы, и разграфленные на клетки, разрисованные и размеченные цифрами куски картона к играм с фишками и игральными костями.<br/> — Ну, что вы, Юрий Андреевич, — как взрослая, обижалась Катенька. — Это всё чужое. И для маленьких. А я большая.<br/> А через минуту она усаживалась поудобнее на середину ковра, и под её руками игрушки всех видов сплошь превращались в строительный материал, из которого Катенька воздвигала привезенной из города кукле Нинке жилище куда с большим смыслом и более постоянное, чем те чужие меняющиеся пристанища, по которым её таскали.<br/> — Какой инстинкт домовитости, неистребимое влечение к гнезду и порядку! — говорила Лариса Федоровна, из кухни наблюдая игру дочери. — Дети искренни без стеснения и не стыдятся правды, а мы из боязни показаться отсталыми готовы предать самое дорогое, хвалим отталкивающее и поддакиваем непонятному.<br/> — Нашлось корыто, — входя с ним из темных сеней, прерывал доктор. — Действительно не на месте было. На полу под протекавшим потолком, с осени, видно, стояло.

