### 7 {-}

На обед, изготовленный впрок на три дня из свеже начатых запасов, Лариса Федоровна подала вещи небывалые, картофельный суп и жареную баранину с картошкой. Разлакомившаяся Катенька не могла накушаться, заливалась смехом и шалила, а потом, наевшись и разомлев от тепла, укрылась маминым пледом и сладко уснула на диване.<br/> Лариса Федоровна, прямо от плиты, усталая, потная, полусонная, как дочь, и удовлетворенная впечатлением, произведенным её стряпнею, не торопилась убирать со стола и присела отдохнуть. Убедившись, что девочка спит, она говорила, навалившись грудью на стол и подперши голову рукою:<br/> — Я бы сил не щадила и в этом находила бы счастье, только бы знать, что это не попусту и ведет к какой-то цели. Ты мне должен ежеминутно напоминать, что мы тут для того, чтобы быть вместе. Подбадривай меня и не давай опомниться. Потому что, строго говоря, если взглянуть трезво, чем мы заняты, что у нас происходит? Налет на чужое жилище, вломились, распоряжаемся и все время подхлестываем себя спешкой, чтобы не видеть, что это не жизнь, а театральная постановка, не всерьез, а «нарочно», как говорят дети, кукольная комедия, курам на смех.<br/> — Но, мой ангел, ты ведь сама настаивала на этой поездке.<br/> Вспомни, как я долго противился и не соглашался.<br/> — Верно. Не спорю. Но вот я уже и провинилась. Тебе можно колебаться, задумываться, а у меня всё должно быть последовательно и логично. Мы вошли в дом, ты увидел детскую кроватку сына и тебе стало дурно, ты чуть не упал в обморок от боли. У тебя на это есть право, а мне это не позволено, страх за Катеньку, мысли о будущем должны отступать перед моею любовью к тебе.<br/> — Ларуша, ангел мой, приди в себя. Одуматься, отступить от решения никогда не поздно. Я первый советовал тебе отнестись к словам Комаровского серьезней. У нас есть лошадь. Хочешь завтра слетаем в Юрятин. Комаровский еще там, не уехал. Ведь мы его видели с саней на улице, причем он нас, по-моему, не заметил. Мы его наверное еще застанем.<br/> — Я почти ничего еще не сказала, а у тебя уже недовольные нотки в голосе. Но скажи, разве я не права? Прятаться так ненадежно, наобум, можно было и в Юрятине. А если уже искать спасения, то надо было наверняка, с продуманным планом, как, в конце концов, предлагал этот сведущий и трезвый, хотя и противный, человек. Ведь здесь мы, я просто не знаю, насколько ближе к опасности, чем где бы то ни было. Беспредельная, вихрям открытая равнина. И мы одни как перст. Нас на ночь снегом занесет, к утру не откопаемся. Или наш таинственный благодетель, наведывающийся в дом, нагрянет, окажется разбойником, и нас зарежет. Есть ли у тебя хотя оружие? Нет, вот видишь. Меня страшит твоя беспечность, которою ты меня заражаешь. От нее у меня сумятица в мыслях.<br/> — Но что ты в таком случае хочешь? Что прикажешь мне делать?<br/> — Я и сама не знаю, как тебе ответить. Держи меня все время в подчинении. Беспрестанно напоминай мне, что я твоя слепо тебя любящая, не рассуждающая раба. О, я скажу тебе.<br/> Наши близкие, твои и мои, в тысячу раз лучше нас. Но разве в этом дело? Дар любви, как всякий другой дар. Он может быть и велик, но без благословения он не проявится. А нас точно научили целоваться на небе и потом детьми послали жить в одно время, чтобы друг на друге проверить эту способность. Какой-то венец совместности, ни сторон, ни степеней, ни высокого, ни низкого, равноценность всего существа, всё доставляет радость, всё стало душою. Но в этой дикой, ежеминутно подстерегающей нежности есть что-то по-детски неукрощенное, недозволенное.<br/> Это своевольная, разрушительная стихия, враждебная покою в доме. Мой долг бояться и не доверять ей.<br/> Она обвивала ему шею руками и, борясь со слезами, заканчивала:<br/> — Понимаешь, мы в разном положении. Окрыленность дана тебе, чтобы на крыльях улетать за облака, а мне, женщине, чтобы прижиматься к земле и крыльями прикрывать птенца от опасности.<br/> Ему страшно нравилось все, что она говорила, но он не показывал этого, чтобы не впасть в приторность. Сдерживаясь, он замечал:<br/> — Бивуачность нашего жилья действительно фальшива и взвинченна. Ты глубоко права. Но не мы её придумали. Угорелое метание — участь всех, это в духе времени.<br/> Я сам с утра думал сегодня приблизительно о том же. Я хотел бы приложить всё старание, чтобы остаться тут подольше. Не могу сказать, как я соскучился по работе. Я имею в виду не сельскохозяйственную. Мы однажды тут всем домом вложили себя в нее, и она удалась. Но я был бы не в силах повторить это еще раз. У меня не то на уме.<br/> Жизнь со всех сторон постепенно упорядочивается. Может быть когда-нибудь снова будут издавать книги.<br/> Вот о чем я раздумывал. Нельзя ли было бы сговориться с Самдевятовым, на выгодных для него условиях, чтобы он полгода продержал нас на своих хлебах, под залог труда, который я обязался бы написать тем временем, руководства по медицине, предположим, или чего-нибудь художественного, книги стихотворений, к примеру. Или, скажем, я взялся бы перевести с иностранного что-нибудь прославленное, мировое. Языки я знаю хорошо, я недавно прочел объявление большого петербургского издательства, занимающегося выпуском одних переводных произведений. Работы такого рода будут, наверное, представлять меновую ценность, обратимую в деньги. Я был бы счастлив заняться чем-нибудь в этом роде.<br/> — Спасибо, что ты мне напомнил. Я тоже сегодня думала о чем-то подобном. Но у меня нет веры, что мы тут продержимся.<br/> Наоборот, я предчувствую, что нас унесет скоро куда-то дальше.<br/> Но пока в нашем распоряжении эта остановка, у меня есть к тебе просьба. Пожертвуй мне несколько часов в ближайшие ночи и запиши, пожалуйста, все из того, что ты читал мне в разное время на память. Половина этого растеряна, а другая не записана, и я боюсь, что потом ты всё забудешь и оно пропадет, как, по твоим словам, с тобой уже часто случалось.

