### 8 {-}

К концу дня все помылись горячею водой, в изобилии оставшейся от стирки. Лара выкупала Катеньку. Юрий Андреевич с блаженным чувством чистоты сидел за оконным столом спиной к комнате, в которой Лара, благоухающая, запахнутая в купальный халат, с мокрыми, замотанными мохнатым полотенцем в тюрбан волосами, укладывала Катеньку и устраивалась на ночь. Весь уйдя в предвкушение скорой сосредоточенности, Юрий Андреевич воспринимал всё совершавшееся сквозь пелену разнеженного и всеобобщающего внимания.<br/> Был час ночи, когда, притворявшаяся до тех пор, будто спит, Лара действительно уснула. Смененное на ней, на Катеньке и на постели белье сияло, чистое, глаженое, кружевное. Лара и в те годы ухитрялась каким-то образом его крахмалить.<br/> Юрия Андреевича окружала блаженная, полная счастья, сладко дышащая жизнью, тишина. Свет лампы спокойной желтизною падал на белые листы бумаги и золотистым бликом плавал на поверхности чернил внутри чернильницы. За окном голубела зимняя морозная ночь. Юрий Андреевич шагнул в соседнюю холодную и неосвещенную комнату, откуда было виднее наружу, и посмотрел в окно. Свет полного месяца стягивал снежную поляну осязательной вязкостью яичного белка или клеевых белил.<br/> Роскошь морозной ночи была непередаваема. Мир был на душе у доктора. Он вернулся в светлую, тепло истопленную комнату и принялся за писание.<br/> Разгонистым почерком, заботясь, чтобы внешность написанного передавала живое движение руки и не теряла лица, обездушиваясь и немея, он вспомнил и записал в постепенно улучшающихся, уклоняющихся от прежнего вида редакциях наиболее определившееся и памятное, «Рождественскую звезду», «Зимнюю ночь» и довольно много других стихотворений близкого рода, впоследствии забытых, затерявшихся и потом никем не найденных.<br/> Потом от вещей отстоявшихся и законченных перешел к когда-то начатым и брошенным, вошел в их тон и стал набрасывать их продолжение, без малейшей надежды их сейчас дописать. Потом разошелся, увлекся и перешел к новому.<br/> После двух-трех легко вылившихся строф и нескольких, его самого поразивших сравнений, работа завладела им, и он испытал приближение того, что называется вдохновением. Соотношение сил, управляющих творчеством, как бы становится на голову.<br/> Первенство получает не человек и состояние его души, которому он ищет выражения, а язык, которым он хочет его выразить.<br/> Язык, родина и вместилище красоты и смысла, сам начинает думать и говорить за человека и весь становится музыкой, не в отношении внешне слухового звучания, но в отношении стремительности и могущества своего внутреннего течения. Тогда подобно катящейся громаде речного потока, самым движением своим обтачивающей камни дна и ворочающей колеса мельниц, льющаяся речь сама, силой своих законов создает по пути, мимоходом, размер и рифму, и тысячи других форм и образований еще более важных, но до сих пор неузнанных, неучтенных, неназванных.<br/> В такие минуты Юрий Андреевич чувствовал, что главную работу совершает не он сам, но то, что выше его, что находится над ним и управляет им, а именно: состояние мировой мысли и поэзии, и то, что ей предназначено в будущем, следующий по порядку шаг, который предстоит ей сделать в её историческом развитии. И он чувствовал себя только поводом и опорной точкой, чтобы она пришла в это движение.<br/> Он избавлялся от упреков самому себе, недовольство собою, чувство собственного ничтожества на время оставляло его. Он оглядывался, он озирался кругом.<br/> Он видел головы спящих Лары и Катеньки на белоснежных подушках. Чистота белья, чистота комнат, чистота их очертаний, сливаясь с чистотою ночи, снега, звезд и месяца в одну равнозначительную, сквозь сердце доктора пропущенную волну, заставляла его ликовать и плакать от чувства торжествующей чистоты существования.<br/> «Господи! Господи!» — готов был шептать он. — «И все это мне! За что мне так много? Как подпустил ты меня к себе, как дал забрести на эту бесценную твою землю, под эти твои звезды, к ногам этой безрассудной, безропотной, незадачливой, ненаглядной?»<br/> Было три часа ночи, когда Юрий Андреевич поднял глаза от стола и бумаги. Из отрешенной сосредоточенности, в которую он ушел с головой, он возвращался к себе, к действительности, счастливый, сильный, спокойный. Вдруг в безмолвии далеких пространств, раскинувшихся за окном, он услышал заунывный, печальный звук.<br/> Он прошел в соседнюю неосвещенную комнату, чтобы из нее посмотреть в окно. За те часы, что он провел за писанием, стекла успели сильно заиндеветь, через них нельзя было ничего разглядеть. Юрий Андреевич оттащил скатанный ковер, которым заложен был низ выходной двери, чтобы из-под нее не дуло, накинул на плечи шубу и вышел на крыльцо.<br/> Белый огонь, которым был объят и полыхал незатененный снег на свету месяца, ослепил его. Вначале он не мог ни во что вглядеться и ничего не увидел. Но через минуту расслышал ослабленное расстоянием протяжное утробно-скулящее завывание и тогда заметил на краю поляны за оврагом четыре вытянутые тени, размером не больше маленькой черточки.<br/> Волки стояли рядом, мордами по направлению к дому и, подняв головы, выли на луну или на отсвечивающие серебряным отливом окна Микулицынского дома. Несколько мгновений они стояли неподвижно, но едва Юрий Андреевич понял, что это волки, они по-собачьи, опустив зады, затрусили прочь с поляны, точно мысль доктора дошла до них. Доктор не успел доискаться, в каком направлении они скрылись.<br/> «Неприятная новость!» — подумал он. — «Только их недоставало. Неужели где-то под боком, совсем близко, их лежка? Может быть, даже в овраге. Как страшно! И на беду еще эта Савраска Самдевятовская в конюшне. Лошадь, наверное, они и почуяли».<br/> Он решил до поры до времени ничего не говорить Ларе, чтобы не пугать ее, вошел внутрь, запер наружную дверь, притворил промежуточные, ведшие с холодной половины на теплую, заткнул их щели и отверстия, и подошел к столу.<br/> Лампа горела ярко и приветливо, по-прежнему. Но больше ему не писалось. Он не мог успокоиться. Ничего, кроме волков и других грозящих осложнений, не шло в голову. Да и устал он. В это время проснулась Лара.<br/> — А ты все горишь и теплишься, свечечка моя яркая! — влажным, заложенным от спанья шопотом тихо сказала она. — На минуту сядь поближе, рядышком. Я расскажу тебе, какой сон видела.<br/> И он потушил лампу.

