### 9 {-}

Опять день прошел в помешательстве тихом. В доме отыскались детские салазки. Раскрасневшаяся Катенька в шубке, громко смеясь, скатывалась на неразметенные дорожки палисадника с ледяной горки, которую ей сделал доктор, плотно уколотив лопатой и облив водою. Она без конца, с застывшей на лице улыбкой, взбиралась назад на горку и втаскивала вверх санки за веревочку.<br/> Морозило, мороз заметно крепчал. На дворе было солнечно.<br/> Снег желтел под лучами полдня и в его медовую желтизну сладким осадком вливалась апельсиновая гуща рано наступавшего вечера.<br/> Вчерашнею стиркой и купаньем Лара напустила в дом сырости.<br/> Окна затянуло рыхлым инеем, отсыревшие от пара обои с потолка до полу покрывались черными струистыми отеками. В комнатах стало темно и неуютно. Юрий Андреевич носил дрова и воду, продолжая недовершенный осмотр дома со всё время непрекращающимися открытиями, и помогал Ларе, с утра занятой беспрестанно возникавшими перед ней домашними делами.<br/> Снова в разгаре какой-нибудь работы их руки сближались и оставались одна в другой, поднятую для переноски тяжесть опускали на пол, не донеся до цели, и приступ туманящей непобедимой нежности обезоруживал их. Снова все валилось у них из рук и вылетало из головы. Опять шли минуты и слагались в часы и становилось поздно, и оба с ужасом спохватывались, вспомнив об оставленной без внимания Катеньке, или о некормленой и непоеной лошади, и сломя голову бросались наверстывать и исправлять упущенное и мучились угрызениями совести.<br/> У доктора от недосыпу ломило голову. Сладкий туман, как с похмелья, стоял в ней и ноющая, блаженная слабость во всем теле. Он с нетерпением ждал вечера, чтобы вернуться к прерванной ночной работе.<br/> Предварительную половину дела совершала за него та сонная дымка, которою был полон он сам, и подернуто было все кругом, и окутаны были его мысли. Обобщенная расплывчатость, которую она всему придавала, шла в направлении, предшествующем точности окончательного воплощения. Подобно смутности первых черновых набросков, томящая праздность целого дня служила трудовой ночи необходимой подготовкой.<br/> Безделье усталости ничего не оставляло нетронутым, непретворенным. Все претерпевало изменения и принимало другой вид.<br/> Юрий Андреевич чувствовал, что мечтам его о более прочном водворении в Варыкине не сбыться, что час его расставания с Ларою близок, что он её неминуемо потеряет, а вслед за ней и побуждение к жизни, а может быть и жизнь. Тоска сосала его сердце. Но еще больше томило его ожидание вечера, и желание выплакать эту тоску в таком выражении, чтобы заплакал всякий.<br/> Волки, о которых он вспоминал весь день, уже не были волками на снегу под луною, но стали темой о волках, стали представлением вражьей силы, поставившей себе целью погубить доктора и Лару или выжить их из Варыкина. Идея этой враждебности, развиваясь, достигла к вечеру такой силы, точно в Шутьме открылись следы допотопного страшилища и в овраге залег чудовищных размеров сказочный, жаждущий докторовой крови и алчущий Лары дракон.<br/> Наступил вечер. По примеру вчерашнего доктор засветил на столе лампу. Лара с Катенькой легли спать раньше, чем накануне.<br/> Написанное ночью распадалось на два разряда. Знакомое, перебеленное в новых видоизменениях было записано чисто, каллиграфически. Новое было набросано сокращенно, с точками, неразборчивыми каракулями.<br/> Разбирая эту мазню, доктор испытал обычное разочарование.<br/> Ночью эти черновые куски вызывали у него слезы и ошеломляли неожиданностью некоторых удач. Теперь как раз эти мнимые удачи остановили и огорчили его резко выступающими натяжками.<br/> Всю жизнь мечтал он об оригинальности сглаженной и приглушенной, внешне неузнаваемой и скрытой под покровом общеупотребительной и привычной формы, всю жизнь стремился к выработке того сдержанного, непритязательного слога, при котором читатель и слушатель овладевают содержанием, сами не замечая, каким способом они его усваивают. Всю жизнь он заботился о незаметном стиле, не привлекающем ничьего внимания, и приходил в ужас от того, как он еще далек от этого идеала.<br/> Во вчерашних набросках ему хотелось средствами, простотою доходящими до лепета и граничащими с задушевностью колыбельной песни, выразить свое смешанное настроение любви и страха и тоски и мужества, так чтобы оно вылилось как бы помимо слов, само собою.<br/> Теперь, на другой день, просматривая эти пробы, он нашел, что им недостает содержательной завязки, которая сводила бы воедино распадающиеся строки. Постепенно перемарывая написанное, Юрий Андреевич стал в той же лирической манере излагать легенду о Егории Храбром. Он начал с широкого, предоставляющего большой простор, пятистопника. Независимое от содержания, самому размеру свойственное благозвучие раздражало его своей казенной фальшивою певучестью. Он бросил напыщенный размер с цензурою, стеснив строки до четырех стоп, как борются в прозе с многословием. Писать стало труднее и заманчивее.<br/> Работа пошла живее, но все же излишняя болтливость проникала в нее. Он заставил себя укоротить строчки еще больше. Словам стало тесно в трехстопнике, последние следы сонливости слетели с пишущего, он пробудился, загорелся, узость строчных промежутков сама подсказывала, чем их наполнить. Предметы, едва названные на словах, стали не шутя вырисовываться в раме упоминания. Он услышал ход лошади, ступающей по поверхности стихотворения, как слышно спотыкание конской иноходи в одной из баллад Шопена. Георгий Победоносец скакал на коне по необозримому пространству степи, Юрий Андреевич видел сзади, как он уменьшается, удаляясь. Юрий Андреевич писал с лихорадочной торопливостью, едва успевая записывать слова и строчки, являвшиеся сплошь к месту и впопад.<br/> Он не заметил, как встала с постели и подошла к столу Лара.<br/> Она казалась тонкой и худенькой и выше, чем на самом деле, в своей длинной ночной рубашке до пят. Юрий Андреевич вздрогнул от неожиданности, когда она выросла рядом, бледная, испуганная и, вытянув руку вперед, шопотом спросила:<br/> — Слышишь? Собака воет. Даже две. Ах как страшно, какая дурная примета! Как-нибудь дотерпим до утра, и едем, едем. Ни минуты тут дольше не останусь.<br/> Через час, после долгих уговоров, Лариса Федоровна успокоилась и снова уснула. Юрий Андреевич вышел на крыльцо.<br/> Волки были ближе, чем прошлую ночь, и скрылись еще скорее. И опять Юрий Андреевич не успел уследить, в какую сторону они ушли. Они стояли кучей, он не успел их сосчитать. Ему показалось, что их стало больше.

