### 10 {-}

Наступил тринадцатый день их обитания в Варыкине, не отличавшийся обстоятельствами от первых. Так же накануне выли волки, исчезнувшие было в середине недели. Снова приняв их за собак, Лариса Федоровна так же положила уехать на другое утро, напуганная дурной приметой. Так же чередовались у нее состояния равновесия с приступами тоскливого беспокойства, естественного у трудолюбивой женщины, не привыкшей к целодневным излияниям души и праздной, непозволительной роскоши неумеренных нежностей.<br/> Всё повторялось в точности, так что когда в это утро на второй неделе Лариса Федоровна опять, как столько раз перед этим, стала собираться в обратную дорогу, можно было подумать, что прожитых в перерыве полутора недель как не бывало.<br/> Опять было сыро в комнатах, в которых было темно вследствие хмурости серого пасмурного дня. Мороз смягчился, с темного неба, покрытого низкими тучами, с минуты на минуту должен был повалить снег. Душевная и телесная усталость от затяжного недосыпания подкашивала Юрия Андреевича. Мысли путались у него, силы были подорваны, он ощущал сильную зябкость от слабости и, ежась и потирая руки от холода, ходил по нетопленной комнате, не зная, что решит Лариса Федоровна и за что, соответственно её решению, ему надо будет приняться.<br/> Ее намерения были неясны. Сейчас она полжизни отдала бы за то, чтобы оба они не были так хаотически свободны, а вынужденно подчинялись какому угодно строгому, но раз навсегда заведенному порядку, чтобы они ходили на службу, чтобы у них были обязанности, чтобы можно было жить разумно и честно.<br/> Она начала день, как обычно, оправила постели, убрала и подмела комнаты, подала завтракать доктору и Кате. Потом стала укладываться и попросила доктора заложить лошадь. Решение уехать было принято ею твердо и неуклонно.<br/> Юрий Андреевич не пробовал её отговаривать. Возвращение их в город в разгар тамошних арестов после их недавнего исчезновения было совершенным безрассудством. Но едва ли разумнее было отсиживаться одним без оружия среди этой, полной своих собственных угроз, страшной зимней пустыни.<br/> Кроме того, последние охапки сена, которые доктор сгребал по соседним сараям, подходили к концу, а новых не предвиделось. Конечно, будь возможность водвориться тут попрочнее, доктор объездил бы окрестности и позаботился о пополнении фуражных и продовольственных запасов. Но для короткого и гадательного пребывания не стоило пускаться на такие разведки. И махнув на всё рукой, доктор пошел запрягать.<br/> Он запрягал неумело. Его этому учил Самдевятов. Юрий Андреевич забывал его наставления. Неопытными руками он сделал однако всё что нужно. Наборный кованый кончик ремня, которым он прикрутил дугу к оглоблям, он затянул узлом на одной из оглобель, намотав его в несколько оборотов на её конец, потом, упершись ногой в бок лошади, туго стянул расходящиеся клешни хомута, после чего, доделав все остальное, подвел лошадь к крыльцу, привязал её к нему и пошел сказать Ларе, что можно собираться.<br/> Он застал её в крайнем замешательстве. Она и Катенька были одеты к выезду, все уложено, но Лариса Федоровна ломала руки и, сдерживая слезы и прося Юрия Андреевича присесть на минуту, бросалась в кресло и вставала, и часто прерывая себя восклицанием «Не правда ли?» на высокой, певучей и жалующейся ноте, говорила быстро-быстро, бессвязною скороговоркой:<br/> — Я не виновата. Я сама не знаю, как это получилось. Но разве можно сейчас ехать? Скоро стемнеет. Ночь застанет нас в дороге. И как раз в твоем страшном лесу. Не правда ли? Я поступлю, как ты прикажешь, но сама, собственною волей, не решусь. Что-то удерживает меня. У меня сердце не на месте. А ты как знаешь. Не правда ли? Что же ты молчишь и не скажешь ни слова? Мы проротозейничали целое утро, неизвестно на что потратили половину дня. Завтра это больше не повторится, мы будем поосторожнее, не правда ли? Может быть, остаться еще на сутки? Встанем завтра пораньше, снимемся чуть свет, часов в семь или шесть утра. Как ты думаешь? Ты затопишь печку, попишешь здесь один лишний вечер, переночуем здесь еще одну ночь. Ах это было бы так неповторимо, волшебно! Что же ты ничего не отвечаешь? Опять я в чем-то виновата, несчастная!<br/> — Ты преувеличиваешь. До сумерек еще далеко. Еще совсем рано. Но будь по-твоему. Хорошо. Останемся. Только успокойся.<br/> Смотри, как ты возбуждена. Действительно, разложимся, снимем шубы. Вот Катенька говорит, что проголодалась. Закусим. Твоя правда, нынешний отъезд был бы слишком неподготовленным, внезапным. Только не волнуйся и не плачь, ради Бога. Сейчас я затоплю. Но перед тем, благо лошадь запряжена и сани у крыльца, съезжу за последними дровами к бывшему Живаговскому сараю, а то у меня тут больше ни полена. А ты не плачь. Я скоро вернусь.

