### 11 {-}

На снегу перед сараем в несколько кругов шли санные следы прежних заездов и заворотов Юрия Андреевича. Снег у порога был затоптан и замусорен позавчерашнею таскою дров.<br/> Облака, заволакивавшие небо с утра, разошлись. Оно очистилось. Подморозило. Варыкинский парк, на разных расстояниях окружавший эти места, близко подступал к сараю, как бы для того, чтобы заглянуть в лицо доктора и что-то ему напомнить. Снег в эту зиму лежал глубоким слоем, выше порога сарая. Его дверная притолока как бы опустилась, сарай точно сгорбился. С его крыши почти на голову доктору шапкой исполинского гриба свисал пласт наметенного снега. Прямо над свесом крыши, точно воткнутый острием в снег, стоял и горел серым жаром по серпяному вырезу молодой, только что народившийся полумесяц.<br/> Хотя был еще день и совсем светло, у доктора было такое чувство, точно он поздним вечером стоит в темном дремучем лесу своей жизни. Такой мрак был у него на душе, так ему было печально. И молодой месяц предвестием разлуки, образом одиночества почти на уровне его лица горел перед ним.<br/> Усталость валила с ног Юрия Андреевича. Швыряя дрова через порог сарая в сани, он забирал меньше поленьев за один раз, чем обыкновенно. Браться на холоде за обледенелые плахи с приставшим снегом даже сквозь рукавицы было больно. Ускоренная подвижность не разогревала его. Что-то остановилось внутри его и порвалось. Он клял на чем свет стоит бесталанную свою судьбу и молил Бога сохранить и уберечь жизнь красоты этой писаной, грустной, покорной, простодушной. А месяц всё стоял над сараем и горел и не грел, светился и не освещал.<br/> Вдруг лошадь, повернувшись в том направлении, откуда её привели, подняла голову и заржала сначала тихо и робко, а потом громко и уверенно.<br/> «Чего это она?» — подумал доктор. «С какой это радости? Не может быть, чтобы со страху. Со страху кони не ржут, какие глупости. Дура она что ли голосом волкам знак подавать, если она их почуяла. И как весело. Это видно в предвкушении дома, домой захотелось. Погоди, сейчас тронем».<br/> В придачу к наложенным дровам Юрий Андреевич набрал в сарае щепы и крупной, сапожным голенищем выгнутой, целиком с полена отвалившейся бересты для растопки, перехватил покрытую рогожей дровяную кучу веревкой и, шагая рядом с санями, повез дрова в сарай к Микулицыным.<br/> Опять лошадь заржала, в ответ на явственное конское ржание где-то вдали, в другой стороне. «У кого бы это? — встрепенувшись, подумал доктор. — Мы считали, что Варыкино пусто. Значит, мы ошибались». Ему в голову не могло прийти, что у них гости, и что ржание коня доносится со стороны Микулицынского крыльца, из сада. Он вел Савраску обходом, задами, к службам заводских усадеб, и за буграми, скрывавшими дом, не видел его передней части.<br/> Не спеша (зачем ему было торопиться?), побросал он дрова в сарай, выпряг лошадь, сани оставил в сарае, а лошадь отвел в пустующую рядом выхоложенную конюшню. Он поставил её в правый угловой станок, где меньше продувало, и принесши из сарая несколько охапок оставшегося сена, навалил его в наклонную решетку яслей.<br/> С неспокойной душою шел он к дому. У крыльца стоял запряженный в очень широкие крестьянские сани с удобным кузовом раскормленный вороной жеребец. Вокруг коня похаживал, похлопывая его по бокам и осматривая щетки его ног, такой же гладкий и сытый, как он, незнакомый малый в хорошей поддевке.<br/> В доме слышался шум. Не желая подслушивать и не будучи в состоянии что-нибудь услышать, Юрий Андреевич невольно замедлил шаг и остановился как вкопанный. Не разбирая слов, он узнавал голоса Комаровского, Лары и Катеньки. Вероятно, они были в первой комнате, у выхода. Комаровский спорил с Ларою, и, судя по звуку её ответов, она волновалась, плакала и то резко возражала ему, то с ним соглашалась. По какому-то непреодолимому признаку Юрий Андреевич вообразил, что Комаровский завел в эту минуту речь именно о нем, предположительно в том духе, что он человек ненадежный («слуга двух господ» — почудилось Юрию Андреевичу), что неизвестно, кто ему дороже, семья или Лара, и что Ларе нельзя на него положиться, потому что доверившись доктору, она «погонится за двумя зайцами и останется между двух стульев». Юрий Андреевич вошел в дом.<br/> В первой комнате, действительно, в шубе до полу стоял, не раздеваясь Комаровский. Лара держала Катеньку за верхние края шубки, стараясь стянуть ворот и не попадая крючком в петлю.<br/> Она сердилась на девочку, крича, чтобы дочь не вертелась и не вырывалась, а Катенька жаловалась: «Мамочка, тише, ты меня задушишь». Все стояли одетые, готовые к выезду. Когда вошел Юрий Андреевич, Лара и Виктор Ипполитович наперерыв бросились к нему навстречу. — Где ты пропадал? Ты нам так нужен!<br/> — Здравствуйте, Юрий Андреевич! Несмотря на грубости, которые мы наговорили в последний раз друг другу, я снова, как видите, к вам без приглашения.<br/> — Здравствуйте, Виктор Ипполитович.<br/> — Куда ты пропал так надолго? Выслушай, что он скажет, и скорей решай за себя и меня. Времени нет. Надо торопиться.<br/> — Что же мы стоим? Садитесь, Виктор Ипполитович. Как куда я пропал, Ларочка? Ты ведь знаешь, я за дровами ездил, а потом о лошади позаботился. Виктор Ипполитович, прошу вас, садитесь.<br/> — Ты не поражен? Отчего ты не выказываешь удивления? Мы жалели, что этот человек уехал и что мы не ухватились за его предложения, а он тут перед тобой и ты не удивляешься. Но еще поразительнее его свежие новости. Расскажите их ему, Виктор Ипполитович.<br/> — Я не знаю, что разумеет Лариса Федоровна, а в свою очередь скажу следующее. Я нарочно распространил слух, что уехал, а сам остался еще на несколько дней, чтобы дать вам и Ларисе Федоровне время по-новому передумать затронутые нами вопросы, и по зрелом размышлении прийти, может быть, к менее опрометчивому решению.<br/> — Но дальше откладывать нельзя. Сейчас для отъезда самое удобное время. Завтра утром, — но лучше пусть Виктор Ипполитович сам расскажет тебе.<br/> — Минуту, Ларочка. Простите, Виктор Ипполитович. Почему мы стоим в шубах? Разденемся и присядем. Разговор-то ведь серьезный. Нельзя так с бухты-барахты. Извините, Виктор Ипполитович. Наши препирательства затрагивают некоторые душевные тонкости. Разбирать эти предметы смешно и неудобно. Я никогда не помышлял о поездке с вами. Другое дело Лариса Федоровна. В тех редких случаях, когда наши беспокойства бывали отделимы одно от другого, и мы вспоминали, что мы не одно существо, а два, с двумя отдельными судьбами, я считал, что Ларе надо, особенно ради Кати, внимательнее задуматься о ваших планах. Да она не переставая это и делает, возвращаясь вновь и вновь к этим возможностям.<br/> — Но только при условии, если бы ты поехал.<br/> — Нам одинаково трудно представить себе наше разъединение, но, может быть, надо пересилить себя и принести эту жертву.<br/> Потому что о моей поездке не может быть и речи.<br/> — Но ведь ты еще ничего не знаешь. Сначала выслушай.<br/> Завтра утром… Виктор Ипполитович!<br/> — Видно, Лариса Федоровна имеет в виду сведения, которые я привез и уже сообщил ей. На путях в Юрятине стоит под парами служебный поезд Дальневосточного правительства. Вчера он прибыл из Москвы и завтра отправляется дальше. Это поезд нашего министерства путей сообщения. Он наполовину состоит из международных спальных вагонов.<br/> Я должен ехать в этом поезде. Мне предоставлены места для лиц, приглашенных в мою рабочую коллегию. Мы покатили бы со всем комфортом. Такой случай больше не представится. Я знаю, вы слов на ветер не бросаете и отказа поехать с нами не отмените. Вы человек твердых решений, я знаю. Но все же.<br/> Сломите себя ради Ларисы Федоровны. Вы слышали, без вас она не поедет. Поедемте с нами, если не во Владивосток, то хотя бы в Юрятин. А там увидим. Но в таком случае надо торопиться.<br/> Нельзя терять ни минуты. Со мною человек, я плохо правлю.<br/> Впятером с ним нам в моих розвальнях не уместиться. Если не ошибаюсь, Самдевятовская лошадь у вас. Вы говорили, что ездили на ней за дровами. Она еще не разложена?<br/> — Нет, я распряг ее.<br/> — Тогда запрягите поскорее снова. Мой кучер вам поможет.<br/> Впрочем, знаете. Ну их к чорту, вторые сани. Как-нибудь доедем на моих. Только ради Бога скорее. В дорогу с собой самое необходимое, что под руку попадется. Дом пусть остается как есть, незапертым. Надо спасать жизнь ребенка, а не ключи к замкам подбирать.<br/> — Я не понимаю вас, Виктор Ипполитович. Вы так разговариваете, точно я согласился поехать. Поезжайте с Богом, если Лара так хочет. А о доме не беспокойтесь. Я останусь, и после вашего отъезда уберу и запру его.<br/> — Что ты говоришь, Юра? К чему этот заведомый вздор, в который ты сам не веришь. «Если Лариса Федоровна решила». И сам прекрасно знает, что без его участия в поездке Ларисы Федоровны и в заводе нет и никаких её решений. Тогда к чему эта фраза: «А дом я уберу и обо всем позабочусь»?<br/> — Значит, вы неумолимы. Тогда другая просьба. С разрешения Ларисы Федоровны мне вас на два слова и, если можно, с глазу на глаз.<br/> — Хорошо. Если это так нужно, пойдемте на кухню. Ты не возражаешь, Ларуша?

