### 12 {-}

— Стрельников схвачен, приговорен к высшей мере и приговор приведен в исполнение.<br/> — Какой ужас. Неужели правда?<br/> — Так я слышал. Я в этом уверен.<br/> — Не говорите Ларе. Она с ума сойдет.<br/> — Еще бы. Для этого я позвал вас в другую комнату. После этого расстрела она и дочь в близкой непосредственно придвинувшейся опасности. Помогите мне спасти их. Вы наотрез отказываетесь сопутствовать нам?<br/> — Я ведь сказал вам. Конечно.<br/> — Но без вас она не уедет. Просто не знаю, что делать.<br/> Тогда от вас требуется другая помощь. Изобразите на словах, обманно, готовность уступить, сделайте вид, будто вас можно уговорить. Я не представляю себе вашего прощания. Ни здесь, на месте, ни на вокзале, в Юрятине, если бы вы действительно поехали нас провожать. Надо добиться, чтобы она поверила, что вы тоже едете. Если не сейчас, вместе с нами, то спустя некоторое время, когда я предоставлю вам новую возможность, которою вы пообещаете воспользоваться. Тут вы должны быть способны дать ей ложную клятву. Но с моей стороны это не пустые слова. Честью вас заверяю, при первом выраженном вами желании я берусь в любое время доставить вас отсюда к нам и переправить дальше, куда бы вы ни пожелали. Лариса Федоровна должна быть уверена, что вы нас провожаете. Удостоверьте её в этом со всею силой убедительности. Скажем, притворно побегите запрягать лошадь, и уговорите нас трогаться немедленно, не дожидаясь, пока вы её заложите и следом нагоните нас в дороге.<br/> — Я потрясен известием о расстреле Павла Павловича и не могу прийти в себя. Я с трудом слежу за вашими словами. Но я с вами согласен. После расправы со Стрельниковым по нашей нынешней логике жизнь Ларисы Федоровны и Кати тоже под угрозой. Кого-то из нас наверняка лишат свободы, и, следовательно, так или иначе все равно разлучат. Тогда, правда, лучше разлучите вы нас и увезите их куда-нибудь подальше, на край света. Сейчас, когда я говорю вам это, все равно дела идут уже по-вашему. Наверное, мне станет невмоготу, и поступившись гордостью и самолюбием, я покорно приползу к вам, чтобы получить из ваших рук и ее, и жизнь, и морской путь к своим и собственное спасение. Но дайте мне во всем этом разобраться. Сообщенная вами новость ошеломила меня. Я раздавлен страданием, которое отнимает у меня способность думать и рассуждать. Может быть, покорясь вам, я совершаю роковую, непоправимую ошибку, которой буду ужасаться всю жизнь, но в тумане обессиливающей меня боли единственное, что я могу сейчас, это машинально поддакивать вам и слепо, безвольно вам повиноваться. Итак я для вида, ради её блага, объявлю ей сейчас, что иду запрягать лошадь и догоню вас, а сам останусь тут один. Одна только мелочь. Как вы теперь поедете, на ночь глядя? Дорога лесом, кругом волки, берегитесь.<br/> — Я знаю. Со мной ружье и револьвер. Не беспокойтесь. Да кстати и спиртику малость прихватил, на случай мороза.<br/> Достаточное количество. Поделюсь, хотите?

