### 13 {-}

«Что я наделал? Что я наделал? Отдал, отрекся, уступил.<br/> Броситься бегом вдогонку, догнать, вернуть. Лара! Лара!<br/> Не слышат. Ветер в обратную сторону. И, наверное, громко разговаривают. У нее все основания быть веселой, спокойной.<br/> Она далась в обман и не подозревает, в каком она заблуждении.<br/> Вот её вероятные мысли. Она думает. Все сложилось как нельзя лучше, по её желанию. Ее Юрочка, фантазер и упрямец, наконец, смягчился, слава Создателю, и отправляется вместе с ней куда-то в верное место, к людям поумнее их, под защиту законности и порядка. Если даже, чтобы настоять на своем и выдержать характер, он покобенится и не сядет завтра в их поезд, то Виктор Ипполитович пришлет за ним другой, он к ним подъедет в самом непродолжительном времени.<br/> А сейчас он, конечно, уже на конюшне, дрожащими от волнения и спешки, путающимися, не слушающимися руками запрягает Савраску и немедленно во весь дух пустится нахлестывать следом, так что нагонит их еще в поле, до въезда в лес».<br/> Вот как, наверное, она думает. А они даже и не простились толком, только Юрий Андреевич рукой махнул и отвернулся, стараясь сглотнуть колом в горле ставшую боль, точно он подавился куском яблока.<br/> Доктор в накинутой на одно плечо шубе стоял на крыльце.<br/> Свободною, не покрытой шубою рукой он под самым потолком сжимал с такой силою шейку точеного крылечного столбика, точно душил его. Всем своим сознанием он был прикован к далекой точке в пространстве. Там, на некотором протяжении, небольшой кусок подымавшегося в гору пути открывался между несколькими, отдельно росшими березами. В это открытое место падал в данное мгновение свет низкого, готового к заходу, солнца. Туда, в полосу этого освещения должны были с минуты на минуту вынестись разогнавшиеся сани из неглубокой ложбины, куда они ненадолго занырнули.<br/> — Прощай,прощай, — предваряя эту минуту, беззвучно-беспамятно твердил доктор, выталкивая из груди эти чуть дышащие звуки в вечеревший морозный воздух. — Прощай, единственно любимая, навсегда утраченная!<br/> — Едут! Едут! — стремительно сухо зашептал он побелевшими губами, когда сани стрелой вылетели снизу, минуя березы одну за другою, и стали сдерживать ход и, о радость, остановились у последней.<br/> О как забилось его сердце, о как забилось его сердце, ноги подкосились у него, он от волнения стал весь мягкий, войлочный, как сползающая с плеча шуба! «О Боже, Ты, кажется, положил вернуть её мне? Что там случилось? Что там делается, на далекой закатной этой черте? Где объяснение? Зачем стоят они? Нет. Пропало. Взяли. Понеслись. Это она верно попросила стать на минуту, чтобы еще раз взглянуть на прощание на дом.<br/> Или может быть, ей захотелось удостовериться, не выехал ли уже Юрий Андреевич и не мчится ли за ними вдогонку? Уехали.<br/> Уехали.<br/> Если успеют, если солнце не сядет раньше (в темноте он не разглядит их), они промелькнут еще раз, и на этот раз в последний, по ту сторону оврага, на поляне, где позапрошлою ночью стояли волки».<br/> И вот пришла и прошла и эта минута. Темнопунцовое солнце еще круглилось над синей линией сугробов. Снег жадно всасывал ананасную сладость, которою оно его заливало. И вот они показались, понеслись, промчались. «Прощай, Лара, до свидания на том свете, прощай краса моя, прощай радость моя, бездонная, неисчерпаемая, вечная». И вот они скрылись. «Больше я тебя никогда не увижу, никогда, никогда в жизни, больше никогда не увижу тебя».<br/> Между тем темнело. Стремительно выцветали, гасли разбросанные по снегу багрово-бронзовые пятна зари. Пепельная мягкость пространств быстро погружалась в сиреневые сумерки, все более лиловевшие. С их серою дымкой сливалась кружевная, рукописная тонкость берез на дороге, нежно прорисованных по бледно-розовому, точно вдруг обмелевшему небу.<br/> Душевное горе обострило восприимчивость Юрия Андреевича. Он улавливал всё с удесятеренною резкостью. Окружающее приобретало черты редкой единственности, даже самый воздух.<br/> Небывалым участием дышал зимний вечер, как всему сочувствующий свидетель. Точно еще никогда не смеркалось так до сих пор, а завечерело в первый раз только сегодня, в утешение осиротевшему, впавшему в одиночество человеку. Точно не просто поясною панорамою стояли, спинами к горизонту, окружные леса по буграм, но как бы только что разместились на них, выйдя из-под земли для изъявления сочувствия.<br/> Доктор почти отмахивался от этой ощутимой красоты часа, как от толпы навязывающихся сострадателей, почти готовый шептать лучам дотягивавшейся до него зари: «Спасибо. Не надо».<br/> Он продолжал стоять на крыльце, лицом к затворенной двери, отвернувшись от мира. «Закатилось мое солнце ясное», — повторяло и вытверживало что-то внутри его. У него не было сил выговорить эти слова вслух все подряд, без судорожных горловых схваток, которые прерывали их.<br/> Он вошел в дом. Двойной, двух родов монолог начался и совершался в нем: сухой, мнимо деловой по отношению к себе самому и растекающийся, безбрежный, в обращении к Ларе. Вот как шли его мысли: «Теперь в Москву. И первым делом — выжить.<br/> Не поддаваться бессоннице. Не ложиться спать. Работать ночами до одурения, пока усталость не свалит замертво. И вот еще что.<br/> Сейчас же истопить в спальне, чтобы не мерзнуть ночью без надобности».<br/> Но и вот еще как разговаривал он с собою. «Прелесть моя незабвенная! Пока тебя помнят вгибы локтей моих, пока еще ты на руках и губах моих, я побуду с тобой. Я выплачу слезы о тебе в чем-нибудь достойном, остающемся. Я запишу память о тебе в нежном, нежном, щемяще печальном изображении. Я останусь тут, пока этого не сделаю. А потом и сам уеду. Вот как я изображу тебя. Я положу черты твои на бумагу, как после страшной бури, взрывающей море до основания, ложатся на песок следы сильнейшей, дальше всего доплескивавшейся волны. Ломаной извилистой линией накидывает море пемзу, пробку, ракушки, водоросли, самое легкое и невесомое, что оно могло поднять со дна. Это бесконечно тянущаяся вдаль береговая граница самого высокого прибоя. Так прибило тебя бурей жизни ко мне, гордость моя. Так я изображу тебя».<br/> Он вошел в дом, запер дверь, снял шубу. Когда он вошел в комнату, которую Лара убрала утром так хорошо и старательно и в которой все наново было разворошено спешным отъездом, когда увидал разрытую и неоправленную постель и в беспорядке валявшиеся вещи, раскиданные на полу и на стульях, он, как маленький, опустился на колени перед постелью, всею грудью прижался к твердому краю кровати и, уронив лицо в свесившийся конец перины, заплакал по-детски легко и горько. Это продолжалось недолго. Юрий Андреевич встал, быстро утер слезы, удивленно-рассеянным, устало-отсутствующим взором осмотрелся кругом, достал оставленную Комаровским бутылку, откупорил, налил из нее полстакана, добавил воды, подмешал снегу и с наслаждением, почти равным только что пролитым безутешным слезам, стал пить эту смесь медленными, жадными глотками.

