### 14 {-}

С Юрием Андреевичем творилось что-то несообразное. Он медленно сходил с ума. Никогда еще не вел он такого странного существования. Он запустил дом, перестал заботиться о себе, превращал ночи в дни и потерял счет времени, которое прошло с Лариного отъезда.<br/> Он пил и писал вещи, посвященные ей, но Лара его стихов и записей, по мере вымарок и замены одного слова другим, все дальше уходила от истинного своего первообраза, от живой Катенькиной мамы, вместе с Катей находившейся в путешествии.<br/> Эти вычеркивания Юрий Андреевич производил из соображений точности и силы выражения, но они также отвечали внушениям внутренней сдержанности, не позволявшей обнажать слишком откровенно лично испытанное и невымышленно бывшее, чтобы не ранить и не задевать непосредственных участников написанного и пережитого. Так кровное, дымящееся и неостывшее вытеснялось из стихотворений, и вместо кровоточащего и болезнетворного в них появилась умиротворенная широта, подымавшая частный случай до общности всем знакомого. Он не добивался этой цели, но эта широта сама приходила как утешение, лично посланное ему с дороги едущей, как далекий её привет, как её явление во сне или как прикосновение её руки к его лбу. И он любил на стихах этот облагораживающий отпечаток.<br/> За этим плачем по Ларе он также домарывал до конца свою мазню разных времен о всякой всячине, о природе, об обиходном.<br/> Как всегда с ним бывало и прежде, множество мыслей о жизни личной и жизни общества налетало на него за этой работой одновременно и попутно.<br/> Он снова думал, что историю, то, что называется ходом истории, он представляет себе совсем не так, как принято, и ему она рисуется наподобие жизни растительного царства. Зимою под снегом оголенные прутья лиственного леса тощи и жалки, как волоски на старческой бородавке. Весной в несколько дней лес преображается, подымается до облаков, в его покрытых листьями дебрях можно затеряться, спрятаться. Это превращение достигается движением, по стремительности превосходящим движения животных, потому что животное не растет так быстро, как растение, и которого никогда нельзя подсмотреть. Лес не передвигается, мы не можем его накрыть, подстеречь за переменою места. Мы всегда застаем его в неподвижности. И в такой же неподвижности застигаем мы вечно растущую, вечно меняющуюся, неуследимую в своих превращениях жизнь общества, историю.<br/> Толстой не довел своей мысли до конца, когда отрицал роль зачинателей за Наполеоном, правителями, полководцами. Он думал именно то же самое, но не договорил этого со всею ясностью.<br/> Истории никто не делает, её не видно, как нельзя увидать, как трава растет. Войны, революции, цари, Робеспьеры это её органические возбудители, её бродильные дрожжи. Революции производят люди действенные, односторонние фанатики, гении самоограничения. Они в несколько часов или дней опрокидывают старый порядок. Перевороты длятся недели, много годы, а потом десятилетиями, веками поклоняются духу ограниченности, приведшей к перевороту, как святыне.<br/> За своим плачем по Ларе он оплакивал также то далекое лето в Мелюзееве, когда революция была тогдашним с неба на землю сошедшим богом, богом того лета, и каждый сумасшествовал по-своему, и жизнь каждого существовала сама по себе, а не пояснительно-иллюстративно, в подтверждение правоты высшей политики.<br/> За этим расчерчиванием разных разностей он снова проверил и отметил, что искусство всегда служит красоте, а красота есть счастье обладания формой, форма же есть органический ключ существования, формой должно владеть все живущее, чтобы существовать, и, таким образом, искусство, в том числе и трагическое, есть рассказ о счастье существования. Эти размышления и записи тоже приносили ему счастье, такое трагическое и полное слез, что от него уставала и болела голова.<br/> Приезжал проведать его Анфим Ефимович. Он тоже привез водки и рассказал ему об отбытии Антиповой с дочкой и Комаровским.<br/> Анфим Ефимович приехал на дрезине по железной дороге. Он выбранил доктора за недостаточный уход за лошадью и увел ее, несмотря на просьбу Юрия Андреевича потерпеть еще дня три-четыре. Зато он пообещал самолично заехать за доктором через этот срок и увезти его из Варыкина окончательно.<br/> Иногда записавшись, заработавшись, Юрий Андреевич вдруг вспоминал уехавшую женщину во всей явственности и терял голову от нежности и остроты лишения. Как когда-то в детстве среди великолепия летней природы в пересвисте птиц мерещился ему голос умершей матери, так привыкший к Ларе, сжившийся с её голосом слух теперь иногда обманывал его. «Юрочка», — в слуховой галлюцинации иногда слышалось ему из соседней комнаты.<br/> Бывали с ним случаи и другого обмана чувств за эту неделю.<br/> В конце ее, ночью, он вдруг проснулся после тяжкой привидевшейся ему нелепицы о драконьем логе под домом. Он открыл глаза. Вдруг дно оврага озарилось огнем и огласилось треском и гулом сделанного кем-то выстрела. Удивительно, что спустя минуту после такого необыкновенного происшествия доктор опять уснул, а утром решил, что все это ему приснилось.

