### 15 {-}

Вот что случилось немного позднее в один из тех дней.<br/> Доктор внял, наконец, голосу разума. Он сказал себе, что если поставить себе целью уморить себя во что бы то не стало, можно изыскать способ, скорее действующий и менее мучительный. Он дал себе слово, что как только Анфим Ефимович явится за ним, он немедленно отсюда уедет.<br/> Перед сумерками, когда было еще светло, он услышал громкое хрустение чьих-то шагов по снегу. Кто-то бодрою, решительною походкой спокойно шел к дому.<br/> Странно. Кто бы это мог быть? Анфим Ефимович приехал бы на лошади. Прохожих в пустом Варыкине не водилось. «За мной», — решил Юрий Андреевич. — «Вызов или требование в город. Или чтобы арестовать. Но на чем они повезут меня? И тогда их было бы двое. Это Микулицын, Аверкий Степанович», — обрадовавшись, предположил он, узнав, как ему показалось, гостя по походке.<br/> Человек, пока еще составлявший загадку, на минуту задержался у двери с отбитой задвижкой, не найдя на ней ожидаемого замка, а потом двинулся дальше уверенным шагом, знающим движением, по-хозяйски отворяя встречавшиеся по пути двери и заботливо затворяя их за собою.<br/> Эти странности застали Юрия Андреевича за письменным столом, у которого он сидел спиною ко входу. Пока он поднимался со стула и поворачивался лицом к двери, чтобы встретить чужого, тот уже стоял на пороге, остановившись, как вкопанный.<br/> «Кого вам?» — вырвалось у доктора с бессознательностью, ни к чему не обязывавшей, и когда ответа не последовало, Юрий Андреевич этому не удивлялся.<br/> Вошедший был сильный, статный человек с красивым лицом, в короткой меховой куртке, меховых штанах и теплых козловых сапогах, с висевшей через плечо винтовкой на ремне.<br/> Только миг появления неизвестного был неожиданностью для доктора, а не его приход. Находки в доме и другие признаки подготовили Юрия Андреевича к этой встрече. Вошедший был, очевидно, тем человеком, которому принадлежали попадавшиеся в доме запасы. Его внешность показалась доктору виденной и знакомой. Вероятно посетитель тоже был предупрежден, что дом не пуст. Он недостаточно удивился его обитаемости. Может быть, его предварили, кого он встретит внутри. Может быть, сам он знал доктора.<br/> «Кто это? Кто это?» — мучительно перебирал в памяти Юрий Андреевич. «Господи твоя воля, где я его раз уже видел?<br/> Возможно ли? Жаркое майское утро незапамятно какого года.<br/> Железнодорожная станция Развилье. Не предвещающий добра вагон комиссара. Ясность понятий, прямолинейность, суровость принципов, правота, правота, правота. Стрельников!»

