### 16 {-}

Они разговаривали уже давно, несколько битых часов, как разговаривают одни только русские люди в России, как в особенности разговаривали те устрашенные и тосковавшие, и те бешеные и исступленные, какими были в ней тогда все люди.<br/> Вечерело. Становилось темно.<br/> Помимо беспокойной разговорчивости, которую Стрельников разделял со всеми, он говорил без умолку еще и по какой-то другой, своей причине.<br/> Он не мог наговориться и всеми силами цеплялся за беседу с доктором, чтобы избежать одиночества. Боялся ли он угрызений совести или печальных воспоминаний, преследовавших его, или его томило недовольство собой, в котором человек невыносим и ненавистен себе и готов умереть со стыда? Или у него было принято какое-то страшное, неотменимое решение, с которым ему не хотелось оставаться одному, и исполнение которого он откладывал, насколько возможно, болтовнею с доктором и его обществом?<br/> Так или иначе Стрельников скрывал какую-то важную, тяготившую его тайну, предаваясь во всем остальном тем более расточительным душевным излияниям.<br/> Это была болезнь века, революционное помешательство эпохи.<br/> В помыслах все были другими, чем на словах и во внешних проявлениях. Совесть ни у кого не была чиста. Каждый с основанием мог чувствовать себя во всем виноватым, тайным преступником, неизобличенным обманщиком. Едва являлся повод, разгул самобичующего воображения разыгрывался до последних пределов. Люди фантазировали, наговаривали на себя не только под действием страха, но и вследствие разрушительного болезненного влечения, по доброй воле, в состоянии метафизического транса и той страсти самообсуждения, которой дай только волю, и её не остановишь.<br/> Сколько таких предсмертных показаний, письменных и устных прочел и выслушал в свое время крупный военный, а иногда и военно-судный деятель Стрельников. Теперь сам он был одержим сходным припадком саморазоблачения, всего себя переоценивал, всему подводил итог, все видел в жаровом, изуродованном, бредовом извращении.<br/> Стрельников рассказывал беспорядочно, перескакивая с признания на признание.<br/> — Это было под Читой. Вас поражали диковинки, которыми я набил шкалы и ящики в этом доме? Это все из военных реквизиций, которые мы производили при занятии Красной Армией Восточной Сибири. Разумеется, я не один это на себе перетащил.<br/> Жизнь всегда баловала меня людьми верными, преданными. Эти свечи, спички, кофе, чай, письменные принадлежности и прочее, частью из чешского военного имущества, частью японские и английские. Чудеса в решете, не правда ли? «Не правда ли» было любимое выражение моей жены, вы наверное заметили. Я не знал, сказать ли вам это сразу, а теперь признаюсь. Я пришел повидаться с нею и дочерью. Мне слишком поздно сообщили, будто они тут. И вот опоздал. Когда из сплетен и донесений я узнал о вашей близости с ней и мне в первый раз назвали имя «доктор Живаго», я из тысячи промелькнувших передо мною за эти годы лиц непостижимейшим образом вспомнил как-то раз приведенного ко мне на допрос доктора с такой фамилией.<br/> — И вы пожалели, что не расстреляли его?<br/> Стрельников оставил это замечание без внимания. Может быть, он даже не расслышал, что собеседник прервал его монолог собственною вставкою. Он продолжал рассеянно и задумчиво.<br/> — Конечно, я её ревновал к вам да и теперь ревную. Могло ли быть иначе? В этих местах я прячусь только последние месяцы, когда провалились другие мои явки, далеко на востоке.<br/> Меня должны были привлечь к военному суду по ложному оговору.<br/> Его исход легко было предугадать. Я не знал никакой вины за собой. У меня явилась надежда оправдаться и отстоять свое доброе имя в будущем, при лучших обстоятельствах. Я решил исчезнуть с поля зрения заблаговременно, до ареста и в промежутке скрываться, скитаться, отшельничать. Может я спасся бы в конце концов. Меня подвел втершийся в мое доверие молодой проходимец.<br/> Я уходил через Сибирь зимой пешком на запад, прятался, голодал. Зарывался в сугробы, ночевал в занесенных снегом поездах, которых целые нескончаемые цепи стояли тогда под снегом на Сибирской магистрали.<br/> Скитания столкнули меня с мальчишкой бродягой, будто бы недостреленным партизанами в строю остальных казненных, при общем расстреле. Будто бы он выполз из толпы убитых, отдышался, отлежался и потом стал кочевать по разным логовищам и берлогам, как я. По крайней мере так он рассказывал. Негодяй подросток, порочный, отсталый, из реалистов второгодников, выгнанный из училища по неспособности.<br/> Чем подробнее рассказывал Стрельников, тем ближе доктор узнавал мальчика.<br/> — Имя Терентий, по фамилии Галузин?<br/> — Да.<br/> — Ну тогда все о партизанах и расстреле правда. Он ничего не выдумал.<br/> — Единственная хорошая черта была у мальчика, — обожал мать до безумия. Отец его пропал в заложниках. Он узнал, что мать в тюрьме и разделит участь отца, и решил пойти на все, чтобы освободить ее. В уездной Чрезвычайной комиссии, куда он пришел с повинною и предложением услуг, согласились простить ему все грехи, ценой какой-нибудь крупной выдачи. Он указал место, где я отсиживался. Мне удалось предупредить его предательство и во-время исчезнуть.<br/> Сказочными усилиями, с тысячею приключений я прошел Сибирь и перебрался сюда, в места, где меня знают, как облупленного, и меньше всего ожидали встретить, не предполагая с моей стороны такой дерзости. И действительно, меня долго еще разыскивали под Читою, пока я забирался то в этот домик, то в другие убежища здесь в окрестностях. Но теперь конец. Меня и тут выследили. Послушайте. Смеркается. Приближается час, которого я не люблю, потому что давно уже потерял сон. Вы знаете, какая это мука. Если вы спалили еще не все мои свечи — прекрасные, стеариновые, не правда ли? — давайте поговорим еще чуть-чуть. Давайте проговорим сколько вы будете в состоянии, со всею роскошью, ночь напролет, при горящих свечах.<br/> — Свечи целы. Только одна пачка начата. Я жег найденный здесь керосин.<br/> — Хлеб у вас есть?<br/> — Нет.<br/> — Чем же вы жили? Впрочем, что я глупости спрашиваю.<br/> Картошкою. Знаю.<br/> — Да. Ее тут сколько угодно. Здешние хозяева были опытные и запасливые. Знали, как её засыпать. Вся в сохранности в подвале. Не погнила и не померзла.<br/> Вдруг Стрельников заговорил о революции.

