### 17 {-}

Все это не для вас. Вам этого не понять. Вы росли по-другому. Был мир городских окраин, мир железнодорожных путей и рабочих казарм. Грязь, теснота, нищета, поругание человека в труженике, поругание женщины. Была смеющаяся, безнаказанная наглость разврата, маменькиных сынков, студентов белоподкладочников и купчиков. Шуткою или вспышкой пренебрежительного раздражения отделывались от слез и жалоб обобранных, обиженных, обольщенных. Какое олимпийство тунеядцев, замечательных только тем, что они ничем себя не утрудили, ничего не искали, ничего миру не дали и не оставили!<br/> А мы жизнь приняли, как военный поход, мы камни ворочали ради тех, кого любили. И хотя мы не принесли им ничего, кроме горя, мы волоском их не обидели, потому что оказались еще большими мучениками, чем они.<br/> Однако перед тем как продолжать, считаю долгом сказать вам вот что. Дело в следующем. Вам надо уходить отсюда, не откладывая, если только жизнь дорога вам. Облава на меня стягивается, и чем бы она ни кончилась, вас ко мне припутают, вы уже в мои дела замешаны фактом нашего разговора. Кроме того, тут много волков, я на днях от них отстреливался.<br/> — А, так это вы стреляли?<br/> — Да. Вы, разумеется, слышали? Я шел в другое убежище, но не доходя, по разным признакам понял, что оно раскрыто, и тамошние люди, наверное, погибли. Я у вас недолго пробуду, только переночую, а утром уйду. Итак, с вашего позволения, я продолжаю.<br/> Но разве Тверские-Ямские и мчащиеся с девочками на лихачах франты в заломленных фуражках и брюках со штрипками были только в одной Москве, только в России? Улица, вечерняя улица, вечерняя улица века, рысаки, саврасы, были повсюду. Что объединило эпоху, что сложило девятнадцатое столетие в один исторический раздел? Нарождение социалистической мысли.<br/> Происходили революции, самоотверженные молодые люди всходили на баррикады. Публицисты ломали голову, как обуздать животную беззастенчивость денег и поднять и отстоять человеческое достоинство бедняка. Явился марксизм. Он усмотрел, в чем корень зла, где средство исцеления. Он стал могучей силой века. Все это были Тверские-Ямские века, и грязь, и сияние святости, и разврат, и рабочие кварталы, прокламации и баррикады.<br/> Ах, как хороша она была девочкой, гимназисткой! Вы понятия не имеете. Она часто бывала у своей школьной подруги в доме, заселенном служащими Брестской железной дороги. Так называлась эта дорога вначале, до нескольких последующих переименований.<br/> Мой отец, нынешний член Юрятинского трибунала, служил тогда дорожным мастером на вокзальном участке. Я заходил в тот дом и там её встречал. Она была девочкой, ребенком, а настороженную мысль, тревогу века уже можно было прочесть на её лице, в её глазах. Все темы времени, все его слезы и обиды, все его побуждения, вся его накопленная месть и гордость были написаны на её лице и в её осанке, в смеси её девической стыдливости и её смелой стройности. Обвинение веку можно было вынести от её имени, её устами. Согласитесь, ведь это не безделица. Это некоторое предназначение, отмеченность. Этим надо было обладать от природы, надо было иметь на это право.<br/> — Вы замечательно о ней говорите. Я её видел в то же время, именно такою, как вы её описали. Воспитанница гимназии соединилась в ней с героинею недетской тайны. Ее тень распластывалась по стене движением настороженной самозащиты.<br/> Такою я её видел. Такою помню. Вы это поразительно выразили.<br/> — Видели и помните? А что вы для этого сделали?<br/> — Это совсем другой вопрос.<br/> — Так вот, видите ли, весь этот девятнадцатый век со всеми его революциями в Париже, несколько поколений русской эмиграции, начиная с Герцена, все задуманные цареубийства, неисполненные и приведенные в исполнение, все рабочее движение мира, весь марксизм в парламентах и университетах Европы, всю новую систему идей, новизну и быстроту умозаключений, насмешливость, всю, во имя жалости выработанную вспомогательную безжалостность, все это впитал в себя и обобщенно выразил собою Ленин, чтобы олицетворенным возмездием за все содеянное обрушиться на старое.<br/> Рядом с ним поднялся неизгладимо огромный образ России, на глазах у всего мира вдруг запылавшей свечой искупления за все бездолье и невзгоды человечества. Но к чему я говорю вам это все? Для вас ведь это кимвал бряцающий, пустые звуки.<br/> Ради этой девочки я пошел в университет, ради нее сделался учителем и поехал служить в этот, тогда еще неведомый мне, Юрятин. Я поглотил кучу книг и приобрел уйму знаний, чтобы быть полезным ей и оказаться под рукой, если бы ей потребовалась моя помощь. Я пошел на войну, чтобы после трех лет брака снова завоевать ее, а потом, после войны и возвращения из плена воспользовался тем, что меня считали убитым, и под чужим, вымышленным именем весь ушел в революцию, чтобы полностью отплатить за все, что она выстрадала, чтобы отмыть начисто эти печальные воспоминания, чтобы возврата к прошлому больше не было, чтобы Тверских-Ямских больше не существовало. И они, она и дочь были рядом, были тут! Скольких сил стоило мне подавлять желание броситься к ним, их увидеть!<br/> Но я хотел сначала довести дело своей жизни до конца. О что бы я сейчас отдал, чтобы еще хоть раз взглянуть на них. Когда она входила в комнату, точно окно распахивалось, комната наполнялась светом и воздухом.<br/> — Я знаю, как она была дорога вам. Но простите, имеете ли вы представление, как она вас любила?<br/> — Виноват. Что вы сказали?<br/> — Я говорю, представляете ли вы себе, до какой степени вы были ей дороги, дороже всех на свете?<br/> — Откуда вы это взяли?<br/> — Она сама мне это говорила.<br/> — Она? Вам?<br/> — Да.<br/> — Простите. Я понимаю, это просьба неисполнимая, но, если это допустимо в рамках скромности, если это в ваших силах, восстановите, пожалуйста, по возможности точно, что именно она вам говорила.<br/> — Очень охотно. Она назвала вас образцом человека, равного которому она больше не видела, единственным по высоте неподдельности, и сказала, что если бы на конце земли еще раз замаячило видение дома, который она когда-то с вами делила, она ползком, на коленях, протащилась бы к его порогу откуда угодно, хоть с края света.<br/> — Виноват. Если это не посягательство на что-то для вас неприкосновенное, припомните, когда, при каких обстоятельствах она это сказала?<br/> — Она убирала эту комнату. А потом вышла на воздух вытряхнуть ковер.<br/> — Простите, какой? Тут два.<br/> — Тот, который больше.<br/> — Ей одной такой не под силу. Вы ей помогали?<br/> — Да.<br/> — Вы держались за противоположные концы ковра, она откидывалась, высоко взмахивая руками, как на качелях, и отворачивалась от летевшей пыли, жмурилась и хохотала? Не правда ли? Как я знаю её привычки! А потом вы стали сходиться вместе, складывая тяжелый ковер сначала вдвое, потом вчетверо, и она шутила и выкидывала при этом разные штуки? Не правда ли?<br/> Не правда ли?<br/> Они поднялись со своих мест, отошли к разным окнам, стали смотреть в разные стороны. После некоторого молчания Стрельников подошел к Юрию Андреевичу. Ловя его руки и прижимая их к груди, он продолжал с прежней торопливостью.<br/> — Простите, я понимаю, что затрагиваю нечто дорогое, сокровенное. Но если можно, я еще расспрошу вас. Только не уходите. Не оставляйте меня одного. Я скоро сам уйду.<br/> Подумайте, шесть лет разлуки, шесть лет немыслимой выдержки.<br/> Но мне казалось, — еще не вся свобода завоевана. Вот я её сначала добуду, и тогда я весь принадлежу им, мои руки развязаны. И вот все мои построения пошли прахом. Завтра меня схватят. Вы родной и близкий ей человек. Может быть, вы когда-нибудь её увидите. Но нет, о чем я прошу? Это безумие.<br/> Меня схватят и не дадут оправдываться. Сразу набросятся, окриками и бранью зажимая рот. Мне ли не знать, как это делается?

