### 18 {-}

Наконец-то он выспится по-настоящему. В первый раз за долгое время Юрий Андреевич не заметил, как заснул, едва только растянулся на постели. Стрельников остался ночевать у него. Юрий Андреевич уложил его спать в соседней комнате. В те короткие мгновения, когда Юрий Андреевич просыпался, чтобы перевернуться на другой бок, или подтянуть сползшее на пол одеяло, он чувствовал подкрепляющую силу своего здорового сна и с наслаждением засыпал снова. Во второй половине ночи ему стали являться короткие, быстро сменяющиеся сновидения из времен детства, толковые и богатые подробностями, которые легко было принять за правду.<br/> Так например, висевшая во сне на стене мамина акварель итальянского взморья вдруг оборвалась, упала на пол и звоном разбившегося стекла разбудила Юрия Андреевича. Он открыл глаза. Нет, это что-то другое. Это, наверное, Антипов, муж Лары, Павел Павлович, по фамилии Стрельников, опять, как говорит Вакх, в Шутьме волков пужая. Да нет, что за вздор.<br/> Конечно, картина сорвалась со стены. Вот она в осколках на полу, — удостоверил он в вернувшемся и продолжающемся сновидении.<br/> Он проснулся с головною болью оттого, что спал слишком долго. Он не сразу сообразил, кто он и где, на каком он свете. Вдруг он вспомнил: «Да ведь у меня Стрельников ночует. Уже поздно. Надо одеваться. Он, наверное, уже встал, а, если нет, подыму его, кофе заварю, будем кофе пить».<br/> — Павел Павлович!<br/> Никакого ответа. «Спит еще, значит. Крепко спит, однако».<br/> Юрий Андреевич, не торопясь, оделся и зашел в соседнюю комнату. На столе лежала военная папаха Стрельникова, а самого его в доме не было. «Видно, гуляет», — подумал доктор. «И без шапки. Закаляется. А надо бы сегодня крест на Варыкине поставить и в город. Да поздно. Опять проспал. И так каждое утро».<br/> Юрий Андреевич развел огонь в плите, взял ведро и пошел к колодцу за водою. В нескольких шагах от крыльца, вкось поперек дорожки, упав и уткнувшись головой в сугруб, лежал застрелившийся Павел Павлович. Снег под его левым виском сбился красным комком, вымокши в луже натекшей крови. Мелкие, в сторону брызнувшие капли крови скатались со снегом в красные шарики, похожие на ягоды мерзлой рябины.

