## ЧАСТЬ пятнадцатая. ОКОНЧАНИЕ {-}

### 1 {-}

Остается досказать немногосложную повесть Юрия Андреевича, восемь или девять последних лет его жизни перед смертью, в течение которых он все больше сдавал и опускался, теряя докторские познания и навыки и утрачивая писательские, на короткое время выходил из состояния угнетения и упадка, воодушевлялся, возвращался к деятельности, и потом, после недолгой вспышки, снова впадал в затяжное безучастие к себе самому и ко всему на свете. В эти годы сильно развилась его давняя болезнь сердца, которую он сам у себя установил уже и раньше, но о степени серьезности которой не имел представления.<br/> Он пришел в Москву в начале нэпа, самого двусмысленного и фальшивого из советских периодов. Он исхудал, оброс и одичал еще более, чем во время своего возвращения в Юрятин из партизанского плена. По дороге он опять постепенно снимал с себя все стоящее и выменивал на хлеб с придачею каких-нибудь рваных обносков, чтобы не остаться голым. Так опять проел он в пути свою вторую шубу и пиджачную пару, и на улицах Москвы появился в серой папахе, обмотках и вытертой солдатской шинели, которая превратилась без пуговиц, споротых до одной, в запашной арестантский халат. В этом наряде он ничем не отличался от бесчисленных красноармейцев, толпами наводнивших площади, бульвары и вокзалы столицы.<br/> Он пришел в Москву не один. За ним всюду по пятам следовал красивый крестьянский юноша, тоже одетый во все солдатское, как он сам. В таком виде они появлялись в тех из уцелевших московских гостиных, где протекло детство Юрия Андреевича, где его помнили и принимали вместе с его спутником, предварительно деликатно осведомившись, побывали ли они после дороги в бане, — сыпной тиф еще свирепствовал, — и где Юрию Андреевичу в первые же дни его появления рассказали об обстоятельствах отъезда его близких из Москвы за границу.<br/> Оба дичились людей, но из обостренной застенчивости избегали случаев являться в гости в единственном числе, когда нельзя молчать и надо самим поддерживать беседу. Обыкновенно они двумя долговязыми фигурами вырастали у знакомых, когда у них собиралось общество, забивались куда-нибудь в угол понезаметнее и молча проводили вечер, не участвуя в общем разговоре.<br/> В сопровождении своего молодого товарища худой рослый доктор в неказистой одежде походил на искателя правды из простонародья, а его постоянный провожатый на послушного, слепо ему преданного ученика и последователя. Кто же был этот молодой спутник?

