### 2 {-}

Последнюю часть пути, ближе к Москве, Юрий Андреевич проехал по железной дороге, а первую, гораздо большую, прошел пешком.<br/> Зрелище деревень, через которые он проходил, было ничем не лучше того, что он видел в Сибири и на Урале во время своего бегства из лесного плена. Только тогда он проходил через край зимою, а теперь в конце лета, теплою, сухою осенью, что было гораздо легче.<br/> Половина пройденных им селений была пуста, как после неприятельского похода, поля покинуты и не убраны, да это в самом деле были последствия войны, войны гражданской.<br/> Два или три дня конца сентября его дорога тянулась вдоль обрывистого высокого берега реки. Река, текшая навстречу Юрию Андреевичу, приходилась ему справа. Слева широко, от самой дороги до загроможденной облаками линии небес раскидывались несжатые поля. Их изредка прерывали лиственные леса, с преобладанием дуба, вяза и клена. Леса глубокими оврагами выбегали к реке, и обрывами и крутыми спусками пересекали дорогу.<br/> В неубранных полях рожь держалась в перезревших колосьях, текла и сыпалась из них. Юрий Андреевич пригоршнями набивал зерном рот, с трудом перемалывал его зубами и питался им в тех особо тяжелых случаях, когда не представлялось возможности сварить из хлебных зерен каши. Желудок плохо переваривал сырой, едва прожеванный корм.<br/> Юрий Андреевич никогда в жизни не видал ржи такой зловеще бурой, коричневой, цвета старого потемневшего золота.<br/> Обыкновенно, когда её снимают в срок, она гораздо светлее.<br/> Эти, цвета пламени без огня горевшие, эти, криком о помощи без звука вопиявшие поля холодным спокойствием окаймляло с края большое, уже к зиме повернувшееся небо, по которому, как тени по лицу, безостановочно плыли длинные слоистые снеговые облака с черною середкой и белыми боками.<br/> И все находилось в движении, медленном, равномерном. Текла река. Ей навстречу шла дорога. По ней шагал доктор. В одном направлении с ним тянулись облака. Но и поля не оставались в неподвижности. Что-то двигалось по ним, они были охвачены мелким неугомонным копошением, вызывавшим гадливость.<br/> В невиданном, до тех пор небывалом количестве в полях развелись мыши. Они сновали по лицу и рукам доктора и пробегали сквозь его штанины и рукава, когда ночь застигала его в поле и ему приходилось залечь где-нибудь у межи на ночлег. Их несметно расплодившиеся, отъевшиеся стаи шмыгали днем по дороге под ногами и превращались в скользкую, пискляво шевелящуюся слякоть, когда их давили.<br/> Страшные, одичалые, лохматые деревенские дворняги, которые так переглядывались между собою, точно совещались, когда им наброситься на доктора и загрызть его, брели скопом за доктором на почтительном расстоянии. Они питались падалью, но не гнушались и мышатиной, какою кишело поле, и поглядывая издали на доктора, уверенно двигались за ним, все время чего-то ожидая. Странным образом они в лес не заходили, с приближением к нему мало по малу начинали отставать, сворачивали назад и пропадали.<br/> Лес и поле представляли тогда полную противоположность.<br/> Поля без человека сиротели, как бы преданные в его отсутствие проклятию. Избавившиеся от человека леса красовались на свободе, как выпущенные на волю узники.<br/> Обыкновенно люди, главным образом, деревенские ребятишки, не дают дозреть орехам и обламывают их зелеными. Теперь лесные склоны холмов и оврагов сплошь были покрыты нетронутой шершаво золотистой листвой, как бы запылившейся и погрубевшей от осеннего загара. Из нее торчали изрядно оттопыренные, точно узлами или бантами завязанные, втрое и вчетверо сросшиеся орехи, спелые, готовые вывалиться из гранок, но еще державшиеся в них. Юрий Андреевич без конца грыз и щелкал их по дороге. Карманы были у него ими набиты, котомка полна ими.<br/> В течение недели орехи были его главным питанием.<br/> Доктору казалось, что поля он видит тяжко заболев, в жаровом бреду, а лес — в просветленном состоянии выздоровления, что в лесу обитает Бог, а по полю змеится насмешливая улыбка диавола.

