### 3 {-}

Как раз в эти дни, на этой части пути доктор зашел в сгоревшую до тла, покинутую жителями деревню. В ней до пожара строились только в один ряд, через дорогу от реки. Речная сторона оставалась незастроенной.<br/> В деревне уцелело несколько считанных домов, почернелых и опаленных снаружи. Но и они были пусты, необитаемы. Прочие избы превратились в кучи угольев, из которых торчали кверху черные стояки закопченных печных труб.<br/> Обрывы речной стороны изрыты были ямами, из которых извлекали жерновой камень деревенские жители, жившие в прежнее время его добычей. Три таких недоработанных мельничных круга лежали на земле против последней в ряду деревенской избы, одной из уцелевших. Она тоже пустовала, как все остальные.<br/> Юрий Андреевич зашел в нее. Вечер был тихий, но точно ветер ворвался в избу, едва доктор ступил в нее. По полу во все стороны поехали клочки валявшегося сена и пакли, по стенам закачались лоскутья отставшей бумаги. Все в избе задвигалось, зашуршало. По ней с писком разбегались мыши, которыми, как вся местность кругом, она кишела.<br/> Доктор вышел из избы. Сзади за полями садилось солнце.<br/> Закат затоплял теплом золотого зарева противоположный берег, отдельные кусты и заводи которого дотягивались до середины реки блеском своих блекнущих отражений. Юрий Андреевич перешел через дорогу и присел отдохнуть на один из лежащих в траве жерновов.<br/> Снизу из-за обрыва высунулась светлорусая волосатая голова, потом плечи, потом руки. С реки подымался кто-то по тропинке с полным ведром воды. Человек увидал доктора и остановился, выставившись над линией обрыва до пояса.<br/> — Хошь, напою, добрый человек? Ты меня не замай и я тебя не трону.<br/> — Спасибо. Дай, напьюсь. Да выходи весь, не бойся. Зачем мне тебя трогать?<br/> Вылезший из-под обрыва водонос оказался молодым подростком.<br/> Он был бос, оборван и лохмат.<br/> Несмотря на свои дружелюбные слова, он впился в доктора беспокойным пронизывающим взором. По необъяснимой причине мальчик странно волновался. Он в волнении поставил ведро наземь, и вдруг, бросившись к доктору, остановился на полдороге и забормотал:<br/> — Никак… Никак… Да нет, нельзя тому быть, привиделось.<br/> Извиняюсь, однако, товарищ, дозвольте спросить. Мне помстилось, точно вы знакомый человек будете. Ну да! Ну да!<br/> Дяденька доктор?!<br/> — А ты сам кто?<br/> — Не признали?<br/> — Нет.<br/> — Из Москвы в эшелоне с вами ехали, в одном вагоне. На трудовую гнали. Под конвоем.<br/> Это был Вася Брыкин. Он повалился перед доктором, стал целовать его руки и заплакал.<br/> Погорелое место оказалось Васиной родной деревней Веретенниками. Матери его не было в живых. При расправе с деревнею и пожаре, когда Вася скрывался в подземной пещере из-под вынутого камня, а мать полагала, что Васю увезли в город, она помешалась с горя и утопилась в той самой реке Пелге, над берегом которой сейчас доктор и Вася, беседуя, сидели. Сестры Васи Аленка и Аришка по неточным сведениям находились в другом уезде в детдоме. Доктор взял Васю с собою в Москву. Дорогою он насказал Юрию Андреевичу разных ужасов.

