### 4 {-}

— Это ведь летошней осени озимые сыплются. Только высеялись, и повалили напасти. Когда тетя Поля уехала. Тетю Палашу помните?<br/> — Нет. Да и не знал никогда. Кто такая?<br/> — Как это не знали? Пелагею Ниловну! С нами ехала.<br/> Тягунова. Лицо открытое, полная, белая.<br/> — Это которая всё косы заплетала и расплетала?<br/> — Косы, косы! Ну да! В самую точку. Косы!<br/> — Ах, вспомнил. Погоди. Да ведь я её потом в Сибири встретил, в городе одном, на улице.<br/> — Статочное ли дело! Тетю Палашу?<br/> — Да что с тобой, Вася? Что ты мне руки трясешь, как бешеный. Смотри, не оторви. И вспыхнул, как красная девица.<br/> — Ну как она там? Скорее сказывайте, скорее.<br/> — Да была жива здорова, когда видел. О вас рассказывала.<br/> Точно стояла она у вас или гостила, помнится. А может забыл, путаю.<br/> — Ну как же, ну как же! У нас, у нас! Мамушка её как родную сестру полюбила. Тихая. Работница. Рукодельница. Пока она у нас жила, дом был полная чаша. Сжили её из Веретенников, не дали покоя наговорами.<br/> Мужик Харлам Гнилой был в деревне. Подбивался к Поле.<br/> Безносый ябедник. А она на него и не глядит. Зуб он на меня за это имел. Худое про нас, про меня и Полю сказывал. Ну, и она уехала. Совсем извел. Тут и пошло.<br/> Убийство тут недалеко приключилось одно страшное. Вдову одинокую убили на лесном хуторе поближе к Буйскому. Одна около лесу жила. В мужских ботинках с ушками ходила, на резиновой перетяжке. Злющая собака на цепи кругом хутора бегала по проволоке. По кличке Горлан. С хозяйством, с землей сама справлялась без помощников. Ну вот, вдруг зима, когда никто не ждал. Рано выпал снег. Не выкопала вдова картошки. Приходит она в Веретенники, — помогите, говорит, возьму в долю или заплачу.<br/> Вызвался я ей копать картошку. Прихожу к ней на хутор, а у нее уже Харлам. Напросился раньше меня. Не сказала она мне. Ну да не драться же из-за этого. Вместе взялись за работу. В самую непогодь копали. Дождь и снег, жижа, грязь. Копали, копали, картофельную ботву жгли, теплым дымом сушили картовь.<br/> Ну выкопали, рассчиталась она с нами по совести. Харлама отпустила, а мне эдак глазком, еще мол у меня дело до тебя, зайди потом или останься.<br/> На другой раз пришел я к ней. Не хочу, говорит, изъятие излишков отдавать, картошку в государственную разверстку. Ты, говорит, парень хороший, знаю, не выдашь. Видишь, я от тебя не таюсь. Я бы сама вырыла яму, схоронить, да вишь что на дворе делается. Поздно я хватилась, — зима. Одной не управиться.<br/> Выкопай мне яму, не пожалеешь. Осушим, ссыпем.<br/> Выкопал я ей яму, как тайничку полагается, книзу шире, кувшином, узким горлом вверх. Яму тоже дымом сушили, обогревали. В самую самую метель. Спрятали картошку честь честью, землей забросали. Комар носу не подточит. Я, понятно, про яму молчок. Ни одной живой душе. Мамушке даже или там сестренкам. Ни Боже мой!<br/> Ну так. Только проходит месяц, — ограбление на хуторе.<br/> Рассказывают которые мимо шли из Буйского, дом настежь, весь очищенный, вдовы след простыл, собака Горлан цепь оборвала, убежала.<br/> Еще прошло время. В первую зимнюю оттепель, под новый год, под Васильев вечер ливни шли, смыли снег с бугров, до земли протаял. Прибежал Горлан и сём лапами землю разгребать в проталине, где была картошка в ямке. Раскопал, раскидал верх, а из ямы хозяйкины ноги в башмаках с перетяжками. Видишь, какие страсти!<br/> В Веретенниках все вдову жалели, поминали. На Харлама никто не думал. Да как и думать-то? Мысленное ли дело? Кабы это он, откуда бы у него прыть оставаться в Веретенниках, по деревне гоголем ходить? Ему бы от нас кубарем, наутек куда подальше.<br/> Обрадовались злодейству на хуторе деревенские кулаки заводилы. Давай деревню мутить. Вот, говорят, на что городские изловчаются. Это вам урок, острастка. Не прячь хлеба, картошки не зарывай. А они, дурачье, свое заладили, — лесные разбойники, разбойники им на хуторе привиделись. Простота народ! Вы побольше их, городских слушайтесь. Они вам еще не то покажут, голодом выморят. Желаешь, деревня, добра, за нами иди. Мы научим уму разуму. Придут ваше кровное, потом нажитое отымать, а вы, куда мол, излишки, своей ржи ни зернышка. И в случае чего за вилы. А кто против мира, смотри, берегись.<br/> Разгуделись старики, похвальба, сходки. А Харламу ябеднику только того и надо. Шапку в охапку и в город. И там шу-шу-шу.<br/> Вот что в деревне деется, а вы что сидите смотрите? Надо туда комитет бедноты. Прикажите, я там мигом брата с братом размежую. А сам из наших мест лататы и больше глаз не казал.<br/> Все что дальше случилось, само сделалось. Никто того не подстраивал, никто тому не вина. Наслали красноармейцев из города. И суд выездной. И сразу за меня. Харлам натрезвонил. И за побег, и за уклонение от трудовой, и деревню я к бунту подстрекал, и я вдову убил. И под замок. Спасибо я догадался половицу вынуть, ушел. Под землей в пещере скрывался. Над моей головой деревня горела, — не видал, надо мной мамушка родимая в прорубь бросилась, — не знал. Всё само сделалось.<br/> Красноармейцам отдельную избу отвели, вином поили, перепились вмертвую. Ночью от неосторожного обращения с огнем загорелся дом, от него — соседние. Свои, где занялось, вон попрыгали, а пришлые, никто их не поджигал, те, ясное дело, живьем сгорели до одного. Наших погорелых Веретенниковских никто с пепелищ насиженных не гнал. Сами со страху разбежались, как бы опять чего не вышло. Опять жилы-коноводы наустили, — расстреляют каждого десятого. Уж я никого не застал, всех по миру развеяло, где-нибудь мыкаются.

