### 5 {-}

Доктор с Васею пришли в Москву весной двадцать второго года, в начале нэпа. Стояли теплые ясные дни. Солнечные блики, отраженные золотыми куполами храма Спасителя, падали на мощенную четырехугольным тесаным камнем, по щелям поросшую травою, площадь.<br/> Были сняты запреты с частной предприимчивости, в строгих границах разрешена была свободная торговля. Совершались сделки в пределах товарооборота старьевщиков на толкучем рынке.<br/> Карликовые размеры, в которых они производились, развивали спекуляцию и вели к злоупотреблениям. Мелкая возня дельцов не производила ничего нового, ничего вещественного не прибавляла к городскому запустению. На бесцельной перепродаже десятикратно проданного наживали состояния.<br/> Владельцы нескольких очень скромных домашних библиотек стаскивали книги из своих шкафов куда-нибудь в одно место.<br/> Делали заявку в горсовет о желании открыть кооперативную книжную торговлю. Испрашивали под таковую помещение. Получали в пользование пустовавший с первых месяцев революции обувной склад или оранжерею тогда же закрывшегося цветоводства и под их обширными сводами распродавали свои тощие и случайные книжные собрания.<br/> Дамы профессорши, и раньше в трудное время тайно выпекавшие белые булочки на продажу наперекор запрещению, теперь торговали ими открыто в какой-нибудь простоявшей все эти годы под учетом велосипедной мастерской. Они сменили вехи, приняли революцию и стали говорить «есть такое дело» вместо «да» или «хорошо».<br/> В Москве Юрий Андреевич сказал:<br/> — Надо будет, Вася, чем-нибудь заняться.<br/> — Я так располагаю, учиться.<br/> — Это само собой.<br/> — А еще мечтание. Хочу маманин лик по памяти написать.<br/> — Очень хорошо. Но ведь для этого надо рисовать уметь. Ты когда-нибудь пробовал?<br/> — В Апраксином, когда дядя не видел, углем баловался.<br/> — Ну что же. В добрый час. Попытаемся.<br/> Больших способностей к рисованию у Васи не оказалось, но средних достаточно, чтобы пустить его по прикладной части. По знакомству Юрий Андреевич поместил его на общеобразовательное отделение бывшего Строгановского училища, откуда его перевели на полиграфический факультет. Здесь он обучался литографской технике, типографскому и переплетному мастерству и искусству художественного украшения книги.<br/> Доктор и Вася соединили свои усилия. Доктор писал маленькие книжки в один лист по самым различным вопросам, а Вася их печатал в училище в качестве засчитывавшихся ему экзаменационных работ. Книжки, выпуском в немного экземпляров, распространяли в новооткрытых букинистических магазинах, основанных общими знакомыми.<br/> Книжки содержали философию Юрия Андреевича, изложение его медицинских взглядов, его определения здоровья и нездоровья, мысли о трансформизме и эволюции, о личности, как биологической основе организма, соображения Юрия Андреевича об истории и религии, близкие дядиным и Симушкиным, очерки Пугачевских мест, где побывал доктор, стихи Юрия Андреевича и рассказы.<br/> Работы изложены были доступно, в разговорной форме, далекой, однако, от целей, которые ставят себе популяризаторы, потому что заключали в себе мнения спорные, произвольные, недостаточно проверенные, но всегда живые и оригинальные.<br/> Книжечки расходились. Любители их ценили.<br/> В то время все стало специальностью, стихотворчество, искусство художественного перевода, обо всем писали теоретические исследования, для всего создавали институты.<br/> Возникли разного рода Дворцы мысли, Академии художественных идей. В половине этих дутых учреждений Юрий Андреевич состоял штатным доктором.<br/> Доктор и Вася долгое время дружили и жили вместе. За этот срок они одну за другой сменили множество комнат и полуразрушенных углов, по-разному нежилых и неудобных.<br/> Тотчас по прибытии в Москву Юрий Андреевич наведался в Сивцев, старый дом, в который, как он узнал, его близкие, проездом через Москву, уже больше не заезжали. Их высылка всё изменила. Закрепленные за доктором и его домашними комнаты были заселены, из вещей его собственных и его семьи ничего не оставалось. От Юрия Андреевича шарахались в сторону, как от опасного знакомца.<br/> Маркел пошел в гору и в Сивцевом больше не обретался. Он перевелся комендантом в Мучной городок, где по условиям службы ему с семьей полагалась квартира управляющего. Однако он предпочел жить в старой дворницкой с земляным полом, проведенною водой и огромной русской печью во всё помещение.<br/> Во всех корпусах городка зимой лопались трубы водопровода и отопления, и только в дворницкой было тепло и вода не замерзала.<br/> В это время в отношениях доктора с Васею произошло охлаждение. Вася необычайно развился. Он стал говорить и думать совсем не так, как говорил и думал босой и волосатый мальчик на реке Пелге в Веретенниках. Очевидность, самодоказательность провозглашенных революцией истин всё более привлекала его. Не вполне понятная, образная речь доктора казалась ему голосом не правоты, осужденной, сознающей свою слабость и потому уклончивой.<br/> Доктор ходил по разным ведомствам. Он хлопотал по двум поводам. О политическом оправдании своей семьи и узаконении их возвращения на родину, и о заграничном паспорте для себя и разрешении выехать за женою и детьми в Париж.<br/> Вася удивлялся тому, как холодны и вялы эти хлопоты. Юрий Андреевич слишком поспешно и рано устанавливал неудачу приложенных стараний, слишком уверенно и почти с удовлетворением заявлял о тщетности дальнейших попыток.<br/> Вася всё чаще осуждал доктора. Тот не обижался на его справедливые порицания. Но его отношения с Васей портились.<br/> Наконец они раздружились и разъехались. Доктор оставил Васе комнату, которую сообща с ним занимал, а сам переселился в Мучной городок, где всесильный Маркел выгородил ему конец бывшей квартиры Свентицких. Эту крайнюю долю квартиры составляли: старая бездействовавшая ванная Свентицких, однооконная комната рядом с ней и покосившаяся кухня с полуобвалившимся и давшим осадку черным ходом. Юрий Андреевич сюда перебрался, и после переезда забросил медицину, превратился в неряху, перестал встречаться с знакомыми и стал бедствовать.

