### 6 {-}

Был серый зимний воскресный день. Дым печей подымался не столбами вверх над крышами, а черными струйками курился из оконных форточек, куда, несмотря на запрещение, продолжали выводить железные трубы времянок. Городской быт все еще не налаживался. Жильцы Мучного городка ходили неумытыми замарашками, страдали фурункулезом, зябли, простужались.<br/> По случаю воскресенья семья Маркела Щапова была вся в сборе.<br/> Щаповы обедали за тем самым столом, на котором, во время оно, при нормированной раздаче хлеба по карточкам, по утрам на рассвете, бывало, мелко нарезали ножницами хлебные купоны квартирантов со всего дома, сортировали, подсчитывали, заворачивали в узелки или бумажки по категориям и относили в булочную, а потом, по возвращении из нее, кромсали, кроили, крошили и развешивали хлеб порционно жильцам городка. Теперь всё это отошло в предание. Продовольственную регистрацию сменили другие виды отчетности. За длинным столом ели с аппетитом, так что за ушами трещало, жевали и чавкали.<br/> Половину дворницкой занимала высившаяся посередине широкая русская печь со свисающим с полатей краем стеганого одеяла.<br/> В передней стене у входа торчал над раковиной край действующего водопровода. По бокам дворницкой тянулись лавки с подсунутыми под них пожитками в мешках и сундуках. Левую сторону занимал кухонный стол. Над столом висел прибитый к стене посудный поставец.<br/> Печь топилась. В дворницкой было жарко. Перед печью, засучив рукава до локтя, стояла Маркелова жена Агафья Тихоновна и длинным, глубоко достающим ухватом передвигала горшки в печи то теснее в кучу, то свободнее, смотря по надобности. Потное лицо её попеременно озарялось светом дышавшего печного жара и туманилось паром готовившегося варева. Отодвинув горшки в сторону, она вытащила из глубины пирог на железном листе, одним махом перевернула его верхней корочкой вниз и на минуту задвинула назад подрумяниться. В дворницкую вошел Юрий Андреевич с двумя ведрами.<br/> — Хлеб да соль.<br/> — Просим вашей милости. Садись, гостем будешь.<br/> — Спасибо, — обедал.<br/> — Знаем мы твои обеды. Сел бы да покушал горячего. Что брезгуешь. Картовь печеная в махотке. Пирог с кашей. Пашано.<br/> — Нет, правда, спасибо. Извини, Маркел, что часто хожу, квартиру тебе стужу. Хочу сразу воды побольше напасти.<br/> Отчистил до блеска ванну цинковую у Свентицких, всю наполню, и в баки натаскаю. Еще раз пять, а то и десять загляну сейчас, а потом долго не буду надоедать. Извини, пожалуйста, что хожу.<br/> Кроме тебя не к кому.<br/> — Лей вволю, не жалко. Сыропу нет, а воды, сколько хошь.<br/> Бери задаром. Не торгуем.<br/> За столом захохотали.<br/> Когда Юрий Андреевич зашел в третий раз за пятым и шестым ведром, тон уже несколько изменился и разговор пошел по-другому.<br/> — Зятья спрашивают, кто такой. Говорю, — не верят. Да ты набирай воду, не сумлевайся. Только на пол не лей, ворона.<br/> Видишь, порог заплескал. Наледенеет, не ты ломом скалывать придешь. Да плотней дверь затворяй, раззява, — со двора тянет. Да, сказываю зятьям, кто ты такой есть, не верят.<br/> Сколько на тебя денег извели! Учился, учился, а какой толк?<br/> Когда Юрий Андреевич зашел в пятый или шестой раз, Маркел нахмурился.<br/> — Ну еще раз изволь, а потом баста. Надо, брат, честь знать. Тебе тут Марина заступница, наша меньшая, а то б я не поглядел, какой ты благородный каменщик, и дверь на запор.<br/> Помнишь Марину-то? Вон она, на конце стола, черненькая. Ишь, заалелась. Не забижайте, говорит, его, папаня. А кто тебя трогает. На главном телеграфе телеграфисткою Марина, по иностранному понимает. Он, говорит, несчастный. За тебя хоть в огонь, так тебя жалеет. А нешто я тебе повинен, что ты не выдался. Не надо было в Сибирь драть, дом в опасный час бросать. Сами виноваты. Вон мы всю эту голодуху, всю эту блокату белую высидели, не пошатнулись, и целы. Сам на себя пеняй. Тоньку не сберег, по заграницам бродяжествует. Мне что.<br/> Твое дело. Только не взыщи, спрошу я, куда тебе воды такую прорву? Ты не двор ли нанялся под каток поливать, чтобы обледенел? Эх ты, как и серчать на тебя, курицыно отродье.<br/> Опять за столом захохотали. Марина недовольным взором обвела своих, вспыхнула, что-то стала им выговаривать. Юрий Андреевич услышал её голос, поразился им, но еще не разобрался в его секрете.<br/> — Мытья много в доме, Маркел. Надо убраться. Полы. Хочу кое-что постирать.<br/> За столом стали удивляться.<br/> — И не страм тебе такое говорить, не то что делать, китайская ты прачешная, незнамо что!<br/> — Юрий Андреевич, вы позвольте я к вам дочку пошлю. Она к вам придет, постирает, помоет. Если что надо, худое починит.<br/> Ты их не бойся, доченька. Видишь, другим не в пример, какие они деликатные. Мухи не обидят.<br/> — Нет, что вы, Агафья Тихоновна, не надо. Никогда я не соглашусь, чтобы Марина для меня маралась, пачкалась. Какая она мне чернорабочая? Обойдусь и сам.<br/> — Вам мараться можно, а что же мне? Какой вы несговорчивый, Юрий Андреевич. Зачем отмахиваетесь? А если я к вам в гости напрошусь, неужто выгоните?<br/> Из Марины могла бы выйти певица. У неё был певучий чистый голос большой высоты и силы. Марина говорила негромко, но голосом, который был сильнее разговорных надобностей и не сливался с Мариною, а мыслился отдельно от нее. Казалось, он доносился из другой комнаты и находился за её спиною. Этот голос был её защитой, её ангелом хранителем. Женщину с таким голосом не хотелось оскорбить или опечалить.<br/> С этого воскресного водоношения и завязалась дружба доктора с Мариною. Она часто заходила к нему помочь по хозяйству.<br/> Однажды она осталась у него и не вернулась больше в дворницкую. Так она стала третьей не зарегистрированной в загсе женою Юрия Андреевича, при неразведенной первой. У них пошли дети. Отец и мать Щаповы не без гордости стали звать дочку докторшей. Маркел ворчал, что Юрий Андреевич не венчан с Мариною и что они не расписываются. — Да что ты, очумел? — возражала ему жена. — Это что же при живой Антонине получится? Двоебрачие? — Сама ты дура, — отвечал Маркел. — Что на Тоньку смотреть. Тоньки ровно как бы нету. За нее никакой закон не заступится.<br/> Юрий Андреевич иногда в шутку говорил, что их сближение было романом в двадцати ведрах, как бывают романы в двадцати главах или двадцати письмах.<br/> Марина прощала доктору его странные, к этому времени образовавшиеся причуды, капризы опустившегося и сознающего свое падение человека, грязь и беспорядок, которые он заводил.<br/> Она терпела его брюзжание, резкости, раздражительность.<br/> Ее самопожертвование шло еще дальше. Когда по его вине они впадали в добровольную, им самим созданную нищету, Марина, чтобы не оставлять его в эти промежутки одного, бросала службу, на которой её так ценили, и куда снова охотно принимали после этих вынужденных перерывов. Подчиняясь фантазии Юрия Андреевича, она отправлялась с ним по дворам на заработки. Оба сдельно пилили дрова проживающим в разных этажах квартирантам. Некоторые, в особенности разбогатевшие в начале нэпа спекулянты и стоявшие близко к правительству люди науки и искусства, стали обстраиваться и обзаводиться обстановкой. Однажды Марина с Юрием Андреевичем, осторожно ступая по коврам валенками, чтобы не натащить с улицы опилок, нанашивала запас дров в кабинет квартирохозяину, оскорбительно погруженному в какое-то чтение и не удостаивавшему пильщика и пильщицу даже взглядом. С ними договаривалась, распоряжалась и расплачивалась хозяйка.<br/> «К чему эта свинья так прикована?» — полюбопытствовал доктор. — «Что размечает он карандашом так яростно?» — Обходя с дровами письменный стол, он заглянул вниз из-за плеча читающего. На столе лежали книжечки Юрия Андреевича в Васином раннем Вхутемасовском издании.

