### 8 {-}

Два дня Гордон и Дудоров не отходили от Марины. Они, сменяясь, дежурили при ней, боясь оставить её одну. В промежутке они отправлялись на розыски доктора. Они обегали все места, куда предположительно он мог забрести, побывали в Мучном городке и Сивцевском доме, наведались во все Дворцы Мысли и Дома Идей, где он когда-либо служил, обошли всех старинных его знакомых, о которых они имели хотя бы малейшее понятие и адреса которых можно было найти. Розыски ничего им не дали.<br/> В милицию не заявляли, чтобы не напоминать властям о человеке, хотя и прописанном и не судившемся, но в современном понимании далеко не образцовом. Наводить милицию на его след решили лишь в крайнем случае.<br/> На третий день Марина, Гордон и Дудоров в разные часы получили по письму от Юрия Андреевича. Они были полны сожалений по поводу доставленных им тревог и страхов. Он умолял простить его и успокоиться, и всем, что есть святого, заклинал их прекратить его розыски, которые всё равно ни к чему не приведут.<br/> Он сообщал им, что в целях скорейшей и полной переделки своей судьбы хочет побыть некоторое время в одиночестве, чтобы в сосредоточенности заняться делами, когда же хоть сколько-нибудь укрепится на новом поприще и убедится, что после совершившегося перелома возврата к старому не будет, выйдет из своего тайного убежища и вернется к Марине и детям.<br/> Гордона он предуведомлял в письме, что переводит на его имя деньги для Марины. Он просил нанять к детям няню, чтобы освободить Марину и дать ей возможность вернуться на службу.<br/> Он объяснял, что остерегается направлять деньги непосредственно по её адресу из боязни, как бы выставленная в извещении сумма не подвергла её опасности ограбления.<br/> Скоро пришли деньги, превышавшие и докторов масштаб и мерила его приятелей. Детям наняли няню. Марину опять приняли на телеграф. Она долго не могла успокоиться, но привыкнув к прошлым странностям Юрия Андреевича, примирилась в конце концов и с этою выходкой. Несмотря на просьбы и предупреждения Юрия Андреевича, приятели и эта близкая ему женщина продолжали его разыскивать, убеждаясь в правильности его предсказания.<br/> Они его не находили.

