### 9 {-}

А между тем он жил в нескольких шагах от них, совсем у них под носом и на виду, в теснейшем кругу их поисков.<br/> Когда в день своего исчезновения он засветло, до наступления сумерек вышел от Гордона на Бронную, направляясь к себе домой на Спиридоновку, он тут же, не пройдя и ста шагов по улице, наткнулся на шедшего во встречном направлении сводного брата Евграфа Живаго. Юрий Андреевич не видел его больше трех лет и ничего не знал о нем. Оказалось, Евграф случайно в Москве, куда приехал совсем недавно. По обыкновению он свалился как с неба, и был недоступен расспросам, от которых отделывался молчаливыми улыбочками и шутками. Зато с места в карьер, минуя мелкие бытовые частности, он по двум-трем заданным Юрию Андреевичу вопросам проник во все его печали и неурядицы и тут же, на узких поворотах кривого переулка, в толкотне обгоняющих их и идущих навстречу пешеходов составил практический план, как помочь брату и спасти его. Пропажа Юрия Андреевича и пребывание в скрытности были мыслью Евграфа, его изобретением.<br/> Он снял Юрию Андреевичу комнату в переулке, тогда еще носившем название Камергерского, рядом с Художественным театром. Он снабдил его деньгами, начал хлопотать о приеме доктора на хорошую службу, открывающую простор научной деятельности, куда-нибудь в больницу. Он всячески покровительствовал брату во всех житейских отношениях.<br/> Наконец, он дал брату слово, что с неустойчивым положением его семьи в Париже так или иначе будет покончено. Либо Юрий Андреевич поедет к ним, либо они сами к нему приедут. За все эти дела Евграф обещал взяться сам и всё устроить. Поддержка брата окрыляла Юрия Андреевича. Как всегда бывало и раньше, загадка его могущества оставалась неразъясненною. Юрий Андреевич и не пробовал проникнуть в эту тайну.

### 10 {-}

Комната обращена была на юг. Она двумя окнами выходила на противоположные театру крыши, за которыми сзади, высоко над Охотным, стояло летнее солнце, погружая в тень мостовую переулка.<br/> Комната была более чем рабочею для Юрия Андреевича, более чем его кабинетом. В этот период пожирающей деятельности, когда его планы и замыслы не умещались в записях, наваленных на столе, и образы задуманного и привидевшегося оставались в воздухе по углам, как загромождают мастерскую художника начатые во множестве и лицом к стене повернутые работы, жилая комната доктора была пиршественным залом духа, чуланом безумств, кладовой откровений.<br/> По счастью переговоры с больничным начальством затягивались, срок поступления на службу отодвигался в неопределенное будущее. Можно было писать, воспользовавшись подвернувшеюся отсрочкой.<br/> Юрий Андреевич стал приводить в порядок то из сочиненного, обрывки чего он помнил и что откуда-то добывал и тащил ему Евграф, частью в собственных рукописях Юрия Андреевича, частью в чьих-то чужих перепечатках. Хаотичность материала заставляла Юрия Андреевича разбрасываться еще больше, чем к этому предрасполагала его собственная природа. Он скоро забросил эту работу и от восстановления неоконченного перешел к сочинению нового, увлеченный свежими набросками.<br/> Он составлял начерно очерки статей, вроде беглых записей времен первой побывки в Варыкине, и записывал отдельные куски напрашивавшихся стихотворений, начала, концы и середки, вперемежку без разбора. Иногда он еле справлялся с набегавшими мыслями, начальные буквы слов и сокращения его стремительной скорописи за ними не поспевали.<br/> Он торопился. Когда воображение уставало и работа задерживалась, он подгонял и подхлестывал их рисунками на полях. На них изображались лесные просеки и городские перекрестки со стоящим посередине рекламным столбом «Моро и Ветчинкин. Сеялки. Молотилки».<br/> Статьи и стихотворения были на одну тему. Их предметом был город.

