### 11 {-}

Впоследствии среди его бумаг нашлась запись:<br/> «В двадцать втором году, когда я вернулся в Москву, я нашел её опустевшею, полуразрушенной. Такою она вышла из испытаний первых лет революции, такою осталась и по сей день. Население в ней поредело, новых домов не строят, старых не подновляют.<br/> Но и в таком виде она остается большим современным городом, единственным вдохновителем воистину современного нового искусства.<br/> Беспорядочное перечисление вещей и понятий с виду несовместимых и поставленных рядом как бы произвольно, у символистов, Блока, Верхарна и Уитмана, совсем не стилистическая прихоть. Это новый строй впечатлений, подмеченный в жизни и списанный с натуры.<br/> Так же, как прогоняют они ряды образов по своим строчкам, плывет сама и гонит мимо нас свои толпы, кареты и экипажи деловая городская улица конца девятнадцатого века, а потом, в начале последующего столетия, вагоны своих городских, электрических и подземных железных дорог.<br/> Пастушеской простоте неоткуда взяться в этих условиях. Ее ложная безыскусственность — литературная подделка, неестественное манерничание, явление книжного порядка, занесенное не из деревни, а с библиотечных полок академических книгохранилищ. Живой, живо сложившийся и естественно отвечающий духу нынешнего дня язык — язык урбанизма.<br/> Я живу на людном городском перекрестке. Летняя, ослепляемая солнцем Москва, накаляясь асфальтами дворов, разбрасывая зайчики оконницами верхних помещений и дыша цветением туч и бульваров, вертится вокруг меня и кружит мне голову и хочет, чтобы я во славу ей кружил голову другим. Для этой цели она воспитала меня и отдала мне в руки искусство.<br/> Постоянно, день и ночь шумящая за стеною улица так же тесно связана с современною душою, как начавшаяся увертюра с полным темноты и тайны, еще спущенным, но уже заалевшимся огнями рампы театральным занавесом. Беспрестанно и без умолку шевелящийся и рокочущий за дверьми и окнами город есть необозримо огромное вступление к жизни каждого из нас. Как раз в таких чертах хотел бы я написать о городе».<br/> В сохранившейся стихотворной тетради Живаго не встретилось таких стихотворений. Может быть стихотворение «Гамлет» относилось к этому разряду?

