### 12 {-}

Однажды утром в конце августа Юрий Андреевич с остановки на углу Газетного сел в вагон трамвая, шедший вверх по Никитской, от университета к Кудринской. Он в первый раз направился на службу в Боткинскую больницу, называвшуюся тогда Солдатенковской. Это было чуть ли не первое с его стороны должностное её посещение.<br/> Юрию Андреевичу не повезло. Он попал в неисправный вагон, на который все время сыпались несчастия. То застрявшая колесами в желобах рельсов телега задерживала его, преграждая ему дорогу. То под полом вагона или на крыше портилась изоляция, происходило короткое замыкание и с треском что-то перегорало.<br/> Вагоновожатый часто с гаечными ключами в руках выходил с передней площадки остановившегося вагона и, обойдя его кругом, углублялся, опустившись на корточки, в починку машинных его частей между колесами и задней площадкой.<br/> Злополучный вагон преграждал движение по всей линии. Улицу запружали уже остановленные им трамваи и новые, прибывающие и постепенно накапливающиеся. Их хвост достигал уже Манежа и растягивался дальше. Пассажиры из задних вагонов переходили в передний, по неисправности которого всё это происходило, думая этим переходом что-то выгадать. В это жаркое утро в набитом битком трамвае было тесно и душно. Над толпой перебегающих по мостовой пассажиров от Никитских ворот ползла, всё выше к небу подымавшаяся, черно-лиловая туча. Надвигалась гроза.<br/> Юрий Андреевич сидел на левой одиночной лавочке вагона, совершенно притиснутый к окну. Левый тротуар Никитской, на котором находится Консерватория, был всё время на виду у него.<br/> Волей-неволей, с притупленным вниманием думающего о другом человека, он глазел на идущих и едущих по этой стороне и никого не пропускал.<br/> Старая седая дама в шляпе из светлой соломки с полотняными ромашками и васильками, и сиреневом, туго стягивавшем ее, старомодном платье, отдуваясь и обмахиваясь плоским свертком, который она несла в руке, плелась по этой стороне. Она затянута была в корсет, изнемогала от жары и, обливаясь потом, утирала кружевным платочком мокрые брови и губы.<br/> Ее путь лежал параллельно маршруту трамвая. Юрий Андреевич уже несколько раз терял её из виду, когда починенный трамвай трогался с места и обгонял ее. И она несколько раз возвращалась в поле его зрения, когда новая поломка останавливала трамвай и дама нагоняла его.<br/> Юрию Андреевичу вспомнились школьные задачи на исчисление срока и порядка пущенных в разные часы и идущих с разною скоростью поездов, и он хотел припомнить общий способ их решения, но у него ничего не вышло, и не доведя их до конца, он перескочил с этих воспоминаний на другие, еще более сложные размышления.<br/> Он подумал о нескольких, развивающихся рядом существованиях, движущихся с разною скоростью одно возле другого, и о том, когда чья-нибудь судьба обгоняет в жизни судьбу другого, и кто кого переживает. Нечто вроде принципа относительности на житейском ристалище представилось ему, но окончательно запутавшись, он бросил и эти сближения.<br/> Сверкнула молния, раскатился гром. Несчастный трамвай в который уже раз застрял на спуске от Кудринской к Зоологическому. Дама в лиловом появилась немного спустя в раме окна, миновала трамвай, стала удаляться. Первые крупные капли дождя упали на тротуар и мостовую, на даму. Порыв пыльного ветра проволокся по деревьям, задевая листьями за листья, стал срывать с дамы шляпу и подворачивать ей юбки, и вдруг улегся.<br/> Доктор почувствовал приступ обессиливающей дурноты.<br/> Преодолевая слабость, он поднялся со скамьи и рывками вверх и вниз за ремни оконницы стал пробовать открыть окно вагона. Оно не поддавалось его усилиям.<br/> Доктору кричали, что рама привинчена к косякам наглухо, но, борясь с припадком и охваченный какою-то тревогою, он не относил этих криков к себе и не вникал в них. Он продолжал попытки и снова тремя движениями вверх, вниз и на себя рванул раму и вдруг ощутил небывалую, непоправимую боль внутри, и понял, что сорвал что-то в себе, что он наделал что-то роковое и что всё пропало. В это время вагон пришел в движение, но проехав совсем немного по Пресне, остановился.<br/> Нечеловеческим усилием воли, шатаясь и едва пробиваясь сквозь сгрудившийся затор стоящих в проходе между скамейками, Юрий Андреевич достиг задней площадки. Его не пропускали, на него огрызались. Ему показалось, что приток воздуха освежил его, что, может быть, еще не всё потеряно, что ему стало лучше.<br/> Он стал протискиваться через толпу на задней площадке, вызывая новую ругань, пинки и озлобление. Не обращая внимания на окрики, он прорвался сквозь толчею, ступил со ступеньки стоящего трамвая на мостовую, сделал шаг, другой, третий, рухнул на камни и больше не вставал.<br/> Поднялся шум, говор, споры, советы. Несколько человек сошло вниз с площадки и обступило упавшего. Скоро установили, что он больше не дышит и сердце у него не работает. К кучке вокруг тела подходили с тротуаров, одни успокаиваемые, другие разочаровываемые тем, что это не задавленный и что его смерть не имеет никакого отношения к вагону. Толпа росла. Подошла к группе и дама в лиловом, постояла, посмотрела на мертвого, послушала разговоры и пошла дальше. Она была иностранка, но поняла, что одни советуют внести тело в трамвай и везти дальше в больницу, а другие говорят, что надо кликнуть милицию. Она пошла дальше, не дожидаясь, к какому придут решению.<br/> Дама в лиловом была швейцарская подданная мадемуазель Флери из Мелюзеева, старая-престарая. Она в течение двенадцати лет хлопотала письменно о праве выезда к себе на родину. Совсем недавно ходатайство её увенчалось успехом. Она приехала в Москву за выездною визою. В этот день она шла за её получением к себе в посольство, обмахиваясь завернутыми и перевязанными ленточкой документами. И она пошла вперед, в десятый раз обогнав трамвай и, ничуть того не ведая, обогнала Живаго и пережила его.

