### 13 {-}

Из коридора в дверь был виден угол комнаты с поставленным в него наискось столом. Со стола в дверь грубо выдолбленным челном смотрел нижний суживающийся конец гроба, в который упирались ноги покойника. Это был тот же стол, на котором прежде писал Юрий Андреевич. Другого в комнате не было.<br/> Рукописи убрали в ящик, а стол поставили под гроб. Подушки изголовья были взбиты высоко, тело в гробу лежало как на поднятом кверху возвышении, горою.<br/> Его окружали цветы во множестве, целые кусты редкой в то время белой сирени, цикламены, цинерарии в горшках и корзинах.<br/> Цветы загораживали свет из окон. Свет скупо просачивался сквозь наставленные цветы на восковое лицо и руки покойника, на дерево и обивку гроба. На столе лежал красивый узор теней, как бы только что переставших качаться.<br/> Обычай сжигать умерших в крематории к тому времени широко распространился. В надежде на получение пенсии для детей, в заботе об их школьном будущем и из нежелания вредить положению Марины на службе отказались от церковного отпевания и решили ограничиться гражданскою кремацией. В соответствующие организации было заявлено. Ждали представителей.<br/> В их ожидании в комнате было пусто, как в освобожденном помещении между выездом старых и водворением новых жильцов.<br/> Эту тишину нарушали только чинные шаги на цыпочках и неосторожное шарканье прощающихся. Их было немного, но все же гораздо больше, чем можно было предположить. Весть о смерти человека почти без имени с чудесной скоростью облетела весь их круг. Набралось порядочное число людей, знавших умершего в разную пору его жизни и в разное время им растерянных и забытых. У его научной мысли и музы нашлось еще большее количество неизвестных друзей, никогда не видавших человека, к которому их тянуло, и пришедших впервые посмотреть на него и бросить на него последний прощальный взгляд.<br/> В эти часы, когда общее молчание, не заполненное никакою церемонией, давило почти ощутимым лишением, одни цветы были заменой недостающего пения и отсутствующего обряда.<br/> Они не просто цвели и благоухали, но как бы хором, может быть, ускоряя этим тление, источали свой запах, и, оделяя всех своей душистою силой, как бы что-то совершали.<br/> Царство растений так легко себе представить ближайшим соседом царства смерти. Здесь, в зелени земли, между деревьями кладбищ, среди вышедших из гряд цветочных всходов сосредоточены, может быть, тайны превращения и загадки жизни, над которыми мы бьемся. Вышедшего из гроба Иисуса Мария не узнала в первую минуту и приняла за идущего по погосту садовника. (Она же, мнящи, яко вертоградарь есть…)

