### 15 {-}

Ее всю сотрясали сдерживаемые рыдания. Пока она могла, она им сопротивлялась, но вдруг это становилось выше её сил, слезы прорывались у нее и она обдавала ими щеки, платье, руки и гроб, к которому она прижималась.<br/> Она ничего не говорила, не думала. Ряды мыслей общности, знания, достоверности привольно неслись, гнали через нее, как облака по небу и как во время их прежних ночных разговоров.<br/> Вот это-то, бывало, и приносило счастье и освобожденье.<br/> Неголовное, горячее, друг другу внушаемое знание.<br/> Инстинктивное, непосредственное.<br/> Таким знанием была полна она и сейчас, темным неотчетливым знанием о смерти, подготовленностью к ней, отсутствием растерянности перед ней. Точно она уже двадцать раз жила на свете, без счета теряла Юрия Живаго и накопила целый опыт сердца на этот счет, так что всё, что она чувствовала и делала у этого гроба, было впопад и кстати.<br/> О какая это была любовь, вольная, небывалая, ни на что не похожая! Они думали, как другие напевают.<br/> Они любили друг друга не из неизбежности, не «опаленные страстью», как это ложно изображают. Они любили друг друга потому, что так хотели все кругом: земля под ними, небо над их головами, облака и деревья. Их любовь нравилась окружающим еще, может быть, больше, чем им самим. Незнакомым на улице, выстраивающимся на прогулке далям, комнатам, в которых они селились и встречались.<br/> Ах вот это, это вот ведь, и было главным, что их роднило и объединяло! Никогда, никогда, даже в минуты самого дарственного, беспамятного счастья не покидало их самое высокое и захватывающее: наслаждение общей лепкою мира, чувство отнесенности их самих ко всей картине, ощущение принадлежности к красоте всего зрелища, ко всей вселенной.<br/> Они дышали только этой совместностью. И потому превознесение человека над остальной природой, модное нянчение с ним и человекопоклонство их не привлекали. Начала ложной общественности, превращенной в политику, казались им жалкой домодельщиной и оставались непонятны.

