### 16 {-}

И вот она стала прощаться с ним простыми, обиходными словами бодрого бесцеремонного разговора, разламывающего рамки реальности и не имеющего смысла, как не имеют смысла хоры и монологи трагедий, и стихотворная речь, и музыка и прочие условности, оправдываемые одною только условностью волнения.<br/> Условностью данного случая, оправдывавшего натяжку её легкой, непредвзятой беседы, были её слезы, в которых тонули, купались и плавали её житейские непраздничные слова.<br/> Казалось именно эти мокрые от слез слова сами слипались в её ласковый и быстрый лепет, как шелестит ветер шелковистой и влажной листвой, спутанной теплым дождем.<br/> — Вот и снова мы вместе, Юрочка. Как опять Бог привел свидеться. Какой ужас, подумай! О я не могу! О Господи! Реву и реву! Подумай! Вот опять что-то в нашем роде, из нашего арсенала. Твой уход, мой конец. Опять что-то крупное, неотменимое. Загадка жизни, загадка смерти, прелесть гения, прелесть обнажения, это пожалуйста, это мы понимали. А мелкие мировые дрязги вроде перекройки земного шара, это извините, увольте, это не по нашей части.<br/> Прощай, большой и родной мой, прощай моя гордость, прощай моя быстрая глубокая реченька, как я любила целодневный плеск твой, как я любила бросаться в твои холодные волны.<br/> Помнишь, прощалась я с тобой тогда там, в снегах? Как ты обманул меня! Разве я поехала бы без тебя? О, я знаю, я знаю, ты это сделал через силу, ради моего воображаемого блага. И тогда всё пошло прахом. Господи, что я испила там, что вынесла! Но ведь ты ничего не знаешь. О, что я наделала, Юра, что я наделала! Я такая преступница, ты понятия не имеешь! Но я не виновата. Я тогда три месяца пролежала в больнице, из них один без сознания. С тех пор не житье мне, Юра. Нет душе покоя от жалости и муки. Но ведь я не говорю, не открываю главного.<br/> Назвать это я не могу, не в силах. Когда я дохожу до этого места своей жизни, у меня шевелятся волосы на голове от ужаса.<br/> И даже, знаешь, я не поручусь, что я вполне нормальна. Но видишь, я не пью, как многие, не вступаю на этот путь, потому что пьяная женщина это уже конец, это что-то немыслимое, не правда ли.<br/> И она что-то говорила еще и рыдала и мучилась. Вдруг она удивленно подняла голову и огляделась. В комнате давно были люди, озабоченность, движение. Она спустилась со скамейки и, шатаясь, отошла от гроба, проведя ладонью по глазам и как бы отжимая недоплаканный остаток слез, чтобы рукой стряхнуть их на пол.<br/> К гробу подошли мужчины и подняли его на трех полотенцах.<br/> Начался вынос.

### 17 {-}

Лариса Федоровна провела несколько дней в Камергерском.<br/> Разбор бумаг, о котором была речь с Евграфом Андреевичем, был начат с её участием, но не доведен до конца. Состоялся и её разговор с Евграфом Андреевичем, о котором она его просила. Он узнал от нее что-то важное. Однажды Лариса Федоровна ушла из дому и больше не возвращалась. Видимо, её арестовали в те дни на улице и она умерла или пропала неизвестно где, забытая под каким-нибудь безымянным номером из впоследствии запропастившихся списков, в одном из неисчислимых общих или женских концлагерей севера.

