## ЧАСТЬ шестнадцатая. ЭПИЛОГ {-}

### 1 {-}

Летом тысяча девятьсот сорок третьего года, после прорыва на Курской дуге и освобождения Орла возвращались порознь в свою общую войсковую часть недавно произведенный в младшие лейтенанты Гордон и майор Дудоров, первый из служебной командировки в Москву, а второй оттуда же из трехдневного отпуска.<br/> На обратном пути оба съехались и заночевали в Черни, маленьком городке, хотя и разоренном, но не совершенно уничтоженном, подобно большинству населенных мест этой «зоны пустыни», стертых с лица земли отступавшим неприятелем.<br/> Среди городских развалин, представлявших груды ломаного кирпича и в мелкую пыль истолченного щебня, нашелся неповрежденный сеновал, на котором оба и залегли с вечера.<br/> Им не спалось. Они проговорили всю ночь. На рассвете часа в три задремавшего было Дудорова разбудила копотня Гордона.<br/> Неловкими движениями, как на воде, ныряя и переваливаясь в мягком сене, он собирал в узелок какие-то носильные пожитки, а потом так же косолапо стал сползать с вершины сенной горы к порогу сеновала и выходу.<br/> — Ты куда это снарядился? Рано еще.<br/> — На речку схожу. Хочу кое-что на себе постирать.<br/> — Вот сумасшедший. Вечером будем в части, бельевщица Танька смену выдаст. Зачем нетерплячку подымать.<br/> — Не хочу откладывать. Пропотел, заносился. Утро жаркое.<br/> Наскоро выполощу, хорошо выжму, мигом на солнце высохнет.<br/> Искупаюсь, переоденусь.<br/> — Все-таки знаешь, неудобно. Согласись, офицер ты, как никак.<br/> — Рано. Все спят кругом. Я где-нибудь за кустиком. Никто не увидит. А ты спи, не разговаривай. Сон разгуляешь.<br/> — Я и так больше не усну. Я с тобою пойду.<br/> И они пошли на речку мимо белых, уже успевших накалиться на жарком, только что взошедшем солнце, каменных развалин.<br/> Посреди бывших улиц, на земле, на самом солнцепеке спали потные, храпящие, раскрасневшиеся люди. Это были в большинстве местные, оставшиеся без крова, старики, женщины и дети, редко — отбившиеся и нагоняющие свои подразделения одиночки красноармейцы. Гордон и Дудоров осторожно, все время глядя под ноги, чтобы не наступить на них, ступали между спящими.<br/> — Говори потише, а то разбудим город и тогда прощай моя стирка.<br/> И они вполголоса продолжали свой ночной разговор.

