### 2 {-}

— Что это за река?<br/> — Не знаю. Не спрашивал. Вероятно, Зуша.<br/> — Нет, не Зуша. Какая-то другая.<br/> — Ну тогда не знаю.<br/> — На Зуше-то ведь это все и случилось. С Христиной.<br/> — Да, но в другом месте течения. Где-то ниже. Говорят церковь её к лику святых причла.<br/> — Там было каменное сооружение, получившее имя «Конюшни».<br/> Действительно, совхозная конюшня конского завода, нарицательное название, ставшее историческим. Старинная, толстостенная. Немцы укрепили её и превратили в неприступную крепость. Из нее хорошо простреливалась вся местность, чем задерживалось наше наступление. Конюшню надо было взять.<br/> Христина чудом храбрости и находчивости проникла в немецкое расположение, взорвала конюшню, живою была схвачена и повешена.<br/> — Отчего Христина Орлецова, а не Дудорова?<br/> — Мы ведь еще не были женаты. Летом сорок первого года мы дали друг другу слово пожениться по окончании войны. После этого я кочевал вместе с остальною армией. Мою часть без конца переводили. За этими перемещениями я утерял её из виду. Больше я её не видел. О её доблестном деле и геройской смерти я узнал, как все. Из газет и полковых приказов. Где-то здесь, говорят, думают ей поставить памятник. Брат покойного Юрия, генерал Живаго, я слышал, объезжает эти места и собирает о ней сведения.<br/> — Прости, что я навел тебя на разговор о ней. Для тебя это должно быть тяжело.<br/> — Не в этом дело. Но мы заболтались. Я не хочу мешать тебе. Раздевайся, лезь в воду и займись своим делом. А я растянусь на берегу со стебельком в зубах, пожую — подумаю, может быть, вздремну.<br/> Спустя несколько минут разговор возобновился.<br/> — Где ты так стирать научился?<br/> — Нужда научит. Нам не повезло. Из штрафных лагерей мы попали в самый ужасный. Редкие выживали. Начиная с прибытия.<br/> Партию вывели из вагона. Снежная пустыня. Вдалеке лес. Охрана, опущенные дула винтовок, собаки овчарки. Около того же часа в разное время пригнали другие новые группы. Построили широким многоугольником во все поле, спинами внутрь, чтобы не видали друг друга. Скомандовали на колени и под страхом расстрела не глядеть по сторонам, и началась бесконечная, на долгие часы растянувшаяся, унизительная процедура переклички. И все на коленях. Потом встали, другие партии развели по пунктам, а нашей объявили: «Вот ваш лагерь. Устраивайтесь, как знаете».<br/> Снежное поле под открытым небом, посередине столб, на столбе надпись «Гулаг 92 Я Н 90» и больше ничего.<br/> — Нет, у нас легче было. Нам посчастливилось. Ведь я вторую отсидку отбывал, которую влечет за собой первая. Кроме того, и статья другая, и условия. По освобождении меня снова восстановили, как в первый раз, и сызнова позволили читать в университете. И на войну мобилизовали с полными правами майора, а не штрафным, как тебя.<br/> — Да. Столб с цифрою «Гулаг 92 Я Н 90» и больше ничего.<br/> Первое время в мороз голыми руками жердинник ломали на шалаши.<br/> И что же, не поверишь, постепенно сами обстроились. Нарубили себе темниц, обнеслись частоколами, обзавелись карцерами, сторожевыми вышками, — все сами. И началась лесозаготовка.<br/> Валка леса. Лес валили. Ввосьмером впрягались в сани, на себе возили бревна, по грудь проваливались в снег. Долго не знали, что разразилась война. Скрывали. И вдруг — предложение.<br/> Охотникам штрафными на фронт, и в случае выхода целыми из нескончаемых боев каждому — воля. И затем атаки и атаки, километры колючей проволоки с электрическим током, мины, минометы, месяцы и месяцы ураганного огня. Нас в этих ротах недаром смертниками звали. До одного выкашивало. Как я выжил?<br/> Как я выжил? Однако, вообрази, весь этот кровавый ад был счастьем по сравнению с ужасами концлагеря, и вовсе не вследствие тяжести условий, а совсем по чему-то другому.<br/> — Да, брат, хлебнул ты горя.<br/> — Тут не то что стирать, тут чему хочешь научишься.<br/> — Удивительное дело. Не только перед лицом твоей каторжной доли, но по отношению ко всей предшествующей жизни тридцатых годов, даже на воле, даже в благополучии университетской деятельности, книг, денег, удобств, война явилась очистительной бурею, струей свежего воздуха, веянием избавления.<br/> Я думаю, коллективизация была ложной, неудавшейся мерою, и в ошибке нельзя было признаться. Чтобы скрыть неудачу, надо было всеми средствами устрашения отучить людей судить и думать и принудить их видеть несуществующее и доказывать обратное очевидности. Отсюда беспримерная жестокость ежовщины, обнародование не рассчитанной на применение конституции, введение выборов, не основанных на выборном начале.<br/> И когда разгорелась война, её реальные ужасы, реальная опасность и угроза реальной смерти были благом по сравнению с бесчеловечным владычеством выдумки, и несли облегчение, потому что ограничивали колдовскую силу мертвой буквы.<br/> Люди не только в твоем положении, на каторге, но все решительно, в тылу и на фронте, вздохнули свободнее, всею грудью, и упоенно, с чувством истинного счастья бросились в горнило грозной борьбы, смертельной и спасительной.<br/> — Война — особое звено в цепи революционных десятилетий.<br/> Кончилось действие причин, прямо лежавших в природе переворота. Стали сказываться итоги косвенные, плоды плодов, последствия последствий. Извлеченная из бедствий закалка характеров, неизбалованность, героизм, готовность к крупному, отчаянному, небывалому. Это качества сказочные, ошеломляющие, и они составляют нравственный цвет поколения.<br/> Эти наблюдения преисполняют меня чувством счастья, несмотря на мученическую смерть Христины, на мои ранения, на наши потери, на всю эту дорогую кровавую цену войны. Снести тяжесть смерти Орлецовой помогает мне свет самопожертвования, которым озарен и её конец, и жизнь каждого из нас.<br/> Как раз, когда ты, бедняга, переносил свои неисчислимые пытки, я вышел на свободу. Орлецова в это время поступила на истфак. Род её научных интересов привел её под мое руководство. Я давно уже раньше, после первого заключения в концлагерь, когда она была ребенком, обратил внимание на эту замечательную девушку. Еще при жизни Юрия, помнишь, я рассказывал. Ну вот, теперь, значит, она попала в число моих слушательниц.<br/> Тогда обычай проработки преподавателей учащимися только что вошел в моду. Орлецова с жаром на нее набросилась. Одному Богу известно, за что она меня так яростно разносила. Ее нападки были так упорны, воинственны и несправедливы, что остальные студенты кафедры иногда восставали и за меня вступались.<br/> Орлецова была замечательной юмористкой. Она под вымышленной фамилией, под которой все меня узнавали, высмеивала меня сколько душе угодно в стенгазете. Вдруг по совершенной случайности выяснилось, что эта закоренелая вражда есть форма маскировки молодой любви, прочной, прячущейся и давней. Я всегда отвечал ей тем же.<br/> У нас было чудное лето в сорок первом году, первом году войны, в самый канун её и вскоре после её объявления.<br/> Несколько человек молодежи, студентов и студенток, и она в том числе, поселились в дачной местности под Москвой, где потом расположилась моя часть. Наша дружба завязалась и протекала в обстановке их военного обучения, формирования пригородных отрядов ополчения, парашютной тренировки Христины, ночного отражения первых немецких налетов с московских городских крыш.<br/> Я уже говорил тебе, что тут мы отпраздновали нашу помолвку и вскоре разлучены были моими начавшимися передвижениями. Больше я её не видел.<br/> Когда в наших делах наметился благоприятный перелом и немцы стали сдаваться тысячами, меня после дважды полученного ранения и двукратного пребывания в госпитале перевели из зенитной артиллерии в седьмой отдел штаба, где требовались люди со знанием иностранных языков, куда я настоял чтобы и тебя откомандировали, после того как раздобыл тебя как со дна морского.<br/> — Бельевщица Таня хорошо знала Орлецову. Они сошлись на фронте и были подругами. Она много рассказывает про Христину.<br/> У этой Тани манера улыбаться во все лицо, как была у Юрия, ты заметил? На минуту пропадает курносость, угловатость скул, лицо становится привлекательным, миловидным. Это один и тот же тип, очень у нас распространенный.<br/> — Я знаю, о чем ты говоришь. Пожалуй. Я не обращал внимания.<br/> — Какая варварская, безобразная кличка Танька Безочередева. Это во всяком случае не фамилия, а что-то придуманное, искаженное. Как ты думаешь?<br/> — Так ведь она объясняла. Она из беспризорных, неизвестных родителей. Наверное, где-то в глубине России, где еще чист и нетронут язык, звали её безотчею, в том смысле, что без отца.<br/> Улица, которой было непонятно это прозвище и которая все ловит на слух и все перевирает, переделала на свой лад это обозначение, ближе к своему злободневному площадному наречию.

