### 3 {-}

Это было в разрушенном до основания городе Карачеве, в скором времени после ночевки Гордона и Дудорова в Черни и их тамошнего ночного разговора. Здесь, нагоняя свою армию, приятели застали кое-какие её тылы, следовавшие за главными силами.<br/> Стояла больше месяца не прерывавшаяся ясная и тихая погода жаркой осени. Обданная жаром синего безоблачного неба, черная, плодородная земля Брынщины, благословенного края между Орлом и Брянском, смуглела на солнце шоколадно-кофейным отливом.<br/> Город прорезала главная прямая улица, сливавшаяся с трассой большой дороги. С одной стороны её лежали обрушенные дома, превращенные минами в кучи строительного мусора, и вывороченные, расщепленные и обгорелые деревья сровненных с землею фруктовых садов. По другую сторону, через дорогу, тянулись пустыри, может быть, мало застроенные и раньше, до разгрома города, и более пощаженные пожаром и пороховыми взрывами, потому что здесь нечего было уничтожать.<br/> На прежде застроенной стороне бесприютные жители ковырялись в кучах недогоревшей золы, что-то откапывали и сносили из дальних углов пожарища в одно место. Другие наскоро рыли себе землянки и резали землю пластами для обкладки верхней части жилья дерном.<br/> На противоположной, незастроенной стороне белели палатки и теснились грузовики и конные фургоны всякого рода служб второго эшелона, оторвавшиеся от своих дивизионных штабов полевые госпитали, заблудившиеся, перепугавшиеся и разыскивающие друг друга отделы всевозможных парков, интендантств и провиантских складов. Тут же опрастывались, примащивались подкрепиться, отсыпались и затем плелись дальше на запад тощие худосочные подростки из маршевых рот пополнения, в серых пилотках и тяжелых серых скатках, с испитыми, землистыми, дизентерией обескровленными лицами.<br/> Наполовину обращенный в пепел и взорванный город продолжал гореть и рваться вдали, в местах залегания мин замедленного действия. То и дело копавшиеся в садах прерывали работу, остановленные отраженным сотрясением земли под ногами, распрямляли согнутые спины, опирались на ручки заступов и, повернувши голову в направлении разразившегося взрыва, отдыхали, долго глядя в ту сторону.<br/> Там сперва столбами и фонтанами, а потом ленивыми, отяжелевшими наплывами восходили к небу серые, черные, кирпично-красные и дымно-огненные облака поднятого на воздух мусора, расплывались, раскидывались султанами, рассеивались, оседали назад на землю. И работавшие снова брались за работу.<br/> Одну из полян на незастроенной стороне окаймляли кусты и покрывали сплошной тенью росшие на ней старые деревья. Этой растительностью поляна отгораживалась от остального мира, как стоящий особняком и погруженный в прохладный сумрак крытый двор.<br/> На поляне бельевщица Таня с двумя или тремя однополчанами и несколькими напросившимися попутчиками, а также Гордон и Дудоров дожидались с утра грузовика, — высланного за Танею и порученным ей полковым имуществом. Оно размещено было в нескольких стоявших на поляне и горой наставленных ящиках.<br/> Татьяна стерегла их и ни на шаг от них не отходила, но и другие держались вблизи от ящиков, чтобы не проворонить возможности уехать, когда она представится.<br/> Ожидание длилось давно, больше пяти часов. Ожидающим нечего было делать. Они слушали неумолчную трескотню словоохотливой и видавшей виды девушки. Только что она рассказала о своей встрече с генерал-майором Живаго:<br/> — Как же. Вчерашний день. К генералу меня лично водили. К генерал-майору Живаго. Он тут проездом насчет Христи интересовался, опрашивал. Очных свидетелей, которые в лицо её знали. Показали ему на меня. Говорят, — подружка. Велел вызвать. Ну вызвали, привели. Совсем не страшный. Ничего особенного, как все. Косоглазый, черный. Ну, я что знала, выложила. Выслушал, говорит, спасибо. А сама ты, говорит, откуда и каковская? Я, естественное дело, туда-сюда, отнекиваться. Чем похвалиться? Беспризорная. И вообще. Сами знаете. Исправдомы, бродяжество. А он ни в какую, валяй, говорит, без стеснения, какой тут стыд. Ну, я по робости сперва слово-два, дальше больше, кивает он, я осмелела. А мне есть что порассказать. Кабы вы услышали, не поверили, сказали бы, — выдумывает. Ну, то же вот и он. Как я кончила, он встал, по избе шагает из угла в угол. Скажи, говорит, на милость, какие чудеса. Ну вот что, говорит. Теперь мне некогда. А я тебя найду, не беспокойся, найду и еще раз позову. Просто не думал я, что услышу. Я тебя, говорит, так не оставлю. Тут еще надо будет кое-что выяснить, разные подробности. А то, говорит, чего доброго, я еще в дядья тебе запишусь, произведу тебя в генеральские племянницы. И в обучение отдам в вуз, в какое захочешь. Ей Богу, правда. Такие веселые насмешники.<br/> В это время на поляну въехала длинная порожняя подвода с высокими боками, на каких в Польше и Западной России возят снопы. Парою лошадей в дышельной упряжке правил военнослужащий, по старинной терминологии фурлейт, солдат конного обоза. Он въехал на поляну, соскочил с передка и стал выпрягать лошадей. Все, кроме Татьяны и нескольких солдат, обступили возницу, упрашивая его не распрягать, и повезти их, куда они укажут, конечно, за деньги. Солдат отказывался, потому что не имел права распоряжаться лошадьми и подводой и должен был повиноваться полученным нарядам. Он куда-то увел распряженных лошадей и больше не появлялся. Все сидевшие на земле поднялись и пересели на оставшуюся на поляне пустую подводу. Рассказы Татьяны, прерванные появлением телеги и переговорами с возницею, возобновились.<br/> — Что ты рассказала генералу, — спросил Гордон. — Если можешь, повтори нам.<br/> — Что же, можно.<br/> И она рассказала им свою страшную историю.

