### 5 {-}

Прошло пять или десять лет, и однажды тихим летним вечером сидели они опять, Гордон и Дудоров, где-то высоко у раскрытого окна над необозримою вечернею Москвою. Они перелистывали составленную Евграфом тетрадь Юрьевых писаний, не раз ими читанную, половину которой они знали наизусть. Читавшие перекидывались замечаниями и предавались размышлениям. К середине чтения стемнело, им стало трудно разбирать печать, пришлось зажечь лампу.<br/> И Москва внизу и вдали, родной город автора и половины того, что с ним случилось, Москва казалась им сейчас не местом этих происшествий, но главною героиней длинной повести, к концу которой они подошли с тетрадью в руках в этот вечер.<br/> Хотя просветление и освобождение, которых ждали после войны, не наступили вместе с победою, как думали, но все равно, предвестие свободы носилось в воздухе все послевоенные годы, составляя их единственное историческое содержание.<br/> Состарившимся друзьям у окна казалось, что эта свобода души пришла, что именно в этот вечер будущее расположилось ощутимо внизу на улицах, что сами они вступили в это будущее и отныне в нем находятся. Счастливое, умиленное спокойствие за этот святой город и за всю землю, за доживших до этого вечера участников этой истории и их детей проникало их и охватывало неслышною музыкой счастья, разлившейся далеко кругом. И книжка в их руках как бы знала все это и давала их чувствам поддержку и подтверждение.

